import { Word } from './types';

export const chunk16_raw: Omit<Word, 'id'>[] = [
  { word: "press conference", meaning: "buổi họp báo", example: "Hold a press conference.", exampleVN: "Tổ chức họp báo." },
  { word: "by far", meaning: "hơn hẳn", example: "This is by far the best movie.", exampleVN: "Đây chắc chắn là bộ phim hay nhất." },
  { word: "extraordinary", meaning: "phi thường, đặc biệt", example: "Extraordinary talent.", exampleVN: "Tài năng phi thường." },
  { word: "postpone", meaning: "hoãn lại", example: "The concert was postponed.", exampleVN: "Buổi hòa nhạc đã bị hoãn." },
  { word: "go on sale", meaning: "được mở bán", example: "Tickets go on sale.", exampleVN: "Vé được mở bán." },
  { word: "trade show", meaning: "triển lãm thương mại", example: "The electronics trade show.", exampleVN: "Triển lãm thương mại điện tử." },
  { word: "represent", meaning: "đại diện", example: "Represent our company.", exampleVN: "Đại diện công ty chúng ta." },
  { word: "scout", meaning: "tìm kiếm, thăm dò", example: "Scouting for locations.", exampleVN: "Tìm kiếm các địa điểm." },
  { word: "business card", meaning: "danh thiếp", example: "Have your business cards ready.", exampleVN: "Chuẩn bị sẵn danh thiếp." },
  { word: "award-winning", meaning: "từng đoạt giải thưởng", example: "An award-winning author.", exampleVN: "Một tác giả từng đoạt giải thưởng." },
  { word: "inconvenient", meaning: "bất tiện", example: "The location is inconvenient.", exampleVN: "Địa điểm rất bất tiện." },
  { word: "recreation", meaning: "sự giải trí", example: "Public recreation.", exampleVN: "Giải trí công cộng." },
  { word: "feature", meaning: "khắc họa, đặc điểm chính", example: "Feature a story.", exampleVN: "Khắc họa một câu chuyện." },
  { word: "relocate", meaning: "chuyển địa điểm", example: "Relocate its office.", exampleVN: "Chuyển địa điểm văn phòng." },
  { word: "annual", meaning: "hàng năm", example: "An annual meeting.", exampleVN: "Cuộc họp hàng năm." },
  { word: "committee", meaning: "ủy ban, ban tổ chức", example: "Join the committee.", exampleVN: "Tham gia ban tổ chức." },
  { word: "exhibit", meaning: "khu triển lãm, vật trưng bày", example: "Manufacturing exhibits.", exampleVN: "Khu triển lãm sản xuất." },
  { word: "exposition", meaning: "cuộc triển lãm", example: "Farming exposition.", exampleVN: "Triển lãm nông nghiệp." },
  { word: "nonprofit", meaning: "phi lợi nhuận", example: "A nonprofit organization.", exampleVN: "Một tổ chức phi lợi nhuận." },
  { word: "fertilizer", meaning: "phân bón", example: "Low-cost fertilizer.", exampleVN: "Phân bón giá rẻ." },
  { word: "ongoing", meaning: "đang diễn ra", example: "An ongoing TV drama.", exampleVN: "Bộ phim truyền hình đang phát sóng." },
  { word: "location", meaning: "vị trí, địa điểm", example: "Stop at this location.", exampleVN: "Dừng tại địa điểm này." },
  { word: "promote", meaning: "quảng bá, thăng chức", example: "Promote his movie.", exampleVN: "Quảng bá bộ phim của anh ấy." },
  { word: "behind schedule", meaning: "chậm tiến độ", example: "Behind schedule.", exampleVN: "Bị chậm tiến độ." },
  { word: "auditorium", meaning: "khán phòng", example: "The main auditorium.", exampleVN: "Khán phòng chính." },
  { word: "autograph", meaning: "chữ ký (người nổi tiếng)", example: "Sign autographs.", exampleVN: "Ký tặng." },
  { word: "exceptional", meaning: "xuất sắc/ngoại lệ", example: "Exceptional performance.", exampleVN: "Thành tích xuất sắc." },
  { word: "vendor", meaning: "nhà cung cấp/người bán", example: "Different vendors.", exampleVN: "Nhiều nhà cung cấp khác nhau." },
  { word: "stream", meaning: "phát trực tuyến", example: "Streaming this event.", exampleVN: "Phát trực tuyến sự kiện này." },
  { word: "honoree", meaning: "người được vinh danh", example: "Tonight's honoree.", exampleVN: "Người được vinh danh tối nay." },
  { word: "tirelessly", meaning: "không mệt mỏi", example: "Worked tirelessly.", exampleVN: "Làm việc không mệt mỏi." },
  { word: "label", meaning: "hãng/nhãn hiệu", example: "A music label.", exampleVN: "Hãng thu âm." },
  { word: "retirement", meaning: "sự nghỉ hưu", example: "Celebrate the retirement.", exampleVN: "Kỷ niệm sự nghỉ hưu." },
  { word: "venue", meaning: "địa điểm tổ chức", example: "A popular venue.", exampleVN: "Một địa điểm phổ biến." },
  { word: "mention", meaning: "đề cập, nhắc đến", example: "Did he mention where?", exampleVN: "Anh ấy có nhắc ở đâu không?" },
  { word: "show someone around", meaning: "dẫn ai đó đi tham quan", example: "Show you around.", exampleVN: "Dẫn bạn đi tham quan." },
  { word: "institution", meaning: "tổ chức, học viện", example: "An educational institution.", exampleVN: "Tổ chức giáo dục." },
  { word: "target audience", meaning: "khách hàng mục tiêu", example: "Reach our target audience.", exampleVN: "Tiếp cận khách hàng mục tiêu." },
  { word: "polished", meaning: "bóng loáng, trau chuốt", example: "Polished performance.", exampleVN: "Phần trình bày trau chuốt." },
  { word: "appear on", meaning: "xuất hiện trên", example: "Appear on a talk show.", exampleVN: "Xuất hiện trên chương trình." },
  { word: "entry", meaning: "sự đi vào, vé vào cửa", example: "Entry to the gallery.", exampleVN: "Vé vào cửa phòng triển lãm." },
  { word: "outstanding", meaning: "xuất sắc, nổi bật", example: "Outstanding performance.", exampleVN: "Màn trình diễn xuất sắc." },
  { word: "state-of-the-art", meaning: "hiện đại nhất", example: "State-of-the-art technology.", exampleVN: "Côngnghệ hiện đại nhất." },
  { word: "sold out", meaning: "hết vé, hết hàng", example: "Tickets are sold out.", exampleVN: "Vé đã bán hết." },
  { word: "reception", meaning: "tiệc tiếp đón, lễ tân", example: "A wedding reception.", exampleVN: "Tiệc cưới." },
  { word: "luncheon", meaning: "tiệc trưa trang trọng", example: "A luncheon for clients.", exampleVN: "Tiệc trưa cho khách hàng." },
  { word: "hallway", meaning: "hành lang", example: "In the hallway.", exampleVN: "Trong hành lang." },
  { word: "crate", meaning: "thùng thưa", example: "A crate of bananas.", exampleVN: "Thùng chuối." },
  { word: "be filled with", meaning: "chứa đầy, được làm đầy bởi", example: "The bottle is filled with water.", exampleVN: "Chai chứa đầy nước." },
  { word: "bucket", meaning: "cái xô, thùng", example: "A bucket of water.", exampleVN: "Một xô nước." },
  { word: "lay out", meaning: "bày ra", example: "Lay out her clothes.", exampleVN: "Bày quần áo ra." },
  { word: "window sill", meaning: "bậu cửa sổ", example: "On the window sill.", exampleVN: "Trên bậu cửa sổ." },
  { word: "handle", meaning: "tay cầm, quai xách", example: "The handle is broken.", exampleVN: "Cái quai bị hỏng." },
  { word: "decoration", meaning: "đồ trang trí", example: "Take down decorations.", exampleVN: "Tháo đồ trang trí xuống." },
  { word: "seem", meaning: "có vẻ, dường như", example: "It seems likely.", exampleVN: "Có vẻ như vậy." },
  { word: "pick", meaning: "chọn, nhặt", example: "Don't pick the flowers.", exampleVN: "Đừng hái hoa." },
  { word: "thoughtful", meaning: "chu đáo, ân cần", example: "It was thoughtful of you.", exampleVN: "Bạn thật chu đáo." },
  { word: "dental", meaning: "răng, nha khoa", example: "Dental care.", exampleVN: "Chăm sóc răng miệng." },
  { word: "invitation", meaning: "lời mời", example: "An invitation to the wedding.", exampleVN: "Lời mời đám cưới." },
  { word: "take care of", meaning: "chăm sóc, giải quyết", example: "Take care of the dog.", exampleVN: "Chăm sóc chú chó." },
  { word: "attendee", meaning: "người tham dự", example: "Each attendee will receive a gift.", exampleVN: "Mỗi người tham dự sẽ nhận quà." },
  { word: "give away", meaning: "tặng, cho đi", example: "Give away free samples.", exampleVN: "Tặng các mẫu dùng thử miễn phí." },
  { word: "community", meaning: "cộng đồng", example: "A small community.", exampleVN: "Một cộng đồng nhỏ." },
  { word: "biodegradable", meaning: "có thể phân hủy sinh học", example: "Biodegradable bags.", exampleVN: "Túi có thể phân hủy sinh học." },
  { word: "hand sth out", meaning: "phân phát", example: "Hand out leaflets.", exampleVN: "Phát tờ rơi." },
  { word: "direction", meaning: "hướng, sự chỉ dẫn", example: "Which direction?", exampleVN: "Hướng nào?" },
  { word: "issue", meaning: "vấn đề, ấn bản", example: "Discuss this issue.", exampleVN: "Thảo luận vấn đề này." },
  { word: "double-check", meaning: "kiểm tra lại lần hai", example: "Double-check your keys.", exampleVN: "Kiểm tra lại chìa khóa." },
  { word: "come up", meaning: "nảy sinh, xuất hiện", example: "Something came up.", exampleVN: "Có việc nảy sinh." },
  { word: "similar", meaning: "tương tự", example: "My dress is similar.", exampleVN: "Váy của tôi tương tự." },
  { word: "thermostat", meaning: "bộ điều chỉnh nhiệt", example: "Set the thermostat.", exampleVN: "Cài đặt bộ điều chỉnh nhiệt." },
  { word: "turn on", meaning: "bật", example: "Turn on the light.", exampleVN: "Bật đèn." },
  { word: "randomly", meaning: "một cách ngẫu nhiên", example: "Chosen randomly.", exampleVN: "Được chọn ngẫu nhiên." },
  { word: "take a look", meaning: "xem qua, nhìn qua", example: "Take a look at the photos.", exampleVN: "Xem qua những bức ảnh." },
  { word: "be supposed to", meaning: "được cho là, phải làm gì", example: "You are supposed to be here.", exampleVN: "Bạn đáng lẽ phải ở đây." },
  { word: "inventory", meaning: "hàng tồn kho, sự kiểm kê", example: "Check the inventory.", exampleVN: "Kiểm kê hàng tồn kho." },
  { word: "express", meaning: "bày tỏ / nhanh, hỏa tốc", example: "Express my gratitude.", exampleVN: "Bày tỏ lòng biết ơn." },
  { word: "experienced", meaning: "có kinh nghiệm", example: "An experienced driver.", exampleVN: "Tài xế có kinh nghiệm." },
  { word: "observe", meaning: "quan sát, theo dõi", example: "Observe the experiment.", exampleVN: "Quan sát cuộc thí nghiệm." },
  { word: "capture", meaning: "ghi lại, chụp lại, bắt giữ", example: "Capture a beautiful sunset.", exampleVN: "Ghi lại cảnh hoàng hôn." }
];

export function processChunk16(): Word[] {
  return chunk16_raw.map((w, index) => {
    return {
      ...w,
      id: `c16_${index}`,
      pos: '(n/a)'
    };
  });
}
