import { Word } from './types';

export const chunkHard5: Word[] = [
  { id: 'h401', word: 'rhetoric', meaning: 'hùng biện', example: 'Empty rhetoric.', exampleVN: 'Lời hùng biện rỗng tuếch.' },
  { id: 'h402', word: 'rife', meaning: 'tràn lan', example: 'Corruption is rife.', exampleVN: 'Tham nhũng tràn lan.' },
  { id: 'h403', word: 'rigorous', meaning: 'nghiêm ngặt', example: 'Rigorous testing.', exampleVN: 'Kiểm tra nghiêm ngặt.' },
  { id: 'h404', word: 'robust', meaning: 'mạnh mẽ', example: 'A robust system.', exampleVN: 'Một hệ thống mạnh mẽ.' },
  { id: 'h405', word: 'rogue', meaning: 'người xảo trá, kẻ lưu manh', example: 'A rogue trader.', exampleVN: 'Một nhà giao dịch gian lận.' },
  { id: 'h406', word: 'rudimentary', meaning: 'sơ khai', example: 'Rudimentary knowledge.', exampleVN: 'Kiến thức sơ khai.' },
  { id: 'h407', word: 'rueful', meaning: 'hối tiếc', example: 'A rueful smile.', exampleVN: 'Một nụ cười hối tiếc.' },
  { id: 'h408', word: 'ruminate', meaning: 'ngẫm nghĩ', example: 'Ruminate on a problem.', exampleVN: 'Ngẫm nghĩ về một vấn đề.' },
  { id: 'h409', word: 'rustic', meaning: 'mộc mạc, nông thôn', example: 'Rustic charm.', exampleVN: 'Vẻ quyến rũ mộc mạc.' },
  { id: 'h410', word: 'ruthless', meaning: 'tàn nhẫn', example: 'A ruthless leader.', exampleVN: 'Một lãnh đạo tàn nhẫn.' },
  { id: 'h411', word: 'sacrosanct', meaning: 'bất khả xâm phạm', example: 'Sacrosanct traditions.', exampleVN: 'Những truyền thống bất khả xâm phạm.' },
  { id: 'h412', word: 'sagacious', meaning: 'thông thái, sắc sảo', example: 'A sagacious advisor.', exampleVN: 'Một cố vấn thông thái.' },
  { id: 'h413', word: 'salient', meaning: 'nổi bật', example: 'Salient points.', exampleVN: 'Những điểm nổi bật.' },
  { id: 'h414', word: 'salutary', meaning: 'có lợi', example: 'A salutary lesson.', exampleVN: 'Một bài học có lợi.' },
  { id: 'h415', word: 'sanctimonious', meaning: 'phô trương lòng thành kính, giả nhân giả nghĩa', example: 'Sanctimonious talk.', exampleVN: 'Lời nói giả nhân giả nghĩa.' },
  { id: 'h416', word: 'sanction', meaning: 'phê chuẩn, lệnh trừng phạt', example: 'Economic sanctions.', exampleVN: 'Lệnh trừng phạt kinh tế.' },
  { id: 'h417', word: 'sanguine', meaning: 'lạc quan', example: 'Sanguine about the future.', exampleVN: 'Lạc quan về tương lai.' },
  { id: 'h418', word: 'sardonic', meaning: 'mỉa mai, châm biếm', example: 'A sardonic grin.', exampleVN: 'Một nụ cười mỉa mai.' },
  { id: 'h419', word: 'scanty', meaning: 'ít ỏi, thiếu thốn', example: 'Scanty evidence.', exampleVN: 'Bằng chứng ít ỏi.' },
  { id: 'h420', word: 'scapegoat', meaning: 'kẻ giơ đầu chịu báng', example: 'A political scapegoat.', exampleVN: 'Kẻ giơ đầu chịu báng chính trị.' },
  { id: 'h421', word: 'scathing', meaning: 'gay gắt', example: 'A scathing review.', exampleVN: 'Một bài đánh giá gay gắt.' },
  { id: 'h422', word: 'schism', meaning: 'sự ly khai, chia rẽ', example: 'A schism in the party.', exampleVN: 'Sự chia rẽ trong nội bộ đảng.' },
  { id: 'h423', word: 'scrupulous', meaning: 'tỉ mỉ, thận trọng', example: 'Scrupulous honesty.', exampleVN: 'Sự trung thực tỉ mỉ.' },
  { id: 'h424', word: 'scrutinize', meaning: 'xem xét kỹ lưỡng', example: 'Scrutinize the results.', exampleVN: 'Xem xét kỹ lưỡng kết quả.' },
  { id: 'h425', word: 'secular', meaning: 'thế tục, không tôn giáo', example: 'Secular education.', exampleVN: 'Giáo dục thế tục.' },
  { id: 'h426', word: 'sedentary', meaning: 'ít vận động', example: 'A sedentary lifestyle.', exampleVN: 'Một lối sống ít vận động.' },
  { id: 'h427', word: 'sedition', meaning: 'sự xúi giục nổi loạn', example: 'Charged with sedition.', exampleVN: 'Bị cáo buộc xúi giục nổi loạn.' },
  { id: 'h428', word: 'sensual', meaning: 'thuộc về giác quan, gợi cảm', example: 'Sensual pleasure.', exampleVN: 'Sự khoái lạc về giác quan.' },
  { id: 'h429', word: 'sententious', meaning: 'thích nói đạo lý', example: 'Sententious remarks.', exampleVN: 'Những nhận xét mang tính giáo điều.' },
  { id: 'h430', word: 'sequester', meaning: 'cô lập, tịch thu', example: 'Sequester a jury.', exampleVN: 'Cô lập bồi thẩm đoàn.' },
  { id: 'h431', word: 'serendipity', meaning: 'sự tình cờ may mắn', example: 'By pure serendipity.', exampleVN: 'Do tình cờ may mắn.' },
  { id: 'h432', word: 'servile', meaning: 'khúm núm, nô lệ', example: 'Servile behavior.', exampleVN: 'Hành vi khúm núm.' },
  { id: 'h433', word: 'shrewd', meaning: 'khôn ngoan, sắc sảo', example: 'A shrewd businessman.', exampleVN: 'Một doanh nhân sắc sảo.' },
  { id: 'h434', word: 'singular', meaning: 'độc đáo, kỳ lạ', example: 'A singular achievement.', exampleVN: 'Một thành tựu độc nhất vô nhị.' },
  { id: 'h435', word: 'sinister', meaning: 'nham hiểm, độc ác', example: 'A sinister plot.', exampleVN: 'Một âm mưu nham hiểm.' },
  { id: 'h436', word: 'skeptical', meaning: 'hoài nghi', example: 'Be skeptical about the news.', exampleVN: 'Hãy hoài nghi về tin tức.' },
  { id: 'h437', word: 'slander', meaning: 'vu khống', example: 'Sue for slander.', exampleVN: 'Kiện vì tội vu khống.' },
  { id: 'h438', word: 'sloth', meaning: 'sự lười biếng', example: 'Spiritual sloth.', exampleVN: 'Sự lười biếng về tinh thần.' },
  { id: 'h439', word: 'sluggish', meaning: 'chậm chạp', example: 'A sluggish economy.', exampleVN: 'Một nền kinh tế chậm chạp.' },
  { id: 'h440', word: 'solicit', meaning: 'khẩn khoản, gạ gẫm', example: 'Solicit advice.', exampleVN: 'Khẩn khoản xin lời khuyên.' },
  { id: 'h441', word: 'solicitous', meaning: 'lo lắng, quan tâm', example: 'A solicitous host.', exampleVN: 'Một người chủ nhà chu đáo.' },
  { id: 'h442', word: 'solitude', meaning: 'sự biệt lập, cô độc', example: 'Live in solitude.', exampleVN: 'Sống trong cô độc.' },
  { id: 'h443', word: 'solvent', meaning: 'có khả năng chi trả', example: 'A solvent company.', exampleVN: 'Một công ty có khả năng chi trả.' },
  { id: 'h444', word: 'somber', meaning: 'u ám, ảm đạm', example: 'A somber mood.', exampleVN: 'Một tâm trạng ảm đạm.' },
  { id: 'h445', word: 'sovereign', meaning: 'tối cao, có chủ quyền', example: 'A sovereign state.', exampleVN: 'Một quốc gia có chủ quyền.' },
  { id: 'h446', word: 'sparse', meaning: 'thưa thớt', example: 'Sparse population.', exampleVN: 'Dân cư thưa thớt.' },
  { id: 'h447', word: 'speculate', meaning: 'suy đoán, đầu cơ', example: 'Speculate on the stock market.', exampleVN: 'Đầu cơ trên thị trường chứng khoán.' },
  { id: 'h448', word: 'spurious', meaning: 'giả mạo, sai lệch', example: 'Spurious arguments.', exampleVN: 'Những lập luận sai lệch.' },
  { id: 'h449', word: 'squalid', meaning: 'dơ bẩn, tồi tàn', example: 'Squalid living conditions.', exampleVN: 'Điều kiện sống tồi tàn.' },
  { id: 'h450', word: 'squander', meaning: 'lãng phí', example: 'Squander money.', exampleVN: 'Lãng phí tiền bạc.' },
  { id: 'h451', word: 'stagnant', meaning: 'trì trệ', example: 'A stagnant economy.', exampleVN: 'Một nền kinh tế trì trệ.' },
  { id: 'h452', word: 'staunch', meaning: 'trung thành, vững chắc', example: 'A staunch supporter.', exampleVN: 'Một người ủng hộ trung thành.' },
  { id: 'h453', word: 'steadfast', meaning: 'kiên định', example: 'Steadfast loyalty.', exampleVN: 'Lòng trung thành kiên định.' },
  { id: 'h454', word: 'stigma', meaning: 'sự kỳ thị, vết nhơ', example: 'Social stigma.', exampleVN: 'Sự kỳ thị của xã hội.' },
  { id: 'h455', word: 'stint', meaning: 'phần việc, hạn chế', example: 'A two-year stint.', exampleVN: 'Một nhiệm kỳ hai năm.' },
  { id: 'h456', word: 'stipulate', meaning: 'quy định', example: 'The contract stipulates that...', exampleVN: 'Hợp đồng quy định rằng...' },
  { id: 'h457', word: 'stoic', meaning: 'khắc kỷ', example: 'A stoic acceptance.', exampleVN: 'Một sự chấp nhận khắc kỷ.' },
  { id: 'h458', word: 'strident', meaning: 'chói tai, gay gắt', example: 'A strident voice.', exampleVN: 'Một giọng nói gay gắt.' },
  { id: 'h459', word: 'stringent', meaning: 'nghiêm ngặt', example: 'Stringent regulations.', exampleVN: 'Các quy định nghiêm ngặt.' },
  { id: 'h460', word: 'stymie', meaning: 'cản trở', example: 'The plan was stymied.', exampleVN: 'Kế hoạch đã bị cản trở.' },
  { id: 'h461', word: 'subjugate', meaning: 'chinh phục, khuất phục', example: 'Subjugate a people.', exampleVN: 'Khuất phục một dân tộc.' },
  { id: 'h462', word: 'sublime', meaning: 'cao cả, tuyệt vời', example: 'Sublime beauty.', exampleVN: 'Vẻ đẹp tuyệt vời.' },
  { id: 'h463', word: 'submissive', meaning: 'phục tùng', example: 'A submissive wife.', exampleVN: 'Một người vợ phục tùng.' },
  { id: 'h464', word: 'subsequent', meaning: 'sau đó', example: 'Subsequent events.', exampleVN: 'Các sự kiện sau đó.' },
  { id: 'h465', word: 'subservient', meaning: 'phụ thuộc, khúm núm', example: 'A subservient role.', exampleVN: 'Một vai trò phụ thuộc.' },
  { id: 'h466', word: 'subside', meaning: 'giảm bớt, lắng xuống', example: 'The storm subsided.', exampleVN: 'Cơn bão đã lắng xuống.' },
  { id: 'h467', word: 'subsidiary', meaning: 'công ty con, phụ trợ', example: 'A subsidiary company.', exampleVN: 'Một công ty con.' },
  { id: 'h468', word: 'subsidize', meaning: 'trợ cấp', example: 'Subsidize the industry.', exampleVN: 'Trợ cấp cho ngành công nghiệp.' },
  { id: 'h469', word: 'substantial', meaning: 'đáng kể', example: 'A substantial amount.', exampleVN: 'Một lượng đáng kể.' },
  { id: 'h470', word: 'substantiate', meaning: 'chứng minh', example: 'Substantiate a claim.', exampleVN: 'Chứng minh một tuyên bố.' },
  { id: 'h471', word: 'subtle', meaning: 'tinh tế', example: 'A subtle difference.', exampleVN: 'Một sự khác biệt tinh tế.' },
  { id: 'h472', word: 'subversive', meaning: 'mang tính lật đổ', example: 'Subversive activities.', exampleVN: 'Các hoạt động lật đổ.' },
  { id: 'h473', word: 'succinct', meaning: 'ngắn gọn, súc tích', example: 'A succinct summary.', exampleVN: 'Một bản tóm tắt súc tích.' },
  { id: 'h474', word: 'succumb', meaning: 'đầu hàng, khuất phục', example: 'Succumb to pressure.', exampleVN: 'Đầu hàng trước áp lực.' },
  { id: 'h475', word: 'suffice', meaning: 'đủ để', example: 'A simple answer will suffice.', exampleVN: 'Một câu trả lời đơn giản là đủ rồi.' },
  { id: 'h476', word: 'suffrage', meaning: 'quyền bầu cử', example: 'Universal suffrage.', exampleVN: 'Quyền bầu cử phổ thông.' },
  { id: 'h477', word: 'sullen', meaning: 'ủ rũ, lầm lì', example: 'A sullen expression.', exampleVN: 'Một biểu cảm lầm lì.' },
  { id: 'h478', word: 'sumptuous', meaning: 'xa hoa, sang trọng', example: 'A sumptuous feast.', exampleVN: 'Một bữa tiệc xa hoa.' },
  { id: 'h479', word: 'supercilious', meaning: 'kiêu kỳ, khinh khỉnh', example: 'A supercilious smile.', exampleVN: 'Một nụ cười khinh khỉnh.' },
  { id: 'h480', word: 'superficial', meaning: 'nông cạn, hời hợt', example: 'A superficial wound.', exampleVN: 'Một vết thương ngoài da.' },
  { id: 'h481', word: 'superfluous', meaning: 'dư thừa', example: 'Superfluous details.', exampleVN: 'Các chi tiết thừa.' },
  { id: 'h482', word: 'supplant', meaning: 'thay thế', example: 'Supplant old ideas.', exampleVN: 'Thay thế các ý tưởng cũ.' },
  { id: 'h483', word: 'supple', meaning: 'mềm dẻo', example: 'Supple leather.', exampleVN: 'Da mềm dẻo.' },
  { id: 'h484', word: 'supplicate', meaning: 'khẩn khoản, nài xin', example: 'Supplicate for help.', exampleVN: 'Nài xin sự giúp đỡ.' },
  { id: 'h485', word: 'surfeit', meaning: 'sự thừa mứa', example: 'A surfeit of food.', exampleVN: 'Sự thừa mứa thức ăn.' },
  { id: 'h486', word: 'surly', meaning: 'cáu kỉnh, gắt gỏng', example: 'A surly waiter.', exampleVN: 'Một người bồi bàn gắt gỏng.' },
  { id: 'h487', word: 'surmise', meaning: 'phỏng đoán', example: 'A lucky surmise.', exampleVN: 'Một sự phỏng đoán may mắn.' },
  { id: 'h488', word: 'surmount', meaning: 'vượt qua', example: 'Surmount difficulties.', exampleVN: 'Vượt qua những khó khăn.' },
  { id: 'h489', word: 'surreptitious', meaning: 'lén lút', example: 'A surreptitious glance.', exampleVN: 'Một cái nhìn lén lút.' },
  { id: 'h490', word: 'surrogate', meaning: 'người đại diện, thay thế', example: 'A surrogate mother.', exampleVN: 'Người mẹ mang thai hộ.' },
  { id: 'h491', word: 'susceptible', meaning: 'dễ bị ảnh hưởng', example: 'Susceptible to cold.', exampleVN: 'Dễ bị cảm lạnh.' },
  { id: 'h492', word: 'sustain', meaning: 'duy trì, chịu đựng', example: 'Sustain injuries.', exampleVN: 'Bị thương.' },
  { id: 'h493', word: 'sycophant', meaning: 'kẻ nịnh hót', example: 'A corporate sycophant.', exampleVN: 'Kẻ nịnh hót trong công ty.' },
  { id: 'h494', word: 'symbiotic', meaning: 'cộng sinh', example: 'A symbiotic relationship.', exampleVN: 'Một mối quan hệ cộng sinh.' },
  { id: 'h495', word: 'symmetry', meaning: 'sự đối xứng', example: 'Perfect symmetry.', exampleVN: 'Sự đối xứng hoàn hảo.' },
  { id: 'h496', word: 'synoptic', meaning: 'tóm tắt', example: 'A synoptic chart.', exampleVN: 'Một biểu đồ tóm tắt.' },
  { id: 'h497', word: 'synthesis', meaning: 'sự tổng hợp', example: 'Protein synthesis.', exampleVN: 'Sự tổng hợp protein.' },
  { id: 'h498', word: 'tacit', meaning: 'ngầm hiểu', example: 'Tacit approval.', exampleVN: 'Sự chấp thuận ngầm.' },
  { id: 'h499', word: 'taciturn', meaning: 'lầm lì, ít nói', example: 'A taciturn man.', exampleVN: 'Một người đàn ông ít nói.' },
  { id: 'h500', word: 'tact', meaning: 'sự khéo léo', example: 'Handle with tact.', exampleVN: 'Xử lý một cách khéo léo.' },
];
