import { Word } from './types';

export const chunkHard3: Word[] = [
  { id: 'h201', word: 'vindicate', meaning: 'minh oan', example: 'The evidence vindicated him.', exampleVN: 'Bằng chứng đã minh oan cho anh.' },
  { id: 'h202', word: 'virulent', meaning: 'ác tính', example: 'A virulent strain of the virus.', exampleVN: 'Một chủng virus ác tính.' },
  { id: 'h203', word: 'vocation', meaning: 'nghề nghiệp', example: 'Teaching is his true vocation.', exampleVN: 'Dạy học là nghề đích thực của anh.' },
  { id: 'h204', word: 'voracious', meaning: 'háu ăn, ham mê', example: 'A voracious reader.', exampleVN: 'Một người đọc sách ham mê.' },
  { id: 'h205', word: 'watershed', meaning: 'bước ngoặt', example: 'A watershed moment in history.', exampleVN: 'Một bước ngoặt trong lịch sử.' },
  { id: 'h206', word: 'acrimonious', meaning: 'cay độc', example: 'An acrimonious dispute.', exampleVN: 'Một cuộc tranh chấp cay độc.' },
  { id: 'h207', word: 'admonish', meaning: 'khuyên răn', example: 'The judge admonished the jury.', exampleVN: 'Thẩm phán khuyên răn bồi thẩm đoàn.' },
  { id: 'h208', word: 'affable', meaning: 'hòa nhã', example: 'An affable manager.', exampleVN: 'Một quản lý hòa nhã.' },
  { id: 'h209', word: 'alacrity', meaning: 'sự hăm hở', example: 'She accepted with alacrity.', exampleVN: 'Cô ấy chấp nhận với sự hăm hở.' },
  { id: 'h210', word: 'amalgamate', meaning: 'hợp nhất', example: 'Amalgamate the two departments.', exampleVN: 'Hợp nhất hai phòng ban.' },
  { id: 'h211', word: 'ambivalent', meaning: 'lưỡng lự', example: 'Ambivalent about the new policy.', exampleVN: 'Lưỡng lự về chính sách mới.' },
  { id: 'h212', word: 'antipathy', meaning: 'ác cảm', example: 'A deep antipathy toward corruption.', exampleVN: 'Sự ác cảm sâu sắc đối với tham nhũng.' },
  { id: 'h213', word: 'apathy', meaning: 'sự thờ ơ', example: 'Voter apathy is increasing.', exampleVN: 'Sự thờ ơ của cử tri đang tăng.' },
  { id: 'h214', word: 'appease', meaning: 'xoa dịu', example: 'Appease the angry customers.', exampleVN: 'Xoa dịu khách hàng tức giận.' },
  { id: 'h215', word: 'arbitrary', meaning: 'tùy tiện', example: 'An arbitrary decision.', exampleVN: 'Một quyết định tùy tiện.' },
  { id: 'h216', word: 'arduous', meaning: 'gian khổ', example: 'An arduous journey.', exampleVN: 'Một hành trình gian khổ.' },
  { id: 'h217', word: 'ascertain', meaning: 'xác định', example: 'Ascertain the cause of the problem.', exampleVN: 'Xác định nguyên nhân vấn đề.' },
  { id: 'h218', word: 'astute', meaning: 'sắc sảo', example: 'An astute businessman.', exampleVN: 'Một doanh nhân sắc sảo.' },
  { id: 'h219', word: 'attrition', meaning: 'sự hao mòn', example: 'Staff attrition rate is high.', exampleVN: 'Tỷ lệ hao mòn nhân viên cao.' },
  { id: 'h220', word: 'austere', meaning: 'khắc khổ', example: 'An austere budget.', exampleVN: 'Một ngân sách khắc khổ.' },
  { id: 'h221', word: 'banal', meaning: 'tầm thường', example: 'A banal marketing slogan.', exampleVN: 'Một khẩu hiệu tiếp thị tầm thường.' },
  { id: 'h222', word: 'bilateral', meaning: 'song phương', example: 'A bilateral trade agreement.', exampleVN: 'Một thỏa thuận thương mại song phương.' },
  { id: 'h223', word: 'blatant', meaning: 'trắng trợn', example: 'A blatant lie.', exampleVN: 'Một lời nói dối trắng trợn.' },
  { id: 'h224', word: 'brevity', meaning: 'sự ngắn gọn', example: 'Brevity is the soul of wit.', exampleVN: 'Ngắn gọn là tinh hoa của trí tuệ.' },
  { id: 'h225', word: 'bureaucracy', meaning: 'bộ máy quan liêu', example: 'Too much bureaucracy slows progress.', exampleVN: 'Quá nhiều quan liêu làm chậm tiến độ.' },
  { id: 'h226', word: 'candid', meaning: 'thẳng thắn', example: 'A candid assessment.', exampleVN: 'Một đánh giá thẳng thắn.' },
  { id: 'h227', word: 'capricious', meaning: 'thất thường', example: 'Capricious consumer demands.', exampleVN: 'Nhu cầu tiêu dùng thất thường.' },
  { id: 'h228', word: 'censure', meaning: 'chỉ trích', example: 'The board censured the CEO.', exampleVN: 'Hội đồng chỉ trích CEO.' },
  { id: 'h229', word: 'circumspect', meaning: 'thận trọng', example: 'Be circumspect in negotiations.', exampleVN: 'Hãy thận trọng trong đàm phán.' },
  { id: 'h230', word: 'clandestine', meaning: 'bí mật', example: 'A clandestine meeting.', exampleVN: 'Một cuộc họp bí mật.' },
  { id: 'h231', word: 'coerce', meaning: 'ép buộc', example: 'Coerce employees into overtime.', exampleVN: 'Ép buộc nhân viên làm thêm giờ.' },
  { id: 'h232', word: 'cogent', meaning: 'có sức thuyết phục', example: 'A cogent argument.', exampleVN: 'Một lập luận thuyết phục.' },
  { id: 'h233', word: 'commensurate', meaning: 'tương xứng', example: 'Salary commensurate with experience.', exampleVN: 'Lương tương xứng với kinh nghiệm.' },
  { id: 'h234', word: 'compelling', meaning: 'hấp dẫn, thuyết phục', example: 'A compelling business case.', exampleVN: 'Một trường hợp kinh doanh thuyết phục.' },
  { id: 'h235', word: 'conciliatory', meaning: 'hòa giải', example: 'A conciliatory tone.', exampleVN: 'Một giọng điệu hòa giải.' },
  { id: 'h236', word: 'condone', meaning: 'bỏ qua, tha thứ', example: 'We cannot condone such behavior.', exampleVN: 'Chúng tôi không thể bỏ qua hành vi đó.' },
  { id: 'h237', word: 'conscientious', meaning: 'tận tâm', example: 'A conscientious worker.', exampleVN: 'Một người làm việc tận tâm.' },
  { id: 'h238', word: 'contentious', meaning: 'gây tranh cãi', example: 'A contentious issue.', exampleVN: 'Một vấn đề gây tranh cãi.' },
  { id: 'h239', word: 'convoluted', meaning: 'phức tạp, rối rắm', example: 'A convoluted tax system.', exampleVN: 'Một hệ thống thuế rối rắm.' },
  { id: 'h240', word: 'copious', meaning: 'phong phú', example: 'Copious notes from the meeting.', exampleVN: 'Ghi chú phong phú từ cuộc họp.' },
  { id: 'h241', word: 'culpable', meaning: 'đáng trách', example: 'The manager was culpable.', exampleVN: 'Người quản lý đáng bị trách.' },
  { id: 'h242', word: 'cursory', meaning: 'qua loa', example: 'A cursory glance at the data.', exampleVN: 'Một cái nhìn qua loa vào dữ liệu.' },
  { id: 'h243', word: 'daunting', meaning: 'đáng sợ', example: 'A daunting task ahead.', exampleVN: 'Một nhiệm vụ đáng sợ phía trước.' },
  { id: 'h244', word: 'debunk', meaning: 'vạch trần', example: 'Debunk the myth.', exampleVN: 'Vạch trần huyền thoại.' },
  { id: 'h245', word: 'defunct', meaning: 'không còn tồn tại', example: 'A defunct company.', exampleVN: 'Một công ty đã giải thể.' },
  { id: 'h246', word: 'deplete', meaning: 'cạn kiệt', example: 'Deplete natural resources.', exampleVN: 'Cạn kiệt tài nguyên thiên nhiên.' },
  { id: 'h247', word: 'deploy', meaning: 'triển khai', example: 'Deploy resources effectively.', exampleVN: 'Triển khai nguồn lực hiệu quả.' },
  { id: 'h248', word: 'deviate', meaning: 'đi chệch', example: 'Deviate from the plan.', exampleVN: 'Đi chệch khỏi kế hoạch.' },
  { id: 'h249', word: 'discern', meaning: 'nhận ra', example: 'Discern patterns in the data.', exampleVN: 'Nhận ra mẫu hình trong dữ liệu.' },
  { id: 'h250', word: 'disclose', meaning: 'tiết lộ', example: 'Disclose financial information.', exampleVN: 'Tiết lộ thông tin tài chính.' },
  { id: 'h251', word: 'discord', meaning: 'bất hòa', example: 'Discord among team members.', exampleVN: 'Bất hòa giữa các thành viên nhóm.' },
  { id: 'h252', word: 'discreet', meaning: 'kín đáo', example: 'Be discreet about the merger.', exampleVN: 'Hãy kín đáo về vụ sáp nhập.' },
  { id: 'h253', word: 'disparate', meaning: 'khác biệt', example: 'Disparate views on the issue.', exampleVN: 'Quan điểm khác biệt về vấn đề.' },
  { id: 'h254', word: 'dissipate', meaning: 'tiêu tan', example: 'The tension began to dissipate.', exampleVN: 'Căng thẳng bắt đầu tiêu tan.' },
  { id: 'h255', word: 'divisive', meaning: 'gây chia rẽ', example: 'A divisive policy.', exampleVN: 'Một chính sách gây chia rẽ.' },
  { id: 'h256', word: 'dogmatic', meaning: 'giáo điều', example: 'A dogmatic approach.', exampleVN: 'Một cách tiếp cận giáo điều.' },
  { id: 'h257', word: 'dormant', meaning: 'ngưng hoạt động', example: 'A dormant account.', exampleVN: 'Một tài khoản ngưng hoạt động.' },
  { id: 'h258', word: 'draconian', meaning: 'hà khắc', example: 'Draconian measures.', exampleVN: 'Các biện pháp hà khắc.' },
  { id: 'h259', word: 'dubious', meaning: 'đáng ngờ', example: 'A dubious claim.', exampleVN: 'Một tuyên bố đáng ngờ.' },
  { id: 'h260', word: 'eclectic', meaning: 'chiết trung', example: 'An eclectic mix of ideas.', exampleVN: 'Sự pha trộn chiết trung các ý tưởng.' },
  { id: 'h261', word: 'elaborate', meaning: 'công phu, chi tiết', example: 'An elaborate plan.', exampleVN: 'Một kế hoạch công phu.' },
  { id: 'h262', word: 'elusive', meaning: 'khó nắm bắt', example: 'An elusive target.', exampleVN: 'Một mục tiêu khó nắm bắt.' },
  { id: 'h263', word: 'embezzle', meaning: 'biển thủ', example: 'Embezzle company funds.', exampleVN: 'Biển thủ quỹ công ty.' },
  { id: 'h264', word: 'eminent', meaning: 'nổi tiếng, lỗi lạc', example: 'An eminent economist.', exampleVN: 'Một nhà kinh tế lỗi lạc.' },
  { id: 'h265', word: 'empirical', meaning: 'thực nghiệm', example: 'Empirical evidence supports the claim.', exampleVN: 'Bằng chứng thực nghiệm ủng hộ tuyên bố.' },
  { id: 'h266', word: 'endemic', meaning: 'đặc hữu, phổ biến', example: 'Corruption is endemic in this industry.', exampleVN: 'Tham nhũng phổ biến trong ngành này.' },
  { id: 'h267', word: 'engender', meaning: 'gây ra, sinh ra', example: 'Trust engenders loyalty.', exampleVN: 'Niềm tin sinh ra lòng trung thành.' },
  { id: 'h268', word: 'enmity', meaning: 'sự thù địch', example: 'Enmity between rival firms.', exampleVN: 'Sự thù địch giữa các công ty đối thủ.' },
  { id: 'h269', word: 'entrepreneur', meaning: 'doanh nhân', example: 'A successful entrepreneur.', exampleVN: 'Một doanh nhân thành đạt.' },
  { id: 'h270', word: 'epitome', meaning: 'hình mẫu, tiêu biểu', example: 'He is the epitome of success.', exampleVN: 'Anh ấy là hình mẫu của thành công.' },
  { id: 'h271', word: 'erratic', meaning: 'thất thường', example: 'Erratic market behavior.', exampleVN: 'Hành vi thị trường thất thường.' },
  { id: 'h272', word: 'exorbitant', meaning: 'quá đắt', example: 'Exorbitant prices.', exampleVN: 'Giá cả quá đắt.' },
  { id: 'h273', word: 'explicit', meaning: 'rõ ràng, minh bạch', example: 'Explicit instructions.', exampleVN: 'Hướng dẫn rõ ràng.' },
  { id: 'h274', word: 'extravagant', meaning: 'xa xỉ, hoang phí', example: 'Extravagant spending habits.', exampleVN: 'Thói quen chi tiêu hoang phí.' },
  { id: 'h275', word: 'fabricate', meaning: 'bịa đặt, chế tạo', example: 'Fabricate false evidence.', exampleVN: 'Bịa đặt bằng chứng giả.' },
  { id: 'h276', word: 'fathom', meaning: 'hiểu thấu', example: 'I cannot fathom his decision.', exampleVN: 'Tôi không hiểu nổi quyết định của anh.' },
  { id: 'h277', word: 'fervent', meaning: 'nhiệt thành', example: 'A fervent supporter.', exampleVN: 'Một người ủng hộ nhiệt thành.' },
  { id: 'h278', word: 'fidelity', meaning: 'sự trung thành', example: 'Brand fidelity among customers.', exampleVN: 'Sự trung thành thương hiệu của khách hàng.' },
  { id: 'h279', word: 'fiasco', meaning: 'sự thất bại ê chề', example: 'The project was a fiasco.', exampleVN: 'Dự án là một thất bại ê chề.' },
  { id: 'h280', word: 'foreclose', meaning: 'tịch thu tài sản thế chấp', example: 'The bank foreclosed on the property.', exampleVN: 'Ngân hàng tịch thu tài sản thế chấp.' },
  { id: 'h281', word: 'formidable', meaning: 'đáng gờm', example: 'A formidable competitor.', exampleVN: 'Một đối thủ đáng gờm.' },
  { id: 'h282', word: 'forthcoming', meaning: 'sắp tới, cởi mở', example: 'Forthcoming changes to the policy.', exampleVN: 'Những thay đổi sắp tới của chính sách.' },
  { id: 'h283', word: 'fortuitous', meaning: 'tình cờ, may mắn', example: 'A fortuitous meeting.', exampleVN: 'Một cuộc gặp tình cờ.' },
  { id: 'h284', word: 'foster', meaning: 'nuôi dưỡng, thúc đẩy', example: 'Foster innovation in the workplace.', exampleVN: 'Thúc đẩy sáng tạo tại nơi làm việc.' },
  { id: 'h285', word: 'fraught', meaning: 'đầy, chứa đầy', example: 'A plan fraught with risks.', exampleVN: 'Một kế hoạch đầy rủi ro.' },
  { id: 'h286', word: 'garner', meaning: 'thu thập', example: 'Garner support for the project.', exampleVN: 'Thu thập sự ủng hộ cho dự án.' },
  { id: 'h287', word: 'genesis', meaning: 'nguồn gốc', example: 'The genesis of the idea.', exampleVN: 'Nguồn gốc của ý tưởng.' },
  { id: 'h288', word: 'germane', meaning: 'liên quan', example: 'Facts germane to the case.', exampleVN: 'Sự kiện liên quan đến vụ việc.' },
  { id: 'h289', word: 'grandiose', meaning: 'hoành tráng, phô trương', example: 'Grandiose plans for expansion.', exampleVN: 'Kế hoạch mở rộng hoành tráng.' },
  { id: 'h290', word: 'harbinger', meaning: 'điềm báo', example: 'A harbinger of change.', exampleVN: 'Một điềm báo của sự thay đổi.' },
  { id: 'h291', word: 'hegemony', meaning: 'quyền bá chủ', example: 'Economic hegemony.', exampleVN: 'Quyền bá chủ kinh tế.' },
  { id: 'h292', word: 'hiatus', meaning: 'khoảng ngừng', example: 'A hiatus in production.', exampleVN: 'Một khoảng ngừng trong sản xuất.' },
  { id: 'h293', word: 'holistic', meaning: 'toàn diện', example: 'A holistic approach to management.', exampleVN: 'Một cách tiếp cận toàn diện.' },
  { id: 'h294', word: 'hypothetical', meaning: 'giả thuyết', example: 'A hypothetical scenario.', exampleVN: 'Một kịch bản giả thuyết.' },
  { id: 'h295', word: 'idyllic', meaning: 'thanh bình, yên ả', example: 'An idyllic countryside.', exampleVN: 'Một vùng quê thanh bình.' },
  { id: 'h296', word: 'impasse', meaning: 'bế tắc', example: 'Negotiations reached an impasse.', exampleVN: 'Đàm phán đi vào bế tắc.' },
  { id: 'h297', word: 'imperative', meaning: 'cấp thiết, bắt buộc', example: 'It is imperative to act now.', exampleVN: 'Cấp thiết phải hành động ngay.' },
  { id: 'h298', word: 'implicit', meaning: 'ngầm, ẩn ý', example: 'An implicit agreement.', exampleVN: 'Một thỏa thuận ngầm.' },
  { id: 'h299', word: 'impromptu', meaning: 'ứng khẩu, ngẫu hứng', example: 'An impromptu speech.', exampleVN: 'Một bài phát biểu ứng khẩu.' },
  { id: 'h300', word: 'inaugurate', meaning: 'khánh thành', example: 'Inaugurate the new building.', exampleVN: 'Khánh thành tòa nhà mới.' },
];
