import { Word } from './types';

export const chunkInter7: Word[] = [
  { id: 'i701', word: 'overwhelm', meaning: 'áp đảo, làm choáng ngợp', example: 'The amount of work was overwhelming.', exampleVN: 'Lượng công việc thật choáng ngợp.' },
  { id: 'i702', word: 'owe', meaning: 'nợ', example: 'I owe you a drink.', exampleVN: 'Tôi nợ bạn một chầu nước.' },
  { id: 'i703', word: 'ownership', meaning: 'quyền sở hữu', example: 'Take ownership of the project.', exampleVN: 'Nhận quyền sở hữu dự án.' },
  { id: 'i704', word: 'pace', meaning: 'tốc độ, nhịp độ', example: 'A fast pace of life.', exampleVN: 'Một nhịp sống nhanh.' },
  { id: 'i705', word: 'package', meaning: 'gói, kiện hàng', example: 'Deliver a package.', exampleVN: 'Giao một kiện hàng.' },
  { id: 'i706', word: 'panel', meaning: 'bảng điều khiển, hội đồng', example: 'A panel of experts.', exampleVN: 'Một hội đồng chuyên gia.' },
  { id: 'i707', word: 'panic', meaning: 'hoảng loạn', example: 'Don\'t panic.', exampleVN: 'Đừng hoảng loạn.' },
  { id: 'i708', word: 'paragraph', meaning: 'đoạn văn', example: 'Write a paragraph.', exampleVN: 'Viết một đoạn văn.' },
  { id: 'i709', word: 'parallel', meaning: 'song song', example: 'Parallel lines.', exampleVN: 'Các đường song song.' },
  { id: 'i710', word: 'parameter', meaning: 'thông số', example: 'Within the parameters.', exampleVN: 'Trong phạm vi các thông số.' },
  { id: 'i711', word: 'pardon', meaning: 'tha lỗi', example: 'Pardon me?', exampleVN: 'Xin lỗi, bạn nói gì?' },
  { id: 'i712', word: 'parliament', meaning: 'nghị viện', example: 'Member of Parliament.', exampleVN: 'Thành viên nghị viện.' },
  { id: 'i713', word: 'partial', meaning: 'một phần', example: 'A partial success.', exampleVN: 'Một thành công một phần.' },
  { id: 'i714', word: 'participant', meaning: 'người tham gia', example: 'Active participant.', exampleVN: 'Người tham gia tích cực.' },
  { id: 'i715', word: 'participate', meaning: 'tham gia', example: 'Participate in a survey.', exampleVN: 'Tham gia khảo sát.' },
  { id: 'i716', word: 'particle', meaning: 'hạt', example: 'Dust particles.', exampleVN: 'Các hạt bụi.' },
  { id: 'i717', word: 'particular', meaning: 'cụ thể, đặc biệt', example: 'In particular.', exampleVN: 'Nói riêng.' },
  { id: 'i718', word: 'partly', meaning: 'một phần', example: 'Partly cloudy.', exampleVN: 'Có mây rải rác.' },
  { id: 'i719', word: 'partner', meaning: 'đối tác', example: 'Business partner.', exampleVN: 'Đối tác kinh doanh.' },
  { id: 'i720', word: 'passage', meaning: 'lối đi, đoạn văn', example: 'A secret passage.', exampleVN: 'Một lối đi bí mật.' },
  { id: 'i721', word: 'passion', meaning: 'đam mê', example: 'A passion for music.', exampleVN: 'Đam mê âm nhạc.' },
  { id: 'i722', word: 'passive', meaning: 'thụ động', example: 'Passive income.', exampleVN: 'Thu nhập thụ động.' },
  { id: 'i723', word: 'passport', meaning: 'hộ chiếu', example: 'Renew a passport.', exampleVN: 'Gia hạn hộ chiếu.' },
  { id: 'i724', word: 'pastime', meaning: 'trò tiêu khiển', example: 'Favorite pastime.', exampleVN: 'Trò tiêu khiển yêu thích.' },
  { id: 'i725', word: 'patch', meaning: 'miếng vá, mảng', example: 'A patch of grass.', exampleVN: 'Một mảng cỏ.' },
  { id: 'i726', word: 'patent', meaning: 'bằng sáng chế', example: 'Apply for a patent.', exampleVN: 'Đăng ký bằng sáng chế.' },
  { id: 'i727', word: 'path', meaning: 'con đường', example: 'Follow the path.', exampleVN: 'Đi theo con đường.' },
  { id: 'i728', word: 'patience', meaning: 'sự kiên nhẫn', example: 'Have patience.', exampleVN: 'Hãy kiên nhẫn.' },
  { id: 'i729', word: 'patient', meaning: 'kiên nhẫn, bệnh nhân', example: 'Be patient.', exampleVN: 'Hãy kiên nhẫn.' },
  { id: 'i730', word: 'patrol', meaning: 'tuần tra', example: 'Police patrol.', exampleVN: 'Cảnh sát tuần tra.' },
  { id: 'i731', word: 'patron', meaning: 'khách hàng quen, người bảo trợ', example: 'Art patron.', exampleVN: 'Người bảo trợ nghệ thuật.' },
  { id: 'i732', word: 'pause', meaning: 'tạm dừng', example: 'Pause the video.', exampleVN: 'Tạm dừng video.' },
  { id: 'i733', word: 'payment', meaning: 'thanh toán', example: 'Make a payment.', exampleVN: 'Thanh toán.' },
  { id: 'i734', word: 'peak', meaning: 'đỉnh', example: 'Peak season.', exampleVN: 'Mùa cao điểm.' },
  { id: 'i735', word: 'penalty', meaning: 'hình phạt', example: 'Pay a penalty.', exampleVN: 'Trả tiền phạt.' },
  { id: 'i736', word: 'pension', meaning: 'lương hưu', example: 'Pension scheme.', exampleVN: 'Chương trình lương hưu.' },
  { id: 'i737', word: 'perceive', meaning: 'nhận thức', example: 'Perceive a threat.', exampleVN: 'Nhận thức được một mối đe dọa.' },
  { id: 'i738', word: 'percentage', meaning: 'tỷ lệ phần trăm', example: 'A high percentage.', exampleVN: 'Một tỷ lệ phần trăm cao.' },
  { id: 'i739', word: 'perfect', meaning: 'hoàn hảo', example: 'Perfect timing.', exampleVN: 'Thời điểm hoàn hảo.' },
  { id: 'i740', word: 'perform', meaning: 'thực hiện, biểu diễn', example: 'Perform a task.', exampleVN: 'Thực hiện một nhiệm vụ.' },
  { id: 'i741', word: 'performance', meaning: 'hiệu suất, buổi diễn', example: 'Academic performance.', exampleVN: 'Kết quả học tập.' },
  { id: 'i742', word: 'period', meaning: 'giai đoạn, thời kỳ', example: 'A long period.', exampleVN: 'Một giai đoạn dài.' },
  { id: 'i743', word: 'permanent', meaning: 'vĩnh viễn', example: 'Permanent job.', exampleVN: 'Công việc ổn định lâu dài.' },
  { id: 'i744', word: 'permission', meaning: 'sự cho phép', example: 'Ask for permission.', exampleVN: 'Xin phép.' },
  { id: 'i745', word: 'permit', meaning: 'cho phép, giấy phép', example: 'Parking permit.', exampleVN: 'Giấy phép đậu xe.' },
  { id: 'i746', word: 'persist', meaning: 'kiên trì, dai dẳng', example: 'If symptoms persist...', exampleVN: 'Nếu các triệu chứng vẫn còn...' },
  { id: 'i747', word: 'personal', meaning: 'cá nhân', example: 'Personal opinion.', exampleVN: 'Ý kiến cá nhân.' },
  { id: 'i748', word: 'personality', meaning: 'tính cách', example: 'A strong personality.', exampleVN: 'Một tính cách mạnh mẽ.' },
  { id: 'i749', word: 'personnel', meaning: 'nhân sự', example: 'Personnel department.', exampleVN: 'Phòng nhân sự.' },
  { id: 'i750', word: 'perspective', meaning: 'góc nhìn, phối cảnh', example: 'From my perspective.', exampleVN: 'Từ góc nhìn của tôi.' },
  { id: 'i751', word: 'persuade', meaning: 'thuyết phục', example: 'Persuade someone to join.', exampleVN: 'Thuyết phục ai đó tham gia.' },
  { id: 'i752', word: 'petrol', meaning: 'xăng', example: 'Petrol station.', exampleVN: 'Trạm xăng.' },
  { id: 'i753', word: 'phase', meaning: 'giai đoạn', example: 'The first phase.', exampleVN: 'Giai đoạn đầu.' },
  { id: 'i754', word: 'phenomenon', meaning: 'hiện tượng', example: 'A natural phenomenon.', exampleVN: 'Một hiện tượng tự nhiên.' },
  { id: 'i755', word: 'philosophy', meaning: 'triết học', example: 'Business philosophy.', exampleVN: 'Triết lý kinh doanh.' },
  { id: 'i756', word: 'phone', meaning: 'điện thoại', example: 'Mobile phone.', exampleVN: 'Điện thoại di động.' },
  { id: 'i757', word: 'photograph', meaning: 'ảnh', example: 'Take a photograph.', exampleVN: 'Chụp ảnh.' },
  { id: 'i758', word: 'phrase', meaning: 'cụm từ', example: 'Common phrases.', exampleVN: 'Các cụm từ phổ biến.' },
  { id: 'i759', word: 'physical', meaning: 'thuộc vật chất, cơ thể', example: 'Physical health.', exampleVN: 'Sức khỏe thể chất.' },
  { id: 'i760', word: 'physics', meaning: 'vật lý', example: 'Study physics.', exampleVN: 'Học vật lý.' },
  { id: 'i761', word: 'pick', meaning: 'chọn, nhặt', example: 'Pick a number.', exampleVN: 'Chọn một số.' },
  { id: 'i762', word: 'picture', meaning: 'bức tranh', example: 'Draw a picture.', exampleVN: 'Vẽ một bức tranh.' },
  { id: 'i763', word: 'piece', meaning: 'mảnh, cái', example: 'A piece of cake.', exampleVN: 'Một miếng bánh.' },
  { id: 'i764', word: 'pile', meaning: 'chồng, đống', example: 'A pile of books.', exampleVN: 'Một chồng sách.' },
  { id: 'i765', word: 'pilot', meaning: 'phi công, thí điểm', example: 'A pilot project.', exampleVN: 'Một dự án thí điểm.' },
  { id: 'i766', word: 'pin', meaning: 'ghim', example: 'Safety pin.', exampleVN: 'Kim ghim an toàn.' },
  { id: 'i767', word: 'pipe', meaning: 'ống', example: 'Water pipe.', exampleVN: 'Ống nước.' },
  { id: 'i768', word: 'pitch', meaning: 'sân cỏ, tông độ', example: 'Sales pitch.', exampleVN: 'Lời chào hàng.' },
  { id: 'i769', word: 'pity', meaning: 'đáng tiếc, lòng trắc ẩn', example: 'What a pity!', exampleVN: 'Thật đáng tiếc!' },
  { id: 'i770', word: 'place', meaning: 'đặt, vị trí', example: 'Place an order.', exampleVN: 'Đặt hàng.' },
  { id: 'i771', word: 'plain', meaning: 'đơn giản, đồng bằng', example: 'Plain paper.', exampleVN: 'Giấy trắng.' },
  { id: 'i772', word: 'plan', meaning: 'kế hoạch', example: 'Strategic plan.', exampleVN: 'Kế hoạch chiến lược.' },
  { id: 'i773', word: 'plane', meaning: 'máy bay', example: 'Board a plane.', exampleVN: 'Lên máy bay.' },
  { id: 'i774', word: 'planet', meaning: 'hành tinh', example: 'Red planet.', exampleVN: 'Hành tinh đỏ.' },
  { id: 'i775', word: 'plant', meaning: 'thực vật, nhà máy', example: 'Power plant.', exampleVN: 'Nhà máy điện.' },
  { id: 'i776', word: 'plastic', meaning: 'nhựa', example: 'Plastic bag.', exampleVN: 'Túi nilon.' },
  { id: 'i777', word: 'plate', meaning: 'đĩa', example: 'Empty plate.', exampleVN: 'Chiếc đĩa trống.' },
  { id: 'i778', word: 'platform', meaning: 'nền tảng', example: 'Social media platform.', exampleVN: 'Nền tảng mạng xã hội.' },
  { id: 'i779', word: 'play', meaning: 'chơi, vở kịch', example: 'Broadway play.', exampleVN: 'Vở kịch Broadway.' },
  { id: 'i780', word: 'player', meaning: 'người chơi', example: 'Team player.', exampleVN: 'Người có tinh thần đồng đội.' },
  { id: 'i781', word: 'pleasant', meaning: 'dễ chịu', example: 'Pleasant weather.', exampleVN: 'Thời tiết dễ chịu.' },
  { id: 'i782', word: 'please', meaning: 'vui lòng, làm hài lòng', example: 'Please wait.', exampleVN: 'Vui lòng đợi.' },
  { id: 'i783', word: 'pleasure', meaning: 'niềm vui', example: 'With pleasure.', exampleVN: 'Rất sẵn lòng.' },
  { id: 'i784', word: 'pledge', meaning: 'cam kết', example: 'Make a pledge.', exampleVN: 'Đưa ra một cam kết.' },
  { id: 'i785', word: 'plenty', meaning: 'nhiều', example: 'Plenty of time.', exampleVN: 'Có nhiều thời gian.' },
  { id: 'i786', word: 'plot', meaning: 'cốt truyện, âm mưu', example: 'Movie plot.', exampleVN: 'Cốt truyện phim.' },
  { id: 'i787', word: 'plow', meaning: 'cày', example: 'Plow the field.', exampleVN: 'Cày ruộng.' },
  { id: 'i788', word: 'plug', meaning: 'phích cắm', example: 'Unplug the TV.', exampleVN: 'Rút phích cắm TV.' },
  { id: 'i789', word: 'plus', meaning: 'cộng, ưu điểm', example: 'A big plus.', exampleVN: 'Một ưu điểm lớn.' },
  { id: 'i790', word: 'pocket', meaning: 'túi áo', example: 'In my pocket.', exampleVN: 'Trong túi tôi.' },
  { id: 'i791', word: 'poem', meaning: 'bài thơ', example: 'Write a poem.', exampleVN: 'Viết một bài thơ.' },
  { id: 'i792', word: 'poet', meaning: 'nhà thơ', example: 'Famous poet.', exampleVN: 'Nhà thơ nổi tiếng.' },
  { id: 'i793', word: 'poetry', meaning: 'thơ ca', example: 'Modern poetry.', exampleVN: 'Thơ ca hiện đại.' },
  { id: 'i794', word: 'point', meaning: 'điểm, chỉ', example: 'Point of view.', exampleVN: 'Quan điểm.' },
  { id: 'i795', word: 'poison', meaning: 'chất độc', example: 'Lethal poison.', exampleVN: 'Chất độc chết người.' },
  { id: 'i796', word: 'pole', meaning: 'cực, cái cột', example: 'North Pole.', exampleVN: 'Bắc Cực.' },
  { id: 'i797', word: 'police', meaning: 'cảnh sát', example: 'Police station.', exampleVN: 'Đồn cảnh sát.' },
  { id: 'i798', word: 'policy', meaning: 'chính sách', example: 'Privacy policy.', exampleVN: 'Chính sách bảo mật.' },
  { id: 'i799', word: 'polish', meaning: 'đánh bóng', example: 'Polish shoes.', exampleVN: 'Đánh bóng giày.' },
  { id: 'i800', word: 'polite', meaning: 'lịch sự', example: 'Be polite.', exampleVN: 'Hãy lịch sự.' },
  { id: 'i801', word: 'political', meaning: 'thuộc về chính trị', example: 'Political leader.', exampleVN: 'Lãnh đạo chính trị.' },
  { id: 'i802', word: 'politician', meaning: 'chính trị gia', example: 'Local politician.', exampleVN: 'Chính trị gia địa phương.' },
  { id: 'i803', word: 'politics', meaning: 'chính trị', example: 'Talk about politics.', exampleVN: 'Thảo luận về chính trị.' },
  { id: 'i804', word: 'poll', meaning: 'thăm dò ý kiến', example: 'Public opinion poll.', exampleVN: 'Thăm dò ý kiến công chúng.' },
  { id: 'i805', word: 'pollute', meaning: 'gây ô nhiễm', example: 'Pollute the river.', exampleVN: 'Gây ô nhiễm dòng sông.' },
  { id: 'i806', word: 'pollution', meaning: 'sự ô nhiễm', example: 'Air pollution.', exampleVN: 'Ô nhiễm không khí.' },
  { id: 'i807', word: 'pool', meaning: 'hồ bơi, nhóm', example: 'Swimming pool.', exampleVN: 'Hồ bơi.' },
  { id: 'i808', word: 'poor', meaning: 'nghèo', example: 'Poor quality.', exampleVN: 'Chất lượng kém.' },
  { id: 'i809', word: 'popular', meaning: 'phổ biến', example: 'Popular culture.', exampleVN: 'Văn hóa đại chúng.' },
  { id: 'i810', word: 'population', meaning: 'dân số', example: 'World population.', exampleVN: 'Dân số thế giới.' },
  { id: 'i811', word: 'portion', meaning: 'phần', example: 'A large portion.', exampleVN: 'Một phần lớn.' },
  { id: 'i812', word: 'portrait', meaning: 'chân dung', example: 'Family portrait.', exampleVN: 'Ảnh chân dung gia đình.' },
  { id: 'i813', word: 'position', meaning: 'vị trí', example: 'Current position.', exampleVN: 'Vị trí hiện tại.' },
  { id: 'i814', word: 'positive', meaning: 'tích cực', example: 'Positive attitude.', exampleVN: 'Thái độ tích cực.' },
  { id: 'i815', word: 'possess', meaning: 'sở hữu', example: 'Possess a skill.', exampleVN: 'Sở hữu một kỹ năng.' },
  { id: 'i816', word: 'possession', meaning: 'tài sản sở hữu', example: 'Personal possessions.', exampleVN: 'Đồ dùng cá nhân.' },
  { id: 'i817', word: 'possible', meaning: 'có thể', example: 'Is it possible?', exampleVN: 'Có thể không?' },
  { id: 'i818', word: 'possibly', meaning: 'có lẽ', example: 'Possibly true.', exampleVN: 'Có lẽ là đúng.' },
  { id: 'i819', word: 'post', meaning: 'bưu điện, đăng tải', example: 'Post a letter.', exampleVN: 'Gửi một bức thư.' },
  { id: 'i820', word: 'postage', meaning: 'cước phí bưu điện', example: 'Pay postage.', exampleVN: 'Trả cước bưu điện.' },
  { id: 'i821', word: 'poster', meaning: 'áp phích', example: 'Movie poster.', exampleVN: 'Áp phích phim.' },
  { id: 'i822', word: 'postpone', meaning: 'hoãn lại', example: 'Postpone the event.', exampleVN: 'Hoãn sự kiện.' },
  { id: 'i823', word: 'pot', meaning: 'nồi, chậu', example: 'Flower pot.', exampleVN: 'Chậu hoa.' },
  { id: 'i824', word: 'potential', meaning: 'tiềm năng', example: 'Customer potential.', exampleVN: 'Khách hàng tiềm năng.' },
  { id: 'i825', word: 'poultry', meaning: 'gia cầm', example: 'Raise poultry.', exampleVN: 'Nuôi gia cầm.' },
  { id: 'i826', word: 'pound', meaning: 'bảng Anh, đơn vị trọng lượng', example: 'Five pounds.', exampleVN: 'Năm bảng Anh.' },
  { id: 'i827', word: 'pour', meaning: 'rót', example: 'Pour tea.', exampleVN: 'Rót trà.' },
  { id: 'i828', word: 'poverty', meaning: 'sự nghèo đói', example: 'Eliminate poverty.', exampleVN: 'Xóa nghèo.' },
  { id: 'i829', word: 'powder', meaning: 'bột', example: 'Face powder.', exampleVN: 'Phấn mặt.' },
  { id: 'i830', word: 'power', meaning: 'năng lượng, quyền lực', example: 'Power supply.', exampleVN: 'Nguồn cung cấp điện.' },
  { id: 'i831', word: 'powerful', meaning: 'mạnh mẽ', example: 'A powerful speech.', exampleVN: 'Một bài phát biểu mạnh mẽ.' },
  { id: 'i832', word: 'practical', meaning: 'thực tế', example: 'Practical experience.', exampleVN: 'Kinh nghiệm thực tế.' },
  { id: 'i833', word: 'practice', meaning: 'thực hành, phòng mạch', example: 'Law practice.', exampleVN: 'Hoạt động luật pháp.' },
  { id: 'i834', word: 'praise', meaning: 'khen ngợi', example: 'He praised her work.', exampleVN: 'Anh ấy khen ngợi công việc của cô.' },
  { id: 'i835', word: 'pray', meaning: 'cầu nguyện', example: 'Pray for peace.', exampleVN: 'Cầu nguyện cho hòa bình.' },
  { id: 'i836', word: 'preach', meaning: 'thuyết giáo', example: 'Preach a sermon.', exampleVN: 'Thuyết giáo.' },
  { id: 'i837', word: 'precaution', meaning: 'sự đề phòng', example: 'Take precautions.', exampleVN: 'Thực hiện các biện pháp phòng ngừa.' },
  { id: 'i838', word: 'precede', meaning: 'đến trước', example: 'A precedes B.', exampleVN: 'A đến trước B.' },
  { id: 'i839', word: 'precedent', meaning: 'tiền lệ', example: 'Set a precedent.', exampleVN: 'Tạo tiền lệ.' },
  { id: 'i840', word: 'precious', meaning: 'quý giá', example: 'Precious stones.', exampleVN: 'Đá quý.' },
  { id: 'i841', word: 'precise', meaning: 'chính xác', example: 'Precise measurements.', exampleVN: 'Các phép đo chính xác.' },
  { id: 'i842', word: 'preclude', meaning: 'ngăn chặn', example: 'Preclude the possibility.', exampleVN: 'Ngăn chặn khả năng.' },
  { id: 'i843', word: 'predict', meaning: 'dự đoán', example: 'Predict the future.', exampleVN: 'Dự đoán tương lai.' },
  { id: 'i844', word: 'preface', meaning: 'lời nói đầu', example: 'Read the preface.', exampleVN: 'Đọc lời nói đầu.' },
  { id: 'i845', word: 'prefer', meaning: 'thích hơn', example: 'I prefer tea.', exampleVN: 'Tôi thích trà hơn.' },
  { id: 'i846', word: 'preference', meaning: 'sự ưu tiên', example: 'Personal preference.', exampleVN: 'Sở thích cá nhân.' },
  { id: 'i847', word: 'prefix', meaning: 'tiền tố', example: 'Add a prefix.', exampleVN: 'Thêm tiền tố.' },
  { id: 'i848', word: 'pregnant', meaning: 'có thai', example: 'She is pregnant.', exampleVN: 'Cô ấy đang mang thai.' },
  { id: 'i849', word: 'prejudice', meaning: 'định kiến', example: 'Racial prejudice.', exampleVN: 'Định kiến chủng tộc.' },
  { id: 'i850', word: 'preliminary', meaning: 'sơ bộ', example: 'Preliminary results.', exampleVN: 'Kết quả sơ bộ.' },
];

export const processChunkInter7 = () => {
  return chunkInter7.map(w => ({ ...w, pos: '(n)' as string }));
};
