import { Word } from './types';

export const chunk22_raw: Omit<Word, 'id'>[] = [
  { word: "appointment", meaning: "cuộc hẹn", example: "I've got a dental appointment.", exampleVN: "Tôi có một cuộc hẹn nha sĩ." },
  { word: "explore", meaning: "khám phá, thăm dò", example: "Explore new markets.", exampleVN: "Khám phá các thị trường mới." },
  { word: "convenient", meaning: "thuận tiện, tiện lợi", example: "The clinic is very convenient.", exampleVN: "Phòng khám rất thuận tiện." },
  { word: "take the afternoon off", meaning: "nghỉ làm buổi chiều", example: "Take the afternoon off to go to the dentist.", exampleVN: "Nghỉ làm buổi chiều để đi khám nha sĩ." },
  { word: "patient", meaning: "bệnh nhân", example: "The doctor sees patients.", exampleVN: "Bác sĩ khám bệnh nhân." },
  { word: "receptionist", meaning: "lễ tân", example: "Looking for a new receptionist.", exampleVN: "Đang tìm một lễ tân mới." },
  { word: "permit", meaning: "cho phép", example: "Smoking is not permitted.", exampleVN: "Không được phép hút thuốc." },
  { word: "prescription", meaning: "đơn thuốc", example: "A prescription for antibiotics.", exampleVN: "Đơn thuốc kháng sinh." },
  { word: "practice", meaning: "phòng khám, cơ sở kinh doanh", example: "Her own dental practice.", exampleVN: "Phòng khám nha khoa của riêng cô ấy." },
  { word: "nutritional", meaning: "thuộc về dinh dưỡng", example: "Nutritional information.", exampleVN: "Thông tin dinh dưỡng." },
  { word: "knowledgeable", meaning: "có kiến thức, am hiểu", example: "Very knowledgeable about exercise.", exampleVN: "Rất am hiểu về thể dục." },
  { word: "routine", meaning: "thói quen, quy trình", example: "Exercise routines.", exampleVN: "Các bài tập thể dục." },
  { word: "composer", meaning: "nhà soạn nhạc", example: "Leading composers.", exampleVN: "Những nhà soạn nhạc hàng đầu." },
  { word: "shift", meaning: "ca làm việc", example: "The night shift.", exampleVN: "Ca đêm." },
  { word: "effectiveness", meaning: "tính hiệu quả", example: "Testing the effectiveness.", exampleVN: "Kiểm tra tính hiệu quả." },
  { word: "lead", meaning: "hàng đầu, dẫn đầu", example: "A leading expert.", exampleVN: "Một chuyên gia hàng đầu." },
  { word: "stay hydrated", meaning: "giữ cho cơ thể đủ nước", example: "Important to stay hydrated.", exampleVN: "Quan trọng là giữ đủ nước." },
  { word: "remind", meaning: "nhắc nhở", example: "Please remind me.", exampleVN: "Vui lòng nhắc tôi." },
  { word: "predict", meaning: "dự đoán", example: "Predict the future.", exampleVN: "Dự đoán tương lai." },
  { word: "accounting department", meaning: "phòng kế toán", example: "The accounting department is on the third floor.", exampleVN: "Phòng kế toán ở tầng 3." },
  { word: "rent out", meaning: "cho thuê", example: "Rent out her spare room.", exampleVN: "Cho thuê phòng trống." },
  { word: "burden", meaning: "gánh nặng", example: "A heavy burden.", exampleVN: "Một gánh nặng lớn." },
  { word: "feasible", meaning: "khả thi", example: "It is not feasible.", exampleVN: "Nó không khả thi." },
  { word: "tenant", meaning: "người thuê nhà", example: "The first tenants.", exampleVN: "Những người thuê nhà đầu tiên." },
  { word: "project plan", meaning: "kế hoạch dự án", example: "A great project plan.", exampleVN: "Một kế hoạch dự án tuyệt vời." },
  { word: "prototype", meaning: "nguyên mẫu, mẫu đầu tiên", example: "The prototype design.", exampleVN: "Thiết kế nguyên mẫu." },
  { word: "originally", meaning: "ban đầu", example: "Originally planned for next year.", exampleVN: "Ban đầu được lên kế hoạch sang năm." },
  { word: "familiar with", meaning: "quen thuộc với", example: "Familiar with new designs.", exampleVN: "Quen thuộc với thiết kế mới." },
  { word: "fresh", meaning: "mới mẻ", example: "A fresh design.", exampleVN: "Một thiết kế mới mẻ." },
  { word: "come up with", meaning: "nghĩ ra, đưa ra", example: "Come up with some prototypes.", exampleVN: "Nghĩ ra vài nguyên mẫu." },
  { word: "undergo", meaning: "trải qua (sửa chữa, kiểm tra)", example: "Undergoing renovations.", exampleVN: "Đang trải qua trùng tu." },
  { word: "floor plan", meaning: "sơ đồ tầng, sơ đồ mặt bằng", example: "Floor plans for the new office.", exampleVN: "Sơ đồ mặt bằng cho văn phòng." },
  { word: "architect", meaning: "kiến trúc sư", example: "Ask the architect.", exampleVN: "Hỏi kiến trúc sư." },
  { word: "lumber", meaning: "gỗ xẻ", example: "Local lumber.", exampleVN: "Gỗ xẻ địa phương." },
  { word: "supervisor", meaning: "người giám sát", example: "The supervisor is checking.", exampleVN: "Người giám sát đang kiểm tra." },
  { word: "renovation", meaning: "sự cải tạo, tu sửa", example: "A major renovation.", exampleVN: "Một sự cải tạo lớn." },
  { word: "extensive", meaning: "sâu rộng, quy mô lớn", example: "Extensive work.", exampleVN: "Khối lượng công việc lớn/sâu rộng." },
  { word: "proceed", meaning: "tiến hành, tiếp tục", example: "Proceed with the project.", exampleVN: "Tiến hành dự án." },
  { word: "hire", meaning: "thuê, tuyển dụng", example: "They were hiring.", exampleVN: "Họ đang tuyển dụng." },
  { word: "brand-new", meaning: "mới toanh", example: "This building is brand-new.", exampleVN: "Tòa nhà này mới toanh." },
  { word: "touch base", meaning: "liên lạc, trao đổi", example: "Calling to touch base with you.", exampleVN: "Gọi để nói chuyện với bạn." },
  { word: "expertise", meaning: "chuyên môn", example: "Extensive expertise.", exampleVN: "Chuyên môn sâu rộng." },
  { word: "consultant", meaning: "tư vấn viên", example: "An engineering consultant.", exampleVN: "Chuyên viên tư vấn kỹ thuật." },
  { word: "estate", meaning: "bất động sản, cơ ngơi", example: "Historic estates.", exampleVN: "Cơ ngơi lịch sử." },
  { word: "agency", meaning: "đại lý/môi giới", example: "A temp agency.", exampleVN: "Một đại lý cung ứng tạm thời." },
  { word: "construction", meaning: "sự xây dựng", example: "Construction sites.", exampleVN: "Các công trường xây dựng." },
  { word: "remodel", meaning: "tu sửa, cải tạo", example: "Remodel the entrance hall.", exampleVN: "Cải tạo sảnh vào." },
  { word: "appreciate", meaning: "trân trọng, đánh giá cao", example: "I really appreciate your help.", exampleVN: "Tôi thực sự đánh giá cao sự giúp đỡ của bạn." },
  { word: "logo", meaning: "biểu trưng, logo", example: "Modern design for its new logo.", exampleVN: "Thiết kế hiện đại cho logo mới." },
  { word: "brand", meaning: "thương hiệu", example: "A global brand.", exampleVN: "Một thương hiệu toàn cầu." },
  { word: "bid", meaning: "sự đấu thầu", example: "Submitted a bid.", exampleVN: "Nộp hồ sơ dự thầu." },
  { word: "interior design", meaning: "thiết kế nội thất", example: "Interior design company.", exampleVN: "Công ty thiết kế nội thất." },
  { word: "under budget", meaning: "dưới ngân sách", example: "Under budget.", exampleVN: "Thấp hơn ngân sách." },
  { word: "city council", meaning: "hội đồng thành phố", example: "The city council approved.", exampleVN: "Hội đồng thành phố phê duyệt." },
  { word: "fund", meaning: "cấp vốn, tài trợ", example: "The government will fund it.", exampleVN: "Chính phủ sẽ tài trợ." },
  { word: "durable", meaning: "bền bỉ, lâu bền", example: "Durable plastic.", exampleVN: "Nhựa bền." },
  { word: "color scheme", meaning: "hệ màu, phối màu", example: "Blue and white color scheme.", exampleVN: "Hệ màu xanh trắng." },
  { word: "pick up", meaning: "lấy, đón (ai đó)", example: "Pick up her prescription.", exampleVN: "Lấy đơn thuốc." },
  { word: "carry", meaning: "mang, vác, có bán (hàng)", example: "Doesn't carry organic milk.", exampleVN: "Không bán sữa hữu cơ." },
  { word: "reflect", meaning: "phản chiếu, phản ánh", example: "The price reflects the quality.", exampleVN: "Giá cả phản ánh chất lượng." },
  { word: "officially", meaning: "một cách chính thức", example: "Will officially open.", exampleVN: "Sẽ chính thức mở cửa." },
  { word: "modernize", meaning: "hiện đại hóa", example: "Completely modernized.", exampleVN: "Được hiện đại hóa hoàn toàn." },
  { word: "grade", meaning: "cấp độ, phẩm cấp", example: "High-grade coffee beans.", exampleVN: "Hạt cà phê chất lượng cao." },
  { word: "pallet", meaning: "tấm pallet (để hàng)", example: "A wooden pallet.", exampleVN: "Một tấm pallet gỗ." },
  { word: "apron", meaning: "tạp dề", example: "Wearing a white apron.", exampleVN: "Đang mặc tạp dề trắng." },
  { word: "sales promotion", meaning: "chương trình khuyến mãi", example: "Running a sales promotion.", exampleVN: "Đang chạy chương trình khuyến mãi." },
  { word: "discount", meaning: "sự giảm giá", example: "A ten percent discount.", exampleVN: "Giảm giá 10 phần trăm." },
  { word: "showcase", meaning: "trưng bày, giới thiệu", example: "Showcase our product.", exampleVN: "Giới thiệu sản phẩm của chúng tôi." },
  { word: "stand out", meaning: "nổi bật", example: "Make our product stand out.", exampleVN: "Làm sản phẩm của chúng ta nổi bật." },
  { word: "my treat", meaning: "tôi bao, tôi mời", example: "It's my treat.", exampleVN: "Chầu này tôi đãi." },
  { word: "corporate", meaning: "thuộc về doanh nghiệp", example: "Corporate clients.", exampleVN: "Khách hàng doanh nghiệp." },
  { word: "roll up one's sleeves", meaning: "xắn tay áo lên (để làm việc)", example: "Rolled up his sleeves.", exampleVN: "Khởi gân lên làm việc." },
  { word: "owner", meaning: "chủ sở hữu", example: "The owner of the restaurant.", exampleVN: "Chủ nhà hàng." },
  { word: "conference", meaning: "hội nghị", example: "Sales conference.", exampleVN: "Hội nghị bán hàng." },
  { word: "patron", meaning: "khách hàng quen", example: "Many loyal patrons.", exampleVN: "Nhiều khách hàng trung thành." },
  { word: "medication", meaning: "dược phẩm, thuốc", example: "Regular medication.", exampleVN: "Thuốc uống định kỳ." },
  { word: "purchase", meaning: "sự mua sắm, mua", example: "Proof of purchase.", exampleVN: "Bằng chứng mua hàng." },
  { word: "refund", meaning: "tiền hoàn lại", example: "A full refund.", exampleVN: "Hoàn lại toàn bộ." },
  { word: "receipt", meaning: "biên lai", example: "A receipt for the coffee.", exampleVN: "Biên lai cho ly cà phê." },
  { word: "container", meaning: "hộp đựng, thùng chứa", example: "A sealed container.", exampleVN: "Hộp kín." },
  { word: "organic", meaning: "hữu cơ", example: "Organic vegetables.", exampleVN: "Rau hữu cơ." },
  { word: "restock", meaning: "bổ sung hàng hóa", example: "Restocking the shelves.", exampleVN: "Đang xếp thêm hàng lên kệ." },
  { word: "detergent", meaning: "chất tẩy rửa", example: "Laundry detergent.", exampleVN: "Bột giặt/Nước giặt." },
  { word: "scan", meaning: "quét (tài liệu)", example: "Scan the receipts.", exampleVN: "Quét các biên lai." },
  { word: "sales representative", meaning: "đại diện bán hàng", example: "A sales representative.", exampleVN: "Một đại diện bán hàng." },
  { word: "control over", meaning: "quyền kiểm soát đối với", example: "More control over quality.", exampleVN: "Kiểm soát chất lượng tốt hơn." },
  { word: "associate", meaning: "cộng tác viên, nhân viên", example: "A sales associate.", exampleVN: "Nhân viên bán hàng." },
  { word: "pitch", meaning: "quảng bá, chào hàng", example: "Pitch our new products.", exampleVN: "Chào hàng sản phẩm mới." },
  { word: "permanent", meaning: "lâu dài, vĩnh viễn", example: "A permanent menu item.", exampleVN: "Một món ăn cố định trong thực đơn." },
  { word: "bakery", meaning: "tiệm bánh", example: "The bakery will be open.", exampleVN: "Tiệm bánh sẽ mở cửa." },
  { word: "offer", meaning: "cung cấp, đưa ra", example: "Offering discounts.", exampleVN: "Đang đưa ra các ưu đãi." },
  { word: "department", meaning: "phòng ban, bộ phận", example: "Sales department.", exampleVN: "Phòng kinh doanh." },
  { word: "purchasing trend", meaning: "xu hướng mua sắm", example: "Track consumer purchasing trends.", exampleVN: "Theo dõi xu hướng mua sắm của người tiêu dùng." },
  { word: "branding", meaning: "xây dựng thương hiệu", example: "Our branding firm.", exampleVN: "Công ty xây dựng thương hiệu của chúng tôi." },
  { word: "chain", meaning: "chuỗi (cửa hàng)", example: "Department store chain.", exampleVN: "Chuỗi cửa hàng bách hóa." },
  { word: "representative", meaning: "người đại diện", example: "Sales representatives.", exampleVN: "Các đại diện bán hàng." }
];

export function processChunk22(): Word[] {
  return chunk22_raw.map((w, index) => {
    return {
      ...w,
      id: `c22_${index}`,
      pos: '(n/a)'
    };
  });
}
