import { Word } from './types';

export const chunk17_raw: Omit<Word, 'id'>[] = [
  { word: "botanical garden", meaning: "vườn bách thảo", example: "The botanical garden has many rare plants.", exampleVN: "Vườn bách thảo có nhiều cây quý hiếm." },
  { word: "bottom", meaning: "đáy, phần dưới cùng", example: "At the bottom of my bag.", exampleVN: "Dưới đáy túi của tôi." },
  { word: "admission", meaning: "sự nhận vào, phí vào cửa", example: "Admission fee.", exampleVN: "Phí vào cửa." },
  { word: "go-ahead", meaning: "sự cho phép bắt đầu", example: "Waiting for the go-ahead.", exampleVN: "Chờ sự cho phép." },
  { word: "I bet", meaning: "Tôi cá là, chắc chắn là", example: "I bet it will rain.", exampleVN: "Tôi cá là trời sẽ mưa." },
  { word: "overflow", meaning: "tràn ra", example: "The dustbin is starting to overflow.", exampleVN: "Thùng rác đang bắt đầu tràn ra." },
  { word: "extend", meaning: "gia hạn, kéo dài", example: "Extend the deadline.", exampleVN: "Gia hạn thời hạn." },
  { word: "temporary", meaning: "tạm thời", example: "A temporary solution.", exampleVN: "Giải pháp tạm thời." },
  { word: "credentials", meaning: "thông tin đăng nhập", example: "Enter your login credentials.", exampleVN: "Nhập thông tin đăng nhập của bạn." },
  { word: "be prompted to", meaning: "được nhắc làm gì", example: "You will be prompted to change your password.", exampleVN: "Bạn sẽ được nhắc thay đổi mật khẩu." },
  { word: "complete", meaning: "hoàn thành", example: "Complete the form.", exampleVN: "Hoàn thành mẫu đơn." },
  { word: "drop", meaning: "giảm, rơi", example: "The temperature will drop.", exampleVN: "Nhiệt độ sẽ giảm." },
  { word: "decline", meaning: "suy giảm, từ chối", example: "Demand has declined.", exampleVN: "Nhu cầu đã suy giảm." },
  { word: "pros and cons", meaning: "ưu và nhược điểm", example: "Weigh the pros and cons.", exampleVN: "Cân nhắc ưu và nhược điểm." },
  { word: "stretch", meaning: "dải (đất/đường), kéo dài", example: "This stretch of road.", exampleVN: "Đoạn đường này." },
  { word: "bold", meaning: "đậm, táo bạo", example: "Written in bold letters.", exampleVN: "Được viết bằng chữ in đậm." },
  { word: "trendy", meaning: "hợp thời trang, xu hướng", example: "Trendy clothes.", exampleVN: "Quần áo hợp thời trang." },
  { word: "determine", meaning: "xác định, quyết định", example: "Determine the cause.", exampleVN: "Xác định nguyên nhân." },
  { word: "media relation department", meaning: "phòng quan hệ truyền thông", example: "Contact the media relation department.", exampleVN: "Liên hệ phòng quan hệ truyền thông." },
  { word: "findings", meaning: "kết quả nghiên cứu", example: "The findings of the survey.", exampleVN: "Kết quả của cuộc khảo sát." },
  { word: "drilling", meaning: "việc khoan", example: "Offshore drilling.", exampleVN: "Khoan ngoài khơi." },
  { word: "walkway", meaning: "lối đi bộ", example: "The walkway is covered with leaves.", exampleVN: "Lối đi bộ bị phủ đầy lá." },
  { word: "balcony", meaning: "ban công", example: "Standing on the balcony.", exampleVN: "Đứng trên ban công." },
  { word: "lean against", meaning: "tựa vào", example: "Leaning against the wall.", exampleVN: "Tựa vào bức tường." },
  { word: "plank", meaning: "tấm ván", example: "Heavy wooden planks.", exampleVN: "Những tấm ván gỗ nặng." },
  { word: "stack", meaning: "chất đống, xếp chồng", example: "Stacked in the corner.", exampleVN: "Được xếp chồng trong góc." },
  { word: "bulletin board", meaning: "bảng tin", example: "Check the bulletin board.", exampleVN: "Kiểm tra bảng tin." },
  { word: "pin", meaning: "ghim lại", example: "Pinned a photo to the wall.", exampleVN: "Đã ghim một bức ảnh lên tường." },
  { word: "bin", meaning: "thùng chứa (rác, đồ)", example: "Recycling bin.", exampleVN: "Thùng rác tái chế." },
  { word: "reach for", meaning: "với lấy", example: "Reaching for a toy.", exampleVN: "Với lấy đồ chơi." },
  { word: "either way", meaning: "cách nào cũng được", example: "Either way is fine.", exampleVN: "Cách nào cũng được." },
  { word: "renovation", meaning: "sự đổi mới, đại tu", example: "Closed for renovations.", exampleVN: "Đóng cửa để đại tu." },
  { word: "in case", meaning: "phòng khi, trong trường hợp", example: "In case it rains.", exampleVN: "Phòng khi trời mưa." },
  { word: "down the hall", meaning: "ở cuối hành lang", example: "Just down the hall.", exampleVN: "Ngay cuối hành lang." },
  { word: "keep up with", meaning: "theo kịp, đáp ứng được", example: "Keep up with the demand.", exampleVN: "Đáp ứng nhu cầu." },
  { word: "concept", meaning: "khái niệm", example: "Explain the concept.", exampleVN: "Giải thích khái niệm." },
  { word: "preliminary", meaning: "sơ bộ, mở đầu", example: "Preliminary sketches.", exampleVN: "Bản phác thảo sơ bộ." },
  { word: "protective", meaning: "bảo vệ, che chắn", example: "Protective mat.", exampleVN: "Tấm thảm bảo vệ." },
  { word: "get back to", meaning: "phản hồi, liên lạc lại", example: "I will get back to you soon.", exampleVN: "Tôi sẽ liên lạc lại với bạn sớm." },
  { word: "upcoming", meaning: "sắp tới", example: "The upcoming conference.", exampleVN: "Hội nghị sắp tới." },
  { word: "opportunity", meaning: "cơ hội", example: "Great opportunity.", exampleVN: "Một cơ hội tuyệt vời." },
  { word: "stay ahead of", meaning: "dẫn trước, đi trước", example: "Stay ahead of developments.", exampleVN: "Đi trước các sự phát triển." },
  { word: "update", meaning: "thông tin cập nhật / cập nhật", example: "Call for an update.", exampleVN: "Gọi để cập nhật tình hình." },
  { word: "generally", meaning: "nói chung, một cách tổng quát", example: "Speak generally.", exampleVN: "Nói một cách khái quát." },
  { word: "incorporate", meaning: "kết hợp, sáp nhập", example: "Incorporate new approaches.", exampleVN: "Kết hợp các phương pháp mới." },
  { word: "physically active", meaning: "vận động thể chất", example: "Be physically active.", exampleVN: "Vận động thể chất." },
  { word: "motivated", meaning: "có động lực, nhiệt huyết", example: "Motivated individuals.", exampleVN: "Những cá nhân đầy nhiệt huyết." },
  { word: "continuing education", meaning: "giáo dục thường xuyên", example: "Continuing education workshop.", exampleVN: "Hội thảo giáo dục thường xuyên." },
  { word: "waiting list", meaning: "danh sách chờ", example: "A waiting list for the workshop.", exampleVN: "Danh sách chờ cho buổi hội thảo." },
  { word: "sign up", meaning: "đăng ký", example: "Sign up for the newsletter.", exampleVN: "Đăng ký nhận bản tin." },
  { word: "bush", meaning: "bụi cây, bụi rậm", example: "Behind the bush.", exampleVN: "Sau bụi cây." },
  { word: "be covered with", meaning: "được bao phủ bởi/với", example: "Covered with snow.", exampleVN: "Phủ đầy tuyết." },
  { word: "fold", meaning: "gấp lại, khoanh (tay)", example: "Fold the laundry.", exampleVN: "Gấp quần áo." },
  { word: "past", meaning: "đi ngang qua", example: "Walked past your house.", exampleVN: "Đi ngang qua nhà bạn." },
  { word: "pedestrian", meaning: "người đi bộ", example: "Yield to pedestrians.", exampleVN: "Nhường đường cho người đi bộ." },
  { word: "contact information", meaning: "Thông tin liên lạc", example: "Update your contact information.", exampleVN: "Cập nhật thông tin liên lạc." },
  { word: "take place", meaning: "Diễn ra", example: "The ceremony will take place here.", exampleVN: "Buổi lễ sẽ diễn ra ở đây." },
  { word: "certificate", meaning: "Chứng chỉ, giấy chứng nhận", example: "A certificate for completing the course.", exampleVN: "Chứng nhận hoàn thành khóa học." },
  { word: "shade", meaning: "sắc thái (màu)", example: "A lighter shade of blue.", exampleVN: "Sắc thái xanh nhạt hơn." },
  { word: "brighten", meaning: "làm sáng bừng", example: "Brighten up a room.", exampleVN: "Làm sáng bừng căn phòng." },
  { word: "author", meaning: "tác giả", example: "The author is famous.", exampleVN: "Tác giả rất nổi tiếng." },
  { word: "package", meaning: "bưu kiện, gói đồ", example: "Return this package.", exampleVN: "Trả lại kiện hàng." },
  { word: "measure", meaning: "biện pháp", example: "Safety measures.", exampleVN: "Biện pháp an toàn." },
  { word: "intern", meaning: "thực tập sinh", example: "Looking for more interns.", exampleVN: "Tìm kiếm thực tập sinh." },
  { word: "plenty", meaning: "nhiều, đủ đầy", example: "Plenty of time.", exampleVN: "Nhiều thời gian." },
  { word: "stand out", meaning: "nổi bật", example: "Made her stand out.", exampleVN: "Khiến cô ấy nổi bật." },
  { word: "consult", meaning: "tham vấn, tư vấn", example: "Consult a lawyer.", exampleVN: "Tham vấn luật sư." },
  { word: "keyword", meaning: "từ khóa", example: "Enter a keyword.", exampleVN: "Nhập từ khóa." },
  { word: "archive", meaning: "kho lưu trữ", example: "Family archive.", exampleVN: "Lưu trữ gia đình." },
  { word: "ladder", meaning: "cái thang", example: "Climbed up the ladder.", exampleVN: "Trèo lên thang." },
  { word: "width", meaning: "chiều rộng", example: "Measure the width.", exampleVN: "Đo chiều rộng." },
  { word: "sealed", meaning: "được niêm phong, đóng kín", example: "Sealed with wax.", exampleVN: "Niêm phong bằng sáp." },
  { word: "individual", meaning: "cá nhân", example: "Each individual.", exampleVN: "Mỗi cá nhân." },
  { word: "sample", meaning: "mẫu thử", example: "Free samples.", exampleVN: "Mẫu thử miễn phí." },
  { word: "professional", meaning: "chuyên nghiệp", example: "Professional advice.", exampleVN: "Lời khuyên chuyên nghiệp." },
  { word: "request", meaning: "yêu cầu", example: "A formal request.", exampleVN: "Một yêu cầu chính thức." },
  { word: "schedule", meaning: "lịch trình", example: "Stick to the schedule.", exampleVN: "Bám sát lịch trình." },
  { word: "application", meaning: "đơn đăng ký, ứng dụng", example: "Job application.", exampleVN: "Đơn xin việc." },
  { word: "opening", meaning: "chỗ trống/giờ mở cửa", example: "Any openings in your schedule?", exampleVN: "Có thời gian trống không?" },
  { word: "hygiene", meaning: "vệ sinh", example: "Dental hygienist.", exampleVN: "Chuyên viên vệ sinh nha khoa." },
  { word: "code", meaning: "mã số", example: "Department code.", exampleVN: "Mã phòng ban." },
  { word: "communicate", meaning: "thông báo, truyền đạt", example: "Details will be communicated.", exampleVN: "Chi tiết sẽ được thông báo." },
  { word: "agriculture", meaning: "nông nghiệp", example: "News in agriculture.", exampleVN: "Tin tức nông nghiệp." }
];

export function processChunk17(): Word[] {
  return chunk17_raw.map((w, index) => {
    return {
      ...w,
      id: `c17_${index}`,
      pos: '(n/a)'
    };
  });
}
