import { Word } from './types';

export const chunk24_raw: Omit<Word, 'id'>[] = [
  { word: "demonstration", meaning: "buổi trình diễn, thuyết minh", example: "Gave a demonstration of the machine.", exampleVN: "Đã có một buổi trình diễn về tính năng máy móc." },
  { word: "injection molding", meaning: "đúc khuôn tiêm", example: "Advanced injection molding.", exampleVN: "Công nghệ đúc khuôn tiêm hiện đại." },
  { word: "currently", meaning: "hiện tại", example: "Is currently fitted with a new mold.", exampleVN: "Hiện đang được gắn một khuôn mới." },
  { word: "widely available", meaning: "có sẵn rộng rãi", example: "Widely available.", exampleVN: "Có sẵn ở khắp nơi." },
  { word: "install", meaning: "cài đặt, lắp đặt", example: "Install the new lights.", exampleVN: "Lắp đặt những bóng đèn mới." },
  { word: "cardboard", meaning: "bìa các-tông", example: "Cardboard boxes.", exampleVN: "Hộp bìa các-tông." },
  { word: "software", meaning: "phần mềm", example: "New software.", exampleVN: "Phần mềm mới." },
  { word: "model", meaning: "mẫu, mô hình", example: "An older model.", exampleVN: "Một mẫu đời cũ." },
  { word: "upload", meaning: "tải lên", example: "Upload the photo.", exampleVN: "Tải bức ảnh lên." },
  { word: "cancel", meaning: "hủy bỏ", example: "Cancel the conference call.", exampleVN: "Hủy bỏ cuộc họp nhóm." },
  { word: "transfer", meaning: "chuyển, chuyển giao", example: "Transfer the service.", exampleVN: "Chuyển giao dịch vụ." },
  { word: "producer", meaning: "nhà sản xuất", example: "A local producer.", exampleVN: "Một nhà sản xuất địa phương." },
  { word: "expand", meaning: "mở rộng", example: "Expand and take on more.", exampleVN: "Mở rộng và đảm nhận nhiều việc hơn." },
  { word: "unpredictability", meaning: "sự không dự đoán trước được", example: "Unpredictability of this system.", exampleVN: "Sự khó đoán của hệ thống này." },
  { word: "survey", meaning: "cuộc khảo sát", example: "Data from the survey.", exampleVN: "Dữ liệu từ cuộc khảo sát." },
  { word: "resource", meaning: "nguồn lực/tài nguyên", example: "A great resource.", exampleVN: "Một nguồn tham khảo tuyệt vời." },
  { word: "transit", meaning: "hệ thống vận tải", example: "Public transit system.", exampleVN: "Hệ thống giao thông công cộng." },
  { word: "notification", meaning: "thông báo", example: "Receive a notification.", exampleVN: "Nhận được một thông báo." },
  { word: "in-house", meaning: "nội bộ (tự làm)", example: "We do everything in-house.", exampleVN: "Chúng tôi tự làm mọi quy trình." },
  { word: "component", meaning: "linh kiện, thành phần", example: "Metal components.", exampleVN: "Thành phần kim loại." },
  { word: "inferior", meaning: "kém chất lượng, thấp hơn", example: "Inferior parts.", exampleVN: "Phụ tùng kém chất lượng." },
  { word: "purchasing trend", meaning: "xu hướng mua sắm", example: "Purchasing trends.", exampleVN: "Nhịp độ mua sắm." },
  { word: "lower", meaning: "hạ xuống, kéo xuống", example: "Lowering the screen.", exampleVN: "Sắp xếp lại màn hình." },
  { word: "stack", meaning: "chồng lên, chất đống", example: "Stacked neatly.", exampleVN: "Chất đống đồ gọn gàng." },
  { word: "invoice", meaning: "hóa đơn", example: "Process the invoice.", exampleVN: "Quy trình làm hóa đơn." },
  { word: "manual", meaning: "sách hướng dẫn", example: "The instruction manual.", exampleVN: "Sách hướng dẫn sử dụng." },
  { word: "compile", meaning: "biên soạn, thu thập dữ liệu", example: "Compile a list.", exampleVN: "Dịch những số liệu." },
  { word: "metal scrap", meaning: "kim loại vụn, phế liệu", example: "Metal scrap.", exampleVN: "Sắt thép vụn." },
  { word: "guarantee", meaning: "sự bảo hành, cam kết", example: "A two-year guarantee.", exampleVN: "Bảo hành hai năm." },
  { word: "support column", meaning: "cột trụ, cột đỡ", example: "Main support columns.", exampleVN: "Cột trống chính." },
  { word: "concrete", meaning: "bê tông", example: "Solid concrete.", exampleVN: "Bê tông nguyên tảng." },
  { word: "affect", meaning: "ảnh hưởng", example: "Will affect our production costs.", exampleVN: "Sẽ tác động vào giá sản xuất." },
  { word: "instead", meaning: "thay vào đó", example: "Have tea instead.", exampleVN: "Thay thế bằng việc uống trà." },
  { word: "zero emissions", meaning: "không phát thải", example: "Zero emissions.", exampleVN: "Lượng khí thải carbon tiệm cận mức không." },
  { word: "engineering team", meaning: "đội ngũ kỹ thuật", example: "The engineering team.", exampleVN: "Tổ chuyên môn phát triển thiết bị." },
  { word: "fix", meaning: "sửa chữa", example: "Fix the equipment.", exampleVN: "Qúa hạn sửa phần cứng." },
  { word: "price", meaning: "giá", example: "The price of this printer.", exampleVN: "Giá cả cái máy in." },
  { word: "upgrade", meaning: "nâng cấp", example: "Upgrade the system.", exampleVN: "Hệ thống cập nhật." },
  { word: "charge", meaning: "tính phí", example: "Charge for delivery.", exampleVN: "Giá ship là thêm tiền." },
  { word: "rental", meaning: "sự cho thuê, đồ thuê", example: "Monthly rental.", exampleVN: "Cho thuê định kỳ." },
  { word: "loan", meaning: "khoản vay", example: "A bank loan.", exampleVN: "Nợ ngân hàng." },
  { word: "snowmobile", meaning: "xe trượt tuyết", example: "Rode a snowmobile.", exampleVN: "Chiếc xe đi được trên dốc băng." },
  { word: "tourism", meaning: "ngành du lịch", example: "Tourism is the main source of income.", exampleVN: "Hoạt động du lịch sẽ mang lại nhiều vốn." },
  { word: "increase", meaning: "tăng lên", example: "Continues to increase.", exampleVN: "Gia tăng với tốc độ khủng khiếp." },
  { word: "vehicle", meaning: "xe cộ, phương tiện", example: "A company vehicle.", exampleVN: "Thuộc quyền sở hữu công ty xe." },
  { word: "delay", meaning: "trì hoãn, sự chậm trễ", example: "The flight was delayed.", exampleVN: "Chuyến bay gặp khó dễ." },
  { word: "commuter", meaning: "người đi làm xa", example: "Daily commuters.", exampleVN: "Dân thường đi làm xa." },
  { word: "depart", meaning: "khởi hành", example: "Depart at 8:00 AM.", exampleVN: "Máy bay chuẩn bị cất cánh." },
  { word: "destination", meaning: "điểm đến", example: "Arrived at our destination.", exampleVN: "Tại nơi đây, tôi đã tới." },
  { word: "kiosk", meaning: "quầy bán hàng, trạm thông tin", example: "An information kiosk.", exampleVN: "Xung quanh có các trạm thông tin." },
  { word: "lettering", meaning: "kiểu chữ", example: "The lettering on the sign.", exampleVN: "Có font chữ khá đẹp." },
  { word: "transportation agency", meaning: "cơ quan vận tải", example: "Local transportation agency.", exampleVN: "Các nhà trung chuyển." },
  { word: "fuel-efficient", meaning: "tiết kiệm nhiên liệu", example: "A fuel-efficient car.", exampleVN: "Tốn tương đối ít xăng." },
  { word: "extract", meaning: "chiết xuất, khai thác", example: "Extract oil.", exampleVN: "Khai mỏ tự nhiên." },
  { word: "line", meaning: "chạy dọc theo, xếp hàng", example: "Line the entrance.", exampleVN: "Quay dọc xung quanh." },
  { word: "platform", meaning: "sân ga, nền tảng", example: "Platform number 9.", exampleVN: "Làm trên nhiều nền tảng số." },
  { word: "railing", meaning: "lan can, rào chắn", example: "Metal railing.", exampleVN: "Rào chắn kim loại." },
  { word: "buffet", meaning: "tiệc buffet", example: "Breakfast buffet.", exampleVN: "Tiệc chiêu đãi tự chọn." },
  { word: "agent", meaning: "đại lý, người đại diện", example: "A travel agent.", exampleVN: "Các tay sale du lịch địa phương." },
  { word: "round-trip", meaning: "khứ hồi", example: "A round-trip ticket.", exampleVN: "Đi vé máy bay hai chiều." },
  { word: "insurance", meaning: "bảo hiểm", example: "Car insurance.", exampleVN: "Bảo hiểm xe tay máy." },
  { word: "well attended", meaning: "có nhiều người tham dự", example: "Was well attended.", exampleVN: "Ai cũng thích và tham gia." },
  { word: "sold out", meaning: "hết hàng / cháy vé", example: "Tickets are sold out.", exampleVN: "Cạn vé." },
  { word: "nonstop flight", meaning: "chuyến bay thẳng", example: "Nonstop flights.", exampleVN: "Chuyến bay trực tiếp đến." },
  { word: "economize", meaning: "tiết kiệm", example: "Economize on hotels.", exampleVN: "Tiết kiệm chi phí nhà trọ." },
  { word: "foot traffic", meaning: "lưu lượng người đi bộ", example: "High foot traffic.", exampleVN: "Càng nhiều người qua lại càng nổi." },
  { word: "shipment", meaning: "lô hàng, sự giao hàng", example: "Shipment of international foods.", exampleVN: "Kiện hàng xách tay nhập khẩu." },
  { word: "inspection", meaning: "sự kiểm tra, thanh tra", example: "A vehicle inspection.", exampleVN: "Theo dõi hiện trạng phương tiện." },
  { word: "access", meaning: "quyền truy cập, lối vào", example: "Visitor access.", exampleVN: "Cổng truy cập." },
  { word: "be advised", meaning: "xin lưu ý rằng", example: "Please be advised.", exampleVN: "Hãy cân nhắc một chút." },
  { word: "entrance", meaning: "lối vào, cổng vào", example: "The station entrance.", exampleVN: "Ngay ngoài điểm trung tâm hành khách." },
  { word: "direct", meaning: "hướng dẫn, chỉ đường", example: "Directing you to the new stop.", exampleVN: "Chỉ người khác đi đúng cách." },
  { word: "timetable", meaning: "thời khóa biểu, lịch trình", example: "Bus timetables.", exampleVN: "Thời gian xe qua trạm." },
  { word: "put into", meaning: "đặt cái gì vào/ bỏ cái gì vào", example: "Put the groceries into the car.", exampleVN: "Ném thức ăn vô hộc." },
  { word: "spread out", meaning: "trải ra, lan ra, tản ra", example: "Spread out the map.", exampleVN: "Quăng cái bản đồ lên bàn." },
  { word: "courtyard", meaning: "sân nhỏ, khuôn viên", example: "A beautiful inner courtyard.", exampleVN: "Có bồn phun nước ngoài hiên." },
  { word: "training session", meaning: "buổi tập huấn, buổi đào tạo", example: "The training sessions.", exampleVN: "Chỉ dành cho giờ luyện tập." },
  { word: "frequently", meaning: "thường xuyên", example: "Run frequently.", exampleVN: "Liên tục lặp đi lặp lại." },
  { word: "unfortunately", meaning: "không may", example: "Unfortunately, the flight...", exampleVN: "Kém vui là thế." },
  { word: "expire", meaning: "hết hạn", example: "Will expire next month.", exampleVN: "Thời gian cạn rồi." },
  { word: "requirement", meaning: "yêu cầu, điều kiện", example: "Size requirements.", exampleVN: "Giới hạn kích thước tối đa và nhỏ nhất." },
  { word: "expense", meaning: "chi phí", example: "Travel expenses.", exampleVN: "Số tiền đi tour." },
  { word: "reimbursement", meaning: "sự hoàn trả (tiền)", example: "Claim reimbursement.", exampleVN: "Nộp biên nhận đòi lấy kinh phí." },
  { word: "include", meaning: "bao gồm", example: "Include delivery charges.", exampleVN: "Của bạn gồm cả phí giao vận." },
  { word: "alignment", meaning: "sự căn chỉnh, thẳng hàng", example: "Proper alignment.", exampleVN: "Thăng bằng cân đối góc độ." },
  { word: "reservation", meaning: "sự đặt chỗ trước", example: "Confirm your reservation.", exampleVN: "Gật đầu với danh sách đợi." },
  { word: "surge pricing", meaning: "định giá tăng vọt", example: "Use surge pricing.", exampleVN: "Nhu cầu cao thì đẩy số cao lên." },
  { word: "route", meaning: "lộ trình, tuyến đường", example: "The fastest route.", exampleVN: "Lộ trình ngắn nhất lên tivi." },
  { word: "garage", meaning: "nhà xe, ga-ra", example: "In the garage.", exampleVN: "Bỏ vào bên trong hầm để xe gia đình." },
  { word: "luggage", meaning: "hành lý", example: "Placing her luggage.", exampleVN: "Vứt đồ xuống cân kí." },
  { word: "ticket", meaning: "vé", example: "Train tickets.", exampleVN: "Các tờ phiếu lưu thông đường sắt." },
  { word: "catering", meaning: "dịch vụ cung cấp đồ ăn", example: "The catering order.", exampleVN: "Toàn bộ nhóm chế biến lương thực." },
  { word: "commute", meaning: "đi lại (giữa nơi ở và nơi làm việc)", example: "Commuted by train.", exampleVN: "Nhiều lần đi vé phương tiện tập thể." },
  { word: "station", meaning: "nhà ga, trạm", example: "The station is on Mulberry Avenue.", exampleVN: "Hành lang dành riêng tại trạm trung chuyển." },
  { word: "additional", meaning: "thêm vào, bổ sung", example: "An additional charge.", exampleVN: "Trả thêm vài khoản cạn tiền." },
  { word: "confirm", meaning: "xác nhận", example: "Confirm your reservation.", exampleVN: "Tích vào để làm dấu." },
  { word: "tour", meaning: "tham quan", example: "Tour the new apartment building.", exampleVN: "Đi dạo bộ một thời gian quanh đây." },
  { word: "congested", meaning: "tắc nghẽn", example: "Routinely congested with vehicles.", exampleVN: "Tiếng rên vang vì xe kẹt tại thành phố." },
  { word: "impact", meaning: "tác động, ảnh hưởng", example: "Will impact your travel time.", exampleVN: "Sẽ dính chưởng chuyện giờ giấc lỡ hẹn." },
  { word: "hospitality", meaning: "ngành khách sạn/dịch vụ", example: "Hospitality conference.", exampleVN: "Trong một cuộc họp của các nhân nhà làm hình thức." },
  { word: "all-access", meaning: "truy cập toàn bộ", example: "All-access tour.", exampleVN: "Khách VIP tự có đặc điểm cho đi mọi nơi." },
  { word: "shuttle bus", meaning: "xe buýt đưa đón", example: "A shuttle bus will meet us.", exampleVN: "Những xe lữ hành đón người tại sân bay." }
];

export function processChunk24(): Word[] {
  return chunk24_raw.map((w, index) => {
    return {
      ...w,
      id: `c24_${index}`,
      pos: '(n/a)'
    };
  });
}
