import { Word } from './types';

export const chunkInter4: Word[] = [
  { id: 'i301', word: 'illiterate', meaning: 'mù chữ', example: 'Many people in that area are illiterate.', exampleVN: 'Nhiều người ở khu vực đó bị mù chữ.' },
  { id: 'i302', word: 'illuminate', meaning: 'chiếu sáng, giải thích rõ', example: 'The room was illuminated by candles.', exampleVN: 'Căn phòng được chiếu sáng bởi những ngọn nến.' },
  { id: 'i303', word: 'illustrate', meaning: 'minh họa', example: 'Use examples to illustrate your point.', exampleVN: 'Sử dụng các ví dụ để minh họa cho ý của bạn.' },
  { id: 'i304', word: 'imaginary', meaning: 'tưởng tượng, không có thật', example: 'The story is about an imaginary land.', exampleVN: 'Câu chuyện kể về một vùng đất tưởng tượng.' },
  { id: 'i305', word: 'imitate', meaning: 'bắt chước', example: 'Children often imitate their parents.', exampleVN: 'Trẻ em thường bắt chước cha mẹ chúng.' },
  { id: 'i306', word: 'immediate', meaning: 'lập tức', example: 'Take immediate action.', exampleVN: 'Hãy hành động lập tức.' },
  { id: 'i307', word: 'immense', meaning: 'bao la, khổng lồ', example: 'An immense amount of data.', exampleVN: 'Một lượng dữ liệu khổng lồ.' },
  { id: 'i308', word: 'immerse', meaning: 'đắm chìm', example: 'He immersed himself in his work.', exampleVN: 'Anh ấy đắm chìm trong công việc của mình.' },
  { id: 'i309', word: 'immigrant', meaning: 'người nhập cư', example: 'The country welcomes immigrants.', exampleVN: 'Đất nước này chào đón những người nhập cư.' },
  { id: 'i310', word: 'impact', meaning: 'tác động', example: 'The news had a huge impact on the market.', exampleVN: 'Tin tức đã có một tác động lớn đến thị trường.' },
  { id: 'i311', word: 'impatient', meaning: 'thiếu kiên nhẫn', example: 'Don\'t be so impatient.', exampleVN: 'Đừng thiếu kiên nhẫn như vậy.' },
  { id: 'i312', word: 'implement', meaning: 'thực hiện, triển khai', example: 'We need to implement the changes.', exampleVN: 'Chúng ta cần thực hiện những thay đổi.' },
  { id: 'i313', word: 'implication', meaning: 'hệ lụy, ý nghĩa', example: 'The implications of the new law.', exampleVN: 'Hệ lụy của bộ luật mới.' },
  { id: 'i314', word: 'import', meaning: 'nhập khẩu', example: 'We import coffee from Brazil.', exampleVN: 'Chúng tôi nhập khẩu cà phê từ Brazil.' },
  { id: 'i315', word: 'impose', meaning: 'áp đặt', example: 'The government imposed a new tax.', exampleVN: 'Chính phủ đã áp đặt một loại thuế mới.' },
  { id: 'i316', word: 'impress', meaning: 'gây ấn tượng', example: 'He impressed the interviewers.', exampleVN: 'Anh ấy đã gây ấn tượng với những người phỏng vấn.' },
  { id: 'i317', word: 'imprison', meaning: 'bỏ tù', example: 'He was imprisoned for fraud.', exampleVN: 'Anh ta bị bỏ tù vì tội gian lận.' },
  { id: 'i318', word: 'improve', meaning: 'cải thiện', example: 'We need to improve our service.', exampleVN: 'Chúng ta cần cải thiện dịch vụ của mình.' },
  { id: 'i319', word: 'impulse', meaning: 'sự thúc đẩy, bốc đồng', example: 'An impulse buy.', exampleVN: 'Một lần mua sắm bốc đồng.' },
  { id: 'i320', word: 'inadequate', meaning: 'không đầy đủ, thiếu', example: 'The facilities are inadequate.', exampleVN: 'Các cơ sở vật chất không đầy đủ.' },
  { id: 'i321', word: 'incentive', meaning: 'sự khuyến khích, ưu đãi', example: 'Tax incentives for small businesses.', exampleVN: 'Ưu đãi thuế cho các doanh nghiệp nhỏ.' },
  { id: 'i322', word: 'incidence', meaning: 'tỷ lệ mắc phải', example: 'The incidence of the disease is rising.', exampleVN: 'Tỷ lệ mắc bệnh đang tăng lên.' },
  { id: 'i323', word: 'incident', meaning: 'sự cố', example: 'The police are investigating the incident.', exampleVN: 'Cảnh sát đang điều tra sự cố.' },
  { id: 'i324', word: 'inclination', meaning: 'khuynh hướng', example: 'He has an inclination towards art.', exampleVN: 'Anh ấy có khuynh hướng thiên về nghệ thuật.' },
  { id: 'i325', word: 'include', meaning: 'bao gồm', example: 'The price includes tax.', exampleVN: 'Giá này bao gồm thuế.' },
  { id: 'i326', word: 'income', meaning: 'thu nhập', example: 'His monthly income is high.', exampleVN: 'Thu nhập hàng tháng của anh ấy cao.' },
  { id: 'i327', word: 'inconvenience', meaning: 'sự bất tiện', example: 'We apologize for the inconvenience.', exampleVN: 'Chúng tôi xin lỗi vì sự bất tiện này.' },
  { id: 'i328', word: 'incorporate', meaning: 'kết hợp, sáp nhập', example: 'We should incorporate new ideas.', exampleVN: 'Chúng ta nên kết hợp các ý tưởng mới.' },
  { id: 'i329', word: 'increase', meaning: 'tăng', example: 'Prices increase every year.', exampleVN: 'Giá cả tăng lên mỗi năm.' },
  { id: 'i330', word: 'incredible', meaning: 'đáng kinh ngạc', example: 'An incredible story.', exampleVN: 'Một câu chuyện đáng kinh ngạc.' },
  { id: 'i331', word: 'indifferent', meaning: 'thờ ơ', example: 'He was indifferent to the news.', exampleVN: 'Anh ta thờ ơ với tin tức.' },
  { id: 'i332', word: 'indigenous', meaning: 'bản địa', example: 'Indigenous people of Australia.', exampleVN: 'Người bản địa của Úc.' },
  { id: 'i333', word: 'indirect', meaning: 'gián tiếp', example: 'An indirect result.', exampleVN: 'Một kết quả gián tiếp.' },
  { id: 'i334', word: 'indispensable', meaning: 'không thể thiếu', example: 'Water is indispensable to life.', exampleVN: 'Nước là không thể thiếu đối với sự sống.' },
  { id: 'i335', word: 'individual', meaning: 'cá nhân', example: 'Each individual has their own style.', exampleVN: 'Mỗi cá nhân đều có phong cách riêng của mình.' },
  { id: 'i336', word: 'induce', meaning: 'xui khiến, gây ra', example: 'Smoking can induce heart disease.', exampleVN: 'Hút thuốc có thể gây ra bệnh tim.' },
  { id: 'i337', word: 'industry', meaning: 'ngành công nghiệp', example: 'The car industry is growing.', exampleVN: 'Ngành công nghiệp ô tô đang phát triển.' },
  { id: 'i338', word: 'inevitable', meaning: 'không thể tránh khỏi', example: 'Changes are inevitable.', exampleVN: 'Sự thay đổi là không thể tránh khỏi.' },
  { id: 'i339', word: 'infant', meaning: 'trẻ sơ sinh', example: 'Health care for infants.', exampleVN: 'Chăm sóc sức khỏe cho trẻ sơ sinh.' },
  { id: 'i340', word: 'infer', meaning: 'suy luận', example: 'What can you infer from this data?', exampleVN: 'Bạn có thể suy luận điều gì từ dữ liệu này?' },
  { id: 'i341', word: 'inferior', meaning: 'thấp kém hơn', example: 'The quality is inferior to the original.', exampleVN: 'Chất lượng thấp kém hơn so với nguyên bản.' },
  { id: 'i342', word: 'inflation', meaning: 'lạm phát', example: 'Inflation is rising rapidly.', exampleVN: 'Lạm phát đang tăng nhanh.' },
  { id: 'i343', word: 'influence', meaning: 'ảnh hưởng', example: 'He has a lot of influence on the team.', exampleVN: 'Anh ấy có nhiều ảnh hưởng đến nhóm.' },
  { id: 'i344', word: 'inform', meaning: 'thông báo', example: 'Please inform me of any changes.', exampleVN: 'Vui lòng thông báo cho tôi về bất kỳ thay đổi nào.' },
  { id: 'i345', word: 'informal', meaning: 'không chính thức, thân mật', example: 'An informal meeting.', exampleVN: 'Một cuộc họp không chính thức.' },
  { id: 'i346', word: 'ingredient', meaning: 'thành phần', example: 'Mix all the ingredients together.', exampleVN: 'Trộn tất cả các thành phần lại với nhau.' },
  { id: 'i347', word: 'inhabitant', meaning: 'cư dân', example: 'The inhabitants of the island.', exampleVN: 'Cư dân của hòn đảo.' },
  { id: 'i348', word: 'inherent', meaning: 'vốn có', example: 'Risk is inherent in business.', exampleVN: 'Rủi ro là vốn có trong kinh doanh.' },
  { id: 'i349', word: 'inherit', meaning: 'thừa kế', example: 'She inherited a fortune.', exampleVN: 'Cô ấy đã thừa kế một gia tài.' },
  { id: 'i350', word: 'inhibit', meaning: 'ngăn chặn, kiềm chế', example: 'Cold weather inhibits growth.', exampleVN: 'Thời tiết lạnh ngăn chặn sự phát triển.' },
  { id: 'i351', word: 'initial', meaning: 'ban đầu', example: 'My initial reaction was surprise.', exampleVN: 'Phản ứng ban đầu của tôi là ngạc nhiên.' },
  { id: 'i352', word: 'initiate', meaning: 'khởi xướng', example: 'Initiate a new project.', exampleVN: 'Khởi xướng một dự án mới.' },
  { id: 'i353', word: 'initiative', meaning: 'sáng kiến', example: 'Use your initiative.', exampleVN: 'Hãy sử dụng sáng kiến của bạn.' },
  { id: 'i354', word: 'inject', meaning: 'tiêm', example: 'The nurse injected the medicine.', exampleVN: 'Y tá đã tiêm thuốc.' },
  { id: 'i355', word: 'injure', meaning: 'làm bị thương', example: 'He was injured in the game.', exampleVN: 'Anh ta bị thương trong trận đấu.' },
  { id: 'i356', word: 'inner', meaning: 'bên trong', example: 'The inner circle.', exampleVN: 'Vòng tròn bên trong.' },
  { id: 'i357', word: 'innocent', meaning: 'vô tội', example: 'He was proven innocent.', exampleVN: 'Anh ta đã được chứng minh là vô tội.' },
  { id: 'i358', word: 'innovation', meaning: 'sự đổi mới', example: 'Innovation is key to success.', exampleVN: 'Sự đổi mới là chìa khóa của thành công.' },
  { id: 'i359', word: 'input', meaning: 'đầu vào, ý kiến đóng góp', example: 'We need your input on this.', exampleVN: 'Chúng tôi cần ý kiến đóng góp của bạn về việc này.' },
  { id: 'i360', word: 'inquire', meaning: 'hỏi, yêu cầu thông tin', example: 'I\'m calling to inquire about the job.', exampleVN: 'Tôi gọi để hỏi về công việc.' },
  { id: 'i361', word: 'insert', meaning: 'chèn', example: 'Insert the card into the slot.', exampleVN: 'Chèn thẻ vào khe.' },
  { id: 'i362', word: 'insight', meaning: 'sự thấu hiểu', example: 'Gain insight into the market.', exampleVN: 'Có được sự thấu hiểu về thị trường.' },
  { id: 'i363', word: 'insist', meaning: 'khăng khăng', example: 'He insisted on paying for lunch.', exampleVN: 'Anh ấy khăng khăng đòi trả tiền bữa trưa.' },
  { id: 'i364', word: 'inspect', meaning: 'kiểm tra', example: 'The building was inspected last week.', exampleVN: 'Tòa nhà đã được kiểm tra vào tuần trước.' },
  { id: 'i365', word: 'inspire', meaning: 'truyền cảm hứng', example: 'He inspires his team.', exampleVN: 'Anh ấy truyền cảm hứng cho nhóm của mình.' },
  { id: 'i366', word: 'install', meaning: 'lắp đặt', example: 'Install the new software.', exampleVN: 'Lắp đặt phần mềm mới.' },
  { id: 'i367', word: 'instance', meaning: 'ví dụ, trường hợp', example: 'For instance, look at this.', exampleVN: 'Ví dụ, hãy nhìn vào cái này.' },
  { id: 'i368', word: 'instinct', meaning: 'bản năng', example: 'Trust your instincts.', exampleVN: 'Hãy tin vào bản năng của bạn.' },
  { id: 'i369', word: 'institute', meaning: 'viện, thiết lập', example: 'The research institute.', exampleVN: 'Viện nghiên cứu.' },
  { id: 'i370', word: 'instruct', meaning: 'hướng dẫn', example: 'He instructed us to wait.', exampleVN: 'Anh ấy hướng dẫn chúng tôi đợi.' },
  { id: 'i371', word: 'instrument', meaning: 'nhạc cụ, dụng cụ', example: 'A musical instrument.', exampleVN: 'Một nhạc cụ.' },
  { id: 'i372', word: 'insufficient', meaning: 'không đủ', example: 'Insufficient evidence.', exampleVN: 'Không đủ bằng chứng.' },
  { id: 'i373', word: 'insulate', meaning: 'cách nhiệt, cách ly', example: 'Insulate the pipes.', exampleVN: 'Cách nhiệt các đường ống.' },
  { id: 'i374', word: 'insult', meaning: 'xúc phạm', example: 'Don\'t insult people.', exampleVN: 'Đừng xúc phạm mọi người.' },
  { id: 'i375', word: 'insurance', meaning: 'bảo hiểm', example: 'Health insurance.', exampleVN: 'Bảo hiểm y tế.' },
  { id: 'i376', word: 'intact', meaning: 'nguyên vẹn', example: 'The building remained intact after the storm.', exampleVN: 'Tòa nhà vẫn còn nguyên vẹn sau cơn bão.' },
  { id: 'i377', word: 'intake', meaning: 'lượng nạp vào', example: 'Daily calorie intake.', exampleVN: 'Lượng calo nạp vào hàng ngày.' },
  { id: 'i378', word: 'integral', meaning: 'thiết yếu, không thể thiếu', example: 'Communication is an integral part of the job.', exampleVN: 'Giao tiếp là một phần thiết yếu của công việc.' },
  { id: 'i379', word: 'integrate', meaning: 'tích hợp', example: 'Integrate the new system.', exampleVN: 'Tích hợp hệ thống mới.' },
  { id: 'i380', word: 'integrity', meaning: 'chính trực', example: 'A man of integrity.', exampleVN: 'Một người đàn ông chính trực.' },
  { id: 'i381', word: 'intellectual', meaning: 'thuộc về trí tuệ', example: 'Intellectual property.', exampleVN: 'Sở hữu trí tuệ.' },
  { id: 'i382', word: 'intelligent', meaning: 'thông minh', example: 'She is an intelligent student.', exampleVN: 'Cô ấy là một học sinh thông minh.' },
  { id: 'i383', word: 'intend', meaning: 'dự định', example: 'I intend to go next week.', exampleVN: 'Tôi dự định sẽ đi vào tuần tới.' },
  { id: 'i384', word: 'intense', meaning: 'mạnh mẽ, dữ dội', example: 'Intense heat.', exampleVN: 'Cái nóng dữ dội.' },
  { id: 'i385', word: 'intent', meaning: 'ý định', example: 'With the intent to defraud.', exampleVN: 'Với ý định gian lận.' },
  { id: 'i386', word: 'interact', meaning: 'tương tác', example: 'How do the molecules interact?', exampleVN: 'Các phân tử tương tác với nhau như thế nào?' },
  { id: 'i387', word: 'interfere', meaning: 'can thiệp', example: 'Don\'t interfere in my business.', exampleVN: 'Đừng can thiệp vào việc của tôi.' },
  { id: 'i388', word: 'interior', meaning: 'nội thất, bên trong', example: 'Interior design.', exampleVN: 'Thiết kế nội thất.' },
  { id: 'i389', word: 'intermediate', meaning: 'trung cấp', example: 'An intermediate course.', exampleVN: 'Một khóa học trung cấp.' },
  { id: 'i390', word: 'internal', meaning: 'nội bộ', example: 'Internal audit.', exampleVN: 'Kiểm toán nội bộ.' },
  { id: 'i391', word: 'interpret', meaning: 'giải thích, phiên dịch', example: 'Can you interpret this for me?', exampleVN: 'Bạn có thể giải thích cái này cho tôi không?' },
  { id: 'i392', word: 'interrupt', meaning: 'ngắt lời', example: 'Don\'t interrupt me.', exampleVN: 'Đừng ngắt lời tôi.' },
  { id: 'i393', word: 'interval', meaning: 'khoảng thời gian', example: 'At regular intervals.', exampleVN: 'Theo định kỳ.' },
  { id: 'i394', word: 'intervene', meaning: 'can thiệp', example: 'The government intervened in the crisis.', exampleVN: 'Chính phủ đã can thiệp vào cuộc khủng hoảng.' },
  { id: 'i395', word: 'interview', meaning: 'phỏng vấn', example: 'A job interview.', exampleVN: 'Một cuộc phỏng vấn xin việc.' },
  { id: 'i396', word: 'intimate', meaning: 'thân mật', example: 'An intimate dinner.', exampleVN: 'Một bữa tối thân mật.' },
  { id: 'i397', word: 'intimidate', meaning: 'hăm dọa', example: 'Don\'t let them intimidate you.', exampleVN: 'Đừng để họ hăm dọa bạn.' },
  { id: 'i398', word: 'intrigue', meaning: 'hấp dẫn, mưu đồ', example: 'The plot intrigues me.', exampleVN: 'Cốt truyện làm tôi thấy hấp dẫn.' },
  { id: 'i399', word: 'intrinsic', meaning: 'bản chất', example: 'Intrinsic value.', exampleVN: 'Giá trị bản chất.' },
  { id: 'i400', word: 'introduce', meaning: 'giới thiệu', example: 'Let me introduce myself.', exampleVN: 'Để tôi tự giới thiệu.' },
  { id: 'i401', word: 'invade', meaning: 'xâm lược', example: 'Invade a country.', exampleVN: 'Xâm lược một quốc gia.' },
  { id: 'i402', word: 'invalid', meaning: 'vô hiệu, người tàn tật', example: 'The contract is invalid.', exampleVN: 'Hợp đồng vô hiệu.' },
  { id: 'i403', word: 'invaluable', meaning: 'vô giá', example: 'Your help was invaluable.', exampleVN: 'Sự giúp đỡ của bạn là vô giá.' },
  { id: 'i404', word: 'invasion', meaning: 'sự xâm lược', example: 'The invasion of privacy.', exampleVN: 'Sự xâm phạm quyền riêng tư.' },
  { id: 'i405', word: 'inventory', meaning: 'hàng tồn kho', example: 'Take an inventory.', exampleVN: 'Kiểm kê hàng tồn kho.' },
  { id: 'i406', word: 'invest', meaning: 'đầu tư', example: 'Invest in stocks.', exampleVN: 'Đầu tư vào cổ phiếu.' },
  { id: 'i407', word: 'investigate', meaning: 'điều tra', example: 'Investigate the crime.', exampleVN: 'Điều tra tội phạm.' },
  { id: 'i408', word: 'investment', meaning: 'khoản đầu tư', example: 'A safe investment.', exampleVN: 'Một khoản đầu tư an toàn.' },
  { id: 'i409', word: 'invisible', meaning: 'vô hình', example: 'Invisible ink.', exampleVN: 'Mực vô hình.' },
  { id: 'i410', word: 'invoice', meaning: 'hóa đơn', example: 'Send the invoice.', exampleVN: 'Gửi hóa đơn.' },
  { id: 'i411', word: 'involve', meaning: 'bao gồm, liên quan', example: 'The job involves travel.', exampleVN: 'Công việc bao gồm việc đi lại.' },
  { id: 'i412', word: 'ironic', meaning: 'mỉa mai', example: 'It\'s ironic that...', exampleVN: 'Thật mỉa mai là...' },
  { id: 'i413', word: 'irrelevant', meaning: 'không liên quan', example: 'Irrelevant information.', exampleVN: 'Thông tin không liên quan.' },
  { id: 'i414', word: 'isolate', meaning: 'cô lập', example: 'Isolate the virus.', exampleVN: 'Cô lập virus.' },
  { id: 'i415', word: 'issue', meaning: 'vấn đề, phát hành', example: 'A political issue.', exampleVN: 'Một vấn đề chính trị.' },
  { id: 'i416', word: 'item', meaning: 'mặt hàng', example: 'An expensive item.', exampleVN: 'Một mặt hàng đắt tiền.' },
  { id: 'i417', word: 'itinerary', meaning: 'lịch trình', example: 'A travel itinerary.', exampleVN: 'Lịch trình du lịch.' },
  { id: 'i418', word: 'jail', meaning: 'nhà tù', example: 'Go to jail.', exampleVN: 'Đi tù.' },
  { id: 'i419', word: 'jealous', meaning: 'ghen tị', example: 'He is jealous of her success.', exampleVN: 'Anh ta ghen tị với thành công của cô ấy.' },
  { id: 'i420', word: 'jet', meaning: 'máy bay phản lực', example: 'A private jet.', exampleVN: 'Một chiếc máy bay riêng.' },
  { id: 'i421', word: 'joint', meaning: 'chung, khớp', example: 'A joint venture.', exampleVN: 'Một liên doanh.' },
  { id: 'i422', word: 'journal', meaning: 'tạp chí, nhật ký', example: 'A medical journal.', exampleVN: 'Một tạp chí y khoa.' },
  { id: 'i423', word: 'journey', meaning: 'hành trình', example: 'A long journey.', exampleVN: 'Một hành trình dài.' },
  { id: 'i424', word: 'judge', meaning: 'thẩm phán, đánh giá', example: 'The judge\'s decision.', exampleVN: 'Quyết định của thẩm phán.' },
  { id: 'i425', word: 'judicial', meaning: 'thuộc về tư pháp', example: 'The judicial system.', exampleVN: 'Hệ thống tư pháp.' },
  { id: 'i426', word: 'junior', meaning: 'cấp thấp hơn, trẻ hơn', example: 'A junior employee.', exampleVN: 'Một nhân viên cấp dưới.' },
  { id: 'i427', word: 'jury', meaning: 'bồi thẩm đoàn', example: 'The jury reached a verdict.', exampleVN: 'Bồi thẩm đoàn đã đưa ra phán quyết.' },
  { id: 'i428', word: 'justice', meaning: 'công lý', example: 'Seek justice.', exampleVN: 'Tìm kiếm công lý.' },
  { id: 'i429', word: 'justify', meaning: 'biện minh', example: 'Justify the costs.', exampleVN: 'Biện minh cho các chi phí.' },
  { id: 'i430', word: 'keen', meaning: 'hăng hái, sắc sảo', example: 'He is keen to start.', exampleVN: 'Anh ấy rất hăng hái bắt đầu.' },
  { id: 'i431', word: 'label', meaning: 'nhãn', example: 'Read the label.', exampleVN: 'Đọc nhãn.' },
  { id: 'i432', word: 'labor', meaning: 'lao động', example: 'Manual labor.', exampleVN: 'Lao động tay chân.' },
  { id: 'i433', word: 'laboratory', meaning: 'phòng thí nghiệm', example: 'A research laboratory.', exampleVN: 'Một phòng thí nghiệm nghiên cứu.' },
  { id: 'i434', word: 'lack', meaning: 'thiếu', example: 'Lack of money.', exampleVN: 'Thiếu tiền.' },
  { id: 'i435', word: 'ladder', meaning: 'cái thang', example: 'Climb the career ladder.', exampleVN: 'Leo lên nấc thang sự nghiệp.' },
  { id: 'i436', word: 'landlord', meaning: 'chủ nhà', example: 'The landlord is nice.', exampleVN: 'Chủ nhà rất tốt.' },
  { id: 'i437', word: 'landscape', meaning: 'phong cảnh', example: 'A beautiful landscape.', exampleVN: 'Một phong cảnh đẹp.' },
  { id: 'i438', word: 'laptop', meaning: 'máy tính xách tay', example: 'I need a new laptop.', exampleVN: 'Tôi cần một chiếc máy tính xách tay mới.' },
  { id: 'i439', word: 'laser', meaning: 'la-ze', example: 'Laser surgery.', exampleVN: 'Phẫu thuật la-ze.' },
  { id: 'i440', word: 'last', meaning: 'cuối cùng, kéo dài', example: 'The meeting lasted two hours.', exampleVN: 'Cuộc họp kéo dài hai giờ.' },
  { id: 'i441', word: 'launch', meaning: 'ra mắt, phóng', example: 'Launch a new product.', exampleVN: 'Ra mắt một sản phẩm mới.' },
  { id: 'i442', word: 'laundry', meaning: 'việc giặt ủi', example: 'Do the laundry.', exampleVN: 'Giặt quần áo.' },
  { id: 'i443', word: 'lawsuit', meaning: 'vụ kiện', example: 'Win a lawsuit.', exampleVN: 'Thắng một vụ kiện.' },
  { id: 'i444', word: 'lawyer', meaning: 'luật sư', example: 'Talk to a lawyer.', exampleVN: 'Nói chuyện với luật sư.' },
  { id: 'i445', word: 'layer', meaning: 'lớp', example: 'A layer of paint.', exampleVN: 'Một lớp sơn.' },
  { id: 'i446', word: 'layout', meaning: 'bố cục', example: 'The layout of the office.', exampleVN: 'Bố cục của văn phòng.' },
  { id: 'i447', word: 'lead', meaning: 'dẫn đầu, chì', example: 'Lead the team.', exampleVN: 'Dẫn dắt nhóm.' },
  { id: 'i448', word: 'leaf', meaning: 'lá', example: 'A green leaf.', exampleVN: 'Một chiếc lá xanh.' },
  { id: 'i449', word: 'leak', meaning: 'rò rỉ', example: 'A water leak.', exampleVN: 'Rò rỉ nước.' },
  { id: 'i450', word: 'lean', meaning: 'nghiêng, gầy', example: 'Lean against the wall.', exampleVN: 'Dựa vào tường.' },
];

export const processChunkInter4 = () => {
  return chunkInter4.map(w => ({ ...w, pos: '(n)' as string }));
};
