import { Word } from './types';

export const chunkEasy: Word[] = [
  { id: 'e1', word: 'apple', meaning: 'quả táo', example: 'I eat an apple every morning.', exampleVN: 'Tôi ăn một quả táo mỗi sáng.' },
  { id: 'e2', word: 'bike', meaning: 'xe đạp', example: 'He rides his bike to school.', exampleVN: 'Anh ấy đi xe đạp đến trường.' },
  { id: 'e3', word: 'book', meaning: 'quyển sách', example: 'I like reading this book.', exampleVN: 'Tôi thích đọc cuốn sách này.' },
  { id: 'e4', word: 'bus', meaning: 'xe buýt', example: 'The bus arrives at 8 AM.', exampleVN: 'Xe buýt đến lúc 8 giờ sáng.' },
  { id: 'e5', word: 'car', meaning: 'xe hơi', example: 'My father has a blue car.', exampleVN: 'Bố tôi có một chiếc xe hơi màu xanh.' },
  { id: 'e6', word: 'cat', meaning: 'con mèo', example: 'The cat is sleeping on the sofa.', exampleVN: 'Con mèo đang ngủ trên ghế sofa.' },
  { id: 'e7', word: 'city', meaning: 'thành phố', example: 'Ho Chi Minh City is very big.', exampleVN: 'Thành phố Hồ Chí Minh rất lớn.' },
  { id: 'e8', word: 'cold', meaning: 'lạnh', example: 'It is very cold in winter.', exampleVN: 'Trời rất lạnh vào mùa đông.' },
  { id: 'e9', word: 'coffee', meaning: 'cà phê', example: 'I drink coffee every day.', exampleVN: 'Tôi uống cà phê mỗi ngày.' },
  { id: 'e10', word: 'country', meaning: 'quốc gia, nông thôn', example: 'I love my country.', exampleVN: 'Tôi yêu đất nước mình.' },
  { id: 'e11', word: 'day', meaning: 'ngày', example: 'Today is a beautiful day.', exampleVN: 'Hôm nay là một ngày đẹp trời.' },
  { id: 'e12', word: 'dog', meaning: 'con chó', example: 'My dog is very friendly.', exampleVN: 'Con chó của tôi rất thân thiện.' },
  { id: 'e13', word: 'drink', meaning: 'uống', example: 'Drink more water.', exampleVN: 'Hãy uống nhiều nước hơn.' },
  { id: 'e14', word: 'eat', meaning: 'ăn', example: 'I eat breakfast at 7 AM.', exampleVN: 'Tôi ăn sáng lúc 7 giờ sáng.' },
  { id: 'e15', word: 'family', meaning: 'gia đình', example: 'I live with my family.', exampleVN: 'Tôi sống với gia đình mình.' },
  { id: 'e16', word: 'father', meaning: 'bố', example: 'My father is a teacher.', exampleVN: 'Bố tôi là giáo viên.' },
  { id: 'e17', word: 'fish', meaning: 'con cá', example: 'Goldfish live in water.', exampleVN: 'Cá vàng sống dưới nước.' },
  { id: 'e18', word: 'food', meaning: 'thức ăn', example: 'Vietnamese food is delicious.', exampleVN: 'Thức ăn Việt Nam rất ngon.' },
  { id: 'e19', word: 'friend', meaning: 'bạn bè', example: 'She is my best friend.', exampleVN: 'Cô ấy là bạn thân nhất của tôi.' },
  { id: 'e20', word: 'fruit', meaning: 'trái cây', example: 'Eat more fresh fruit.', exampleVN: 'Hãy ăn thêm trái cây tươi.' },
  { id: 'e21', word: 'girl', meaning: 'cô gái', example: 'The girl is wearing a red hat.', exampleVN: 'Cô gái đang đội một chiếc mũ màu đỏ.' },
  { id: 'e22', word: 'good', meaning: 'tốt', example: 'Have a good day!', exampleVN: 'Chúc một ngày tốt lành!' },
  { id: 'e23', word: 'happy', meaning: 'hạnh phúc', example: 'I am so happy today.', exampleVN: 'Hôm nay tôi rất hạnh phúc.' },
  { id: 'e24', word: 'home', meaning: 'nhà', example: 'I go home after work.', exampleVN: 'Tôi về nhà sau giờ làm việc.' },
  { id: 'e25', word: 'hot', meaning: 'nóng', example: 'The tea is very hot.', exampleVN: 'Trà rất nóng.' },
  { id: 'e26', word: 'house', meaning: 'ngôi nhà', example: 'Their house is big.', exampleVN: 'Ngôi nhà của họ rất lớn.' },
  { id: 'e27', word: 'learn', meaning: 'học', example: 'I want to learn English.', exampleVN: 'Tôi muốn học tiếng Anh.' },
  { id: 'e28', word: 'milk', meaning: 'sữa', example: 'Do you want some milk?', exampleVN: 'Bạn có muốn uống chút sữa không?' },
  { id: 'e29', word: 'money', meaning: 'tiền', example: 'I need some money.', exampleVN: 'Tôi cần một ít tiền.' },
  { id: 'e30', word: 'morning', meaning: 'buổi sáng', example: 'I wake up early in the morning.', exampleVN: 'Tôi thức dậy sớm vào buổi sáng.' },
  { id: 'e31', word: 'mother', meaning: 'mẹ', example: 'My mother is cooking.', exampleVN: 'Mẹ tôi đang nấu ăn.' },
  { id: 'e32', word: 'name', meaning: 'tên', example: 'My name is Bao.', exampleVN: 'Tên tôi là Bảo.' },
  { id: 'e33', word: 'new', meaning: 'mới', example: 'I bought a new phone.', exampleVN: 'Tôi đã mua một chiếc điện thoại mới.' },
  { id: 'e34', word: 'night', meaning: 'ban đêm', example: 'Good night!', exampleVN: 'Chúc ngủ ngon!' },
  { id: 'e35', word: 'old', meaning: 'cũ, già', example: 'This is an old car.', exampleVN: 'Đây là một chiếc xe hơi cũ.' },
  { id: 'e36', word: 'pen', meaning: 'bút mực', example: 'Can I borrow your pen?', exampleVN: 'Tôi có thể mượn bút của bạn không?' },
  { id: 'e37', word: 'phone', meaning: 'điện thoại', example: 'The phone is ringing.', exampleVN: 'Điện thoại đang reo.' },
  { id: 'e38', word: 'price', meaning: 'giá cả', example: 'What is the price of this bag?', exampleVN: 'Giá của chiếc túi này là bao nhiêu?' },
  { id: 'e39', word: 'read', meaning: 'đọc', example: 'I read the news every day.', exampleVN: 'Tôi đọc tin tức mỗi ngày.' },
  { id: 'e40', word: 'rice', meaning: 'gạo, cơm', example: 'Vietnamese people eat rice.', exampleVN: 'Người Việt Nam ăn cơm.' },
  { id: 'e41', word: 'road', meaning: 'con đường', example: 'The road is very busy.', exampleVN: 'Con đường rất đông đúc.' },
  { id: 'e42', word: 'room', meaning: 'phòng', example: 'My room is clean.', exampleVN: 'Phòng của tôi sạch sẽ.' },
  { id: 'e43', word: 'school', meaning: 'trường học', example: 'I go to school at 7:30.', exampleVN: 'Tôi đi học lúc 7:30.' },
  { id: 'e44', word: 'shop', meaning: 'cửa hàng', example: 'I am going to the shop.', exampleVN: 'Tôi đang đi đến cửa hàng.' },
  { id: 'e45', word: 'small', meaning: 'nhỏ', example: 'This box is very small.', exampleVN: 'Chiếc hộp này rất nhỏ.' },
  { id: 'e46', word: 'student', meaning: 'học sinh', example: 'She is a good student.', exampleVN: 'Cô ấy là một học sinh giỏi.' },
  { id: 'e47', word: 'tea', meaning: 'trà', example: 'Do you like green tea?', exampleVN: 'Bạn có thích trà xanh không?' },
  { id: 'e48', word: 'teacher', meaning: 'giáo viên', example: 'The teacher is very kind.', exampleVN: 'Giáo viên rất tử tế.' },
  { id: 'e49', word: 'time', meaning: 'thời gian', example: 'What time is it?', exampleVN: 'Mấy giờ rồi?' },
  { id: 'e50', word: 'today', meaning: 'hôm nay', example: 'Today is Monday.', exampleVN: 'Hôm nay là thứ Hai.' },
  { id: 'e51', word: 'water', meaning: 'nước', example: 'Please give me some water.', exampleVN: 'Vui lòng cho tôi một ít nước.' },
  { id: 'e52', word: 'week', meaning: 'tuần', example: 'There are seven days in a week.', exampleVN: 'Có bảy ngày trong một tuần.' },
  { id: 'e53', word: 'work', meaning: 'làm việc', example: 'I work from 8 AM to 5 PM.', exampleVN: 'Tôi làm việc từ 8 giờ sáng đến 5 giờ chiều.' },
  { id: 'e54', word: 'write', meaning: 'viết', example: 'Write your name here.', exampleVN: 'Viết tên của bạn ở đây.' },
  { id: 'e55', word: 'year', meaning: 'năm', example: 'Happy New Year!', exampleVN: 'Chúc mừng năm mới!' },
  { id: 'e56', word: 'because', meaning: 'vì, bởi vì', example: 'I am late because of the rain.', exampleVN: 'Tôi đến muộn vì trời mưa.' },
  { id: 'e57', word: 'but', meaning: 'nhưng', example: 'I like coffee but I don\'t like tea.', exampleVN: 'Tôi thích cà phê nhưng không thích trà.' },
  { id: 'e58', word: 'so', meaning: 'vì vậy, cho nên', example: 'It was raining, so we stayed home.', exampleVN: 'Trời đang mưa, vì vậy chúng tôi đã ở nhà.' },
  { id: 'e59', word: 'and', meaning: 'và', example: 'I have a pen and a book.', exampleVN: 'Tôi có một chiếc bút và một cuốn sách.' },
  { id: 'e60', word: 'with', meaning: 'với', example: 'I go to school with my friends.', exampleVN: 'Tôi đi học với bạn bè.' },
  { id: 'e61', word: 'without', meaning: 'không có, thiếu', example: 'I cannot live without water.', exampleVN: 'Tôi không thể sống thiếu nước.' },
  { id: 'e62', word: 'between', meaning: 'ở giữa', example: 'The bank is between the shop and the cafe.', exampleVN: 'Ngân hàng ở giữa cửa hàng và quán cà phê.' },
  { id: 'e63', word: 'near', meaning: 'gần', example: 'I live near the station.', exampleVN: 'Tôi sống gần nhà ga.' },
  { id: 'e64', word: 'far', meaning: 'xa', example: 'The airport is very far.', exampleVN: 'Sân bay rất xa.' },
  { id: 'e65', word: 'listen', meaning: 'nghe', example: 'Listen to the music.', exampleVN: 'Nghe nhạc.' },
  { id: 'e66', word: 'speak', meaning: 'nói', example: 'Can you speak English?', exampleVN: 'Bạn có thể nói tiếng Anh không?' },
  { id: 'e67', word: 'walk', meaning: 'đi bộ', example: 'I walk to the park.', exampleVN: 'Tôi đi bộ đến công viên.' },
  { id: 'e68', word: 'run', meaning: 'chạy', example: 'Don\'t run in the house.', exampleVN: 'Đừng chạy trong nhà.' },
  { id: 'e69', word: 'sleep', meaning: 'ngủ', example: 'I sleep 8 hours a night.', exampleVN: 'Tôi ngủ 8 tiếng mỗi đêm.' },
  { id: 'e70', word: 'open', meaning: 'mở', example: 'Please open the door.', exampleVN: 'Vui lòng mở cửa.' },
  { id: 'e71', word: 'close', meaning: 'đóng', example: 'Close the window, please.', exampleVN: 'Làm ơn đóng cửa sổ lại.' },
  { id: 'e72', word: 'buy', meaning: 'mua', example: 'I want to buy some clothes.', exampleVN: 'Tôi muốn mua một ít quần áo.' },
  { id: 'e73', word: 'sell', meaning: 'bán', example: 'They sell fresh bread.', exampleVN: 'Họ bán bánh mì tươi.' },
  { id: 'e74', word: 'give', meaning: 'cho, tặng', example: 'Give me your hand.', exampleVN: 'Đưa tay cho tôi.' },
  { id: 'e75', word: 'take', meaning: 'lấy, cầm, đưa đi', example: 'Take an umbrella with you.', exampleVN: 'Hãy mang theo ô bên mình.' },
  { id: 'e76', word: 'help', meaning: 'giúp đỡ', example: 'Can you help me?', exampleVN: 'Bạn có thể giúp tôi không?' },
  { id: 'e77', word: 'look', meaning: 'nhìn', example: 'Look at that bird!', exampleVN: 'Hãy nhìn con chim kia kìa!' },
  { id: 'e78', word: 'find', meaning: 'tìm thấy', example: 'I can\'t find my keys.', exampleVN: 'Tôi không thể tìm thấy chìa khóa của mình.' },
  { id: 'e79', word: 'lost', meaning: 'mất, lạc', example: 'I lost my wallet.', exampleVN: 'Tôi bị mất ví.' },
  { id: 'e80', word: 'see', meaning: 'nhìn thấy', example: 'I see a rainbow.', exampleVN: 'Tôi thấy cầu vồng.' },
  { id: 'e81', word: 'hear', meaning: 'nghe thấy', example: 'Can you hear the noise?', exampleVN: 'Bạn có nghe thấy tiếng ồn không?' },
  { id: 'e82', word: 'understand', meaning: 'hiểu', example: 'I don\'t understand this question.', exampleVN: 'Tôi không hiểu câu hỏi này.' },
  { id: 'e83', word: 'think', meaning: 'suy nghĩ', example: 'What do you think?', exampleVN: 'Bạn nghĩ sao?' },
  { id: 'e84', word: 'know', meaning: 'biết', example: 'I know the answer.', exampleVN: 'Tôi biết câu trả lời.' },
  { id: 'e85', word: 'believe', meaning: 'tin tưởng', example: 'I believe you.', exampleVN: 'Tôi tin bạn.' },
  { id: 'e86', word: 'remember', meaning: 'nhớ', example: 'Do you remember me?', exampleVN: 'Bạn có nhớ tôi không?' },
  { id: 'e87', word: 'forget', meaning: 'quên', example: 'Don\'t forget your bag.', exampleVN: 'Đừng quên túi xách của bạn.' },
  { id: 'e88', word: 'need', meaning: 'cần', example: 'I need some help.', exampleVN: 'Tôi cần một chút giúp đỡ.' },
  { id: 'e89', word: 'want', meaning: 'muốn', example: 'I want an ice cream.', exampleVN: 'Tôi muốn một cây kem.' },
  { id: 'e90', word: 'like', meaning: 'thích', example: 'I like this music.', exampleVN: 'Tôi thích bản nhạc này.' },
  { id: 'e91', word: 'love', meaning: 'yêu', example: 'I love my family.', exampleVN: 'Tôi yêu gia đình mình.' },
  { id: 'e92', word: 'hate', meaning: 'ghét', example: 'I hate spiders.', exampleVN: 'Tôi ghét nhện.' },
  { id: 'e93', word: 'fast', meaning: 'nhanh', example: 'He is a fast runner.', exampleVN: 'Anh ấy là một người chạy nhanh.' },
  { id: 'e94', word: 'slow', meaning: 'chậm', example: 'The turtle is very slow.', exampleVN: 'Con rùa rất chậm.' },
  { id: 'e95', word: 'heavy', meaning: 'nặng', example: 'This box is too heavy.', exampleVN: 'Chiếc hộp này quá nặng.' },
  { id: 'e96', word: 'light', meaning: 'nhẹ, ánh sáng', example: 'The bag is very light.', exampleVN: 'Chiếc túi rất nhẹ.' },
  { id: 'e97', word: 'easy', meaning: 'dễ dàng', example: 'The test was easy.', exampleVN: 'Bài kiểm tra thật dễ.' },
  { id: 'e98', word: 'hard', meaning: 'khó khăn, cứng', example: 'Life can be hard.', exampleVN: 'Cuộc sống có thể khó khăn.' },
  { id: 'e99', word: 'rich', meaning: 'giàu có', example: 'He is a rich businessman.', exampleVN: 'Anh ấy là một doanh nhân giàu có.' },
  { id: 'e100', word: 'poor', meaning: 'nghèo', example: 'We should help poor people.', exampleVN: 'Chúng ta nên giúp đỡ những người nghèo.' },
  { id: 'e101', word: 'clean', meaning: 'sạch sẽ', example: 'Your hands are clean.', exampleVN: 'Tay bạn sạch sẽ.' },
  { id: 'e102', word: 'dirty', meaning: 'bẩn', example: 'The floor is dirty.', exampleVN: 'Sàn nhà bị bẩn.' },
  { id: 'e103', word: 'cheap', meaning: 'rẻ', example: 'The tickets are very cheap.', exampleVN: 'Vé rất rẻ.' },
  { id: 'e104', word: 'expensive', meaning: 'đắt tiền', example: 'That car is too expensive.', exampleVN: 'Chiếc xe đó quá đắt.' },
  { id: 'e105', word: 'hungry', meaning: 'đói', example: 'I am so hungry.', exampleVN: 'Tôi đói quá.' },
  { id: 'e106', word: 'thirsty', meaning: 'khát', example: 'I am thirsty after running.', exampleVN: 'Tôi khát sau khi chạy.' },
  { id: 'e107', word: 'tired', meaning: 'mệt mỏi', example: 'I am tired after work.', exampleVN: 'Tôi mệt mỏi sau khi làm việc.' },
  { id: 'e108', word: 'angry', meaning: 'tức giận', example: 'Don\'t be angry with me.', exampleVN: 'Đừng giận tôi nhé.' },
  { id: 'e109', word: 'sad', meaning: 'buồn', example: 'The movie was very sad.', exampleVN: 'Bộ phim rất buồn.' },
  { id: 'e110', word: 'beautiful', meaning: 'đẹp', example: 'She is a beautiful girl.', exampleVN: 'Cô ấy là một cô gái xinh đẹp.' },
  { id: 'e111', word: 'both', meaning: 'cả hai', example: 'I like both of them.', exampleVN: 'Tôi thích cả hai người họ.' },
  { id: 'e112', word: 'between', meaning: 'ở giữa (2 vật/người)', example: 'Sit between your parents.', exampleVN: 'Hãy ngồi giữa bố mẹ con.' },
  { id: 'e113', word: 'fall', meaning: 'ngã, rơi, mùa thu', example: 'Be careful, don\'t fall.', exampleVN: 'Cẩn thận, đừng để ngã.' },
  { id: 'e114', word: 'leave', meaning: 'rời đi, bỏ lại', example: 'I leave for work at 8.', exampleVN: 'Tôi đi làm lúc 8 giờ.' },
  { id: 'e115', word: 'tomorrow', meaning: 'ngày mai', example: 'See you tomorrow!', exampleVN: 'Hẹn gặp lại vào ngày mai!' },
  { id: 'e116', word: 'yesterday', meaning: 'ngày hôm qua', example: 'I saw him yesterday.', exampleVN: 'Tôi đã thấy anh ấy ngày hôm qua.' },
  { id: 'e117', word: 'early', meaning: 'sớm', example: 'I woke up early.', exampleVN: 'Tôi đã thức dậy sớm.' },
  { id: 'e118', word: 'late', meaning: 'muộn', example: 'Don\'t be late for class.', exampleVN: 'Đừng đi học muộn.' },
  { id: 'e119', word: 'long', meaning: 'dài', example: 'She has long hair.', exampleVN: 'Cô ấy có mái tóc dài.' },
  { id: 'e120', word: 'short', meaning: 'ngắn, thấp', example: 'He is short but strong.', exampleVN: 'Anh ấy thấp nhưng khỏe.' },
  { id: 'e121', word: 'office', meaning: 'văn phòng', example: 'I work in an office.', exampleVN: 'Tôi làm việc ở văn phòng.' },
  { id: 'e122', word: 'meeting', meaning: 'cuộc họp', example: 'We have a meeting at 10.', exampleVN: 'Chúng tôi có cuộc họp lúc 10 giờ.' },
  { id: 'e123', word: 'job', meaning: 'công việc', example: 'He got a new job.', exampleVN: 'Anh ấy có công việc mới.' },
  { id: 'e124', word: 'boss', meaning: 'sếp', example: 'My boss is very nice.', exampleVN: 'Sếp của tôi rất tốt.' },
  { id: 'e125', word: 'email', meaning: 'thư điện tử', example: 'Please send me an email.', exampleVN: 'Hãy gửi email cho tôi.' },
  { id: 'e126', word: 'table', meaning: 'bàn', example: 'Put it on the table.', exampleVN: 'Đặt nó lên bàn.' },
  { id: 'e127', word: 'chair', meaning: 'ghế', example: 'Sit on the chair.', exampleVN: 'Ngồi lên ghế.' },
  { id: 'e128', word: 'door', meaning: 'cửa', example: 'Please close the door.', exampleVN: 'Làm ơn đóng cửa.' },
  { id: 'e129', word: 'window', meaning: 'cửa sổ', example: 'Open the window.', exampleVN: 'Mở cửa sổ.' },
  { id: 'e130', word: 'computer', meaning: 'máy tính', example: 'I use a computer every day.', exampleVN: 'Tôi dùng máy tính mỗi ngày.' },
  { id: 'e131', word: 'question', meaning: 'câu hỏi', example: 'Do you have a question?', exampleVN: 'Bạn có câu hỏi nào không?' },
  { id: 'e132', word: 'answer', meaning: 'câu trả lời', example: 'I know the answer.', exampleVN: 'Tôi biết câu trả lời.' },
  { id: 'e133', word: 'problem', meaning: 'vấn đề', example: 'There is a problem.', exampleVN: 'Có một vấn đề.' },
  { id: 'e134', word: 'start', meaning: 'bắt đầu', example: 'Let us start now.', exampleVN: 'Hãy bắt đầu ngay.' },
  { id: 'e135', word: 'stop', meaning: 'dừng lại', example: 'Stop the car.', exampleVN: 'Dừng xe lại.' },
  { id: 'e136', word: 'finish', meaning: 'kết thúc', example: 'I will finish soon.', exampleVN: 'Tôi sẽ hoàn thành sớm.' },
  { id: 'e137', word: 'wait', meaning: 'chờ đợi', example: 'Wait for me.', exampleVN: 'Chờ tôi với.' },
  { id: 'e138', word: 'come', meaning: 'đến', example: 'Come here please.', exampleVN: 'Đến đây.' },
  { id: 'e139', word: 'go', meaning: 'đi', example: 'I go to work by bus.', exampleVN: 'Tôi đi làm bằng xe buýt.' },
  { id: 'e140', word: 'play', meaning: 'chơi', example: 'Children love to play.', exampleVN: 'Trẻ em thích chơi.' },
  { id: 'e141', word: 'watch', meaning: 'xem, đồng hồ', example: 'I watch TV at night.', exampleVN: 'Tôi xem TV vào buổi tối.' },
  { id: 'e142', word: 'use', meaning: 'sử dụng', example: 'How do you use this?', exampleVN: 'Bạn sử dụng cái này thế nào?' },
  { id: 'e143', word: 'pay', meaning: 'trả tiền', example: 'I will pay by card.', exampleVN: 'Tôi sẽ trả bằng thẻ.' },
  { id: 'e144', word: 'change', meaning: 'thay đổi, tiền thối', example: 'Keep the change.', exampleVN: 'Giữ lại tiền thối.' },
  { id: 'e145', word: 'order', meaning: 'đặt hàng, thứ tự', example: 'I want to order food.', exampleVN: 'Tôi muốn đặt đồ ăn.' },
  { id: 'e146', word: 'number', meaning: 'số', example: 'What is your phone number?', exampleVN: 'Số điện thoại của bạn là gì?' },
  { id: 'e147', word: 'letter', meaning: 'lá thư, chữ cái', example: 'I got a letter today.', exampleVN: 'Tôi nhận được một lá thư hôm nay.' },
  { id: 'e148', word: 'map', meaning: 'bản đồ', example: 'Look at the map.', exampleVN: 'Nhìn vào bản đồ.' },
  { id: 'e149', word: 'ticket', meaning: 'vé', example: 'Buy a train ticket.', exampleVN: 'Mua vé tàu.' },
  { id: 'e150', word: 'weather', meaning: 'thời tiết', example: 'The weather is nice today.', exampleVN: 'Thời tiết hôm nay đẹp.' },
  { id: 'e151', word: 'color', meaning: 'màu sắc', example: 'What color do you like?', exampleVN: 'Bạn thích màu gì?' },
  { id: 'e152', word: 'picture', meaning: 'hình ảnh, bức tranh', example: 'Look at this picture.', exampleVN: 'Nhìn bức tranh này.' },
  { id: 'e153', word: 'bag', meaning: 'túi, cặp', example: 'Put it in the bag.', exampleVN: 'Bỏ nó vào túi.' },
  { id: 'e154', word: 'key', meaning: 'chìa khóa', example: 'Where is my key?', exampleVN: 'Chìa khóa của tôi đâu?' },
  { id: 'e155', word: 'street', meaning: 'đường phố', example: 'Cross the street carefully.', exampleVN: 'Băng qua đường cẩn thận.' },
  { id: 'e156', word: 'store', meaning: 'cửa hàng', example: 'The store opens at 9 AM.', exampleVN: 'Cửa hàng mở lúc 9 giờ sáng.' },
  { id: 'e157', word: 'bank', meaning: 'ngân hàng', example: 'I go to the bank.', exampleVN: 'Tôi đi đến ngân hàng.' },
  { id: 'e158', word: 'hospital', meaning: 'bệnh viện', example: 'He is in the hospital.', exampleVN: 'Anh ấy ở trong bệnh viện.' },
  { id: 'e159', word: 'park', meaning: 'công viên', example: 'We play in the park.', exampleVN: 'Chúng tôi chơi trong công viên.' },
  { id: 'e160', word: 'train', meaning: 'tàu hỏa', example: 'Take the train to Hanoi.', exampleVN: 'Đi tàu đến Hà Nội.' },
  { id: 'e161', word: 'plane', meaning: 'máy bay', example: 'The plane is late.', exampleVN: 'Máy bay bị trễ.' },
  { id: 'e162', word: 'airport', meaning: 'sân bay', example: 'Go to the airport early.', exampleVN: 'Đến sân bay sớm.' },
  { id: 'e163', word: 'hotel', meaning: 'khách sạn', example: 'We stay at a hotel.', exampleVN: 'Chúng tôi ở khách sạn.' },
  { id: 'e164', word: 'restaurant', meaning: 'nhà hàng', example: 'Let us eat at a restaurant.', exampleVN: 'Hãy ăn ở nhà hàng.' },
  { id: 'e165', word: 'movie', meaning: 'phim', example: 'I saw a good movie.', exampleVN: 'Tôi đã xem một bộ phim hay.' },
  { id: 'e166', word: 'music', meaning: 'âm nhạc', example: 'I love music.', exampleVN: 'Tôi yêu âm nhạc.' },
  { id: 'e167', word: 'sport', meaning: 'thể thao', example: 'My favorite sport is soccer.', exampleVN: 'Môn thể thao yêu thích của tôi là bóng đá.' },
  { id: 'e168', word: 'birthday', meaning: 'sinh nhật', example: 'Happy birthday!', exampleVN: 'Chúc mừng sinh nhật!' },
  { id: 'e169', word: 'holiday', meaning: 'ngày lễ, kỳ nghỉ', example: 'We go on holiday next week.', exampleVN: 'Chúng tôi đi nghỉ tuần sau.' },
  { id: 'e170', word: 'clothes', meaning: 'quần áo', example: 'Buy new clothes.', exampleVN: 'Mua quần áo mới.' },
];
