import { Word } from './types';

export const chunk13: Word[] = [
  { id: 'ext401', word: 'gesture', meaning: 'điệu bộ, cử chỉ', example: 'A friendly gesture.', exampleVN: 'Một cử chỉ thân thiện.' },
  { id: 'ext402', word: 'gigantic', meaning: 'khổng lồ', example: 'A gigantic wave.', exampleVN: 'Một con sóng khổng lồ.' },
  { id: 'ext403', word: 'glance', meaning: 'liếc nhìn', example: 'Glance at your watch.', exampleVN: 'Liếc nhìn đồng hồ.' },
  { id: 'ext404', word: 'global', meaning: 'toàn cầu', example: 'Global warming.', exampleVN: 'Sự nóng lên toàn cầu.' },
  { id: 'ext405', word: 'glory', meaning: 'vinh quang', example: 'Fight for glory.', exampleVN: 'Chiến đấu vì vinh quang.' },
  { id: 'ext406', word: 'glossary', meaning: 'bảng chú giải', example: 'Check the glossary.', exampleVN: 'Kiểm tra bảng chú giải thuật ngữ.' },
  { id: 'ext407', word: 'gorgeous', meaning: 'tuyệt đẹp', example: 'You look gorgeous.', exampleVN: 'Bạn trông thật lộng lẫy.' },
  { id: 'ext408', word: 'govern', meaning: 'cai trị, quản lý', example: 'Govern a country.', exampleVN: 'Cai trị một đất nước.' },
  { id: 'ext409', word: 'grab', meaning: 'vồ lấy, chộp lấy', example: 'Grab a sandwich.', exampleVN: 'Ăn nhanh một cái bánh mì kẹp thịt.' },
  { id: 'ext410', word: 'grace', meaning: 'vẻ duyên dáng', example: 'Dance with grace.', exampleVN: 'Nhảy múa đầy duyên dáng.' },
  { id: 'ext411', word: 'gradual', meaning: 'dần dần', example: 'A gradual increase.', exampleVN: 'Sự gia tăng dần dần.' },
  { id: 'ext412', word: 'graduate', meaning: 'tốt nghiệp', example: 'Graduate from university.', exampleVN: 'Tốt nghiệp đại học.' },
  { id: 'ext413', word: 'grammar', meaning: 'ngữ pháp', example: 'Check your grammar.', exampleVN: 'Kiểm tra ngữ pháp của bạn.' },
  { id: 'ext414', word: 'grand', meaning: 'vĩ đại, lộng lẫy', example: 'A grand staircase.', exampleVN: 'Một cầu thang lớn.' },
  { id: 'ext415', word: 'grant', meaning: 'trợ cấp, ban cho', example: 'Student grant.', exampleVN: 'Trợ cấp sinh viên.' },
  { id: 'ext416', word: 'graph', meaning: 'đồ thị', example: 'Draw a graph.', exampleVN: 'Vẽ đồ thị.' },
  { id: 'ext417', word: 'grasp', meaning: 'nắm bắt', example: 'Grasp the concept.', exampleVN: 'Nắm bắt khái niệm.' },
  { id: 'ext418', word: 'grateful', meaning: 'biết ơn', example: 'I am grateful for your help.', exampleVN: 'Tôi biết ơn sự giúp đỡ của bạn.' },
  { id: 'ext419', word: 'gravity', meaning: 'trọng lực', example: 'The law of gravity.', exampleVN: 'Định luật trọng lực.' },
  { id: 'ext420', word: 'greedy', meaning: 'tham lam', example: 'A greedy person.', exampleVN: 'Một người tham lam.' },
  { id: 'ext421', word: 'grief', meaning: 'nỗi đau buồn', example: 'Overcome with grief.', exampleVN: 'Vượt qua nỗi đau buồn.' },
  { id: 'ext422', word: 'grin', meaning: 'cười tươi', example: 'He grinned widely.', exampleVN: 'Anh ta đã cười rất tươi.' },
  { id: 'ext423', word: 'grind', meaning: 'nghiền, xay', example: 'Grind coffee beans.', exampleVN: 'Xay hạt cà phê.' },
  { id: 'ext424', word: 'grip', meaning: 'nắm chặt', example: 'Tighten your grip.', exampleVN: 'Nắm chặt tay lại.' },
  { id: 'ext425', word: 'gross', meaning: 'tổng, thô bỉ', example: 'Gross profit.', exampleVN: 'Lợi nhuận gộp.' },
  { id: 'ext426', word: 'guarantee', meaning: 'bảo hành, đảm bảo', example: 'Money-back guarantee.', exampleVN: 'Đảm bảo hoàn tiền.' },
  { id: 'ext427', word: 'guideline', meaning: 'hướng dẫn', example: 'Follow the guidelines.', exampleVN: 'Làm theo hướng dẫn.' },
  { id: 'ext428', word: 'guilt', meaning: 'tội lỗi', example: 'Feelings of guilt.', exampleVN: 'Cảm giác tội lỗi.' },
  { id: 'ext429', word: 'habitat', meaning: 'môi trường sống', example: 'Natural habitat.', exampleVN: 'Môi trường sống tự nhiên.' },
  { id: 'ext430', word: 'halt', meaning: 'tạm dừng', example: 'The car came to a halt.', exampleVN: 'Chiếc xe đã dừng lại.' },
  { id: 'ext431', word: 'handle', meaning: 'xử lý, tay cầm', example: 'Handle with care.', exampleVN: 'Xử lý cẩn thận.' },
  { id: 'ext432', word: 'handy', meaning: 'tiện lợi', example: 'Keep it handy.', exampleVN: 'Giữ nó ở nơi thuận tiện.' },
  { id: 'ext433', word: 'harbor', meaning: 'bến cảng', example: 'The ship entered the harbor.', exampleVN: 'Con tàu tiến vào bến cảng.' },
  { id: 'ext434', word: 'harmony', meaning: 'sự hài hòa', example: 'Live in harmony.', exampleVN: 'Sống trong sự hài hòa.' },
  { id: 'ext435', word: 'harsh', meaning: 'khắc nghiệt', example: 'Harsh conditions.', exampleVN: 'Điều kiện khắc nghiệt.' },
  { id: 'ext436', word: 'harvest', meaning: 'thu hoạch', example: 'Wait for the harvest.', exampleVN: 'Chờ đợi vụ thu hoạch.' },
  { id: 'ext437', word: 'haste', meaning: 'sự vội vã', example: 'More haste, less speed.', exampleVN: 'Dục tốc bất đạt.' },
  { id: 'ext438', word: 'hazard', meaning: 'mối nguy hiểm', example: 'Health hazard.', exampleVN: 'Nguy hiểm cho sức khỏe.' },
  { id: 'ext439', word: 'headline', meaning: 'tiêu đề', example: 'Read the headlines.', exampleVN: 'Đọc các tiêu đề.' },
  { id: 'ext440', word: 'headquarters', meaning: 'trụ sở chính', example: 'Visit the headquarters.', exampleVN: 'Ghé thăm trụ sở chính.' },
  { id: 'ext441', word: 'heap', meaning: 'đống', example: 'A heap of stones.', exampleVN: 'Một đống đá.' },
  { id: 'ext442', word: 'heritage', meaning: 'di sản', example: 'Cultural heritage.', exampleVN: 'Di sản văn hóa.' },
  { id: 'ext443', word: 'hierarchy', meaning: 'hệ thống phân cấp', example: 'In the hierarchy.', exampleVN: 'Trong hệ thống phân bậc.' },
  { id: 'ext444', word: 'highlight', meaning: 'nổi bật', example: 'Highlight the text.', exampleVN: 'Làm nổi bật văn bản.' },
  { id: 'ext445', word: 'hint', meaning: 'gợi ý', example: 'Give me a hint.', exampleVN: 'Gợi ý cho tôi đi.' },
  { id: 'ext446', word: 'hollow', meaning: 'rỗng', example: 'A hollow tree.', exampleVN: 'Một cái cây bị rỗng.' },
  { id: 'ext447', word: 'horizon', meaning: 'chân trời', example: 'On the horizon.', exampleVN: 'Phía cuối chân trời.' },
  { id: 'ext448', word: 'hospitality', meaning: 'lòng hiếu khách', example: 'Thank you for your hospitality.', exampleVN: 'Cảm ơn vì sự hiếu khách của bạn.' },
  { id: 'ext449', word: 'hostile', meaning: 'thù địch', example: 'A hostile environment.', exampleVN: 'Một môi trường thù địch.' },
  { id: 'ext450', word: 'household', meaning: 'hộ gia đình', example: 'Household chores.', exampleVN: 'Việc nhà.' },
  { id: 'ext451', word: 'humble', meaning: 'khiêm tốn', example: 'A humble beginning.', exampleVN: 'Một khởi đầu giản khiêm tốn.' },
  { id: 'ext452', word: 'humid', meaning: 'ẩm ướt', example: 'Hot and humid.', exampleVN: 'Nóng và ẩm.' },
  { id: 'ext453', word: 'hygiene', meaning: 'vệ sinh', example: 'Personal hygiene.', exampleVN: 'Vệ sinh cá nhân.' },
  { id: 'ext454', word: 'hypothesis', meaning: 'giả thuyết', example: 'Test a hypothesis.', exampleVN: 'Kiểm tra một giả thuyết.' },
  { id: 'ext455', word: 'ideal', meaning: 'lý tưởng', example: 'The ideal solution.', exampleVN: 'Giải pháp lý tưởng.' },
  { id: 'ext456', word: 'identical', meaning: 'giống hệt nhau', example: 'Identical twins.', exampleVN: 'Cặp song sinh giống hệt nhau.' },
  { id: 'ext457', word: 'identify', meaning: 'nhận dạng', example: 'Identify the problem.', exampleVN: 'Xác định vấn đề.' },
  { id: 'ext458', word: 'idiom', meaning: 'thành ngữ', example: 'Learn English idioms.', exampleVN: 'Học các thành ngữ tiếng Anh.' },
  { id: 'ext459', word: 'idle', meaning: 'nhàn rỗi', example: 'Idle machines.', exampleVN: 'Máy móc ngừng hoạt động.' },
  { id: 'ext460', word: 'ignorant', meaning: 'thiếu hiểu biết', example: 'Ignorant of the facts.', exampleVN: 'Thiếu hiểu biết về các sự kiện.' },
  { id: 'ext461', word: 'illegal', meaning: 'bất hợp pháp', example: 'Illegal drug.', exampleVN: 'Thuốc bất hợp pháp.' },
  { id: 'ext462', word: 'illiterate', meaning: 'mù chữ', example: 'A highly illiterate area.', exampleVN: 'Một khu vực có tỷ lệ mù chữ cao.' },
  { id: 'ext463', word: 'illusion', meaning: 'ảo tưởng', example: 'Under the illusion.', exampleVN: 'Dưới ảo tưởng.' },
  { id: 'ext464', word: 'illustrate', meaning: 'minh họa', example: 'Illustrate with examples.', exampleVN: 'Minh họa bằng các ví dụ.' },
  { id: 'ext465', word: 'imitate', meaning: 'bắt chước', example: 'Imitate his voice.', exampleVN: 'Bắt chước giọng của anh ấy.' },
  { id: 'ext466', word: 'immense', meaning: 'mênh mông', example: 'An immense library.', exampleVN: 'Một thư viện mênh mông.' },
  { id: 'ext467', word: 'immigrate', meaning: 'nhập cư', example: 'They immigrated to Canada.', exampleVN: 'Họ đã nhập cư vào Canada.' },
  { id: 'ext468', word: 'immune', meaning: 'miễn dịch', example: 'Immune system.', exampleVN: 'Hệ miễn dịch.' },
  { id: 'ext469', word: 'impact', meaning: 'tác động', example: 'Economic impact.', exampleVN: 'Tác động kinh tế.' },
  { id: 'ext470', word: 'imperial', meaning: 'thuộc về đế quốc', example: 'Imperial Palace.', exampleVN: 'Cung điện Hoàng gia.' },
  { id: 'ext471', word: 'implement', meaning: 'triển khai', example: 'Implement a policy.', exampleVN: 'Thực hiện một chính sách.' },
  { id: 'ext472', word: 'implicit', meaning: 'ngầm hiểu', example: 'Implicit trust.', exampleVN: 'Sự tin tưởng ngầm định.' },
  { id: 'ext473', word: 'imply', meaning: 'ám chỉ', example: 'What do you imply?', exampleVN: 'Bạn đang ám chỉ điều gì?' },
  { id: 'ext474', word: 'import', meaning: 'nhập khẩu', example: 'Import goods from China.', exampleVN: 'Nhập khẩu hàng hóa từ Trung Quốc.' },
  { id: 'ext475', word: 'impose', meaning: 'áp đặt', example: 'Impose a tax.', exampleVN: 'Áp thuế.' },
  { id: 'ext476', word: 'impressive', meaning: 'ấn tượng', example: 'An impressive performance.', exampleVN: 'Một buổi trình diễn ấn tượng.' },
  { id: 'ext477', word: 'imprison', meaning: 'bỏ tù', example: 'She was imprisoned.', exampleVN: 'Cô ấy đã bị bỏ tù.' },
  { id: 'ext478', word: 'incentive', meaning: 'khuyến khích, ưu đãi', example: 'Financial incentive.', exampleVN: 'Ưu đãi tài chính.' },
  { id: 'ext479', word: 'incidence', meaning: 'tỷ lệ mắc phải', example: 'The incidence of heart disease.', exampleVN: 'Tỷ lệ mắc bệnh tim.' },
  { id: 'ext480', word: 'incident', meaning: 'sự cố', example: 'A minor incident.', exampleVN: 'Một sự cố nhỏ.' },
  { id: 'ext481', word: 'inclined', meaning: 'có xu hướng', example: 'I am inclined to agree.', exampleVN: 'Tôi thiên về việc đồng ý.' },
  { id: 'ext482', word: 'include', meaning: 'bao gồm', example: 'Service is included.', exampleVN: 'Đã bao gồm phí phục vụ.' },
  { id: 'ext483', word: 'incorrect', meaning: 'không đúng', example: 'Incorrect answer.', exampleVN: 'Câu trả lời sai.' },
  { id: 'ext484', word: 'index', meaning: 'chỉ mục', example: 'Consumer price index.', exampleVN: 'Chỉ số giá tiêu dùng.' },
  { id: 'ext485', word: 'indicate', meaning: 'chỉ ra', example: 'A sign indicating the exit.', exampleVN: 'Một biển báo chỉ lỗi thoát.' },
  { id: 'ext486', word: 'indifferent', meaning: 'thờ ơ', example: 'Indifferent to the outcome.', exampleVN: 'Thờ ơ với kết quả.' },
  { id: 'ext487', word: 'induce', meaning: 'xui khiến, gây ra', example: 'Stress-induced illness.', exampleVN: 'Bệnh do căng thẳng.' },
  { id: 'ext488', word: 'indulge', meaning: 'nuông chiều, thưởng thức', example: 'Indulge in chocolate.', exampleVN: 'Thưởng thức sô cô la.' },
  { id: 'ext489', word: 'industrious', meaning: 'cần cù', example: 'An industrious student.', exampleVN: 'Một học sinh siêng năng.' },
  { id: 'ext490', word: 'inevitable', meaning: 'không thể tránh khỏi', example: 'Changes are inevitable.', exampleVN: 'Sự thay đổi là tất yếu.' },
  { id: 'ext491', word: 'infancy', meaning: 'thời thơ ấu, giai đoạn sơ khai', example: 'The project is in its infancy.', exampleVN: 'Dự án đang trong giai đoạn đầu.' },
  { id: 'ext492', word: 'infect', meaning: 'lây nhiễm', example: 'Be infected with a virus.', exampleVN: 'Bị nhiễm vi-rút.' },
  { id: 'ext493', word: 'infer', meaning: 'suy luận', example: 'Infer from the text.', exampleVN: 'Suy luận từ văn bản.' },
  { id: 'ext494', word: 'infinite', meaning: 'vô tận', example: 'Infinite possibilities.', exampleVN: 'Khả năng vô tận.' },
  { id: 'ext495', word: 'influence', meaning: 'ảnh hưởng', example: 'Under the influence.', exampleVN: 'Chịu ảnh hưởng.' },
  { id: 'ext496', word: 'informal', meaning: 'không trang trọng', example: 'An informal meeting.', exampleVN: 'Một cuộc gặp gỡ không chính thức.' },
  { id: 'ext497', word: 'infrastructure', meaning: 'cơ sở hạ tầng', example: 'Improve infrastructure.', exampleVN: 'Cải thiện cơ sở hạ tầng.' },
  { id: 'ext498', word: 'inherent', meaning: 'vốn có', example: 'Inherent risks.', exampleVN: 'Những rủi ro tiềm tàng.' },
  { id: 'ext499', word: 'inherit', meaning: 'thừa kế', example: 'Inherit a fortune.', exampleVN: 'Thừa kế một tài sản.' },
  { id: 'ext500', word: 'initial', meaning: 'ban đầu', example: 'The initial cost.', exampleVN: 'Chi phí ban đầu.' },
  { id: 'ext501', word: 'inject', meaning: 'tiêm', example: 'Inject fuel.', exampleVN: 'Phun nhiên liệu.' },
  { id: 'ext502', word: 'injure', meaning: 'làm bị thương', example: 'He was badly injured.', exampleVN: 'Anh ta bị thương nặng.' },
  { id: 'ext503', word: 'injustice', meaning: 'sự bất công', example: 'Fight against injustice.', exampleVN: 'Đấu tranh chống lại sự bất công.' },
  { id: 'ext504', word: 'inner', meaning: 'bên trong', example: 'Inner circle.', exampleVN: 'Vòng tròn bên trong.' },
  { id: 'ext505', word: 'innocent', meaning: 'vô tội', example: 'Proven innocent.', exampleVN: 'Được chứng minh là vô tội.' },
  { id: 'ext506', word: 'innovate', meaning: 'đổi mới', example: 'Innovate to survive.', exampleVN: 'Đổi mới để tồn tại.' },
  { id: 'ext507', word: 'input', meaning: 'đầu vào', example: 'Data input.', exampleVN: 'Nhập dữ liệu.' },
  { id: 'ext508', word: 'insight', meaning: 'thấu hiểu, cái nhìn sâu sắc', example: 'Valuable insight.', exampleVN: 'Cái nhìn thấu đáo đầy giá trị.' },
  { id: 'ext509', word: 'install', meaning: 'cài đặt', example: 'Install the app.', exampleVN: 'Cài đặt ứng dụng.' },
  { id: 'ext510', word: 'instance', meaning: 'ví dụ, trường hợp', example: 'For instance.', exampleVN: 'Ví dụ.' },
  { id: 'ext511', word: 'instant', meaning: 'ngay lập tức', example: 'Instant coffee.', exampleVN: 'Cà phê hòa tan.' },
  { id: 'ext512', word: 'instinct', meaning: 'bản năng', example: 'Trust your instinct.', exampleVN: 'Tin vào bản năng của mình.' },
  { id: 'ext513', word: 'institute', meaning: 'viện, học viện, thiết lập', example: 'Research institute.', exampleVN: 'Viện nghiên cứu.' },
  { id: 'ext514', word: 'instruct', meaning: 'hướng dẫn', example: 'Instruct someone to do it.', exampleVN: 'Hướng dẫn ai đó làm việc đó.' },
  { id: 'ext515', word: 'instrument', meaning: 'nhạc cụ, công cụ', example: 'Musical instrument.', exampleVN: 'Nhạc cụ.' },
  { id: 'ext516', word: 'insulate', meaning: 'cách nhiệt, cách ly', example: 'Insulated pipes.', exampleVN: 'Ống nước cách nhiệt.' },
  { id: 'ext517', word: 'insure', meaning: 'bảo hiểm', example: 'Insure your car.', exampleVN: 'Mua bảo hiểm cho xe của bạn.' },
  { id: 'ext518', word: 'intact', meaning: 'nguyên vẹn', example: 'The box was still intact.', exampleVN: 'Chiếc hộp vẫn còn nguyên vẹn.' },
  { id: 'ext519', word: 'intake', meaning: 'lượng tiêu thụ', example: 'Reduce salt intake.', exampleVN: 'Giảm lượng muối nạp vào.' },
  { id: 'ext520', word: 'integral', meaning: 'thiết yếu, tích hợp', example: 'An integral part.', exampleVN: 'Một phần thiết yếu.' },
  { id: 'ext521', word: 'integrate', meaning: 'tích hợp', example: 'Integrate the systems.', exampleVN: 'Tích hợp các hệ thống.' },
  { id: 'ext522', word: 'intellectual', meaning: 'thuộc về trí tuệ', example: 'Intellectual property.', exampleVN: 'Sở hữu trí tuệ.' },
  { id: 'ext523', word: 'intense', meaning: 'mãnh liệt', example: 'Intense heat.', exampleVN: 'Nhiệt độ dữ dội.' },
  { id: 'ext524', word: 'intent', meaning: 'ý định', example: 'No evil intent.', exampleVN: 'Không có ý xấu.' },
  { id: 'ext525', word: 'interaction', meaning: 'sự tương tác', example: 'Social interaction.', exampleVN: 'Tương tác xã hội.' },
  { id: 'ext526', word: 'interior', meaning: 'nội thất', example: 'Interior design.', exampleVN: 'Thiết kế nội thất.' },
  { id: 'ext527', word: 'intermediary', meaning: 'người trung gian', example: 'Act as an intermediary.', exampleVN: 'Đóng vai trò là người trung gian.' },
  { id: 'ext528', word: 'internal', meaning: 'nội bộ', example: 'Internal audit.', exampleVN: 'Kiểm toán nội bộ.' },
  { id: 'ext529', word: 'interpret', meaning: 'giả thích, phiên dịch', example: 'Interpret the results.', exampleVN: 'Giải thích kết quả.' },
  { id: 'ext530', word: 'interrupt', meaning: 'ngắt lời', example: 'Don\'t interrupt me.', exampleVN: 'Đừng ngắt lời tôi.' },
  { id: 'ext531', word: 'interval', meaning: 'khoảng thời gian', example: 'Regular intervals.', exampleVN: 'Khoảng thời gian thường xuyên.' },
  { id: 'ext532', word: 'intervene', meaning: 'can thiệp', example: 'Police intervened.', exampleVN: 'Cảnh sát đã can thiệp.' },
  { id: 'ext533', word: 'intimate', meaning: 'thân mật', example: 'An intimate dinner.', exampleVN: 'Một bữa tối thân mật.' },
  { id: 'ext534', word: 'intrigue', meaning: 'mưu đồ, hấp dẫn', example: 'Political intrigue.', exampleVN: 'Âm mưu chính trị.' },
  { id: 'ext535', word: 'intrinsic', meaning: 'bản chất, nội tại', example: 'Intrinsic value.', exampleVN: 'Giá trị nội tại.' },
  { id: 'ext536', word: 'introduce', meaning: 'giới thiệu', example: 'Introduce a new law.', exampleVN: 'Giới thiệu một luật mới.' },
  { id: 'ext537', word: 'invade', meaning: 'xâm lược', example: 'Invade a country.', exampleVN: 'Xâm lược một quốc gia.' },
  { id: 'ext538', word: 'invalid', meaning: 'không hợp lệ', example: 'Invalid password.', exampleVN: 'Mật khẩu không hợp lệ.' },
  { id: 'ext539', word: 'inventory', meaning: 'hàng tồn kho', example: 'Check the inventory.', exampleVN: 'Kiểm kê hàng tồn kho.' },
  { id: 'ext540', word: 'invest', meaning: 'đầu tư', example: 'Invest in real estate.', exampleVN: 'Đầu tư vào bất động sản.' },
  { id: 'ext541', word: 'investigate', meaning: 'điều tra', example: 'Investigate the accident.', exampleVN: 'Điều tra vụ tai nạn.' },
  { id: 'ext542', word: 'invite', meaning: 'mời', example: 'Invite friends to dinner.', exampleVN: 'Mời bạn bè đi ăn tối.' },
  { id: 'ext543', word: 'involve', meaning: 'liên quan', example: 'Don\'t involve me.', exampleVN: 'Đừng kéo tôi vào.' },
  { id: 'ext544', word: 'irony', meaning: 'trớ trêu', example: 'The irony of the situation.', exampleVN: 'Sự trớ trêu của tình huống này.' },
  { id: 'ext545', word: 'irrigate', meaning: 'tưới tiêu', example: 'Irrigate the fields.', exampleVN: 'Tưới nước cho đồng ruộng.' },
  { id: 'ext546', word: 'isolate', meaning: 'cách ly', example: 'Isolated islands.', exampleVN: 'Những hòn đảo biệt lập.' },
  { id: 'ext547', word: 'issue', meaning: 'vấn đề, phát hành', example: 'The current issue.', exampleVN: 'Vấn đề hiện tại.' },
  { id: 'ext548', word: 'item', meaning: 'mặt hàng', example: 'Add to the list of items.', exampleVN: 'Thêm vào danh sách các mục.' },
  { id: 'ext549', word: 'ivory', meaning: 'ngà voi', example: 'Ivory jewelry.', exampleVN: 'Trang sức bằng ngà voi.' },
  { id: 'ext550', word: 'jail', meaning: 'tù', example: 'Sent to jail.', exampleVN: 'Bị đưa vào tù.' }
];

export const processChunk13 = () => {
    const nouns = new Set(['gesture', 'glory', 'glossary', 'grammar', 'grant', 'graph', 'gravity', 'grief', 'grin', 'grip', 'guideline', 'guilt', 'habitat', 'harbor', 'harmony', 'harvest', 'haste', 'hazard', 'headline', 'headquarters', 'heap', 'heritage', 'hierarchy', 'hint', 'horizon', 'hospitality', 'household', 'hygiene', 'hypothesis', 'idiom', 'illusion', 'immigrate', 'impact', 'incite', 'incidence', 'incident', 'index', 'infancy', 'influence', 'infrastructure', 'injustice', 'input', 'insight', 'instance', 'instinct', 'institute', 'instrument', 'intake', 'intent', 'interaction', 'interior', 'intermediary', 'interval', 'intrigue', 'inventory', 'irony', 'issue', 'item', 'ivory', 'jail']);
    const adjs = new Set(['gigantic', 'global', 'gorgeous', 'gradual', 'grand', 'grateful', 'greedy', 'gross', 'handy', 'harsh', 'hollow', 'hostile', 'humble', 'humid', 'ideal', 'identical', 'idle', 'ignorant', 'illegal', 'illiterate', 'immense', 'immune', 'imperial', 'implicit', 'impressive', 'inclined', 'incorrect', 'indifferent', 'industrious', 'inevitable', 'infinite', 'informal', 'inherent', 'initial', 'inner', 'innocent', 'instant', 'intact', 'integral', 'intellectual', 'intense', 'internal', 'intimate', 'intrinsic', 'invalid']);

    return chunk13.map(w => {
        let pos = '(v)';
        if (nouns.has(w.word)) pos = '(n)';
        else if (adjs.has(w.word)) pos = '(adj)';
        return { ...w, pos };
    });
};
