import { Word } from './types';

export const chunkHard4: Word[] = [
  { id: 'h301', word: 'premeditate', meaning: 'đã được suy tính trước', example: 'A premeditated crime.', exampleVN: 'Một tội ác đã được suy tính trước.' },
  { id: 'h302', word: 'preponderance', meaning: 'sự vượt trội về số lượng', example: 'A preponderance of evidence.', exampleVN: 'Sự vượt trội về bằng chứng.' },
  { id: 'h303', word: 'preposterous', meaning: 'phi lý, lố bịch', example: 'A preposterous suggestion.', exampleVN: 'Một đề nghị phi lý.' },
  { id: 'h304', word: 'presumptuous', meaning: 'tự phụ, quá đỗi tự nhiên', example: 'It was presumptuous of him to speak for us.', exampleVN: 'Thật là tự phụ khi anh ta thay mặt chúng tôi phát biểu.' },
  { id: 'h305', word: 'prevalent', meaning: 'phổ biến, thịnh hành', example: 'The custom is prevalent in this area.', exampleVN: 'Phong tục này thịnh hành ở khu vực này.' },
  { id: 'h306', word: 'pristine', meaning: 'nguyên sơ, sạch sẽ', example: 'A pristine beach.', exampleVN: 'Một bãi biển nguyên sơ.' },
  { id: 'h307', word: 'probity', meaning: 'sự chính trực', example: 'A man of unquestionable probity.', exampleVN: 'Một người đàn ông có sự chính trực không thể nghi ngờ.' },
  { id: 'h308', word: 'proclivity', meaning: 'khuynh hướng', example: 'A proclivity for hard work.', exampleVN: 'Khuynh hướng làm việc chăm chỉ.' },
  { id: 'h309', word: 'procrastinate', meaning: 'trì hoãn', example: 'Don\'t procrastinate on your tasks.', exampleVN: 'Đừng trì hoãn các nhiệm vụ của bạn.' },
  { id: 'h310', word: 'prodigious', meaning: 'phi thường, to lớn', example: 'A prodigious amount of effort.', exampleVN: 'Một nỗ lực phi thường.' },
  { id: 'h311', word: 'proficient', meaning: 'thành thạo', example: 'Proficient in English.', exampleVN: 'Thành thạo tiếng Anh.' },
  { id: 'h312', word: 'profound', meaning: 'sâu sắc', example: 'A profound impact.', exampleVN: 'Một tác động sâu sắc.' },
  { id: 'h313', word: 'prohibit', meaning: 'cấm', example: 'Smoking is prohibited.', exampleVN: 'Hút thuốc bị cấm.' },
  { id: 'h314', word: 'prolix', meaning: 'dài dòng', example: 'A prolix legal document.', exampleVN: 'Một tài liệu pháp lý dài dòng.' },
  { id: 'h315', word: 'promulgate', meaning: 'ban bố, công bố', example: 'Promulgate a new law.', exampleVN: 'Ban bố một đạo luật mới.' },
  { id: 'h316', word: 'propagate', meaning: 'tuyên truyền, nhân giống', example: 'Propagate ideas.', exampleVN: 'Tuyên truyền ý tưởng.' },
  { id: 'h317', word: 'propensity', meaning: 'khuynh hướng', example: 'A propensity for violence.', exampleVN: 'Khuynh hướng bạo lực.' },
  { id: 'h318', word: 'propitious', meaning: 'thuận lợi', example: 'A propitious moment.', exampleVN: 'Một thời điểm thuận lợi.' },
  { id: 'h319', word: 'propriety', meaning: 'sự đúng đắn, lễ nghi', example: 'Maintain propriety.', exampleVN: 'Duy trì sự đúng mực.' },
  { id: 'h320', word: 'prosaic', meaning: 'tầm thường, không sáng tạo', example: 'A prosaic description.', exampleVN: 'Một mô tả tầm thường.' },
  { id: 'h321', word: 'proscribe', meaning: 'cấm, trục xuất', example: 'The drug was proscribed.', exampleVN: 'Loại thuốc đó đã bị cấm.' },
  { id: 'h322', word: 'prosper', meaning: 'thịnh vượng', example: 'The business is prospering.', exampleVN: 'Công việc kinh doanh đang thịnh vượng.' },
  { id: 'h323', word: 'protracted', meaning: 'kéo dài', example: 'A protracted legal battle.', exampleVN: 'Một cuộc chiến pháp lý kéo dài.' },
  { id: 'h324', word: 'provident', meaning: 'lo xa, tiết kiệm', example: 'A provident investor.', exampleVN: 'Một nhà đầu tư biết lo xa.' },
  { id: 'h325', word: 'provincial', meaning: 'thuộc về tỉnh, hẹp hòi', example: 'Provincial government.', exampleVN: 'Chính quyền tỉnh.' },
  { id: 'h326', word: 'prudence', meaning: 'sự thận trọng', example: 'Exercise prudence.', exampleVN: 'Thực hiện sự thận trọng.' },
  { id: 'h327', word: 'puerile', meaning: 'trẻ con, khờ dại', example: 'Puerile jokes.', exampleVN: 'Những trò đùa trẻ con.' },
  { id: 'h328', word: 'pugnacious', meaning: 'hay gây gổ', example: 'A pugnacious attitude.', exampleVN: 'Một thái độ hay gây gổ.' },
  { id: 'h329', word: 'punctilious', meaning: 'tỉ mỉ, cầu kỳ', example: 'Punctilious attention to detail.', exampleVN: 'Sự chú ý tỉ mỉ đến từng chi tiết.' },
  { id: 'h330', word: 'pundit', meaning: 'chuyên gia, học giả', example: 'Political pundits.', exampleVN: 'Các chuyên gia chính trị.' },
  { id: 'h331', word: 'pungent', meaning: 'hăng, cay', example: 'A pungent smell.', exampleVN: 'Một mùi hăng.' },
  { id: 'h332', word: 'purport', meaning: 'có ý đồ, ngụ ý', example: 'The letter purports to be from him.', exampleVN: 'Bức thư ngụ ý là từ anh ấy.' },
  { id: 'h333', word: 'quandary', meaning: 'tình thế khó xử', example: 'Be in a quandary.', exampleVN: 'Ở trong tình thế khó xử.' },
  { id: 'h334', word: 'quarantine', meaning: 'cách ly', example: 'Put in quarantine.', exampleVN: 'Đưa vào diện cách ly.' },
  { id: 'h335', word: 'quell', meaning: 'dập tắt, trấn áp', example: 'Quell the riot.', exampleVN: 'Trấn áp cuộc bạo loạn.' },
  { id: 'h336', word: 'querulous', meaning: 'hay cáu bẳn, hay phàn nàn', example: 'A querulous voice.', exampleVN: 'Một giọng nói hay phàn nàn.' },
  { id: 'h337', word: 'quiescent', meaning: 'yên lặng, thụ động', example: 'A quiescent volcano.', exampleVN: 'Một ngọn núi lửa đang ngủ yên.' },
  { id: 'h338', word: 'quintessential', meaning: 'tinh túy, tiêu biểu', example: 'The quintessential Englishman.', exampleVN: 'Người Anh tiêu biểu nhất.' },
  { id: 'h339', word: 'quixotic', meaning: 'viển vông, hão huyền', example: 'A quixotic quest.', exampleVN: 'Một nhiệm vụ viển vông.' },
  { id: 'h340', word: 'quotidian', meaning: 'hàng ngày, tầm thường', example: 'Quotidian tasks.', exampleVN: 'Các công việc hàng ngày.' },
  { id: 'h341', word: 'ramification', meaning: 'hệ quả', example: 'Political ramifications.', exampleVN: 'Hệ quả chính trị.' },
  { id: 'h342', word: 'rancor', meaning: 'sự căm thù', example: 'Feel no rancor.', exampleVN: 'Không cảm thấy căm thù.' },
  { id: 'h343', word: 'rapacious', meaning: 'tham lam, cưỡng đoạt', example: 'Rapacious creditors.', exampleVN: 'Các chủ nợ tham lam.' },
  { id: 'h344', word: 'ratify', meaning: 'phê chuẩn', example: 'Ratify an agreement.', exampleVN: 'Phê chuẩn một thỏa thuận.' },
  { id: 'h345', word: 'rebut', meaning: 'bác bỏ', example: 'Rebut an argument.', exampleVN: 'Bác bỏ một lập luận.' },
  { id: 'h346', word: 'recalcitrant', meaning: 'ngoan cố, cứng đầu', example: 'A recalcitrant child.', exampleVN: 'Một đứa trẻ ngoan cố.' },
  { id: 'h347', word: 'recant', meaning: 'công khai rút lại (ý kiến)', example: 'Recant a statement.', exampleVN: 'Rút lại một tuyên bố.' },
  { id: 'h348', word: 'recapitulate', meaning: 'tóm tắt lại', example: 'Recapitulate the main points.', exampleVN: 'Tóm tắt lại các ý chính.' },
  { id: 'h349', word: 'recede', meaning: 'rút đi, lùi lại', example: 'The tide receded.', exampleVN: 'Thủy triều rút đi.' },
  { id: 'h350', word: 'receptive', meaning: 'dễ tiếp thu', example: 'Be receptive to new ideas.', exampleVN: 'Dễ tiếp thu những ý tưởng mới.' },
  { id: 'h351', word: 'reciprocal', meaning: 'có đi có lại', example: 'A reciprocal agreement.', exampleVN: 'Một thỏa thuận có đi có lại.' },
  { id: 'h352', word: 'recluse', meaning: 'người ẩn dật', example: 'He lived as a recluse.', exampleVN: 'Ông ấy sống như một người ẩn dật.' },
  { id: 'h353', word: 'recondite', meaning: 'tối nghĩa, thâm hiểm', example: 'A recondite subject.', exampleVN: 'Một chủ đề thâm sâu.' },
  { id: 'h354', word: 'rectify', meaning: 'sửa cho đúng', example: 'Rectify the error.', exampleVN: 'Sửa lỗi.' },
  { id: 'h355', word: 'rectitude', meaning: 'sự chính trực', example: 'Moral rectitude.', exampleVN: 'Sự chính trực về đạo đức.' },
  { id: 'h356', word: 'redolent', meaning: 'ngào ngạt, gợi nhớ', example: 'Redolent of the sea.', exampleVN: 'Gợi nhớ về biển cả.' },
  { id: 'h357', word: 'redoubtable', meaning: 'đáng gờm', example: 'A redoubtable opponent.', exampleVN: 'Một đối thủ đáng gờm.' },
  { id: 'h358', word: 'redundant', meaning: 'dư thừa, bị sa thải', example: 'Make someone redundant.', exampleVN: 'Sa thải ai đó.' },
  { id: 'h359', word: 'refute', meaning: 'bác bỏ', example: 'Refute a theory.', exampleVN: 'Bác bỏ một lý thuyết.' },
  { id: 'h360', word: 'reiterate', meaning: 'lặp lại', example: 'Reiterate the importance of...', exampleVN: 'Nhắc lại tầm quan trọng của...' },
  { id: 'h361', word: 'rejuvenate', meaning: 'làm trẻ lại', example: 'Rejuvenate the skin.', exampleVN: 'Làm trẻ hóa làn da.' },
  { id: 'h362', word: 'relegate', meaning: 'giáng chức, đẩy xuống', example: 'Relegate to a lower position.', exampleVN: 'Giáng xuống một vị trí thấp hơn.' },
  { id: 'h363', word: 'relentless', meaning: 'không ngừng nghỉ, tàn nhẫn', example: 'Relentless pressure.', exampleVN: 'Áp lực không ngừng nghỉ.' },
  { id: 'h364', word: 'relinquish', meaning: 'từ bỏ, buông bỏ', example: 'Relinquish control.', exampleVN: 'Từ bỏ quyền kiểm soát.' },
  { id: 'h365', word: 'reminisce', meaning: 'hồi tưởng', example: 'Reminisce about the past.', exampleVN: 'Hồi tưởng về quá khứ.' },
  { id: 'h366', word: 'remiss', meaning: 'cẩu thả, lơ là', example: 'Be remiss in your duties.', exampleVN: 'Lơ là nhiệm vụ của bạn.' },
  { id: 'h367', word: 'remonstrate', meaning: 'phản đối, quở trách', example: 'Remonstrate with someone.', exampleVN: 'Phản đối ai đó.' },
  { id: 'h368', word: 'remorse', meaning: 'sự hối hận', example: 'Feel remorse.', exampleVN: 'Cảm thấy hối hận.' },
  { id: 'h369', word: 'remuneration', meaning: 'thù lao', example: 'Fair remuneration.', exampleVN: 'Thù lao xứng đáng.' },
  { id: 'h370', word: 'renaissance', meaning: 'sự phục hưng', example: 'A cultural renaissance.', exampleVN: 'Một sự phục hưng văn hóa.' },
  { id: 'h371', word: 'rendezvous', meaning: 'điểm hẹn', example: 'A secret rendezvous.', exampleVN: 'Một điểm hẹn bí mật.' },
  { id: 'h372', word: 'renegade', meaning: 'người phản bội', example: 'A renegade soldier.', exampleVN: 'Một người lính đào ngũ.' },
  { id: 'h373', word: 'renounce', meaning: 'từ bỏ', example: 'Renounce citizenship.', exampleVN: 'Từ bỏ quốc tịch.' },
  { id: 'h374', word: 'renowned', meaning: 'nổi tiếng', example: 'A renowned artist.', exampleVN: 'Một nghệ sĩ nổi tiếng.' },
  { id: 'h375', word: 'reparable', meaning: 'có thể sửa chữa', example: 'Reparable damage.', exampleVN: 'Thiệt hại có thể sửa chữa.' },
  { id: 'h376', word: 'reparation', meaning: 'sự bồi thường', example: 'War reparations.', exampleVN: 'Bồi thường chiến tranh.' },
  { id: 'h377', word: 'repartee', meaning: 'sự đáp lại sắc sảo', example: 'Witty repartee.', exampleVN: 'Sự đáp trả hóm hỉnh.' },
  { id: 'h378', word: 'replete', meaning: 'đầy đủ, no nê', example: 'Replete with details.', exampleVN: 'Đầy đủ các chi tiết.' },
  { id: 'h379', word: 'reprehensible', meaning: 'đáng bị chỉ trích', example: 'Reprehensible conduct.', exampleVN: 'Hành vi đáng bị chỉ trích.' },
  { id: 'h380', word: 'repress', meaning: 'đàn áp, kìm nén', example: 'Repress your emotions.', exampleVN: 'Kìm nén cảm xúc của bạn.' },
  { id: 'h381', word: 'reproach', meaning: 'chỉ trích, quở trách', example: 'Beyond reproach.', exampleVN: 'Không thể chê trách.' },
  { id: 'h382', word: 'repudiate', meaning: 'bác bỏ', example: 'Repudiate a claim.', exampleVN: 'Bác bỏ một tuyên bố.' },
  { id: 'h383', word: 'repugnant', meaning: 'đáng ghét, kinh tởm', example: 'A repugnant idea.', exampleVN: 'Một ý tưởng đáng ghét.' },
  { id: 'h384', word: 'requisite', meaning: 'điều kiện cần thiết', example: 'The requisite skills.', exampleVN: 'Các kỹ năng cần thiết.' },
  { id: 'h385', word: 'rescind', meaning: 'hủy bỏ', example: 'Rescind a contract.', exampleVN: 'Hủy bỏ một hợp đồng.' },
  { id: 'h386', word: 'resentment', meaning: 'sự phẫn uất', example: 'Feel resentment.', exampleVN: 'Cảm thấy phẫn uất.' },
  { id: 'h387', word: 'resilient', meaning: 'kiên cường', example: 'A resilient economy.', exampleVN: 'Một nền kinh tế kiên cường.' },
  { id: 'h388', word: 'resolute', meaning: 'kiên quyết', example: 'A resolute leader.', exampleVN: 'Một lãnh đạo kiên quyết.' },
  { id: 'h389', word: 'resonate', meaning: 'vang dội, cộng hưởng', example: 'The message resonates with voters.', exampleVN: 'Thông điệp cộng hưởng với cử tri.' },
  { id: 'h390', word: 'respite', meaning: 'thời gian nghỉ ngơi', example: 'A brief respite.', exampleVN: 'Một quãng nghỉ ngắn.' },
  { id: 'h391', word: 'restitution', meaning: 'sự bồi thường, hoàn lại', example: 'Make restitution.', exampleVN: 'Thực hiện bồi thường.' },
  { id: 'h392', word: 'restive', meaning: 'không yên, bồn chồn', example: 'A restive crowd.', exampleVN: 'Đám đông bồn chồn.' },
  { id: 'h393', word: 'resurgent', meaning: 'trỗi dậy', example: 'A resurgent economy.', exampleVN: 'Một nền kinh tế đang trỗi dậy.' },
  { id: 'h394', word: 'reticent', meaning: 'kín đáo, ít nói', example: 'He is reticent about his past.', exampleVN: 'Anh ta kín đáo về quá khứ của mình.' },
  { id: 'h395', word: 'retort', meaning: 'đáp trả lại', example: 'A quick retort.', exampleVN: 'Một sự đáp trả nhanh chóng.' },
  { id: 'h396', word: 'retract', meaning: 'rút lại', example: 'Retract a statement.', exampleVN: 'Rút lại một tuyên bố.' },
  { id: 'h397', word: 'retribution', meaning: 'sự báo thù', example: 'Divine retribution.', exampleVN: 'Sự báo ứng của thần linh.' },
  { id: 'h398', word: 'retroactive', meaning: 'có hiệu lực hồi tố', example: 'A retroactive pay raise.', exampleVN: 'Một lần tăng lương có hiệu lực hồi tố.' },
  { id: 'h399', word: 'revelation', meaning: 'sự tiết lộ, khải huyền', example: 'A shocking revelation.', exampleVN: 'Một sự tiết lộ gây sốc.' },
  { id: 'h400', word: 'revere', meaning: 'tôn kính', example: 'Revere a hero.', exampleVN: 'Tôn kính một vị anh hùng.' },
];
