import { Word } from './types';

export const chunk23_raw: Omit<Word, 'id'>[] = [
  { word: "mention", meaning: "đề cập/nhắc đến", example: "Mention this ad.", exampleVN: "Nhắc đến quảng cáo này." },
  { word: "figure", meaning: "con số/ số liệu", example: "First-quarter sales figures.", exampleVN: "Số liệu bán hàng quý đầu tiên." },
  { word: "fall", meaning: "giảm xuống", example: "Sales have continued to fall.", exampleVN: "Doanh số tiếp tục giảm." },
  { word: "propose", meaning: "đề xuất", example: "Propose expanding the line.", exampleVN: "Đề xuất mở rộng dòng sản phẩm." },
  { word: "virtual reality", meaning: "thực tế ảo", example: "Virtual reality headsets.", exampleVN: "Kính thực tế ảo." },
  { word: "prep", meaning: "chuẩn bị", example: "Prepping dinner.", exampleVN: "Đang chuẩn bị bữa tối." },
  { word: "available", meaning: "có sẵn, rảnh", example: "Free beverages are available.", exampleVN: "Đồ uống miễn phí luôn có sẵn." },
  { word: "display", meaning: "trưng bày", example: "Displayed in the shop window.", exampleVN: "Được trưng bày trên cửa sổ cửa hàng." },
  { word: "delicious", meaning: "thơm ngon", example: "A delicious meal.", exampleVN: "Một bữa ăn ngon." },
  { word: "quarterly report", meaning: "báo cáo quý", example: "The quarterly report.", exampleVN: "Báo cáo hàng quý." },
  { word: "florist's shop", meaning: "cửa hàng hoa", example: "Stopped by the florist's shop.", exampleVN: "Ghé qua cửa hàng hoa." },
  { word: "market analysis", meaning: "phân tích thị trường", example: "The market analysis.", exampleVN: "Bản phân tích thị trường." },
  { word: "packaging", meaning: "đóng gói, bao bì", example: "Attractive packaging.", exampleVN: "Bao bì bắt mắt." },
  { word: "sample", meaning: "mẫu thử", example: "Product samples.", exampleVN: "Mẫu sản phẩm." },
  { word: "launch", meaning: "ra mắt, tung ra", example: "Launch a new product.", exampleVN: "Ra mắt sản phẩm mới." },
  { word: "inventory", meaning: "hàng tồn kho", example: "Reduce its inventory.", exampleVN: "Giảm hàng tồn kho." },
  { word: "break room", meaning: "phòng nghỉ giải lao", example: "In the break room.", exampleVN: "Trong phòng nghỉ giải lao." },
  { word: "match the price", meaning: "khớp giá, bán bằng giá", example: "Match the price.", exampleVN: "Bán bằng giá." },
  { word: "nearby", meaning: "gần đó, lân cận", example: "A good restaurant nearby.", exampleVN: "Một nhà hàng ngon gần đây." },
  { word: "variety", meaning: "sự đa dạng, nhiều loại", example: "A wide variety of gifts.", exampleVN: "Nhiều loại quà tặng đa dạng." },
  { word: "open-air market", meaning: "chợ ngoài trời", example: "At the open-air market.", exampleVN: "Tại chợ ngoài trời." },
  { word: "target customer", meaning: "khách hàng mục tiêu", example: "Target customers.", exampleVN: "Khách hàng mục tiêu." },
  { word: "vegetarian", meaning: "người ăn chay", example: "Vegetarians.", exampleVN: "Người ăn chay." },
  { word: "product launch", meaning: "ra mắt sản phẩm", example: "Product launch.", exampleVN: "Sự ra mắt sản phẩm." },
  { word: "sales", meaning: "bán hàng/doanh số", example: "The sales meeting.", exampleVN: "Buổi họp bán hàng." },
  { word: "hardware store", meaning: "cửa hàng kim khí", example: "Hardware store.", exampleVN: "Cửa hàng đồ kim khí." },
  { word: "device", meaning: "thiết bị", example: "This device helps us.", exampleVN: "Thiết bị này giúp chúng ta." },
  { word: "aisle", meaning: "lối đi (giữa các kệ hàng)", example: "In aisle 5.", exampleVN: "Ở lối đi số 5." },
  { word: "database", meaning: "cơ sở dữ liệu", example: "Customer database.", exampleVN: "Cơ sở dữ liệu khách hàng." },
  { word: "operation", meaning: "sự vận hành, hoạt động", example: "In full operation.", exampleVN: "Hoạt động hết công suất." },
  { word: "point out", meaning: "chỉ ra", example: "Pointed out the mistake.", exampleVN: "Đã chỉ ra lỗi sai." },
  { word: "reach", meaning: "đạt tới, liên lạc được", example: "You can reach me by phone.", exampleVN: "Bạn có thể liên lạc cho tôi qua điện thoại." },
  { word: "maintenance", meaning: "sự bảo trì, bảo dưỡng", example: "Routine maintenance.", exampleVN: "Bảo trì định kỳ." },
  { word: "shut off", meaning: "tắt, ngắt (máy móc)", example: "Shut off automatically.", exampleVN: "Tự động tắt." },
  { word: "equipment", meaning: "thiết bị, dụng cụ", example: "The latest equipment.", exampleVN: "Các thiết bị mới nhất." },
  { word: "automobile", meaning: "xe ô tô", example: "The automobile industry.", exampleVN: "Ngành công nghiệp ô tô/xe hơi." },
  { word: "warranty", meaning: "sự bảo hành, giấy bảo hành", example: "Under the warranty.", exampleVN: "Chịu bảo hành." },
  { word: "worry-free", meaning: "không lo lắng, thảnh thơi", example: "Worry-free service.", exampleVN: "Dịch vụ không lo âu." },
  { word: "facilitate", meaning: "tạo điều kiện, làm cho dễ dàng", example: "Facilitate the process.", exampleVN: "Thúc đẩy quy trình." },
  { word: "incredibly", meaning: "vô cùng, cực kỳ", example: "Incredibly fast.", exampleVN: "Nhanh không tưởng." },
  { word: "manufacture", meaning: "sản xuất", example: "Manufacture car parts.", exampleVN: "Sản xuất phụ tùng ô tô." },
  { word: "apologize for", meaning: "xin lỗi vì", example: "Apologize for the delay.", exampleVN: "Xin lỗi về sự chậm trễ." },
  { word: "depart from", meaning: "khởi hành từ, khác với", example: "Depart from Gate 5.", exampleVN: "Khởi hành từ Cổng 5." },
  { word: "trial run", meaning: "chuyến chạy thử", example: "A trial run of the new system.", exampleVN: "Chạy thử hệ thống mới." },
  { word: "feature", meaning: "tính năng, đặc điểm", example: "Cool features.", exampleVN: "Các tính năng hay ho." },
  { word: "ore", meaning: "quặng", example: "Iron ore.", exampleVN: "Quặng sắt." },
  { word: "appliance", meaning: "thiết bị, đồ gia dụng", example: "Kitchen appliances.", exampleVN: "Đồ gia dụng nhà bếp." },
  { word: "estimated", meaning: "ước tính", example: "The estimated cost.", exampleVN: "Chi phí ước tính." },
  { word: "in stock", meaning: "còn hàng", example: "In stock.", exampleVN: "Có sẵn trong kho." },
  { word: "data", meaning: "dữ liệu", example: "Update the sales data.", exampleVN: "Cập nhật dữ liệu bán hàng." },
  { word: "technician", meaning: "kỹ thuật viên", example: "Our technician.", exampleVN: "Kỹ thuật viên của chúng tôi." },
  { word: "robotic", meaning: "thuộc về rô-bốt", example: "Robotic vacuum cleaner.", exampleVN: "Máy hút bụi robot." },
  { word: "technical", meaning: "thuộc về kỹ thuật", example: "Technical concepts.", exampleVN: "Những khái niệm kỹ thuật." },
  { word: "interrupt", meaning: "ngắt lời, làm phiền", example: "Interrupt your meeting.", exampleVN: "Làm gián đoạn cuộc họp của bạn." },
  { word: "industrial", meaning: "thuộc về công nghiệp", example: "An industrial zone.", exampleVN: "Một khu công nghiệp." },
  { word: "from scratch", meaning: "từ con số không, từ đầu", example: "From scratch.", exampleVN: "Từ đầu." },
  { word: "trend", meaning: "xu hướng", example: "New trends.", exampleVN: "Các xu hướng mới." },
  { word: "admire", meaning: "ngưỡng mộ", example: "I admire your work.", exampleVN: "Tôi khâm phục thành quả của bạn." },
  { word: "be known for", meaning: "nổi tiếng vì", example: "Known for making mobile phones.", exampleVN: "Được biết đến vì sản xuất điện thoại." },
  { word: "be stuck", meaning: "bị kẹt, bị mắc kẹt", example: "We're stuck.", exampleVN: "Chúng ta bị kẹt." },
  { word: "reputation", meaning: "danh tiếng, uy tín", example: "A great reputation.", exampleVN: "Danh tiếng tốt." },
  { word: "leverage", meaning: "tận dụng, đòn bẩy", example: "Leveraging social media.", exampleVN: "Tận dụng mạng xã hội." },
  { word: "constantly", meaning: "liên tục, không ngừng", example: "Constantly changing.", exampleVN: "Thay đổi liên tục." },
  { word: "home appliance", meaning: "thiết bị gia dụng", example: "Home appliances.", exampleVN: "Đồ gia dụng trong nhà." },
  { word: "follow along", meaning: "theo dõi, làm theo", example: "Follow along on your screen.", exampleVN: "Làm theo qua màn hình của bạn." },
  { word: "consumer", meaning: "người tiêu dùng", example: "Consumers.", exampleVN: "Người tiêu dùng." },
  { word: "maintain", meaning: "duy trì, bảo trì", example: "Maintain the hiking trails.", exampleVN: "Bảo trì đường mòn đi bộ." },
  { word: "run smoothly", meaning: "vận hành trôi chảy", example: "Things ran smoothly.", exampleVN: "Mọi thứ diễn ra êm đẹp." },
  { word: "participant", meaning: "người tham gia", example: "Many participants.", exampleVN: "Nhiều người tham gia." },
  { word: "vending machine", meaning: "máy bán hàng tự động", example: "Vending machines.", exampleVN: "Máy bán hàng tự động." },
  { word: "spreadsheet", meaning: "bảng tính", example: "The spreadsheet.", exampleVN: "Bảng tính." },
  { word: "warehouse", meaning: "kho hàng", example: "A large warehouse.", exampleVN: "Một nhà kho lớn." },
  { word: "return", meaning: "trả lại, quay về", example: "The item was returned.", exampleVN: "Món hàng đã được hoàn trả." },
  { word: "manufacturer", meaning: "nhà sản xuất", example: "The manufacturer.", exampleVN: "Nhà sản xuất." },
  { word: "extended", meaning: "được gia hạn, mở rộng", example: "An extended warranty.", exampleVN: "Chế độ bảo hành mở rộng." },
  { word: "promotional", meaning: "quảng cáo, quảng bá", example: "Promotional materials.", exampleVN: "Các tài liệu quảng cáo." },
  { word: "material", meaning: "tài liệu, nguyên liệu", example: "The same material.", exampleVN: "Cùng một tài liệu đó." },
  { word: "competition", meaning: "sự cạnh tranh", example: "A lot of competition.", exampleVN: "Nhiều sự cạnh tranh." },
  { word: "dispenser", meaning: "máy/hộp phân phát", example: "The soap dispenser.", exampleVN: "Hộp xà phòng." },
  { word: "pump", meaning: "cái bơm", example: "A fuel injection pump.", exampleVN: "Bơm phun nhiên liệu." }
];

export function processChunk23(): Word[] {
  return chunk23_raw.map((w, index) => {
    return {
      ...w,
      id: `c23_${index}`,
      pos: '(n/a)'
    };
  });
}
