import { Word } from './types';

export const chunk15_raw: Omit<Word, 'id'>[] = [
  { word: "analyst", meaning: "chuyên viên phân tích", example: "He's a senior research analyst.", exampleVN: "Anh ấy là chuyên viên phân tích." },
  { word: "introduction", meaning: "sự giới thiệu, phần mở đầu", example: "The introduction of your essay is interesting.", exampleVN: "Phần mở đầu rất thú vị." },
  { word: "bring in", meaning: "thu về, mang lại", example: "The new law will bring in more money.", exampleVN: "Luật sẽ mang lại nhiều tiền hơn." },
  { word: "expand", meaning: "mở rộng", example: "The company wants to expand its market.", exampleVN: "Công ty muốn mở rộng thị trường." },
  { word: "shareholder", meaning: "cổ đông", example: "The shareholders approved.", exampleVN: "Cổ đông đã chấp thuận." },
  { word: "rack", meaning: "giá đỡ, kệ", example: "Put it on the rack.", exampleVN: "Đặt nó lên kệ." },
  { word: "specialize in", meaning: "chuyên về", example: "Our company specializes in solar energy.", exampleVN: "Công ty chuyên về năng lượng mặt trời." },
  { word: "be disappointed by", meaning: "bị thất vọng bởi", example: "We were disappointed by the poor sales.", exampleVN: "Chúng tôi bị thất vọng bởi doanh số kém." },
  { word: "overseas", meaning: "ở nước ngoài", example: "He works overseas.", exampleVN: "Anh ấy làm việc ở nước ngoài." },
  { word: "inquiry", meaning: "câu hỏi, yêu cầu thông tin", example: "We received an inquiry.", exampleVN: "Chúng tôi đã nhận được một yêu cầu." },
  { word: "economical", meaning: "tiết kiệm (kinh tế)", example: "Solar power is an economical choice.", exampleVN: "Năng lượng mặt trời là lựa chọn tiết kiệm." },
  { word: "cosmetics", meaning: "mỹ phẩm", example: "She spends money on cosmetics.", exampleVN: "Cô ấy mua nhiều mỹ phẩm." },
  { word: "associate", meaning: "cộng tác viên, liên kết", example: "He is a business associate.", exampleVN: "Anh ấy là đối tác / cộng tác viên." },
  { word: "exploratory", meaning: "mang tính thăm dò", example: "Exploratory drilling.", exampleVN: "Khoan thăm dò." },
  { word: "deposit", meaning: "mỏ khoáng sản, tiền cọc", example: "Mineral deposits.", exampleVN: "Mỏ khoáng sản." },
  { word: "charge", meaning: "tính phí /đòi giá", example: "How much do you charge?", exampleVN: "Bạn tính phí bao nhiêu?" },
  { word: "conference", meaning: "hội nghị", example: "Attend the conference.", exampleVN: "Tham dự hội nghị." },
  { word: "rate", meaning: "mức giá, tỷ lệ", example: "A cheaper rate.", exampleVN: "Một mức giá rẻ hơn." },
  { word: "print version", meaning: "bản in", example: "The print version is available.", exampleVN: "Bản in đã có sẵn." },
  { word: "leadership", meaning: "sự lãnh đạo / ban lãnh đạo", example: "Improve leadership strategies.", exampleVN: "Cải thiện chiến lược lãnh đạo." },
  { word: "strategy", meaning: "chiến lược", example: "A new marketing strategy.", exampleVN: "Chiến lược tiếp thị mới." },
  { word: "advertisement", meaning: "quảng cáo", example: "We found your advertisement.", exampleVN: "Chúng tôi đã tìm thấy quảng cáo của bạn." },
  { word: "potential", meaning: "tiềm năng", example: "Potential clients.", exampleVN: "Khách hàng tiềm năng." },
  { word: "competition", meaning: "sự cạnh tranh", example: "A lot of competition.", exampleVN: "Rất nhiều sự cạnh tranh." },
  { word: "reach out", meaning: "liên lạc", example: "I will reach out to the supplier.", exampleVN: "Tôi sẽ liên lạc nhà cung cấp." },
  { word: "profit", meaning: "lợi nhuận", example: "This month's profits.", exampleVN: "Lợi nhuận tháng này." },
  { word: "charity", meaning: "hội từ thiện, việc từ thiện", example: "Give profits to charity.", exampleVN: "Đóng góp lợi nhuận cho hội từ thiện." },
  { word: "streamline", meaning: "tối ưu hóa, sắp xếp hợp lý", example: "Streamline their operations.", exampleVN: "Tối ưu hóa các hoạt động." },
  { word: "in a row", meaning: "liên tiếp", example: "Two years in a row.", exampleVN: "Hai năm liên tiếp." },
  { word: "eligible", meaning: "đủ điều kiện, đủ tư cách", example: "Eligible for a bonus.", exampleVN: "Đủ điều kiện nhận tiền thưởng." },
  { word: "calculate", meaning: "tính toán", example: "Explain how the bonus is calculated.", exampleVN: "Giải thích cách tính tiền thưởng." },
  { word: "newsletter", meaning: "bản tin nội bộ", example: "Read the company newsletter.", exampleVN: "Đọc bản tin công ty." },
  { word: "review", meaning: "xem xét, đánh giá", example: "Review the safety procedures.", exampleVN: "Xem xét các quy trình an toàn." },
  { word: "disappointing", meaning: "đáng thất vọng", example: "The results were disappointing.", exampleVN: "Kết quả đáng thất vọng." },
  { word: "decade", meaning: "thập kỷ", example: "For over two decades.", exampleVN: "Trong hơn hai thập kỷ." },
  { word: "philosophy", meaning: "triết lý", example: "Business philosophy.", exampleVN: "Triết lý kinh doanh." },
  { word: "tasting", meaning: "buổi nếm thử", example: "An olive oil tasting class.", exampleVN: "Một lớp học nếm thử dầu ô liu." },
  { word: "pricing", meaning: "cách định giá, giá cả", example: "Ask about pricing.", exampleVN: "Hỏi về giá cả." },
  { word: "headquarters", meaning: "trụ sở chính", example: "The company headquarters.", exampleVN: "Trụ sở chính công ty." },
  { word: "supplier", meaning: "nhà cung cấp", example: "Find a new supplier.", exampleVN: "Tìm nhà cung cấp mới." },
  { word: "gala", meaning: "buổi dạ tiệc", example: "The charity gala.", exampleVN: "Buổi dạ tiệc từ thiện." },
  { word: "benefit", meaning: "có lợi, lợi ích", example: "The law will benefit small businesses.", exampleVN: "Luật sẽ có lợi cho doanh nghiệp nhỏ." },
  { word: "significant", meaning: "đáng kể", example: "A significant increase.", exampleVN: "Một sự gia tăng đáng kể." },
  { word: "campaign", meaning: "chiến dịch", example: "The advertising campaign.", exampleVN: "Chiến dịch quảng cáo." },
  { word: "appreciate", meaning: "trân trọng, cảm kích", example: "I appreciate your help.", exampleVN: "Tôi trân trọng sự giúp đỡ của bạn." },
  { word: "survey", meaning: "cuộc khảo sát", example: "Complete our customer survey.", exampleVN: "Hoàn thành cuộc khảo sát khách hàng." },
  { word: "process", meaning: "xử lý / quy trình", example: "Process your loan application.", exampleVN: "Xử lý đơn xin vay vốn." },
  { word: "experience", meaning: "trải nghiệm, kinh nghiệm", example: "Years of experience.", exampleVN: "Nhiều năm kinh nghiệm." },
  { word: "in charge of", meaning: "phụ trách, chịu trách nhiệm", example: "He is in charge of the accounts.", exampleVN: "Ông ấy phụ trách các tài khoản." },
  { word: "launch", meaning: "ra mắt, thành lập", example: "Launch a new product.", exampleVN: "Ra mắt sản phẩm mới." },
  { word: "yield", meaning: "sản lượng, năng suất", example: "Increase their yields.", exampleVN: "Tăng sản lượng." },
  { word: "evaluate", meaning: "đánh giá", example: "The branch was evaluated.", exampleVN: "Chi nhánh đã được đánh giá." },
  { word: "interact", meaning: "tương tác", example: "Interact politely with customers.", exampleVN: "Tương tác lịch sự với khách hàng." },
  { word: "peak demand", meaning: "nhu cầu cao điểm", example: "Times of peak demand.", exampleVN: "Thời gian nhu cầu cao điểm." },
  { word: "feedback", meaning: "phản hồi", example: "Give positive feedback.", exampleVN: "Đưa ra phản hồi tích cực." },
  { word: "account", meaning: "tài khoản", example: "Send money to my bank account.", exampleVN: "Gửi tiền vào tài khoản ngân hàng." },
  { word: "expensive", meaning: "đắt tiền", example: "It is expensive.", exampleVN: "Nó đắt tiền." },
  { word: "picnic", meaning: "chuyến dã ngoại", example: "The company picnic.", exampleVN: "Chuyến dã ngoại công ty." },
  { word: "reschedule", meaning: "đổi lịch, sắp xếp lại", example: "I am calling to reschedule.", exampleVN: "Tôi gọi để đổi lịch." },
  { word: "landscape", meaning: "bối cảnh/toàn cảnh", example: "The advertising landscape.", exampleVN: "Bối cảnh quảng cáo." },
  { word: "stock", meaning: "tích trữ/nhập hàng", example: "Stock them before the holiday.", exampleVN: "Nhập hàng trước kỳ nghỉ." },
  { word: "statement", meaning: "sao kê (ngân hàng)", example: "A charge on my statement.", exampleVN: "Một khoản phí trên sao kê." },
  { word: "priority", meaning: "sự ưu tiên", example: "Other priorities.", exampleVN: "Những ưu tiên khác." },
  { word: "commuter", meaning: "người đi làm xa", example: "Commuters use the app.", exampleVN: "Người đi làm xa dùng ứng dụng." },
  { word: "prospective", meaning: "tiềm năng", example: "Prospective clients.", exampleVN: "Khách hàng tiềm năng." },
  { word: "subject to", meaning: "chịu tác động bởi/lệ thuộc vào", example: "Subject to change.", exampleVN: "Có thể thay đổi." },
  { word: "informative", meaning: "cung cấp nhiều thông tin", example: "The session was informative.", exampleVN: "Buổi học cung cấp nhiều thông tin." },
  { word: "perform", meaning: "biểu diễn", example: "Perform for us tonight.", exampleVN: "Biểu diễn cho chúng tôi tối nay." },
  { word: "announce", meaning: "thông báo", example: "Announce the winner.", exampleVN: "Thông báo người chiến thắng." },
  { word: "article", meaning: "bài báo", example: "An interesting article.", exampleVN: "Một bài báo thú vị." },
  { word: "in stock", meaning: "còn hàng", example: "We don't have this in stock.", exampleVN: "Chúng tôi không còn hàng." },
  { word: "consulting firm", meaning: "công ty tư vấn", example: "The consulting firm provided advice.", exampleVN: "Công ty tư vấn đã cung cấp lời khuyên." },
  { word: "agenda", meaning: "chương trình nghị sự", example: "The next item on the agenda.", exampleVN: "Mục tiếp theo trong chương trình nghị sự." },
  { word: "competitor", meaning: "đối thủ cạnh tranh", example: "Our main competitors.", exampleVN: "Các đối thủ cạnh tranh chính." },
  { word: "recurring", meaning: "lặp đi lặp lại", example: "A recurring problem.", exampleVN: "Vấn đề lặp đi lặp lại." },
  { word: "reach out to", meaning: "liên lạc với ai đó", example: "Reach out to the team.", exampleVN: "Liên lạc đội ngũ." },
  { word: "situation", meaning: "tình huống, tình hình", example: "Assess the situation.", exampleVN: "Đánh giá tình hình." },
  { word: "breakdown", meaning: "bản kê chi tiết, sự phân tích", example: "A breakdown of total costs.", exampleVN: "Bản kê chi tiết tổng chi phí." },
  { word: "branch", meaning: "chi nhánh", example: "Opened a new branch.", exampleVN: "Đã mở một chi nhánh mới." },
  { word: "expand into", meaning: "mở rộng sang", example: "Expand into international markets.", exampleVN: "Mở rộng sang thị trường quốc tế." },
  { word: "original", meaning: "nguyên bản, gốc", example: "The original plan.", exampleVN: "Kế hoạch nguyên bản." },
  { word: "worthwhile", meaning: "đáng giá, xứng đáng", example: "A worthwhile endeavor.", exampleVN: "Nỗ lực xứng đáng." },
  { word: "approve", meaning: "chấp thuận, phê duyệt", example: "Approve the loan application.", exampleVN: "Chấp thuận đơn xin vay vốn." },
  { word: "full supply", meaning: "nguồn cung đầy đủ", example: "A full supply of paper.", exampleVN: "Nguồn cung đầy đủ giấy tờ." },
  { word: "advertising", meaning: "sự quảng cáo", example: "Money spent on advertising.", exampleVN: "Tiền chi cho quảng cáo." },
  { word: "security protocol", meaning: "quy trình an ninh", example: "Revise its security protocol.", exampleVN: "Sửa đổi quy trình an ninh." },
  { word: "closet", meaning: "tủ chứa đồ", example: "The supply closet.", exampleVN: "Tủ vật tư." },
  { word: "client", meaning: "khách hàng", example: "The client asked for details.", exampleVN: "Khách hàng yêu cầu chi tiết." },
  { word: "customer review", meaning: "đánh giá của khách hàng", example: "Positive customer reviews.", exampleVN: "Những đánh giá tích cực của khách hàng." },
  { word: "retreat", meaning: "kỳ nghỉ dưỡng", example: "A company retreat.", exampleVN: "Kỳ nghỉ dưỡng công ty." },
  { word: "organize", meaning: "tổ chức, sắp xếp", example: "Organize a party.", exampleVN: "Tổ chức một bữa tiệc." },
  { word: "fund-raising", meaning: "gây quỹ", example: "A fund-raising event.", exampleVN: "Sự kiện gây quỹ." },
  { word: "release", meaning: "phát hành, giải phóng", example: "Release the new movie.", exampleVN: "Phát hành bộ phim mới." },
  { word: "videotape", meaning: "quay phim", example: "Videotape the ceremony.", exampleVN: "Quay phim buổi lễ." },
  { word: "exhibition", meaning: "cuộc triển lãm", example: "An art exhibition.", exampleVN: "Buổi triển lãm nghệ thuật." },
  { word: "press", meaning: "báo chí", example: "Covered by the local press.", exampleVN: "Được báo chí địa phương đưa tin." }
];

export function processChunk15(): Word[] {
  return chunk15_raw.map((w, index) => {
    return {
      ...w,
      id: `c15_${index}`,
      pos: '(n/a)'
    };
  });
}
