import { Word } from './types';

export const chunk11: Word[] = [
  { id: 'ext1', word: 'abandon', meaning: 'từ bỏ, bỏ rơi', example: 'They had to abandon the plan.', exampleVN: 'Họ đã phải từ bỏ kế hoạch.' },
  { id: 'ext2', word: 'abundant', meaning: 'dồi dào, phong phú', example: 'There is abundant evidence.', exampleVN: 'Có bằng chứng dồi dào.' },
  { id: 'ext3', word: 'accommodate', meaning: 'đáp ứng, cung cấp chỗ ở', example: 'The hotel can accommodate 500 guests.', exampleVN: 'Khách sạn có thể chứa 500 khách.' },
  { id: 'ext4', word: 'accurate', meaning: 'chính xác', example: 'Is the report accurate?', exampleVN: 'Báo cáo có chính xác không?' },
  { id: 'ext5', word: 'adequate', meaning: 'đầy đủ, thỏa đáng', example: 'The supply is adequate for our needs.', exampleVN: 'Nguồn cung đầy đủ cho nhu cầu của chúng tôi.' },
  { id: 'ext6', word: 'aggressive', meaning: 'quyết đoán, hung hăng', example: 'They launched an aggressive marketing campaign.', exampleVN: 'Họ đã khởi động một chiến dịch tiếp thị quyết đoán.' },
  { id: 'ext7', word: 'alert', meaning: 'cảnh báo, tỉnh táo', example: 'The security guard is always alert.', exampleVN: 'Nhân viên bảo vệ luôn tỉnh táo.' },
  { id: 'ext8', word: 'alliance', meaning: 'liên minh', example: 'The two companies formed an alliance.', exampleVN: 'Hai công ty đã thành lập một liên minh.' },
  { id: 'ext9', word: 'ambitious', meaning: 'tham vọng', example: 'The project is very ambitious.', exampleVN: 'Dự án rất tham vọng.' },
  { id: 'ext10', word: 'amend', meaning: 'sửa đổi', example: 'They voted to amend the law.', exampleVN: 'Họ đã bỏ phiếu sửa đổi luật.' },
  { id: 'ext11', word: 'analyse', meaning: 'phân tích', example: 'Analyse the data.', exampleVN: 'Phân tích dữ liệu.' },
  { id: 'ext12', word: 'apparent', meaning: 'rõ ràng', example: 'It was apparent that they were lying.', exampleVN: 'Rõ ràng là họ đang nói dối.' },
  { id: 'ext13', word: 'aptitude', meaning: 'năng khiếu', example: 'He has an aptitude for math.', exampleVN: 'Anh ấy có năng khiếu toán học.' },
  { id: 'ext14', word: 'array', meaning: 'dãy, mảng', example: 'They offer an array of services.', exampleVN: 'Họ cung cấp một loạt các dịch vụ.' },
  { id: 'ext15', word: 'assert', meaning: 'khẳng định', example: 'She asserted her rights.', exampleVN: 'Cô ấy đã khẳng định quyền của mình.' },
  { id: 'ext16', word: 'asset', meaning: 'tài sản', example: 'Good health is a great asset.', exampleVN: 'Sức khỏe tốt là một tài sản lớn.' },
  { id: 'ext17', word: 'astound', meaning: 'làm sửng sốt', example: 'The news astounded everyone.', exampleVN: 'Tin tức làm mọi người sửng sốt.' },
  { id: 'ext18', word: 'attain', meaning: 'đạt được', example: 'He attained his goal.', exampleVN: 'Anh ấy đã đạt được mục tiêu của mình.' },
  { id: 'ext19', word: 'attribute', meaning: 'thuộc tính, cho là do', example: 'She attributes her success to hard work.', exampleVN: 'Cô cho rằng thành công của mình là nhờ sự chăm chỉ.' },
  { id: 'ext20', word: 'authentic', meaning: 'đích thực, xác thực', example: 'It is an authentic document.', exampleVN: 'Đó là một tài liệu xác thực.' },
  { id: 'ext21', word: 'authorize', meaning: 'ủy quyền', example: 'Who authorized this?', exampleVN: 'Ai đã ủy quyền việc này?' },
  { id: 'ext22', word: 'automation', meaning: 'tự động hóa', example: 'Automation reduces labor costs.', exampleVN: 'Tự động hóa giúp giảm chi phí lao động.' },
  { id: 'ext23', word: 'barrier', meaning: 'rào cản', example: 'Language can be a barrier.', exampleVN: 'Ngôn ngữ có thể là một rào cản.' },
  { id: 'ext24', word: 'behalf', meaning: 'thay mặt', example: 'I am writing on behalf of my client.', exampleVN: 'Tôi đang viết thư thay mặt khách hàng của mình.' },
  { id: 'ext25', word: 'beware', meaning: 'cẩn thận, coi chừng', example: 'Beware of pickpockets.', exampleVN: 'Coi chừng móc túi.' },
  { id: 'ext26', word: 'bias', meaning: 'thành kiến', example: 'The report show a clear bias.', exampleVN: 'Báo cáo cho thấy một sự thành kiến rõ ràng.' },
  { id: 'ext27', word: 'blend', meaning: 'pha trộn', example: 'Blend the ingredients together.', exampleVN: 'Trộn các thành phần với nhau.' },
  { id: 'ext28', word: 'boost', meaning: 'thúc đẩy, tăng cường', example: 'Boost sales.', exampleVN: 'Thúc đẩy doanh số bán hàng.' },
  { id: 'ext29', word: 'bound', meaning: 'giới hạn, chắc chắn', example: 'It is bound to happen.', exampleVN: 'Nó chắc chắn sẽ xảy ra.' },
  { id: 'ext30', word: 'bureau', meaning: 'cục, văn phòng', example: 'The travel bureau is closed.', exampleVN: 'Văn phòng du lịch đã đóng cửa.' },
  { id: 'ext31', word: 'cabinet', meaning: 'tủ, nội các', example: 'Keep the files in the cabinet.', exampleVN: 'Giữ các tập tin trong tủ.' },
  { id: 'ext32', word: 'casual', meaning: 'thông thường, ngẫu nhiên', example: 'Wear casual clothes.', exampleVN: 'Mặc quần áo thông thường.' },
  { id: 'ext33', word: 'catastrophe', meaning: 'thảm họa', example: 'The flood was a catastrophe.', exampleVN: 'Trận lũ lụt là một thảm họa.' },
  { id: 'ext34', word: 'cease', meaning: 'ngừng', example: 'The rain ceased.', exampleVN: 'Mưa đã tạnh.' },
  { id: 'ext35', word: 'chamber', meaning: 'phòng, buồng', example: 'The Chamber of Commerce.', exampleVN: 'Phòng Thương mại.' },
  { id: 'ext36', word: 'chaos', meaning: 'sự hỗn loạn', example: 'The room was in chaos.', exampleVN: 'Căn phòng đang trong tình trạng hỗn loạn.' },
  { id: 'ext37', word: 'charity', meaning: 'từ thiện', example: 'Give money to charity.', exampleVN: 'Quyên góp tiền cho tổ chức từ thiện.' },
  { id: 'ext38', word: 'chronic', meaning: 'mãn tính', example: 'He suffers from chronic pain.', exampleVN: 'Anh ấy bị đau mãn tính.' },
  { id: 'ext39', word: 'cite', meaning: 'trích dẫn', example: 'Cite your sources.', exampleVN: 'Trích dẫn nguồn của bạn.' },
  { id: 'ext40', word: 'clause', meaning: 'điều khoản', example: 'Read the contract clause.', exampleVN: 'Đọc điều khoản hợp đồng.' },
  { id: 'ext41', word: 'clinical', meaning: 'lâm sàng', example: 'Clinical trials are necessary.', exampleVN: 'Thử nghiệm lâm sàng là cần thiết.' },
  { id: 'ext42', word: 'closure', meaning: 'sự đóng cửa', example: 'The closure of the factory.', exampleVN: 'Sự đóng cửa của nhà máy.' },
  { id: 'ext43', word: 'cluster', meaning: 'cụm, nhóm', example: 'A cluster of stars.', exampleVN: 'Một cụm sao.' },
  { id: 'ext44', word: 'coach', meaning: 'huấn luyện viên', example: 'The football coach.', exampleVN: 'Huấn luyện viên bóng đá.' },
  { id: 'ext45', word: 'coalition', meaning: 'sự liên minh', example: 'Form a coalition government.', exampleVN: 'Thành lập chính phủ liên minh.' },
  { id: 'ext46', word: 'coherent', meaning: 'mạch lạc', example: 'He gave a coherent explanation.', exampleVN: 'Anh ấy đã đưa ra một lời giải thích mạch lạc.' },
  { id: 'ext47', word: 'coincide', meaning: 'trùng hợp', example: 'Our vacations coincide.', exampleVN: 'Kỳ nghỉ của chúng tôi trùng nhau.' },
  { id: 'ext48', word: 'collective', meaning: 'tập thể', example: 'Collective bargaining.', exampleVN: 'Thương lượng tập thể.' },
  { id: 'ext49', word: 'collision', meaning: 'va chạm', example: 'A collision between two ships.', exampleVN: 'Sự va chạm giữa hai con tàu.' },
  { id: 'ext50', word: 'column', meaning: 'cột', example: 'Write in the left column.', exampleVN: 'Viết vào cột bên trái.' },
  { id: 'ext51', word: 'combat', meaning: 'chiến đấu', example: 'Measures to combat inflation.', exampleVN: 'Các biện pháp chống lạm phát.' },
  { id: 'ext52', word: 'commend', meaning: 'khen ngợi', example: 'He was commended for his bravery.', exampleVN: 'Anh được khen ngợi vì lòng dũng cảm.' },
  { id: 'ext53', word: 'commentary', meaning: 'bình luận', example: 'Listen to the radio commentary.', exampleVN: 'Nghe bình luận trên đài phát thanh.' },
  { id: 'ext54', word: 'commodity', meaning: 'hàng hóa', example: 'Oil is a valuable commodity.', exampleVN: 'Dầu mỏ là một loại hàng hóa có giá trị.' },
  { id: 'ext55', word: 'compel', meaning: 'bắt buộc', example: 'They were compelled to leave.', exampleVN: 'Họ buộc phải rời đi.' },
  { id: 'ext56', word: 'compensate', meaning: 'bồi thường', example: 'They compensated him for the loss.', exampleVN: 'Họ đã bồi thường thiệt hại cho anh ta.' },
  { id: 'ext57', word: 'competence', meaning: 'năng lực', example: 'Prove your competence.', exampleVN: 'Chứng minh năng lực của bạn.' },
  { id: 'ext58', word: 'compile', meaning: 'biên soạn', example: 'Compile a list of names.', exampleVN: 'Biên soạn một danh sách các tên.' },
  { id: 'ext59', word: 'complement', meaning: 'bổ sung', example: 'The white wine complements the fish.', exampleVN: 'Rượu vang trắng bổ sung cho món cá.' },
  { id: 'ext60', word: 'compliance', meaning: 'sự tuân thủ', example: 'Compliance with the regulations.', exampleVN: 'Tuân thủ các quy định.' },
  { id: 'ext61', word: 'composite', meaning: 'hợp thành', example: 'A composite material.', exampleVN: 'Một vật liệu composite.' },
  { id: 'ext62', word: 'compromise', meaning: 'thỏa hiệp', example: 'They reached a compromise.', exampleVN: 'Họ đã đạt được một sự thỏa hiệp.' },
  { id: 'ext63', word: 'concede', meaning: 'thừa nhận', example: 'He conceded defeat.', exampleVN: 'Anh thừa nhận thất bại.' },
  { id: 'ext64', word: 'conceive', meaning: 'thụ thai, quan niệm', example: 'Conceive a new idea.', exampleVN: 'Nghĩ ra một ý tưởng mới.' },
  { id: 'ext65', word: 'concrete', meaning: 'bê tông, cụ thể', example: 'Concrete evidence.', exampleVN: 'Bằng chứng cụ thể.' },
  { id: 'ext66', word: 'condemn', meaning: 'lên án', example: 'The move was condemned.', exampleVN: 'Động thái này đã bị lên án.' },
  { id: 'ext67', word: 'condense', meaning: 'ngưng tụ, cô đọng', example: 'Condense the report.', exampleVN: 'Cô đọng bản báo cáo.' },
  { id: 'ext68', word: 'confer', meaning: 'trao tặng, thảo luận', example: 'Confer with colleagues.', exampleVN: 'Thảo luận với các đồng nghiệp.' },
  { id: 'ext69', word: 'confess', meaning: 'thú tội', example: 'He confessed to the crime.', exampleVN: 'Anh ta đã thú nhận tội lỗi.' },
  { id: 'ext70', word: 'configure', meaning: 'cấu hình', example: 'Configure the software.', exampleVN: 'Cấu hình phần mềm.' },
  { id: 'ext71', word: 'confine', meaning: 'hạn chế, giam giữ', example: 'Confine your remarks to the topic.', exampleVN: 'Hạn chế nhận xét của bạn vào chủ đề.' },
  { id: 'ext72', word: 'conflict', meaning: 'xung đột', example: 'Resolving the conflict.', exampleVN: 'Giải quyết xung đột.' },
  { id: 'ext73', word: 'conform', meaning: 'tuân thủ', example: 'Conform to reach standards.', exampleVN: 'Tuân thủ các tiêu chuẩn.' },
  { id: 'ext74', word: 'confront', meaning: 'đối mặt', example: 'Confront the problem.', exampleVN: 'Đối mặt với vấn đề.' },
  { id: 'ext75', word: 'congratulate', meaning: 'chúc mừng', example: 'Congratulate him on his promotion.', exampleVN: 'Chúc mừng anh ấy được thăng chức.' },
  { id: 'ext76', word: 'congress', meaning: 'quốc hội', example: 'Member of Congress.', exampleVN: 'Thành viên Quốc hội.' },
  { id: 'ext77', word: 'conscience', meaning: 'lương tâm', example: 'A clear conscience.', exampleVN: 'Một lương tâm trong sạch.' },
  { id: 'ext78', word: 'consensus', meaning: 'sự đồng thuận', example: 'Reach a consensus.', exampleVN: 'Đạt được sự đồng thuận.' },
  { id: 'ext79', word: 'consequent', meaning: 'hậu quả', example: 'The consequent damage.', exampleVN: 'Thiệt hại hệ quả.' },
  { id: 'ext80', word: 'conserve', meaning: 'bảo tồn', example: 'Conserve energy.', exampleVN: 'Tiết kiệm năng lượng.' },
  { id: 'ext81', word: 'constitute', meaning: 'thiết lập, cấu thành', example: 'What constitutes a family?', exampleVN: 'Cái gì cấu thành một gia đình?' },
  { id: 'ext82', word: 'constrain', meaning: 'hạn chế, cưỡng ép', example: 'Financial constraints.', exampleVN: 'Các khó khăn tài chính.' },
  { id: 'ext83', word: 'consult', meaning: 'tham khảo, tư vấn', example: 'Consult a specialist.', exampleVN: 'Tham khảo ý kiến chuyên gia.' },
  { id: 'ext84', word: 'consume', meaning: 'tiêu thụ', example: 'The car consumes too much gas.', exampleVN: 'Chiếc xe tiêu thụ quá nhiều xăng.' },
  { id: 'ext85', word: 'contaminate', meaning: 'làm ô nhiễm', example: 'Contaminated water.', exampleVN: 'Nước bị ô nhiễm.' },
  { id: 'ext86', word: 'contemporary', meaning: 'đương đại', example: 'Contemporary art.', exampleVN: 'Nghệ thuật đương đại.' },
  { id: 'ext87', word: 'contempt', meaning: 'sự khinh thường', example: 'Shows contempt for the law.', exampleVN: 'Thể hiện sự khinh thường luật pháp.' },
  { id: 'ext88', word: 'contest', meaning: 'cuộc thi', example: 'A music contest.', exampleVN: 'Một cuộc thi âm nhạc.' },
  { id: 'ext89', word: 'context', meaning: 'ngữ cảnh', example: 'In the context of the meeting.', exampleVN: 'Trong ngữ cảnh của cuộc họp.' },
  { id: 'ext90', word: 'continent', meaning: 'lục địa', example: 'The continent of Asia.', exampleVN: 'Lục địa châu Á.' },
  { id: 'ext91', word: 'contradict', meaning: 'mâu thuẫn', example: 'He contradicted himself.', exampleVN: 'Anh ta đã tự mâu thuẫn chính mình.' },
  { id: 'ext92', word: 'contrary', meaning: 'trái ngược', example: 'On the contrary.', exampleVN: 'Ngược lại.' },
  { id: 'ext93', word: 'contrast', meaning: 'tương phản', example: 'In contrast to last year.', exampleVN: 'Ngược lại với năm ngoái.' },
  { id: 'ext94', word: 'contribute', meaning: 'đóng góp', example: 'Contribute to a cause.', exampleVN: 'Đóng góp cho một sự nghiệp.' },
  { id: 'ext95', word: 'controversy', meaning: 'sự tranh luận', example: 'Cause controversy.', exampleVN: 'Gây ra tranh luận.' },
  { id: 'ext96', word: 'convenience', meaning: 'sự tiện lợi', example: 'For your convenience.', exampleVN: 'Vì sự tiện lợi của bạn.' },
  { id: 'ext97', word: 'convention', meaning: 'hội nghị, quy ước', example: 'The Geneva Convention.', exampleVN: 'Công ước Geneva.' },
  { id: 'ext98', word: 'convert', meaning: 'chuyển đổi', example: 'Convert dollars into yen.', exampleVN: 'Chuyển đổi đô la sang yên.' },
  { id: 'ext99', word: 'convey', meaning: 'truyền tải', example: 'Convey a message.', exampleVN: 'Truyền tải một thông điệp.' },
  { id: 'ext100', word: 'convince', meaning: 'thuyết phục', example: 'Convince him to stay.', exampleVN: 'Thuyết phục anh ấy ở lại.' },
  { id: 'ext101', word: 'cope', meaning: 'đối phó, đương đầu', example: 'Cope with stress.', exampleVN: 'Đối phó với căng thẳng.' },
  { id: 'ext102', word: 'core', meaning: 'cốt lõi', example: 'The core values.', exampleVN: 'Các giá trị cốt lõi.' },
  { id: 'ext103', word: 'corporate', meaning: 'thuộc về doanh nghiệp', example: 'Corporate culture.', exampleVN: 'Văn hóa doanh nghiệp.' },
  { id: 'ext104', word: 'correspond', meaning: 'tương ứng, trao đổi thư từ', example: 'Does this correspond to reality?', exampleVN: 'Điều này có tương ứng với thực tế không?' },
  { id: 'ext105', word: 'corrupt', meaning: 'tham nhũng', example: 'Corrupt officials.', exampleVN: 'Các quan chức tham nhũng.' },
  { id: 'ext106', word: 'council', meaning: 'hội đồng', example: 'The city council.', exampleVN: 'Hội đồng thành phố.' },
  { id: 'ext107', word: 'counter', meaning: 'quầy, phản bác', example: 'Opposite the counter.', exampleVN: 'Đối diện quầy.' },
  { id: 'ext108', word: 'counterpart', meaning: 'đối tác, bên tương ứng', example: 'Our Japanese counterparts.', exampleVN: 'Các đối tác Nhật Bản của chúng tôi.' },
  { id: 'ext109', word: 'county', meaning: 'hạt, quận', example: 'Live in the county.', exampleVN: 'Sống ở hạt.' },
  { id: 'ext110', word: 'coupon', meaning: 'phiếu giảm giá', example: 'Use a coupon.', exampleVN: 'Sử dụng phiếu giảm giá.' },
  { id: 'ext111', word: 'courage', meaning: 'lòng can đảm', example: 'Have the courage to speak up.', exampleVN: 'Hãy can đảm để lên tiếng.' },
  { id: 'ext112', word: 'courtesy', meaning: 'sự lịch sự, nhã nhặn', example: 'Common courtesy.', exampleVN: 'Phép lịch sự thông thường.' },
  { id: 'ext113', word: 'coverage', meaning: 'phạm vi bao phủ', example: 'Insurance coverage.', exampleVN: 'Phạm vi bảo hiểm.' },
  { id: 'ext114', word: 'craft', meaning: 'thủ công', example: 'Traditional craft.', exampleVN: 'Thủ công truyền thống.' },
  { id: 'ext115', word: 'creditor', meaning: 'chủ nợ', example: 'Meeting with creditors.', exampleVN: 'Cuộc gặp với các chủ nợ.' },
  { id: 'ext116', word: 'criteria', meaning: 'tiêu chí', example: 'The evaluation criteria.', exampleVN: 'Các tiêu chí đánh giá.' },
  { id: 'ext117', word: 'critical', meaning: 'quan trọng, chỉ trích', example: 'In a critical condition.', exampleVN: 'Đang trong tình trạng nguy kịch.' },
  { id: 'ext118', word: 'crucial', meaning: 'cốt yếu', example: 'A crucial decision.', exampleVN: 'Một quyết định cốt yếu.' },
  { id: 'ext119', word: 'crude', meaning: 'thô', example: 'Crude oil.', exampleVN: 'Dầu thô.' },
  { id: 'ext120', word: 'cruise', meaning: 'du ngoạn trên biển', example: 'Go on a cruise.', exampleVN: 'Đi du lịch bằng tàu thủy.' },
  { id: 'ext121', word: 'cue', meaning: 'tín hiệu, gợi ý', example: 'Take your cue from him.', exampleVN: 'Hãy làm theo gợi ý từ anh ấy.' },
  { id: 'ext122', word: 'curiosity', meaning: 'sự tò mò', example: 'Satisfy your curiosity.', exampleVN: 'Thỏa mãn sự tò mò của bạn.' },
  { id: 'ext123', word: 'currency', meaning: 'tiền tệ', example: 'Foreign currency.', exampleVN: 'Ngoại tệ.' },
  { id: 'ext124', word: 'curriculum', meaning: 'chương trình giảng dạy', example: 'The school curriculum.', exampleVN: 'Chương trình giảng dạy của trường.' },
  { id: 'ext125', word: 'customary', meaning: 'theo phong tục', example: 'It is customary to tip.', exampleVN: 'Tiền boa là một thói quen thông thường.' },
  { id: 'ext126', word: 'dairy', meaning: 'sữa và sản phẩm từ sữa', example: 'Dairy products.', exampleVN: 'Các sản phầm từ sữa.' },
  { id: 'ext127', word: 'database', meaning: 'cơ sở dữ liệu', example: 'Update the database.', exampleVN: 'Cập nhật cơ sở dữ liệu.' },
  { id: 'ext128', word: 'deadline', meaning: 'hạn chót', example: 'Meet the deadline.', exampleVN: 'Kịp thời hạn.' },
  { id: 'ext129', word: 'debate', meaning: 'tranh luận', example: 'Political debate.', exampleVN: 'Tranh luận chính trị.' },
  { id: 'ext130', word: 'debris', meaning: 'vụn, mảnh vỡ', example: 'Debris from the explosion.', exampleVN: 'Mảnh vụn từ vụ nổ.' },
  { id: 'ext131', word: 'decade', meaning: 'thập kỷ', example: 'For over a decade.', exampleVN: 'Trong suốt hơn một thập kỷ.' },
  { id: 'ext132', word: 'declare', meaning: 'tuyên bố', example: 'Declare independence.', exampleVN: 'Tuyên bố độc lập.' },
  { id: 'ext133', word: 'dedicate', meaning: 'cống hiến', example: 'Dedicate your life to work.', exampleVN: 'Cống hiến cả cuộc đời cho công việc.' },
  { id: 'ext134', word: 'deem', meaning: 'cho là', example: 'Deemed unnecessary.', exampleVN: 'Được coi là không cần thiết.' },
  { id: 'ext135', word: 'defect', meaning: 'khuyết tật, lỗi', example: 'A manufacturing defect.', exampleVN: 'Lỗi sản xuất.' },
  { id: 'ext136', word: 'defend', meaning: 'phòng thủ, bảo vệ', example: 'Defend your country.', exampleVN: 'Bảo vệ đất nước của bạn.' },
  { id: 'ext137', word: 'deficit', meaning: 'sự thâm hụt', example: 'The budget deficit.', exampleVN: 'Thâm hụt ngân sách.' },
  { id: 'ext138', word: 'delegate', meaning: 'đại biểu, ủy quyền', example: 'Delegate tasks.', exampleVN: 'Giao phó công việc.' },
  { id: 'ext139', word: 'deliberate', meaning: 'thận trọng, cố ý', example: 'A deliberate lie.', exampleVN: 'Một lời nói dối có chủ ý.' },
  { id: 'ext140', word: 'delicate', meaning: 'tinh tế, mỏng manh', example: 'Delicate flowers.', exampleVN: 'Những bông hoa mỏng manh.' },
  { id: 'ext141', word: 'demonstrate', meaning: 'chứng minh', example: 'Demonstrate how it works.', exampleVN: 'Chứng minh cách hoạt động của nó.' },
  { id: 'ext142', word: 'denial', meaning: 'sự phủ nhận', example: 'Her denial was believed.', exampleVN: 'Lời phủ nhận của cô ấy đã được tin tưởng.' },
  { id: 'ext143', word: 'dense', meaning: 'dày đặc', example: 'A dense forest.', exampleVN: 'Một khu rừng rậm rạp.' },
  { id: 'ext144', word: 'depart', meaning: 'khởi hành', example: 'The train departs at 6.', exampleVN: 'Chuyến tàu khởi hành lúc 6 giờ.' },
  { id: 'ext145', word: 'dependence', meaning: 'sự phụ thuộc', example: 'Our dependence on oil.', exampleVN: 'Sự phụ thuộc của chúng ta vào dầu mỏ.' },
  { id: 'ext146', word: 'deposit', meaning: 'tiền đặt cọc, gửi tiền', example: 'Pay a deposit.', exampleVN: 'Trả tiền đặt cọc.' },
  { id: 'ext147', word: 'deprive', meaning: 'tước đoạt', example: 'Being deprived of sleep.', exampleVN: 'Bị mất ngủ.' },
  { id: 'ext148', word: 'derive', meaning: 'bắt nguồn từ', example: 'Derive satisfaction from work.', exampleVN: 'Tìm thấy sự hài lòng từ công việc.' },
  { id: 'ext149', word: 'descend', meaning: 'đi xuống', example: 'Descend the stairs.', exampleVN: 'Đi xuống cầu thang.' },
  { id: 'ext150', word: 'deserve', meaning: 'xứng đáng', example: 'You deserve a break.', exampleVN: 'Bạn xứng đáng được nghỉ ngơi.' },
  { id: 'ext151', word: 'designate', meaning: 'chỉ định', example: 'Designated driver.', exampleVN: 'Người lái xe được chỉ định.' },
  { id: 'ext152', word: 'desirable', meaning: 'đáng khát khao', example: 'A desirable neighborhood.', exampleVN: 'Một khu phố đáng mơ ước.' },
  { id: 'ext153', word: 'detect', meaning: 'phát hiện', example: 'Detect a gas leak.', exampleVN: 'Phát hiện rò rỉ khí gas.' },
  { id: 'ext154', word: 'deter', meaning: 'ngăn chặn', example: 'Deter crime.', exampleVN: 'Ngăn chặn tội phạm.' },
  { id: 'ext155', word: 'deteriorate', meaning: 'xấu đi', example: 'His health deteriorated.', exampleVN: 'Sức khỏe của anh ấy đã tệ đi.' },
  { id: 'ext156', word: 'diagnose', meaning: 'chẩn đoán', example: 'Diagnosed with cancer.', exampleVN: 'Được chẩn đoán bị ung thư.' },
  { id: 'ext157', word: 'diagram', meaning: 'biểu đồ', example: 'Look at the diagram.', exampleVN: 'Nhìn vào sơ đồ.' },
  { id: 'ext158', word: 'diet', meaning: 'chế độ ăn uống', example: 'A balanced diet.', exampleVN: 'Một chế độ ăn uống cân bằng.' },
  { id: 'ext159', word: 'differentiate', meaning: 'phân biệt', example: 'Differentiate between the two.', exampleVN: 'Phân biệt giữa hai cái.' },
  { id: 'ext160', word: 'diffusion', meaning: 'sự khuếch tán', example: 'The diffusion of culture.', exampleVN: 'Sự truyền bá văn hóa.' },
  { id: 'ext161', word: 'digest', meaning: 'tiêu hóa, tóm tắt', example: 'Hard to digest.', exampleVN: 'Khó tiêu.' },
  { id: 'ext162', word: 'dimension', meaning: 'kích thước', example: 'The dimensions of the box.', exampleVN: 'Kích thước của hộp.' },
  { id: 'ext163', word: 'diminish', meaning: 'giảm bớt', example: 'Our hopes diminished.', exampleVN: 'Hy vọng của chúng tôi giảm dần.' },
  { id: 'ext164', word: 'diploma', meaning: 'bằng cấp', example: 'High school diploma.', exampleVN: 'Bằng tốt nghiệp trung học.' },
  { id: 'ext165', word: 'directory', meaning: 'danh mục, danh bạ', example: 'Phone directory.', exampleVN: 'Danh bạ điện thoại.' },
  { id: 'ext166', word: 'disaster', meaning: 'thảm họa', example: 'A natural disaster.', exampleVN: 'Một thảm họa tự nhiên.' },
  { id: 'ext167', word: 'discard', meaning: 'vứt bỏ', example: 'Discard old clothes.', exampleVN: 'Vứt bỏ quần áo cũ.' },
  { id: 'ext168', word: 'discipline', meaning: 'kỷ luật', example: 'Self-discipline.', exampleVN: 'Kỷ luật tự giác.' },
  { id: 'ext169', word: 'disclose', meaning: 'tiết lộ', example: 'Disclose secrets.', exampleVN: 'Tiết lộ bí mật.' },
  { id: 'ext170', word: 'discourse', meaning: 'diễn văn, đàm thoại', example: 'Academic discourse.', exampleVN: 'Đàm thoại học thuật.' },
  { id: 'ext171', word: 'discrete', meaning: 'rời rạc', example: 'Discrete categories.', exampleVN: 'Các danh mục rời rạc.' },
  { id: 'ext172', word: 'discriminate', meaning: 'phân biệt đối xử', example: 'Discriminate against women.', exampleVN: 'Phân biệt đối xử với phụ nữ.' },
  { id: 'ext173', word: 'dismiss', meaning: 'sa thải, bác bỏ', example: 'Dismiss a claim.', exampleVN: 'Bác bỏ một yêu cầu.' },
  { id: 'ext174', word: 'disorder', meaning: 'sự rối loạn', example: 'Sleeping disorder.', exampleVN: 'Rối loạn giấc ngủ.' },
  { id: 'ext175', word: 'displace', meaning: 'thay thế, dời chỗ', example: 'Displaced workers.', exampleVN: 'Những công nhân bị sa thải.' },
  { id: 'ext176', word: 'display', meaning: 'hiển thị', example: 'Display the products.', exampleVN: 'Trưng bày các sản phẩm.' },
  { id: 'ext177', word: 'dispose', meaning: 'vứt bỏ', example: 'Dispose of waste.', exampleVN: 'Xử lý chất thải.' },
  { id: 'ext178', word: 'dispute', meaning: 'tranh chấp', example: 'A labor dispute.', exampleVN: 'Tranh chấp lao động.' },
  { id: 'ext179', word: 'disrupt', meaning: 'phá vỡ, gián đoạn', example: 'Disrupt the class.', exampleVN: 'Làm gián đoạn lớp học.' },
  { id: 'ext180', word: 'distant', meaning: 'xa xôi', example: 'A distant relative.', exampleVN: 'Một người họ hàng xa.' },
  { id: 'ext181', word: 'distinct', meaning: 'khác biệt', example: 'Two distinct patterns.', exampleVN: 'Hai mẫu khác biệt.' },
  { id: 'ext182', word: 'distort', meaning: 'xuyên tạc', example: 'Distort the truth.', exampleVN: 'Xuyên tạc sự thật.' },
  { id: 'ext183', word: 'distract', meaning: 'làm xao nhãng', example: 'Don\'t distract me.', exampleVN: 'Đừng làm tôi xao nhãng.' },
  { id: 'ext184', word: 'distribute', meaning: 'phân phối', example: 'Distribute leaflets.', exampleVN: 'Phân phát tờ rơi.' },
  { id: 'ext185', word: 'diverse', meaning: 'đa dạng', example: 'A diverse range of interests.', exampleVN: 'Một loạt các sở thích đa dạng.' },
  { id: 'ext186', word: 'divert', meaning: 'chuyển hướng', example: 'Divert traffic.', exampleVN: 'Chuyển hướng giao thông.' },
  { id: 'ext187', word: 'divine', meaning: 'thần thánh', example: 'Divine grace.', exampleVN: 'Ân điển thiêng liêng.' },
  { id: 'ext188', word: 'document', meaning: 'tài liệu', example: 'Sign the document.', exampleVN: 'Ký vào tài liệu.' },
  { id: 'ext189', word: 'domain', meaning: 'miền, lĩnh vực', example: 'In the public domain.', exampleVN: 'Trong phạm vi công cộng.' },
  { id: 'ext190', word: 'domestic', meaning: 'nội địa', example: 'Domestic flights.', exampleVN: 'Các chuyến bay nội địa.' },
  { id: 'ext191', word: 'dominant', meaning: 'thống trị', example: 'The dominant player.', exampleVN: 'Người chơi chiếm ưu thế.' },
  { id: 'ext192', word: 'donate', meaning: 'quyên góp', example: 'Donate blood.', exampleVN: 'Hiến máu.' },
  { id: 'ext193', word: 'doom', meaning: 'số phận bi thảm', example: 'Doomed to fail.', exampleVN: 'Bị định sẵn là thất bại.' },
  { id: 'ext194', word: 'dormitory', meaning: 'ký túc xá', example: 'Live in a dormitory.', exampleVN: 'Sống trong ký túc xá.' },
  { id: 'ext195', word: 'dose', meaning: 'liều lượng', example: 'Take a dose of medicine.', exampleVN: 'Uống một liều thuốc.' },
  { id: 'ext196', word: 'dotted', meaning: 'có chấm', example: 'A dotted line.', exampleVN: 'Một đường đứt nét.' },
  { id: 'ext197', word: 'drain', meaning: 'thoát nước, cạn kiệt', example: 'Drain the water.', exampleVN: 'Tháo nước.' },
  { id: 'ext198', word: 'drastic', meaning: 'quyết liệt', example: 'Drastic changes.', exampleVN: 'Những thay đổi quyết liệt.' },
  { id: 'ext199', word: 'drought', meaning: 'hạn hán', example: 'The region suffered from drought.', exampleVN: 'Vùng này bị hạn hán.' },
  { id: 'ext200', word: 'dull', meaning: 'đần độn, xỉn, nhàm chán', example: 'A dull knife.', exampleVN: 'Một con dao cùn.' }
];

export const processChunk11 = () => {
    const nouns = new Set(['alliance', 'aptitude', 'array', 'asset', 'barrier', 'bias', 'bureau', 'cabinet', 'catastrophe', 'chamber', 'chaos', 'charity', 'clause', 'closure', 'cluster', 'coach', 'coalition', 'collision', 'column', 'commentary', 'commodity', 'competence', 'compliance', 'compromise', 'conflict', 'congress', 'conscience', 'consensus', 'contest', 'context', 'continent', 'controversy', 'convenience', 'convention', 'core', 'council', 'counter', 'counterpart', 'county', 'coupon', 'courage', 'courtesy', 'coverage', 'craft', 'creditor', 'criteria', 'cruise', 'cue', 'curiosity', 'currency', 'curriculum', 'dairy', 'database', 'deadline', 'debate', 'debris', 'decade', 'defect', 'deficit', 'denial', 'dependence', 'deposit', 'diagram', 'diet', 'diffusion', 'dimension', 'diploma', 'directory', 'disaster', 'discipline', 'discourse', 'disorder', 'dispute', 'domain', 'doom', 'dormitory', 'dose', 'drought']);
    const adjs = new Set(['abundant', 'accurate', 'adequate', 'aggressive', 'alert', 'ambitious', 'apparent', 'authentic', 'casual', 'chronic', 'clinical', 'coherent', 'collective', 'composite', 'concrete', 'consequent', 'contemporary', 'contrary', 'customary', 'delicate', 'dense', 'desirable', 'discrete', 'distant', 'distinct', 'diverse', 'divine', 'domestic', 'dominant', 'dotted', 'drastic', 'dull']);
    
    return chunk11.map(w => {
        let pos = '(v)';
        if (nouns.has(w.word)) pos = '(n)';
        else if (adjs.has(w.word)) pos = '(adj)';
        return { ...w, pos };
    });
};
