import { Word } from './types';

export const chunk19_raw: Omit<Word, 'id'>[] = [
  { word: "draft", meaning: "bản thảo", example: "First draft of my report.", exampleVN: "Bản thảo đầu tiên của báo cáo." },
  { word: "summary", meaning: "bản tóm tắt", example: "Give me a summary.", exampleVN: "Cho tôi một bản tóm tắt." },
  { word: "mine", meaning: "mỏ", example: "Working in a gold mine.", exampleVN: "Làm việc trong mỏ vàng." },
  { word: "get through", meaning: "hoàn thành, giải quyết xong", example: "Get through today.", exampleVN: "Giải quyết xong hôm nay." },
  { word: "out of the office", meaning: "không có mặt ở văn phòng", example: "I am out of the office.", exampleVN: "Tôi không có ở văn phòng." },
  { word: "submit", meaning: "nộp / đệ trình", example: "Submit my application.", exampleVN: "Nộp đơn ứng tuyển của tôi." },
  { word: "inbox", meaning: "hộp thư đến", example: "Check your inbox.", exampleVN: "Kiểm tra hộp thư đến của bạn." },
  { word: "candidate", meaning: "ứng viên", example: "Potential candidates.", exampleVN: "Ứng viên tiềm năng." },
  { word: "colleague", meaning: "đồng nghiệp", example: "A former colleague.", exampleVN: "Một đồng nghiệp cũ." },
  { word: "publication", meaning: "ấn phẩm, sự xuất bản", example: "Released in a trade publication.", exampleVN: "Được xuất bản trong một ấn phẩm." },
  { word: "challenging", meaning: "đầy thách thức, khó khăn", example: "The meeting was challenging.", exampleVN: "Cuộc họp rất thách thức." },
  { word: "retire", meaning: "nghỉ hưu", example: "Planning to retire.", exampleVN: "Dự định nghỉ hưu." },
  { word: "handout", meaning: "tài liệu phát tay", example: "Here is a handout.", exampleVN: "Đây là tài liệu phát tay." },
  { word: "new hire", meaning: "nhân viên mới", example: "Some tips to the new hire.", exampleVN: "Một vài lời khuyên cho nhân viên mới." },
  { word: "initiative", meaning: "sáng kiến, kế hoạch mới", example: "About this initiative.", exampleVN: "Về sáng kiến này." },
  { word: "reward", meaning: "thưởng / phần thưởng", example: "Reward your hard work.", exampleVN: "Thưởng cho sự chăm chỉ của bạn." },
  { word: "monetary", meaning: "thuộc về tiền tệ", example: "Monetary reward.", exampleVN: "Phần thưởng bằng tiền." },
  { word: "work remotely", meaning: "làm việc từ xa", example: "Work remotely twice a week.", exampleVN: "Làm việc từ xa hai lần tuần." },
  { word: "register", meaning: "đăng ký", example: "Find out how to register.", exampleVN: "Tìm hiểu cách đăng ký." },
  { word: "resurface", meaning: "làm lại bề mặt (đường)", example: "Closed for resurfacing work.", exampleVN: "Đóng cửa làm lại bề mặt." },
  { word: "latest", meaning: "mới nhất", example: "More details in the latest report.", exampleVN: "Chi tiết trong báo cáo mới nhất." },
  { word: "physically", meaning: "về mặt thể chất", example: "Not physically demanding.", exampleVN: "Không đòi hỏi về thể chất." },
  { word: "hiring", meaning: "việc tuyển dụng", example: "Freezing all hiring.", exampleVN: "Dừng mọi việc tuyển dụng." },
  { word: "firm", meaning: "công ty, hãng", example: "Works for a law firm.", exampleVN: "Làm việc cho công ty luật." },
  { word: "directory", meaning: "danh bạ, sách hướng dẫn", example: "Find his number in the directory.", exampleVN: "Tìm số điện thoại trong danh bạ." },
  { word: "workshop", meaning: "buổi hội thảo, buổi đào tạo", example: "Workshop on Friday.", exampleVN: "Buổi hội thảo vào thứ Sáu." },
  { word: "join", meaning: "tham gia, gia nhập", example: "Join our book club.", exampleVN: "Tham gia câu lạc bộ sách." },
  { word: "department", meaning: "phòng ban, bộ phận", example: "Each department.", exampleVN: "Mỗi phòng ban." },
  { word: "storage", meaning: "lưu trữ, kho chứa", example: "Storage space.", exampleVN: "Không gian lưu trữ." },
  { word: "qualification", meaning: "trình độ chuyên môn, bằng cấp", example: "Qualifications for this position.", exampleVN: "Chứng chỉ cho vị trí này." },
  { word: "unexpected", meaning: "bất ngờ, không mong đợi", example: "An unexpected client meeting.", exampleVN: "Cuộc họp khách hàng bất ngờ." },
  { word: "résumé", meaning: "sơ yếu lý lịch", example: "Send your résumé.", exampleVN: "Gửi sơ yếu lý lịch của bạn." },
  { word: "efficient", meaning: "hiệu quả", example: "A more efficient way.", exampleVN: "Một cách làm việc hiệu quả hơn." },
  { word: "contract", meaning: "hợp đồng", example: "Read the contract.", exampleVN: "Đọc hợp đồng." },
  { word: "certainly", meaning: "chắc chắn, dĩ nhiên", example: "I will certainly help you.", exampleVN: "Tôi chắc chắn sẽ giúp bạn." },
  { word: "division", meaning: "bộ phận, phân điểm", example: "Research and development division.", exampleVN: "Bộ phận nghiên cứu và phát triển." },
  { word: "assignment", meaning: "nhiệm vụ, công việc được giao", example: "Work assignments.", exampleVN: "Nhiệm vụ công việc." },
  { word: "recordkeeping", meaning: "việc lưu trữ hồ sơ", example: "Company's recordkeeping.", exampleVN: "Việc lưu trữ hồ sơ của công ty." },
  { word: "replace", meaning: "thay thế", example: "Being replaced.", exampleVN: "Đang bị thay thế." },
  { word: "prefer", meaning: "thích hơn", example: "Prefer working with a team.", exampleVN: "Thích làm việc với nhóm hơn." },
  { word: "usually", meaning: "thường xuyên", example: "Usually come in.", exampleVN: "Thường xuyên đến." },
  { word: "identification", meaning: "giấy tờ tùy thân, sự nhận dạng", example: "Valid identification.", exampleVN: "Giấy tờ tùy thân hợp lệ." },
  { word: "accounting", meaning: "kế toán", example: "Accounting department.", exampleVN: "Bộ phận kế toán." },
  { word: "expire", meaning: "hết hạn", example: "Contract will expire.", exampleVN: "Hợp đồng sẽ hết hạn." },
  { word: "renew", meaning: "gia hạn, làm mới", example: "Renew the vendor contracts.", exampleVN: "Gia hạn hợp đồng nhà cung cấp." },
  { word: "forward", meaning: "chuyển tiếp (email)", example: "Forward me the e-mail.", exampleVN: "Chuyển tiếp e-mail cho tôi." },
  { word: "remote", meaning: "từ xa", example: "Remote workers.", exampleVN: "Những nhân viên làm từ xa." },
  { word: "workstation", meaning: "vị trí làm việc", example: "Finding a workstation.", exampleVN: "Tìm vị trí làm việc." },
  { word: "finalize", meaning: "hoàn tất", example: "Finalize by noon.", exampleVN: "Hoàn tất trước buổi trưa." },
  { word: "influencer", meaning: "người có sức ảnh hưởng", example: "Online influencer.", exampleVN: "Người có sức ảnh hưởng trực tuyến." },
  { word: "appropriate", meaning: "phù hợp", example: "An appropriate workstation.", exampleVN: "Một vị trí làm việc phù hợp." },
  { word: "recognition", meaning: "sự công nhận/ghi nhận", example: "Contributions need more recognition.", exampleVN: "Đóng góp cần được ghi nhận nhiều hơn." },
  { word: "persuade", meaning: "thuyết phục", example: "Persuade them to listen.", exampleVN: "Thuyết phục họ lắng nghe." },
  { word: "staffing", meaning: "nhân sự", example: "Staffing needs.", exampleVN: "Nhu cầu nhân sự." },
  { word: "progress report", meaning: "báo cáo tiến độ", example: "A progress report.", exampleVN: "Một bản báo cáo tiến độ." },
  { word: "sort through", meaning: "phân loại, sắp xếp", example: "Sort through these documents.", exampleVN: "Sắp xếp những tài liệu này." },
  { word: "file cabinet", meaning: "tủ đựng hồ sơ", example: "Top drawer of the file cabinet.", exampleVN: "Ngăn trên cùng của tủ hồ sơ." },
  { word: "exterior", meaning: "bên ngoài, ngoại thất", example: "Exterior walls.", exampleVN: "Tường bên ngoài." },
  { word: "budget report", meaning: "báo cáo ngân sách", example: "Annual budget report.", exampleVN: "Báo cáo ngân sách hàng năm." },
  { word: "expense report", meaning: "báo cáo chi phí", example: "Submit your expense report.", exampleVN: "Nộp báo cáo chi phí." },
  { word: "available", meaning: "rảnh, có sẵn", example: "Available to talk.", exampleVN: "Rảnh để nói chuyện." },
  { word: "human resources", meaning: "phòng nhân sự", example: "Submit to human resources.", exampleVN: "Nộp cho phòng nhân sự." },
  { word: "onboarding", meaning: "quá trình hội nhập nhân viên mới", example: "The onboarding process.", exampleVN: "Quá trình hội nhập." },
  { word: "commitment", meaning: "cam kết, nhiệm vụ đã hứa", example: "A lot of work commitments.", exampleVN: "Rất nhiều nhiệm vụ đã cam kết." },
  { word: "impressed", meaning: "bị ấn tượng", example: "Was impressed with.", exampleVN: "Việc đã bị ấn tượng với." },
  { word: "catch up", meaning: "bắt kịp (công việc, tin tức)", example: "Catch up on my emails.", exampleVN: "Bắt kịp để đọc emails." },
  { word: "progress", meaning: "tiến triển, tiến bộ", example: "Progressing slowly.", exampleVN: "Đang tiến triển chậm." },
  { word: "resolve", meaning: "giải quyết", example: "Resolve the conflict.", exampleVN: "Giải quyết xung đột." },
  { word: "confident", meaning: "tự tin", example: "I am confident that.", exampleVN: "Tôi tự tin rằng." },
  { word: "sales figures", meaning: "số liệu doanh thu", example: "Analyzing the sales figures.", exampleVN: "Đang phân tích số liệu doanh thu." },
  { word: "congratulate", meaning: "chúc mừng", example: "Congratulate you.", exampleVN: "Chúc mừng bạn." },
  { word: "submission", meaning: "bản nộp, hồ sơ nộp", example: "Submission of reports.", exampleVN: "Hồ sơ nộp của các báo cáo." },
  { word: "review process", meaning: "quy trình xem xét", example: "The review process.", exampleVN: "Quy trình xem xét." },
  { word: "normally", meaning: "thông thường", example: "Normally we start work.", exampleVN: "Thông thường chúng tôi bắt đầu." },
  { word: "on behalf of", meaning: "thay mặt cho", example: "On behalf of my manager.", exampleVN: "Thay mặt cho quản lý." },
  { word: "familiarize yourself", meaning: "làm quen với cái gì", example: "Familiarize yourself with the rules.", exampleVN: "Làm quen với các quy định." },
  { word: "in-depth", meaning: "chuyên sâu, kỹ lưỡng", example: "An in-depth analysis.", exampleVN: "Một phân tích chuyên sâu." }
];

export function processChunk19(): Word[] {
  return chunk19_raw.map((w, index) => {
    return {
      ...w,
      id: `c19_${index}`,
      pos: '(n/a)'
    };
  });
}
