import { Word } from './types';

export const chunk7: Word[] = [
  { id: '801', word: 'award', meaning: 'giải thưởng', example: 'Win an award.', exampleVN: 'Giành được một giải thưởng.' },
  { id: '802', word: 'aware', meaning: 'nhận thức', example: 'Be aware of.', exampleVN: 'Nhận thức được.' },
  { id: '803', word: 'awareness', meaning: 'sự nhận thức', example: 'Brand awareness.', exampleVN: 'Nhận thức về thương hiệu.' },
  { id: '804', word: 'away', meaning: 'xa', example: 'Go away.', exampleVN: 'Rời đi.' },
  { id: '805', word: 'background', meaning: 'nền tảng', example: 'Check background.', exampleVN: 'Kiểm tra lý lịch.' },
  { id: '806', word: 'baggage', meaning: 'hành lý', example: 'Baggage claim.', exampleVN: 'Nhận lại hành lý.' },
  { id: '807', word: 'balance', meaning: 'số dư, cân bằng', example: 'Bank balance.', exampleVN: 'Số dư ngân hàng.' },
  { id: '808', word: 'bankrupt', meaning: 'phá sản', example: 'Go bankrupt.', exampleVN: 'Phá sản.' },
  { id: '809', word: 'barely', meaning: 'hầu như không', example: 'Barely enough.', exampleVN: 'Vừa đủ.' },
  { id: '810', word: 'barrier', meaning: 'rào cản', example: 'Language barrier.', exampleVN: 'Rào cản ngôn ngữ.' },
  { id: '811', word: 'base', meaning: 'cơ sở', example: 'Customer base.', exampleVN: 'Cơ sở khách hàng.' },
  { id: '812', word: 'basic', meaning: 'cơ bản', example: 'Basic needs.', exampleVN: 'Những nhu cầu cơ bản.' },
  { id: '813', word: 'basis', meaning: 'nền tảng, cơ sở', example: 'Daily basis.', exampleVN: 'Cơ sở hàng ngày.' },
  { id: '814', word: 'bear', meaning: 'chịu đựng', example: 'Bear the cost.', exampleVN: 'Chịu chi phí.' },
  { id: '815', word: 'beat', meaning: 'đánh bại', example: 'Beat the competition.', exampleVN: 'Đánh bại đối thủ.' },
  { id: '816', word: 'behalf', meaning: 'đại diện', example: 'On behalf of.', exampleVN: 'Thay mặt.' },
  { id: '817', word: 'behave', meaning: 'cư xử', example: 'Behave well.', exampleVN: 'Cư xử tốt.' },
  { id: '818', word: 'behavior', meaning: 'hành vi', example: 'Consumer behavior.', exampleVN: 'Hành vi của người tiêu dùng.' },
  { id: '819', word: 'belief', meaning: 'niềm tin', example: 'Strong belief.', exampleVN: 'Niềm tin mạnh mẽ.' },
  { id: '820', word: 'belong', meaning: 'thuộc về', example: 'Belong to us.', exampleVN: 'Thuộc về chúng ta.' },
  { id: '821', word: 'below', meaning: 'dưới', example: 'See below.', exampleVN: 'Xem bên dưới.' },
  { id: '822', word: 'belt', meaning: 'thắt lưng', example: 'Seat belt.', exampleVN: 'Dây an toàn.' },
  { id: '823', word: 'bench', meaning: 'ghế dài', example: 'Park bench.', exampleVN: 'Ghế đá công viên.' },
  { id: '824', word: 'benchmark', meaning: 'tiêu chuẩn', example: 'Set a benchmark.', exampleVN: 'Thiết lập một tiêu chuẩn.' },
  { id: '825', word: 'beneath', meaning: 'bên dưới', example: 'Beneath the surface.', exampleVN: 'Ở bên dưới bề mặt.' },
  { id: '826', word: 'benefit', meaning: 'lợi ích', example: 'Fringe benefit.', exampleVN: 'Lợi ích phụ.' },
  { id: '827', word: 'besides', meaning: 'ngoài ra', example: 'Besides that.', exampleVN: 'Bên cạnh đó.' },
  { id: '828', word: 'beyond', meaning: 'vượt ra ngoài', example: 'Beyond expectations.', exampleVN: 'Vượt quá sự mong đợi.' },
  { id: '829', word: 'bias', meaning: 'thiên vị', example: 'Show bias.', exampleVN: 'Thể hiện sự thiên vị.' },
  { id: '830', word: 'bid', meaning: 'đấu thầu', example: 'Winning bid.', exampleVN: 'Trúng thầu.' },
  { id: '831', word: 'bill', meaning: 'hóa đơn', example: 'Pay the bill.', exampleVN: 'Thanh toán hóa đơn.' },
  { id: '832', word: 'bind', meaning: 'ràng buộc', example: 'Bind together.', exampleVN: 'Gắn kết với nhau.' },
  { id: '833', word: 'biography', meaning: 'tiểu sử', example: 'Read a biography.', exampleVN: 'Đọc tiểu sử.' },
  { id: '834', word: 'bitter', meaning: 'đắng', example: 'Bitter taste.', exampleVN: 'Nếm vị đắng.' },
  { id: '835', word: 'blame', meaning: 'đổ lỗi', example: 'Take the blame.', exampleVN: 'Nhận lỗi.' },
  { id: '836', word: 'blank', meaning: 'trống', example: 'Blank page.', exampleVN: 'Để trống trang.' },
  { id: '837', word: 'blind', meaning: 'mù', example: 'Blind spot.', exampleVN: 'Tạo điểm mù.' },
  { id: '838', word: 'block', meaning: 'khối, chặn', example: 'Block the road.', exampleVN: 'Chặn đường.' },
  { id: '839', word: 'blood', meaning: 'máu', example: 'Blood test.', exampleVN: 'Xét nghiệm máu.' },
  { id: '840', word: 'blow', meaning: 'thổi', example: 'Blow the wind.', exampleVN: 'Thổi gió.' },
  { id: '841', word: 'board', meaning: 'bảng, ban quản trị', example: 'Board of directors.', exampleVN: 'Có ban giám đốc.' },
  { id: '842', word: 'boast', meaning: 'khoe khoang', example: 'Boast about.', exampleVN: 'Khoe khoang về điều đó.' },
  { id: '843', word: 'bond', meaning: 'trái phiếu, liên kết', example: 'Government bond.', exampleVN: 'Trái phiếu chính phủ.' },
  { id: '844', word: 'bone', meaning: 'xương', example: 'Broken bone.', exampleVN: 'Xương gãy.' },
  { id: '845', word: 'bonus', meaning: 'tiền thưởng', example: 'Annual bonus.', exampleVN: 'Tiền thưởng hàng năm.' },
  { id: '846', word: 'book', meaning: 'đặt trước', example: 'Book a flight.', exampleVN: 'Đặt một chuyến bay.' },
  { id: '847', word: 'boost', meaning: 'thúc đẩy', example: 'Boost sales.', exampleVN: 'Tăng doanh số bán hàng.' },
  { id: '848', word: 'border', meaning: 'biên giới', example: 'Cross the border.', exampleVN: 'Vượt biên.' },
  { id: '849', word: 'bother', meaning: 'làm phiền', example: "Don't bother.", exampleVN: "Đừng bận tâm." },
  { id: '850', word: 'bottom', meaning: 'đáy', example: 'Rock bottom.', exampleVN: 'Đáy đá.' },
  { id: '851', word: 'bound', meaning: 'ràng buộc', example: 'Bound by law.', exampleVN: 'Bị ràng buộc bởi pháp luật.' },
  { id: '852', word: 'boundary', meaning: 'ranh giới', example: 'Cross the boundary.', exampleVN: 'Vượt qua ranh giới.' },
  { id: '853', word: 'brain', meaning: 'não', example: 'Brain storming.', exampleVN: 'Động não.' },
  { id: '854', word: 'branch', meaning: 'chi nhánh', example: 'Local branch.', exampleVN: 'Chi nhánh địa phương.' },
  { id: '855', word: 'brand', meaning: 'thương hiệu', example: 'Brand name.', exampleVN: 'Có thương hiệu.' },
  { id: '856', word: 'bread', meaning: 'bánh mì', example: 'Bake bread.', exampleVN: 'Nướng bánh mì.' },
  { id: '857', word: 'break', meaning: 'phá vỡ, giờ nghỉ', example: 'Take a break.', exampleVN: 'Nghỉ ngơi.' },
  { id: '858', word: 'breakdown', meaning: 'sự cố', example: 'Machine breakdown.', exampleVN: 'Sự cố máy móc.' },
  { id: '859', word: 'breakfast', meaning: 'bữa sáng', example: 'Eat breakfast.', exampleVN: 'Ăn sáng.' },
  { id: '861', word: 'breath', meaning: 'hơi thở', example: 'Deep breath.', exampleVN: 'Hơi thở sâu.' },
  { id: '862', word: 'breathe', meaning: 'thở', example: 'Breathe freely.', exampleVN: 'Thở tự do.' },
  { id: '863', word: 'brick', meaning: 'gạch', example: 'Brick wall.', exampleVN: 'Xây tường gạch.' },
  { id: '864', word: 'bridge', meaning: 'cây cầu', example: 'Build a bridge.', exampleVN: 'Xây dựng một cây cầu.' },
  { id: '865', word: 'brief', meaning: 'ngắn gọn', example: 'Brief meeting.', exampleVN: 'Một cuộc gặp ngắn gọn.' },
  { id: '866', word: 'briefly', meaning: 'ngắn gọn', example: 'Speak briefly.', exampleVN: 'Nói ngắn gọn.' },
  { id: '867', word: 'brilliant', meaning: 'rực rỡ', example: 'Brilliant idea.', exampleVN: 'Có ý tưởng tuyệt vời.' },
  { id: '868', word: 'bring', meaning: 'mang lại', example: 'Bring success.', exampleVN: 'Mang lại thành công.' },
  { id: '869', word: 'broad', meaning: 'rộng', example: 'Broad range.', exampleVN: 'Có phạm vi rộng.' },
  { id: '870', word: 'broadcast', meaning: 'phát sóng', example: 'News broadcast.', exampleVN: 'Phát sóng tin tức.' },
  { id: '871', word: 'brother', meaning: 'anh em', example: 'My brother.', exampleVN: 'Họ thảo luận về anh trai tôi.' },
  { id: '872', word: 'brown', meaning: 'màu nâu', example: 'Brown shoes.', exampleVN: 'Đôi giày màu nâu.' },
  { id: '873', word: 'brush', meaning: 'bàn chải', example: 'Paint brush.', exampleVN: 'Cọ sơn.' },
  { id: '874', word: 'bubble', meaning: 'bong bóng', example: 'Housing bubble.', exampleVN: 'Bong bóng nhà ở.' },
  { id: '875', word: 'budget', meaning: 'ngân sách', example: 'Strict budget.', exampleVN: 'Ngân sách nghiêm ngặt.' },
  { id: '876', word: 'build', meaning: 'xây dựng', example: 'Build a house.', exampleVN: 'Xây một ngôi nhà.' },
  { id: '877', word: 'bulk', meaning: 'số lượng lớn', example: 'Buy in bulk.', exampleVN: 'Mua với số lượng lớn.' },
  { id: '878', word: 'bulletin', meaning: 'bản tin', example: 'News bulletin.', exampleVN: 'Bản tin thời sự.' },
  { id: '879', word: 'bunch', meaning: 'một bó', example: 'Bunch of keys.', exampleVN: 'Chùm chìa khóa.' },
  { id: '880', word: 'burden', meaning: 'gánh nặng', example: 'Heavy burden.', exampleVN: 'Gánh nặng.' },
  { id: '881', word: 'burn', meaning: 'đốt', example: 'Burn completely.', exampleVN: 'Đốt cháy hoàn toàn.' },
  { id: '882', word: 'burst', meaning: 'nổ', example: 'Burst open.', exampleVN: 'Nổ tung.' },
  { id: '883', word: 'bury', meaning: 'chôn', example: 'Bury the hatchet.', exampleVN: 'Chôn cái rìu.' },
  { id: '884', word: 'bus', meaning: 'xe buýt', example: 'Take the bus.', exampleVN: 'Đi xe buýt.' },
  { id: '885', word: 'bush', meaning: 'bụi cây', example: 'Hide in the bush.', exampleVN: 'Trốn trong bụi rậm.' },
  { id: '886', word: 'business', meaning: 'kinh doanh', example: 'Doing business.', exampleVN: 'Kinh doanh.' },
  { id: '887', word: 'busy', meaning: 'bận rộn', example: 'Busy schedule.', exampleVN: 'Có lịch trình bận rộn.' },
  { id: '888', word: 'button', meaning: 'nút bấm', example: 'Push the button.', exampleVN: 'Nhấn nút.' },
  { id: '889', word: 'buyer', meaning: 'người mua', example: 'Potential buyer.', exampleVN: 'Người mua tiềm năng.' },
  { id: '890', word: 'cabinet', meaning: 'tủ đựng', example: 'File cabinet.', exampleVN: 'Tủ hồ sơ.' },
  { id: '891', word: 'cable', meaning: 'dây cáp', example: 'Cable TV.', exampleVN: 'Truyền hình cáp.' },
  { id: '892', word: 'calculate', meaning: 'tính toán', example: 'Calculate costs.', exampleVN: 'Tính toán chi phí.' },
  { id: '893', word: 'calculation', meaning: 'sự tính toán', example: 'Exact calculation.', exampleVN: 'Tính toán chính xác.' },
  { id: '894', word: 'calendar', meaning: 'lịch', example: 'Mark the calendar.', exampleVN: 'Đánh dấu lịch.' },
  { id: '895', word: 'campaign', meaning: 'chiến dịch', example: 'Ad campaign.', exampleVN: 'Chiến dịch quảng cáo.' },
  { id: '896', word: 'camping', meaning: 'cắm trại', example: 'Go camping.', exampleVN: 'Đi cắm trại.' },
  { id: '897', word: 'cancel', meaning: 'hủy bỏ', example: 'Cancel orders.', exampleVN: 'Hủy đơn hàng.' },
  { id: '898', word: 'cancer', meaning: 'ung thư', example: 'Lung cancer.', exampleVN: 'Ung thư phổi.' },
  { id: '899', word: 'candidate', meaning: 'ứng viên', example: 'Good candidate.', exampleVN: 'Ứng viên tốt.' },
  { id: '900', word: 'capable', meaning: 'có khả năng', example: 'Fully capable.', exampleVN: 'Năng lực đầy đủ.' }
];

export const processChunk7 = () => chunk7;
