import { Word } from './types';

export const chunkHard2: Word[] = [
  { id: 'h101', word: 'ameliorate', meaning: 'cải thiện', example: 'Efforts to ameliorate working conditions.', exampleVN: 'Nỗ lực cải thiện điều kiện làm việc.' },
  { id: 'h102', word: 'auspicious', meaning: 'tốt lành, thuận lợi', example: 'An auspicious start to the project.', exampleVN: 'Một khởi đầu thuận lợi cho dự án.' },
  { id: 'h103', word: 'burgeon', meaning: 'phát triển nhanh', example: 'The tech industry continues to burgeon.', exampleVN: 'Ngành công nghệ tiếp tục phát triển nhanh.' },
  { id: 'h104', word: 'cacophony', meaning: 'tiếng ồn chói tai', example: 'A cacophony of car horns.', exampleVN: 'Tiếng còi xe inh ỏi.' },
  { id: 'h105', word: 'capitulate', meaning: 'đầu hàng', example: 'The company capitulated to union demands.', exampleVN: 'Công ty đầu hàng trước yêu cầu công đoàn.' },
  { id: 'h106', word: 'confiscate', meaning: 'tịch thu', example: 'Customs officers confiscated the goods.', exampleVN: 'Nhân viên hải quan tịch thu hàng hóa.' },
  { id: 'h107', word: 'corroborate', meaning: 'chứng thực', example: 'Evidence to corroborate his story.', exampleVN: 'Bằng chứng chứng thực câu chuyện của anh.' },
  { id: 'h108', word: 'debacle', meaning: 'thất bại thảm hại', example: 'The product launch was a debacle.', exampleVN: 'Việc ra mắt sản phẩm là một thảm họa.' },
  { id: 'h109', word: 'debilitate', meaning: 'làm suy yếu', example: 'The illness debilitated him for months.', exampleVN: 'Bệnh tật khiến anh suy yếu nhiều tháng.' },
  { id: 'h110', word: 'denigrate', meaning: 'bôi nhọ', example: 'Do not denigrate your competitors.', exampleVN: 'Đừng bôi nhọ đối thủ cạnh tranh.' },
  { id: 'h111', word: 'derogatory', meaning: 'xúc phạm, miệt thị', example: 'Derogatory remarks about colleagues.', exampleVN: 'Những nhận xét xúc phạm đồng nghiệp.' },
  { id: 'h112', word: 'dichotomy', meaning: 'sự phân đôi', example: 'The dichotomy between theory and practice.', exampleVN: 'Sự phân đôi giữa lý thuyết và thực hành.' },
  { id: 'h113', word: 'dilatory', meaning: 'chậm chạp, trì hoãn', example: 'Dilatory tactics delayed the deal.', exampleVN: 'Chiến thuật trì hoãn làm chậm thỏa thuận.' },
  { id: 'h114', word: 'disparage', meaning: 'hạ thấp, chê bai', example: 'She disparaged his achievements.', exampleVN: 'Cô ấy hạ thấp thành tựu của anh.' },
  { id: 'h115', word: 'disseminate', meaning: 'phổ biến, lan truyền', example: 'Disseminate information to all staff.', exampleVN: 'Phổ biến thông tin cho tất cả nhân viên.' },
  { id: 'h116', word: 'efficacious', meaning: 'hiệu quả, hữu hiệu', example: 'An efficacious treatment for the disease.', exampleVN: 'Một phương pháp điều trị hiệu quả cho bệnh.' },
  { id: 'h117', word: 'emulate', meaning: 'noi gương, bắt chước', example: 'Young workers emulate successful leaders.', exampleVN: 'Nhân viên trẻ noi gương những lãnh đạo thành công.' },
  { id: 'h118', word: 'enervate', meaning: 'làm kiệt sức', example: 'The long meeting enervated everyone.', exampleVN: 'Cuộc họp dài làm kiệt sức mọi người.' },
  { id: 'h119', word: 'enigmatic', meaning: 'bí ẩn', example: 'An enigmatic smile.', exampleVN: 'Một nụ cười bí ẩn.' },
  { id: 'h120', word: 'ephemeral', meaning: 'phù du, ngắn ngủi', example: 'Fame can be ephemeral.', exampleVN: 'Danh vọng có thể phù du.' },
  { id: 'h121', word: 'equivocal', meaning: 'mập mờ, không rõ ràng', example: 'An equivocal answer.', exampleVN: 'Một câu trả lời mập mờ.' },
  { id: 'h122', word: 'eradicate', meaning: 'tiêu diệt, xóa bỏ', example: 'Eradicate poverty in the region.', exampleVN: 'Xóa bỏ nghèo đói trong khu vực.' },
  { id: 'h123', word: 'esoteric', meaning: 'bí truyền, khó hiểu', example: 'Esoteric terminology in the contract.', exampleVN: 'Thuật ngữ khó hiểu trong hợp đồng.' },
  { id: 'h124', word: 'exonerate', meaning: 'minh oan, giải tội', example: 'He was exonerated of all charges.', exampleVN: 'Anh ấy được minh oan mọi cáo buộc.' },
  { id: 'h125', word: 'expedite', meaning: 'đẩy nhanh, xúc tiến', example: 'Expedite the shipping process.', exampleVN: 'Đẩy nhanh quy trình vận chuyển.' },
  { id: 'h126', word: 'flagrant', meaning: 'trắng trợn', example: 'A flagrant violation of the rules.', exampleVN: 'Một sự vi phạm trắng trợn các quy tắc.' },
  { id: 'h127', word: 'frivolous', meaning: 'phù phiếm, không nghiêm túc', example: 'Frivolous spending on luxury items.', exampleVN: 'Chi tiêu phù phiếm cho hàng xa xỉ.' },
  { id: 'h128', word: 'futile', meaning: 'vô ích, vô vọng', example: 'All resistance proved futile.', exampleVN: 'Mọi sự kháng cự đều vô ích.' },
  { id: 'h129', word: 'galvanize', meaning: 'kích thích hành động', example: 'The speech galvanized the workers.', exampleVN: 'Bài phát biểu đã kích thích công nhân.' },
  { id: 'h130', word: 'heresy', meaning: 'tà thuyết, dị giáo', example: 'His ideas were considered heresy.', exampleVN: 'Ý tưởng của ông bị coi là tà thuyết.' },
  { id: 'h131', word: 'homogeneous', meaning: 'đồng nhất', example: 'A homogeneous team lacks diversity.', exampleVN: 'Một đội đồng nhất thiếu đa dạng.' },
  { id: 'h132', word: 'ignominious', meaning: 'nhục nhã', example: 'An ignominious defeat.', exampleVN: 'Một thất bại nhục nhã.' },
  { id: 'h133', word: 'imminent', meaning: 'sắp xảy ra', example: 'An imminent deadline.', exampleVN: 'Một hạn chót sắp đến.' },
  { id: 'h134', word: 'impervious', meaning: 'không bị ảnh hưởng', example: 'He seemed impervious to criticism.', exampleVN: 'Anh ấy dường như không bị ảnh hưởng bởi chỉ trích.' },
  { id: 'h135', word: 'inadvertent', meaning: 'vô ý, không chủ đích', example: 'An inadvertent error in the report.', exampleVN: 'Một lỗi vô ý trong báo cáo.' },
  { id: 'h136', word: 'incisive', meaning: 'sắc bén', example: 'An incisive analysis of the market.', exampleVN: 'Một phân tích sắc bén về thị trường.' },
  { id: 'h137', word: 'incontrovertible', meaning: 'không thể bác bỏ', example: 'Incontrovertible evidence of fraud.', exampleVN: 'Bằng chứng không thể bác bỏ về gian lận.' },
  { id: 'h138', word: 'indigent', meaning: 'nghèo khó', example: 'Support for indigent families.', exampleVN: 'Hỗ trợ cho các gia đình nghèo khó.' },
  { id: 'h139', word: 'insidious', meaning: 'nham hiểm, ngấm ngầm', example: 'The insidious effects of pollution.', exampleVN: 'Tác hại ngấm ngầm của ô nhiễm.' },
  { id: 'h140', word: 'intransigent', meaning: 'không khoan nhượng', example: 'An intransigent negotiating position.', exampleVN: 'Một lập trường đàm phán không khoan nhượng.' },
  { id: 'h141', word: 'irrevocable', meaning: 'không thể thu hồi', example: 'An irrevocable decision.', exampleVN: 'Một quyết định không thể thu hồi.' },
  { id: 'h142', word: 'juxtaposition', meaning: 'sự đặt cạnh nhau', example: 'The juxtaposition of old and new.', exampleVN: 'Sự đặt cạnh nhau giữa cũ và mới.' },
  { id: 'h143', word: 'lament', meaning: 'than thở, tiếc nuối', example: 'He lamented the loss of his job.', exampleVN: 'Anh ấy tiếc nuối về việc mất việc.' },
  { id: 'h144', word: 'largesse', meaning: 'sự hào phóng', example: 'Corporate largesse to charities.', exampleVN: 'Sự hào phóng của doanh nghiệp cho từ thiện.' },
  { id: 'h145', word: 'lethargy', meaning: 'sự uể oải', example: 'Economic lethargy slowed growth.', exampleVN: 'Sự trì trệ kinh tế làm chậm tăng trưởng.' },
  { id: 'h146', word: 'magnate', meaning: 'đại gia, trùm', example: 'A real estate magnate.', exampleVN: 'Một đại gia bất động sản.' },
  { id: 'h147', word: 'malicious', meaning: 'ác ý', example: 'Malicious gossip in the workplace.', exampleVN: 'Tin đồn ác ý ở nơi làm việc.' },
  { id: 'h148', word: 'misconstrue', meaning: 'hiểu sai', example: 'His words were misconstrued.', exampleVN: 'Lời anh bị hiểu sai.' },
  { id: 'h149', word: 'misnomer', meaning: 'tên gọi sai', example: 'Calling it simple is a misnomer.', exampleVN: 'Gọi nó đơn giản là sai.' },
  { id: 'h150', word: 'nonchalant', meaning: 'thờ ơ, lãnh đạm', example: 'He was nonchalant about the results.', exampleVN: 'Anh ấy thờ ơ với kết quả.' },
  { id: 'h151', word: 'obfuscate', meaning: 'làm mù mờ', example: 'Do not obfuscate the facts.', exampleVN: 'Đừng làm mờ sự thật.' },
  { id: 'h152', word: 'obsolete', meaning: 'lỗi thời', example: 'The technology became obsolete.', exampleVN: 'Công nghệ trở nên lỗi thời.' },
  { id: 'h153', word: 'onerous', meaning: 'nặng nề', example: 'Onerous regulations on small businesses.', exampleVN: 'Các quy định nặng nề cho doanh nghiệp nhỏ.' },
  { id: 'h154', word: 'ostentatious', meaning: 'phô trương', example: 'An ostentatious display of wealth.', exampleVN: 'Sự phô trương tài sản.' },
  { id: 'h155', word: 'panacea', meaning: 'thần dược, giải pháp vạn năng', example: 'Technology is not a panacea.', exampleVN: 'Công nghệ không phải giải pháp vạn năng.' },
  { id: 'h156', word: 'paradox', meaning: 'nghịch lý', example: 'The paradox of progress.', exampleVN: 'Nghịch lý của sự tiến bộ.' },
  { id: 'h157', word: 'paucity', meaning: 'sự thiếu thốn', example: 'A paucity of skilled workers.', exampleVN: 'Sự thiếu hụt công nhân lành nghề.' },
  { id: 'h158', word: 'pecuniary', meaning: 'thuộc về tiền bạc', example: 'Pecuniary benefits of the merger.', exampleVN: 'Lợi ích tài chính của việc sáp nhập.' },
  { id: 'h159', word: 'penchant', meaning: 'sở thích đặc biệt', example: 'A penchant for expensive cars.', exampleVN: 'Sở thích đặc biệt với xe sang.' },
  { id: 'h160', word: 'perfunctory', meaning: 'qua loa, chiếu lệ', example: 'A perfunctory review of the document.', exampleVN: 'Một đánh giá qua loa tài liệu.' },
  { id: 'h161', word: 'perpetuate', meaning: 'duy trì mãi', example: 'Perpetuate old traditions.', exampleVN: 'Duy trì những truyền thống cũ.' },
  { id: 'h162', word: 'pertinent', meaning: 'thích hợp, có liên quan', example: 'Pertinent information for the case.', exampleVN: 'Thông tin liên quan đến vụ việc.' },
  { id: 'h163', word: 'plausible', meaning: 'hợp lý, có vẻ đúng', example: 'A plausible explanation.', exampleVN: 'Một lời giải thích hợp lý.' },
  { id: 'h164', word: 'precarious', meaning: 'bấp bênh, nguy hiểm', example: 'A precarious financial situation.', exampleVN: 'Một tình hình tài chính bấp bênh.' },
  { id: 'h165', word: 'precedent', meaning: 'tiền lệ', example: 'Set a precedent for future cases.', exampleVN: 'Tạo tiền lệ cho các vụ việc tương lai.' },
  { id: 'h166', word: 'preemptive', meaning: 'mang tính phủ đầu', example: 'A preemptive strategy.', exampleVN: 'Một chiến lược phủ đầu.' },
  { id: 'h167', word: 'prolific', meaning: 'sung mãn, đa sản', example: 'A prolific writer.', exampleVN: 'Một nhà văn đa sản.' },
  { id: 'h168', word: 'propensity', meaning: 'khuynh hướng', example: 'A propensity for taking risks.', exampleVN: 'Khuynh hướng chấp nhận rủi ro.' },
  { id: 'h169', word: 'proponent', meaning: 'người ủng hộ', example: 'A proponent of free trade.', exampleVN: 'Một người ủng hộ thương mại tự do.' },
  { id: 'h170', word: 'prudent', meaning: 'thận trọng, khôn ngoan', example: 'A prudent investment strategy.', exampleVN: 'Một chiến lược đầu tư thận trọng.' },
  { id: 'h171', word: 'quagmire', meaning: 'bãi lầy, tình thế khó khăn', example: 'The project became a quagmire.', exampleVN: 'Dự án trở thành vũng lầy.' },
  { id: 'h172', word: 'rampant', meaning: 'tràn lan', example: 'Rampant inflation hurt the economy.', exampleVN: 'Lạm phát tràn lan gây tổn hại kinh tế.' },
  { id: 'h173', word: 'ratify', meaning: 'phê chuẩn', example: 'The board ratified the agreement.', exampleVN: 'Hội đồng đã phê chuẩn thỏa thuận.' },
  { id: 'h174', word: 'rebuke', meaning: 'khiển trách', example: 'The manager rebuked him sharply.', exampleVN: 'Quản lý đã khiển trách anh ta gay gắt.' },
  { id: 'h175', word: 'reclusive', meaning: 'ẩn dật', example: 'A reclusive billionaire.', exampleVN: 'Một tỷ phú ẩn dật.' },
  { id: 'h176', word: 'remuneration', meaning: 'thù lao', example: 'Adequate remuneration for the work.', exampleVN: 'Thù lao xứng đáng cho công việc.' },
  { id: 'h177', word: 'repercussion', meaning: 'hậu quả', example: 'The decision had serious repercussions.', exampleVN: 'Quyết định có hậu quả nghiêm trọng.' },
  { id: 'h178', word: 'repudiate', meaning: 'bác bỏ, từ chối', example: 'Repudiate the allegations.', exampleVN: 'Bác bỏ các cáo buộc.' },
  { id: 'h179', word: 'rescind', meaning: 'hủy bỏ (luật/quyết định)', example: 'The policy was rescinded.', exampleVN: 'Chính sách đã bị hủy bỏ.' },
  { id: 'h180', word: 'reticent', meaning: 'kín đáo, ít nói', example: 'He was reticent about the deal.', exampleVN: 'Anh ấy kín đáo về thỏa thuận.' },
  { id: 'h181', word: 'revoke', meaning: 'thu hồi, hủy bỏ', example: 'Revoke the license.', exampleVN: 'Thu hồi giấy phép.' },
  { id: 'h182', word: 'rigorous', meaning: 'nghiêm ngặt', example: 'Rigorous quality control.', exampleVN: 'Kiểm soát chất lượng nghiêm ngặt.' },
  { id: 'h183', word: 'robust', meaning: 'mạnh mẽ, vững chắc', example: 'A robust economy.', exampleVN: 'Một nền kinh tế mạnh mẽ.' },
  { id: 'h184', word: 'rudimentary', meaning: 'sơ khai, cơ bản', example: 'Rudimentary knowledge of accounting.', exampleVN: 'Kiến thức sơ khai về kế toán.' },
  { id: 'h185', word: 'sanguine', meaning: 'lạc quan', example: 'Sanguine about the future.', exampleVN: 'Lạc quan về tương lai.' },
  { id: 'h186', word: 'scrupulous', meaning: 'tỉ mỉ, cẩn thận', example: 'Scrupulous attention to detail.', exampleVN: 'Chú ý tỉ mỉ đến từng chi tiết.' },
  { id: 'h187', word: 'sporadic', meaning: 'rải rác, lẻ tẻ', example: 'Sporadic protests across the city.', exampleVN: 'Các cuộc biểu tình lẻ tẻ khắp thành phố.' },
  { id: 'h188', word: 'stringent', meaning: 'nghiêm ngặt', example: 'Stringent safety regulations.', exampleVN: 'Các quy định an toàn nghiêm ngặt.' },
  { id: 'h189', word: 'subjugate', meaning: 'chinh phục, khuất phục', example: 'Subjugate a rival company.', exampleVN: 'Khuất phục một công ty đối thủ.' },
  { id: 'h190', word: 'substantiate', meaning: 'chứng minh, xác minh', example: 'Substantiate your claims with data.', exampleVN: 'Chứng minh tuyên bố bằng dữ liệu.' },
  { id: 'h191', word: 'succinct', meaning: 'ngắn gọn, súc tích', example: 'A succinct summary of the report.', exampleVN: 'Một bản tóm tắt ngắn gọn báo cáo.' },
  { id: 'h192', word: 'supplant', meaning: 'thay thế, chiếm chỗ', example: 'New technology will supplant old methods.', exampleVN: 'Công nghệ mới sẽ thay thế phương pháp cũ.' },
  { id: 'h193', word: 'surreptitious', meaning: 'lén lút', example: 'A surreptitious glance at the clock.', exampleVN: 'Một cái liếc lén lút vào đồng hồ.' },
  { id: 'h194', word: 'tantamount', meaning: 'tương đương', example: 'This is tantamount to fraud.', exampleVN: 'Điều này tương đương gian lận.' },
  { id: 'h195', word: 'transient', meaning: 'tạm thời, thoáng qua', example: 'A transient economic boom.', exampleVN: 'Một đợt bùng nổ kinh tế tạm thời.' },
  { id: 'h196', word: 'truncate', meaning: 'cắt ngắn', example: 'Truncate the report to 5 pages.', exampleVN: 'Cắt ngắn báo cáo còn 5 trang.' },
  { id: 'h197', word: 'turmoil', meaning: 'sự hỗn loạn', example: 'Political turmoil in the region.', exampleVN: 'Hỗn loạn chính trị trong khu vực.' },
  { id: 'h198', word: 'ubiquity', meaning: 'sự phổ biến khắp nơi', example: 'The ubiquity of smartphones.', exampleVN: 'Sự phổ biến khắp nơi của điện thoại thông minh.' },
  { id: 'h199', word: 'undermine', meaning: 'phá hoại ngầm', example: 'Undermine the authority of the manager.', exampleVN: 'Phá hoại ngầm quyền lực của quản lý.' },
  { id: 'h200', word: 'unscrupulous', meaning: 'vô đạo đức', example: 'Unscrupulous business practices.', exampleVN: 'Các hoạt động kinh doanh vô đạo đức.' },
];
