import { Word } from './types';

export const chunkInter3: Word[] = [
  { id: 'i201', word: 'enhance', meaning: 'nâng cao', example: 'We need to enhance our security system.', exampleVN: 'Chúng ta cần nâng cao hệ thống an ninh.' },
  { id: 'i202', word: 'enroll', meaning: 'đăng ký học', example: 'You can enroll in the course online.', exampleVN: 'Bạn có thể đăng ký khóa học trực tuyến.' },
  { id: 'i203', word: 'ensure', meaning: 'đảm bảo', example: 'Please ensure all doors are locked.', exampleVN: 'Vui lòng đảm bảo tất cả các cửa đã được khóa.' },
  { id: 'i204', word: 'enterprise', meaning: 'doanh nghiệp, sự nghiệp', example: 'It was a risky enterprise.', exampleVN: 'Đó là một sự nghiệp đầy rủi ro.' },
  { id: 'i205', word: 'enthusiastic', meaning: 'nhiệt tình', example: 'She is very enthusiastic about the project.', exampleVN: 'Cô ấy rất nhiệt tình với dự án.' },
  { id: 'i206', word: 'entitle', meaning: 'cho quyền', example: 'This ticket entitles you to a free meal.', exampleVN: 'Tấm vé này cho phép bạn được một bữa ăn miễn phí.' },
  { id: 'i207', word: 'entrepreneur', meaning: 'doanh nhân', example: 'A successful entrepreneur takes risks.', exampleVN: 'Một doanh nhân thành công biết chấp nhận rủi ro.' },
  { id: 'i208', word: 'envelope', meaning: 'phong bì', example: 'Put the letter in the envelope.', exampleVN: 'Bỏ bức thư vào phong bì.' },
  { id: 'i209', word: 'environment', meaning: 'môi trường', example: 'Protecting the environment is important.', exampleVN: 'Bảo vệ môi trường là quan trọng.' },
  { id: 'i210', word: 'equivalent', meaning: 'tương đương', example: 'The salary is equivalent to $2000.', exampleVN: 'Mức lương tương đương với 2000 đô la.' },
  { id: 'i211', word: 'establish', meaning: 'thiết lập, thành lập', example: 'The company was established in 1990.', exampleVN: 'Công ty được thành lập vào năm 1990.' },
  { id: 'i212', word: 'estate', meaning: 'bất động sản, tài sản', example: 'He owns a large real estate company.', exampleVN: 'Anh ấy sở hữu một công ty bất động sản lớn.' },
  { id: 'i213', word: 'estimate', meaning: 'ước tính', example: 'Can you give me a rough estimate?', exampleVN: 'Bạn có thể cho tôi một ước tính sơ bộ không?' },
  { id: 'i214', word: 'ethics', meaning: 'đạo đức', example: 'Business ethics are essential.', exampleVN: 'Đạo đức kinh doanh là điều thiết yếu.' },
  { id: 'i215', word: 'evaluate', meaning: 'đánh giá', example: 'The teachers evaluate the students.', exampleVN: 'Các giáo viên đánh giá học sinh.' },
  { id: 'i216', word: 'evident', meaning: 'hiển nhiên, rõ ràng', example: 'It was evident that she was lying.', exampleVN: 'Rõ ràng là cô ấy đang nói dối.' },
  { id: 'i217', word: 'exaggerate', meaning: 'phóng đại', example: 'Don\'t exaggerate the problem.', exampleVN: 'Đừng phóng đại vấn đề.' },
  { id: 'i218', word: 'exceed', meaning: 'vượt quá', example: 'The costs exceeded the budget.', exampleVN: 'Chi phí đã vượt quá ngân sách.' },
  { id: 'i219', word: 'exception', meaning: 'ngoại lệ', example: 'There are no exceptions to this rule.', exampleVN: 'Không có ngoại lệ cho quy tắc này.' },
  { id: 'i220', word: 'exchange', meaning: 'trao đổi', example: 'Let\'s exchange phone numbers.', exampleVN: 'Hãy trao đổi số điện thoại.' },
  { id: 'i221', word: 'exclude', meaning: 'loại trừ', example: 'The price excludes shipping costs.', exampleVN: 'Giá này không bao gồm chi phí vận chuyển.' },
  { id: 'i222', word: 'exclusive', meaning: 'độc quyền, riêng biệt', example: 'An exclusive interview with the star.', exampleVN: 'Một cuộc phỏng vấn độc quyền với ngôi sao.' },
  { id: 'i223', word: 'excursion', meaning: 'chuyến tham quan, dã ngoại', example: 'We went on a weekend excursion.', exampleVN: 'Chúng tôi đã đi dã ngoại vào cuối tuần.' },
  { id: 'i224', word: 'execute', meaning: 'thi hành, thực hiện', example: 'They executed the plan perfectly.', exampleVN: 'Họ đã thực hiện kế hoạch một cách hoàn hảo.' },
  { id: 'i225', word: 'executive', meaning: 'người điều hành', example: 'He is a senior executive at the firm.', exampleVN: 'Ông ấy là một nhà điều hành cấp cao tại công ty.' },
  { id: 'i226', word: 'exempt', meaning: 'được miễn', example: 'Small businesses are exempt from this tax.', exampleVN: 'Các doanh nghiệp nhỏ được miễn loại thuế này.' },
  { id: 'i227', word: 'exhibit', meaning: 'triển lãm', example: 'The museum has a new exhibit.', exampleVN: 'Bảo tàng có một cuộc triển lãm mới.' },
  { id: 'i228', word: 'expand', meaning: 'mở rộng', example: 'The business is expanding globally.', exampleVN: 'Doanh nghiệp đang mở rộng ra toàn cầu.' },
  { id: 'i229', word: 'expenditure', meaning: 'chi phí, sự tiêu dùng', example: 'Government expenditure on health.', exampleVN: 'Chi tiêu của chính phủ cho y tế.' },
  { id: 'i230', word: 'expertise', meaning: 'chuyên môn', example: 'We need someone with technical expertise.', exampleVN: 'Chúng ta cần một người có chuyên môn kỹ thuật.' },
  { id: 'i231', word: 'expire', meaning: 'hết hạn', example: 'My passport expires next month.', exampleVN: 'Hộ chiếu của tôi hết hạn vào tháng tới.' },
  { id: 'i232', word: 'explicit', meaning: 'rõ ràng, dứt khoát', example: 'She gave me explicit instructions.', exampleVN: 'Cô ấy đã cho tôi những hướng dẫn rõ ràng.' },
  { id: 'i233', word: 'exploit', meaning: 'khai thác, bóc lột', example: 'We should exploit new markets.', exampleVN: 'Chúng ta nên khai thác các thị trường mới.' },
  { id: 'i234', word: 'export', meaning: 'xuất khẩu', example: 'The country exports rice.', exampleVN: 'Đất nước này xuất khẩu gạo.' },
  { id: 'i235', word: 'expose', meaning: 'phơi bày, tiếp xúc', example: 'Don\'t expose the film to light.', exampleVN: 'Đừng để phim tiếp xúc với ánh sáng.' },
  { id: 'i236', word: 'express', meaning: 'bày tỏ, nhanh', example: 'Express your feelings openly.', exampleVN: 'Hãy bày tỏ cảm xúc của bạn một cách cởi mở.' },
  { id: 'i237', word: 'extend', meaning: 'kéo dài, mở rộng', example: 'Can we extend the deadline?', exampleVN: 'Chúng ta có thể kéo dài hạn chót không?' },
  { id: 'i238', word: 'extensive', meaning: 'rộng rãi, bao quát', example: 'The house has extensive gardens.', exampleVN: 'Ngôi nhà có những khu vườn rộng rãi.' },
  { id: 'i239', word: 'exterior', meaning: 'bên ngoài', example: 'The exterior of the building is white.', exampleVN: 'Bên ngoài của tòa nhà màu trắng.' },
  { id: 'i240', word: 'extinguish', meaning: 'dập tắt', example: 'Firefighters extinguished the fire.', exampleVN: 'Lính cứu hỏa đã dập tắt đám cháy.' },
  { id: 'i241', word: 'extraordinary', meaning: 'phi thường', example: 'An extraordinary achievement.', exampleVN: 'Một thành tựu phi thường.' },
  { id: 'i242', word: 'facilitate', meaning: 'tạo điều kiện thuận lợi', example: 'New technology facilitates communication.', exampleVN: 'Công nghệ mới tạo điều kiện thuận lợi cho việc giao tiếp.' },
  { id: 'i243', word: 'factor', meaning: 'nhân tố', example: 'Cost is a major factor.', exampleVN: 'Chi phí là một nhân tố chính.' },
  { id: 'i244', word: 'faculty', meaning: 'khoa, giảng viên', example: 'She joined the law faculty.', exampleVN: 'Cô ấy đã tham gia khoa luật.' },
  { id: 'i245', word: 'failure', meaning: 'sự thất bại', example: 'Don\'t be afraid of failure.', exampleVN: 'Đừng sợ thất bại.' },
  { id: 'i246', word: 'fair', meaning: 'công bằng, hội chợ', example: 'Life isn\'t always fair.', exampleVN: 'Cuộc sống không phải lúc nào cũng công bằng.' },
  { id: 'i247', word: 'familiar', meaning: 'quen thuộc', example: 'Are you familiar with this software?', exampleVN: 'Bạn có quen thuộc với phần mềm này không?' },
  { id: 'i248', word: 'fatal', meaning: 'chết người, định mệnh', example: 'A fatal car accident.', exampleVN: 'Một vụ tai nạn xe hơi chết người.' },
  { id: 'i249', word: 'feasible', meaning: 'khả thi', example: 'The project is economically feasible.', exampleVN: 'Dự án này khả thi về mặt kinh tế.' },
  { id: 'i250', word: 'feature', meaning: 'đặc điểm, tính năng', example: 'This phone has many new features.', exampleVN: 'Chiếc điện thoại này có nhiều tính năng mới.' },
  { id: 'i251', word: 'federal', meaning: 'thuộc liên bang', example: 'A federal agency.', exampleVN: 'Một cơ quan liên bang.' },
  { id: 'i252', word: 'fee', meaning: 'phí', example: 'The registration fee is $50.', exampleVN: 'Phí đăng ký là 50 đô la.' },
  { id: 'i253', word: 'feedback', meaning: 'phản hồi', example: 'We value your feedback.', exampleVN: 'Chúng tôi trân trọng phản hồi của bạn.' },
  { id: 'i254', word: 'fertile', meaning: 'phì nhiêu', example: 'The land is very fertile.', exampleVN: 'Đất đai rất phì nhiêu.' },
  { id: 'i255', word: 'frequent', meaning: 'thường xuyên', example: 'He is a frequent traveler.', exampleVN: 'Anh ấy là một người hay đi du lịch.' },
  { id: 'i256', word: 'fulfill', meaning: 'hoàn thành, đáp ứng', example: 'We must fulfill our promises.', exampleVN: 'Chúng ta phải thực hiện lời hứa của mình.' },
  { id: 'i257', word: 'function', meaning: 'chức năng', example: 'What is the function of this button?', exampleVN: 'Chức năng của nút này là gì?' },
  { id: 'i258', word: 'fund', meaning: 'quỹ, tài trợ', example: 'The project is funded by the government.', exampleVN: 'Dự án được tài trợ bởi chính phủ.' },
  { id: 'i259', word: 'fundamental', meaning: 'cơ bản, chủ yếu', example: 'A fundamental change in policy.', exampleVN: 'Một sự thay đổi cơ bản trong chính sách.' },
  { id: 'i260', word: 'gain', meaning: 'đạt được, tăng', example: 'He gained a lot of experience.', exampleVN: 'Anh ấy đã đạt được nhiều kinh nghiệm.' },
  { id: 'i261', word: 'gather', meaning: 'tập hợp, thu thập', example: 'Gather all the documents.', exampleVN: 'Thu thập tất cả các tài liệu.' },
  { id: 'i262', word: 'general', meaning: 'chung, tổng quát', example: 'In general, people like the idea.', exampleVN: 'Nói chung, mọi người thích ý tưởng này.' },
  { id: 'i263', word: 'generate', meaning: 'tạo ra', example: 'The wind farm generates electricity.', exampleVN: 'Trang trại gió tạo ra điện.' },
  { id: 'i264', word: 'generous', meaning: 'hào phóng', example: 'He is very generous with his money.', exampleVN: 'Anh ấy rất hào phóng với tiền bạc của mình.' },
  { id: 'i265', word: 'genuine', meaning: 'thật, chính hãng', example: 'Is this genuine leather?', exampleVN: 'Đây có phải là da thật không?' },
  { id: 'i266', word: 'gesture', meaning: 'cử chỉ', example: 'A friendly gesture.', exampleVN: 'Một cử chỉ thân thiện.' },
  { id: 'i267', word: 'global', meaning: 'toàn cầu', example: 'Global warming is a serious issue.', exampleVN: 'Nóng lên toàn cầu là một vấn đề nghiêm trọng.' },
  { id: 'i268', word: 'governance', meaning: 'quản trị', example: 'Good corporate governance.', exampleVN: 'Quản trị doanh nghiệp tốt.' },
  { id: 'i269', word: 'gradual', meaning: 'dần dần', example: 'A gradual improvement in health.', exampleVN: 'Sự cải thiện sức khỏe dần dần.' },
  { id: 'i270', word: 'grant', meaning: 'trợ cấp, ban cho', example: 'The government gave them a grant.', exampleVN: 'Chính phủ đã cấp cho họ một khoản trợ cấp.' },
  { id: 'i271', word: 'grateful', meaning: 'biết ơn', example: 'I am grateful for your help.', exampleVN: 'Tôi biết ơn sự giúp đỡ của bạn.' },
  { id: 'i272', word: 'gross', meaning: 'tổng, gớm ghiếc', example: 'Gross national product.', exampleVN: 'Tổng sản phẩm quốc nội.' },
  { id: 'i273', word: 'guarantee', meaning: 'bảo hành, đảm bảo', example: 'The car comes with a one-year guarantee.', exampleVN: 'Xe hơi đi kèm với bảo hành một năm.' },
  { id: 'i274', word: 'guideline', meaning: 'hướng dẫn', example: 'Follow the guidelines carefully.', exampleVN: 'Tuân thủ các hướng dẫn một cách cẩn thận.' },
  { id: 'i275', word: 'guilty', meaning: 'có tội', example: 'He felt guilty about lying.', exampleVN: 'Anh ấy cảm thấy tội lỗi vì đã nói dối.' },
  { id: 'i276', word: 'handle', meaning: 'xử lý, tay cầm', example: 'Can you handle this situation?', exampleVN: 'Bạn có thể xử lý tình huống này không?' },
  { id: 'i277', word: 'harbor', meaning: 'cảng, nuôi dưỡng', example: 'The ship is in the harbor.', exampleVN: 'Con tàu đang ở trong cảng.' },
  { id: 'i278', word: 'hardship', meaning: 'khó khăn, gian khổ', example: 'They faced many hardships.', exampleVN: 'Họ đã đối mặt với nhiều gian khổ.' },
  { id: 'i279', word: 'hazard', meaning: 'mối nguy hiểm', example: 'Smoking is a health hazard.', exampleVN: 'Hút thuốc là một mối nguy hại cho sức khỏe.' },
  { id: 'i280', word: 'headquarters', meaning: 'trụ sở chính', example: 'The company\'s headquarters is in London.', exampleVN: 'Trụ sở chính của công ty ở Luân Đôn.' },
  { id: 'i281', word: 'hesitate', meaning: 'do dự', example: 'Don\'t hesitate to ask questions.', exampleVN: 'Đừng ngần ngại đặt câu hỏi.' },
  { id: 'i282', word: 'highlight', meaning: 'làm nổi bật, điểm nhấn', example: 'The report highlights the main issues.', exampleVN: 'Báo cáo làm nổi bật các vấn đề chính.' },
  { id: 'i283', word: 'highly', meaning: 'rất, cao', example: 'He is a highly skilled worker.', exampleVN: 'Anh ấy là một nhân viên tay nghề rất cao.' },
  { id: 'i284', word: 'hinder', meaning: 'cản trở', example: 'Bad weather hindered the progress.', exampleVN: 'Thời tiết xấu đã cản trở tiến độ.' },
  { id: 'i285', word: 'hire', meaning: 'thuê', example: 'We need to hire more staff.', exampleVN: 'Chúng ta cần thuê thêm nhân viên.' },
  { id: 'i286', word: 'holiday', meaning: 'ngày lễ, kỳ nghỉ', example: 'Where are you going for your holiday?', exampleVN: 'Bạn sẽ đi đâu vào kỳ nghỉ của mình?' },
  { id: 'i287', word: 'horizontal', meaning: 'nằm ngang', example: 'A horizontal line.', exampleVN: 'Một đường nằm ngang.' },
  { id: 'i288', word: 'hospitality', meaning: 'sự hiếu khách', example: 'Thank you for your hospitality.', exampleVN: 'Cảm ơn sự hiếu khách của bạn.' },
  { id: 'i289', word: 'hostile', meaning: 'thù địch', example: 'A hostile environment.', exampleVN: 'Một môi trường thù địch.' },
  { id: 'i290', word: 'household', meaning: 'hộ gia đình', example: 'Household chores.', exampleVN: 'Công việc nhà.' },
  { id: 'i291', word: 'housing', meaning: 'nhà ở', example: 'Low-cost housing.', exampleVN: 'Nhà ở giá rẻ.' },
  { id: 'i292', word: 'huge', meaning: 'khổng lồ', example: 'A huge amount of money.', exampleVN: 'Một số tiền khổng lồ.' },
  { id: 'i293', word: 'humanity', meaning: 'nhân loại', example: 'Crimes against humanity.', exampleVN: 'Tội ác chống lại nhân loại.' },
  { id: 'i294', word: 'humble', meaning: 'khiêm tốn', example: 'He is a very humble man.', exampleVN: 'Ông ấy là một người rất khiêm tốn.' },
  { id: 'i295', word: 'humor', meaning: 'hài hước', example: 'He has a good sense of humor.', exampleVN: 'Anh ấy có khiếu hài hước.' },
  { id: 'i296', word: 'hunger', meaning: 'sự đói khát', example: 'The world is fighting hunger.', exampleVN: 'Thế giới đang chống lại nạn đói.' },
  { id: 'i297', word: 'hypothesis', meaning: 'giả thuyết', example: 'A scientific hypothesis.', exampleVN: 'Một giả thuyết khoa học.' },
  { id: 'i298', word: 'ideal', meaning: 'lý tưởng', example: 'The weather is ideal for a picnic.', exampleVN: 'Thời tiết thật lý tưởng cho một buổi dã ngoại.' },
  { id: 'i299', word: 'identify', meaning: 'xác định, nhận dạng', example: 'Can you identify this person?', exampleVN: 'Bạn có thể nhận dạng người này không?' },
  { id: 'i300', word: 'ignore', meaning: 'lờ đi', example: 'Don\'t ignore the warning signs.', exampleVN: 'Đừng lờ đi những dấu hiệu cảnh báo.' },
];

export const processChunkInter3 = () => {
  return chunkInter3.map(w => ({ ...w, pos: '(n)' as string }));
};
