import { Word } from './types';

export const chunk6: Word[] = [
  { id: '701', word: 'amazing', meaning: 'tuyệt vời', example: 'An amazing experience.', exampleVN: 'Họ thảo luận về một trải nghiệm tuyệt vời.' },
  { id: '702', word: 'ambition', meaning: 'tham vọng', example: 'Career ambition.', exampleVN: 'Tham vọng nghề nghiệp.' },
  { id: '703', word: 'amend', meaning: 'sửa đổi', example: 'Amend the document.', exampleVN: 'Sửa đổi tài liệu.' },
  { id: '704', word: 'amount', meaning: 'số lượng', example: 'A large amount.', exampleVN: 'Họ đã thảo luận rất nhiều.' },
  { id: '705', word: 'ample', meaning: 'rộng rãi, phong phú', example: 'Ample time.', exampleVN: 'Có nhiều thời gian.' },
  { id: '706', word: 'analysis', meaning: 'sự phân tích', example: 'Data analysis.', exampleVN: 'Phân tích dữ liệu.' },
  { id: '707', word: 'analyze', meaning: 'phân tích', example: 'Analyze the data.', exampleVN: 'Phân tích dữ liệu.' },
  { id: '708', word: 'anchor', meaning: 'mỏ neo, người dẫn', example: 'News anchor.', exampleVN: 'Người đưa tin.' },
  { id: '709', word: 'ancient', meaning: 'cổ đại', example: 'Ancient history.', exampleVN: 'Lịch sử cổ xưa.' },
  { id: '710', word: 'anger', meaning: 'sự tức giận', example: 'Control your anger.', exampleVN: 'Kiểm soát cơn giận của bạn.' },
  { id: '711', word: 'angle', meaning: 'góc độ', example: 'A different angle.', exampleVN: 'Họ đã thảo luận ở một góc độ khác.' },
  { id: '712', word: 'angry', meaning: 'tức giận', example: 'He is angry.', exampleVN: 'Anh ấy đang tức giận.' },
  { id: '713', word: 'animal', meaning: 'động vật', example: 'Animal shelter.', exampleVN: 'Nơi trú ẩn động vật.' },
  { id: '714', word: 'announce', meaning: 'thông báo', example: 'Announce the news.', exampleVN: 'Thông báo tin này.' },
  { id: '715', word: 'annoy', meaning: 'làm phiền', example: 'Do not annoy him.', exampleVN: 'Không làm phiền anh ấy.' },
  { id: '716', word: 'annual', meaning: 'hàng năm', example: 'Annual report.', exampleVN: 'Báo cáo hàng năm.' },
  { id: '717', word: 'anticipate', meaning: 'dự đoán', example: 'Anticipate problems.', exampleVN: 'Lường trước các vấn đề.' },
  { id: '718', word: 'anxiety', meaning: 'sự lo lắng', example: 'Reduce anxiety.', exampleVN: 'Giảm bớt lo lắng.' },
  { id: '719', word: 'anxious', meaning: 'lo lắng', example: 'Anxious waiting.', exampleVN: 'Hồi hộp chờ đợi.' },
  { id: '720', word: 'apart', meaning: 'tách rời', example: 'Fall apart.', exampleVN: 'Sự sụp đổ.' },
  { id: '721', word: 'apartment', meaning: 'căn hộ', example: 'Rent an apartment.', exampleVN: 'Thuê một căn hộ.' },
  { id: '722', word: 'apologize', meaning: 'xin lỗi', example: 'Apologize for the delay.', exampleVN: 'xin lỗi vì sự chậm trễ.' },
  { id: '723', word: 'apology', meaning: 'lời xin lỗi', example: 'Sincere apology.', exampleVN: 'Lời xin lỗi chân thành.' },
  { id: '724', word: 'apparel', meaning: 'trang phục', example: 'Men apparel.', exampleVN: 'Trang phục nam giới.' },
  { id: '725', word: 'apparent', meaning: 'rõ ràng', example: 'It is apparent.', exampleVN: 'Nó là điều hiển nhiên.' },
  { id: '726', word: 'appeal', meaning: 'kêu gọi, hấp dẫn', example: 'Appeal to customers.', exampleVN: 'Thu hút khách hàng.' },
  { id: '727', word: 'appear', meaning: 'xuất hiện', example: 'Appear on screen.', exampleVN: 'Xuất hiện trên màn hình.' },
  { id: '728', word: 'appearance', meaning: 'ngoại hình', example: 'Neat appearance.', exampleVN: 'Vẻ ngoài gọn gàng.' },
  { id: '729', word: 'appetite', meaning: 'sự thèm ăn', example: 'Good appetite.', exampleVN: 'Sự thèm ăn tốt.' },
  { id: '730', word: 'applaud', meaning: 'vỗ tay', example: 'Applaud the speaker.', exampleVN: 'Hoan nghênh diễn giả.' },
  { id: '731', word: 'appliance', meaning: 'thiết bị gia dụng', example: 'Home appliance.', exampleVN: 'Thiết bị gia dụng.' },
  { id: '732', word: 'applicant', meaning: 'người nộp đơn', example: 'Job applicant.', exampleVN: 'Người xin việc.' },
  { id: '733', word: 'application', meaning: 'đơn xin, ứng dụng', example: 'Software application.', exampleVN: 'Ứng dụng phần mềm.' },
  { id: '734', word: 'apply', meaning: 'áp dụng, nộp đơn', example: 'Apply for a job.', exampleVN: 'nộp đơn xin việc.' },
  { id: '735', word: 'appoint', meaning: 'bổ nhiệm', example: 'Appoint a manager.', exampleVN: 'Bổ nhiệm một người quản lý.' },
  { id: '736', word: 'appointment', meaning: 'cuộc hẹn', example: 'Doctor appointment.', exampleVN: 'Hẹn gặp bác sĩ.' },
  { id: '737', word: 'appraisal', meaning: 'sự đánh giá', example: 'Performance appraisal.', exampleVN: 'Đánh giá hiệu suất.' },
  { id: '738', word: 'appreciate', meaning: 'đánh giá cao', example: 'Appreciate your effort.', exampleVN: 'Đánh giá cao nỗ lực của bạn.' },
  { id: '739', word: 'approach', meaning: 'phương pháp, tiếp cận', example: 'A new approach.', exampleVN: 'Một cách tiếp cận mới.' },
  { id: '740', word: 'appropriate', meaning: 'thích hợp', example: 'Appropriate action.', exampleVN: 'Có hành động thích hợp.' },
  { id: '741', word: 'approval', meaning: 'sự chấp thuận', example: 'Need approval.', exampleVN: 'Cần được phê duyệt.' },
  { id: '742', word: 'approve', meaning: 'chấp thuận', example: 'Approve the plan.', exampleVN: 'Phê duyệt kế hoạch.' },
  { id: '743', word: 'approximate', meaning: 'xấp xỉ', example: 'Approximate cost.', exampleVN: 'Ước tính chi phí.' },
  { id: '744', word: 'arbitrary', meaning: 'tùy tiện', example: 'Arbitrary rule.', exampleVN: 'Cai trị tùy tiện.' },
  { id: '745', word: 'architect', meaning: 'kiến trúc sư', example: 'Lead architect.', exampleVN: 'Kiến ​​trúc sư trưởng.' },
  { id: '746', word: 'architecture', meaning: 'kiến trúc', example: 'Modern architecture.', exampleVN: 'Kiến ​​trúc hiện đại.' },
  { id: '747', word: 'archive', meaning: 'lưu trữ', example: 'Email archive.', exampleVN: 'Lưu trữ email.' },
  { id: '748', word: 'argue', meaning: 'tranh luận', example: 'Argue with him.', exampleVN: 'Tranh luận với anh ta.' },
  { id: '749', word: 'argument', meaning: 'lý lẽ', example: 'Valid argument.', exampleVN: 'Lập luận hợp lệ.' },
  { id: '750', word: 'arise', meaning: 'phát sinh', example: 'Problems arise.', exampleVN: 'Những vấn đề phát sinh.' },
  { id: '751', word: 'arm', meaning: 'cánh tay, vũ trang', example: 'Break an arm.', exampleVN: 'Bẻ gãy một cánh tay.' },
  { id: '752', word: 'army', meaning: 'quân đội', example: 'Join the army.', exampleVN: 'Gia nhập quân đội.' },
  { id: '753', word: 'around', meaning: 'xung quanh', example: 'Look around.', exampleVN: 'Nhìn xung quanh.' },
  { id: '754', word: 'arrange', meaning: 'sắp xếp', example: 'Arrange a meeting.', exampleVN: 'Sắp xếp một cuộc gặp.' },
  { id: '755', word: 'arrangement', meaning: 'sự sắp xếp', example: 'Seating arrangement.', exampleVN: 'Sắp xếp chỗ ngồi.' },
  { id: '756', word: 'arrest', meaning: 'bắt giữ', example: 'Under arrest.', exampleVN: 'Bị bắt giữ.' },
  { id: '757', word: 'arrive', meaning: 'đến nơi', example: 'Arrive on time.', exampleVN: 'Đến đúng giờ.' },
  { id: '758', word: 'article', meaning: 'bài báo', example: 'Newspaper article.', exampleVN: 'Bài báo.' },
  { id: '759', word: 'artist', meaning: 'nghệ sĩ', example: 'Famous artist.', exampleVN: 'Nghệ sĩ nổi tiếng.' },
  { id: '760', word: 'aspect', meaning: 'khía cạnh', example: 'Every aspect.', exampleVN: 'Mọi khía cạnh.' },
  { id: '761', word: 'assemble', meaning: 'lắp ráp', example: 'Assemble parts.', exampleVN: 'Lắp ráp các bộ phận.' },
  { id: '762', word: 'assembly', meaning: 'sự lắp ráp', example: 'Assembly line.', exampleVN: 'Đến dây chuyền lắp ráp.' },
  { id: '763', word: 'assert', meaning: 'khẳng định', example: 'Assert your rights.', exampleVN: 'Khẳng định quyền lợi của bạn.' },
  { id: '764', word: 'assess', meaning: 'đánh giá', example: 'Assess the damage.', exampleVN: 'Đánh giá thiệt hại.' },
  { id: '765', word: 'assessment', meaning: 'sự đánh giá', example: 'Risk assessment.', exampleVN: 'Đánh giá rủi ro.' },
  { id: '766', word: 'asset', meaning: 'tài sản', example: 'Company asset.', exampleVN: 'Tài sản của công ty.' },
  { id: '767', word: 'assign', meaning: 'phân công', example: 'Assign tasks.', exampleVN: 'Phân công nhiệm vụ.' },
  { id: '768', word: 'assignment', meaning: 'nhiệm vụ', example: 'Homework assignment.', exampleVN: 'Bài tập về nhà.' },
  { id: '769', word: 'assist', meaning: 'hỗ trợ', example: 'Assist customers.', exampleVN: 'Hỗ trợ khách hàng.' },
  { id: '770', word: 'assistance', meaning: 'sự hỗ trợ', example: 'Need assistance.', exampleVN: 'Cần hỗ trợ.' },
  { id: '771', word: 'assistant', meaning: 'trợ lý', example: 'Personal assistant.', exampleVN: 'Trợ lý cá nhân.' },
  { id: '772', word: 'associate', meaning: 'liên kết, đối tác', example: 'Business associate.', exampleVN: 'Cộng tác viên kinh doanh.' },
  { id: '773', word: 'association', meaning: 'hiệp hội', example: 'Trade association.', exampleVN: 'Hiệp hội thương mại.' },
  { id: '774', word: 'assume', meaning: 'giả định, đảm nhận', example: 'Assume control.', exampleVN: 'Nắm quyền kiểm soát.' },
  { id: '775', word: 'assumption', meaning: 'giả định', example: 'Wrong assumption.', exampleVN: 'Giả định sai lầm.' },
  { id: '776', word: 'assure', meaning: 'đảm bảo', example: 'I assure you.', exampleVN: 'Tôi đảm bảo với bạn.' },
  { id: '777', word: 'atmosphere', meaning: 'không khí, bầu khí quyển', example: 'Relaxed atmosphere.', exampleVN: 'Bầu không khí thoải mái.' },
  { id: '778', word: 'attach', meaning: 'đính kèm', example: 'Attach a file.', exampleVN: 'Đính kèm một tập tin.' },
  { id: '779', word: 'attack', meaning: 'tấn công', example: 'Heart attack.', exampleVN: 'Cơn đau tim.' },
  { id: '780', word: 'attempt', meaning: 'nỗ lực', example: 'Make an attempt.', exampleVN: 'Cố gắng.' },
  { id: '781', word: 'attend', meaning: 'tham dự', example: 'Attend a meeting.', exampleVN: 'Tham dự một cuộc họp.' },
  { id: '782', word: 'attention', meaning: 'sự chú ý', example: 'Pay attention.', exampleVN: 'Chú ý.' },
  { id: '783', word: 'attitude', meaning: 'thái độ', example: 'Positive attitude.', exampleVN: 'Thái độ tích cực.' },
  { id: '784', word: 'attorney', meaning: 'luật sư', example: 'Defense attorney.', exampleVN: 'Luật sư bào chữa.' },
  { id: '785', word: 'attract', meaning: 'thu hút', example: 'Attract investors.', exampleVN: 'Thu hút các nhà đầu tư.' },
  { id: '786', word: 'attraction', meaning: 'sức hút, điểm tham quan', example: 'Tourist attraction.', exampleVN: 'Thu hút khách du lịch.' },
  { id: '787', word: 'attractive', meaning: 'hấp dẫn', example: 'Attractive offer.', exampleVN: 'Đưa ra lời đề nghị hấp dẫn.' },
  { id: '788', word: 'attribute', meaning: 'thuộc tính. gán cho', example: 'Key attribute.', exampleVN: 'Thuộc tính quan trọng.' },
  { id: '789', word: 'auction', meaning: 'đấu giá', example: 'Art auction.', exampleVN: 'Đấu giá nghệ thuật.' },
  { id: '790', word: 'audience', meaning: 'khán giả', example: 'Target audience.', exampleVN: 'Đối tượng mục tiêu.' },
  { id: '791', word: 'audit', meaning: 'kiểm toán', example: 'Annual audit.', exampleVN: 'Kiểm toán hàng năm.' },
  { id: '792', word: 'author', meaning: 'tác giả', example: 'Book author.', exampleVN: 'Đặt tác giả.' },
  { id: '793', word: 'authority', meaning: 'thẩm quyền', example: 'Local authority.', exampleVN: 'Chính quyền địa phương.' },
  { id: '794', word: 'authorize', meaning: 'ủy quyền', example: 'Authorize payment.', exampleVN: 'Ủy quyền thanh toán.' },
  { id: '795', word: 'auto', meaning: 'ô tô tự động', example: 'Auto repair.', exampleVN: 'Sửa chữa ô tô.' },
  { id: '796', word: 'automatic', meaning: 'tự động', example: 'Automatic renewal.', exampleVN: 'Tự động gia hạn.' },
  { id: '797', word: 'available', meaning: 'có sẵn', example: 'Available online.', exampleVN: 'Có sẵn trực tuyến.' },
  { id: '798', word: 'avenue', meaning: 'đại lộ', example: 'Fifth Avenue.', exampleVN: 'Đại lộ thứ năm.' },
  { id: '799', word: 'average', meaning: 'trung bình', example: 'Average income.', exampleVN: 'Thu nhập trung bình.' },
  { id: '800', word: 'avoid', meaning: 'tránh', example: 'Avoid mistakes.', exampleVN: 'Tránh những sai lầm.' }
];

export const processChunk6 = () => chunk6;
