import { Word } from './types';

export const chunk8: Word[] = [
  { id: '901', word: 'capacity', meaning: 'sức chứa, năng lực', example: 'Max capacity.', exampleVN: 'Công suất tối đa.' },
  { id: '902', word: 'capital', meaning: 'vốn', example: 'Venture capital.', exampleVN: 'Đầu tư mạo hiểm.' },
  { id: '903', word: 'captain', meaning: 'đội trưởng', example: 'Team captain.', exampleVN: 'Đội trưởng.' },
  { id: '904', word: 'capture', meaning: 'chụp lấy', example: 'Capture market.', exampleVN: 'Nắm bắt thị trường.' },
  { id: '905', word: 'card', meaning: 'thẻ', example: 'Credit card.', exampleVN: 'Thẻ tín dụng.' },
  { id: '906', word: 'care', meaning: 'chăm sóc', example: 'Take care.', exampleVN: 'Chăm sóc.' },
  { id: '907', word: 'career', meaning: 'sự nghiệp', example: 'Career path.', exampleVN: 'Con đường sự nghiệp.' },
  { id: '908', word: 'careful', meaning: 'cẩn thận', example: 'Be careful.', exampleVN: 'Cẩn thận.' },
  { id: '909', word: 'cargo', meaning: 'hàng hóa', example: 'Cargo ship.', exampleVN: 'Tàu chở hàng.' },
  { id: '910', word: 'carpet', meaning: 'thảm', example: 'Red carpet.', exampleVN: 'Thảm đỏ.' },
  { id: '911', word: 'carrier', meaning: 'người vận chuyển', example: 'Mail carrier.', exampleVN: 'Người vận chuyển thư.' },
  { id: '912', word: 'cart', meaning: 'xe đẩy hàng', example: 'Shopping cart.', exampleVN: 'Giỏ hàng.' },
  { id: '913', word: 'cash', meaning: 'tiền mặt', example: 'Pay in cash.', exampleVN: 'Thanh toán bằng tiền mặt.' },
  { id: '914', word: 'cast', meaning: 'dàn diễn viên', example: 'Great cast.', exampleVN: 'Dàn diễn viên tuyệt vời.' },
  { id: '915', word: 'casual', meaning: 'bình thường', example: 'Casual dress.', exampleVN: 'Ăn mặc giản dị.' },
  { id: '916', word: 'catalog', meaning: 'danh mục', example: 'View catalog.', exampleVN: 'Xem danh mục.' },
  { id: '917', word: 'catch', meaning: 'bắt', example: 'Catch fire.', exampleVN: 'Bắt lửa.' },
  { id: '918', word: 'category', meaning: 'thể loại', example: 'Main category.', exampleVN: 'Danh mục chính.' },
  { id: '919', word: 'cause', meaning: 'nguyên nhân', example: 'Cause trouble.', exampleVN: 'Gây rắc rối.' },
  { id: '920', word: 'caution', meaning: 'cảnh báo', example: 'Use caution.', exampleVN: 'Sử dụng thận trọng.' },
  { id: '921', word: 'cautious', meaning: 'thận trọng', example: 'Cautious approach.', exampleVN: 'Tiếp cận thận trọng.' },
  { id: '922', word: 'cave', meaning: 'hang động', example: 'Dark cave.', exampleVN: 'Hang tối.' },
  { id: '923', word: 'cease', meaning: 'chấm dứt', example: 'Cease operations.', exampleVN: 'Ngừng hoạt động.' },
  { id: '924', word: 'ceiling', meaning: 'trần nhà', example: 'Glass ceiling.', exampleVN: 'Trần kính.' },
  { id: '925', word: 'celebrate', meaning: 'ăn mừng', example: 'Celebrate win.', exampleVN: 'Ăn mừng chiến thắng.' },
  { id: '926', word: 'celebration', meaning: 'sự kỷ niệm', example: 'Big celebration.', exampleVN: 'Lễ kỷ niệm lớn.' },
  { id: '927', word: 'cell', meaning: 'tế bào', example: 'Stem cell.', exampleVN: 'Tế bào gốc.' },
  { id: '928', word: 'central', meaning: 'trung tâm', example: 'Central bank.', exampleVN: 'Đến ngân hàng trung ương.' },
  { id: '929', word: 'centre', meaning: 'trung tâm', example: 'City centre.', exampleVN: 'Trung tâm thành phố.' },
  { id: '930', word: 'century', meaning: 'thế kỷ', example: '21st century.', exampleVN: 'Thế kỷ 21.' },
  { id: '931', word: 'ceremony', meaning: 'nghi lễ', example: 'Awards ceremony.', exampleVN: 'Lễ trao giải.' },
  { id: '932', word: 'certain', meaning: 'chắc chắn', example: 'Make certain.', exampleVN: 'Đảm bảo chắc chắn.' },
  { id: '933', word: 'certainly', meaning: 'chắc chắn(adv)', example: 'Certainly true.', exampleVN: 'Chắc chắn đúng.' },
  { id: '934', word: 'certificate', meaning: 'giấy chứng nhận', example: 'Gift certificate.', exampleVN: 'Phiếu quà tặng.' },
  { id: '935', word: 'chain', meaning: 'chuỗi', example: 'Supply chain.', exampleVN: 'Chuỗi cung ứng.' },
  { id: '936', word: 'chair', meaning: 'ghế', example: 'Empty chair.', exampleVN: 'Chiếc ghế trống.' },
  { id: '937', word: 'chairman', meaning: 'chủ tịch', example: 'Board chairman.', exampleVN: 'Chủ tịch hội đồng quản trị.' },
  { id: '938', word: 'challenge', meaning: 'thách thức', example: 'Tough challenge.', exampleVN: 'Thử thách khó khăn.' },
  { id: '939', word: 'chamber', meaning: 'phòng', example: 'Chamber of commerce.', exampleVN: 'Đến phòng thương mại.' },
  { id: '940', word: 'champion', meaning: 'nhà vô địch', example: 'World champion.', exampleVN: 'Nhà vô địch thế giới.' },
  { id: '941', word: 'championship', meaning: 'giải vô địch', example: 'Win championship.', exampleVN: 'Giành chức vô địch.' },
  { id: '942', word: 'chance', meaning: 'cơ hội', example: 'Good chance.', exampleVN: 'Cơ hội tốt.' },
  { id: '943', word: 'change', meaning: 'thay đổi', example: 'Climate change.', exampleVN: 'Vấn đề biến đổi khí hậu.' },
  { id: '944', word: 'channel', meaning: 'kênh', example: 'Sales channel.', exampleVN: 'Kênh bán hàng.' },
  { id: '945', word: 'chapter', meaning: 'chương', example: 'Next chapter.', exampleVN: 'Chương tiếp theo.' },
  { id: '946', word: 'character', meaning: 'nhân vật', example: 'Main character.', exampleVN: 'Nhân vật chính.' },
  { id: '947', word: 'characteristic', meaning: 'đặc điểm', example: 'Key characteristic.', exampleVN: 'Đặc điểm chính.' },
  { id: '948', word: 'charge', meaning: 'tính phí', example: 'Free of charge.', exampleVN: 'Miễn phí.' },
  { id: '949', word: 'charity', meaning: 'từ thiện', example: 'Local charity.', exampleVN: 'Hoạt động từ thiện địa phương.' },
  { id: '950', word: 'chart', meaning: 'biểu đồ', example: 'Flow chart.', exampleVN: 'Biểu đồ dòng chảy.' },
  { id: '951', word: 'chase', meaning: 'theo đuổi', example: 'Chase a dream.', exampleVN: 'Theo đuổi một giấc mơ.' },
  { id: '952', word: 'cheap', meaning: 'rẻ', example: 'Cheap price.', exampleVN: 'Giá rẻ.' },
  { id: '953', word: 'cheat', meaning: 'gian lận', example: 'Cheat on test.', exampleVN: 'Gian lận trong bài kiểm tra.' },
  { id: '954', word: 'check', meaning: 'kiểm tra', example: 'Check the mail.', exampleVN: 'Kiểm tra thư.' },
  { id: '955', word: 'cheerful', meaning: 'vui vẻ', example: 'Cheerful mood.', exampleVN: 'Tâm trạng vui vẻ.' },
  { id: '956', word: 'cheese', meaning: 'phô mai', example: 'Swiss cheese.', exampleVN: 'Phô mai Thụy Sĩ.' },
  { id: '957', word: 'chef', meaning: 'đầu bếp', example: 'Head chef.', exampleVN: 'Bếp trưởng.' },
  { id: '958', word: 'chemical', meaning: 'hóa chất', example: 'Chemical reaction.', exampleVN: 'Phản ứng hóa học.' },
  { id: '959', word: 'chemistry', meaning: 'hóa học', example: 'Chemistry class.', exampleVN: 'Đến lớp hóa học.' },
  { id: '960', word: 'chest', meaning: 'ngực', example: 'Chest pain.', exampleVN: 'Đau ngực.' },
  { id: '961', word: 'chicken', meaning: 'gà', example: 'Fried chicken.', exampleVN: 'Món gà rán.' },
  { id: '962', word: 'chief', meaning: 'giám đốc, chính', example: 'Chief executive.', exampleVN: 'Có giám đốc điều hành.' },
  { id: '963', word: 'child', meaning: 'đứa trẻ', example: 'Only child.', exampleVN: 'Đứa trẻ duy nhất.' },
  { id: '964', word: 'childhood', meaning: 'tuổi thơ', example: 'Happy childhood.', exampleVN: 'Tuổi thơ hạnh phúc.' },
  { id: '965', word: 'chip', meaning: 'vi mạch, khoai tây chiên', example: 'Computer chip.', exampleVN: 'Chip máy tính.' },
  { id: '966', word: 'choice', meaning: 'sự lựa chọn', example: 'Multiple choice.', exampleVN: 'Câu hỏi trắc nghiệm.' },
  { id: '967', word: 'choose', meaning: 'chọn', example: 'Choose wisely.', exampleVN: 'Lựa chọn một cách khôn ngoan.' },
  { id: '968', word: 'church', meaning: 'nhà thờ', example: 'Go to church.', exampleVN: 'Đi nhà thờ.' },
  { id: '969', word: 'cigarette', meaning: 'thuốc lá', example: 'Smoke cigarette.', exampleVN: 'Hút thuốc lá.' },
  { id: '970', word: 'circle', meaning: 'vòng tròn', example: 'Draw a circle.', exampleVN: 'Vẽ một vòng tròn.' },
  { id: '971', word: 'circuit', meaning: 'mạch điện', example: 'Short circuit.', exampleVN: 'Vấn đề ngắn mạch.' },
  { id: '972', word: 'circumstance', meaning: 'hoàn cảnh', example: 'Under circumstance.', exampleVN: 'Trong hoàn cảnh.' },
  { id: '973', word: 'cite', meaning: 'trích dẫn', example: 'Cite a source.', exampleVN: 'Trích dẫn nguồn.' },
  { id: '974', word: 'citizen', meaning: 'công dân', example: 'Global citizen.', exampleVN: 'Công dân toàn cầu.' },
  { id: '975', word: 'city', meaning: 'thành phố', example: 'Inner city.', exampleVN: 'Nội thành.' },
  { id: '976', word: 'civil', meaning: 'dân sự', example: 'Civil rights.', exampleVN: 'Có quyền công dân.' },
  { id: '977', word: 'claim', meaning: 'yêu cầu bồi thường', example: 'Make a claim.', exampleVN: 'Đưa ra yêu cầu bồi thường.' },
  { id: '978', word: 'class', meaning: 'lớp học', example: 'Middle class.', exampleVN: 'Tầng lớp trung lưu.' },
  { id: '979', word: 'classic', meaning: 'cổ điển', example: 'Classic style.', exampleVN: 'Phong cách cổ điển.' },
  { id: '980', word: 'classical', meaning: 'nhạc cổ điển', example: 'Classical music.', exampleVN: 'Âm nhạc cổ điển.' },
  { id: '981', word: 'classroom', meaning: 'phòng học', example: 'Empty classroom.', exampleVN: 'Lớp học trống.' },
  { id: '982', word: 'clean', meaning: 'sạch', example: 'Clean energy.', exampleVN: 'Làm sạch năng lượng.' },
  { id: '983', word: 'clear', meaning: 'rõ ràng', example: 'Crystal clear.', exampleVN: 'Sự rõ ràng như pha lê.' },
  { id: '984', word: 'clearly', meaning: 'rõ ràng(adv)', example: 'State clearly.', exampleVN: 'Trạng thái rõ ràng.' },
  { id: '985', word: 'clerk', meaning: 'nhân viên bán hàng', example: 'Sales clerk.', exampleVN: 'Nhân viên bán hàng.' },
  { id: '986', word: 'click', meaning: 'nhấn chuột', example: 'Click here.', exampleVN: 'Bấm vào đây.' },
  { id: '987', word: 'client', meaning: 'khách hàng', example: 'Loyal client.', exampleVN: 'Khách hàng trung thành.' },
  { id: '988', word: 'climate', meaning: 'khí hậu', example: 'Climate change.', exampleVN: 'Biến đổi khí hậu.' },
  { id: '989', word: 'climb', meaning: 'leo', example: 'Climb a mountain.', exampleVN: 'Leo lên một ngọn núi.' },
  { id: '990', word: 'clinic', meaning: 'phòng khám', example: 'Dental clinic.', exampleVN: 'Phòng khám nha khoa.' },
  { id: '991', word: 'clock', meaning: 'đồng hồ', example: 'Wall clock.', exampleVN: 'Đồng hồ treo tường.' },
  { id: '992', word: 'close', meaning: 'đóng', example: 'Close the door.', exampleVN: 'Đóng cửa lại.' },
  { id: '993', word: 'closely', meaning: 'chặt chẽ', example: 'Watch closely.', exampleVN: 'Theo dõi chặt chẽ.' },
  { id: '994', word: 'clothes', meaning: 'quần áo', example: 'Wash clothes.', exampleVN: 'Giặt quần áo.' },
  { id: '995', word: 'clothing', meaning: 'quần áo', example: 'Winter clothing.', exampleVN: 'Quần áo mùa đông.' },
  { id: '996', word: 'cloud', meaning: 'đám mây', example: 'Dark cloud.', exampleVN: 'Đám mây đen.' },
  { id: '997', word: 'club', meaning: 'câu lạc bộ', example: 'Join a club.', exampleVN: 'Tham gia một câu lạc bộ.' },
  { id: '998', word: 'clue', meaning: 'manh mối', example: 'Find a clue.', exampleVN: 'Tìm ra manh mối.' },
  { id: '999', word: 'coach', meaning: 'huấn luyện viên', example: 'Head coach.', exampleVN: 'Huấn luyện viên trưởng.' },
  { id: '1000', word: 'coal', meaning: 'than đá', example: 'Coal mine.', exampleVN: 'Khai thác than.' }
];

export const processChunk8 = () => chunk8;
