import { Word } from './types';

export const chunk4: Word[] = [
  { id: '451', word: 'estimate', meaning: 'ước tính', example: 'Estimate cost.', exampleVN: 'Ước tính chi phí.' },
  { id: '452', word: 'evaluate', meaning: 'đánh giá', example: 'Evaluate performance.', exampleVN: 'Đánh giá hiệu suất.' },
  { id: '453', word: 'even', meaning: 'thậm chí', example: 'Even more.', exampleVN: 'Nhiều hơn nữa.' },
  { id: '454', word: 'evening', meaning: 'buổi tối', example: 'Good evening.', exampleVN: 'Buổi tối tốt lành.' },
  { id: '455', word: 'event', meaning: 'sự kiện', example: 'Main event.', exampleVN: 'Sự kiện chính.' },
  { id: '456', word: 'eventually', meaning: 'cuối cùng', example: 'Eventually finished.', exampleVN: 'Cuối cùng chúng ta cần phải hoàn thành.' },
  { id: '457', word: 'ever', meaning: 'bao giờ', example: 'Best ever.', exampleVN: 'Điều tốt nhất từ ​​trước đến nay.' },
  { id: '458', word: 'every', meaning: 'mọi', example: 'Every day.', exampleVN: 'Mỗi ngày.' },
  { id: '459', word: 'evidence', meaning: 'bằng chứng', example: 'Clear evidence.', exampleVN: 'Làm rõ bằng chứng.' },
  { id: '460', word: 'exact', meaning: 'chính xác', example: 'Exact match.', exampleVN: 'Khớp chính xác.' },
  { id: '461', word: 'exactly', meaning: 'chính xác', example: 'Exactly right.', exampleVN: 'Chính xác.' },
  { id: '462', word: 'examine', meaning: 'kiểm tra', example: 'Examine thoroughly.', exampleVN: 'Kiểm tra kỹ lưỡng.' },
  { id: '463', word: 'example', meaning: 'ví dụ', example: 'For example.', exampleVN: 'Ví dụ.' },
  { id: '464', word: 'exceed', meaning: 'vượt mức', example: 'Exceed limit.', exampleVN: 'Vượt quá giới hạn.' },
  { id: '465', word: 'excellent', meaning: 'tuyệt vời', example: 'Excellent service.', exampleVN: 'Dịch vụ xuất sắc.' },
  { id: '466', word: 'except', meaning: 'ngoại trừ', example: 'Except for this.', exampleVN: 'Ngoại trừ điều này.' },
  { id: '467', word: 'exception', meaning: 'ngoại lệ', example: 'With the exception.', exampleVN: 'Ngoại lệ.' },
  { id: '468', word: 'exchange', meaning: 'đổi', example: 'Exchange ideas.', exampleVN: 'Trao đổi ý kiến.' },
  { id: '469', word: 'excite', meaning: 'làm hứng thú', example: 'Excite the fans.', exampleVN: 'kích thích người hâm mộ.' },
  { id: '470', word: 'exclude', meaning: 'loại trừ', example: 'Exclude from list.', exampleVN: 'Loại trừ khỏi danh sách.' },
  { id: '471', word: 'excuse', meaning: 'lý do', example: 'No excuse.', exampleVN: 'Không có lý do gì.' },
  { id: '472', word: 'execute', meaning: 'thực thi', example: 'Execute order.', exampleVN: 'Thực hiện mệnh lệnh.' },
  { id: '473', word: 'executive', meaning: 'quản lý', example: 'Executive director.', exampleVN: 'Giám đốc điều hành.' },
  { id: '474', word: 'exercise', meaning: 'tập thể dục', example: 'Exercise daily.', exampleVN: 'Tập thể dục hàng ngày.' },
  { id: '475', word: 'exhibit', meaning: 'triển lãm', example: 'Exhibit art.', exampleVN: 'Thể hiện nghệ thuật.' },
  { id: '476', word: 'exhibition', meaning: 'cuộc triển lãm', example: 'Art exhibition.', exampleVN: 'Triển lãm nghệ thuật.' },
  { id: '477', word: 'exist', meaning: 'tồn tại', example: 'Exist in nature.', exampleVN: 'Tồn tại trong tự nhiên.' },
  { id: '478', word: 'expect', meaning: 'kỳ vọng', example: 'Expect results.', exampleVN: 'Mong đợi kết quả.' },
  { id: '479', word: 'expectation', meaning: 'sự kỳ vọng', example: 'High expectation.', exampleVN: 'Kỳ vọng cao.' },
  { id: '480', word: 'expensive', meaning: 'đắt', example: 'Expensive car.', exampleVN: 'Xe đắt tiền.' },
  { id: '481', word: 'experience', meaning: 'kinh nghiệm', example: 'User experience.', exampleVN: 'Trải nghiệm người dùng.' },
  { id: '482', word: 'experiment', meaning: 'cuộc thí nghiệm', example: 'Do an experiment.', exampleVN: 'Làm một thí nghiệm.' },
  { id: '483', word: 'expert', meaning: 'chuyên gia', example: 'Industry expert.', exampleVN: 'Chuyên gia trong ngành.' },
  { id: '484', word: 'explain', meaning: 'gỉải thích', example: 'Explain clearly.', exampleVN: 'Giải thích rõ ràng.' },
  { id: '485', word: 'explanation', meaning: 'sự giải thích', example: 'Detailed explanation.', exampleVN: 'Giải thích chi tiết.' },
  { id: '486', word: 'explore', meaning: 'khám phá', example: 'Explore options.', exampleVN: 'Khám phá các lựa chọn.' },
  { id: '487', word: 'export', meaning: 'xuất khẩu', example: 'Export goods.', exampleVN: 'Xuất khẩu hàng hóa.' },
  { id: '488', word: 'expose', meaning: 'bày tỏ', example: 'Expose to danger.', exampleVN: 'Đối mặt với nguy hiểm.' },
  { id: '489', word: 'express', meaning: 'bày tỏ', example: 'Express interest.', exampleVN: 'Bày tỏ sự quan tâm.' },
  { id: '490', word: 'extend', meaning: 'mở rộng', example: 'Extend deadline.', exampleVN: 'Gia hạn thời hạn.' },
  { id: '491', word: 'extension', meaning: 'sự gia hạn', example: 'Deadline extension.', exampleVN: 'Gia hạn thời hạn.' },
  { id: '492', word: 'extensive', meaning: 'mở rộng', example: 'Extensive research.', exampleVN: 'Nghiên cứu sâu rộng.' },
  { id: '493', word: 'extent', meaning: 'mức độ', example: 'To some extent.', exampleVN: 'Ở một mức độ nào đó.' },
  { id: '494', word: 'external', meaning: 'bên ngoài', example: 'External force.', exampleVN: 'Đến lực lượng bên ngoài.' },
  { id: '495', word: 'extra', meaning: 'thêm', example: 'Extra cost.', exampleVN: 'trả thêm chi phí.' },
  { id: '496', word: 'extract', meaning: 'chiết xuất', example: 'Extract data.', exampleVN: 'Trích xuất dữ liệu.' },
  { id: '497', word: 'extreme', meaning: 'cực độ', example: 'Extreme weather.', exampleVN: 'Thời tiết khắc nghiệt.' },
  { id: '498', word: 'eye', meaning: 'mắt', example: 'Keep an eye on.', exampleVN: 'Để mắt tới.' },
  { id: '499', word: 'fabricate', meaning: 'chế tạo', example: 'Fabricate evidence.', exampleVN: 'Bịa đặt bằng chứng.' },
  { id: '500', word: 'face', meaning: 'đối mặt', example: 'Face to face.', exampleVN: 'Đối mặt.' },
  { id: '501', word: 'facilitate', meaning: 'tạo điều kiện', example: 'Facilitate process.', exampleVN: 'Tạo điều kiện thuận lợi cho quá trình này.' },
  { id: '502', word: 'facility', meaning: 'cơ sở', example: 'Sports facility.', exampleVN: 'Cơ sở thể thao.' },
  { id: '503', word: 'fact', meaning: 'sự thật', example: 'In fact.', exampleVN: 'Thực tế.' },
  { id: '504', word: 'factor', meaning: 'thành phần', example: 'Key factor.', exampleVN: 'Yếu tố then chốt.' },
  { id: '505', word: 'factory', meaning: 'nhà máy', example: 'Factory worker.', exampleVN: 'Công nhân nhà máy.' },
  { id: '506', word: 'fail', meaning: 'thất bại', example: 'Do not be afraid to fail.', exampleVN: 'Đừng sợ thất bại.' },
  { id: '507', word: 'failure', meaning: 'sự thất bại', example: 'System failure.', exampleVN: 'Lỗi hệ thống.' },
  { id: '508', word: 'fair', meaning: 'công bằng', example: 'Fair play.', exampleVN: 'Chơi công bằng.' },
  { id: '509', word: 'fall', meaning: 'rơi', example: 'Fall down.', exampleVN: 'Rơi xuống.' },
  { id: '510', word: 'false', meaning: 'sai', example: 'False alarm.', exampleVN: 'Báo động sai.' },
  { id: '511', word: 'familiar', meaning: 'quen thuộc', example: 'Familiar face.', exampleVN: 'Làm quen khuôn mặt.' },
  { id: '512', word: 'family', meaning: 'gia đình', example: 'Family tie.', exampleVN: 'Sự ràng buộc gia đình.' },
  { id: '513', word: 'famous', meaning: 'nổi tiếng', example: 'Famous brand.', exampleVN: 'Thương hiệu nổi tiếng.' },
  { id: '514', word: 'fan', meaning: 'quạt', example: 'Ceiling fan.', exampleVN: 'Quạt trần.' },
  { id: '515', word: 'fantastic', meaning: 'tuyệt vời', example: 'Fantastic view.', exampleVN: 'Có cái nhìn tuyệt vời.' },
  { id: '516', word: 'far', meaning: 'xa', example: 'Far away.', exampleVN: 'Đi thật xa' },
  { id: '517', word: 'farm', meaning: 'nông trại', example: 'Farm animal.', exampleVN: 'Chăn nuôi động vật.' },
  { id: '518', word: 'farmer', meaning: 'nông phu', example: 'Local farmer.', exampleVN: 'Nông dân địa phương.' },
  { id: '519', word: 'fascinate', meaning: 'mê hoặc', example: 'Fascinate audience.', exampleVN: 'Mê hoặc khán giả.' },
  { id: '520', word: 'fashion', meaning: 'kiểu cách', example: 'Latest fashion.', exampleVN: 'Thời trang mới nhất.' },
  { id: '521', word: 'fast', meaning: 'nhanh', example: 'Fast food.', exampleVN: 'Thức ăn nhanh.' },
  { id: '522', word: 'fasten', meaning: 'buộc chặt', example: 'Fasten seatbelt.', exampleVN: 'Thắt dây an toàn.' },
  { id: '523', word: 'fat', meaning: 'béo', example: 'Body fat.', exampleVN: 'Lượng mỡ trong cơ thể.' },
  { id: '524', word: 'father', meaning: 'cha', example: 'My father.', exampleVN: 'Họ thảo luận về cha tôi.' },
  { id: '525', word: 'fault', meaning: 'lỗi', example: 'My fault.', exampleVN: 'Họ thảo luận về lỗi của tôi.' },
  { id: '526', word: 'favor', meaning: 'sự chiếu cố', example: 'Do me a favor.', exampleVN: 'Giúp tôi một việc.' },
  { id: '527', word: 'favorite', meaning: 'ưa thích', example: 'Favorite movie.', exampleVN: 'Yêu thích bộ phim.' },
  { id: '528', word: 'fear', meaning: 'nỗi sợ', example: 'Overcome fear.', exampleVN: 'Vượt qua nỗi sợ hãi.' },
  { id: '529', word: 'feature', meaning: 'đặc tính', example: 'Key feature.', exampleVN: 'Tính năng chính.' },
  { id: '530', word: 'federal', meaning: 'liên bang', example: 'Federal law.', exampleVN: 'Luật liên bang.' },
  { id: '531', word: 'fee', meaning: 'lệ phí', example: 'Entrance fee.', exampleVN: 'Phí vào cửa.' },
  { id: '532', word: 'feed', meaning: 'sự ăn', example: 'Cattle feed.', exampleVN: 'Thức ăn gia súc.' },
  { id: '533', word: 'feedback', meaning: 'phản hồi', example: 'Customer feedback.', exampleVN: 'Phản hồi của khách hàng.' },
  { id: '534', word: 'feel', meaning: 'cảm thấy', example: 'Feel good.', exampleVN: 'Cảm thấy tốt.' },
  { id: '535', word: 'feeling', meaning: 'cảm giác', example: 'Good feeling.', exampleVN: 'Cảm giác tốt.' },
  { id: '536', word: 'female', meaning: 'giống cái', example: 'Female worker.', exampleVN: 'Tuyển nhân viên nữ.' },
  { id: '537', word: 'few', meaning: 'một ít', example: 'A few.', exampleVN: 'Họ đã thảo luận một vài điều.' },
  { id: '538', word: 'field', meaning: 'cánh đồng', example: 'Football field.', exampleVN: 'Sân bóng đá.' },
  { id: '539', word: 'fight', meaning: 'đấu tranh', example: 'Fight back.', exampleVN: 'Chiến đấu trở lại.' },
  { id: '540', word: 'figure', meaning: 'số liệu', example: 'Sales figure.', exampleVN: 'Con số bán hàng.' },
  { id: '541', word: 'file', meaning: 'tập tin', example: 'Attach file.', exampleVN: 'Đính kèm tập tin.' },
  { id: '542', word: 'fill', meaning: 'điền vào', example: 'Fill the form.', exampleVN: 'Điền vào mẫu đơn.' },
  { id: '543', word: 'film', meaning: 'phim', example: 'Short film.', exampleVN: 'Phim ngắn.' },
  { id: '544', word: 'final', meaning: 'cuối cùng', example: 'Final answer.', exampleVN: 'Câu trả lời cuối cùng.' },
  { id: '545', word: 'find', meaning: 'tìm', example: 'Find out.', exampleVN: 'Tìm hiểu.' },
  { id: '546', word: 'fine', meaning: 'tiền phạt', example: 'Pay a fine.', exampleVN: 'Nộp phạt.' },
  { id: '547', word: 'finish', meaning: 'kết thúc', example: 'Finish line.', exampleVN: 'Hoàn thành dòng.' },
  { id: '548', word: 'fire', meaning: 'sa thải', example: 'Fire someone.', exampleVN: 'Sa thải ai đó.' },
  { id: '549', word: 'firm', meaning: 'hãng', example: 'Law firm.', exampleVN: 'Công ty luật.' },
  { id: '550', word: 'first', meaning: 'đầu', example: 'First name.', exampleVN: 'Nêu tên.' },
  { id: '551', word: 'fish', meaning: 'cá', example: 'Catch fish.', exampleVN: 'Bắt cá.' },
  { id: '552', word: 'fit', meaning: 'vừa vặn', example: 'Fit perfectly.', exampleVN: 'Phù hợp một cách hoàn hảo.' },
  { id: '553', word: 'fix', meaning: 'cố định, sửa', example: 'Fix the bug.', exampleVN: 'Sửa lỗi.' },
  { id: '554', word: 'flat', meaning: 'bằng phẳng', example: 'Flat rate.', exampleVN: 'Có tỷ giá cố định.' },
  { id: '555', word: 'flight', meaning: 'chuyến bay', example: 'Direct flight.', exampleVN: 'Chuyến bay thẳng.' },
  { id: '556', word: 'floor', meaning: 'tầng', example: 'Top floor.', exampleVN: 'Tầng trên cùng.' },
  { id: '557', word: 'flow', meaning: 'chảy', example: 'Cash flow.', exampleVN: 'Dòng tiền.' },
  { id: '558', word: 'flower', meaning: 'hoa', example: 'Flower shop.', exampleVN: 'Đến cửa hàng hoa.' },
  { id: '559', word: 'fly', meaning: 'bay', example: 'Fly high.', exampleVN: 'Bay cao.' },
  { id: '560', word: 'focus', meaning: 'tập trung', example: 'Focus group.', exampleVN: 'Tập trung vào nhóm.' },
  { id: '561', word: 'fold', meaning: 'gấp lại', example: 'Fold the paper.', exampleVN: 'Gấp tờ giấy lại.' },
  { id: '562', word: 'follow', meaning: 'đi theo', example: 'Follow the rules.', exampleVN: 'Tuân theo các quy tắc.' },
  { id: '563', word: 'food', meaning: 'thực phẩm', example: 'Fast food.', exampleVN: 'Thức ăn nhanh.' },
  { id: '564', word: 'foot', meaning: 'chân', example: 'On foot.', exampleVN: 'Đi bộ.' },
  { id: '565', word: 'football', meaning: 'bóng đá', example: 'Football match.', exampleVN: 'Trận đấu bóng đá.' },
  { id: '566', word: 'for', meaning: 'cho', example: 'For sale.', exampleVN: 'Bán.' },
  { id: '567', word: 'force', meaning: 'bắt buột', example: 'Force to do.', exampleVN: 'Buộc phải làm.' },
  { id: '568', word: 'forecast', meaning: 'dự báo', example: 'Sales forecast.', exampleVN: 'Dự báo doanh thu.' },
  { id: '569', word: 'foreign', meaning: 'ngoại quốc', example: 'Foreign language.', exampleVN: 'Ngoại ngữ.' },
  { id: '570', word: 'forget', meaning: 'quên', example: "Don't forget.", exampleVN: "Đừng quên." },
  { id: '571', word: 'form', meaning: 'đơn', example: 'Order form.', exampleVN: 'Hình thức đặt hàng.' },
  { id: '572', word: 'formal', meaning: 'trang trọng', example: 'Formal dress.', exampleVN: 'Ăn mặc trang trọng.' },
  { id: '573', word: 'format', meaning: 'sự định dạng', example: 'File format.', exampleVN: 'Định dạng tập tin.' },
  { id: '574', word: 'former', meaning: 'cũ, trước', example: 'Former boss.', exampleVN: 'Ông chủ cũ.' },
  { id: '575', word: 'formula', meaning: 'công thức', example: 'Secret formula.', exampleVN: 'Công thức bí mật.' },
  { id: '576', word: 'forth', meaning: 'về phía', example: 'Back and forth.', exampleVN: 'Qua lại.' },
  { id: '577', word: 'fortunate', meaning: 'may mắn', example: 'Fortunate event.', exampleVN: 'Sự kiện may mắn.' },
  { id: '578', word: 'fortune', meaning: 'vận may', example: 'Make a fortune.', exampleVN: 'Kiếm tiền.' },
  { id: '579', word: 'forward', meaning: 'về phía trước', example: 'Looking forward.', exampleVN: 'Mong đợi.' },
  { id: '580', word: 'found', meaning: 'thành lập', example: 'Found a company.', exampleVN: 'Thành lập một công ty.' },
  { id: '581', word: 'foundation', meaning: 'nền tảng', example: 'Solid foundation.', exampleVN: 'Nền tảng vững chắc.' },
  { id: '582', word: 'frame', meaning: 'khung', example: 'Picture frame.', exampleVN: 'Khung hình.' },
  { id: '583', word: 'free', meaning: 'miễn phí', example: 'Free trial.', exampleVN: 'Dùng thử miễn phí.' },
  { id: '584', word: 'freedom', meaning: 'tự do', example: 'Freedom of speech.', exampleVN: 'Quyền tự do ngôn luận.' },
  { id: '585', word: 'freeze', meaning: 'đóng băng', example: 'Freeze account.', exampleVN: 'Đóng băng tài khoản.' },
  { id: '586', word: 'frequent', meaning: 'thường xuyên', example: 'Frequent flyer.', exampleVN: 'Bay thường xuyên.' },
  { id: '587', word: 'fresh', meaning: 'tươi', example: 'Fresh food.', exampleVN: 'Thực phẩm tươi sống.' },
  { id: '588', word: 'friend', meaning: 'bạn', example: 'Close friend.', exampleVN: 'Có một người bạn thân.' },
  { id: '589', word: 'front', meaning: 'mặt trước', example: 'In front.', exampleVN: 'Ở phía trước.' },
  { id: '590', word: 'fruit', meaning: 'trái cây', example: 'Fresh fruit.', exampleVN: 'Trái cây tươi.' },
  { id: '591', word: 'fuel', meaning: 'nhiên liệu', example: 'Fossil fuel.', exampleVN: 'Nhiên liệu hóa thạch.' },
  { id: '592', word: 'full', meaning: 'đầy', example: 'Full time.', exampleVN: 'làm việc toàn thời gian.' },
  { id: '593', word: 'fully', meaning: 'đầy đủ', example: 'Fully booked.', exampleVN: 'đặt chỗ đầy đủ.' },
  { id: '594', word: 'fun', meaning: 'sự thú vị', example: 'Have fun.', exampleVN: 'Vui chơi.' },
  { id: '595', word: 'function', meaning: 'chức năng', example: 'Main function.', exampleVN: 'Chức năng chính.' },
  { id: '596', word: 'fund', meaning: 'quỹ', example: 'Trust fund.', exampleVN: 'Quỹ tín thác.' },
  { id: '597', word: 'fundamental', meaning: 'cơ bản', example: 'Fundamental rule.', exampleVN: 'Cai trị cơ bản.' },
  { id: '598', word: 'funding', meaning: 'kinh phí', example: 'Government funding.', exampleVN: 'Nguồn tài trợ của chính phủ.' },
  { id: '599', word: 'furniture', meaning: 'đồ nội thất', example: 'Office furniture.', exampleVN: 'Nội thất văn phòng.' },
  { id: '600', word: 'further', meaning: 'hơn nửa', example: 'Further details.', exampleVN: 'Biết thêm chi tiết.' }
];

export const processChunk4 = () => {
    return chunk4.map(w => {
      let pos = '(v)';
      const nouns = new Set(['evening', 'event', 'evidence', 'example', 'exception', 'excuse', 'executive', 'exhibition', 'expectation', 'experience', 'expert', 'explanation', 'extension', 'extent', 'eye', 'facility', 'fact', 'factor', 'factory', 'failure', 'family', 'fan', 'farm', 'farmer', 'fashion', 'father', 'fault', 'favor', 'fear', 'feature', 'fee', 'feedback', 'feeling', 'female', 'field', 'figure', 'file', 'film', 'fine', 'firm', 'fish', 'flight', 'floor', 'flower', 'food', 'foot', 'football', 'forecast', 'form', 'format', 'formula', 'fortune', 'foundation', 'frame', 'freedom', 'friend', 'front', 'fruit', 'fuel', 'fun', 'function', 'fund', 'funding', 'furniture', 'future']);
      const adjs = new Set(['even', 'exact', 'excellent', 'expensive', 'extensive', 'external', 'extra', 'extreme', 'fair', 'false', 'familiar', 'famous', 'fantastic', 'far', 'fast', 'fat', 'favorite', 'federal', 'female', 'few', 'final', 'first', 'flat', 'foreign', 'formal', 'former', 'fortunate', 'free', 'frequent', 'fresh', 'front', 'full', 'fundamental', 'further']);
      const both = new Set(['estimate', 'exchange', 'exercise', 'exhibit', 'experience', 'experiment', 'export', 'express', 'extract', 'face', 'fall', 'farm', 'fashion', 'fast', 'favor', 'fear', 'feature', 'feed', 'feel', 'female', 'fight', 'figure', 'file', 'fill', 'film', 'fine', 'finish', 'fire', 'firm', 'fish', 'fit', 'fix', 'flat', 'flow', 'fly', 'focus', 'fold', 'force', 'forecast', 'form', 'format', 'forward', 'frame', 'free', 'freeze', 'front', 'function', 'fund', 'further', 'future']);
      if (nouns.has(w.word)) pos = '(n)';
      else if (adjs.has(w.word)) pos = '(adj)';
      else if (both.has(w.word)) pos = '(n, v)';
      return { ...w, pos };
    });
};
