import { Word } from './types';

export const chunkMochi: Word[] = [
  { id: 'm1', word: 'ability', meaning: 'năng lực, khả năng', example: 'The manager has the ability to motivate the team.', exampleVN: 'Người quản lý có khả năng thúc đẩy nhóm.' },
  { id: 'm2', word: 'abroad', meaning: 'ở nước ngoài', example: 'We are expanding our business abroad.', exampleVN: 'Chúng tôi đang mở rộng kinh doanh ra nước ngoài.' },
  { id: 'm3', word: 'accept', meaning: 'chấp nhận, chấp thuận', example: 'Please accept our apologies for the delay.', exampleVN: 'Vui lòng chấp nhận lời xin lỗi của chúng tôi vì sự chậm trễ.' },
  { id: 'm4', word: 'accessible', meaning: 'khả năng tiếp cận được', example: 'The office is easily accessible by public transport.', exampleVN: 'Văn phòng có thể dễ dàng tiếp cận bằng phương tiện công cộng.' },
  { id: 'm5', word: 'accident', meaning: 'tai nạn, sự tình cờ', example: 'Safety measures are in place to prevent accidents.', exampleVN: 'Các biện pháp an toàn đã được áp dụng để ngăn ngừa tai nạn.' },
  { id: 'm6', word: 'accommodation', meaning: 'chỗ ở, nơi ở', example: 'The company provides accommodation for its employees.', exampleVN: 'Công ty cung cấp chỗ ở cho nhân viên.' },
  { id: 'm7', word: 'accomplish', meaning: 'hoàn thành, thực hiện', example: 'We can accomplish our goals if we work together.', exampleVN: 'Chúng ta có thể hoàn thành mục tiêu nếu làm việc cùng nhau.' },
  { id: 'm8', word: 'according', meaning: 'theo như, dựa vào', example: 'According to the report, sales are up.', exampleVN: 'Theo báo cáo, doanh số bán hàng đang tăng.' },
  { id: 'm9', word: 'accordingly', meaning: 'theo đó, vì vậy', example: 'Plan accordingly to avoid any issues.', exampleVN: 'Lên kế hoạch phù hợp để tránh mọi vấn đề.' },
  { id: 'm10', word: 'accounting', meaning: 'sự tính toán, thanh toán', example: 'The accounting department handles all invoices.', exampleVN: 'Bộ phận kế toán xử lý tất cả các hóa đơn.' },
  { id: 'm11', word: 'act', meaning: 'hành động; thực hiện', example: 'We must act quickly to resolve the problem.', exampleVN: 'Chúng ta phải hành động nhanh chóng để giải quyết vấn đề.' },
  { id: 'm12', word: 'actually', meaning: 'thực sự, trên thực tế', example: 'What did he actually say at the meeting?', exampleVN: 'Anh ấy thực sự đã nói gì tại cuộc họp?' },
  { id: 'm13', word: 'adapter', meaning: 'thiết bị chuyển đổi', example: 'You will need a travel adapter for the UK.', exampleVN: 'Bạn sẽ cần một bộ chuyển đổi khi đi du lịch ở Anh.' },
  { id: 'm14', word: 'administration', meaning: 'sự quản lý, quản trị', example: 'The new administration will start next month.', exampleVN: 'Chính quyền mới sẽ bắt đầu vào tháng tới.' },
  { id: 'm15', word: 'admire', meaning: 'ngưỡng mộ, thán phục', example: 'I admire her dedication to the project.', exampleVN: 'Tôi ngưỡng mộ sự tận tâm của cô ấy cho dự án.' },
  { id: 'm16', word: 'admittance', meaning: 'sự thu nạp, đón nhận', example: 'Admittance is restricted to authorized personnel.', exampleVN: 'Việc vào cửa bị hạn chế đối với nhân viên có thẩm quyền.' },
  { id: 'm17', word: 'adopt', meaning: 'nhận nuôi, áp dụng', example: 'The company decided to adopt a new strategy.', exampleVN: 'Công ty đã quyết định áp dụng một chiến lược mới.' },
  { id: 'm18', word: 'advanced', meaning: 'tiến bộ, cấp tiến', example: 'This software uses advanced algorithms.', exampleVN: 'Phần mềm này sử dụng các thuật toán tiên tiến.' },
  { id: 'm19', word: 'advantageous', meaning: 'có lợi, thuận lợi', example: 'The merger will be advantageous for both firms.', exampleVN: 'Việc sáp nhập sẽ có lợi cho cả hai công ty.' },
  { id: 'm20', word: 'advertisement', meaning: 'bản tin quảng cáo', example: 'We placed an advertisement in the newspaper.', exampleVN: 'Chúng tôi đã đăng một mẩu quảng cáo trên báo.' },
  { id: 'm21', word: 'advise', meaning: 'đưa ra lời khuyên', example: 'I advise you to check the contract carefully.', exampleVN: 'Tôi khuyên bạn nên kiểm tra hợp đồng cẩn thận.' },
  { id: 'm22', word: 'affect', meaning: 'ảnh hưởng, tác động', example: 'The changing weather will affect our crops.', exampleVN: 'Thời tiết thay đổi sẽ ảnh hưởng đến mùa màng của chúng ta.' },
  { id: 'm23', word: 'afford', meaning: 'có khả năng, đủ điều kiện', example: 'We cannot afford to lose any more customers.', exampleVN: 'Chúng ta không thể để mất thêm khách hàng nào nữa.' },
  { id: 'm24', word: 'affordable', meaning: 'có khả năng chi trả', example: 'The company provides affordable housing.', exampleVN: 'Công ty cung cấp nhà ở giá rẻ.' },
  { id: 'm25', word: 'agency', meaning: 'đại lý, bên môi giới', example: 'Contact the travel agency for more details.', exampleVN: 'Liên hệ với đại lý du lịch để biết thêm chi tiết.' },
  { id: 'm26', word: 'agenda', meaning: 'chương trình nghị sự', example: 'What is on the agenda for today?', exampleVN: 'Chương trình nghị sự hôm nay có gì?' },
  { id: 'm27', word: 'agreeable', meaning: 'dễ chịu; thích hợp', example: 'Find an agreeable solution for all.', exampleVN: 'Tìm một giải pháp dễ chịu cho tất cả mọi người.' },
  { id: 'm28', word: 'agricultural', meaning: 'thuộc nông nghiệp', example: 'New agricultural techniques can improve yield.', exampleVN: 'Kỹ thuật nông nghiệp mới có thể cải thiện năng suất.' },
  { id: 'm29', word: 'aid', meaning: 'sự giúp đỡ; cứu trợ', example: 'The government sent foreign aid to the region.', exampleVN: 'Chính phủ đã gửi viện trợ nước ngoài cho khu vực.' },
  { id: 'm30', word: 'aim', meaning: 'mục tiêu; nhắm đến', example: 'Our primary aim is to improve customer service.', exampleVN: 'Mục tiêu chính của chúng tôi là cải thiện dịch vụ khách hàng.' },
  { id: 'm31', word: 'airline', meaning: 'công ty hàng không', example: 'The airline offers direct flights to London.', exampleVN: 'Hãng hàng không cung cấp các chuyến bay thẳng đến London.' },
  { id: 'm32', word: 'aisle', meaning: 'lối đi giữa các dãy ghế', example: 'Would you like a window or an aisle seat?', exampleVN: 'Bạn muốn ngồi ở cửa sổ hay lối đi?' },
  { id: 'm33', word: 'alarm', meaning: 'sự báo động', example: 'The fire alarm went off at midnight.', exampleVN: 'Chuông báo cháy vang lên lúc nửa đêm.' },
  { id: 'm34', word: 'allow', meaning: 'cho phép', example: 'Smoking is not allowed in this building.', exampleVN: 'Hút thuốc không được phép trong tòa nhà này.' },
  { id: 'm35', word: 'alternative', meaning: 'xen kẽ, luân phiên; sự lựa chọn khác', example: 'We have no alternative but to cancel the event.', exampleVN: 'Chúng tôi không còn lựa chọn nào khác ngoài việc hủy bỏ sự kiện.' },
  { id: 'm36', word: 'ambitious', meaning: 'tham vọng', example: 'He is an ambitious young lawyer.', exampleVN: 'Anh ấy là một luật sư trẻ đầy tham vọng.' },
  { id: 'm37', word: 'amend', meaning: 'sửa chữa, cải tạo', example: 'They voted to amend the constitution.', exampleVN: 'Họ đã bỏ phiếu sửa đổi hiến pháp.' },
  { id: 'm38', word: 'amount', meaning: 'số lượng; cộng dồn', example: 'The total amount due is $50.', exampleVN: 'Tổng số tiền phải trả là $50.' },
  { id: 'm39', word: 'amusing', meaning: 'vui, có tính hài hước', example: 'I found her stories very amusing.', exampleVN: 'Tôi thấy những câu chuyện của cô ấy rất vui nhộn.' },
  { id: 'm40', word: 'analysis', meaning: 'sự phân tích', example: 'The analysis of the data took weeks.', exampleVN: 'Việc phân tích dữ liệu mất hàng tuần.' },
  { id: 'm41', word: 'analyze', meaning: 'phân tích', example: 'Analyze the results.', exampleVN: 'Phân tích kết quả.' },
  { id: 'm42', word: 'annual', meaning: 'hằng năm', example: 'The annual report is published in March.', exampleVN: 'Báo cáo hàng năm được công bố vào tháng Ba.' },
  { id: 'm43', word: 'anxious', meaning: 'bồn chồn, lo lắng', example: 'Investors are anxious about the stock market.', exampleVN: 'Các nhà đầu tư đang lo lắng về thị trường chứng khoán.' },
  { id: 'm44', word: 'apologize', meaning: 'xin lỗi', example: 'He apologized for being late.', exampleVN: 'Anh ấy đã xin lỗi vì đến muộn.' },
  { id: 'm45', word: 'appetizer', meaning: 'món khai vị', example: 'We ordered some appetizers for the party.', exampleVN: 'Chúng tôi đã đặt một số món khai vị cho bữa tiệc.' },
  { id: 'm46', word: 'appliance', meaning: 'thiết bị, dụng cụ', example: 'Modern kitchens have many appliances.', exampleVN: 'Nhà bếp hiện đại có nhiều thiết bị.' },
  { id: 'm47', word: 'applicant', meaning: 'người ứng tuyển', example: 'There were over 100 applicants for the job.', exampleVN: 'Có hơn 100 người ứng tuyển cho công việc này.' },
  { id: 'm48', word: 'application', meaning: 'ứng dụng, sự áp dụng', example: 'Submit your application by Friday.', exampleVN: 'Nộp đơn đăng ký của bạn trước thứ Sáu.' },
  { id: 'm49', word: 'apply', meaning: 'áp dụng, ứng tuyển', example: 'You should apply for the scholarship.', exampleVN: 'Bạn nên nộp đơn xin học bổng.' },
  { id: 'm50', word: 'appointment', meaning: 'sự bổ nhiệm, cuộc hẹn', example: 'I have an appointment with the dentist.', exampleVN: 'Tôi có một cuộc hẹn với nha sĩ.' },
  { id: 'm51', word: 'appreciable', meaning: 'đáng kể', example: 'There has been an appreciable increase in sales.', exampleVN: 'Đã có một sự gia tăng đáng kể trong doanh số bán hàng.' },
  { id: 'm52', word: 'appreciate', meaning: 'đánh giá cao, cảm kích', example: 'I appreciate your help.', exampleVN: 'Tôi đánh giá cao sự giúp đỡ của bạn.' },
  { id: 'm53', word: 'appreciation', meaning: 'sự đánh giá cao', example: 'Please accept this gift as a token of our appreciation.', exampleVN: 'Vui lòng chấp nhận món quà này như một biểu hiện của sự đánh giá cao của chúng tôi.' },
  { id: 'm54', word: 'appreciative', meaning: 'đánh giá cao, ghi nhận', example: 'The manager was appreciative of her hard work.', exampleVN: 'Người quản lý đánh giá cao sự chăm chỉ của cô ấy.' },
  { id: 'm55', word: 'apprentice', meaning: 'người học việc', example: 'He started as an apprentice mechanic.', exampleVN: 'Anh ấy bắt đầu như một thợ sửa xe tập sự.' },
  { id: 'm56', word: 'approximate', meaning: 'xấp xỉ, gần đúng', example: 'The approximate cost is $200.', exampleVN: 'Chi phí xấp xỉ là $200.' },
  { id: 'm57', word: 'arbitrate', meaning: 'phân xử, làm trọng tài', example: 'An independent body will arbitrate the dispute.', exampleVN: 'Một cơ quan độc lập sẽ phân xử tranh chấp.' },
  { id: 'm58', word: 'area', meaning: 'khu vực, lĩnh vực', example: 'The smoking area is outside.', exampleVN: 'Khu vực hút thuốc ở phía ngoài.' },
  { id: 'm59', word: 'argue', meaning: 'tranh cãi, tranh luận', example: 'They argued about the budget.', exampleVN: 'Họ đã tranh cãi về ngân sách.' },
  { id: 'm60', word: 'argument', meaning: 'cuộc tranh luận', example: 'They had a heated argument.', exampleVN: 'Họ đã có một cuộc tranh luận sôi nổi.' },
  { id: 'm61', word: 'arrangement', meaning: 'sự sắp đặt', example: 'Travel arrangements have been made.', exampleVN: 'Các sắp xếp chuyến đi đã được thực hiện.' },
  { id: 'm62', word: 'assignment', meaning: 'sự phân việc, bài tập', example: 'Complete the assignment by tomorrow.', exampleVN: 'Hoàn thành bài tập trước ngày mai.' },
  { id: 'm63', word: 'assistance', meaning: 'sự giúp đỡ, hỗ trợ', example: 'Do you need any assistance?', exampleVN: 'Bạn có cần sự giúp đỡ nào không?' },
  { id: 'm64', word: 'assume', meaning: 'cho rằng, làm ra vẻ', example: 'I assume that you are coming.', exampleVN: 'Tôi giả định rằng bạn đang đến.' },
  { id: 'm65', word: 'attachment', meaning: 'sự gắn thêm; phần kèm thêm', example: 'Please see the attachment for details.', exampleVN: 'Vui lòng xem tệp đính kèm để biết thêm chi tiết.' },
  { id: 'm66', word: 'attendance', meaning: 'sự tham gia, có mặt', example: 'Attendance at the meeting is mandatory.', exampleVN: 'Việc tham gia cuộc họp là bắt buộc.' },
  { id: 'm67', word: 'audience', meaning: 'khán thính giả', example: 'The audience cheered after the performance.', exampleVN: 'Khán giả đã reo hò sau buổi biểu diễn.' },
  { id: 'm68', word: 'authority', meaning: 'quyền thế, nhà chức trách', example: 'He has the authority to sign the cheque.', exampleVN: 'Anh ấy có thẩm quyền ký tờ séc.' },
  { id: 'm69', word: 'authorize', meaning: 'ủy quyền, cấp quyền', example: 'I authorize you to act on my behalf.', exampleVN: 'Tôi ủy quyền cho bạn hành động thay mặt tôi.' },
  { id: 'm70', word: 'availability', meaning: 'tính sẵn có', example: 'Check the availability of the room.', exampleVN: 'Kiểm tra xem phòng có trống không.' },
  { id: 'm71', word: 'available', meaning: 'có sẵn để dùng', example: 'Is there a table available for two?', exampleVN: 'Có bàn nào trống cho hai người không?' },
  { id: 'm72', word: 'avoid', meaning: 'tránh xa, ngăn ngừa', example: 'Try to avoid traveling during rush hour.', exampleVN: 'Cố gắng tránh đi lại trong giờ cao điểm.' },
  { id: 'm73', word: 'avid', meaning: 'khao khát, thèm khát', example: 'He is an avid reader of crime novels.', exampleVN: 'Anh ấy là một người ham đọc tiểu thuyết tội phạm.' },
  { id: 'm74', word: 'awareness', meaning: 'sự nhận thức, ý thức', example: 'Raise public awareness of the issue.', exampleVN: 'Nâng cao nhận thức cộng đồng về vấn đề này.' },
  { id: 'm75', word: 'awkward', meaning: 'ngại ngùng, khó xử', example: 'There was an awkward silence in the room.', exampleVN: 'Có một sự im lặng khó xử trong phòng.' },
  { id: 'm76', word: 'background', meaning: 'phông nền, gia cảnh', example: 'Tell me about your educational background.', exampleVN: 'Hãy cho tôi biết về nền tảng giáo dục của bạn.' },
  { id: 'm77', word: 'backpack', meaning: 'ba lô đeo sau lưng', example: 'He carried his books in a backpack.', exampleVN: 'Anh ấy để sách trong ba lô.' },
  { id: 'm78', word: 'baggage claim', meaning: 'chỗ nhận hành lý', example: 'Wait for your suitcase at the baggage claim.', exampleVN: 'Chờ vali của bạn ở khu vực nhận hành lý.' },
  { id: 'm79', word: 'bar code', meaning: 'mã vạch', example: 'The scanner reads the bar code on the product.', exampleVN: 'Máy quét đọc mã vạch trên sản phẩm.' },
  { id: 'm80', word: 'beautiful', meaning: 'xinh đẹp, tốt đẹp', example: 'The view from the top is beautiful.', exampleVN: 'Khung cảnh từ trên cao thật tuyệt đẹp.' },
  { id: 'm81', word: 'behave', meaning: 'hành xử, cư xử', example: 'The children behaved very well.', exampleVN: 'Lũ trẻ đã cư xử rất tốt.' },
  { id: 'm82', word: 'belongings', meaning: 'tài sản, đồ dùng cá nhân', example: 'Do not leave your belongings unattended.', exampleVN: 'Đừng để đồ dùng cá nhân mà không có người trông coi.' },
  { id: 'm83', word: 'beneficial', meaning: 'có ích, có lợi', example: 'Regular exercise is beneficial to health.', exampleVN: 'Tập thể dục thường xuyên có lợi cho sức khỏe.' },
  { id: 'm84', word: 'beverage', meaning: 'đồ uống, đồ giải khát', example: 'Hot beverages are served in the lounge.', exampleVN: 'Đồ uống nóng được phục vụ trong phòng chờ.' },
  { id: 'm85', word: 'bill', meaning: 'hóa đơn', example: 'Could we have the bill, please?', exampleVN: 'Cho chúng tôi xin hóa đơn được không?' },
  { id: 'm86', word: 'binder', meaning: 'bìa ôm, bìa rời', example: 'Keep the files in a three-ring binder.', exampleVN: 'Giữ các tệp tin trong một bìa hồ sơ ba chấu.' },
  { id: 'm87', word: 'blanket', meaning: 'chăn, mền', example: 'He wrapped himself in a warm blanket.', exampleVN: 'Anh ấy tự quấn mình trong một chiếc chăn ấm.' },
  { id: 'm88', word: 'boardroom', meaning: 'phòng họp ban giám đốc', example: 'The meeting was held in the boardroom.', exampleVN: 'Cuộc họp được tổ chức trong phòng họp ban giám đốc.' },
  { id: 'm89', word: 'boast', meaning: 'sự khoe khoang; khoác lác', example: 'The hotel boasts a fine view of the sea.', exampleVN: 'Khách sạn tự hào có tầm nhìn đẹp ra biển.' },
  { id: 'm90', word: 'boost', meaning: 'đẩy mạnh, kích thích', example: 'The new campaign helped to boost sales.', exampleVN: 'Chiến dịch mới đã giúp thúc đẩy doanh số bán hàng.' },
  { id: 'm91', word: 'bored', meaning: 'buồn chán, tẻ nhạt', example: 'I was bored with my job.', exampleVN: 'Tôi đã chán ngấy với công việc của mình.' },
  { id: 'm92', word: 'bother', meaning: 'điều gây khó chịu; làm phiền', example: 'I am sorry to bother you.', exampleVN: 'Tôi xin lỗi đã làm phiền bạn.' },
  { id: 'm93', word: 'bottom line', meaning: 'điểm mấu chốt, cốt yếu', example: 'The bottom line is that we need more money.', exampleVN: 'Điểm mấu chốt là chúng ta cần thêm tiền.' },
  { id: 'm94', word: 'briefcase', meaning: 'cặp tài liệu', example: 'He opened his briefcase and took out some papers.', exampleVN: 'Anh ấy mở cặp tài liệu và lấy ra một số giấy tờ.' },
  { id: 'm95', word: 'briefing', meaning: 'sự chỉ dẫn, hướng dẫn', example: 'We were given a short briefing before the tour.', exampleVN: 'Chúng tôi đã được hướng dẫn ngắn gọn trước chuyến tham quan.' },
  { id: 'm96', word: 'broadcast', meaning: 'truyền bá, phát thanh', example: 'The news is broadcast every hour.', exampleVN: 'Tin tức được phát sóng mỗi giờ.' },
  { id: 'm97', word: 'broaden', meaning: 'mở rộng, nới rộng', example: 'Travel broadens the mind.', exampleVN: 'Du lịch giúp mở rộng tầm hiểu biết.' },
  { id: 'm98', word: 'browser', meaning: 'trình duyệt', example: 'Please update your web browser.', exampleVN: 'Vui lòng cập nhật trình duyệt web của bạn.' },
  { id: 'm99', word: 'brush', meaning: 'lược, bàn chải; chải, quét', example: 'She brushed her hair before going out.', exampleVN: 'Cô ấy chải tóc trước khi đi ra ngoài.' },
  { id: 'm100', word: 'bulletin', meaning: 'bảng thông báo, tập san', example: 'Check the bulletin board for updates.', exampleVN: 'Kiểm tra bảng thông báo để cập nhật.' },
  { id: 'm101', word: 'cabin crew', meaning: 'đội bay, tiếp viên hàng không', example: 'The cabin crew will serve drinks shortly.', exampleVN: 'Đội ngũ tiếp viên sẽ phục vụ đồ uống ngay sau đây.' },
  { id: 'm102', word: 'cafeteria', meaning: 'quán ăn tự phục vụ', example: 'Let\'s meet in the cafeteria for lunch.', exampleVN: 'Hãy gặp nhau ở nhà ăn để ăn trưa.' },
  { id: 'm103', word: 'calculate', meaning: 'tính toán, suy tính', example: 'Calculate the total cost.', exampleVN: 'Tính toán tổng chi phí.' },
  { id: 'm104', word: 'calculation', meaning: 'sự tính toán', example: 'The calculation of the tax is complex.', exampleVN: 'Việc tính toán thuế rất phức tạp.' },
  { id: 'm105', word: 'calculator', meaning: 'máy tính bỏ túi', example: 'You can use a calculator during the exam.', exampleVN: 'Bạn có thể sử dụng máy tính trong kỳ thi.' },
  { id: 'm106', word: 'campaign', meaning: 'chiến dịch, cuộc vận động', example: 'The marketing campaign was a big success.', exampleVN: 'Chiến dịch tiếp thị là một thành công lớn.' },
  { id: 'm107', word: 'cancellation', meaning: 'sự xóa bỏ, bãi bỏ', example: 'There is a fee for late cancellation.', exampleVN: 'Có một khoản phí cho việc hủy bỏ muộn.' },
  { id: 'm108', word: 'candidacy', meaning: 'sự ứng cử', example: 'He announced his candidacy for mayor.', exampleVN: 'Ông tuyên bố ứng cử chức thị trưởng.' },
  { id: 'm109', word: 'careless', meaning: 'bất cẩn, cẩu thả', example: 'It was careless of him to leave the door open.', exampleVN: 'Thật là bất cẩn khi anh ấy để cửa mở.' },
  { id: 'm110', word: 'cash', meaning: 'tiền mặt', example: 'Are you paying by credit card or cash?', exampleVN: 'Bạn thanh toán bằng thẻ tín dụng hay tiền mặt?' },
  { id: 'm111', word: 'cashier', meaning: 'nhân viên thu ngân', example: 'The cashier gave me the wrong change.', exampleVN: 'Nhân viên thu ngân đã thối nhầm tiền cho tôi.' },
  { id: 'm112', word: 'cause', meaning: 'nguyên nhân, lý do; gây ra', example: 'The cause of the fire is unknown.', exampleVN: 'Chưa rõ nguyên nhân vụ hỏa hoạn.' },
  { id: 'm113', word: 'cautious', meaning: 'thận trọng, cẩn thận', example: 'The company is cautious about new investments.', exampleVN: 'Công ty đang thận trọng đối với các khoản đầu tư mới.' },
  { id: 'm114', word: 'celebrate', meaning: 'kỉ niệm, tán dương', example: 'We are planning to celebrate his retirement.', exampleVN: 'Chúng tôi dự định tổ chức kỷ niệm ngày ông ấy nghỉ hưu.' },
  { id: 'm115', word: 'celebration', meaning: 'lễ kỉ niệm', example: 'The victory was a cause for celebration.', exampleVN: 'Chiến thắng là một lý do để ăn mừng.' },
  { id: 'm116', word: 'certificate', meaning: 'giấy chứng nhận', example: 'I received a certificate for completing the course.', exampleVN: 'Tôi đã nhận được một chứng chỉ cho việc hoàn thành khóa học.' },
  { id: 'm117', word: 'certification', meaning: 'sự cấp giấy chứng nhận', example: 'Professional certification can help your career.', exampleVN: 'Chứng chỉ chuyên môn có thể giúp ích cho sự nghiệp của bạn.' },
  { id: 'm118', word: 'chain store', meaning: 'cửa hàng theo chuỗi', example: 'The city has many international chain stores.', exampleVN: 'Thành phố có nhiều cửa hàng theo chuỗi quốc tế.' },
  { id: 'm119', word: 'chairperson', meaning: 'chủ tịch', example: 'The chairperson called the meeting to order.', exampleVN: 'Chủ tịch đã yêu cầu cuộc họp bắt đầu.' },
  { id: 'm120', word: 'characteristic', meaning: 'đặc điểm, tính cách', example: 'One characteristic of this breed is its speed.', exampleVN: 'Một đặc điểm của giống vật này là tốc độ.' },
  { id: 'm121', word: 'characterize', meaning: 'biểu thị đặc điểm, mô tả', example: 'The region is characterized by high mountains.', exampleVN: 'Khu vực này được đặc trưng bởi những dãy núi cao.' },
  { id: 'm122', word: 'charity', meaning: 'lòng từ bi, tổ chức từ thiện', example: 'He gave all his money to charity.', exampleVN: 'Ông ấy đã quyên góp toàn bộ số tiền của mình cho tổ chức từ thiện.' },
  { id: 'm123', word: 'cheap', meaning: 'rẻ tiền, xấu', example: 'Fuel is relatively cheap in this country.', exampleVN: 'Nhiên liệu tương đối rẻ ở đất nước này.' },
  { id: 'm124', word: 'check in', meaning: 'đăng ký phòng, vé máy bay...', example: 'Check in at the desk on the first floor.', exampleVN: 'Đăng ký tại quầy ở tầng một.' },
  { id: 'm125', word: 'check out', meaning: 'trả phòng, thanh toán', example: 'You must check out by 11 AM.', exampleVN: 'Bạn phải trả phòng trước 11 giờ sáng.' },
  { id: 'm126', word: 'chef', meaning: 'đầu bếp', example: 'The chef prepared a delicious meal.', exampleVN: 'Đầu bếp đã chuẩn bị một bữa ăn ngon.' },
  { id: 'm127', word: 'circumstances', meaning: 'hoàn cảnh, tình huống', example: 'Under no circumstances should you open the door.', exampleVN: 'Trong bất kỳ hoàn cảnh nào bạn cũng không được mở cửa.' },
  { id: 'm128', word: 'claim', meaning: 'quyền đòi sở hữu; đòi hỏi, nhận', example: 'He made a claim for damages.', exampleVN: 'Ông ấy đã yêu cầu đòi bồi thường thiệt hại.' },
  { id: 'm129', word: 'claimant', meaning: 'người thỉnh cầu, người đòi hỏi', example: 'The claimant was awarded $1000 in damages.', exampleVN: 'Người khiếu nại đã được bồi thường thiệt hại 1000 đô la.' },
  { id: 'm130', word: 'classify', meaning: 'phân loại', example: 'The books are classified by subject.', exampleVN: 'Sách được phân loại theo chủ đề.' },
  { id: 'm131', word: 'client', meaning: 'khách hàng', example: 'Focus on our new client.', exampleVN: 'Tập trung vào khách hàng mới.' },
  { id: 'm132', word: 'climate', meaning: 'khí hậu, thời tiết', example: 'The political climate is very tense.', exampleVN: 'Không khí chính trị đang rất căng thẳng.' },
  { id: 'm133', word: 'commence', meaning: 'bắt đầu, mở đầu, khởi đầu', example: 'The meeting will commence at 10 AM.', exampleVN: 'Cuộc họp sẽ bắt đầu lúc 10 giờ sáng.' },
  { id: 'm134', word: 'commission', meaning: 'hội đồng, ủy ban, tiền hoa hồng', example: 'He earns a 10% commission on every sale.', exampleVN: 'Anh ấy nhận được 10% tiền hoa hồng trên mỗi lần bán hàng.' },
  { id: 'm135', word: 'committee', meaning: 'ủy ban', example: 'The committee met to discuss the proposal.', exampleVN: 'Ủy ban đã họp để thảo luận về đề xuất.' },
  { id: 'm136', word: 'commonly', meaning: 'thông thường, bình thường', example: 'This drug is commonly used for headaches.', exampleVN: 'Loại thuốc này thường được dùng để chữa đau đầu.' },
  { id: 'm137', word: 'commuter', meaning: 'người đi lại (bằng vé tháng...)', example: 'The train was full of commuters.', exampleVN: 'Chuyến tàu đầy những người đi làm.' },
  { id: 'm138', word: 'company', meaning: 'công ty, bạn bè, bằng hữu', example: 'She works for a software company.', exampleVN: 'Cô ấy làm việc cho một công ty phần mềm.' },
  { id: 'm139', word: 'compare', meaning: 'so sánh, đối chiếu', example: 'Compare the two products before buying.', exampleVN: 'So sánh hai sản phẩm trước khi mua.' },
  { id: 'm140', word: 'compatible', meaning: 'tương thích, phù hợp', example: 'The software is compatible with Windows.', exampleVN: 'Phần mềm này tương thích với hệ điều hành Windows.' },
  { id: 'm141', word: 'compensation', meaning: 'sự đền bù, vật bồi thường', example: 'She received compensation for her injury.', exampleVN: 'Cô ấy nhận được bồi thường cho thương tích của mình.' },
  { id: 'm142', word: 'competent', meaning: 'có khả năng, đủ trình độ', example: 'She is a very competent secretary.', exampleVN: 'Cô ấy là một thư ký rất có năng lực.' },
  { id: 'm143', word: 'competitor', meaning: 'người cạnh tranh, đối thủ', example: 'They are our main competitors in the market.', exampleVN: 'Họ là những đối thủ cạnh tranh chính của chúng tôi trên thị trường.' },
  { id: 'm144', word: 'complaint', meaning: 'lời than phiền, lời phàn nàn', example: 'I wish to make a formal complaint.', exampleVN: 'Tôi muốn đưa ra một khiếu nại chính thức.' },
  { id: 'm145', word: 'complex', meaning: 'khu phức hợp; phức tạp', example: 'The issue is very complex.', exampleVN: 'Vấn đề này rất phức tạp.' },
  { id: 'm146', word: 'complexity', meaning: 'sự phức tạp', example: 'I was surprised by the complexity of the task.', exampleVN: 'Tôi ngạc nhiên trước sự phức tạp của nhiệm vụ.' },
  { id: 'm147', word: 'compliment', meaning: 'lời khen, sự ca tụng', example: 'Thank you for the compliment.', exampleVN: 'Cảm ơn vì lời khen.' },
  { id: 'm148', word: 'complimentary', meaning: 'ngợi khen, đánh giá cao; miễn phí', example: 'The hotel provides complimentary breakfast.', exampleVN: 'Khách sạn cung cấp bữa sáng miễn phí.' },
  { id: 'm149', word: 'comprehensive', meaning: 'toàn diện, thông minh', example: 'The study was very comprehensive.', exampleVN: 'Nghiên cứu rất toàn diện.' },
  { id: 'm150', word: 'compulsory', meaning: 'bắt buộc, ép buộc', example: 'Education is compulsory until the age of 16.', exampleVN: 'Giáo dục là bắt buộc cho đến 16 tuổi.' }
];

export const processChunkMochi = () => {
    return chunkMochi.map(w => {
        let pos = '(v)';
        const nouns = new Set(['ability', 'accident', 'accommodation', 'accounting', 'adapter', 'administration', 'admittance', 'advertisement', 'agency', 'agenda', 'aid', 'aim', 'airline', 'aisle', 'alarm', 'amount', 'analysis', 'appetizer', 'appliance', 'applicant', 'application', 'appointment', 'appreciation', 'apprentice', 'area', 'argument', 'arrangement', 'assignment', 'assistance', 'attachment', 'attendance', 'audience', 'authority', 'availability', 'awareness', 'background', 'backpack', 'baggage claim', 'bar code', 'belongings', 'beverage', 'bill', 'binder', 'blanket', 'boardroom', 'boast', 'boost', 'bother', 'bottom line', 'briefcase', 'briefing', 'broadcast', 'browser', 'brush', 'bulletin', 'cabin crew', 'cafeteria', 'calculation', 'calculator', 'campaign', 'cancellation', 'candidacy', 'cash', 'cashier', 'cause', 'celebration', 'certificate', 'certification', 'chain store', 'chairperson', 'characteristic', 'charity', 'chef', 'circumstances', 'claimant', 'client', 'climate', 'commission', 'committee', 'commuter', 'company', 'compensation', 'complaint', 'complexity', 'compliment']);
        const both_nv = new Set(['act', 'aid', 'aim', 'alarm', 'amount', 'appeal', 'appointment', 'area', 'arrangement', 'boast', 'boost', 'bother', 'broadcast', 'brush', 'cause', 'claim', 'check in', 'check out']);
        const adjs = new Set(['accessible', 'advanced', 'advantageous', 'affordable', 'agreeable', 'agricultural', 'alternative', 'ambitious', 'amusing', 'annual', 'anxious', 'appreciable', 'appreciative', 'approximate', 'available', 'avid', 'awkward', 'beautiful', 'beneficial', 'bored', 'careless', 'cautious', 'cheap', 'compatible', 'competent', 'complex', 'complimentary', 'comprehensive', 'compulsory']);
        const advs = new Set(['abroad', 'accordingly', 'actually', 'commonly']);
        const preps = new Set(['according']);

        if (nouns.has(w.word)) pos = '(n)';
        if (both_nv.has(w.word)) pos = '(n, v)';
        if (adjs.has(w.word)) pos = '(adj)';
        if (advs.has(w.word)) pos = '(adv)';
        if (preps.has(w.word)) pos = '(prep)';
        
        return { ...w, pos };
    });
};
