import { Word } from './types';

export const chunkHardExtra: Word[] = [
  { id: 'h1', word: 'circumvent', meaning: 'né tránh, đi vòng qua', example: 'They found a way to circumvent the security system.', exampleVN: 'Họ đã tìm ra cách để né tránh hệ thống an ninh.' },
  { id: 'h2', word: 'deputy', meaning: 'người được ủy thác, cấp phó', example: 'The deputy manager is in charge today.', exampleVN: 'Phó quản lý chịu trách nhiệm hôm nay.' },
  { id: 'h3', word: 'delectable', meaning: 'ngon lành, thú vị', example: 'The chef prepared a delectable meal.', exampleVN: 'Đầu bếp đã chuẩn bị một bữa ăn ngon lành.' },
  { id: 'h4', word: 'gracious', meaning: 'tử tế, hào hiệp, trang nhã', example: 'She was a gracious host.', exampleVN: 'Cô ấy là một chủ nhà tử tế.' },
  { id: 'h5', word: 'wilder', meaning: 'làm cho hoang dã, làm lúng túng (hiếm)', example: 'The path leads into the wilder parts of the forest.', exampleVN: 'Con đường dẫn vào những phần hoang dã hơn của khu rừng.' },
  { id: 'h6', word: 'adversary', meaning: 'đối thủ, kẻ thù', example: 'He was a formidable adversary in the debate.', exampleVN: 'Anh ấy là một đối thủ đáng gờm trong cuộc tranh luận.' },
  { id: 'h7', word: 'benevolent', meaning: 'nhân từ, hay làm phúc', example: 'A benevolent donor gave $1 million to the school.', exampleVN: 'Một nhà tài trợ nhân từ đã tặng 1 triệu đô la cho trường học.' },
  { id: 'h8', word: 'candor', meaning: 'sự thật thà, ngay thẳng', example: 'I appreciate your candor about the situation.', exampleVN: 'Tôi đánh giá cao sự ngay thẳng của bạn về tình hình này.' },
  { id: 'h9', word: 'diligent', meaning: 'siêng năng, cần cù', example: 'She is a diligent student who works hard.', exampleVN: 'Cô ấy là một học sinh siêng năng, làm việc chăm chỉ.' },
  { id: 'h10', word: 'eloquent', meaning: 'có tài hùng biện', example: 'The president gave an eloquent speech.', exampleVN: 'Tổng thống đã có một bài phát biểu hùng hồn.' },
  { id: 'h11', word: 'frugal', meaning: 'tiết kiệm, thanh đạm', example: 'He is frugal with his money.', exampleVN: 'Anh ấy rất tiết kiệm tiền bạc.' },
  { id: 'h12', word: 'gregarious', meaning: 'thích giao du, hiệp đàn', example: 'She is a gregarious person who loves parties.', exampleVN: 'Cô ấy là một người thích giao du, yêu thích các bữa tiệc.' },
  { id: 'h13', word: 'haughty', meaning: 'kiêu kỳ, ngạo mạn', example: 'The haughty waiter ignored us.', exampleVN: 'Người phục vụ kiêu ngạo đã phớt lờ chúng tôi.' },
  { id: 'h14', word: 'impeccable', meaning: 'hoàn hảo, không chê vào đâu được', example: 'Her English is impeccable.', exampleVN: 'Tiếng Anh của cô ấy thật hoàn hảo.' },
  { id: 'h15', word: 'jovial', meaning: 'vui vẻ, vui tính', example: 'He was in a jovial mood.', exampleVN: 'Anh ấy đang trong một tâm trạng vui vẻ.' },
  { id: 'h16', word: 'knack', meaning: 'sở trường, tài riêng', example: 'She has a knack for mathematics.', exampleVN: 'Cô ấy có năng khiếu về toán học.' },
  { id: 'h17', word: 'lucid', meaning: 'rõ ràng, dễ hiểu', example: 'The explanation was lucid and easy to follow.', exampleVN: 'Lời giải thích rất rõ ràng và dễ theo dõi.' },
  { id: 'h18', word: 'mitigate', meaning: 'giảm nhẹ, làm dịu bớt', example: 'We need to mitigate the effects of the crisis.', exampleVN: 'Chúng ta cần giảm nhẹ tác động của cuộc khủng hoảng.' },
  { id: 'h19', word: 'nefarious', meaning: 'hung ác, bất chính', example: 'The hackers had nefarious intentions.', exampleVN: 'Các hacker có những ý định bất chính.' },
  { id: 'h20', word: 'oblivious', meaning: 'không để ý đến, quên', example: 'She was oblivious to the danger.', exampleVN: 'Cô ấy không để ý đến nguy hiểm.' },
  { id: 'h21', word: 'pensive', meaning: 'trầm tư, suy nghĩ', example: 'He sat in a pensive silence.', exampleVN: 'Anh ngồi lặng lẽ trầm tư.' },
  { id: 'h22', word: 'quaint', meaning: 'cổ kính, lạ lùng', example: 'What a quaint little village!', exampleVN: 'Thật là một ngôi làng nhỏ cổ kính!' },
  { id: 'h23', word: 'resilient', meaning: 'kiên cường, đàn hồi', example: 'The economy is surprisingly resilient.', exampleVN: 'Nền kinh tế kiên cường một cách đáng ngạc nhiên.' },
  { id: 'h24', word: 'scrutinize', meaning: 'xem xét kỹ lưỡng', example: 'The lawyer scrutinized every detail of the contract.', exampleVN: 'Luật sư đã xem xét kỹ lưỡng từng chi tiết của bản hợp đồng.' },
  { id: 'h25', word: 'tenacious', meaning: 'kiên trì, ngoan cường', example: 'A tenacious negotiator never gives up.', exampleVN: 'Một người đàm phán ngoan cường không bao giờ bỏ cuộc.' },
  { id: 'h26', word: 'ubiquitous', meaning: 'ở khắp mọi nơi', example: 'Cell phones are ubiquitous these days.', exampleVN: 'Điện thoại di động có mặt ở khắp mọi nơi ngày nay.' },
  { id: 'h27', word: 'venerable', meaning: 'đáng kính, lâu đời', example: 'The venerable professor has retired.', exampleVN: 'Vị giáo sư đáng kính đã nghỉ hưu.' },
  { id: 'h28', word: 'wary', meaning: 'thận trọng, cảnh giác', example: 'Be wary of strangers.', exampleVN: 'Hãy cảnh giác với người lạ.' },
  { id: 'h29', word: 'zealous', meaning: 'nhiệt huyết, hăng hái', example: 'She is a zealous supporter of the cause.', exampleVN: 'Cô ấy là một người ủng hộ nhiệt huyết cho chính nghĩa.' },
  { id: 'h30', word: 'abundant', meaning: 'dồi dào, phong phú', example: 'There is abundant evidence of climate change.', exampleVN: 'Có bằng chứng dồi dào về sự biến đổi khí hậu.' },
  { id: 'h31', word: 'belligerent', meaning: 'hiếu chiến, hung hăng', example: 'A belligerent attitude will not help.', exampleVN: 'Một thái độ hiếu chiến sẽ không giúp ích được gì.' },
  { id: 'h32', word: 'complacent', meaning: 'tự mãn', example: 'We cannot afford to be complacent.', exampleVN: 'Chúng ta không thể cho phép mình tự mãn.' },
  { id: 'h33', word: 'dearth', meaning: 'sự khan hiếm', example: 'There is a dearth of skilled workers.', exampleVN: 'Có một sự khan hiếm công nhân lành nghề.' },
  { id: 'h34', word: 'eccentric', meaning: 'lập dị', example: 'The eccentric billionaire lives alone.', exampleVN: 'Vị tỷ phú lập dị sống một mình.' },
  { id: 'h35', word: 'fastidious', meaning: 'khó tính, kén chọn', example: 'He is fastidious about his appearance.', exampleVN: 'Anh ấy rất kén chọn về ngoại hình của mình.' },
  { id: 'h36', word: 'gratuitous', meaning: 'vô cớ, cho không', example: 'The film contained gratuitous violence.', exampleVN: 'Bộ phim chứa đựng bạo lực vô cớ.' },
  { id: 'h37', word: 'hyperbole', meaning: 'lời nói ngoa, cường điệu', example: 'He is prone to hyperbole.', exampleVN: 'Anh ta hay nói quá.' },
  { id: 'h38', word: 'immutable', meaning: 'không thay đổi', example: 'The laws of nature are immutable.', exampleVN: 'Các quy luật của tự nhiên là bất biến.' },
  { id: 'h39', word: 'juxtapose', meaning: 'để cạnh nhau để so sánh', example: 'The exhibition juxtaposes old and new art.', exampleVN: 'Triển lãm đặt nghệ thuật cũ và mới cạnh nhau.' },
  { id: 'h40', word: 'labyrinth', meaning: 'mê cung', example: 'The office was a labyrinth of corridors.', exampleVN: 'Văn phòng là một mê cung các hành lang.' },
  { id: 'h41', word: 'magnanimous', meaning: 'hào hiệp, cao thượng', example: 'He was magnanimous in victory.', exampleVN: 'Anh ấy đã hào hiệp khi chiến thắng.' },
  { id: 'h42', word: 'nostalgia', meaning: 'nỗi nhớ quê hương, hoài niệm', example: 'I feel nostalgia for my school days.', exampleVN: 'Tôi cảm thấy hoài niệm về những ngày đi học.' },
  { id: 'h43', word: 'ominous', meaning: 'điềm xấu, đáng ngại', example: 'There were ominous black clouds in the sky.', exampleVN: 'Có những đám mây đen đáng ngại trên bầu trời.' },
  { id: 'h44', word: 'pragmatic', meaning: 'thực dụng, thực tế', example: 'We need a pragmatic approach to the problem.', exampleVN: 'Chúng ta cần một cách tiếp cận thực tế cho vấn đề này.' },
  { id: 'h45', word: 'quintessential', meaning: 'tinh túy, mẫu mực', example: 'It was the quintessential English village.', exampleVN: 'Đó là một ngôi làng Anh mẫu mực.' },
  { id: 'h46', word: 'rhetoric', meaning: 'thuật hùng biện, lời nói suông', example: 'The empty rhetoric of politicians.', exampleVN: 'Những lời hùng biện trống rỗng của các chính trị gia.' },
  { id: 'h47', word: 'superfluous', meaning: 'thừa, vô ích', example: 'The extra detail was superfluous.', exampleVN: 'Chi tiết bổ sung là thừa.' },
  { id: 'h48', word: 'trepidation', meaning: 'sự lo lắng, run rẩy', example: 'I approached the meeting with trepidation.', exampleVN: 'Tôi đến cuộc họp với sự lo lắng.' },
  { id: 'h49', word: 'unilateral', meaning: 'đơn phương', example: 'A unilateral decision was made.', exampleVN: 'Một quyết định đơn phương đã được đưa ra.' },
  { id: 'h50', word: 'verbose', meaning: 'dài dòng, lắm lời', example: 'His report was overly verbose.', exampleVN: 'Báo cáo của ông ấy quá dài dòng.' },
  { id: 'h51', word: 'whimsical', meaning: 'kỳ dị, bất chợt', example: 'A whimsical sense of humor.', exampleVN: 'Một khiếu hài hước kỳ lạ.' },
  { id: 'h52', word: 'xenophobia', meaning: 'sự bài ngoại', example: 'The rise of xenophobia in the country.', exampleVN: 'Sự trỗi dậy của chứng bài ngoại trong nước.' },
  { id: 'h53', word: 'yield', meaning: 'sản lượng, lợi nhuận, đầu hàng', example: 'The investment gives a high yield.', exampleVN: 'Khoản đầu tư mang lại lợi nhuận cao.' },
  { id: 'h54', word: 'zenith', meaning: 'thiên đỉnh, cực điểm', example: 'The Roman Empire reached its zenith in the 2nd century.', exampleVN: 'Đế chế La Mã đạt đến đỉnh cao vào thế kỷ thứ 2.' },
  { id: 'h55', word: 'abdicate', meaning: 'từ ngôi, thoái vị', example: 'The king was forced to abdicate.', exampleVN: 'Nhà vua bị buộc phải thoái vị.' },
  { id: 'h56', word: 'blandishment', meaning: 'sự xu nịnh, dỗ dành', example: 'Despite her blandishments, he refused.', exampleVN: 'Bất chấp những lời dỗ dành của cô, anh vẫn từ chối.' },
  { id: 'h57', word: 'camaraderie', meaning: 'tình bạn, sự thân thiết', example: 'The camaraderie among the team members.', exampleVN: 'Sự thân thiết giữa các thành viên trong nhóm.' },
  { id: 'h58', word: 'deleterious', meaning: 'có hại, độc hại', example: 'Smoking has deleterious effects on health.', exampleVN: 'Hút thuốc có hại cho sức khỏe.' },
  { id: 'h59', word: 'ebullient', meaning: 'sôi nổi, hăng hái', example: 'He was ebullient about his new job.', exampleVN: 'Anh ấy rất hăng hái về công việc mới của mình.' },
  { id: 'h60', word: 'facetious', meaning: 'khôi hài, không nghiêm túc', example: 'Stop being facetious!', exampleVN: 'Đừng đùa cợt nữa!' },
  { id: 'h61', word: 'gourmet', meaning: 'người sành ăn', example: 'A gourmet meal at a top restaurant.', exampleVN: 'Một bữa ăn sành điệu tại một nhà hàng hàng đầu.' },
  { id: 'h62', word: 'harangue', meaning: 'bài diễn thuyết dài, chỉ trích', example: 'He harangued the crowd for hours.', exampleVN: 'Anh ta đã diễn thuyết chỉ trích đám đông trong nhiều giờ.' },
  { id: 'h63', word: 'idiosyncrasy', meaning: 'đặc tính riêng, phong cách riêng', example: 'One of his idiosyncrasies is that he always wears two different socks.', exampleVN: 'Một trong những đặc điểm riêng của anh ấy là luôn đi hai chiếc tất khác nhau.' },
  { id: 'h64', word: 'judicious', meaning: 'sáng suốt, đúng đắn', example: 'We should make a judicious choice.', exampleVN: 'Chúng ta nên đưa ra một lựa chọn sáng suốt.' },
  { id: 'h65', word: 'kindle', meaning: 'nhen nhóm, kích thích', example: 'The book kindled my interest in history.', exampleVN: 'Cuốn sách đã khơi dậy niềm yêu thích lịch sử của tôi.' },
  { id: 'h66', word: 'levity', meaning: 'sự khinh suất, coi thường', example: 'We need some levity in this serious meeting.', exampleVN: 'Chúng ta cần một chút vui vẻ trong cuộc họp nghiêm túc này.' },
  { id: 'h67', word: 'modicum', meaning: 'một chút, một tí', example: 'They showed a modicum of respect.', exampleVN: 'Họ đã thể hiện một chút sự tôn trọng.' },
  { id: 'h68', word: 'nuance', meaning: 'sắc thái', example: 'He missed the nuances of the speech.', exampleVN: 'Anh ấy đã bỏ lỡ các sắc thái của bài phát biểu.' },
  { id: 'h69', word: 'opulent', meaning: 'giàu có, sang trọng', example: 'The opulent lifestyle of the rich.', exampleVN: 'Lối sống sang trọng của những người giàu có.' },
  { id: 'h70', word: 'parsimonious', meaning: 'keo kiệt, bủn xỉn', example: 'A parsimonious employer.', exampleVN: 'Một chủ nhân keo kiệt.' },
  { id: 'h71', word: 'quandary', meaning: 'tình trạng khó khăn, lúng túng', example: 'I am in a quandary about what to do.', exampleVN: 'Tôi đang lúng túng không biết phải làm gì.' },
  { id: 'h72', word: 'rancor', meaning: 'sự ác cảm, hận thù', example: 'The debate was conducted without rancor.', exampleVN: 'Cuộc tranh luận được tiến hành mà không có ác cảm.' },
  { id: 'h73', word: 'sagacious', meaning: 'thông thái, mẫn tiệp', example: 'A sagacious old man.', exampleVN: 'Một cụ già thông thái.' },
  { id: 'h74', word: 'tome', meaning: 'quyển sách dày', example: 'He produced a massive tome on the history of art.', exampleVN: 'Ông đã viết một cuốn sách dày về lịch sử nghệ thuật.' },
  { id: 'h75', word: 'unctuous', meaning: 'khéo léo (quá mức), trơn tru', example: 'An unctuous salesman.', exampleVN: 'Một người bán hàng khéo léo quá mức.' },
  { id: 'h76', word: 'vacillate', meaning: 'dao động, lưỡng lự', example: 'He vacillated between the two options.', exampleVN: 'Anh ấy lưỡng lự giữa hai lựa chọn.' },
  { id: 'h77', word: 'wistful', meaning: 'nuối tiếc, bâng khuâng', example: 'A wistful smile.', exampleVN: 'Một nụ cười bâng khuâng.' },
  { id: 'h78', word: 'yield', meaning: 'sản lượng, nhường bộ', example: 'The trees yield fruit every year.', exampleVN: 'Cây cối cho trái mỗi năm.' },
  { id: 'h79', word: 'zealot', meaning: 'người cuồng tín', example: 'A religious zealot.', exampleVN: 'Một người cuồng tín tôn giáo.' },
  { id: 'h80', word: 'aberration', meaning: 'sự khác thường, lầm lạc', example: 'The bad result was a temporary aberration.', exampleVN: 'Kết quả tồi tệ chỉ là một sự khác thường tạm thời.' },
  { id: 'h81', word: 'bellicose', meaning: 'hiếu chiến', example: 'A bellicose tone.', exampleVN: 'Một giọng điệu hiếu chiến.' },
  { id: 'h82', word: 'cajole', meaning: 'tán tỉnh, dỗ dành', example: 'He cajoled her into going to the party.', exampleVN: 'Anh ấy đã dỗ dành cô ấy đi dự tiệc.' },
  { id: 'h83', word: 'deride', meaning: 'nhạo báng, chế giễu', example: 'They derided his efforts.', exampleVN: 'Họ đã chế giễu những nỗ lực của anh.' },
  { id: 'h84', word: 'egregious', meaning: 'quá xá, cực kỳ tệ', example: 'An egregious error.', exampleVN: 'Một lỗi lầm cực kỳ tệ hại.' },
  { id: 'h85', word: 'fallacious', meaning: 'sai lầm, giả tạo', example: 'A fallacious argument.', exampleVN: 'Một lập luận sai lầm.' },
  { id: 'h86', word: 'garrulous', meaning: 'nói nhiều, ba hoa', example: 'A garrulous old neighbor.', exampleVN: 'Một người hàng xóm già nói nhiều.' },
  { id: 'h87', word: 'hackneyed', meaning: 'nhàm chán, sáo rỗng', example: 'Hackneyed phrases.', exampleVN: 'Những cụm từ sáo rỗng.' },
  { id: 'h88', word: 'iconoclast', meaning: 'người đả phá những quan niệm cũ', example: 'He was an iconoclast in the world of fashion.', exampleVN: 'Anh ấy là một người phá vỡ những quy tắc cũ trong thế giới thời trang.' },
  { id: 'h89', word: 'jubilant', meaning: 'vui sướng, hân hoan', example: 'The crowd was jubilant after the win.', exampleVN: 'Đám đông hân hoan sau chiến thắng.' },
  { id: 'h90', word: 'laconic', meaning: 'vắn tắt, gọn gàng', example: 'A laconic reply.', exampleVN: 'Một câu trả lời vắn tắt.' },
  { id: 'h91', word: 'maverick', meaning: 'người độc lập, không theo quy tắc', example: 'A political maverick.', exampleVN: 'Một người độc lập về chính trị.' },
  { id: 'h92', word: 'neophyte', meaning: 'người mới bắt đầu', example: 'A neophyte in the kitchen.', exampleVN: 'Một người mới bắt đầu trong bếp.' },
  { id: 'h93', word: 'obdurate', meaning: 'bướng bỉnh, cứng đầu', example: 'An obdurate refusal.', exampleVN: 'Một sự từ chối bướng bỉnh.' },
  { id: 'h94', word: 'pallid', meaning: 'nhợt nhạt, xanh xao', example: 'A pallid complexion.', exampleVN: 'Một làn da nhợt nhạt.' },
  { id: 'h95', word: 'quiescent', meaning: 'im lìm, yên lặng', example: 'The volcano is quiescent.', exampleVN: 'Ngọn núi lửa đang im lìm.' },
  { id: 'h96', word: 'recalcitrant', meaning: 'ngoan cố, hay cãi lại', example: 'A recalcitrant child.', exampleVN: 'Một đứa trẻ ngoan cố.' },
  { id: 'h97', word: 'salient', meaning: 'nổi bật, quan trọng nhất', example: 'The salient points of the argument.', exampleVN: 'Những điểm nổi bật của lập luận.' },
  { id: 'h251', word: 'tacit', meaning: 'ngầm, không nói ra', example: 'A tacit agreement.', exampleVN: 'Một sự đồng ý ngầm.' },
  { id: 'h252', word: 'taciturn', meaning: 'ít nói, lầm lì', example: 'A taciturn man.', exampleVN: 'Một người đàn ông ít nói.' },
  { id: 'h253', word: 'tantamount', meaning: 'tương đương với', example: 'His silence was tantamount to an admission of guilt.', exampleVN: 'Sự im lặng của anh ta tương đương với việc thừa nhận tội lỗi.' },
  { id: 'h254', word: 'temerity', meaning: 'sự táo bạo, liều lĩnh', example: 'He had the temerity to challenge the boss.', exampleVN: 'Anh ta đã có gan thách thức sếp.' },
  { id: 'h255', word: 'tenuous', meaning: 'mong manh, hời hợt', example: 'A tenuous connection.', exampleVN: 'Một sự kết nối mong manh.' },
  { id: 'h256', word: 'timorous', meaning: 'nhút nhát, sợ sệt', example: 'A timorous child.', exampleVN: 'Một đứa trẻ nhút nhát.' },
  { id: 'h257', word: 'torpid', meaning: 'uể oải, lờ đờ', example: 'A torpid economy.', exampleVN: 'Một nền kinh tế trì trệ.' },
  { id: 'h258', word: 'tractable', meaning: 'dễ bảo, dễ kiểm soát', example: 'A tractable horse.', exampleVN: 'Một con ngựa dễ bảo.' },
  { id: 'h259', word: 'transient', meaning: 'tạm thời, ngắn ngủi', example: 'Transient beauty.', exampleVN: 'Vẻ đẹp ngắn ngủi.' },
  { id: 'h260', word: 'travesty', meaning: 'sự nhại lại, sự xuyên tạc', example: 'A travesty of justice.', exampleVN: 'Một sự xuyên tạc công lý.' },
  { id: 'h261', word: 'trenchant', meaning: 'sắc bén, đanh thép', example: 'A trenchant analysis.', exampleVN: 'Một phân tích sắc bén.' },
  { id: 'h262', word: 'truculent', meaning: 'hung hăng, tàn bạo', example: 'A truculent attitude.', exampleVN: 'Một thái độ hung hăng.' },
  { id: 'h263', word: 'turpitude', meaning: 'sự đồi bại, xấu xa', example: 'Moral turpitude.', exampleVN: 'Sự đồi bại về đạo đức.' },
  { id: 'h264', word: 'ubiquitous', meaning: 'khắp nơi, phổ biến', example: 'The ubiquitous influence of social media.', exampleVN: 'Sự ảnh hưởng lan rộng của mạng xã hội.' },
  { id: 'h265', word: 'umbrage', meaning: 'sự xúc phạm, bóng râm', example: 'To take umbrage at something.', exampleVN: 'Cảm thấy bị xúc phạm bởi điều gì đó.' },
  { id: 'h266', word: 'unctuous', meaning: 'khéo léo quá mức, trơn tru', example: 'An unctuous smile.', exampleVN: 'Một nụ cười khéo léo quá mức.' },
  { id: 'h267', word: 'undulate', meaning: 'lượn sóng, nhấp nhô', example: 'Undulating hills.', exampleVN: 'Những ngọn đồi nhấp nhô.' },
  { id: 'h268', word: 'upbraid', meaning: 'quở trách, khiển trách', example: 'The manager upbraided the staff.', exampleVN: 'Quản lý đã khiển trách nhân viên.' },
  { id: 'h269', word: 'usurp', meaning: 'chiếm đoạt', example: 'To usurp power.', exampleVN: 'Chiếm đoạt quyền lực.' },
  { id: 'h270', word: 'vacuous', meaning: 'trống rỗng, đần độn', example: 'A vacuous expression.', exampleVN: 'Một biểu cảm trống rỗng.' },
  { id: 'h271', word: 'variegated', meaning: 'đa dạng, nhiều màu', example: 'Variegated leaves.', exampleVN: 'Những chiếc lá nhiều màu.' },
  { id: 'h272', word: 'venerate', meaning: 'tôn kính, thờ phụng', example: 'To venerate the dead.', exampleVN: 'Tôn kính người đã khuất.' },
  { id: 'h273', word: 'veracity', meaning: 'sự thật thà, tính xác thực', example: 'We questioned the veracity of her story.', exampleVN: 'Chúng tôi nghi ngờ tính xác thực của câu chuyện của cô ấy.' },
  { id: 'h274', word: 'vex', meaning: 'làm phiền, gây bực mình', example: 'The problem continued to vex them.', exampleVN: 'Vấn đề tiếp tục làm phiền họ.' },
  { id: 'h275', word: 'vicarious', meaning: 'thay thế, gián tiếp', example: 'A vicarious thrill.', exampleVN: 'Một cảm giác hồi hộp gián tiếp.' },
  { id: 'h276', word: 'vicissitude', meaning: 'sự thăng trầm', example: 'The vicissitudes of life.', exampleVN: 'Những thăng trầm của cuộc đời.' },
  { id: 'h277', word: 'vilify', meaning: 'nói xấu, phỉ báng', example: 'To vilify someone in the press.', exampleVN: 'Nói xấu ai đó trên báo chí.' },
  { id: 'h278', word: 'viscous', meaning: 'dẻo, dính', example: 'A viscous liquid.', exampleVN: 'Một chất lỏng dính.' },
  { id: 'h279', word: 'vitriolic', meaning: 'châm chọc, cay độc', example: 'A vitriolic attack.', exampleVN: 'Một cuộc tấn công cay độc.' },
  { id: 'h280', word: 'vituperate', meaning: 'chửi rủa, lăng mạ', example: 'To vituperate against the government.', exampleVN: 'Chửi rủa chính phủ.' },
  { id: 'h281', word: 'vociferous', meaning: 'om sòm, mạnh mẽ', example: 'A vociferous protest.', exampleVN: 'Một cuộc biểu tình mạnh mẽ.' },
  { id: 'h282', word: 'wanton', meaning: 'bừa bãi, vô cớ', example: 'Wanton destruction.', exampleVN: 'Sự phá hủy bừa bãi.' },
  { id: 'h283', word: 'winsome', meaning: 'hấp dẫn, quyến rũ', example: 'A winsome smile.', exampleVN: 'Một nụ cười quyến rũ.' },
  { id: 'h284', word: 'wistful', meaning: 'nuối tiếc, bâng khuâng', example: 'A wistful glance.', exampleVN: 'Một cái nhìn nuối tiếc.' },
  { id: 'h285', word: 'zealot', meaning: 'người cuồng tín', example: 'A religious zealot.', exampleVN: 'Một người cuồng tín tôn giáo.' },
  { id: 'h286', word: 'zenith', meaning: 'cực điểm', example: 'At the zenith of his power.', exampleVN: 'Tại đỉnh cao quyền lực của mình.' },
  { id: 'h287', word: 'abject', meaning: 'khốn khổ, hèn hạ', example: 'Abject poverty.', exampleVN: 'Sự nghèo đói cùng cực.' },
  { id: 'h288', word: 'abjure', meaning: 'từ bỏ (đặc biệt là niềm tin)', example: 'To abjure one\'s religion.', exampleVN: 'Từ bỏ tôn giáo của mình.' },
  { id: 'h289', word: 'abnegation', meaning: 'sự từ bỏ, sự hy sinh', example: 'Self-abnegation.', exampleVN: 'Sự hy sinh quên mình.' },
  { id: 'h290', word: 'abrogate', meaning: 'hủy bỏ, bài trừ (luật)', example: 'To abrogate a treaty.', exampleVN: 'Hủy bỏ một hiệp ước.' },
  { id: 'h291', word: 'abscond', meaning: 'lẩn trốn, bỏ trốn', example: 'He absconded with the money.', exampleVN: 'Hắn đã bỏ trốn cùng với số tiền.' },
  { id: 'h292', word: 'abstruse', meaning: 'thâm thúy, khó hiểu', example: 'Abstruse theories.', exampleVN: 'Những lý thuyết thâm thúy.' },
  { id: 'h293', word: 'accede', meaning: 'đồng ý, nhậm chức', example: 'To accede to a request.', exampleVN: 'Đồng ý với một yêu cầu.' },
  { id: 'h294', word: 'accost', meaning: 'đến gần và nói chuyện (hung hăng)', example: 'He was accosted by a beggar.', exampleVN: 'Anh ta bị một người ăn xin tiếp cận.' },
  { id: 'h295', word: 'accretion', meaning: 'sự bồi đắp, sự tăng thêm', example: 'The accretion of wealth.', exampleVN: 'Sự tích lũy của cải.' },
  { id: 'h296', word: 'acumen', meaning: 'sự nhạy bén, thính nhạy', example: 'Business acumen.', exampleVN: 'Sự nhạy bén trong kinh doanh.' },
  { id: 'h297', word: 'adamant', meaning: 'kiên quyết, cứng rắn', example: 'She was adamant that she would not go.', exampleVN: 'Cô ấy kiên quyết không đi.' },
  { id: 'h298', word: 'admonish', meaning: 'quở trách, nhắc nhở', example: 'To admonish someone for being late.', exampleVN: 'Nhắc nhở ai đó vì đến muộn.' },
  { id: 'h299', word: 'adumbrate', meaning: 'phác thảo, báo hiệu', example: 'To adumbrate a new policy.', exampleVN: 'Phác thảo một chính sách mới.' },
  { id: 'h300', word: 'adverse', meaning: 'bất lợi, có hại', example: 'Adverse weather conditions.', exampleVN: 'Điều kiện thời tiết bất lợi.' },
  { id: 'h301', word: 'advocate', meaning: 'biện hộ, ủng hộ', example: 'To advocate for human rights.', exampleVN: 'Ủng hộ quyền con người.' },
  { id: 'h302', word: 'affable', meaning: 'lịch sự, niềm nở', example: 'An affable host.', exampleVN: 'Một chủ nhà niềm nở.' },
  { id: 'h303', word: 'affinity', meaning: 'sự tương đồng, sự cuốn hút', example: 'A natural affinity between the two sisters.', exampleVN: 'Sự tương đồng tự nhiên giữa hai chị em.' },
  { id: 'h304', word: 'affluent', meaning: 'giàu có, thịnh vượng', example: 'An affluent neighborhood.', exampleVN: 'Một khu xóm giàu có.' },
  { id: 'h305', word: 'aggrandize', meaning: 'phóng đại, nâng cao (quyền lực)', example: 'To aggrandize one\'s own position.', exampleVN: 'Nâng cao vị thế của chính mình.' },
  { id: 'h306', word: 'aggregate', meaning: 'tập hợp, tổng số', example: 'The aggregate score.', exampleVN: 'Tổng điểm.' },
  { id: 'h307', word: 'alacrity', meaning: 'sự sốt sắng', example: 'Accept with alacrity.', exampleVN: 'Chấp nhận với sự sốt sắng.' },
  { id: 'h308', word: 'alias', meaning: 'bí danh', example: 'Known by the alias of...', exampleVN: 'Được biết đến với bí danh là...' },
  { id: 'h309', word: 'alleviate', meaning: 'làm nhẹ bớt, giảm bớt', example: 'To alleviate pain.', exampleVN: 'Làm giảm cơn đau.' },
  { id: 'h310', word: 'allocate', meaning: 'phân bổ', example: 'To allocate resources.', exampleVN: 'Phân bổ nguồn lực.' },
  { id: 'h311', word: 'altercation', meaning: 'cuộc cãi vã, đấu khẩu', example: 'A noisy altercation.', exampleVN: 'Một cuộc cãi vã ồn ào.' },
  { id: 'h312', word: 'altruistic', meaning: 'vị tha', example: 'Altruistic behavior.', exampleVN: 'Hành vi vị tha.' },
  { id: 'h313', word: 'amalgamate', meaning: 'hợp nhất, trộn lẫn', example: 'To amalgamate two companies.', exampleVN: 'Hợp nhất hai công ty.' },
  { id: 'h314', word: 'ambivalent', meaning: 'mâu thuẫn (về cảm xúc)', example: 'Feeling ambivalent about the decision.', exampleVN: 'Cảm thấy mâu thuẫn về quyết định này.' },
  { id: 'h315', word: 'ameliorate', meaning: 'làm tốt hơn, cải thiện', example: 'To ameliorate living conditions.', exampleVN: 'Cải thiện điều kiện sống.' },
  { id: 'h316', word: 'amenable', meaning: 'dễ bảo, tuân theo', example: 'An amenable person.', exampleVN: 'Một người dễ bảo.' },
  { id: 'h317', word: 'amenity', meaning: 'tiện nghi, sự dễ chịu', example: 'Modern amenities.', exampleVN: 'Các tiện nghi hiện đại.' },
  { id: 'h318', word: 'amiable', meaning: 'tử tế, thân thiện', example: 'An amiable young woman.', exampleVN: 'Một phụ nữ trẻ tử tế.' },
  { id: 'h319', word: 'amicable', meaning: 'hòa giải, thân mật', example: 'An amicable settlement.', exampleVN: 'Một sự hòa giải thân mật.' },
  { id: 'h320', word: 'amorous', meaning: 'say đắm, thuộc về tình yêu', example: 'Amorous feelings.', exampleVN: 'Những cảm xúc yêu đương.' },
  { id: 'h321', word: 'amorphous', meaning: 'không có hình dạng nhất định', example: 'An amorphous mass of clouds.', exampleVN: 'Một khối mây không có hình dạng nhất định.' },
  { id: 'h322', word: 'anachronism', meaning: 'sự sai niên đại', example: 'A historical anachronism.', exampleVN: 'Một sự sai lệch lịch sử.' },
  { id: 'h323', word: 'analgesic', meaning: 'thuốc giảm đau', example: 'Take an analgesic.', exampleVN: 'Hãy uống thuốc giảm đau.' },
  { id: 'h324', word: 'analogous', meaning: 'tương tự', example: 'An analogous situation.', exampleVN: 'Một tình huống tương tự.' },
  { id: 'h325', word: 'anarchy', meaning: 'tình trạng vô chính phủ', example: 'A state of anarchy.', exampleVN: 'Tình trạng vô chính phủ.' },
  { id: 'h326', word: 'anathema', meaning: 'lời nguyền rủa, điều đáng ghét', example: 'His ideas were anathema to me.', exampleVN: 'Ý tưởng của anh ta là điều đáng ghét đối với tôi.' },
  { id: 'h327', word: 'anecdote', meaning: 'giai thoại', example: 'Tell an amusing anecdote.', exampleVN: 'Kể một giai thoại thú vị.' },
  { id: 'h328', word: 'anesthesia', meaning: 'sự gây mê', example: 'Under general anesthesia.', exampleVN: 'Dưới sự gây mê toàn thân.' },
  { id: 'h329', word: 'anguish', meaning: 'sự đau khổ tột cùng', example: 'Mental anguish.', exampleVN: 'Sự đau khổ về tinh thần.' },
  { id: 'h330', word: 'animated', meaning: 'sống động, hoạt bát', example: 'An animated discussion.', exampleVN: 'Một cuộc thảo luận sôi nổi.' },
  { id: 'h331', word: 'annex', meaning: 'thôn tính, phụ lục', example: 'To annex a territory.', exampleVN: 'Thôn tính một lãnh thổ.' },
  { id: 'h332', word: 'annul', meaning: 'bãi bỏ, hủy bỏ (pháp lý)', example: 'To annul a marriage.', exampleVN: 'Hủy bỏ một cuộc hôn nhân.' },
  { id: 'h333', word: 'anomaly', meaning: 'sự dị thường', example: 'A statistical anomaly.', exampleVN: 'Một sự dị thường về thống kê.' },
  { id: 'h334', word: 'anonymous', meaning: 'vô danh', example: 'An anonymous tip.', exampleVN: 'Một tin báo vô danh.' },
  { id: 'h335', word: 'antagonism', meaning: 'sự thù địch', example: 'Open antagonism.', exampleVN: 'Sự thù địch công khai.' },
  { id: 'h336', word: 'antecedent', meaning: 'tiền đề, tổ tiên', example: 'Historical antecedents.', exampleVN: 'Tiền đề lịch sử.' },
  { id: 'h337', word: 'antediluvian', meaning: 'cổ xưa, lỗi thời', example: 'Antediluvian ideas.', exampleVN: 'Những ý tưởng cổ xưa.' },
  { id: 'h338', word: 'anthology', meaning: 'tuyển tập', example: 'An anthology of poems.', exampleVN: 'Một tuyển tập thơ.' },
  { id: 'h339', word: 'antipathy', meaning: 'ác cảm', example: 'A deep antipathy towards him.', exampleVN: 'Một ác cảm sâu sắc đối với anh ta.' },
  { id: 'h340', word: 'antiquated', meaning: 'cổ xưa, cũ kỹ', example: 'Antiquated machinery.', exampleVN: 'Máy móc cũ kỹ.' },
  { id: 'h341', word: 'antiseptic', meaning: 'chất khử trùng', example: 'Use an antiseptic.', exampleVN: 'Hãy dùng chất khử trùng.' },
  { id: 'h342', word: 'antithesis', meaning: 'sự tương phản, phép đối chọi', example: 'The exact antithesis of what he said.', exampleVN: 'Sự đối lập hoàn toàn với những gì anh ấy nói.' },
  { id: 'h343', word: 'apathy', meaning: 'sự thờ ơ', example: 'Voter apathy.', exampleVN: 'Sự thờ ơ của cử tri.' },
  { id: 'h344', word: 'apocryphal', meaning: 'không xác thực, giả mạo', example: 'An apocryphal story.', exampleVN: 'Một câu chuyện không xác thực.' },
  { id: 'h345', word: 'appease', meaning: 'xoa dịu, nhân nhượng', example: 'To appease the protesters.', exampleVN: 'Xoa dịu những người biểu tình.' },
  { id: 'h346', word: 'appraise', meaning: 'đánh giá, định giá', example: 'To appraise the situation.', exampleVN: 'Đánh giá tình hình.' },
  { id: 'h347', word: 'apprehend', meaning: 'bắt giữ, hiểu', example: 'To apprehend a criminal.', exampleVN: 'Bắt giữ một tên tội phạm.' },
  { id: 'h348', word: 'approbation', meaning: 'sự tán thành, phê chuẩn', example: 'A murmur of approbation.', exampleVN: 'Một lời thì thầm tán thành.' },
  { id: 'h349', word: 'appropriate', meaning: 'chiếm đoạt, thích hợp', example: 'To appropriate funds.', exampleVN: 'Chiếm dụng quỹ.' },
  { id: 'h350', word: 'arbitrary', meaning: 'độc đoán, tùy hứng', example: 'An arbitrary decision.', exampleVN: 'Một quyết định độc đoán.' },
  { id: 'h351', word: 'arboreal', meaning: 'thuộc về cây', example: 'Arboreal animals.', exampleVN: 'Động vật sống trên cây.' },
  { id: 'h352', word: 'arcane', meaning: 'bí mật, huyền bí', example: 'Arcane rituals.', exampleVN: 'Những nghi lễ huyền bí.' },
  { id: 'h353', word: 'archaic', meaning: 'cổ xưa', example: 'Archaic laws.', exampleVN: 'Luật lệ cổ xưa.' },
  { id: 'h354', word: 'archetypal', meaning: 'nguyên mẫu', example: 'An archetypal example.', exampleVN: 'Một ví dụ điển hình.' },
  { id: 'h355', word: 'ardent', meaning: 'hăng hái, nồng nhiệt', example: 'An ardent supporter.', exampleVN: 'Một người ủng hộ nhiệt thành.' },
  { id: 'h356', word: 'arid', meaning: 'khô cằn', example: 'An arid desert.', exampleVN: 'Một sa mạc khô cằn.' },
  { id: 'h357', word: 'arrogate', meaning: 'chiếm quyền, chiếm đoạt', example: 'To arrogate power to oneself.', exampleVN: 'Chiếm đoạt quyền lực cho bản thân.' },
  { id: 'h358', word: 'ascertain', meaning: 'xác định, tìm hiểu chắc chắn', example: 'To ascertain the facts.', exampleVN: 'Xác định các sự thật.' },
  { id: 'h359', word: 'ascetic', meaning: 'khổ hạnh', example: 'An ascetic lifestyle.', exampleVN: 'Một lối sống khổ hạnh.' },
  { id: 'h360', word: 'ascribe', meaning: 'đổ tại, gán cho', example: 'To ascribe failure to bad luck.', exampleVN: 'Đổ lỗi thất bại cho sự xui xẻo.' },
  { id: 'h361', word: 'aspersion', meaning: 'sự nói xấu, sự vu khống', example: 'To cast aspersions on someone\'s character.', exampleVN: 'Nói xấu nhân cách của ai đó.' },
  { id: 'h362', word: 'aspire', meaning: 'thiết tha, khao khát', example: 'To aspire to greatness.', exampleVN: 'Khao khát sự vĩ đại.' },
  { id: 'h363', word: 'assail', meaning: 'tấn công dồn dập', example: 'To assail with questions.', exampleVN: 'Tấn công dồn dập bằng các câu hỏi.' },
  { id: 'h364', word: 'assess', meaning: 'đánh giá', example: 'To assess the value.', exampleVN: 'Đánh giá giá trị.' },
  { id: 'h365', word: 'assiduous', meaning: 'siêng năng', example: 'Assiduous study.', exampleVN: 'Nghiên cứu siêng năng.' },
  { id: 'h366', word: 'assuage', meaning: 'làm dịu bớt', example: 'To assuage fears.', exampleVN: 'Làm dịu bớt nỗi sợ hãi.' },
  { id: 'h367', word: 'astute', meaning: 'tinh khôn, sắc sảo', example: 'An astute businessman.', exampleVN: 'Một doanh nhân sắc sảo.' },
  { id: 'h368', word: 'atrophy', meaning: 'sự hao mòn, sự teo đi', example: 'Muscular atrophy.', exampleVN: 'Sự teo cơ.' },
  { id: 'h369', word: 'attenuate', meaning: 'làm gầy đi, làm yếu đi', example: 'To attenuate the effects of a drug.', exampleVN: 'Làm giảm tác dụng của thuốc.' },
  { id: 'h370', word: 'attest', meaning: 'chứng nhận, chứng thực', example: 'To attest to someone\'s character.', exampleVN: 'Chứng thực cho nhân cách của ai đó.' },
  { id: 'h371', word: 'audacious', meaning: 'táo bạo, trơ tráo', example: 'An audacious plan.', exampleVN: 'Một kế hoạch táo bạo.' },
  { id: 'h372', word: 'augment', meaning: 'làm tăng lên', example: 'To augment one\'s income.', exampleVN: 'Làm tăng thu nhập.' },
  { id: 'h373', word: 'augur', meaning: 'báo hiệu, tiên đoán', example: 'This augurs well for the future.', exampleVN: 'Điều này báo hiệu tốt cho tương lai.' },
  { id: 'h374', word: 'austere', meaning: 'khắc khổ, mộc mạc', example: 'An austere life.', exampleVN: 'Một cuộc sống khắc khổ.' },
  { id: 'h375', word: 'avarice', meaning: 'sự tham lam', example: 'Driven by avarice.', exampleVN: 'Bị thúc đẩy bởi sự tham lam.' },
  { id: 'h376', word: 'avenge', meaning: 'trả thù', example: 'To avenge a death.', exampleVN: 'Trả thù cho một cái chết.' },
  { id: 'h377', word: 'aversion', meaning: 'sự ghét, sự ác cảm', example: 'A strong aversion to exercise.', exampleVN: 'Một sự ghét cay ghét đắng việc tập thể dục.' },
  { id: 'h378', word: 'balk', meaning: 'chùn bước, ngăn cản', example: 'To balk at the price.', exampleVN: 'Chùn bước trước mức giá.' },
  { id: 'h379', word: 'banal', meaning: 'tầm thường', example: 'Banal conversation.', exampleVN: 'Cuộc trò chuyện tầm thường.' },
  { id: 'h380', word: 'bane', meaning: 'tai ương, tai họa', example: 'The bane of my existence.', exampleVN: 'Tai họa của đời tôi.' },
  { id: 'h381', word: 'bashful', meaning: 'rụt rè, bảnh bao', example: 'A bashful smile.', exampleVN: 'Một nụ cười rụt rè.' },
  { id: 'h382', word: 'beguile', meaning: 'lừa gạt, làm mê hoặc', example: 'To beguile someone with promises.', exampleVN: 'Lừa gạt ai đó bằng những lời hứa.' },
  { id: 'h383', word: 'behemoth', meaning: 'quái vật khổng lồ, vật khổng lồ', example: 'A corporate behemoth.', exampleVN: 'Một tập đoàn khổng lồ.' },
  { id: 'h384', word: 'belie', meaning: 'làm cho lầm lẫn, trái với', example: 'His smile belied his anger.', exampleVN: 'Nụ cười của anh ấy che giấu sự tức giận.' },
  { id: 'h385', word: 'belligerent', meaning: 'hiếu chiến', example: 'A belligerent country.', exampleVN: 'Một đất nước hiếu chiến.' },
  { id: 'h386', word: 'benevolent', meaning: 'nhân từ', example: 'A benevolent smile.', exampleVN: 'Một nụ cười nhân từ.' },
  { id: 'h387', word: 'benign', meaning: 'lành tính, tử tế', example: 'A benign tumor.', exampleVN: 'Một khối u lành tính.' },
  { id: 'h388', word: 'bequeath', meaning: 'để lại, truyền lại', example: 'To bequeath property.', exampleVN: 'Để lại tài sản.' },
  { id: 'h389', word: 'berate', meaning: 'mắng mỏ, chỉ trích', example: 'To berate a child.', exampleVN: 'Mắng mỏ một đứa trẻ.' },
  { id: 'h390', word: 'bereft', meaning: 'mất hết, thiếu thốn', example: 'Bereft of hope.', exampleVN: 'Thiếu thốn hy vọng.' },
  { id: 'h391', word: 'beseech', meaning: 'van xin, cầu khẩn', example: 'To beseech someone for help.', exampleVN: 'Van xin ai đó giúp đỡ.' },
  { id: 'h392', word: 'bilk', meaning: 'lừa đảo, quỵt nợ', example: 'To bilk a customer.', exampleVN: 'Lừa đảo một khách hàng.' },
  { id: 'h393', word: 'blandishment', meaning: 'sự dỗ dành, xu nịnh', example: 'Yield to blandishments.', exampleVN: 'Nhượng bộ trước những lời nịnh hót.' },
  { id: 'h394', word: 'blemish', meaning: 'vết nhơ, nhược điểm', example: 'A blemish on his record.', exampleVN: 'Một vết nhơ trong hồ sơ của anh ta.' },
  { id: 'h395', word: 'blight', meaning: 'ảnh hưởng xấu, tàn lụi', example: 'An urban blight.', exampleVN: 'Sự tàn lụi của đô thị.' },
  { id: 'h396', word: 'boisterous', meaning: 'náo nhiệt, huyên náo', example: 'A boisterous party.', exampleVN: 'Một bữa tiệc náo nhiệt.' },
  { id: 'h397', word: 'bombastic', meaning: 'khoa trương, đao to búa lớn', example: 'A bombastic speech.', exampleVN: 'Một bài phát biểu đao to búa lớn.' },
  { id: 'h398', word: 'boon', meaning: 'lợi ích, ân huệ', example: 'A boon to the local economy.', exampleVN: 'Một lợi ích cho nền kinh tế địa phương.' },
  { id: 'h399', word: 'bourgeois', meaning: 'thuộc tầng lớp trung lưu', example: 'Bourgeois values.', exampleVN: 'Các giá trị của tầng lớp trung lưu.' },
  { id: 'h400', word: 'brazen', meaning: 'trơ tráo, vô liêm sỉ', example: 'A brazen lie.', exampleVN: 'Một lời nói dối trơ tráo.' },
  { id: 'h401', word: 'brusque', meaning: 'lỗ mãng, cộc lốc', example: 'A brusque manner.', exampleVN: 'Một phong thái cộc lốc.' },
  { id: 'h402', word: 'buffet', meaning: 'đấm, tát, vùi dập', example: 'Buffeted by the wind.', exampleVN: 'Bị gió vùi dập.' },
  { id: 'h403', word: 'burnish', meaning: 'đánh bóng', example: 'To burnish one\'s reputation.', exampleVN: 'Đánh bóng danh tiếng của mình.' },
  { id: 'h404', word: 'buttress', meaning: 'ủng hộ, củng cố', example: 'To buttress an argument.', exampleVN: 'Củng cố một lập luận.' },
  { id: 'h405', word: 'cacophony', meaning: 'âm thanh chói tai', example: 'A cacophony of car horns.', exampleVN: 'Những tiếng còi xe chói tai.' },
  { id: 'h406', word: 'cadence', meaning: 'nhịp điệu', example: 'The cadence of her voice.', exampleVN: 'Nhịp điệu giọng nói của cô ấy.' },
  { id: 'h407', word: 'cajole', meaning: 'tán tỉnh, dỗ dành', example: 'Cajole into doing something.', exampleVN: 'Dỗ dành để làm việc gì đó.' },
  { id: 'h408', word: 'calamity', meaning: 'tai ương, thiên tai', example: 'A natural calamity.', exampleVN: 'Một thiên tai.' },
  { id: 'h409', word: 'callous', meaning: 'nhẫn tâm, chai sạn', example: 'A callous disregard for life.', exampleVN: 'Sự coi thường mạng sống nhẫn tâm.' },
  { id: 'h410', word: 'calumny', meaning: 'sự vu khống, phỉ báng', example: 'To utter calumnies against someone.', exampleVN: 'Thốt ra những lời phỉ báng ai đó.' },
  { id: 'h411', word: 'camaraderie', meaning: 'tình đồng nghiệp, tình bạn', example: 'Team camaraderie.', exampleVN: 'Tình đồng đội.' },
  { id: 'h412', word: 'candor', meaning: 'sự thật thà', example: 'I value your candor.', exampleVN: 'Tôi đánh giá cao sự thật thà của bạn.' },
  { id: 'h413', word: 'canny', meaning: 'cẩn thận, tinh khôn', example: 'A canny investor.', exampleVN: 'Một nhà đầu tư tinh khôn.' },
  { id: 'h414', word: 'canvas', meaning: 'vải bạt, thảo luận', example: 'A canvas tent.', exampleVN: 'Một chiếc lều bạt.' },
  { id: 'h415', word: 'capitulate', meaning: 'đầu hàng', example: 'To capitulate to the enemy.', exampleVN: 'Đầu hàng kẻ thù.' },
  { id: 'h416', word: 'capricious', meaning: 'thất thường', example: 'Capricious behavior.', exampleVN: 'Hành vi thất thường.' },
  { id: 'h417', word: 'captivate', meaning: 'làm say đắm', example: 'Captivated by the show.', exampleVN: 'Bị say đắm bởi buổi biểu diễn.' },
  { id: 'h418', word: 'carouse', meaning: 'uống rượu say sưa', example: 'To carouse all night.', exampleVN: 'Nhậu nhẹt suốt đêm.' },
  { id: 'h419', word: 'carp', meaning: 'bới lông tìm vết, phàn nàn', example: 'To carp about small things.', exampleVN: 'Phàn nàn về những điều nhỏ nhặt.' },
  { id: 'h420', word: 'catalog', meaning: 'danh mục', example: 'A catalog of products.', exampleVN: 'Một danh mục sản phẩm.' },
  { id: 'h421', word: 'catalyst', meaning: 'chất xúc tác', example: 'A catalyst for change.', exampleVN: 'Chất xúc tác cho sự thay đổi.' },
  { id: 'h422', word: 'caucus', meaning: 'cuộc họp kín (chính trị)', example: 'To hold a caucus.', exampleVN: 'Tổ chức một cuộc họp kín.' },
  { id: 'h423', word: 'caustic', meaning: 'châm chọc, ăn mòn', example: 'A caustic remark.', exampleVN: 'Một lời nhận xét châm chọc.' },
  { id: 'h424', word: 'cavort', meaning: 'nhảy nhót, vui đùa', example: 'Children cavorting in the park.', exampleVN: 'Trẻ em nô đùa trong công viên.' },
  { id: 'h425', word: 'celestial', meaning: 'thuộc về bầu trời, thiên đình', example: 'Celestial bodies.', exampleVN: 'Các thiên thể.' },
  { id: 'h426', word: 'censure', meaning: 'chỉ trích, khiển trách', example: 'To face public censure.', exampleVN: 'Đối mặt với sự chỉ trích của công chúng.' },
  { id: 'h427', word: 'cerebral', meaning: 'thuộc về não, trí tuệ', example: 'A cerebral movie.', exampleVN: 'Một bộ phim mang tính trí tuệ.' },
  { id: 'h428', word: 'chaos', meaning: 'sự hỗn loạn', example: 'Absolute chaos.', exampleVN: 'Sự hỗn loạn tuyệt đối.' },
  { id: 'h429', word: 'chastise', meaning: 'trừng phạt, khiển trách', example: 'To chastise a child.', exampleVN: 'Khiển trách một đứa trẻ.' },
  { id: 'h430', word: 'cherish', meaning: 'yêu thương, trân trọng', example: 'To cherish memories.', exampleVN: 'Trân trọng những kỷ niệm.' },
  { id: 'h431', word: 'chide', meaning: 'quở trách, mắng mỏ', example: 'To chide someone for being late.', exampleVN: 'Mắng mỏ ai đó vì đến muộn.' },
  { id: 'h432', word: 'choreography', meaning: 'biên đạo múa', example: 'Excellent choreography.', exampleVN: 'Biên đạo múa xuất sắc.' },
  { id: 'h433', word: 'chronicle', meaning: 'ghi chép sự kiện', example: 'To chronicle the war.', exampleVN: 'Ghi chép lại cuộc chiến.' },
  { id: 'h434', word: 'chronological', meaning: 'theo thứ tự thời gian', example: 'In chronological order.', exampleVN: 'Theo thứ tự thời gian.' },
  { id: 'h435', word: 'circumspect', meaning: 'thận trọng', example: 'A circumspect approach.', exampleVN: 'Một cách tiếp cận thận trọng.' },
  { id: 'h436', word: 'circumvent', meaning: 'né tránh', example: 'Circumvent the law.', exampleVN: 'Lách luật.' },
  { id: 'h437', word: 'clairvoyant', meaning: 'có khả năng thấu thị', example: 'A clairvoyant psychic.', exampleVN: 'Một nhà ngoại cảm có khả năng thấu thị.' },
  { id: 'h438', word: 'clamor', meaning: 'tiếng la hét, tiếng ồn ào', example: 'A clamor for reform.', exampleVN: 'Tiếng la hét đòi cải cách.' },
  { id: 'h439', word: 'clandestine', meaning: 'bí mật, giấu giếm', example: 'A clandestine meeting.', exampleVN: 'Một cuộc họp bí mật.' },
  { id: 'h440', word: 'cleave', meaning: 'chẻ, bám chặt', example: 'To cleave a piece of wood.', exampleVN: 'Chẻ một khúc gỗ.' },
  { id: 'h441', word: 'clemency', meaning: 'sự khoan hồng', example: 'To grant clemency.', exampleVN: 'Ban lệnh khoan hồng.' },
  { id: 'h442', word: 'cliche', meaning: 'lời sáo rỗng', example: 'An old cliche.', exampleVN: 'Một câu sáo rỗng cũ.' },
  { id: 'h443', word: 'cloying', meaning: 'ngọt xớt, phát ngấy', example: 'Cloying sentimentality.', exampleVN: 'Sự đa sầu đa cảm đến phát ngấy.' },
  { id: 'h444', word: 'coagulate', meaning: 'đông tụ', example: 'The blood began to coagulate.', exampleVN: 'Máu bắt đầu đông tụ.' },
  { id: 'h445', word: 'coalesce', meaning: 'kết hợp, hợp nhất', example: 'To coalesce into a single group.', exampleVN: 'Kết hợp thành một nhóm duy nhất.' },
  { id: 'h446', word: 'coerce', meaning: 'ép buộc', example: 'To coerce someone into signing.', exampleVN: 'Ép buộc ai đó ký tên.' },
  { id: 'h447', word: 'cogent', meaning: 'thuyết phục', example: 'A cogent argument.', exampleVN: 'Một lập luận thuyết phục.' },
  { id: 'h448', word: 'cognizant', meaning: 'có hiểu biết, nhận thức', example: 'Cognizant of the risks.', exampleVN: 'Nhận thức được các rủi ro.' },
  { id: 'h449', word: 'coherent', meaning: 'chặt chẽ, mạch lạc', example: 'A coherent explanation.', exampleVN: 'Một lời giải thích mạch lạc.' },
  { id: 'h450', word: 'collateral', meaning: 'tài sản thế chấp', example: 'To provide collateral for a loan.', exampleVN: 'Cung cấp tài sản thế chấp cho một khoản vay.' },
];
