import { Word } from './types';

export const chunk5: Word[] = [
  { id: '601', word: 'abandon', meaning: 'từ bỏ', example: 'They had to abandon the plan.', exampleVN: 'Họ đã phải từ bỏ kế hoạch.' },
  { id: '602', word: 'abide', meaning: 'tuân thủ', example: 'Abide by the decision.', exampleVN: 'Tuân theo quyết định.' },
  { id: '603', word: 'abolish', meaning: 'bãi bỏ', example: 'Abolish the old laws.', exampleVN: 'Bãi bỏ luật lệ cũ.' },
  { id: '604', word: 'abrupt', meaning: 'đột ngột', example: 'An abrupt change.', exampleVN: 'Họ thảo luận về một sự thay đổi đột ngột.' },
  { id: '605', word: 'absent', meaning: 'vắng mặt', example: 'He is absent from work.', exampleVN: 'Anh ấy vắng mặt ở nơi làm việc.' },
  { id: '606', word: 'absolute', meaning: 'tuyệt đối', example: 'An absolute necessity.', exampleVN: 'Một sự cần thiết tuyệt đối.' },
  { id: '607', word: 'absorb', meaning: 'hấp thụ', example: 'Absorb the information.', exampleVN: 'Tiếp thu thông tin.' },
  { id: '608', word: 'abstract', meaning: 'trừu tượng', example: 'An abstract concept.', exampleVN: 'Một khái niệm trừu tượng.' },
  { id: '609', word: 'abundance', meaning: 'sự phong phú', example: 'An abundance of resources.', exampleVN: 'Rất nhiều nguồn lực.' },
  { id: '610', word: 'academy', meaning: 'học viện', example: 'A music academy.', exampleVN: 'Họ thảo luận về một học viện âm nhạc.' },
  { id: '611', word: 'accelerate', meaning: 'tăng tốc', example: 'Accelerate the process.', exampleVN: 'Đẩy nhanh quá trình này.' },
  { id: '612', word: 'accent', meaning: 'giọng', example: 'A foreign accent.', exampleVN: 'Họ thảo luận về một giọng nước ngoài.' },
  { id: '613', word: 'acceptable', meaning: 'có thể chấp nhận', example: 'An acceptable solution.', exampleVN: 'Họ thảo luận về một giải pháp có thể chấp nhận được.' },
  { id: '614', word: 'access', meaning: 'truy cập', example: 'Access to the internet.', exampleVN: 'Truy cập internet.' },
  { id: '615', word: 'accommodate', meaning: 'chứa chấp, đáp ứng', example: 'Accommodate many guests.', exampleVN: 'Tiếp đón nhiều khách.' },
  { id: '616', word: 'accompany', meaning: 'đi cùng', example: 'He will accompany her.', exampleVN: 'Anh ấy sẽ đi cùng cô ấy.' },
  { id: '617', word: 'accomplish', meaning: 'hoàn thành', example: 'Accomplish the goal.', exampleVN: 'Hoàn thành mục tiêu.' },
  { id: '618', word: 'accordance', meaning: 'sự phù hợp', example: 'In accordance with the plan.', exampleVN: 'Diễn ra đúng như kế hoạch.' },
  { id: '619', word: 'accountable', meaning: 'có trách nhiệm', example: 'You are accountable for this.', exampleVN: 'Bạn phải chịu trách nhiệm về việc này.' },
  { id: '620', word: 'accumulate', meaning: 'tích lũy', example: 'Accumulate wealth.', exampleVN: 'Tích lũy của cải.' },
  { id: '621', word: 'accusation', meaning: 'sự buộc tội', example: 'A serious accusation.', exampleVN: 'Họ thảo luận về một lời buộc tội nghiêm trọng.' },
  { id: '622', word: 'accuse', meaning: 'buộc tội', example: 'Accuse him of theft.', exampleVN: 'Buộc tội anh ta về tội trộm cắp.' },
  { id: '623', word: 'achieve', meaning: 'đạt được', example: 'Achieve great success.', exampleVN: 'Đạt được thành công lớn.' },
  { id: '624', word: 'acid', meaning: 'axit', example: 'A strong acid.', exampleVN: 'Họ thảo luận về một axit mạnh.' },
  { id: '625', word: 'acknowledge', meaning: 'thừa nhận', example: 'Acknowledge the receipt.', exampleVN: 'Xác nhận đã nhận.' },
  { id: '626', word: 'acquire', meaning: 'thu được', example: 'Acquire new skills.', exampleVN: 'Có được những kỹ năng mới.' },
  { id: '627', word: 'acquisition', meaning: 'sự thu mua', example: 'The company acquisition.', exampleVN: 'Họ thảo luận về việc mua lại công ty.' },
  { id: '628', word: 'acting', meaning: 'diễn xuất', example: 'His acting is good.', exampleVN: 'Họ thảo luận rằng diễn xuất của anh ấy rất tốt.' },
  { id: '629', word: 'action', meaning: 'hành động', example: 'Take immediate action.', exampleVN: 'Hành động ngay lập tức.' },
  { id: '630', word: 'activate', meaning: 'kích hoạt', example: 'Activate the alarm.', exampleVN: 'Kích hoạt báo động.' },
  { id: '631', word: 'active', meaning: 'tích cực', example: 'An active member.', exampleVN: 'Một thành viên tích cực.' },
  { id: '632', word: 'activity', meaning: 'hoạt động', example: 'Physical activity.', exampleVN: 'Hoạt động thể chất.' },
  { id: '633', word: 'actual', meaning: 'thực tế', example: 'The actual results.', exampleVN: 'Kết quả thực tế.' },
  { id: '634', word: 'acute', meaning: 'nhạy bén, trầm trọng', example: 'Acute pain.', exampleVN: 'Đau cấp tính.' },
  { id: '635', word: 'adapt', meaning: 'thích nghi', example: 'Adapt to changes.', exampleVN: 'Thích ứng với những thay đổi.' },
  { id: '636', word: 'addict', meaning: 'người nghiện', example: 'A drug addict.', exampleVN: 'Họ thảo luận về một người nghiện ma túy.' },
  { id: '637', word: 'additional', meaning: 'thêm', example: 'Additional costs.', exampleVN: 'Thêm chi phí.' },
  { id: '638', word: 'address', meaning: 'địa chỉ', example: 'What is your address?', exampleVN: 'Địa chỉ của bạn là gì?' },
  { id: '639', word: 'adequate', meaning: 'đầy đủ', example: 'Adequate supply.', exampleVN: 'Cung cấp đầy đủ.' },
  { id: '640', word: 'adhere', meaning: 'dính chặt, tuân thủ', example: 'Adhere to policy.', exampleVN: 'Tuân thủ chính sách.' },
  { id: '641', word: 'adjacent', meaning: 'kế bên', example: 'An adjacent room.', exampleVN: 'Họ thảo luận về một căn phòng bên cạnh.' },
  { id: '642', word: 'adjust', meaning: 'điều chỉnh', example: 'Adjust the volume.', exampleVN: 'Điều chỉnh âm lượng.' },
  { id: '643', word: 'administer', meaning: 'quản lý', example: 'Administer treatment.', exampleVN: 'Tiến hành điều trị.' },
  { id: '644', word: 'administrative', meaning: 'hành chính', example: 'Administrative staff.', exampleVN: 'Nhân viên hành chính.' },
  { id: '645', word: 'admirable', meaning: 'đáng ngưỡng mộ', example: 'An admirable quality.', exampleVN: 'Họ thảo luận về một phẩm chất đáng ngưỡng mộ.' },
  { id: '646', word: 'admission', meaning: 'sự cho phép vào', example: 'Free admission.', exampleVN: 'Vào cửa miễn phí.' },
  { id: '647', word: 'admit', meaning: 'thừa nhận', example: 'He admitted his guilt.', exampleVN: 'Anh ấy đã thừa nhận tội lỗi của mình.' },
  { id: '648', word: 'adolescent', meaning: 'thanh thiếu niên', example: 'An adolescent girl.', exampleVN: 'Họ thảo luận về một cô gái vị thành niên.' },
  { id: '649', word: 'adopt', meaning: 'nhận nuôi, thông qua', example: 'Adopt a child.', exampleVN: 'Nhận nuôi một đứa trẻ.' },
  { id: '650', word: 'advance', meaning: 'tiến bộ', example: 'Make great advances.', exampleVN: 'Đạt được những tiến bộ lớn.' },
  { id: '651', word: 'advantage', meaning: 'lợi thế', example: 'An unfair advantage.', exampleVN: 'Họ thảo luận về một lợi thế không công bằng.' },
  { id: '652', word: 'adventure', meaning: 'cuộc phiêu lưu', example: 'A big adventure.', exampleVN: 'Họ thảo luận về một cuộc phiêu lưu lớn.' },
  { id: '653', word: 'adverse', meaning: 'bất lợi', example: 'Adverse weather.', exampleVN: 'Thời tiết bất lợi.' },
  { id: '654', word: 'advertise', meaning: 'quảng cáo', example: 'Advertise online.', exampleVN: 'Quảng cáo trực tuyến.' },
  { id: '655', word: 'advice', meaning: 'lời khuyên', example: 'Seek advice.', exampleVN: 'Tìm kiếm lời khuyên.' },
  { id: '656', word: 'advisable', meaning: 'nên làm', example: 'It is advisable to go.', exampleVN: 'Đó là điều nên đi.' },
  { id: '657', word: 'advocate', meaning: 'người ủng hộ', example: 'An advocate for peace.', exampleVN: 'Họ thảo luận về một người ủng hộ hòa bình.' },
  { id: '658', word: 'aesthetic', meaning: 'thẩm mỹ', example: 'Aesthetic value.', exampleVN: 'Có giá trị thẩm mỹ.' },
  { id: '659', word: 'affair', meaning: 'việc, vụ việc', example: 'A personal affair.', exampleVN: 'Họ thảo luận về một vấn đề cá nhân.' },
  { id: '660', word: 'affect', meaning: 'ảnh hưởng', example: 'It affects us all.', exampleVN: 'Nó ảnh hưởng đến tất cả chúng ta.' },
  { id: '661', word: 'affection', meaning: 'tình cảm', example: 'Show affection.', exampleVN: 'Thể hiện tình cảm.' },
  { id: '662', word: 'affirm', meaning: 'khẳng định', example: 'Affirm the truth.', exampleVN: 'Khẳng định sự thật.' },
  { id: '663', word: 'afford', meaning: 'có đủ khả năng', example: 'Cannot afford it.', exampleVN: 'Không đủ khả năng chi trả.' },
  { id: '664', word: 'affordable', meaning: 'phải chăng', example: 'Affordable price.', exampleVN: 'Giá cả phải chăng.' },
  { id: '665', word: 'agency', meaning: 'cơ quan', example: 'A travel agency.', exampleVN: 'Họ thảo luận về một công ty du lịch.' },
  { id: '666', word: 'agenda', meaning: 'chương trình nghị sự', example: 'Meeting agenda.', exampleVN: 'Chương trình họp.' },
  { id: '667', word: 'agent', meaning: 'đại lý', example: 'A real estate agent.', exampleVN: 'Họ thảo luận về một đại lý bất động sản.' },
  { id: '668', word: 'aggressive', meaning: 'hung hăng', example: 'Aggressive behavior.', exampleVN: 'Có hành vi hung hăng.' },
  { id: '669', word: 'agitate', meaning: 'làm rung động, kích động', example: 'Agitate for change.', exampleVN: 'Vận động để thay đổi.' },
  { id: '670', word: 'agony', meaning: 'nỗi đau đớn', example: 'In great agony.', exampleVN: 'Đang vô cùng đau khổ.' },
  { id: '671', word: 'agree', meaning: 'đồng ý', example: 'I agree with you.', exampleVN: 'Tôi đồng ý với bạn.' },
  { id: '672', word: 'agreement', meaning: 'hợp đồng, sự đồng ý', example: 'Sign the agreement.', exampleVN: 'Ký kết thỏa thuận.' },
  { id: '673', word: 'agriculture', meaning: 'nông nghiệp', example: 'Modern agriculture.', exampleVN: 'Nền nông nghiệp hiện đại.' },
  { id: '674', word: 'aid', meaning: 'viện trợ', example: 'Foreign aid.', exampleVN: 'Viện trợ nước ngoài.' },
  { id: '675', word: 'aim', meaning: 'mục đích', example: 'The aim is to help.', exampleVN: 'Họ thảo luận mục đích là để giúp đỡ.' },
  { id: '676', word: 'aircraft', meaning: 'máy bay', example: 'A military aircraft.', exampleVN: 'Họ thảo luận về một chiếc máy bay quân sự.' },
  { id: '677', word: 'alarm', meaning: 'báo động', example: 'Sound the alarm.', exampleVN: 'Phát ra âm thanh báo động.' },
  { id: '678', word: 'album', meaning: 'album', example: 'A music album.', exampleVN: 'Họ thảo luận về một album nhạc.' },
  { id: '679', word: 'alert', meaning: 'cảnh giác', example: 'Stay alert.', exampleVN: 'Luôn cảnh giác.' },
  { id: '680', word: 'alien', meaning: 'người ngoài hành tinh', example: 'A sci-fi alien.', exampleVN: 'Một người ngoài hành tinh khoa học viễn tưởng.' },
  { id: '681', word: 'align', meaning: 'sắp xếp, căn chỉnh', example: 'Align the text.', exampleVN: 'Căn chỉnh văn bản.' },
  { id: '682', word: 'alike', meaning: 'giống nhau', example: 'They look alike.', exampleVN: 'Chúng trông giống nhau.' },
  { id: '683', word: 'alive', meaning: 'còn sống', example: 'She is still alive.', exampleVN: 'Cô ấy vẫn còn sống.' },
  { id: '684', word: 'allegation', meaning: 'cáo buộc', example: 'False allegation.', exampleVN: 'Cáo buộc sai sự thật.' },
  { id: '685', word: 'alleviate', meaning: 'làm giảm bớt', example: 'Alleviate pain.', exampleVN: 'Giảm bớt nỗi đau.' },
  { id: '686', word: 'alliance', meaning: 'liên minh', example: 'A strong alliance.', exampleVN: 'Họ thảo luận về một liên minh mạnh mẽ.' },
  { id: '687', word: 'allocate', meaning: 'phân bổ', example: 'Allocate funds.', exampleVN: 'Phân bổ kinh phí.' },
  { id: '688', word: 'allot', meaning: 'phân chia', example: 'Allot time properly.', exampleVN: 'Phân bổ thời gian hợp lý.' },
  { id: '689', word: 'allow', meaning: 'cho phép', example: 'Allow me to go.', exampleVN: 'Cho phép tôi đi.' },
  { id: '690', word: 'allure', meaning: 'sự quyến rũ', example: 'The allure of fame.', exampleVN: 'Họ thảo luận về sức hấp dẫn của sự nổi tiếng.' },
  { id: '691', word: 'ally', meaning: 'đồng minh', example: 'A close ally.', exampleVN: 'Một đồng minh thân thiết.' },
  { id: '692', word: 'almighty', meaning: 'toàn năng', example: 'The almighty god.', exampleVN: 'Họ thảo luận về vị thần toàn năng.' },
  { id: '693', word: 'almost', meaning: 'gần như', example: 'Almost there.', exampleVN: 'Gần như ở đó.' },
  { id: '694', word: 'alone', meaning: 'một mình', example: 'All alone.', exampleVN: 'Tất cả một mình.' },
  { id: '695', word: 'along', meaning: 'dọc theo', example: 'Walk along the river.', exampleVN: 'Đi bộ dọc bờ sông.' },
  { id: '696', word: 'alongside', meaning: 'bên cạnh', example: 'Work alongside me.', exampleVN: 'Công việc cùng với tôi.' },
  { id: '697', word: 'aloud', meaning: 'thành tiếng', example: 'Read it aloud.', exampleVN: 'Đọc to nó.' },
  { id: '698', word: 'alphabet', meaning: 'bảng chữ cái', example: 'The English alphabet.', exampleVN: 'Bảng chữ cái tiếng Anh.' },
  { id: '699', word: 'alter', meaning: 'thay đổi', example: 'Alter the design.', exampleVN: 'Thay đổi thiết kế.' },
  { id: '700', word: 'alternate', meaning: 'thay thế', example: 'Alternate days.', exampleVN: 'Luân phiên các ngày.' }
];

export const processChunk5 = () => {
    return chunk5;
};
