import { Word } from './types';

export const chunk12: Word[] = [
  { id: 'ext201', word: 'duplicate', meaning: 'bản sao, gấp đôi', example: 'Is this a duplicate copy?', exampleVN: 'Đây có phải là bản sao không?' },
  { id: 'ext202', word: 'durable', meaning: 'bền', example: 'Durable goods.', exampleVN: 'Hàng bền.' },
  { id: 'ext203', word: 'dynamic', meaning: 'năng động', example: 'A dynamic leader.', exampleVN: 'Một nhà lãnh đạo năng động.' },
  { id: 'ext204', word: 'earnings', meaning: 'thu nhập', example: 'Company earnings.', exampleVN: 'Thu nhập của công ty.' },
  { id: 'ext205', word: 'echo', meaning: 'vọng lại', example: 'The room echoed.', exampleVN: 'Căn phòng vang vọng.' },
  { id: 'ext206', word: 'ecology', meaning: 'sinh thái học', example: 'Study ecology.', exampleVN: 'Học sinh thái học.' },
  { id: 'ext207', word: 'economical', meaning: 'tiết kiệm', example: 'An economical car.', exampleVN: 'Một chiếc xe tiết kiệm.' },
  { id: 'ext208', word: 'edit', meaning: 'chỉnh sửa', example: 'Edit the video.', exampleVN: 'Chỉnh sửa video.' },
  { id: 'ext209', word: 'edition', meaning: 'phiên bản, lần xuất bản', example: 'The second edition.', exampleVN: 'Tái bản lần thứ hai.' },
  { id: 'ext210', word: 'effective', meaning: 'hiệu quả', example: 'An effective cure.', exampleVN: 'Một phương thuốc hiệu quả.' },
  { id: 'ext211', word: 'efficiency', meaning: 'hiệu suất', example: 'Improve efficiency.', exampleVN: 'Cải thiện hiệu suất.' },
  { id: 'ext212', word: 'elaborate', meaning: 'tỉ mỉ, trau chuốt', example: 'An elaborate design.', exampleVN: 'Một thiết kế công phu.' },
  { id: 'ext213', word: 'elastic', meaning: 'đàn hồi', example: 'Elastic band.', exampleVN: 'Dây chun.' },
  { id: 'ext214', word: 'elderly', meaning: 'người già', example: 'Look after the elderly.', exampleVN: 'Chăm sóc người già.' },
  { id: 'ext215', word: 'elect', meaning: 'bầu cử', example: 'They elected him president.', exampleVN: 'Họ đã bầu ông làm tổng thống.' },
  { id: 'ext216', word: 'elegant', meaning: 'thanh lịch', example: 'She looks elegant.', exampleVN: 'Cô ấy trông thật thanh lịch.' },
  { id: 'ext217', word: 'element', meaning: 'yếu tố', example: 'An important element.', exampleVN: 'Một yếu tố quan trọng.' },
  { id: 'ext218', word: 'elevate', meaning: 'nâng lên', example: 'Elevate your feet.', exampleVN: 'Nâng cao bàn chân của bạn.' },
  { id: 'ext219', word: 'eligible', meaning: 'đủ điều kiện', example: 'Eligible for a pension.', exampleVN: 'Đủ điều kiện nhận lương hưu.' },
  { id: 'ext220', word: 'eliminate', meaning: 'loại bỏ', example: 'Eliminate the risk.', exampleVN: 'Loại bỏ rủi ro.' },
  { id: 'ext221', word: 'elite', meaning: 'ưu tú', example: 'The political elite.', exampleVN: 'Tầng lớp chính trị ưu tú.' },
  { id: 'ext222', word: 'embark', meaning: 'lên tàu, bắt đầu', example: 'Embark on a journey.', exampleVN: 'Bắt đầu một cuộc hành trình.' },
  { id: 'ext223', word: 'embarrass', meaning: 'làm ngượng ngùng', example: 'Don\'t embarrass me.', exampleVN: 'Đừng làm tôi xấu hổ.' },
  { id: 'ext224', word: 'embassy', meaning: 'đại sứ quán', example: 'Go to the embassy.', exampleVN: 'Đến đại sứ quán.' },
  { id: 'ext225', word: 'embody', meaning: 'hiện thân', example: 'The book embodies his ideas.', exampleVN: 'Cuốn sách hiện thực hóa các ý tưởng của ông.' },
  { id: 'ext226', word: 'embrace', meaning: 'ôm, đón nhận', example: 'Embrace change.', exampleVN: 'Đón nhận sự thay đổi.' },
  { id: 'ext227', word: 'emerge', meaning: 'nổi lên', example: 'New evidence emerged.', exampleVN: 'Bằng chứng mới đã xuất hiện.' },
  { id: 'ext228', word: 'emergency', meaning: 'khẩn cấp', example: 'In case of emergency.', exampleVN: 'Trong trường hợp khẩn cấp.' },
  { id: 'ext229', word: 'eminent', meaning: 'lỗi lạc', example: 'An eminent scientist.', exampleVN: 'Một nhà khoa học lỗi lạc.' },
  { id: 'ext230', word: 'emission', meaning: 'khí thải', example: 'Gas emissions.', exampleVN: 'Khí thải khí.' },
  { id: 'ext231', word: 'emotion', meaning: 'cảm xúc', example: 'High emotion.', exampleVN: 'Cảm xúc dâng trào.' },
  { id: 'ext232', word: 'emphasis', meaning: 'nhấn mạnh', example: 'Place emphasis on safety.', exampleVN: 'Nhấn mạnh vào sự an toàn.' },
  { id: 'ext233', word: 'empirical', meaning: 'theo kinh nghiệm', example: 'Empirical research.', exampleVN: 'Nghiên cứu thực nghiệm.' },
  { id: 'ext234', word: 'employ', meaning: 'thuê, sử dụng', example: 'They employ 100 people.', exampleVN: 'Họ thuê 100 người.' },
  { id: 'ext235', word: 'enable', meaning: 'cho phép', example: 'Enable cookies.', exampleVN: 'Cho phép cookie.' },
  { id: 'ext236', word: 'enclosed', meaning: 'đính kèm, bao quanh', example: 'Enclosed please find the invoice.', exampleVN: 'Gửi kèm theo đây xin vui lòng tìm thấy hóa đơn.' },
  { id: 'ext237', word: 'encounter', meaning: 'gặp gỡ, chạm trán', example: 'Encounter difficulties.', exampleVN: 'Gặp khó khăn.' },
  { id: 'ext238', word: 'encourage', meaning: 'khuyến khích', example: 'They encouraged us to try.', exampleVN: 'Họ khuyến khích chúng tôi thử.' },
  { id: 'ext239', word: 'endeavor', meaning: 'nỗ lực', example: 'A worthy endeavor.', exampleVN: 'Một nỗ lực xứng đáng.' },
  { id: 'ext240', word: 'endorse', meaning: 'xác nhận, tán thành', example: 'Endorse the candidate.', exampleVN: 'Tán thành ứng cử viên.' },
  { id: 'ext241', word: 'endure', meaning: 'chịu đựng', example: 'Endure pain.', exampleVN: 'Chịu đựng nỗi đau.' },
  { id: 'ext242', word: 'energetic', meaning: 'năng động', example: 'An energetic person.', exampleVN: 'Một người năng động.' },
  { id: 'ext243', word: 'enforce', meaning: 'thực thi', example: 'Enforce the law.', exampleVN: 'Thực thi pháp luật.' },
  { id: 'ext244', word: 'engage', meaning: 'thuê, đính hôn, tham gia', example: 'Engaged in business.', exampleVN: 'Tham gia kinh doanh.' },
  { id: 'ext245', word: 'engine', meaning: 'động cơ', example: 'Start the engine.', exampleVN: 'Khởi động động cơ.' },
  { id: 'ext246', word: 'enhance', meaning: 'nâng cao', example: 'Enhance the quality.', exampleVN: 'Nâng cao chất lượng.' },
  { id: 'ext247', word: 'enlarge', meaning: 'mở rộng', example: 'Enlarge the photo.', exampleVN: 'Phóng to ảnh.' },
  { id: 'ext248', word: 'enlighten', meaning: 'làm sáng tỏ', example: 'Enlighten me about the situation.', exampleVN: 'Hãy giải thích cho tôi về tình hình này.' },
  { id: 'ext249', word: 'enormous', meaning: 'khổng lồ', example: 'An enormous house.', exampleVN: 'Một ngôi nhà khổng lồ.' },
  { id: 'ext250', word: 'enroll', meaning: 'ghi danh', example: 'Enroll in a course.', exampleVN: 'Ghi danh vào một khóa học.' },
  { id: 'ext251', word: 'ensure', meaning: 'đảm bảo', example: 'Ensure safety.', exampleVN: 'Đảm bảo an toàn.' },
  { id: 'ext252', word: 'enterprise', meaning: 'doanh nghiệp', example: 'Small and medium enterprises.', exampleVN: 'Các doanh nghiệp vừa và nhỏ.' },
  { id: 'ext253', word: 'entertainment', meaning: 'giải trí', example: 'A form of entertainment.', exampleVN: 'Một hình thức giải trí.' },
  { id: 'ext254', word: 'enthusiastic', meaning: 'nhiệt tình', example: 'An enthusiastic support.', exampleVN: 'Sự ủng hộ nhiệt tình.' },
  { id: 'ext255', word: 'entitle', meaning: 'được quyền', example: 'You are entitled to a refund.', exampleVN: 'Bạn có quyền được hoàn tiền.' },
  { id: 'ext256', word: 'entity', meaning: 'thực thể', example: 'A separate legal entity.', exampleVN: 'Một thực thể pháp lý độc lập.' },
  { id: 'ext257', word: 'entrepreneur', meaning: 'doanh nhân', example: 'A successful entrepreneur.', exampleVN: 'Một doanh nhân thành đạt.' },
  { id: 'ext258', word: 'entry', meaning: 'lối vào, mục nhập', example: 'No entry.', exampleVN: 'Cấm vào.' },
  { id: 'ext259', word: 'envelope', meaning: 'phong bì', example: 'Put the letter in the envelope.', exampleVN: 'Cho thư vào phong bì.' },
  { id: 'ext260', word: 'environment', meaning: 'môi trường', example: 'Protect the environment.', exampleVN: 'Bảo vệ môi trường.' },
  { id: 'ext261', word: 'envoy', meaning: 'đặc phái viên', example: 'Peace envoy.', exampleVN: 'Đặc phái viên hòa bình.' },
  { id: 'ext262', word: 'episode', meaning: 'tập phim', example: 'The final episode.', exampleVN: 'Tập phim cuối cùng.' },
  { id: 'ext263', word: 'equity', meaning: 'vốn chủ sở hữu, sự công bằng', example: 'Share equity.', exampleVN: 'Vốn cổ phần.' },
  { id: 'ext264', word: 'equivalent', meaning: 'tương đương', example: 'Equivalent amount.', exampleVN: 'Số lượng tương đương.' },
  { id: 'ext265', word: 'erase', meaning: 'xóa bỏ', example: 'Erase the blackboard.', exampleVN: 'Xóa bảng.' },
  { id: 'ext266', word: 'erect', meaning: 'xây dựng', example: 'Erect a monument.', exampleVN: 'Xây dựng một tượng đài.' },
  { id: 'ext267', word: 'erroneous', meaning: 'sai lầm', example: 'Erroneous belief.', exampleVN: 'Niềm tin sai lầm.' },
  { id: 'ext268', word: 'erupt', meaning: 'phun trào', example: 'The volcano erupted.', exampleVN: 'Núi lửa đã phun trào.' },
  { id: 'ext269', word: 'escalate', meaning: 'leo thang', example: 'The tension escalated.', exampleVN: 'Căng thẳng leo thang.' },
  { id: 'ext270', word: 'essence', meaning: 'bản chất', example: 'The essence of the problem.', exampleVN: 'Bản chất của vấn đề.' },
  { id: 'ext271', word: 'essential', meaning: 'thiết yếu', example: 'Essential oils.', exampleVN: 'Tinh dầu.' },
  { id: 'ext272', word: 'establish', meaning: 'thiết lập', example: 'Establish a business.', exampleVN: 'Thành lập một doanh nghiệp.' },
  { id: 'ext273', word: 'estate', meaning: 'bất động sản', example: 'Real estate.', exampleVN: 'Bất động sản.' },
  { id: 'ext274', word: 'estimate', meaning: 'ước tính', example: 'Give an estimate.', exampleVN: 'Đưa ra một ước tính.' },
  { id: 'ext275', word: 'eternal', meaning: 'vĩnh cửu', example: 'Eternal life.', exampleVN: 'Sự sống vĩnh cửu.' },
  { id: 'ext276', word: 'ethics', meaning: 'đạo đức', example: 'Business ethics.', exampleVN: 'Đạo đức kinh doanh.' },
  { id: 'ext277', word: 'ethnic', meaning: 'dân tộc', example: 'Ethnic minorities.', exampleVN: 'Các dân tộc thiểu số.' },
  { id: 'ext278', word: 'evacuate', meaning: 'sơ tán', example: 'Evacuate the building.', exampleVN: 'Sơ tán khỏi tòa nhà.' },
  { id: 'ext279', word: 'evaluate', meaning: 'đánh giá', example: 'Evaluate performance.', exampleVN: 'Đánh giá hiệu suất.' },
  { id: 'ext280', word: 'evaporate', meaning: 'bay hơi', example: 'The water evaporated.', exampleVN: 'Nước đã bay hơi.' },
  { id: 'ext281', word: 'eventual', meaning: 'cuối cùng', example: 'Eventual success.', exampleVN: 'Thành công cuối cùng.' },
  { id: 'ext282', word: 'evident', meaning: 'hiển nhiên', example: 'It was evident that she was angry.', exampleVN: 'Rõ ràng là cô ấy đang tức giận.' },
  { id: 'ext283', word: 'evolve', meaning: 'tiến hóa', example: 'Evolve over time.', exampleVN: 'Tiến hóa theo thời gian.' },
  { id: 'ext284', word: 'exaggerate', meaning: 'phóng đại', example: 'Don\'t exaggerate.', exampleVN: 'Đừng thổi phồng nó lên.' },
  { id: 'ext285', word: 'exceed', meaning: 'vượt quá', example: 'Exceed the speed limit.', exampleVN: 'Vượt quá tốc độ cho phép.' },
  { id: 'ext286', word: 'excel', meaning: 'xuất sắc', example: 'She excels at sports.', exampleVN: 'Cô ấy xuất sắc trong thể thao.' },
  { id: 'ext287', word: 'exceptional', meaning: 'ngoại lệ, xuất sắc', example: 'An exceptional student.', exampleVN: 'Một học sinh xuất sắc.' },
  { id: 'ext288', word: 'excerpt', meaning: 'đoạn trích', example: 'Read this excerpt.', exampleVN: 'Đọc đoạn trích này.' },
  { id: 'ext289', word: 'excess', meaning: 'dư thừa', example: 'Excess weight.', exampleVN: 'Trọng lượng dư thừa.' },
  { id: 'ext290', word: 'exclusive', meaning: 'độc quyền', example: 'An exclusive interview.', exampleVN: 'Một cuộc phỏng vấn độc quyền.' },
  { id: 'ext291', word: 'execute', meaning: 'thi hành, thực hiện', example: 'Execute a plan.', exampleVN: 'Thực hiện một kế hoạch.' },
  { id: 'ext292', word: 'exempt', meaning: 'miễn', example: 'Exempt from tax.', exampleVN: 'Miễn thuế.' },
  { id: 'ext293', word: 'exert', meaning: 'gắng sức, áp dụng', example: 'Exert pressure.', exampleVN: 'Gây sức ép.' },
  { id: 'ext294', word: 'exhale', meaning: 'thở ra', example: 'Inhale and exhale.', exampleVN: 'Hít vào và thở ra.' },
  { id: 'ext295', word: 'exhaust', meaning: 'làm kiệt sức, khí thải', example: 'This work exhausts me.', exampleVN: 'Công việc này làm tôi kiệt sức.' },
  { id: 'ext296', word: 'exhibit', meaning: 'trưng bày', example: 'Exhibit at a gallery.', exampleVN: 'Trưng bày tại phòng triển lãm.' },
  { id: 'ext297', word: 'exile', meaning: 'lưu đày', example: 'Go into exile.', exampleVN: 'Đi lưu vong.' },
  { id: 'ext298', word: 'exist', meaning: 'tồn tại', example: 'Do aliens exist?', exampleVN: 'Người ngoài hành tinh có tồn tại không?' },
  { id: 'ext299', word: 'expand', meaning: 'mở rộng', example: 'Expand the business.', exampleVN: 'Mở rộng quy mô kinh doanh.' },
  { id: 'ext300', word: 'expel', meaning: 'trục xuất', example: 'Expelled from school.', exampleVN: 'Bị đuổi khỏi trường.' },
  { id: 'ext301', word: 'expenditure', meaning: 'chi phí', example: 'Military expenditure.', exampleVN: 'Chi phí quân sự.' },
  { id: 'ext302', word: 'expertise', meaning: 'chuyên môn', example: 'Technical expertise.', exampleVN: 'Chuyên môn kỹ thuật.' },
  { id: 'ext303', word: 'expire', meaning: 'hết hạn', example: 'The contract expires in May.', exampleVN: 'Hợp đồng hết hạn vào tháng Năm.' },
  { id: 'ext304', word: 'explicit', meaning: 'rõ ràng', example: 'Explicit instructions.', exampleVN: 'Hướng dẫn rõ ràng.' },
  { id: 'ext305', word: 'exploit', meaning: 'khai thác', example: 'Exploit natural resources.', exampleVN: 'Khai thác tài nguyên thiên nhiên.' },
  { id: 'ext306', word: 'explore', meaning: 'khám phá', example: 'Explore the city.', exampleVN: 'Khám phá thành phố.' },
  { id: 'ext307', word: 'export', meaning: 'xuất khẩu', example: 'Export to Japan.', exampleVN: 'Xuất khẩu sang Nhật Bản.' },
  { id: 'ext308', word: 'expose', meaning: 'phơi bày, tiếp xúc', example: 'Exposed to the sun.', exampleVN: 'Tiếp xúc với ánh nắng mặt trời.' },
  { id: 'ext309', word: 'exquisite', meaning: 'tinh tế', example: 'Exquisite jewelry.', exampleVN: 'Trang sức tinh xảo.' },
  { id: 'ext310', word: 'extend', meaning: 'kéo dài, mở rộng', example: 'Extend the deadline.', exampleVN: 'Gia hạn.' },
  { id: 'ext311', word: 'extensive', meaning: 'rộng rãi', example: 'Extensive knowledge.', exampleVN: 'Kiến thức sâu rộng.' },
  { id: 'ext312', word: 'external', meaning: 'bên ngoài', example: 'External hard drive.', exampleVN: 'Ổ cứng ngoài.' },
  { id: 'ext313', word: 'extinct', meaning: 'tuyệt chủng', example: 'Dinosaurs are extinct.', exampleVN: 'Khủng long đã tuyệt chủng.' },
  { id: 'ext314', word: 'extract', meaning: 'chiết xuất', example: 'Extract oil.', exampleVN: 'Chiết xuất dầu.' },
  { id: 'ext315', word: 'extraordinary', meaning: 'phi thường', example: 'An extraordinary performance.', exampleVN: 'Một hiệu suất phi thường.' },
  { id: 'ext316', word: 'extravagant', meaning: 'phung phí', example: 'An extravagant lifestyle.', exampleVN: 'Một lối sống phung phí.' },
  { id: 'ext317', word: 'extreme', meaning: 'vô cùng', example: 'Extreme weather.', exampleVN: 'Thời tiết cực đoan.' },
  { id: 'ext318', word: 'fabric', meaning: 'vải', example: 'Cotton fabric.', exampleVN: 'Vải bông.' },
  { id: 'ext319', word: 'facilitate', meaning: 'tạo điều kiện', example: 'Facilitate learning.', exampleVN: 'Tạo điều kiện thuận lợi cho việc học tập.' },
  { id: 'ext320', word: 'facility', meaning: 'cơ sở vật chất', example: 'Sports facilities.', exampleVN: 'Cơ sở vật chất thể thao.' },
  { id: 'ext321', word: 'factor', meaning: 'yếu tố', example: 'An important factor.', exampleVN: 'Một yếu tố quan trọng.' },
  { id: 'ext322', word: 'faculty', meaning: 'khoa, khả năng', example: 'The faculty of law.', exampleVN: 'Khoa luật.' },
  { id: 'ext323', word: 'failure', meaning: 'thất bại', example: 'Fear of failure.', exampleVN: 'Nỗi sợ thất bại.' },
  { id: 'ext324', word: 'fake', meaning: 'giả', example: 'A fake watch.', exampleVN: 'Một chiếc đồng hồ giả.' },
  { id: 'ext325', word: 'fallacy', meaning: 'ngụy biện, sai lầm', example: 'A common fallacy.', exampleVN: 'Một quan niệm sai lầm phổ biến.' },
  { id: 'ext326', word: 'fame', meaning: 'danh tiếng', example: 'Achieve fame.', exampleVN: 'Đạt được sự nổi tiếng.' },
  { id: 'ext327', word: 'fantasy', meaning: 'tưởng tượng', example: 'A world of fantasy.', exampleVN: 'Một thế giới tưởng tượng.' },
  { id: 'ext328', word: 'fare', meaning: 'giá vé', example: 'Bus fare.', exampleVN: 'Giá vé xe buýt.' },
  { id: 'ext329', word: 'fascinate', meaning: 'mê hoặc', example: 'He is fascinated by history.', exampleVN: 'Anh ấy bị mê hoặc bởi lịch sử.' },
  { id: 'ext330', word: 'fasten', meaning: 'buộc chặt', example: 'Fasten your seatbelt.', exampleVN: 'Thắt dây an toàn.' },
  { id: 'ext331', word: 'fatal', meaning: 'gây chết người, tai hại', example: 'A fatal accident.', exampleVN: 'Một tai nạn chết người.' },
  { id: 'ext332', word: 'fatigue', meaning: 'mệt mỏi', example: 'Muscle fatigue.', exampleVN: 'Mỏi cơ.' },
  { id: 'ext333', word: 'feat', meaning: 'kỳ tích', example: 'A remarkable feat.', exampleVN: 'Một kỳ tích đáng chú ý.' },
  { id: 'ext334', word: 'feature', meaning: 'đặc điểm', example: 'Unique features.', exampleVN: 'Các tính năng độc đáo.' },
  { id: 'ext335', word: 'federal', meaning: 'liên bang', example: 'Federal government.', exampleVN: 'Chính phủ liên bang.' },
  { id: 'ext336', word: 'feedback', meaning: 'phản hồi', example: 'Customer feedback.', exampleVN: 'Phản hồi khách hàng.' },
  { id: 'ext337', word: 'fellow', meaning: 'bạn, đồng chí', example: 'Fellow students.', exampleVN: 'Các học sinh khác.' },
  { id: 'ext338', word: 'fertile', meaning: 'màu mỡ', example: 'Fertile soil.', exampleVN: 'Đất màu mỡ.' },
  { id: 'ext339', word: 'fetch', meaning: 'tìm về', example: 'Fetch a pale of water.', exampleVN: 'Đi xách một xô nước.' },
  { id: 'ext340', word: 'fiction', meaning: 'viễn tưởng', example: 'A work of fiction.', exampleVN: 'Một tác phẩm hư cấu.' },
  { id: 'ext341', word: 'fierce', meaning: 'hung dữ, khốc liệt', example: 'Fierce competition.', exampleVN: 'Cạnh tranh khốc liệt.' },
  { id: 'ext342', word: 'figure', meaning: 'con số, nhân vật', example: 'A key figure.', exampleVN: 'Một nhân vật chủ chốt.' },
  { id: 'ext343', word: 'finance', meaning: 'tài chính', example: 'Study finance.', exampleVN: 'Học tài chính.' },
  { id: 'ext344', word: 'finding', meaning: 'kết quả nghiên cứu', example: 'Research findings.', exampleVN: 'Kết quả nghiên cứu.' },
  { id: 'ext345', word: 'finite', meaning: 'hữu hạn', example: 'Finite resources.', exampleVN: 'Tài nguyên hữu hạn.' },
  { id: 'ext346', word: 'flat', meaning: 'bằng phẳng, căn hộ', example: 'A flat surface.', exampleVN: 'Một bề mặt phẳng.' },
  { id: 'ext347', word: 'flee', meaning: 'chạy trốn', example: 'Flee the scene.', exampleVN: 'Trốn khỏi hiện trường.' },
  { id: 'ext348', word: 'flexible', meaning: 'linh hoạt', example: 'Flexible working hours.', exampleVN: 'Giờ làm việc linh hoạt.' },
  { id: 'ext349', word: 'flock', meaning: 'đàn, bầy', example: 'A flock of birds.', exampleVN: 'Một đàn chim.' },
  { id: 'ext350', word: 'flourish', meaning: 'hưng thịnh', example: 'Business is flourishing.', exampleVN: 'Công việc kinh doanh đang khởi sắc.' },
  { id: 'ext351', word: 'fluctuate', meaning: 'dao động', example: 'Prices fluctuate.', exampleVN: 'Giá cả biến động.' },
  { id: 'ext352', word: 'fluid', meaning: 'chất lỏng, lỏng lẻo', example: 'Fluid motion.', exampleVN: 'Chuyển động linh hoạt.' },
  { id: 'ext353', word: 'focus', meaning: 'tập trung', example: 'Focus on your work.', exampleVN: 'Tập trung vào công việc của bạn.' },
  { id: 'ext354', word: 'forbid', meaning: 'cấm', example: 'Smoking is forbidden.', exampleVN: 'Hút thuốc bị cấm.' },
  { id: 'ext355', word: 'forecast', meaning: 'dự báo', example: 'Weather forecast.', exampleVN: 'Dự báo thời tiết.' },
  { id: 'ext356', word: 'formal', meaning: 'trang trọng', example: 'Formal education.', exampleVN: 'Giáo dục chính quy.' },
  { id: 'ext357', word: 'format', meaning: 'định dạng', example: 'Choose a file format.', exampleVN: 'Chọn định dạng tập tin.' },
  { id: 'ext358', word: 'formula', meaning: 'công thức', example: 'A secret formula.', exampleVN: 'Một công thức bí mật.' },
  { id: 'ext359', word: 'fortune', meaning: 'vận may, tài sản', example: 'Make a fortune.', exampleVN: 'Kiếm được một tài sản lớn.' },
  { id: 'ext360', word: 'foster', meaning: 'nuôi dưỡng, thúc đẩy', example: 'Foster innovation.', exampleVN: 'Thúc đẩy đổi mới.' },
  { id: 'ext361', word: 'foundation', meaning: 'nền tảng', example: 'The foundation of the building.', exampleVN: 'Nền móng của tòa nhà.' },
  { id: 'ext362', word: 'fraction', meaning: 'phân số, phần nhỏ', example: 'A small fraction.', exampleVN: 'Một phần nhỏ.' },
  { id: 'ext363', word: 'fragile', meaning: 'mỏng manh, dễ vỡ', example: 'Fragile glass.', exampleVN: 'Thủy tinh dễ vỡ.' },
  { id: 'ext364', word: 'fragment', meaning: 'mảnh vỡ', example: 'Fragment of a vase.', exampleVN: 'Mảnh vỡ của một chiếc bình.' },
  { id: 'ext365', word: 'fraud', meaning: 'gian lận', example: 'Credit card fraud.', exampleVN: 'Gian lận thẻ tín dụng.' },
  { id: 'ext366', word: 'frequent', meaning: 'thường xuyên', example: 'A frequent visitor.', exampleVN: 'Một vị khách thường xuyên.' },
  { id: 'ext367', word: 'friction', meaning: 'ma sát', example: 'Reduce friction.', exampleVN: 'Giảm ma sát.' },
  { id: 'ext368', word: 'frontier', meaning: 'biên giới', example: 'Cross the frontier.', exampleVN: 'Vượt qua biên giới.' },
  { id: 'ext369', word: 'frown', meaning: 'cau mày', example: 'Don\'t frown.', exampleVN: 'Đừng cau mày.' },
  { id: 'ext370', word: 'frustrate', meaning: 'làm nản lòng', example: 'Frustrated by the delay.', exampleVN: 'Thất vọng vì sự chậm trễ.' },
  { id: 'ext371', word: 'fuel', meaning: 'nhiên liệu', example: 'Running out of fuel.', exampleVN: 'Hết nhiên liệu.' },
  { id: 'ext372', word: 'fulfill', meaning: 'hoàn thành', example: 'Fulfill a promise.', exampleVN: 'Thực hiện một lời hứa.' },
  { id: 'ext373', word: 'function', meaning: 'chức năng', example: 'The main function.', exampleVN: 'Chức năng chính.' },
  { id: 'ext374', word: 'fundamental', meaning: 'cơ bản', example: 'Fundamental rights.', exampleVN: 'Các quyền cơ bản.' },
  { id: 'ext375', word: 'funeral', meaning: 'đám tang', example: 'Attend a funeral.', exampleVN: 'Tham dự một đám tang.' },
  { id: 'ext376', word: 'furious', meaning: 'giận dữ', example: 'He was furious at the news.', exampleVN: 'Anh ta đã rất giận dữ trước tin tức này.' },
  { id: 'ext377', word: 'furnace', meaning: 'lò nung', example: 'A blast furnace.', exampleVN: 'Một lò cao.' },
  { id: 'ext378', word: 'furnish', meaning: 'cung cấp đồ đạc', example: 'Furnished apartment.', exampleVN: 'Căn hộ đầy đủ nội thất.' },
  { id: 'ext379', word: 'further', meaning: 'xa hơn, thêm nữa', example: 'Further details.', exampleVN: 'Thông tin bổ sung.' },
  { id: 'ext380', word: 'futile', meaning: 'vô ích', example: 'A futile attempt.', exampleVN: 'Một sự nỗ lực vô ích.' },
  { id: 'ext381', word: 'gadget', meaning: 'tiện ích', example: 'A useful kitchen gadget.', exampleVN: 'Một dụng cụ nhà bếp hữu ích.' },
  { id: 'ext382', word: 'gain', meaning: 'đạt được', example: 'Gain weight.', exampleVN: 'Tăng cân.' },
  { id: 'ext383', word: 'galaxy', meaning: 'thiên hà', example: 'The Milky Way galaxy.', exampleVN: 'Thiên hà Ngân Hà.' },
  { id: 'ext384', word: 'gallery', meaning: 'phòng trưng bày', example: 'An art gallery.', exampleVN: 'Một phòng triển lãm nghệ thuật.' },
  { id: 'ext385', word: 'gamble', meaning: 'đánh bạc', example: 'Don\'t gamble your life away.', exampleVN: 'Đừng đánh bạc cả cuộc đời mình.' },
  { id: 'ext386', word: 'gang', meaning: 'băng nhóm', example: 'A street gang.', exampleVN: 'Một băng đảng đường phố.' },
  { id: 'ext387', word: 'gap', meaning: 'khoảng cách', example: 'The bridge gap.', exampleVN: 'Khoảng cách giữa các nhịp cầu.' },
  { id: 'ext388', word: 'garbage', meaning: 'rác', example: 'Take out the garbage.', exampleVN: 'Đi đổ rác.' },
  { id: 'ext389', word: 'garment', meaning: 'quần áo', example: 'Outer garment.', exampleVN: 'Áo khoác ngoài.' },
  { id: 'ext390', word: 'gasp', meaning: 'thở hổn hển', example: 'Gasp for air.', exampleVN: 'Thở hổn hển.' },
  { id: 'ext391', word: 'gauge', meaning: 'đo lường', example: 'Gauge public opinion.', exampleVN: 'Đo lường ý kiến công chúng.' },
  { id: 'ext392', word: 'gear', meaning: 'bánh răng, trang bị', example: 'Camping gear.', exampleVN: 'Đồ dùng cắm trại.' },
  { id: 'ext393', word: 'gender', meaning: 'giới tính', example: 'Equality between genders.', exampleVN: 'Bình đẳng giữa các giới.' },
  { id: 'ext394', word: 'gene', meaning: 'gen', example: 'Inherit genes.', exampleVN: 'Di truyền gen.' },
  { id: 'ext395', word: 'general', meaning: 'tổng quát', example: 'Gerenal knowledge.', exampleVN: 'Kiến thức tổng quát.' },
  { id: 'ext396', word: 'generate', meaning: 'tạo ra', example: 'Generate electricity.', exampleVN: 'Tạo ra điện.' },
  { id: 'ext397', word: 'generous', meaning: 'hào phóng', example: 'A generous gift.', exampleVN: 'Một món quà hào phóng.' },
  { id: 'ext398', word: 'genius', meaning: 'thiên tài', example: 'He is a mathematical genius.', exampleVN: 'Anh ấy là một thiên tài toán học.' },
  { id: 'ext399', word: 'genuine', meaning: 'thật, chính hãng', example: 'Genuine leather.', exampleVN: 'Da thật.' },
  { id: 'ext400', word: 'geometry', meaning: 'hình học', example: 'Study geometry.', exampleVN: 'Học hình học.' }
];

export const processChunk12 = () => {
    const nouns = new Set(['earnings', 'ecology', 'edition', 'efficiency', 'elastic', 'element', 'elite', 'embassy', 'emergency', 'emission', 'emotion', 'emphasis', 'endeavor', 'engine', 'enterprise', 'entertainment', 'entity', 'entrepreneur', 'entry', 'envelope', 'environment', 'envoy', 'episode', 'equity', 'essence', 'estate', 'ethics', 'excerpt', 'excess', 'expenditure', 'expertise', 'fabric', 'facility', 'factor', 'faculty', 'failure', 'fallacy', 'fame', 'fantasy', 'fare', 'fatigue', 'feat', 'feature', 'feedback', 'fellow', 'fiction', 'figure', 'finance', 'finding', 'flat', 'flock', 'format', 'formula', 'fortune', 'foundation', 'fraction', 'fragment', 'fraud', 'friction', 'frontier', 'fuel', 'function', 'funeral', 'furnace', 'gadget', 'galaxy', 'gallery', 'gang', 'gap', 'garbage', 'garment', 'gear', 'gender', 'gene', 'genius', 'geometry']);
    const adjs = new Set(['durable', 'dynamic', 'economical', 'effective', 'elaborate', 'elderly', 'elegant', 'eligible', 'eminent', 'empirical', 'enclosed', 'energetic', 'enormous', 'enthusiastic', 'erroneous', 'essential', 'eternal', 'ethnic', 'eventual', 'evident', 'exceptional', 'exclusive', 'explicit', 'exquisite', 'extensive', 'external', 'extinct', 'extraordinary', 'extravagant', 'extreme', 'fake', 'fatal', 'federal', 'fertile', 'fierce', 'finite', 'fluid', 'formal', 'fragile', 'frequent', 'fundamental', 'furious', 'further', 'futile', 'general', 'generous', 'genuine']);

    return chunk12.map(w => {
        let pos = '(v)';
        if (nouns.has(w.word)) pos = '(n)';
        else if (adjs.has(w.word)) pos = '(adj)';
        return { ...w, pos };
    });
};
