import { Word } from './types';

export const chunkEasy: Word[] = [
  { id: 'e1', word: 'apple', meaning: 'quả táo', example: 'I eat an apple every morning.', exampleVN: 'Tôi ăn một quả táo mỗi sáng.' },
  { id: 'e2', word: 'bike', meaning: 'xe đạp', example: 'He rides his bike to school.', exampleVN: 'Anh ấy đi xe đạp đến trường.' },
  { id: 'e3', word: 'book', meaning: 'quyển sách', example: 'I like reading this book.', exampleVN: 'Tôi thích đọc cuốn sách này.' },
  { id: 'e4', word: 'bus', meaning: 'xe buýt', example: 'The bus arrives at 8 AM.', exampleVN: 'Xe buýt đến lúc 8 giờ sáng.' },
  { id: 'e5', word: 'car', meaning: 'xe hơi', example: 'My father has a blue car.', exampleVN: 'Bố tôi có một chiếc xe hơi màu xanh.' },
  { id: 'e6', word: 'cat', meaning: 'con mèo', example: 'The cat is sleeping on the sofa.', exampleVN: 'Con mèo đang ngủ trên ghế sofa.' },
  { id: 'e7', word: 'city', meaning: 'thành phố', example: 'Ho Chi Minh City is very big.', exampleVN: 'Thành phố Hồ Chí Minh rất lớn.' },
  { id: 'e8', word: 'cold', meaning: 'lạnh', example: 'It is very cold in winter.', exampleVN: 'Trời rất lạnh vào mùa đông.' },
  { id: 'e9', word: 'coffee', meaning: 'cà phê', example: 'I drink coffee every day.', exampleVN: 'Tôi uống cà phê mỗi ngày.' },
  { id: 'e10', word: 'country', meaning: 'quốc gia, nông thôn', example: 'I love my country.', exampleVN: 'Tôi yêu đất nước mình.' },
  { id: 'e11', word: 'day', meaning: 'ngày', example: 'Today is a beautiful day.', exampleVN: 'Hôm nay là một ngày đẹp trời.' },
  { id: 'e12', word: 'dog', meaning: 'con chó', example: 'My dog is very friendly.', exampleVN: 'Con chó của tôi rất thân thiện.' },
  { id: 'e13', word: 'drink', meaning: 'uống', example: 'Drink more water.', exampleVN: 'Hãy uống nhiều nước hơn.' },
  { id: 'e14', word: 'eat', meaning: 'ăn', example: 'I eat breakfast at 7 AM.', exampleVN: 'Tôi ăn sáng lúc 7 giờ sáng.' },
  { id: 'e15', word: 'family', meaning: 'gia đình', example: 'I live with my family.', exampleVN: 'Tôi sống với gia đình mình.' },
  { id: 'e16', word: 'father', meaning: 'bố', example: 'My father is a teacher.', exampleVN: 'Bố tôi là giáo viên.' },
  { id: 'e17', word: 'fish', meaning: 'con cá', example: 'Goldfish live in water.', exampleVN: 'Cá vàng sống dưới nước.' },
  { id: 'e18', word: 'food', meaning: 'thức ăn', example: 'Vietnamese food is delicious.', exampleVN: 'Thức ăn Việt Nam rất ngon.' },
  { id: 'e19', word: 'friend', meaning: 'bạn bè', example: 'She is my best friend.', exampleVN: 'Cô ấy là bạn thân nhất của tôi.' },
  { id: 'e20', word: 'fruit', meaning: 'trái cây', example: 'Eat more fresh fruit.', exampleVN: 'Hãy ăn thêm trái cây tươi.' },
  { id: 'e21', word: 'girl', meaning: 'cô gái', example: 'The girl is wearing a red hat.', exampleVN: 'Cô gái đang đội một chiếc mũ màu đỏ.' },
  { id: 'e22', word: 'good', meaning: 'tốt', example: 'Have a good day!', exampleVN: 'Chúc một ngày tốt lành!' },
  { id: 'e23', word: 'happy', meaning: 'hạnh phúc', example: 'I am so happy today.', exampleVN: 'Hôm nay tôi rất hạnh phúc.' },
  { id: 'e24', word: 'home', meaning: 'nhà', example: 'I go home after work.', exampleVN: 'Tôi về nhà sau giờ làm việc.' },
  { id: 'e25', word: 'hot', meaning: 'nóng', example: 'The tea is very hot.', exampleVN: 'Trà rất nóng.' },
  { id: 'e26', word: 'house', meaning: 'ngôi nhà', example: 'Their house is big.', exampleVN: 'Ngôi nhà của họ rất lớn.' },
  { id: 'e27', word: 'learn', meaning: 'học', example: 'I want to learn English.', exampleVN: 'Tôi muốn học tiếng Anh.' },
  { id: 'e28', word: 'milk', meaning: 'sữa', example: 'Do you want some milk?', exampleVN: 'Bạn có muốn uống chút sữa không?' },
  { id: 'e29', word: 'money', meaning: 'tiền', example: 'I need some money.', exampleVN: 'Tôi cần một ít tiền.' },
  { id: 'e30', word: 'morning', meaning: 'buổi sáng', example: 'I wake up early in the morning.', exampleVN: 'Tôi thức dậy sớm vào buổi sáng.' },
  { id: 'e31', word: 'mother', meaning: 'mẹ', example: 'My mother is cooking.', exampleVN: 'Mẹ tôi đang nấu ăn.' },
  { id: 'e32', word: 'name', meaning: 'tên', example: 'My name is Bao.', exampleVN: 'Tên tôi là Bảo.' },
  { id: 'e33', word: 'new', meaning: 'mới', example: 'I bought a new phone.', exampleVN: 'Tôi đã mua một chiếc điện thoại mới.' },
  { id: 'e34', word: 'night', meaning: 'ban đêm', example: 'Good night!', exampleVN: 'Chúc ngủ ngon!' },
  { id: 'e35', word: 'old', meaning: 'cũ, già', example: 'This is an old car.', exampleVN: 'Đây là một chiếc xe hơi cũ.' },
  { id: 'e36', word: 'pen', meaning: 'bút mực', example: 'Can I borrow your pen?', exampleVN: 'Tôi có thể mượn bút của bạn không?' },
  { id: 'e37', word: 'phone', meaning: 'điện thoại', example: 'The phone is ringing.', exampleVN: 'Điện thoại đang reo.' },
  { id: 'e38', word: 'price', meaning: 'giá cả', example: 'What is the price of this bag?', exampleVN: 'Giá của chiếc túi này là bao nhiêu?' },
  { id: 'e39', word: 'read', meaning: 'đọc', example: 'I read the news every day.', exampleVN: 'Tôi đọc tin tức mỗi ngày.' },
  { id: 'e40', word: 'rice', meaning: 'gạo, cơm', example: 'Vietnamese people eat rice.', exampleVN: 'Người Việt Nam ăn cơm.' },
  { id: 'e41', word: 'road', meaning: 'con đường', example: 'The road is very busy.', exampleVN: 'Con đường rất đông đúc.' },
  { id: 'e42', word: 'room', meaning: 'phòng', example: 'My room is clean.', exampleVN: 'Phòng của tôi sạch sẽ.' },
  { id: 'e43', word: 'school', meaning: 'trường học', example: 'I go to school at 7:30.', exampleVN: 'Tôi đi học lúc 7:30.' },
  { id: 'e44', word: 'shop', meaning: 'cửa hàng', example: 'I am going to the shop.', exampleVN: 'Tôi đang đi đến cửa hàng.' },
  { id: 'e45', word: 'small', meaning: 'nhỏ', example: 'This box is very small.', exampleVN: 'Chiếc hộp này rất nhỏ.' },
  { id: 'e46', word: 'student', meaning: 'học sinh', example: 'She is a good student.', exampleVN: 'Cô ấy là một học sinh giỏi.' },
  { id: 'e47', word: 'tea', meaning: 'trà', example: 'Do you like green tea?', exampleVN: 'Bạn có thích trà xanh không?' },
  { id: 'e48', word: 'teacher', meaning: 'giáo viên', example: 'The teacher is very kind.', exampleVN: 'Giáo viên rất tử tế.' },
  { id: 'e49', word: 'time', meaning: 'thời gian', example: 'What time is it?', exampleVN: 'Mấy giờ rồi?' },
  { id: 'e50', word: 'today', meaning: 'hôm nay', example: 'Today is Monday.', exampleVN: 'Hôm nay là thứ Hai.' },
  { id: 'e51', word: 'water', meaning: 'nước', example: 'Please give me some water.', exampleVN: 'Vui lòng cho tôi một ít nước.' },
  { id: 'e52', word: 'week', meaning: 'tuần', example: 'There are seven days in a week.', exampleVN: 'Có bảy ngày trong một tuần.' },
  { id: 'e53', word: 'work', meaning: 'làm việc', example: 'I work from 8 AM to 5 PM.', exampleVN: 'Tôi làm việc từ 8 giờ sáng đến 5 giờ chiều.' },
  { id: 'e54', word: 'write', meaning: 'viết', example: 'Write your name here.', exampleVN: 'Viết tên của bạn ở đây.' },
  { id: 'e55', word: 'year', meaning: 'năm', example: 'Happy New Year!', exampleVN: 'Chúc mừng năm mới!' },
  { id: 'e56', word: 'because', meaning: 'vì, bởi vì', example: 'I am late because of the rain.', exampleVN: 'Tôi đến muộn vì trời mưa.' },
  { id: 'e57', word: 'but', meaning: 'nhưng', example: 'I like coffee but I don\'t like tea.', exampleVN: 'Tôi thích cà phê nhưng không thích trà.' },
  { id: 'e58', word: 'so', meaning: 'vì vậy, cho nên', example: 'It was raining, so we stayed home.', exampleVN: 'Trời đang mưa, vì vậy chúng tôi đã ở nhà.' },
  { id: 'e59', word: 'and', meaning: 'và', example: 'I have a pen and a book.', exampleVN: 'Tôi có một chiếc bút và một cuốn sách.' },
  { id: 'e60', word: 'with', meaning: 'với', example: 'I go to school with my friends.', exampleVN: 'Tôi đi học với bạn bè.' },
  { id: 'e61', word: 'without', meaning: 'không có, thiếu', example: 'I cannot live without water.', exampleVN: 'Tôi không thể sống thiếu nước.' },
  { id: 'e62', word: 'between', meaning: 'ở giữa', example: 'The bank is between the shop and the cafe.', exampleVN: 'Ngân hàng ở giữa cửa hàng và quán cà phê.' },
  { id: 'e63', word: 'near', meaning: 'gần', example: 'I live near the station.', exampleVN: 'Tôi sống gần nhà ga.' },
  { id: 'e64', word: 'far', meaning: 'xa', example: 'The airport is very far.', exampleVN: 'Sân bay rất xa.' },
  { id: 'e65', word: 'listen', meaning: 'nghe', example: 'Listen to the music.', exampleVN: 'Nghe nhạc.' },
  { id: 'e66', word: 'speak', meaning: 'nói', example: 'Can you speak English?', exampleVN: 'Bạn có thể nói tiếng Anh không?' },
  { id: 'e67', word: 'walk', meaning: 'đi bộ', example: 'I walk to the park.', exampleVN: 'Tôi đi bộ đến công viên.' },
  { id: 'e68', word: 'run', meaning: 'chạy', example: 'Don\'t run in the house.', exampleVN: 'Đừng chạy trong nhà.' },
  { id: 'e69', word: 'sleep', meaning: 'ngủ', example: 'I sleep 8 hours a night.', exampleVN: 'Tôi ngủ 8 tiếng mỗi đêm.' },
  { id: 'e70', word: 'open', meaning: 'mở', example: 'Please open the door.', exampleVN: 'Vui lòng mở cửa.' },
  { id: 'e71', word: 'close', meaning: 'đóng', example: 'Close the window, please.', exampleVN: 'Làm ơn đóng cửa sổ lại.' },
  { id: 'e72', word: 'buy', meaning: 'mua', example: 'I want to buy some clothes.', exampleVN: 'Tôi muốn mua một ít quần áo.' },
  { id: 'e73', word: 'sell', meaning: 'bán', example: 'They sell fresh bread.', exampleVN: 'Họ bán bánh mì tươi.' },
  { id: 'e74', word: 'give', meaning: 'cho, tặng', example: 'Give me your hand.', exampleVN: 'Đưa tay cho tôi.' },
  { id: 'e75', word: 'take', meaning: 'lấy, cầm, đưa đi', example: 'Take an umbrella with you.', exampleVN: 'Hãy mang theo ô bên mình.' },
  { id: 'e76', word: 'help', meaning: 'giúp đỡ', example: 'Can you help me?', exampleVN: 'Bạn có thể giúp tôi không?' },
  { id: 'e77', word: 'look', meaning: 'nhìn', example: 'Look at that bird!', exampleVN: 'Hãy nhìn con chim kia kìa!' },
  { id: 'e78', word: 'find', meaning: 'tìm thấy', example: 'I can\'t find my keys.', exampleVN: 'Tôi không thể tìm thấy chìa khóa của mình.' },
  { id: 'e79', word: 'lost', meaning: 'mất, lạc', example: 'I lost my wallet.', exampleVN: 'Tôi bị mất ví.' },
  { id: 'e80', word: 'see', meaning: 'nhìn thấy', example: 'I see a rainbow.', exampleVN: 'Tôi thấy cầu vồng.' },
  { id: 'e81', word: 'hear', meaning: 'nghe thấy', example: 'Can you hear the noise?', exampleVN: 'Bạn có nghe thấy tiếng ồn không?' },
  { id: 'e82', word: 'understand', meaning: 'hiểu', example: 'I don\'t understand this question.', exampleVN: 'Tôi không hiểu câu hỏi này.' },
  { id: 'e83', word: 'think', meaning: 'suy nghĩ', example: 'What do you think?', exampleVN: 'Bạn nghĩ sao?' },
  { id: 'e84', word: 'know', meaning: 'biết', example: 'I know the answer.', exampleVN: 'Tôi biết câu trả lời.' },
  { id: 'e85', word: 'believe', meaning: 'tin tưởng', example: 'I believe you.', exampleVN: 'Tôi tin bạn.' },
  { id: 'e86', word: 'remember', meaning: 'nhớ', example: 'Do you remember me?', exampleVN: 'Bạn có nhớ tôi không?' },
  { id: 'e87', word: 'forget', meaning: 'quên', example: 'Don\'t forget your bag.', exampleVN: 'Đừng quên túi xách của bạn.' },
  { id: 'e88', word: 'need', meaning: 'cần', example: 'I need some help.', exampleVN: 'Tôi cần một chút giúp đỡ.' },
  { id: 'e89', word: 'want', meaning: 'muốn', example: 'I want an ice cream.', exampleVN: 'Tôi muốn một cây kem.' },
  { id: 'e90', word: 'like', meaning: 'thích', example: 'I like this music.', exampleVN: 'Tôi thích bản nhạc này.' },
  { id: 'e91', word: 'love', meaning: 'yêu', example: 'I love my family.', exampleVN: 'Tôi yêu gia đình mình.' },
  { id: 'e92', word: 'hate', meaning: 'ghét', example: 'I hate spiders.', exampleVN: 'Tôi ghét nhện.' },
  { id: 'e93', word: 'fast', meaning: 'nhanh', example: 'He is a fast runner.', exampleVN: 'Anh ấy là một người chạy nhanh.' },
  { id: 'e94', word: 'slow', meaning: 'chậm', example: 'The turtle is very slow.', exampleVN: 'Con rùa rất chậm.' },
  { id: 'e95', word: 'heavy', meaning: 'nặng', example: 'This box is too heavy.', exampleVN: 'Chiếc hộp này quá nặng.' },
  { id: 'e96', word: 'light', meaning: 'nhẹ, ánh sáng', example: 'The bag is very light.', exampleVN: 'Chiếc túi rất nhẹ.' },
  { id: 'e97', word: 'easy', meaning: 'dễ dàng', example: 'The test was easy.', exampleVN: 'Bài kiểm tra thật dễ.' },
  { id: 'e98', word: 'hard', meaning: 'khó khăn, cứng', example: 'Life can be hard.', exampleVN: 'Cuộc sống có thể khó khăn.' },
  { id: 'e99', word: 'rich', meaning: 'giàu có', example: 'He is a rich businessman.', exampleVN: 'Anh ấy là một doanh nhân giàu có.' },
  { id: 'e100', word: 'poor', meaning: 'nghèo', example: 'We should help poor people.', exampleVN: 'Chúng ta nên giúp đỡ những người nghèo.' },
  { id: 'e101', word: 'clean', meaning: 'sạch sẽ', example: 'Your hands are clean.', exampleVN: 'Tay bạn sạch sẽ.' },
  { id: 'e102', word: 'dirty', meaning: 'bẩn', example: 'The floor is dirty.', exampleVN: 'Sàn nhà bị bẩn.' },
  { id: 'e103', word: 'cheap', meaning: 'rẻ', example: 'The tickets are very cheap.', exampleVN: 'Vé rất rẻ.' },
  { id: 'e104', word: 'expensive', meaning: 'đắt tiền', example: 'That car is too expensive.', exampleVN: 'Chiếc xe đó quá đắt.' },
  { id: 'e105', word: 'hungry', meaning: 'đói', example: 'I am so hungry.', exampleVN: 'Tôi đói quá.' },
  { id: 'e106', word: 'thirsty', meaning: 'khát', example: 'I am thirsty after running.', exampleVN: 'Tôi khát sau khi chạy.' },
  { id: 'e107', word: 'tired', meaning: 'mệt mỏi', example: 'I am tired after work.', exampleVN: 'Tôi mệt mỏi sau khi làm việc.' },
  { id: 'e108', word: 'angry', meaning: 'tức giận', example: 'Don\'t be angry with me.', exampleVN: 'Đừng giận tôi nhé.' },
  { id: 'e109', word: 'sad', meaning: 'buồn', example: 'The movie was very sad.', exampleVN: 'Bộ phim rất buồn.' },
  { id: 'e110', word: 'beautiful', meaning: 'đẹp', example: 'She is a beautiful girl.', exampleVN: 'Cô ấy là một cô gái xinh đẹp.' },
  { id: 'e111', word: 'both', meaning: 'cả hai', example: 'I like both of them.', exampleVN: 'Tôi thích cả hai người họ.' },
  { id: 'e112', word: 'between', meaning: 'ở giữa (2 vật/người)', example: 'Sit between your parents.', exampleVN: 'Hãy ngồi giữa bố mẹ con.' },
  { id: 'e113', word: 'fall', meaning: 'ngã, rơi, mùa thu', example: 'Be careful, don\'t fall.', exampleVN: 'Cẩn thận, đừng để ngã.' },
  { id: 'e114', word: 'leave', meaning: 'rời đi, bỏ lại', example: 'I leave for work at 8.', exampleVN: 'Tôi đi làm lúc 8 giờ.' },
  { id: 'e115', word: 'tomorrow', meaning: 'ngày mai', example: 'See you tomorrow!', exampleVN: 'Hẹn gặp lại vào ngày mai!' },
  { id: 'e116', word: 'yesterday', meaning: 'ngày hôm qua', example: 'I saw him yesterday.', exampleVN: 'Tôi đã thấy anh ấy ngày hôm qua.' },
  { id: 'e117', word: 'early', meaning: 'sớm', example: 'I woke up early.', exampleVN: 'Tôi đã thức dậy sớm.' },
  { id: 'e118', word: 'late', meaning: 'muộn', example: 'Don\'t be late for class.', exampleVN: 'Đừng đi học muộn.' },
  { id: 'e119', word: 'long', meaning: 'dài', example: 'She has long hair.', exampleVN: 'Cô ấy có mái tóc dài.' },
  { id: 'e120', word: 'short', meaning: 'ngắn, thấp', example: 'He is short but strong.', exampleVN: 'Anh ấy thấp nhưng khỏe.' },
  { id: 'e121', word: 'office', meaning: 'văn phòng', example: 'I work in an office.', exampleVN: 'Tôi làm việc ở văn phòng.' },
  { id: 'e122', word: 'meeting', meaning: 'cuộc họp', example: 'We have a meeting at 10.', exampleVN: 'Chúng tôi có cuộc họp lúc 10 giờ.' },
  { id: 'e123', word: 'job', meaning: 'công việc', example: 'He got a new job.', exampleVN: 'Anh ấy có công việc mới.' },
  { id: 'e124', word: 'boss', meaning: 'sếp', example: 'My boss is very nice.', exampleVN: 'Sếp của tôi rất tốt.' },
  { id: 'e125', word: 'email', meaning: 'thư điện tử', example: 'Please send me an email.', exampleVN: 'Hãy gửi email cho tôi.' },
  { id: 'e126', word: 'table', meaning: 'bàn', example: 'Put it on the table.', exampleVN: 'Đặt nó lên bàn.' },
  { id: 'e127', word: 'chair', meaning: 'ghế', example: 'Sit on the chair.', exampleVN: 'Ngồi lên ghế.' },
  { id: 'e128', word: 'door', meaning: 'cửa', example: 'Please close the door.', exampleVN: 'Làm ơn đóng cửa.' },
  { id: 'e129', word: 'window', meaning: 'cửa sổ', example: 'Open the window.', exampleVN: 'Mở cửa sổ.' },
  { id: 'e130', word: 'computer', meaning: 'máy tính', example: 'I use a computer every day.', exampleVN: 'Tôi dùng máy tính mỗi ngày.' },
  { id: 'e131', word: 'question', meaning: 'câu hỏi', example: 'Do you have a question?', exampleVN: 'Bạn có câu hỏi nào không?' },
  { id: 'e132', word: 'answer', meaning: 'câu trả lời', example: 'I know the answer.', exampleVN: 'Tôi biết câu trả lời.' },
  { id: 'e133', word: 'problem', meaning: 'vấn đề', example: 'There is a problem.', exampleVN: 'Có một vấn đề.' },
  { id: 'e134', word: 'start', meaning: 'bắt đầu', example: 'Let us start now.', exampleVN: 'Hãy bắt đầu ngay.' },
  { id: 'e135', word: 'stop', meaning: 'dừng lại', example: 'Stop the car.', exampleVN: 'Dừng xe lại.' },
  { id: 'e136', word: 'finish', meaning: 'kết thúc', example: 'I will finish soon.', exampleVN: 'Tôi sẽ hoàn thành sớm.' },
  { id: 'e137', word: 'wait', meaning: 'chờ đợi', example: 'Wait for me.', exampleVN: 'Chờ tôi với.' },
  { id: 'e138', word: 'come', meaning: 'đến', example: 'Come here please.', exampleVN: 'Đến đây.' },
  { id: 'e139', word: 'go', meaning: 'đi', example: 'I go to work by bus.', exampleVN: 'Tôi đi làm bằng xe buýt.' },
  { id: 'e140', word: 'play', meaning: 'chơi', example: 'Children love to play.', exampleVN: 'Trẻ em thích chơi.' },
  { id: 'e141', word: 'watch', meaning: 'xem, đồng hồ', example: 'I watch TV at night.', exampleVN: 'Tôi xem TV vào buổi tối.' },
  { id: 'e142', word: 'use', meaning: 'sử dụng', example: 'How do you use this?', exampleVN: 'Bạn sử dụng cái này thế nào?' },
  { id: 'e143', word: 'pay', meaning: 'trả tiền', example: 'I will pay by card.', exampleVN: 'Tôi sẽ trả bằng thẻ.' },
  { id: 'e144', word: 'change', meaning: 'thay đổi, tiền thối', example: 'Keep the change.', exampleVN: 'Giữ lại tiền thối.' },
  { id: 'e145', word: 'order', meaning: 'đặt hàng, thứ tự', example: 'I want to order food.', exampleVN: 'Tôi muốn đặt đồ ăn.' },
  { id: 'e146', word: 'number', meaning: 'số', example: 'What is your phone number?', exampleVN: 'Số điện thoại của bạn là gì?' },
  { id: 'e147', word: 'letter', meaning: 'lá thư, chữ cái', example: 'I got a letter today.', exampleVN: 'Tôi nhận được một lá thư hôm nay.' },
  { id: 'e148', word: 'map', meaning: 'bản đồ', example: 'Look at the map.', exampleVN: 'Nhìn vào bản đồ.' },
  { id: 'e149', word: 'ticket', meaning: 'vé', example: 'Buy a train ticket.', exampleVN: 'Mua vé tàu.' },
  { id: 'e150', word: 'weather', meaning: 'thời tiết', example: 'The weather is nice today.', exampleVN: 'Thời tiết hôm nay đẹp.' },
  { id: 'e151', word: 'color', meaning: 'màu sắc', example: 'What color do you like?', exampleVN: 'Bạn thích màu gì?' },
  { id: 'e152', word: 'picture', meaning: 'hình ảnh, bức tranh', example: 'Look at this picture.', exampleVN: 'Nhìn bức tranh này.' },
  { id: 'e153', word: 'bag', meaning: 'túi, cặp', example: 'Put it in the bag.', exampleVN: 'Bỏ nó vào túi.' },
  { id: 'e154', word: 'key', meaning: 'chìa khóa', example: 'Where is my key?', exampleVN: 'Chìa khóa của tôi đâu?' },
  { id: 'e155', word: 'street', meaning: 'đường phố', example: 'Cross the street carefully.', exampleVN: 'Băng qua đường cẩn thận.' },
  { id: 'e156', word: 'store', meaning: 'cửa hàng', example: 'The store opens at 9 AM.', exampleVN: 'Cửa hàng mở lúc 9 giờ sáng.' },
  { id: 'e157', word: 'bank', meaning: 'ngân hàng', example: 'I go to the bank.', exampleVN: 'Tôi đi đến ngân hàng.' },
  { id: 'e158', word: 'hospital', meaning: 'bệnh viện', example: 'He is in the hospital.', exampleVN: 'Anh ấy ở trong bệnh viện.' },
  { id: 'e159', word: 'park', meaning: 'công viên', example: 'We play in the park.', exampleVN: 'Chúng tôi chơi trong công viên.' },
  { id: 'e160', word: 'train', meaning: 'tàu hỏa', example: 'Take the train to Hanoi.', exampleVN: 'Đi tàu đến Hà Nội.' },
  { id: 'e161', word: 'plane', meaning: 'máy bay', example: 'The plane is late.', exampleVN: 'Máy bay bị trễ.' },
  { id: 'e162', word: 'airport', meaning: 'sân bay', example: 'Go to the airport early.', exampleVN: 'Đến sân bay sớm.' },
  { id: 'e163', word: 'hotel', meaning: 'khách sạn', example: 'We stay at a hotel.', exampleVN: 'Chúng tôi ở khách sạn.' },
  { id: 'e164', word: 'restaurant', meaning: 'nhà hàng', example: 'Let us eat at a restaurant.', exampleVN: 'Hãy ăn ở nhà hàng.' },
  { id: 'e165', word: 'movie', meaning: 'phim', example: 'I saw a good movie.', exampleVN: 'Tôi đã xem một bộ phim hay.' },
  { id: 'e166', word: 'music', meaning: 'âm nhạc', example: 'I love music.', exampleVN: 'Tôi yêu âm nhạc.' },
  { id: 'e167', word: 'sport', meaning: 'thể thao', example: 'My favorite sport is soccer.', exampleVN: 'Môn thể thao yêu thích của tôi là bóng đá.' },
  { id: 'e168', word: 'birthday', meaning: 'sinh nhật', example: 'Happy birthday!', exampleVN: 'Chúc mừng sinh nhật!' },
  { id: 'e169', word: 'holiday', meaning: 'ngày lễ, kỳ nghỉ', example: 'We go on holiday next week.', exampleVN: 'Chúng tôi đi nghỉ tuần sau.' },
  { id: 'e170', word: 'clothes', meaning: 'quần áo', example: 'Buy new clothes.', exampleVN: 'Mua quần áo mới.' },
  { id: 'e171', word: 'shoe', meaning: 'giày', example: 'I need new shoes.', exampleVN: 'Tôi cần giày mới.' },
  { id: 'e172', word: 'clock', meaning: 'đồng hồ treo tường', example: 'Look at the clock.', exampleVN: 'Nhìn đồng hồ.' },
  { id: 'e173', word: 'drive', meaning: 'lái xe', example: 'Can you drive a car?', exampleVN: 'Bạn có lái xe được không?' },
  { id: 'e174', word: 'turn', meaning: 'rẽ, lượt', example: 'Turn left at the corner.', exampleVN: 'Rẽ trái ở góc đường.' },
  { id: 'e175', word: 'send', meaning: 'gửi', example: 'Send me a message.', exampleVN: 'Gửi cho tôi một tin nhắn.' },
  { id: 'e176', word: 'receive', meaning: 'nhận', example: 'I received your letter.', exampleVN: 'Tôi đã nhận được thư của bạn.' },
  { id: 'e177', word: 'call', meaning: 'gọi điện', example: 'Call me later.', exampleVN: 'Gọi cho tôi sau nhé.' },
  { id: 'e178', word: 'try', meaning: 'thử', example: 'Try this food.', exampleVN: 'Thử món ăn này.' },
  { id: 'e179', word: 'ask', meaning: 'hỏi', example: 'Ask the teacher.', exampleVN: 'Hỏi giáo viên.' },
  { id: 'e180', word: 'tell', meaning: 'kể, nói', example: 'Tell me a story.', exampleVN: 'Kể cho tôi một câu chuyện.' },
  { id: 'e181', word: 'show', meaning: 'cho xem', example: 'Show me the way.', exampleVN: 'Chỉ đường cho tôi.' },
  { id: 'e182', word: 'bring', meaning: 'mang đến', example: 'Bring your book.', exampleVN: 'Mang sách đến.' },
  { id: 'e183', word: 'carry', meaning: 'mang, xách', example: 'Carry this box.', exampleVN: 'Xách cái hộp này.' },
  { id: 'e184', word: 'move', meaning: 'di chuyển', example: 'Move to a new house.', exampleVN: 'Chuyển đến nhà mới.' },
  { id: 'e185', word: 'build', meaning: 'xây dựng', example: 'Build a new road.', exampleVN: 'Xây một con đường mới.' },
  { id: 'e186', word: 'fix', meaning: 'sửa chữa', example: 'Fix the broken chair.', exampleVN: 'Sửa cái ghế hỏng.' },
  { id: 'e187', word: 'break', meaning: 'vỡ, phá vỡ', example: 'Do not break the glass.', exampleVN: 'Đừng làm vỡ cái ly.' },
  { id: 'e188', word: 'cut', meaning: 'cắt', example: 'Cut the paper.', exampleVN: 'Cắt giấy.' },
  { id: 'e189', word: 'wash', meaning: 'rửa, giặt', example: 'Wash your hands.', exampleVN: 'Rửa tay đi.' },
  { id: 'e190', word: 'cook', meaning: 'nấu ăn', example: 'She can cook well.', exampleVN: 'Cô ấy nấu ăn giỏi.' },
  { id: 'e191', word: 'clean', meaning: 'dọn dẹp', example: 'Clean the kitchen.', exampleVN: 'Dọn dẹp nhà bếp.' },
  { id: 'e192', word: 'check', meaning: 'kiểm tra', example: 'Check your email.', exampleVN: 'Kiểm tra email của bạn.' },
  { id: 'e193', word: 'choose', meaning: 'chọn', example: 'Choose one color.', exampleVN: 'Chọn một màu.' },
  { id: 'e194', word: 'wrong', meaning: 'sai', example: 'That answer is wrong.', exampleVN: 'Câu trả lời đó sai.' },
  { id: 'e195', word: 'right', meaning: 'đúng, phải', example: 'You are right.', exampleVN: 'Bạn đúng rồi.' },
  { id: 'e196', word: 'young', meaning: 'trẻ', example: 'He is still young.', exampleVN: 'Anh ấy vẫn còn trẻ.' },
  { id: 'e197', word: 'tall', meaning: 'cao', example: 'She is very tall.', exampleVN: 'Cô ấy rất cao.' },
  { id: 'e198', word: 'big', meaning: 'lớn', example: 'A big house.', exampleVN: 'Một ngôi nhà lớn.' },
  { id: 'e199', word: 'safe', meaning: 'an toàn', example: 'Is it safe here?', exampleVN: 'Ở đây có an toàn không?' },
  { id: 'e200', word: 'free', meaning: 'miễn phí, tự do', example: 'The ticket is free.', exampleVN: 'Vé miễn phí.' },
  { id: 'e201', word: 'ready', meaning: 'sẵn sàng', example: 'Are you ready?', exampleVN: 'Bạn sẵn sàng chưa?' },
  { id: 'e202', word: 'busy', meaning: 'bận', example: 'I am very busy today.', exampleVN: 'Hôm nay tôi rất bận.' },
  { id: 'e203', word: 'quiet', meaning: 'yên tĩnh', example: 'Please be quiet.', exampleVN: 'Xin hãy yên lặng.' },
  { id: 'e204', word: 'loud', meaning: 'ồn ào', example: 'The music is too loud.', exampleVN: 'Nhạc quá ồn.' },
  { id: 'e205', word: 'full', meaning: 'đầy', example: 'The bus is full.', exampleVN: 'Xe buýt đầy rồi.' },
  { id: 'e206', word: 'empty', meaning: 'trống', example: 'The room is empty.', exampleVN: 'Phòng trống.' },
  { id: 'e207', word: 'true', meaning: 'đúng, thật', example: 'Is that true?', exampleVN: 'Điều đó có thật không?' },
  { id: 'e208', word: 'false', meaning: 'sai, giả', example: 'The information is false.', exampleVN: 'Thông tin đó sai.' },
  { id: 'e209', word: 'important', meaning: 'quan trọng', example: 'This is very important.', exampleVN: 'Điều này rất quan trọng.' },
  { id: 'e210', word: 'simple', meaning: 'đơn giản', example: 'It is a simple question.', exampleVN: 'Đó là một câu hỏi đơn giản.' },
  { id: 'e211', word: 'nice', meaning: 'tốt đẹp', example: 'Have a nice day.', exampleVN: 'Chúc một ngày tốt lành.' },
  { id: 'e212', word: 'welcome', meaning: 'chào mừng', example: 'Welcome to Vietnam!', exampleVN: 'Chào mừng đến Việt Nam!' },
  { id: 'e213', word: 'sorry', meaning: 'xin lỗi', example: 'I am sorry for being late.', exampleVN: 'Tôi xin lỗi vì đến muộn.' },
  { id: 'e214', word: 'thank', meaning: 'cảm ơn', example: 'Thank you very much.', exampleVN: 'Cảm ơn bạn rất nhiều.' },
  { id: 'e215', word: 'please', meaning: 'xin vui lòng', example: 'Please sit down.', exampleVN: 'Xin hãy ngồi xuống.' },
  { id: 'e216', word: 'enough', meaning: 'đủ', example: 'That is enough.', exampleVN: 'Đủ rồi.' },
  { id: 'e217', word: 'many', meaning: 'nhiều', example: 'There are many people.', exampleVN: 'Có nhiều người.' },
  { id: 'e218', word: 'few', meaning: 'ít', example: 'Only a few left.', exampleVN: 'Chỉ còn lại ít thôi.' },
  { id: 'e219', word: 'every', meaning: 'mỗi', example: 'I exercise every day.', exampleVN: 'Tôi tập thể dục mỗi ngày.' },
  { id: 'e220', word: 'always', meaning: 'luôn luôn', example: 'She is always on time.', exampleVN: 'Cô ấy luôn đúng giờ.' },
  { id: 'e221', word: 'never', meaning: 'không bao giờ', example: 'I never eat meat.', exampleVN: 'Tôi không bao giờ ăn thịt.' },
  { id: 'e222', word: 'often', meaning: 'thường xuyên', example: 'I often go swimming.', exampleVN: 'Tôi thường đi bơi.' },
  { id: 'e223', word: 'sometimes', meaning: 'thỉnh thoảng', example: 'Sometimes I feel tired.', exampleVN: 'Thỉnh thoảng tôi cảm thấy mệt.' },
  { id: 'e224', word: 'already', meaning: 'đã rồi', example: 'I already finished.', exampleVN: 'Tôi đã hoàn thành rồi.' },
  { id: 'e225', word: 'again', meaning: 'lại', example: 'Say it again.', exampleVN: 'Nói lại lần nữa.' },
  { id: 'e226', word: 'still', meaning: 'vẫn', example: 'He is still working.', exampleVN: 'Anh ấy vẫn đang làm việc.' },
  { id: 'e227', word: 'together', meaning: 'cùng nhau', example: 'Let us work together.', exampleVN: 'Hãy làm việc cùng nhau.' },
  { id: 'e228', word: 'alone', meaning: 'một mình', example: 'She lives alone.', exampleVN: 'Cô ấy sống một mình.' },
  { id: 'e229', word: 'inside', meaning: 'bên trong', example: 'Come inside.', exampleVN: 'Vào bên trong.' },
  { id: 'e230', word: 'outside', meaning: 'bên ngoài', example: 'Wait outside.', exampleVN: 'Chờ bên ngoài.' },
  { id: 'e231', word: 'above', meaning: 'phía trên', example: 'The light is above the table.', exampleVN: 'Đèn ở phía trên bàn.' },
  { id: 'e232', word: 'below', meaning: 'phía dưới', example: 'Sign below the line.', exampleVN: 'Ký phía dưới đường kẻ.' },
  { id: 'e233', word: 'behind', meaning: 'phía sau', example: 'The garden is behind the house.', exampleVN: 'Vườn ở phía sau nhà.' },
  { id: 'e234', word: 'next', meaning: 'tiếp theo, bên cạnh', example: 'The next bus comes at 3.', exampleVN: 'Xe buýt tiếp theo đến lúc 3 giờ.' },
  { id: 'e235', word: 'last', meaning: 'cuối cùng, trước', example: 'I saw her last week.', exampleVN: 'Tôi gặp cô ấy tuần trước.' },
  { id: 'e236', word: 'first', meaning: 'đầu tiên', example: 'This is my first time.', exampleVN: 'Đây là lần đầu tiên.' },
  { id: 'e237', word: 'second', meaning: 'thứ hai', example: 'Wait a second.', exampleVN: 'Đợi một chút.' },
  { id: 'e238', word: 'half', meaning: 'một nửa', example: 'Give me half.', exampleVN: 'Cho tôi một nửa.' },
  { id: 'e239', word: 'kind', meaning: 'tử tế, loại', example: 'She is very kind.', exampleVN: 'Cô ấy rất tử tế.' },
  { id: 'e240', word: 'sick', meaning: 'bệnh, ốm', example: 'I feel sick today.', exampleVN: 'Hôm nay tôi cảm thấy ốm.' },
  { id: 'e241', word: 'medicine', meaning: 'thuốc', example: 'Take your medicine.', exampleVN: 'Uống thuốc đi.' },
  { id: 'e242', word: 'doctor', meaning: 'bác sĩ', example: 'See a doctor.', exampleVN: 'Đi gặp bác sĩ.' },
  { id: 'e243', word: 'sign', meaning: 'ký tên, biển báo', example: 'Sign here please.', exampleVN: 'Ký tên ở đây.' },
  { id: 'e244', word: 'form', meaning: 'mẫu đơn, hình thức', example: 'Fill out this form.', exampleVN: 'Điền vào mẫu đơn này.' },
  { id: 'e245', word: 'copy', meaning: 'bản sao', example: 'Make a copy.', exampleVN: 'Sao chép.' },
  { id: 'e246', word: 'page', meaning: 'trang', example: 'Turn to page 5.', exampleVN: 'Mở đến trang 5.' },
  { id: 'e247', word: 'note', meaning: 'ghi chú', example: 'Take notes in class.', exampleVN: 'Ghi chú trong lớp.' },
  { id: 'e248', word: 'list', meaning: 'danh sách', example: 'Make a shopping list.', exampleVN: 'Lập danh sách mua sắm.' },
  { id: 'e249', word: 'report', meaning: 'báo cáo', example: 'Write a report.', exampleVN: 'Viết một bản báo cáo.' },
  { id: 'e250', word: 'test', meaning: 'bài kiểm tra', example: 'Study for the test.', exampleVN: 'Ôn bài cho bài kiểm tra.' },
  { id: 'e251', word: 'class', meaning: 'lớp học', example: 'English class starts at 9.', exampleVN: 'Lớp tiếng Anh bắt đầu lúc 9 giờ.' },
  { id: 'e252', word: 'practice', meaning: 'luyện tập', example: 'Practice makes perfect.', exampleVN: 'Luyện tập tạo nên sự hoàn hảo.' },
  { id: 'e253', word: 'example', meaning: 'ví dụ', example: 'Give me an example.', exampleVN: 'Cho tôi một ví dụ.' },
  { id: 'e254', word: 'lesson', meaning: 'bài học', example: 'Today is lesson 5.', exampleVN: 'Hôm nay là bài 5.' },
  { id: 'e255', word: 'word', meaning: 'từ vựng', example: 'Learn new words.', exampleVN: 'Học từ mới.' },
  { id: 'e256', word: 'sentence', meaning: 'câu', example: 'Write a sentence.', exampleVN: 'Viết một câu.' },
  { id: 'e257', word: 'mean', meaning: 'có nghĩa là', example: 'What does this word mean?', exampleVN: 'Từ này có nghĩa là gì?' },
  { id: 'e258', word: 'wrong', meaning: 'sai', example: 'You are wrong.', exampleVN: 'Bạn sai rồi.' },
  { id: 'e259', word: 'correct', meaning: 'đúng', example: 'The correct answer is B.', exampleVN: 'Đáp án đúng là B.' },
  { id: 'e260', word: 'pass', meaning: 'đậu, đi qua', example: 'I passed the exam.', exampleVN: 'Tôi đã đậu kỳ thi.' },
  { id: 'e261', word: 'fail', meaning: 'trượt, thất bại', example: 'Do not fail the test.', exampleVN: 'Đừng trượt bài kiểm tra.' },
  { id: 'e262', word: 'piece', meaning: 'miếng, mẩu', example: 'A piece of cake.', exampleVN: 'Một miếng bánh.' },
  { id: 'e263', word: 'part', meaning: 'phần', example: 'This is part of the plan.', exampleVN: 'Đây là một phần của kế hoạch.' },
  { id: 'e264', word: 'side', meaning: 'bên, phía', example: 'On the left side.', exampleVN: 'Ở bên trái.' },
  { id: 'e265', word: 'end', meaning: 'cuối, kết thúc', example: 'At the end of the road.', exampleVN: 'Ở cuối con đường.' },
  { id: 'e266', word: 'middle', meaning: 'ở giữa', example: 'Stand in the middle.', exampleVN: 'Đứng ở giữa.' },
  { id: 'e267', word: 'corner', meaning: 'góc', example: 'At the corner of the street.', exampleVN: 'Ở góc đường.' },
  { id: 'e268', word: 'floor', meaning: 'sàn nhà, tầng', example: 'Sit on the floor.', exampleVN: 'Ngồi trên sàn.' },
  { id: 'e269', word: 'wall', meaning: 'tường', example: 'A picture on the wall.', exampleVN: 'Một bức tranh trên tường.' },
  { id: 'e270', word: 'garden', meaning: 'vườn', example: 'She has a beautiful garden.', exampleVN: 'Cô ấy có một khu vườn đẹp.' },
  { id: 'e271', word: 'tree', meaning: 'cây', example: 'A big tree in the park.', exampleVN: 'Một cái cây lớn trong công viên.' },
  { id: 'e272', word: 'flower', meaning: 'hoa', example: 'Buy some flowers.', exampleVN: 'Mua vài bông hoa.' },
  { id: 'e273', word: 'river', meaning: 'sông', example: 'The river is long.', exampleVN: 'Con sông rất dài.' },
  { id: 'e274', word: 'mountain', meaning: 'núi', example: 'Climb the mountain.', exampleVN: 'Leo núi.' },
  { id: 'e275', word: 'sea', meaning: 'biển', example: 'I like the sea.', exampleVN: 'Tôi thích biển.' },
  { id: 'e276', word: 'sun', meaning: 'mặt trời', example: 'The sun is shining.', exampleVN: 'Mặt trời đang tỏa sáng.' },
  { id: 'e277', word: 'rain', meaning: 'mưa', example: 'It is going to rain.', exampleVN: 'Trời sắp mưa.' },
  { id: 'e278', word: 'wind', meaning: 'gió', example: 'The wind is strong.', exampleVN: 'Gió rất mạnh.' },
  { id: 'e279', word: 'animal', meaning: 'con vật', example: 'I like animals.', exampleVN: 'Tôi thích động vật.' },
  { id: 'e280', word: 'hand', meaning: 'bàn tay', example: 'Raise your hand.', exampleVN: 'Giơ tay lên.' },
  { id: 'e281', word: 'head', meaning: 'đầu', example: 'My head hurts.', exampleVN: 'Đầu tôi đau.' },
  { id: 'e282', word: 'eye', meaning: 'mắt', example: 'Close your eyes.', exampleVN: 'Nhắm mắt lại.' },
  { id: 'e283', word: 'face', meaning: 'khuôn mặt', example: 'Wash your face.', exampleVN: 'Rửa mặt.' },
  { id: 'e284', word: 'body', meaning: 'cơ thể', example: 'Exercise is good for your body.', exampleVN: 'Tập thể dục tốt cho cơ thể.' },
  { id: 'e285', word: 'mouth', meaning: 'miệng', example: 'Open your mouth.', exampleVN: 'Mở miệng ra.' },
  { id: 'e286', word: 'heart', meaning: 'trái tim', example: 'Follow your heart.', exampleVN: 'Hãy đi theo trái tim.' },
  { id: 'e287', word: 'smile', meaning: 'nụ cười', example: 'She has a nice smile.', exampleVN: 'Cô ấy có nụ cười đẹp.' },
  { id: 'e288', word: 'cry', meaning: 'khóc', example: 'Do not cry.', exampleVN: 'Đừng khóc.' },
  { id: 'e289', word: 'laugh', meaning: 'cười', example: 'He makes me laugh.', exampleVN: 'Anh ấy làm tôi cười.' },
  { id: 'e290', word: 'dream', meaning: 'giấc mơ', example: 'Follow your dream.', exampleVN: 'Hãy theo đuổi giấc mơ.' },
  { id: 'e291', word: 'hour', meaning: 'giờ', example: 'Wait one hour.', exampleVN: 'Chờ một giờ.' },
  { id: 'e292', word: 'minute', meaning: 'phút', example: 'Five more minutes.', exampleVN: 'Thêm năm phút nữa.' },
  { id: 'e293', word: 'month', meaning: 'tháng', example: 'Next month.', exampleVN: 'Tháng sau.' },
  { id: 'e294', word: 'spring', meaning: 'mùa xuân', example: 'Spring is beautiful.', exampleVN: 'Mùa xuân thật đẹp.' },
  { id: 'e295', word: 'summer', meaning: 'mùa hè', example: 'I love summer.', exampleVN: 'Tôi yêu mùa hè.' },
  { id: 'e296', word: 'winter', meaning: 'mùa đông', example: 'Winter is cold.', exampleVN: 'Mùa đông lạnh.' },
  { id: 'e297', word: 'brother', meaning: 'anh/em trai', example: 'My brother is tall.', exampleVN: 'Anh trai tôi cao.' },
  { id: 'e298', word: 'sister', meaning: 'chị/em gái', example: 'My sister is kind.', exampleVN: 'Chị gái tôi tốt bụng.' },
  { id: 'e299', word: 'son', meaning: 'con trai', example: 'He has one son.', exampleVN: 'Anh ấy có một con trai.' },
  { id: 'e300', word: 'daughter', meaning: 'con gái', example: 'She has two daughters.', exampleVN: 'Cô ấy có hai con gái.' },
  { id: 'e301', word: 'husband', meaning: 'chồng', example: 'Her husband works at a bank.', exampleVN: 'Chồng cô ấy làm ở ngân hàng.' },
  { id: 'e302', word: 'wife', meaning: 'vợ', example: 'His wife is a nurse.', exampleVN: 'Vợ anh ấy là y tá.' },
  { id: 'e303', word: 'child', meaning: 'trẻ em', example: 'The child is playing.', exampleVN: 'Đứa trẻ đang chơi.' },
  { id: 'e304', word: 'people', meaning: 'mọi người', example: 'Many people are here.', exampleVN: 'Nhiều người ở đây.' },
  { id: 'e305', word: 'woman', meaning: 'phụ nữ', example: 'The woman is reading.', exampleVN: 'Người phụ nữ đang đọc sách.' },
  { id: 'e306', word: 'man', meaning: 'đàn ông', example: 'The man is standing.', exampleVN: 'Người đàn ông đang đứng.' },
  { id: 'e307', word: 'boy', meaning: 'con trai', example: 'The boy is running.', exampleVN: 'Cậu bé đang chạy.' },
  { id: 'e308', word: 'wear', meaning: 'mặc', example: 'She wears a hat.', exampleVN: 'Cô ấy đội nón.' },
  { id: 'e309', word: 'sit', meaning: 'ngồi', example: 'Please sit down.', exampleVN: 'Xin hãy ngồi xuống.' },
  { id: 'e310', word: 'stand', meaning: 'đứng', example: 'Stand up please.', exampleVN: 'Xin hãy đứng dậy.' },
  { id: 'e311', word: 'put', meaning: 'đặt, để', example: 'Put the book on the table.', exampleVN: 'Đặt sách lên bàn.' },
  { id: 'e312', word: 'hold', meaning: 'cầm, giữ', example: 'Hold my hand.', exampleVN: 'Nắm tay tôi.' },
  { id: 'e313', word: 'pick', meaning: 'chọn, nhặt', example: 'Pick a number.', exampleVN: 'Chọn một số.' },
  { id: 'e314', word: 'push', meaning: 'đẩy', example: 'Push the door.', exampleVN: 'Đẩy cửa.' },
  { id: 'e315', word: 'pull', meaning: 'kéo', example: 'Pull the handle.', exampleVN: 'Kéo tay cầm.' },
  { id: 'e316', word: 'keep', meaning: 'giữ', example: 'Keep the receipt.', exampleVN: 'Giữ hóa đơn lại.' },
  { id: 'e317', word: 'return', meaning: 'trả lại, quay lại', example: 'Return the book to the library.', exampleVN: 'Trả sách cho thư viện.' },
  { id: 'e318', word: 'lend', meaning: 'cho mượn', example: 'Lend me your pen.', exampleVN: 'Cho tôi mượn bút.' },
  { id: 'e319', word: 'borrow', meaning: 'mượn', example: 'Can I borrow your phone?', exampleVN: 'Tôi có thể mượn điện thoại không?' },
  { id: 'e320', word: 'lose', meaning: 'mất, thua', example: 'I lost my wallet.', exampleVN: 'Tôi bị mất ví.' },
  { id: 'e321', word: 'win', meaning: 'thắng', example: 'We won the game.', exampleVN: 'Chúng tôi thắng trận.' },
  { id: 'e322', word: 'size', meaning: 'kích thước', example: 'What size do you need?', exampleVN: 'Bạn cần cỡ nào?' },
  { id: 'e323', word: 'idea', meaning: 'ý tưởng', example: 'Good idea!', exampleVN: 'Ý hay!' },
  { id: 'e324', word: 'plan', meaning: 'kế hoạch', example: 'What is your plan?', exampleVN: 'Kế hoạch của bạn là gì?' },
  { id: 'e325', word: 'group', meaning: 'nhóm', example: 'Work in a group.', exampleVN: 'Làm việc nhóm.' },
  { id: 'e326', word: 'team', meaning: 'đội', example: 'Our team won.', exampleVN: 'Đội chúng tôi thắng.' },
  { id: 'e327', word: 'place', meaning: 'nơi chốn', example: 'This is a nice place.', exampleVN: 'Đây là một nơi đẹp.' },
  { id: 'e328', word: 'thing', meaning: 'đồ vật, điều', example: 'What is this thing?', exampleVN: 'Đây là cái gì?' },
  { id: 'e329', word: 'story', meaning: 'câu chuyện', example: 'Tell me a story.', exampleVN: 'Kể chuyện cho tôi.' },
  { id: 'e330', word: 'news', meaning: 'tin tức', example: 'Watch the news.', exampleVN: 'Xem tin tức.' },
  { id: 'e331', word: 'language', meaning: 'ngôn ngữ', example: 'Learn a new language.', exampleVN: 'Học một ngôn ngữ mới.' },
  { id: 'e332', word: 'country', meaning: 'quốc gia', example: 'Which country are you from?', exampleVN: 'Bạn đến từ nước nào?' },
  { id: 'e333', word: 'land', meaning: 'đất', example: 'Buy some land.', exampleVN: 'Mua một ít đất.' },
  { id: 'e334', word: 'bridge', meaning: 'cầu', example: 'Cross the bridge.', exampleVN: 'Qua cầu.' },
  { id: 'e335', word: 'market', meaning: 'chợ', example: 'Go to the market.', exampleVN: 'Đi chợ.' },
  { id: 'e336', word: 'boat', meaning: 'thuyền', example: 'Ride a boat.', exampleVN: 'Đi thuyền.' },
  { id: 'e337', word: 'ship', meaning: 'tàu', example: 'The ship is big.', exampleVN: 'Con tàu rất lớn.' },
  { id: 'e338', word: 'ride', meaning: 'cưỡi, đi', example: 'Ride a bicycle.', exampleVN: 'Đi xe đạp.' },
  { id: 'e339', word: 'fly', meaning: 'bay', example: 'Birds can fly.', exampleVN: 'Chim có thể bay.' },
  { id: 'e340', word: 'swim', meaning: 'bơi', example: 'I like to swim.', exampleVN: 'Tôi thích bơi.' },
  { id: 'e341', word: 'sing', meaning: 'hát', example: 'She sings well.', exampleVN: 'Cô ấy hát hay.' },
  { id: 'e342', word: 'dance', meaning: 'nhảy, múa', example: 'Let us dance.', exampleVN: 'Hãy nhảy nào.' },
  { id: 'e343', word: 'draw', meaning: 'vẽ', example: 'Draw a picture.', exampleVN: 'Vẽ một bức tranh.' },
  { id: 'e344', word: 'paint', meaning: 'sơn, vẽ', example: 'Paint the wall.', exampleVN: 'Sơn tường.' },
  { id: 'e345', word: 'grow', meaning: 'mọc, lớn lên', example: 'Plants grow fast.', exampleVN: 'Cây mọc nhanh.' },
  { id: 'e346', word: 'fill', meaning: 'đổ đầy', example: 'Fill the glass.', exampleVN: 'Rót đầy ly.' },
  { id: 'e347', word: 'pour', meaning: 'rót', example: 'Pour some water.', exampleVN: 'Rót nước.' },
  { id: 'e348', word: 'mix', meaning: 'trộn', example: 'Mix the ingredients.', exampleVN: 'Trộn các nguyên liệu.' },
  { id: 'e349', word: 'taste', meaning: 'nếm, mùi vị', example: 'Taste this soup.', exampleVN: 'Nếm thử canh này.' },
  { id: 'e350', word: 'smell', meaning: 'ngửi, mùi', example: 'The flowers smell good.', exampleVN: 'Hoa thơm quá.' },
  { id: 'e351', word: 'touch', meaning: 'chạm', example: 'Do not touch it.', exampleVN: 'Đừng chạm vào.' },
  { id: 'e352', word: 'feel', meaning: 'cảm thấy', example: 'I feel happy.', exampleVN: 'Tôi cảm thấy vui.' },
  { id: 'e353', word: 'count', meaning: 'đếm', example: 'Count to ten.', exampleVN: 'Đếm đến mười.' },
  { id: 'e354', word: 'add', meaning: 'thêm, cộng', example: 'Add sugar to tea.', exampleVN: 'Thêm đường vào trà.' },
  { id: 'e355', word: 'share', meaning: 'chia sẻ', example: 'Share your food.', exampleVN: 'Chia sẻ đồ ăn.' },
  { id: 'e356', word: 'save', meaning: 'tiết kiệm, cứu', example: 'Save your money.', exampleVN: 'Tiết kiệm tiền.' },
  { id: 'e357', word: 'spend', meaning: 'tiêu (tiền/thời gian)', example: 'Do not spend too much.', exampleVN: 'Đừng tiêu quá nhiều.' },
  { id: 'e358', word: 'cost', meaning: 'có giá', example: 'How much does it cost?', exampleVN: 'Nó giá bao nhiêu?' },
  { id: 'e359', word: 'gift', meaning: 'quà tặng', example: 'A birthday gift.', exampleVN: 'Quà sinh nhật.' },
  { id: 'e360', word: 'party', meaning: 'bữa tiệc', example: 'Come to my party.', exampleVN: 'Đến bữa tiệc của tôi.' },
  { id: 'e361', word: 'game', meaning: 'trò chơi', example: 'Play a game.', exampleVN: 'Chơi trò chơi.' },
  { id: 'e362', word: 'toy', meaning: 'đồ chơi', example: 'Buy a new toy.', exampleVN: 'Mua đồ chơi mới.' },
  { id: 'e363', word: 'photo', meaning: 'ảnh', example: 'Take a photo.', exampleVN: 'Chụp ảnh.' },
  { id: 'e364', word: 'box', meaning: 'hộp', example: 'Open the box.', exampleVN: 'Mở hộp.' },
  { id: 'e365', word: 'bottle', meaning: 'chai', example: 'A bottle of water.', exampleVN: 'Một chai nước.' },
  { id: 'e366', word: 'glass', meaning: 'ly, kính', example: 'A glass of juice.', exampleVN: 'Một ly nước trái cây.' },
  { id: 'e367', word: 'plate', meaning: 'đĩa', example: 'Put food on the plate.', exampleVN: 'Để thức ăn lên đĩa.' },
  { id: 'e368', word: 'cup', meaning: 'tách', example: 'A cup of coffee.', exampleVN: 'Một tách cà phê.' },
  { id: 'e369', word: 'knife', meaning: 'con dao', example: 'Use a knife to cut.', exampleVN: 'Dùng dao để cắt.' },
  { id: 'e370', word: 'paper', meaning: 'giấy', example: 'Write on paper.', exampleVN: 'Viết trên giấy.' },
  { id: 'e371', word: 'cake', meaning: 'bánh', example: 'Eat some cake.', exampleVN: 'Ăn bánh.' },
  { id: 'e372', word: 'bread', meaning: 'bánh mì', example: 'Buy some bread.', exampleVN: 'Mua bánh mì.' },
  { id: 'e373', word: 'egg', meaning: 'trứng', example: 'Fry an egg.', exampleVN: 'Chiên trứng.' },
  { id: 'e374', word: 'chicken', meaning: 'gà', example: 'I like fried chicken.', exampleVN: 'Tôi thích gà rán.' },
  { id: 'e375', word: 'meat', meaning: 'thịt', example: 'Cook the meat well.', exampleVN: 'Nấu thịt cho chín.' },
  { id: 'e376', word: 'sugar', meaning: 'đường', example: 'Too much sugar.', exampleVN: 'Quá nhiều đường.' },
  { id: 'e377', word: 'salt', meaning: 'muối', example: 'Add some salt.', exampleVN: 'Thêm chút muối.' },
  { id: 'e378', word: 'oil', meaning: 'dầu', example: 'Cooking oil.', exampleVN: 'Dầu ăn.' },
  { id: 'e379', word: 'vegetable', meaning: 'rau', example: 'Eat more vegetables.', exampleVN: 'Ăn thêm rau.' },
  { id: 'e380', word: 'lunch', meaning: 'bữa trưa', example: 'Time for lunch.', exampleVN: 'Đến giờ ăn trưa.' },
  { id: 'e381', word: 'dinner', meaning: 'bữa tối', example: 'What is for dinner?', exampleVN: 'Bữa tối ăn gì?' },
  { id: 'e382', word: 'breakfast', meaning: 'bữa sáng', example: 'I eat breakfast at 7.', exampleVN: 'Tôi ăn sáng lúc 7 giờ.' },
  { id: 'e383', word: 'menu', meaning: 'thực đơn', example: 'Look at the menu.', exampleVN: 'Xem thực đơn.' },
  { id: 'e384', word: 'bill', meaning: 'hóa đơn', example: 'Can I have the bill?', exampleVN: 'Cho tôi hóa đơn.' },
  { id: 'e385', word: 'tip', meaning: 'tiền boa, mẹo', example: 'Leave a tip.', exampleVN: 'Để lại tiền boa.' },
  { id: 'e386', word: 'enter', meaning: 'vào', example: 'Enter the room.', exampleVN: 'Vào phòng.' },
  { id: 'e387', word: 'exit', meaning: 'ra, lối ra', example: 'Find the exit.', exampleVN: 'Tìm lối ra.' },
  { id: 'e388', word: 'cross', meaning: 'băng qua', example: 'Cross the street.', exampleVN: 'Băng qua đường.' },
  { id: 'e389', word: 'follow', meaning: 'đi theo', example: 'Follow me.', exampleVN: 'Đi theo tôi.' },
  { id: 'e390', word: 'join', meaning: 'tham gia', example: 'Join our group.', exampleVN: 'Tham gia nhóm chúng tôi.' },
  { id: 'e391', word: 'meet', meaning: 'gặp', example: 'Nice to meet you.', exampleVN: 'Rất vui được gặp bạn.' },
  { id: 'e392', word: 'visit', meaning: 'thăm', example: 'Visit my house.', exampleVN: 'Đến thăm nhà tôi.' },
  { id: 'e393', word: 'invite', meaning: 'mời', example: 'Invite your friends.', exampleVN: 'Mời bạn bè đến.' },
  { id: 'e394', word: 'agree', meaning: 'đồng ý', example: 'I agree with you.', exampleVN: 'Tôi đồng ý với bạn.' },
  { id: 'e395', word: 'decide', meaning: 'quyết định', example: 'Decide quickly.', exampleVN: 'Quyết định nhanh.' },
  { id: 'e396', word: 'hope', meaning: 'hy vọng', example: 'I hope so.', exampleVN: 'Tôi hy vọng vậy.' },
  { id: 'e397', word: 'wish', meaning: 'ước', example: 'I wish you luck.', exampleVN: 'Chúc bạn may mắn.' },
  { id: 'e398', word: 'worry', meaning: 'lo lắng', example: 'Do not worry.', exampleVN: 'Đừng lo lắng.' },
  { id: 'e399', word: 'afraid', meaning: 'sợ', example: 'I am afraid of dogs.', exampleVN: 'Tôi sợ chó.' },
  { id: 'e400', word: 'surprise', meaning: 'bất ngờ', example: 'What a surprise!', exampleVN: 'Thật bất ngờ!' },
];
