import { Word } from './types';

export const chunk10: Word[] = [
  { id: '1101', word: 'contractor', meaning: 'nhà thầu', example: 'Independent contractor.', exampleVN: 'Nhà thầu độc lập.' },
  { id: '1102', word: 'contrast', meaning: 'sự tương phản', example: 'In contrast.', exampleVN: 'Ngược lại.' },
  { id: '1103', word: 'contribute', meaning: 'đóng góp', example: 'Contribute to society.', exampleVN: 'Đóng góp cho xã hội.' },
  { id: '1104', word: 'contribution', meaning: 'sự đóng góp', example: 'Make a contribution.', exampleVN: 'Đóng góp.' },
  { id: '1105', word: 'control', meaning: 'kiểm soát', example: 'Under control.', exampleVN: 'Kiểm soát.' },
  { id: '1106', word: 'controversial', meaning: 'gây tranh cãi', example: 'Controversial issue.', exampleVN: 'Giải quyết vấn đề gây tranh cãi.' },
  { id: '1107', word: 'controversy', meaning: 'sự tranh cãi', example: 'Cause controversy.', exampleVN: 'Gây ra tranh cãi.' },
  { id: '1108', word: 'convenience', meaning: 'sự tiện lợi', example: 'For your convenience.', exampleVN: 'Để thuận tiện cho bạn.' },
  { id: '1109', word: 'convenient', meaning: 'tiện lợi', example: 'Convenient time.', exampleVN: 'Thời gian thuận tiện.' },
  { id: '1110', word: 'convention', meaning: 'hội nghị', example: 'Annual convention.', exampleVN: 'Hội nghị hàng năm.' },
  { id: '1111', word: 'conventional', meaning: 'thông thường', example: 'Conventional wisdom.', exampleVN: 'Sự khôn ngoan thông thường.' },
  { id: '1112', word: 'conversation', meaning: 'cuộc hội thoại', example: 'Private conversation.', exampleVN: 'Cuộc trò chuyện riêng tư.' },
  { id: '1113', word: 'convert', meaning: 'chuyển đổi', example: 'Convert into cash.', exampleVN: 'Chuyển đổi thành tiền mặt.' },
  { id: '1114', word: 'convince', meaning: 'thuyết phục', example: 'Convince him.', exampleVN: 'Thuyết phục anh ấy.' },
  { id: '1115', word: 'cook', meaning: 'nấu', example: 'Cook dinner.', exampleVN: 'Nấu bữa tối.' },
  { id: '1116', word: 'cookie', meaning: 'bánh quy', example: 'Chocolate cookie.', exampleVN: 'Bánh quy sô cô la.' },
  { id: '1117', word: 'cool', meaning: 'mát mẻ', example: 'Keep cool.', exampleVN: 'Giữ bình tĩnh.' },
  { id: '1118', word: 'copy', meaning: 'bản sao', example: 'Make a copy.', exampleVN: 'Tạo một bản sao.' },
  { id: '1119', word: 'core', meaning: 'cốt lõi', example: 'Core value.', exampleVN: 'Giá trị cốt lõi' },
  { id: '1120', word: 'corn', meaning: 'ngô', example: 'Sweet corn.', exampleVN: 'Ngô ngọt.' },
  { id: '1121', word: 'corner', meaning: 'góc', example: 'Street corner.', exampleVN: 'Góc phố.' },
  { id: '1122', word: 'corporate', meaning: 'thuộc về công ty', example: 'Corporate culture.', exampleVN: 'Văn hóa doanh nghiệp.' },
  { id: '1123', word: 'corporation', meaning: 'tập đoàn', example: 'Large corporation.', exampleVN: 'Tập đoàn lớn.' },
  { id: '1124', word: 'correct', meaning: 'chính xác', example: 'Correct answer.', exampleVN: 'Trả lời đúng.' },
  { id: '1125', word: 'cost', meaning: 'chi phí', example: 'Low cost.', exampleVN: 'Chi phí thấp.' },
  { id: '1126', word: 'cotton', meaning: 'bông', example: 'Cotton shirt.', exampleVN: 'Áo cotton.' },
  { id: '1127', word: 'cough', meaning: 'ho', example: 'Bad cough.', exampleVN: 'Bệnh ho nặng.' },
  { id: '1128', word: 'council', meaning: 'Hội đồng', example: 'City council.', exampleVN: 'Hội đồng thành phố.' },
  { id: '1129', word: 'counsel', meaning: 'tư vấn', example: 'Seek counsel.', exampleVN: 'Tìm kiếm lời khuyên.' },
  { id: '1130', word: 'count', meaning: 'đếm', example: 'Count the money.', exampleVN: 'Đếm tiền.' },
  { id: '1131', word: 'counter', meaning: 'quầy', example: 'Check-in counter.', exampleVN: 'Quầy nhận phòng.' },
  { id: '1132', word: 'country', meaning: 'quốc gia', example: 'Foreign country.', exampleVN: 'Nước ngoài.' },
  { id: '1133', word: 'county', meaning: 'quận, hạt', example: 'County hospital.', exampleVN: 'Bệnh viện quận.' },
  { id: '1134', word: 'couple', meaning: 'cặp đôi', example: 'Young couple.', exampleVN: 'Cặp vợ chồng trẻ.' },
  { id: '1135', word: 'course', meaning: 'khóa học', example: 'Training course.', exampleVN: 'Khóa đào tạo.' },
  { id: '1136', word: 'court', meaning: 'tòa án', example: 'Supreme court.', exampleVN: 'Tòa án tối cao.' },
  { id: '1137', word: 'cousin', meaning: 'anh em họ', example: 'First cousin.', exampleVN: 'Người anh họ đầu tiên.' },
  { id: '1138', word: 'cover', meaning: 'bao phủ', example: 'Cover the cost.', exampleVN: 'Trang trải chi phí.' },
  { id: '1139', word: 'coverage', meaning: 'phạm vi', example: 'News coverage.', exampleVN: 'Đưa tin.' },
  { id: '1140', word: 'crack', meaning: 'vết nứt', example: 'Crack the code.', exampleVN: 'Giải mã.' },
  { id: '1141', word: 'craft', meaning: 'thủ công', example: 'Hand craft.', exampleVN: 'Nghề thủ công.' },
  { id: '1142', word: 'crash', meaning: 'tai nạn', example: 'Car crash.', exampleVN: 'Vụ tai nạn xe hơi.' },
  { id: '1143', word: 'crazy', meaning: 'điên cuồng', example: 'Drive me crazy.', exampleVN: 'Khiến tôi phát điên.' },
  { id: '1144', word: 'cream', meaning: 'kem', example: 'Ice cream.', exampleVN: 'Kem.' },
  { id: '1145', word: 'create', meaning: 'tạo', example: 'Create a plan.', exampleVN: 'Lập một kế hoạch.' },
  { id: '1146', word: 'creation', meaning: 'sự tạo ra', example: 'Job creation.', exampleVN: 'Tạo việc làm.' },
  { id: '1147', word: 'creative', meaning: 'sáng tạo', example: 'Creative thinking.', exampleVN: 'Tư duy sáng tạo.' },
  { id: '1148', word: 'creature', meaning: 'sinh vật', example: 'Living creature.', exampleVN: 'Sinh vật sống.' },
  { id: '1149', word: 'credit', meaning: 'tín dụng', example: 'Credit card.', exampleVN: 'Thẻ tín dụng.' },
  { id: '1150', word: 'crew', meaning: 'phi hành đoàn', example: 'Cabin crew.', exampleVN: 'Phi hành đoàn.' },
  { id: '1151', word: 'crime', meaning: 'tội phạm', example: 'Commit a crime.', exampleVN: 'Phạm tội.' },
  { id: '1152', word: 'criminal', meaning: 'tội phạm', example: 'Criminal record.', exampleVN: 'Lập hồ sơ tội phạm.' },
  { id: '1153', word: 'crisis', meaning: 'khủng hoảng', example: 'Economic crisis.', exampleVN: 'Khủng hoảng kinh tế.' },
  { id: '1154', word: 'criteria', meaning: 'tiêu chí', example: 'Meet the criteria.', exampleVN: 'Đáp ứng các tiêu chí.' },
  { id: '1155', word: 'critic', meaning: 'nhà phê bình', example: 'Movie critic.', exampleVN: 'Nhà phê bình phim.' },
  { id: '1156', word: 'critical', meaning: 'trầm trọng', example: 'Critical thinking.', exampleVN: 'Tư duy phản biện.' },
  { id: '1157', word: 'criticism', meaning: 'sự phê bình', example: 'Constructive criticism.', exampleVN: 'Những lời phê bình mang tính xây dựng.' },
  { id: '1158', word: 'criticize', meaning: 'chỉ trích', example: 'Criticize someone.', exampleVN: 'Chỉ trích ai đó.' },
  { id: '1159', word: 'crop', meaning: 'vụ mùa', example: 'Cash crop.', exampleVN: 'Vụ mùa.' },
  { id: '1160', word: 'cross', meaning: 'băng qua', example: 'Cross the street.', exampleVN: 'Băng qua đường.' },
  { id: '1161', word: 'crowd', meaning: 'đám đông', example: 'Large crowd.', exampleVN: 'Đám đông lớn.' },
  { id: '1162', word: 'crucial', meaning: 'quan trọng', example: 'Crucial role.', exampleVN: 'Vai trò quan trọng.' },
  { id: '1163', word: 'cry', meaning: 'khóc', example: "Don't cry.", exampleVN: "Đừng khóc." },
  { id: '1164', word: 'cultural', meaning: 'thuộc về văn hóa', example: 'Cultural difference.', exampleVN: 'Sự khác biệt văn hóa.' },
  { id: '1165', word: 'culture', meaning: 'văn hóa', example: 'Corporate culture.', exampleVN: 'Văn hóa doanh nghiệp.' },
  { id: '1166', word: 'cup', meaning: 'cốc', example: 'Cup of tea.', exampleVN: 'Một tách trà.' },
  { id: '1167', word: 'cure', meaning: 'chữa trị', example: 'Find a cure.', exampleVN: 'Tìm cách chữa trị.' },
  { id: '1168', word: 'curiosity', meaning: 'sự tò mò', example: 'Out of curiosity.', exampleVN: 'Vì tò mò.' },
  { id: '1169', word: 'curious', meaning: 'tò mò', example: 'Curious about.', exampleVN: 'Tò mò về.' },
  { id: '1170', word: 'currency', meaning: 'tiền tệ', example: 'Foreign currency.', exampleVN: 'Ngoại tệ.' },
  { id: '1171', word: 'current', meaning: 'hiện tại', example: 'Current situation.', exampleVN: 'Theo tình hình hiện tại.' },
  { id: '1172', word: 'currently', meaning: 'hiện tại(adv)', example: 'Currently unavailable.', exampleVN: 'Hiện không có sẵn.' },
  { id: '1173', word: 'custody', meaning: 'quyền nuôi dưỡng', example: 'Child custody.', exampleVN: 'Quyền nuôi con.' },
  { id: '1174', word: 'custom', meaning: 'phong tục', example: 'Local custom.', exampleVN: 'Phong tục địa phương.' },
  { id: '1175', word: 'customer', meaning: 'khách hàng', example: 'Customer service.', exampleVN: 'Dịch vụ khách hàng.' },
  { id: '1176', word: 'cut', meaning: 'cắt', example: 'Cut costs.', exampleVN: 'Cắt giảm chi phí.' },
  { id: '1177', word: 'cycle', meaning: 'chu kỳ', example: 'Life cycle.', exampleVN: 'Vòng đời.' },
  { id: '1178', word: 'daily', meaning: 'hàng ngày', example: 'Daily routine.', exampleVN: 'Có thói quen hàng ngày.' },
  { id: '1179', word: 'damage', meaning: 'thiệt hại', example: 'Cause damage.', exampleVN: 'Gây ra thiệt hại.' },
  { id: '1180', word: 'dance', meaning: 'khiêu vũ', example: 'Learn to dance.', exampleVN: 'Học nhảy.' },
  { id: '1181', word: 'danger', meaning: 'mối nguy hiểm', example: 'In danger.', exampleVN: 'Nguy hiểm.' },
  { id: '1182', word: 'dangerous', meaning: 'nguy hiểm', example: 'Dangerous animal.', exampleVN: 'Động vật nguy hiểm.' },
  { id: '1183', word: 'dare', meaning: 'dám', example: 'Don\'t dare.' },
  { id: '1184', word: 'dark', meaning: 'tối', example: 'In the dark.', exampleVN: 'Bóng tối.' },
  { id: '1185', word: 'daughter', meaning: 'con gái', example: 'My daughter.', exampleVN: 'Họ thảo luận về con gái tôi.' },
  { id: '1186', word: 'day', meaning: 'ngày', example: 'Have a good day.', exampleVN: 'Chúc một ngày tốt lành.' },
  { id: '1187', word: 'dead', meaning: 'chết', example: 'Dead end.', exampleVN: 'Đi vào ngõ cụt.' },
  { id: '1188', word: 'deadline', meaning: 'hạn chót', example: 'Meet the deadline.', exampleVN: 'Đáp ứng thời hạn.' },
  { id: '1189', word: 'deal', meaning: 'thỏa thuận', example: 'Great deal.', exampleVN: 'Rất nhiều.' },
  { id: '1190', word: 'dealer', meaning: 'người bán', example: 'Car dealer.', exampleVN: 'Đại lý xe hơi.' },
  { id: '1191', word: 'dear', meaning: 'thân mến', example: 'Oh dear.', exampleVN: 'Ôi trời ơi.' },
  { id: '1192', word: 'debate', meaning: 'tranh luận', example: 'Public debate.', exampleVN: 'Cuộc tranh luận công khai.' },
  { id: '1193', word: 'debt', meaning: 'nợ', example: 'In debt.', exampleVN: 'Nợ nần.' },
  { id: '1194', word: 'decade', meaning: 'thập kỷ', example: 'Over a decade.', exampleVN: 'Hơn một thập kỷ.' },
  { id: '1195', word: 'decide', meaning: 'quyết định', example: 'Decide to go.', exampleVN: 'Quyết định đi.' },
  { id: '1196', word: 'decision', meaning: 'sự quyết định', example: 'Make a decision.', exampleVN: 'Đưa ra quyết định.' },
  { id: '1197', word: 'deck', meaning: 'boong tàu', example: 'Upper deck.', exampleVN: 'Tầng trên.' },
  { id: '1198', word: 'declare', meaning: 'tuyên bố', example: 'Declare independence.', exampleVN: 'Tuyên bố độc lập.' },
  { id: '1199', word: 'decline', meaning: 'từ chối', example: 'Decline an offer.', exampleVN: 'Từ chối một lời đề nghị.' },
  { id: '1200', word: 'decrease', meaning: 'giảm', example: 'Decrease in sales.', exampleVN: 'Giảm doanh số bán hàng.' }
];

export const processChunk10 = () => chunk10;
