import { Word } from './types';

export const chunkInter6: Word[] = [
  { id: 'i601', word: 'native', meaning: 'bản địa, tự nhiên', example: 'Native speaker.', exampleVN: 'Người bản ngữ.' },
  { id: 'i602', word: 'natural', meaning: 'tự nhiên', example: 'Natural resources.', exampleVN: 'Tài nguyên thiên nhiên.' },
  { id: 'i603', word: 'nature', meaning: 'thiên nhiên, bản chất', example: 'Mother Nature.', exampleVN: 'Mẹ Thiên Nhiên.' },
  { id: 'i604', word: 'navigation', meaning: 'điều hướng', example: 'Car navigation system.', exampleVN: 'Hệ thống định vị ô tô.' },
  { id: 'i605', word: 'nearby', meaning: 'gần đây', example: 'A nearby restaurant.', exampleVN: 'Một nhà hàng gần đây.' },
  { id: 'i606', word: 'nearly', meaning: 'gần như', example: 'Nearly 50 people.', exampleVN: 'Gần 50 người.' },
  { id: 'i607', word: 'necessary', meaning: 'cần thiết', example: 'It is necessary to wait.', exampleVN: 'Cần thiết phải đợi.' },
  { id: 'i608', word: 'negative', meaning: 'tiêu cực, phủ định', example: 'Negative feedback.', exampleVN: 'Phản hồi tiêu cực.' },
  { id: 'i609', word: 'neglect', meaning: 'bỏ bê', example: 'Neglect your duties.', exampleVN: 'Bỏ bê nhiệm vụ.' },
  { id: 'i610', word: 'negotiate', meaning: 'đàm phán', example: 'Negotiate a deal.', exampleVN: 'Đàm phán một thỏa thuận.' },
  { id: 'i611', word: 'neighbor', meaning: 'hàng xóm', example: 'A friendly neighbor.', exampleVN: 'Một người hàng xóm thân thiện.' },
  { id: 'i612', word: 'neither', meaning: 'cũng không', example: 'Neither of them.', exampleVN: 'Không ai trong số họ.' },
  { id: 'i613', word: 'nervous', meaning: 'lo lắng', example: 'Feel nervous.', exampleVN: 'Cảm thấy lo lắng.' },
  { id: 'i614', word: 'network', meaning: 'mạng lưới', example: 'Social network.', exampleVN: 'Mạng xã hội.' },
  { id: 'i615', word: 'neutral', meaning: 'trung lập', example: 'A neutral position.', exampleVN: 'Một lập trường trung lập.' },
  { id: 'i616', word: 'nevertheless', meaning: 'tuy nhiên', example: 'Nevertheless, he tried.', exampleVN: 'Tuy nhiên, anh ấy đã cố gắng.' },
  { id: 'i617', word: 'newly', meaning: 'mới', example: 'Newly married.', exampleVN: 'Mới cưới.' },
  { id: 'i618', word: 'nickname', meaning: 'biệt danh', example: 'Give a nickname.', exampleVN: 'Đặt biệt danh.' },
  { id: 'i619', word: 'noble', meaning: 'quý tộc, cao quý', example: 'A noble cause.', exampleVN: 'Một sự nghiệp cao cả.' },
  { id: 'i620', word: 'noise', meaning: 'tiếng ồn', example: 'Loud noise.', exampleVN: 'Tiếng ồn lớn.' },
  { id: 'i621', word: 'nominate', meaning: 'đề cử', example: 'Nominate for an award.', exampleVN: 'Đề cử cho một giải thưởng.' },
  { id: 'i622', word: 'none', meaning: 'không ai, không cái gì', example: 'None of the above.', exampleVN: 'Không có cái nào ở trên.' },
  { id: 'i623', word: 'nonetheless', meaning: 'tuy nhiên', example: 'Nonetheless, she smiled.', exampleVN: 'Tuy nhiên, cô ấy đã mỉm cười.' },
  { id: 'i624', word: 'normal', meaning: 'bình thường', example: 'Normal behavior.', exampleVN: 'Hành vi bình thường.' },
  { id: 'i625', word: 'notable', meaning: 'đáng chú ý', example: 'A notable achievement.', exampleVN: 'Một thành tựu đáng chú ý.' },
  { id: 'i626', word: 'notice', meaning: 'thông báo, chú ý', example: 'Give notice.', exampleVN: 'Đưa ra thông báo.' },
  { id: 'i627', word: 'notify', meaning: 'thông báo', example: 'Notify the police.', exampleVN: 'Thông báo cho cảnh sát.' },
  { id: 'i628', word: 'notion', meaning: 'khái niệm, quan niệm', example: 'A strange notion.', exampleVN: 'Một quan niệm kỳ lạ.' },
  { id: 'i629', word: 'novel', meaning: 'tiểu thuyết, mới lạ', example: 'A novel approach.', exampleVN: 'Một cách tiếp cận mới lạ.' },
  { id: 'i630', word: 'nowadays', meaning: 'ngày nay', example: 'Nowadays, people travel more.', exampleVN: 'Ngày nay, mọi người đi du lịch nhiều hơn.' },
  { id: 'i631', word: 'nowhere', meaning: 'không nơi nào', example: 'Nowhere to go.', exampleVN: 'Không có nơi nào để đi.' },
  { id: 'i632', word: 'nuclear', meaning: 'thuộc hạt nhân', example: 'Nuclear energy.', exampleVN: 'Năng lượng hạt nhân.' },
  { id: 'i633', word: 'nuisance', meaning: 'sự phiền toái', example: 'What a nuisance!', exampleVN: 'Thật là phiền phức!' },
  { id: 'i634', word: 'numerous', meaning: 'nhiều, đông đảo', example: 'Numerous errors.', exampleVN: 'Nhiều lỗi.' },
  { id: 'i635', word: 'nutrition', meaning: 'dinh dưỡng', example: 'Good nutrition.', exampleVN: 'Dinh dưỡng tốt.' },
  { id: 'i636', word: 'obey', meaning: 'vâng lời, tuân theo', example: 'Obey the rules.', exampleVN: 'Tuân thủ các quy tắc.' },
  { id: 'i637', word: 'object', meaning: 'vật thể, phản đối', example: 'Do you object?', exampleVN: 'Bạn có phản đối không?' },
  { id: 'i638', word: 'objective', meaning: 'mục tiêu, khách quan', example: 'An objective report.', exampleVN: 'Một báo cáo khách quan.' },
  { id: 'i639', word: 'obligation', meaning: 'nghĩa vụ', example: 'Legal obligation.', exampleVN: 'Nghĩa vụ pháp lý.' },
  { id: 'i640', word: 'observation', meaning: 'sự quan sát', example: 'Keep under observation.', exampleVN: 'Giữ dưới sự quan sát.' },
  { id: 'i641', word: 'observe', meaning: 'quan sát, tuân thủ', example: 'Observe the stars.', exampleVN: 'Quan sát các vì sao.' },
  { id: 'i642', word: 'obsession', meaning: 'sự ám ảnh', example: 'A healthy obsession.', exampleVN: 'Một sự ám ảnh lành mạnh.' },
  { id: 'i643', word: 'obstacle', meaning: 'trở ngại', example: 'Overcome obstacles.', exampleVN: 'Vượt qua những trở ngại.' },
  { id: 'i644', word: 'obtain', meaning: 'đạt được', example: 'Obtain a permit.', exampleVN: 'Xin được giấy phép.' },
  { id: 'i645', word: 'obvious', meaning: 'rõ ràng', example: 'An obvious mistake.', exampleVN: 'Một lỗi rõ ràng.' },
  { id: 'i646', word: 'occasion', meaning: 'dịp', example: 'A special occasion.', exampleVN: 'Một dịp đặc biệt.' },
  { id: 'i647', word: 'occupation', meaning: 'nghề nghiệp', example: 'State your occupation.', exampleVN: 'Ghi rõ nghề nghiệp của bạn.' },
  { id: 'i648', word: 'occupy', meaning: 'chiếm giữ, bận rộn', example: 'The seat is occupied.', exampleVN: 'Ghế đã có người ngồi.' },
  { id: 'i649', word: 'occur', meaning: 'xảy ra', example: 'It occurred to me.', exampleVN: 'Tôi chợt nhận ra.' },
  { id: 'i650', word: 'ocean', meaning: 'đại dương', example: 'Pacific Ocean.', exampleVN: 'Thái Bình Dương.' },
  { id: 'i651', word: 'odd', meaning: 'kỳ lạ, số lẻ', example: 'Odd numbers.', exampleVN: 'Số lẻ.' },
  { id: 'i652', word: 'offend', meaning: 'xúc phạm', example: 'Offend someone.', exampleVN: 'Làm ai đó mếch lòng.' },
  { id: 'i653', word: 'offense', meaning: 'sự xúc phạm, tội lỗi', example: 'A criminal offense.', exampleVN: 'Một hành vi phạm tội.' },
  { id: 'i654', word: 'offer', meaning: 'đề nghị, ưu đãi', example: 'Job offer.', exampleVN: 'Lời mời làm việc.' },
  { id: 'i655', word: 'official', meaning: 'chính thức', example: 'Official website.', exampleVN: 'Trang web chính thức.' },
  { id: 'i656', word: 'offset', meaning: 'bù đắp', example: 'Offset the costs.', exampleVN: 'Bù đắp chi phí.' },
  { id: 'i657', word: 'omit', meaning: 'bỏ sót', example: 'Omit a detail.', exampleVN: 'Bỏ sót một chi tiết.' },
  { id: 'i658', word: 'ongoing', meaning: 'đang diễn ra', example: 'Ongoing project.', exampleVN: 'Dự án đang diễn ra.' },
  { id: 'i659', word: 'online', meaning: 'trực tuyến', example: 'Online shopping.', exampleVN: 'Mua sắm trực tuyến.' },
  { id: 'i660', word: 'opera', meaning: 'nhạc kịch', example: 'Go to the opera.', exampleVN: 'Đi xem nhạc kịch.' },
  { id: 'i661', word: 'operate', meaning: 'vận hành, phẫu thuật', example: 'Operate a machine.', exampleVN: 'Vận hành máy móc.' },
  { id: 'i662', word: 'operation', meaning: 'hoạt động, cuộc phẫu thuật', example: 'Business operation.', exampleVN: 'Hoạt động kinh doanh.' },
  { id: 'i663', word: 'operator', meaning: 'người vận hành', example: 'Phone operator.', exampleVN: 'Tổng đài viên.' },
  { id: 'i664', word: 'opinion', meaning: 'ý kiến', example: 'In my opinion.', exampleVN: 'Theo ý kiến của tôi.' },
  { id: 'i665', word: 'opponent', meaning: 'đối thủ', example: 'A strong opponent.', exampleVN: 'Một đối thủ mạnh.' },
  { id: 'i666', word: 'opportunity', meaning: 'cơ hội', example: 'A golden opportunity.', exampleVN: 'Một cơ hội vàng.' },
  { id: 'i667', word: 'oppose', meaning: 'phản đối', example: 'Oppose the plan.', exampleVN: 'Phản đối kế hoạch.' },
  { id: 'i668', word: 'opposite', meaning: 'đối diện, ngược lại', example: 'Opposite direction.', exampleVN: 'Hướng ngược lại.' },
  { id: 'i669', word: 'opposition', meaning: 'sự phản đối, phe đối lập', example: 'Political opposition.', exampleVN: 'Phe đối lập chính trị.' },
  { id: 'i670', word: 'optimistic', meaning: 'lạc quan', example: 'Optimistic outlook.', exampleVN: 'Cái nhìn lạc quan.' },
  { id: 'i671', word: 'option', meaning: 'tùy chọn', example: 'Have no option.', exampleVN: 'Không còn lựa chọn nào khác.' },
  { id: 'i672', word: 'oral', meaning: 'bằng miệng', example: 'Oral exam.', exampleVN: 'Kỳ thi vấn đáp.' },
  { id: 'i673', word: 'orchestra', meaning: 'dàn nhạc', example: 'Symphony orchestra.', exampleVN: 'Dàn nhạc giao hưởng.' },
  { id: 'i674', word: 'ordinary', meaning: 'bình thường', example: 'An ordinary day.', exampleVN: 'Một ngày bình thường.' },
  { id: 'i675', word: 'organ', meaning: 'cơ quan (trong cơ thể), đàn phong cầm', example: 'Internal organs.', exampleVN: 'Các cơ quan nội tạng.' },
  { id: 'i676', word: 'organic', meaning: 'hữu cơ', example: 'Organic food.', exampleVN: 'Thực phẩm hữu cơ.' },
  { id: 'i677', word: 'organism', meaning: 'sinh vật', example: 'Living organism.', exampleVN: 'Sinh vật sống.' },
  { id: 'i678', word: 'organization', meaning: 'tổ chức', example: 'International organization.', exampleVN: 'Tổ chức quốc tế.' },
  { id: 'i679', word: 'organize', meaning: 'tổ chức', example: 'Organize a party.', exampleVN: 'Tổ chức một bữa tiệc.' },
  { id: 'i680', word: 'orientation', meaning: 'sự định hướng', example: 'Orientation day.', exampleVN: 'Ngày định hướng.' },
  { id: 'i681', word: 'origin', meaning: 'nguồn gốc', example: 'Country of origin.', exampleVN: 'Quốc gia xuất xứ.' },
  { id: 'i682', word: 'original', meaning: 'nguyên bản, độc đáo', example: 'Original copy.', exampleVN: 'Bản gốc.' },
  { id: 'i683', word: 'otherwise', meaning: 'nếu không thì', example: 'Hurry up, otherwise we\'ll be late.', exampleVN: 'Nhanh lên, nếu không chúng ta sẽ muộn.' },
  { id: 'i684', word: 'outcome', meaning: 'kết quả', example: 'The outcome of the election.', exampleVN: 'Kết quả của cuộc bầu cử.' },
  { id: 'i685', word: 'outdoor', meaning: 'ngoài trời', example: 'Outdoor activities.', exampleVN: 'Các hoạt động ngoài trời.' },
  { id: 'i686', word: 'outer', meaning: 'bên ngoài', example: 'Outer space.', exampleVN: 'Không gian vũ trụ.' },
  { id: 'i687', word: 'outfit', meaning: 'trang phục', example: 'A new outfit.', exampleVN: 'Một bộ đồ mới.' },
  { id: 'i688', word: 'outline', meaning: 'phác thảo', example: 'An outline of the plan.', exampleVN: 'Phác thảo kế hoạch.' },
  { id: 'i689', word: 'outlook', meaning: 'triển vọng, quan điểm', example: 'Economic outlook.', exampleVN: 'Triển vọng kinh tế.' },
  { id: 'i690', word: 'output', meaning: 'sản lượng', example: 'Industrial output.', exampleVN: 'Sản lượng công nghiệp.' },
  { id: 'i691', word: 'outrage', meaning: 'sự xúc phạm, phẫn nộ', example: 'Public outrage.', exampleVN: 'Sự phẫn nộ của công chúng.' },
  { id: 'i692', word: 'outside', meaning: 'bên ngoài', example: 'Go outside.', exampleVN: 'Ra ngoài.' },
  { id: 'i693', word: 'outstanding', meaning: 'nổi bật, chưa thanh toán', example: 'Outstanding balance.', exampleVN: 'Số dư chưa thanh toán.' },
  { id: 'i694', word: 'overall', meaning: 'tổng thể', example: 'Overall performance.', exampleVN: 'Hiệu suất tổng thể.' },
  { id: 'i695', word: 'overcome', meaning: 'vượt qua', example: 'Overcome fear.', exampleVN: 'Vượt qua nỗi sợ.' },
  { id: 'i696', word: 'overdue', meaning: 'quá hạn', example: 'The library book is overdue.', exampleVN: 'Sách thư viện đã quá hạn.' },
  { id: 'i697', word: 'overlap', meaning: 'chồng chéo', example: 'The schedules overlap.', exampleVN: 'Các lịch trình bị chồng chéo.' },
  { id: 'i698', word: 'overlook', meaning: 'bỏ qua, nhìn ra', example: 'Overlook a mistake.', exampleVN: 'Bỏ qua một lỗi.' },
  { id: 'i699', word: 'overseas', meaning: 'nước ngoài', example: 'Work overseas.', exampleVN: 'Làm việc ở nước ngoài.' },
  { id: 'i700', word: 'overtime', meaning: 'giờ làm thêm', example: 'Work overtime.', exampleVN: 'Làm thêm giờ.' },
];

export const processChunkInter6 = () => {
  return chunkInter6.map(w => ({ ...w, pos: '(n)' as string }));
};
