import { Word } from './types';

export const chunkInter2: Word[] = [
  { id: 'i101', word: 'accrue', meaning: 'tích lũy', example: 'Interest will accrue over time.', exampleVN: 'Tiền lãi sẽ được tích lũy theo thời gian.' },
  { id: 'i102', word: 'adjust', meaning: 'điều chỉnh', example: 'Adjust the settings for better results.', exampleVN: 'Điều chỉnh cài đặt để có kết quả tốt hơn.' },
  { id: 'i103', word: 'allocate', meaning: 'phân bổ', example: 'The company must allocate resources wisely.', exampleVN: 'Công ty phải phân bổ nguồn lực một cách khôn ngoan.' },
  { id: 'i104', word: 'amend', meaning: 'sửa đổi (luật, văn bản)', example: 'The contract was amended last week.', exampleVN: 'Hợp đồng đã được sửa đổi vào tuần trước.' },
  { id: 'i105', word: 'appraisal', meaning: 'đánh giá, định giá', example: 'The annual performance appraisal is coming.', exampleVN: 'Kỳ đánh giá hiệu suất hàng năm đang đến.' },
  { id: 'i106', word: 'assign', meaning: 'phân công', example: 'The manager will assign tasks to the team.', exampleVN: 'Người quản lý sẽ phân công nhiệm vụ cho nhóm.' },
  { id: 'i107', word: 'audit', meaning: 'kiểm toán', example: 'The company undergoes a financial audit every year.', exampleVN: 'Công ty trải qua một cuộc kiểm toán tài chính hàng năm.' },
  { id: 'i108', word: 'authorize', meaning: 'ủy quyền, cho phép', example: 'Who is authorized to sign this?', exampleVN: 'Ai được ủy quyền ký cái này?' },
  { id: 'i109', word: 'behalf', meaning: 'thay mặt', example: 'I am calling on behalf of Mr. Smith.', exampleVN: 'Tôi gọi điện thay mặt cho ông Smith.' },
  { id: 'i110', word: 'beneficiary', meaning: 'người thụ hưởng', example: 'He is the main beneficiary of the will.', exampleVN: 'Anh ấy là người thụ hưởng chính của di chúc.' },
  { id: 'i111', word: 'bid', meaning: 'đấu thầu, trả giá', example: 'They made a high bid for the project.', exampleVN: 'Họ đã đưa ra mức giá thầu cao cho dự án.' },
  { id: 'i112', word: 'bonus', meaning: 'tiền thưởng', example: 'Employees receive a year-end bonus.', exampleVN: 'Nhân viên nhận được tiền thưởng cuối năm.' },
  { id: 'i113', word: 'brochure', meaning: 'sách quảng cáo nhỏ', example: 'Pick up a brochure for more information.', exampleVN: 'Lấy một cuốn sách quảng cáo để biết thêm thông tin.' },
  { id: 'i114', word: 'budget', meaning: 'ngân sách', example: 'We need to stay within the budget.', exampleVN: 'Chúng ta cần giữ cho nằm trong ngân sách.' },
  { id: 'i115', word: 'candidate', meaning: 'ứng viên', example: 'She is a strong candidate for the position.', exampleVN: 'Cô ấy là một ứng cử viên sáng giá cho vị trí này.' },
  { id: 'i116', word: 'cargo', meaning: 'hàng hóa (vận chuyển)', example: 'The ship is carrying heavy cargo.', exampleVN: 'Con tàu đang chở hàng hóa nặng.' },
  { id: 'i117', word: 'certificate', meaning: 'chứng chỉ', example: 'You will receive a certificate after the course.', exampleVN: 'Bạn sẽ nhận được chứng chỉ sau khóa học.' },
  { id: 'i118', word: 'circumstance', meaning: 'hoàn cảnh, trường hợp', example: 'Under no circumstances should you open this.', exampleVN: 'Trong bất kỳ hoàn cảnh nào bạn cũng không nên mở cái này.' },
  { id: 'i119', word: 'collateral', meaning: 'tài sản thế chấp', example: 'The house was used as collateral for the loan.', exampleVN: 'Ngôi nhà được dùng làm tài sản thế chấp cho khoản vay.' },
  { id: 'i120', word: 'commission', meaning: 'tiền hoa hồng', example: 'Salespeople earn a commission on each sale.', exampleVN: 'Nhân viên bán hàng kiếm được hoa hồng trên mỗi lần bán.' },
  { id: 'i121', word: 'commitment', meaning: 'cam kết', example: 'We have a commitment to quality.', exampleVN: 'Chúng tôi có cam kết về chất lượng.' },
  { id: 'i122', word: 'compensate', meaning: 'bồi thường', example: 'The company will compensate you for the loss.', exampleVN: 'Công ty sẽ bồi thường cho bạn những tổn thất.' },
  { id: 'i123', word: 'compete', meaning: 'cạnh tranh', example: 'We must compete with international brands.', exampleVN: 'Chúng ta phải cạnh tranh với các thương hiệu quốc tế.' },
  { id: 'i124', word: 'comply', meaning: 'tuân thủ', example: 'All products must comply with safety standards.', exampleVN: 'Tất cả sản phẩm phải tuân thủ các tiêu chuẩn an toàn.' },
  { id: 'i125', word: 'comprehensive', meaning: 'toàn diện', example: 'A comprehensive study of the market.', exampleVN: 'Một nghiên cứu toàn diện về thị trường.' },
  { id: 'i126', word: 'compromise', meaning: 'thỏa hiệp', example: 'We reached a compromise after hours of talk.', exampleVN: 'Chúng tôi đã đạt được một sự thỏa hiệp sau hàng giờ nói chuyện.' },
  { id: 'i127', word: 'confirm', meaning: 'xác nhận', example: 'Please confirm your attendance.', exampleVN: 'Vui lòng xác nhận sự tham dự của bạn.' },
  { id: 'i128', word: 'consecutive', meaning: 'liên tiếp', example: 'It rained for three consecutive days.', exampleVN: 'Trời mưa trong ba ngày liên tiếp.' },
  { id: 'i129', word: 'consensus', meaning: 'sự đồng thuận', example: 'The committee reached a consensus.', exampleVN: 'Ủy ban đã đạt được một sự đồng thuận.' },
  { id: 'i130', word: 'consequently', meaning: 'hậu quả là, do đó', example: 'He missed the train; consequently, he was late.', exampleVN: 'Anh ấy lỡ chuyến tàu; do đó, anh ấy đã đến muộn.' },
  { id: 'i131', word: 'conserve', meaning: 'bảo tồn, tiết kiệm', example: 'We need to conserve energy.', exampleVN: 'Chúng ta cần tiết kiệm năng lượng.' },
  { id: 'i132', word: 'consist', meaning: 'bao gồm', example: 'The team consists of five experts.', exampleVN: 'Nhóm bao gồm năm chuyên gia.' },
  { id: 'i133', word: 'consultant', meaning: 'người tư vấn', example: 'He works as an IT consultant.', exampleVN: 'Anh ấy làm việc như một tư vấn viên CNTT.' },
  { id: 'i134', word: 'consume', meaning: 'tiêu thụ', example: 'The new engine consumes less fuel.', exampleVN: 'Động cơ mới tiêu thụ ít nhiên liệu hơn.' },
  { id: 'i135', word: 'contribute', meaning: 'đóng góp', example: 'Many people contributed to the success.', exampleVN: 'Nhiều người đã đóng góp vào thành công.' },
  { id: 'i136', word: 'coordinate', meaning: 'điều phối', example: 'We need to coordinate our efforts.', exampleVN: 'Chúng ta cần điều phối các nỗ lực của mình.' },
  { id: 'i137', word: 'corporate', meaning: 'thuộc về doanh nghiệp', example: 'Corporate social responsibility is important.', exampleVN: 'Trách nhiệm xã hội của doanh nghiệp là quan trọng.' },
  { id: 'i138', word: 'correspondence', meaning: 'thư từ giao dịch', example: 'Keep all business correspondence in this file.', exampleVN: 'Giữ tất cả thư từ kinh doanh trong tập tin này.' },
  { id: 'i139', word: 'counterfeit', meaning: 'giả mạo', example: 'Counterfeit goods are sold everywhere.', exampleVN: 'Hàng giả được bán ở khắp mọi nơi.' },
  { id: 'i140', word: 'crucial', meaning: 'quan trọng, cốt yếu', example: 'This is a crucial decision for the company.', exampleVN: 'Đây là một quyết định quan trọng đối với công ty.' },
  { id: 'i141', word: 'curriculum', meaning: 'chương trình giảng dạy', example: 'The curriculum is updated every year.', exampleVN: 'Chương trình giảng dạy được cập nhật hàng năm.' },
  { id: 'i142', word: 'debt', meaning: 'khoản nợ', example: 'The company is struggling with debt.', exampleVN: 'Công ty đang vật lộn với các khoản nợ.' },
  { id: 'i143', word: 'decade', meaning: 'thập kỷ', example: 'The economy has grown over the last decade.', exampleVN: 'Nền kinh tế đã tăng trưởng trong thập kỷ qua.' },
  { id: 'i144', word: 'decline', meaning: 'từ chối, suy giảm', example: 'Sales declined by 10% this quarter.', exampleVN: 'Doanh số đã giảm 10% trong quý này.' },
  { id: 'i145', word: 'deduct', meaning: 'khấu trừ', example: 'Taxes are deducted from your salary.', exampleVN: 'Thuế được khấu trừ từ lương của bạn.' },
  { id: 'i146', word: 'defect', meaning: 'lỗi, khuyết điểm', example: 'The product was returned due to a defect.', exampleVN: 'Sản phẩm đã bị trả lại do một lỗi.' },
  { id: 'i147', word: 'delegate', meaning: 'ủy thác, đại biểu', example: 'The manager delegated the task to his assistant.', exampleVN: 'Người quản lý đã ủy thác nhiệm vụ cho trợ lý của mình.' },
  { id: 'i148', word: 'demographic', meaning: 'nhân khẩu học', example: 'Targeting a specific demographic.', exampleVN: 'Nhắm mục tiêu vào một nhóm nhân khẩu học cụ thể.' },
  { id: 'i149', word: 'deposit', meaning: 'tiền đặt cọc, gửi tiền', example: 'You need to pay a deposit for the apartment.', exampleVN: 'Bạn cần trả tiền đặt cọc cho căn hộ.' },
  { id: 'i150', word: 'depreciate', meaning: 'giảm giá trị', example: 'Cars depreciate quickly.', exampleVN: 'Xe hơi giảm giá trị nhanh chóng.' },
  { id: 'i151', word: 'designate', meaning: 'chỉ định', example: 'This area is designated for smokers.', exampleVN: 'Khu vực này được chỉ định cho người hút thuốc.' },
  { id: 'i152', word: 'deteriorate', meaning: 'xấu đi, xuống cấp', example: 'The weather condition deteriorated rapidly.', exampleVN: 'Điều kiện thời tiết xấu đi nhanh chóng.' },
  { id: 'i153', word: 'determine', meaning: 'xác định, quyết tâm', example: 'We need to determine the cause of the failure.', exampleVN: 'Chúng ta cần xác định nguyên nhân của sự thất bại.' },
  { id: 'i154', word: 'devise', meaning: 'nghĩ ra, phát minh', example: 'We must devise a new plan.', exampleVN: 'Chúng ta phải nghĩ ra một kế hoạch mới.' },
  { id: 'i155', word: 'digit', meaning: 'chữ số', example: 'Enter a four-digit code.', exampleVN: 'Nhập mã gồm bốn chữ số.' },
  { id: 'i156', word: 'diligent', meaning: 'siêng năng', example: 'She is a diligent worker.', exampleVN: 'Cô ấy là một nhân viên siêng năng.' },
  { id: 'i157', word: 'dimension', meaning: 'kích thước, chiều', example: 'What are the dimensions of the box?', exampleVN: 'Kích thước của chiếc hộp là bao nhiêu?' },
  { id: 'i158', word: 'discount', meaning: 'giảm giá', example: 'Get a 20% discount on all items.', exampleVN: 'Nhận giảm giá 20% cho tất cả các mặt hàng.' },
  { id: 'i159', word: 'discrepancy', meaning: 'sự khác biệt, không thống nhất', example: 'There is a discrepancy in the accounts.', exampleVN: 'Có một sự khác biệt trong các tài khoản.' },
  { id: 'i160', word: 'discretion', meaning: 'sự thận trọng, tự ý quyết định', example: 'Use your own discretion.', exampleVN: 'Hãy tự quyết định theo ý của bạn.' },
  { id: 'i161', word: 'dismiss', meaning: 'sa thải, bác bỏ', example: 'He was dismissed for being late.', exampleVN: 'Anh ấy bị sa thải vì đi muộn.' },
  { id: 'i162', word: 'display', meaning: 'trưng bày', example: 'The new models are on display.', exampleVN: 'Các mẫu mới đang được trưng bày.' },
  { id: 'i163', word: 'dispose', meaning: 'vứt bỏ, xử lý', example: 'Dispose of waste properly.', exampleVN: 'Xử lý chất thải đúng cách.' },
  { id: 'i164', word: 'dispute', meaning: 'tranh chấp', example: 'The labor dispute was settled.', exampleVN: 'Cuộc tranh chấp lao động đã được giải quyết.' },
  { id: 'i165', word: 'distinct', meaning: 'khác biệt, rõ rệt', example: 'There are three distinct categories.', exampleVN: 'Có ba loại riêng biệt.' },
  { id: 'i166', word: 'distinguish', meaning: 'phân biệt', example: 'It is hard to distinguish between the two.', exampleVN: 'Thật khó để phân biệt giữa hai cái này.' },
  { id: 'i167', word: 'dividend', meaning: 'cổ tức', example: 'The company announced a higher dividend.', exampleVN: 'Công ty đã thông báo mức cổ tức cao hơn.' },
  { id: 'i168', word: 'document', meaning: 'tài liệu', example: 'Please sign this document.', exampleVN: 'Vui lòng ký tài liệu này.' },
  { id: 'i169', word: 'domestic', meaning: 'trong nước, nội địa', example: 'Domestic flights are cheaper.', exampleVN: 'Các chuyến bay nội địa rẻ hơn.' },
  { id: 'i170', word: 'dormitory', meaning: 'ký túc xá', example: 'She lives in a college dormitory.', exampleVN: 'Cô ấy sống trong ký túc xá đại học.' },
  { id: 'i171', word: 'drastic', meaning: 'quyết liệt, mạnh mẽ', example: 'We need to take drastic measures.', exampleVN: 'Chúng ta cần thực hiện các biện pháp quyết liệt.' },
  { id: 'i172', word: 'duplicate', meaning: 'bản sao, nhân bản', example: 'Keep a duplicate copy of the key.', exampleVN: 'Giữ một bản sao của chìa khóa.' },
  { id: 'i173', word: 'durable', meaning: 'bền', example: 'The material is very durable.', exampleVN: 'Vật liệu này rất bền.' },
  { id: 'i174', word: 'duration', meaning: 'thời lượng, khoảng thời gian', example: 'The duration of the flight is two hours.', exampleVN: 'Thời lượng của chuyến bay là hai giờ.' },
  { id: 'i175', word: 'ecology', meaning: 'sinh thái học', example: 'We should care about the local ecology.', exampleVN: 'Chúng ta nên quan tâm đến sinh thái địa phương.' },
  { id: 'i176', word: 'economic', meaning: 'thuộc về kinh tế', example: 'The economic situation is improving.', exampleVN: 'Tình hình kinh tế đang được cải thiện.' },
  { id: 'i177', word: 'economy', meaning: 'nền kinh tế', example: 'The world economy is growing slowly.', exampleVN: 'Nền kinh tế thế giới đang tăng trưởng chậm.' },
  { id: 'i178', word: 'edit', meaning: 'chỉnh sửa', example: 'Can you edit this video?', exampleVN: 'Bạn có thể chỉnh sửa video này không?' },
  { id: 'i179', word: 'edition', meaning: 'phiên bản, lần xuất bản', example: 'The first edition was sold out.', exampleVN: 'Phiên bản đầu tiên đã được bán hết.' },
  { id: 'i180', word: 'effect', meaning: 'tác động, hiệu quả', example: 'The new law has a positive effect.', exampleVN: 'Luật mới có tác động tích cực.' },
  { id: 'i181', word: 'efficient', meaning: 'hiệu quả, năng suất', example: 'The new system is more efficient.', exampleVN: 'Hệ thống mới hiệu quả hơn.' },
  { id: 'i182', word: 'elaborate', meaning: 'tỉ mỉ, chi tiết', example: 'Can you elaborate on your point?', exampleVN: 'Bạn có thể giải thích chi tiết hơn về ý của mình không?' },
  { id: 'i183', word: 'elastic', meaning: 'đàn hồi', example: 'The demand for luxury goods is elastic.', exampleVN: 'Nhu cầu đối với hàng xa xỉ là có tính đàn hồi.' },
  { id: 'i184', word: 'elect', meaning: 'bầu cử', example: 'They elected a new president.', exampleVN: 'Họ đã bầu ra một vị tổng thống mới.' },
  { id: 'i185', word: 'eligible', meaning: 'đủ điều kiện', example: 'Are you eligible for the grant?', exampleVN: 'Bạn có đủ điều kiện nhận trợ cấp không?' },
  { id: 'i186', word: 'eliminate', meaning: 'loại bỏ', example: 'We must eliminate waste.', exampleVN: 'Chúng ta phải loại bỏ lãng phí.' },
  { id: 'i187', word: 'embark', meaning: 'bắt đầu, lên tàu', example: 'They embarked on a new journey.', exampleVN: 'Họ đã bắt đầu một hành trình mới.' },
  { id: 'i188', word: 'embarrass', meaning: 'làm ngượng ngùng', example: 'I didn\'t mean to embarrass you.', exampleVN: 'Tôi không cố ý làm bạn ngượng.' },
  { id: 'i189', word: 'emerge', meaning: 'xuất hiện, nổi lên', example: 'New problems emerged during the project.', exampleVN: 'Những vấn đề mới đã xuất hiện trong quá trình thực hiện dự án.' },
  { id: 'i190', word: 'emphasis', meaning: 'sự nhấn mạnh', example: 'The emphasis is on quality, not quantity.', exampleVN: 'Sự nhấn mạnh đặt vào chất lượng, không phải số lượng.' },
  { id: 'i191', word: 'empirical', meaning: 'thực nghiệm', example: 'Based on empirical evidence.', exampleVN: 'Dựa trên bằng chứng thực nghiệm.' },
  { id: 'i192', word: 'employ', meaning: 'thuê, tuyển dụng', example: 'The company employs 200 workers.', exampleVN: 'Công ty thuê 200 công nhân.' },
  { id: 'i193', word: 'employee', meaning: 'nhân viên', example: 'Happy employees are more productive.', exampleVN: 'Nhân viên hạnh phúc làm việc năng suất hơn.' },
  { id: 'i194', word: 'employer', meaning: 'người chủ', example: 'He is a generous employer.', exampleVN: 'Ông ấy là một người chủ hào phóng.' },
  { id: 'i195', word: 'enable', meaning: 'cho phép, kích hoạt', example: 'This software enables remote work.', exampleVN: 'Phần mềm này cho phép làm việc từ xa.' },
  { id: 'i196', word: 'enclose', meaning: 'đính kèm, bao quanh', example: 'Please find the document enclosed.', exampleVN: 'Vui lòng xem tài liệu đính kèm.' },
  { id: 'i197', word: 'encounter', meaning: 'gặp gỡ, chạm chán', example: 'We encountered some difficulties.', exampleVN: 'Chúng tôi đã gặp phải một số khó khăn.' },
  { id: 'i198', word: 'encourage', meaning: 'khuyến khích', example: 'Parents should encourage their children.', exampleVN: 'Cha mẹ nên khuyến khích con cái mình.' },
  { id: 'i199', word: 'endorse', meaning: 'xác nhận, ủng hộ', example: 'The celebrity endorsed the product.', exampleVN: 'Người nổi tiếng đã ủng hộ sản phẩm.' },
  { id: 'i200', word: 'enforce', meaning: 'thực thi, bắt buộc', example: 'The police enforce the law.', exampleVN: 'Cảnh sát thực thi pháp luật.' },
];

export const processChunkInter2 = () => {
  return chunkInter2.map(w => ({ ...w, pos: '(n)' as string }));
};
