import { Word } from './types';

export const chunk14: Omit<Word, 'id'>[] = [
  { word: 'propose', meaning: 'đề nghị, đề xuất', example: 'The committee proposed a new set of rules.', exampleVN: 'Ủy ban đã đề xuất một bộ quy tắc mới.' },
  { word: 'proposal', meaning: 'bản đề xuất, sự đề nghị', example: 'The proposal was submitted for review.', exampleVN: 'Bản đề xuất đã được gửi đi để xem xét.' },
  { word: 'submit', meaning: 'nộp, trình', example: 'Candidates must submit their applications by Friday.', exampleVN: 'Các ứng viên phải nộp hồ sơ trước thứ Sáu.' },
  { word: 'fair', meaning: 'hội chợ, triển lãm', example: 'The local job fair is a great way to meet employers.', exampleVN: 'Hội chợ việc làm địa phương là một cách tuyệt vời để gặp gỡ các nhà tuyển dụng.' },
  { word: 'project', meaning: 'dự án, kế hoạch', example: 'The project is ahead of schedule.', exampleVN: 'Dự án đang vượt tiến độ.' },
  { word: 'projector', meaning: 'máy chiếu', example: 'The technician is fixing the overhead projector.', exampleVN: 'Kỹ thuật viên đang sửa máy chiếu.' },
  { word: 'technician', meaning: 'kỹ thuật viên', example: 'Call the technician to fix the server.', exampleVN: 'Hãy gọi kỹ thuật viên đến sửa máy chủ.' },
  { word: 'satisfy', meaning: 'làm hài lòng, thỏa mãn', example: 'The company strives to satisfy its customers.', exampleVN: 'Công ty nỗ lực để làm hài lòng khách hàng của mình.' },
  { word: 'satisfaction', meaning: 'sự hài lòng, niềm hân hoan', example: 'Customer satisfaction is our top priority.', exampleVN: 'Sự hài lòng của khách hàng là ưu tiên hàng đầu của chúng tôi.' },
  { word: 'colleague', meaning: 'đồng nghiệp', example: 'I discussed the matter with my colleagues.', exampleVN: 'Tôi đã thảo luận vấn đề này với các đồng nghiệp của mình.' },
  { word: 'representative', meaning: 'người đại diện', example: 'A sales representative will contact you soon.', exampleVN: 'Một đại diện bán hàng sẽ sớm liên hệ với bạn.' },
  { word: 'confirm', meaning: 'xác nhận', example: 'Please confirm your reservation by phone.', exampleVN: 'Vui lòng xác nhận việc đặt chỗ của bạn qua điện thoại.' },
  { word: 'reservation', meaning: 'sự đặt chỗ trước', example: 'I made a reservation for two at the restaurant.', exampleVN: 'Tôi đã đặt chỗ cho hai người tại nhà hàng.' },
  { word: 'brochure', meaning: 'sách hướng dẫn, tờ rơi quảng cáo', example: 'The travel brochure has beautiful pictures.', exampleVN: 'Tờ rơi du lịch có những hình ảnh rất đẹp.' },
  { word: 'itinerary', meaning: 'hành trình, lịch trình', example: 'She left her itinerary with her assistant.', exampleVN: 'Cô ấy đã để lại lịch trình cho trợ lý của mình.' },
  { word: 'invoice', meaning: 'hóa đơn', example: 'You will receive an invoice via email.', exampleVN: 'Bạn sẽ nhận được hóa đơn qua email.' },
  { word: 'manual', meaning: 'sách hướng dẫn sử dụng, thủ công', example: 'Read the instruction manual carefully.', exampleVN: 'Hãy đọc kỹ sách hướng dẫn sử dụng.' },
  { word: 'warranty', meaning: 'sự bảo hành', example: 'The refrigerator comes with a two-year warranty.', exampleVN: 'Tủ lạnh đi kèm với bảo hành hai năm.' },
  { word: 'refund', meaning: 'hoàn tiền', example: 'If you are not satisfied, you can get a refund.', exampleVN: 'Nếu bạn không hài lòng, bạn có thể được hoàn tiền.' },
  { word: 'substitute', meaning: 'người/vật thay thế', example: 'Small change is no substitute for a real solution.', exampleVN: 'Sự thay đổi nhỏ không thể thay thế cho một giải pháp thực sự.' },
  { word: 'prioritize', meaning: 'ưu tiên', example: 'Prioritize tasks based on urgency.', exampleVN: 'Ưu tiên các nhiệm vụ dựa trên mức độ khẩn cấp.' },
  { word: 'deadline', meaning: 'hạn chót', example: 'The deadline for the report is 5 PM.', exampleVN: 'Hạn chót cho báo cáo là 5 giờ chiều.' },
  { word: 'extension', meaning: 'sự gia hạn, số máy lẻ', example: 'He asked for an extension on his project.', exampleVN: 'Anh ấy đã xin gia hạn cho dự án của mình.' },
  { word: 'department', meaning: 'phòng ban, bộ phận', example: 'The marketing department is hiring new staff.', exampleVN: 'Phòng marketing đang tuyển thêm nhân viên mới.' },
  { word: 'personnel', meaning: 'nhân sự', example: 'The personnel office is on the third floor.', exampleVN: 'Văn phòng nhân sự nằm ở tầng ba.' },
  { word: 'recruitment', meaning: 'sự tuyển dụng', example: 'The company has a rigorous recruitment process.', exampleVN: 'Công ty có một quy trình tuyển dụng khắt khe.' },
  { word: 'candidate', meaning: 'ứng viên', example: 'We have several candidates for the position.', exampleVN: 'Chúng tôi có một vài ứng viên cho vị trí này.' },
  { word: 'interview', meaning: 'phỏng vấn', example: 'Your interview is scheduled for next Tuesday.', exampleVN: 'Cuộc phỏng vấn của bạn được lên lịch vào thứ Ba tới.' },
  { word: 'qualification', meaning: 'bằng cấp, năng lực', example: 'Does she have the necessary qualifications for the job?', exampleVN: 'Cô ấy có những bằng cấp cần thiết cho công việc không?' },
  { word: 'certificate', meaning: 'chứng chỉ', example: 'He received a certificate after completing the course.', exampleVN: 'Anh ấy đã nhận được chứng chỉ sau khi hoàn thành khóa học.' },
  { word: 'promotion', meaning: 'sự thăng chức, khuyến mãi', example: 'The promotion of active lifestyle is essential.', exampleVN: 'Việc thúc đẩy lối sống năng động là rất quan trọng.' },
  { word: 'retirement', meaning: 'sự nghỉ hưu', example: 'She is looking forward to her retirement next year.', exampleVN: 'Cô ấy đang mong chờ đợt nghỉ hưu vào năm tới.' },
  { word: 'benefit', meaning: 'lợi ích, phúc lợi', example: 'Employees enjoy many benefits, including health insurance.', exampleVN: 'Nhân viên hưởng nhiều phúc lợi, bao gồm cả bảo hiểm y tế.' },
  { word: 'allowance', meaning: 'tiền trợ cấp', example: 'He gets a travel allowance for his business trips.', exampleVN: 'Anh ấy được trợ cấp đi lại cho các chuyến công tác của mình.' },
  { word: 'commission', meaning: 'tiền hoa hồng', example: 'Salespeople earn a commission on each sale.', exampleVN: 'Nhân viên bán hàng kiếm được tiền hoa hồng trên mỗi lần bán hàng.' },
  { word: 'bonus', meaning: 'tiền thưởng', example: 'The staff received a performance bonus this year.', exampleVN: 'Nhân viên đã nhận được tiền thưởng hiệu quả công việc trong năm nay.' },
  { word: 'salary', meaning: 'lương (tháng)', example: 'The company offers a competitive salary.', exampleVN: 'Công ty cung cấp một mức lương cạnh tranh.' },
  { word: 'wage', meaning: 'lương (tuần/giờ)', example: 'The minimum wage has increased recently.', exampleVN: 'Mức lương tối thiểu đã tăng lên gần đây.' },
  { word: 'overhead', meaning: 'chi phí cố định', example: 'Reducing overhead costs can improve profit.', exampleVN: 'Giảm chi phí cố định có thể cải thiện lợi nhuận.' },
  { word: 'inventory', meaning: 'hàng tồn kho', example: 'Take inventory of all supplies.', exampleVN: 'Kiểm kê tất cả vật tư tiêu hao.' },
  { word: 'warehouse', meaning: 'kho hàng', example: 'The products are stored in a large warehouse.', exampleVN: 'Sản phẩm được lưu trữ trong một kho hàng lớn.' },
  { word: 'logistics', meaning: 'hậu cần', example: 'The company specializes in global logistics.', exampleVN: 'Công ty chuyên về hậu cần toàn cầu.' },
  { word: 'distribute', meaning: 'phân phối', example: 'The software is distributed through local retailers.', exampleVN: 'Phần mềm được phân phối qua các nhà bán lẻ địa phương.' },
  { word: 'supply', meaning: 'cung cấp', example: 'The company supplies coffee to local cafes.', exampleVN: 'Công ty cung cấp cà phê cho các quán cà phê địa phương.' },
  { word: 'contract', meaning: 'hợp đồng', example: 'Read the contract before you sign it.', exampleVN: 'Hãy đọc hợp đồng trước khi bạn ký.' },
  { word: 'negotiate', meaning: 'đàm phán', example: 'We are trying to negotiate a better deal.', exampleVN: 'Chúng tôi đang cố gắng đàm phán một thỏa thuận tốt hơn.' },
  { word: 'agenda', meaning: 'chương trình nghị sự', example: 'The next item on the agenda is the budget.', exampleVN: 'Mục tiếp theo trong chương trình nghị sự là ngân sách.' },
  { word: 'minutes', meaning: 'biên bản cuộc họp', example: 'The secretary takes the minutes of the meeting.', exampleVN: 'Thư ký ghi biên bản cuộc họp.' },
  { word: 'delegate', meaning: 'ủy thác, đại biểu', example: 'A good manager knows how to delegate tasks.', exampleVN: 'Một người quản lý giỏi biết cách ủy thác công việc.' },
  { word: 'collaborate', meaning: 'cộng tác', example: 'Researchers from different departments collaborated on the project.', exampleVN: 'Các nhà nghiên cứu từ các phòng ban khác nhau đã cộng tác trong dự án.' },
  { word: 'feedback', meaning: 'ý kiến phản hồi', example: 'Customer feedback helps us improve our services.', exampleVN: 'Phản hồi của khách hàng giúp chúng tôi cải thiện dịch vụ.' },
  { word: 'procedure', meaning: 'quy trình, thủ tục', example: 'Follow the standard procedure for handling complaints.', exampleVN: 'Hãy tuân theo quy trình tiêu chuẩn để giải quyết các khiếu nại.' },
  { word: 'compliance', meaning: 'sự tuân thủ', example: 'The company is in complete compliance with food safety laws.', exampleVN: 'Công ty hoàn toàn tuân thủ các luật an toàn thực phẩm.' },
  { word: 'regulate', meaning: 'điều tiết, quy định', example: 'The government regulates the banking industry.', exampleVN: 'Chính phủ quy định ngành ngân hàng.' },
  { word: 'violate', meaning: 'vi phạm', example: 'Illegal dumping violates environmental laws.', exampleVN: 'Việc đổ thải bất hợp pháp vi phạm luật môi trường.' },
  { word: 'policy', meaning: 'chính sách', example: 'Our return policy is very flexible.', exampleVN: 'Chính sách trả hàng của chúng tôi rất linh hoạt.' },
  { word: 'guideline', meaning: 'hướng dẫn', example: 'The government issued new guidelines for healthy eating.', exampleVN: 'Chính phủ đã ban hành các hướng dẫn mới về việc ăn uống lành mạnh.' },
  { word: 'strategy', meaning: 'chiến lược', example: 'The long-term strategy of the firm is sound.', exampleVN: 'Chiến lược dài hạn của công ty là hợp lý.' },
  { word: 'objective', meaning: 'mục tiêu', example: 'Our primary objective is to increase market share.', exampleVN: 'Mục tiêu chính của chúng tôi là tăng thị phần.' },
  { word: 'summary', meaning: 'bản tóm tắt', example: 'Can you give me a brief summary of the report?', exampleVN: 'Bạn có thể cho tôi một bản tóm tắt ngắn gọn về báo cáo không?' },
  { word: 'analyze', meaning: 'phân tích', example: 'Analyze the results of the survey.', exampleVN: 'Phân tích các kết quả của cuộc khảo sát.' },
  { word: 'evaluate', meaning: 'đánh giá', example: 'The manager evaluated the team\'s performance.', exampleVN: 'Người quản lý đã đánh giá hiệu suất của nhóm.' },
  { word: 'efficient', meaning: 'hiệu quả', example: 'The new system is much more efficient than the old one.', exampleVN: 'Hệ thống mới hiệu quả hơn nhiều so với hệ thống cũ.' },
  { word: 'productive', meaning: 'năng suất', example: 'We had a very productive meeting today.', exampleVN: 'Chúng tôi đã có một cuộc họp rất năng suất vào ngày hôm nay.' },
  { word: 'innovative', meaning: 'đổi mới, sáng tạo', example: 'The company is known for its innovative products.', exampleVN: 'Công ty được biết đến với những sản phẩm sáng tạo.' },
  { word: 'expand', meaning: 'mở rộng', example: 'The business is planning to expand overseas.', exampleVN: 'Doanh nghiệp đang có kế hoạch mở rộng ra nước ngoài.' },
  { word: 'merger', meaning: 'sự sáp nhập', example: 'The merger of the two companies created a giant in the industry.', exampleVN: 'Việc sáp nhập hai công ty đã tạo ra một gã khổng lồ trong ngành.' },
  { word: 'acquisition', meaning: 'sự thu mua, thâu tóm', example: 'The firm is looking for more acquisitions.', exampleVN: 'Công ty đang tìm kiếm thêm các thương vụ thâu tóm.' },
  { word: 'competitor', meaning: 'đối thủ cạnh tranh', example: 'Price cuts were a response to the competitor\'s strategy.', exampleVN: 'Việc giảm giá là một phản ứng đối với chiến lược của đối thủ cạnh tranh.' },
  { word: 'consumer', meaning: 'người tiêu dùng', example: 'Consumer spending increased last month.', exampleVN: 'Chi tiêu tiêu dùng đã tăng vào tháng trước.' },
  { word: 'survey', meaning: 'cuộc khảo sát', example: 'The survey revealed that most people prefer online shopping.', exampleVN: 'Cuộc khảo sát tiết lộ rằng hầu hết mọi người thích mua sắm trực tuyến.' },
  { word: 'monopoly', meaning: 'độc quyền', example: 'The company has a monopoly on electricity in the region.', exampleVN: 'Công ty có độc quyền về điện trong khu vực.' },
  { word: 'profitable', meaning: 'có lãi', example: 'The new business venture proved to be very profitable.', exampleVN: 'Dự án kinh doanh mới đã chứng minh là rất có lãi.' },
  { word: 'deficit', meaning: 'thâm hụt', example: 'The trade deficit has widened this year.', exampleVN: 'Thâm hụt thương mại đã mở rộng trong năm nay.' },
  { word: 'surplus', meaning: 'dư thừa', example: 'The government reported a budget surplus.', exampleVN: 'Chính phủ đã báo cáo một khoản thặng dư ngân sách.' },
  { word: 'revenue', meaning: 'doanh thu', example: 'Total revenue for the quarter was up 10%.', exampleVN: 'Tổng doanh thu cho quý đã tăng 10%.' },
  { word: 'expenditure', meaning: 'chi tiêu', example: 'Public expenditure on health has increased.', exampleVN: 'Chi tiêu công cho y tế đã tăng lên.' },
  { word: 'appreciation', meaning: 'sự đánh giá cao, sự tăng giá', example: 'The staff showed their appreciation for the bonus.', exampleVN: 'Nhân viên đã bày tỏ sự trân trọng của họ đối với tiền thưởng.' },
  { word: 'depreciation', meaning: 'sự sụp giảm giá trị, khấu hao', example: 'The depreciation of the currency made imports expensive.', exampleVN: 'Sự sụt giảm giá trị của đồng tiền đã làm cho hàng nhập khẩu trở nên đắt đỏ.' },
  { word: 'liquidate', meaning: 'thanh lý, giải thể', example: 'The company was forced to liquidate its assets.', exampleVN: 'Công ty đã bị buộc phải thanh lý tài sản của mình.' },
  { word: 'bankrupt', meaning: 'phá sản', example: 'The firm went bankrupt after several bad years.', exampleVN: 'Công ty đã phá sản sau vài năm tồi tệ.' },
  { word: 'consultant', meaning: 'tư vấn viên', example: 'They hired a business consultant to improve efficiency.', exampleVN: 'Họ đã thuê một tư vấn viên kinh doanh để cải thiện hiệu quả.' },
  { word: 'subsidiary', meaning: 'công ty con', example: 'The company has several subsidiaries in Asia.', exampleVN: 'Công ty có một vài công ty con ở châu Á.' },
  { word: 'franchise', meaning: 'nhượng quyền thương mại', example: 'He decided to buy a fast-food franchise.', exampleVN: 'Anh ấy đã quyết định mua một cửa hàng nhượng quyền đồ ăn nhanh.' },
  { word: 'headquarters', meaning: 'trụ sở chính', example: 'The company headquarters is located in New York.', exampleVN: 'Trụ sở chính của công ty đặt tại New York.' },
  { word: 'branch', meaning: 'chi nhánh', example: 'The bank has branches all over the country.', exampleVN: 'Ngân hàng có các chi nhánh trên khắp cả nước.' },
  { word: 'outsource', meaning: 'thuê ngoài', example: 'The company decided to outsource its accounting.', exampleVN: 'Công ty đã quyết định thuê ngoài bộ phận kế toán của mình.' },
  { word: 'automation', meaning: 'tự động hóa', example: 'Automation has replaced many manual jobs.', exampleVN: 'Tự động hóa đã thay thế nhiều công việc thủ công.' },
  { word: 'reimburse', meaning: 'hoàn trả (chi phí)', example: 'The company will reimburse you for travel expenses.', exampleVN: 'Công ty sẽ hoàn trả cho bạn các chi phí đi lại.' },
  { word: 'vacancy', meaning: 'vị trí trống', example: 'There are several vacancies in the IT department.', exampleVN: 'Có một vài vị trí trống trong phòng IT.' },
  { word: 'mandatory', meaning: 'bắt buộc', example: 'Attendance at the meeting is mandatory.', exampleVN: 'Sự tham dự buổi họp là bắt buộc.' },
  { word: 'premise', meaning: 'cơ sở, tiền đề', example: 'Smoking is not allowed on the premises.', exampleVN: 'Hút thuốc không được phép trong khuôn viên.' },
  { word: 'facility', meaning: 'cơ sở vật chất, tiện nghi', example: 'The research facility is equipped with the latest technology.', exampleVN: 'Cơ sở nghiên cứu được trang bị công nghệ mới nhất.' },
  { word: 'amenity', meaning: 'tiện nghi (khách sạn, khu nghỉ dưỡng)', example: 'The hotel has many amenities, including a swimming pool.', exampleVN: 'Khách sạn có nhiều tiện nghi, bao gồm cả hồ bơi.' },
  { word: 'renovate', meaning: 'cải tạo, sửa mới', example: 'They are planning to renovate the old building.', exampleVN: 'Họ đang có kế hoạch cải tạo tòa nhà cũ.' },
  { word: 'landmark', meaning: 'địa danh, cột mốc', example: 'The Statue of Liberty is a famous landmark.', exampleVN: 'Tượng Nữ thần Tự do là một địa danh nổi tiếng.' },
  { word: 'occupant', meaning: 'người chiếm giữ, cư dân', example: 'The former occupants of the building have moved out.', exampleVN: 'Những người cư ngụ trước đó trong tòa nhà đã chuyển đi.' },
  { word: 'lease', meaning: 'hợp đồng thuê nhà/đất', example: 'He signed a three-year lease for the apartment.', exampleVN: 'Anh ấy đã ký một hợp đồng thuê căn hộ trong ba năm.' },
  { word: 'landlord', meaning: 'chủ nhà, chủ đất', example: 'The landlord is responsible for repairs.', exampleVN: 'Chủ nhà có trách nhiệm sửa chữa.' },
  { word: 'tenant', meaning: 'người thuê nhà/đất', example: 'The tenant is moving out next month.', exampleVN: 'Người thuê sẽ chuyển đi vào tháng tới.' }
];

export function processChunk14(): Word[] {
  return chunk14.map((w, index) => {
    const nouns = new Set(['proposal', 'fair', 'project', 'projector', 'technician', 'satisfaction', 'colleague', 'representative', 'reservation', 'brochure', 'itinerary', 'invoice', 'manual', 'warranty', 'refund', 'substitute', 'deadline', 'extension', 'department', 'personnel', 'recruitment', 'candidate', 'interview', 'qualification', 'certificate', 'promotion', 'retirement', 'benefit', 'allowance', 'commission', 'bonus', 'salary', 'wage', 'overhead', 'inventory', 'warehouse', 'logistics', 'contract', 'agenda', 'minutes', 'delegate', 'feedback', 'procedure', 'compliance', 'policy', 'guideline', 'strategy', 'objective', 'summary', 'merger', 'acquisition', 'competitor', 'consumer', 'survey', 'monopoly', 'deficit', 'surplus', 'revenue', 'expenditure', 'appreciation', 'depreciation', 'consultant', 'subsidiary', 'franchise', 'headquarters', 'branch', 'automation', 'vacancy', 'premise', 'facility', 'amenity', 'landmark', 'occupant', 'lease', 'landlord', 'tenant']);
    const both_nv = new Set(['submit', 'project', 'confirm', 'substitute', 'interview', 'benefit', 'supply', 'contract', 'minutes', 'delegate', 'survey']);
    const adjs = new Set(['efficient', 'productive', 'innovative', 'profitable', 'bankrupt', 'mandatory']);
    
    let pos = '(v)';
    if (nouns.has(w.word)) pos = '(n)';
    if (both_nv.has(w.word)) pos = '(n, v)';
    if (adjs.has(w.word)) pos = '(adj)';

    return {
      ...w,
      id: `c14_${index}`,
      pos
    };
  });
}
