import { Word } from './types';

export const chunkInter1: Word[] = [
  { id: 'i1', word: 'deadline', meaning: 'hạn chót', example: 'The deadline for submission is Friday.', exampleVN: 'Hạn chót nộp bài là thứ Sáu.' },
  { id: 'i2', word: 'schedule', meaning: 'lịch trình', example: 'Check the meeting schedule.', exampleVN: 'Kiểm tra lịch trình cuộc họp.' },
  { id: 'i3', word: 'opportunity', meaning: 'cơ hội', example: 'This is a great opportunity.', exampleVN: 'Đây là một cơ hội tuyệt vời.' },
  { id: 'i4', word: 'recommend', meaning: 'đề xuất, giới thiệu', example: 'I recommend this restaurant.', exampleVN: 'Tôi giới thiệu nhà hàng này.' },
  { id: 'i5', word: 'require', meaning: 'yêu cầu', example: 'This job requires experience.', exampleVN: 'Công việc này yêu cầu kinh nghiệm.' },
  { id: 'i6', word: 'available', meaning: 'có sẵn', example: 'Is this product available?', exampleVN: 'Sản phẩm này có sẵn không?' },
  { id: 'i7', word: 'appointment', meaning: 'cuộc hẹn', example: 'I have an appointment at 3 PM.', exampleVN: 'Tôi có cuộc hẹn lúc 3 giờ chiều.' },
  { id: 'i8', word: 'application', meaning: 'đơn xin, ứng dụng', example: 'Submit your application online.', exampleVN: 'Nộp đơn xin trực tuyến.' },
  { id: 'i9', word: 'negotiate', meaning: 'đàm phán', example: 'Negotiate the terms of the contract.', exampleVN: 'Đàm phán các điều khoản hợp đồng.' },
  { id: 'i10', word: 'proposal', meaning: 'đề xuất', example: 'The board reviewed the proposal.', exampleVN: 'Hội đồng đã xem xét đề xuất.' },
  { id: 'i11', word: 'equipment', meaning: 'thiết bị', example: 'New equipment was installed.', exampleVN: 'Thiết bị mới đã được lắp đặt.' },
  { id: 'i12', word: 'manufacture', meaning: 'sản xuất', example: 'We manufacture electronics.', exampleVN: 'Chúng tôi sản xuất thiết bị điện tử.' },
  { id: 'i13', word: 'warehouse', meaning: 'nhà kho', example: 'Store the goods in the warehouse.', exampleVN: 'Lưu trữ hàng hóa trong nhà kho.' },
  { id: 'i14', word: 'purchase', meaning: 'mua sắm', example: 'Purchase the supplies online.', exampleVN: 'Mua vật tư trực tuyến.' },
  { id: 'i15', word: 'shipment', meaning: 'lô hàng', example: 'The shipment arrives tomorrow.', exampleVN: 'Lô hàng đến vào ngày mai.' },
  { id: 'i16', word: 'inspection', meaning: 'sự kiểm tra', example: 'A safety inspection is required.', exampleVN: 'Cần có kiểm tra an toàn.' },
  { id: 'i17', word: 'regulation', meaning: 'quy định', example: 'Follow all safety regulations.', exampleVN: 'Tuân thủ tất cả quy định an toàn.' },
  { id: 'i18', word: 'guarantee', meaning: 'bảo đảm', example: 'We guarantee product quality.', exampleVN: 'Chúng tôi bảo đảm chất lượng sản phẩm.' },
  { id: 'i19', word: 'inventory', meaning: 'hàng tồn kho', example: 'Check the inventory list.', exampleVN: 'Kiểm tra danh sách hàng tồn kho.' },
  { id: 'i20', word: 'merchandise', meaning: 'hàng hóa', example: 'Display the merchandise properly.', exampleVN: 'Trưng bày hàng hóa đúng cách.' },
  { id: 'i21', word: 'refund', meaning: 'hoàn tiền', example: 'Request a full refund.', exampleVN: 'Yêu cầu hoàn tiền đầy đủ.' },
  { id: 'i22', word: 'warranty', meaning: 'bảo hành', example: 'The warranty lasts two years.', exampleVN: 'Bảo hành kéo dài hai năm.' },
  { id: 'i23', word: 'promotion', meaning: 'thăng chức, khuyến mãi', example: 'She got a promotion last month.', exampleVN: 'Cô ấy được thăng chức tháng trước.' },
  { id: 'i24', word: 'advertisement', meaning: 'quảng cáo', example: 'Place an advertisement in the newspaper.', exampleVN: 'Đặt quảng cáo trên báo.' },
  { id: 'i25', word: 'conference', meaning: 'hội nghị', example: 'Attend the annual conference.', exampleVN: 'Tham dự hội nghị thường niên.' },
  { id: 'i26', word: 'presentation', meaning: 'bài thuyết trình', example: 'Prepare a presentation for Monday.', exampleVN: 'Chuẩn bị bài thuyết trình cho thứ Hai.' },
  { id: 'i27', word: 'supervisor', meaning: 'người giám sát', example: 'Report to your supervisor.', exampleVN: 'Báo cáo cho người giám sát.' },
  { id: 'i28', word: 'personnel', meaning: 'nhân sự', example: 'Contact the personnel department.', exampleVN: 'Liên hệ phòng nhân sự.' },
  { id: 'i29', word: 'qualification', meaning: 'bằng cấp, trình độ', example: 'List your qualifications on the resume.', exampleVN: 'Liệt kê trình độ trên sơ yếu lý lịch.' },
  { id: 'i30', word: 'resign', meaning: 'từ chức', example: 'He decided to resign from his position.', exampleVN: 'Anh ấy quyết định từ chức.' },
  { id: 'i31', word: 'retirement', meaning: 'nghỉ hưu', example: 'Plan for your retirement early.', exampleVN: 'Lên kế hoạch nghỉ hưu sớm.' },
  { id: 'i32', word: 'salary', meaning: 'lương tháng', example: 'The salary is competitive.', exampleVN: 'Mức lương cạnh tranh.' },
  { id: 'i33', word: 'wage', meaning: 'lương (theo giờ)', example: 'The minimum wage was raised.', exampleVN: 'Mức lương tối thiểu đã được tăng.' },
  { id: 'i34', word: 'overtime', meaning: 'giờ làm thêm', example: 'She works overtime every week.', exampleVN: 'Cô ấy làm thêm giờ mỗi tuần.' },
  { id: 'i35', word: 'colleague', meaning: 'đồng nghiệp', example: 'Discuss it with your colleagues.', exampleVN: 'Thảo luận với đồng nghiệp.' },
  { id: 'i36', word: 'performance', meaning: 'hiệu suất, biểu diễn', example: 'Improve your work performance.', exampleVN: 'Cải thiện hiệu suất công việc.' },
  { id: 'i37', word: 'responsibility', meaning: 'trách nhiệm', example: 'Take responsibility for your actions.', exampleVN: 'Chịu trách nhiệm về hành động của mình.' },
  { id: 'i38', word: 'achievement', meaning: 'thành tựu', example: 'Celebrate your achievements.', exampleVN: 'Ăn mừng thành tựu của bạn.' },
  { id: 'i39', word: 'demonstrate', meaning: 'trình bày, chứng minh', example: 'Demonstrate how the product works.', exampleVN: 'Trình bày cách sản phẩm hoạt động.' },
  { id: 'i40', word: 'participate', meaning: 'tham gia', example: 'Everyone should participate in the training.', exampleVN: 'Mọi người nên tham gia đào tạo.' },
  { id: 'i41', word: 'accommodation', meaning: 'chỗ ở', example: 'Book accommodation in advance.', exampleVN: 'Đặt chỗ ở trước.' },
  { id: 'i42', word: 'itinerary', meaning: 'lịch trình hành trình', example: 'Check the travel itinerary.', exampleVN: 'Kiểm tra lịch trình du lịch.' },
  { id: 'i43', word: 'reservation', meaning: 'đặt chỗ', example: 'Make a dinner reservation.', exampleVN: 'Đặt chỗ ăn tối.' },
  { id: 'i44', word: 'destination', meaning: 'điểm đến', example: 'Our destination is Tokyo.', exampleVN: 'Điểm đến của chúng tôi là Tokyo.' },
  { id: 'i45', word: 'passenger', meaning: 'hành khách', example: 'All passengers must board now.', exampleVN: 'Tất cả hành khách phải lên tàu ngay.' },
  { id: 'i46', word: 'luggage', meaning: 'hành lý', example: 'Collect your luggage at the carousel.', exampleVN: 'Nhận hành lý tại băng chuyền.' },
  { id: 'i47', word: 'departure', meaning: 'khởi hành', example: 'The departure time is 10 AM.', exampleVN: 'Giờ khởi hành là 10 giờ sáng.' },
  { id: 'i48', word: 'arrival', meaning: 'sự đến nơi', example: 'Notify us of your arrival.', exampleVN: 'Thông báo cho chúng tôi khi bạn đến.' },
  { id: 'i49', word: 'permit', meaning: 'giấy phép, cho phép', example: 'You need a building permit.', exampleVN: 'Bạn cần giấy phép xây dựng.' },
  { id: 'i50', word: 'renovate', meaning: 'cải tạo, tu sửa', example: 'Renovate the old building.', exampleVN: 'Cải tạo tòa nhà cũ.' },
  { id: 'i51', word: 'maintenance', meaning: 'bảo trì', example: 'Schedule regular maintenance.', exampleVN: 'Lên lịch bảo trì định kỳ.' },
  { id: 'i52', word: 'facility', meaning: 'cơ sở vật chất', example: 'The facility is well-equipped.', exampleVN: 'Cơ sở vật chất được trang bị tốt.' },
  { id: 'i53', word: 'construction', meaning: 'xây dựng', example: 'The construction will take six months.', exampleVN: 'Việc xây dựng sẽ mất sáu tháng.' },
  { id: 'i54', word: 'architect', meaning: 'kiến trúc sư', example: 'Hire a professional architect.', exampleVN: 'Thuê kiến trúc sư chuyên nghiệp.' },
  { id: 'i55', word: 'estimate', meaning: 'ước tính', example: 'Give me a cost estimate.', exampleVN: 'Cho tôi một bản ước tính chi phí.' },
  { id: 'i56', word: 'postpone', meaning: 'hoãn lại', example: 'Postpone the meeting until next week.', exampleVN: 'Hoãn cuộc họp đến tuần sau.' },
  { id: 'i57', word: 'reschedule', meaning: 'sắp xếp lại lịch', example: 'Reschedule the appointment.', exampleVN: 'Sắp xếp lại lịch hẹn.' },
  { id: 'i58', word: 'reimburse', meaning: 'hoàn trả chi phí', example: 'The company will reimburse travel costs.', exampleVN: 'Công ty sẽ hoàn trả chi phí đi lại.' },
  { id: 'i59', word: 'implement', meaning: 'triển khai, thực hiện', example: 'Implement the new policy today.', exampleVN: 'Triển khai chính sách mới hôm nay.' },
  { id: 'i60', word: 'revise', meaning: 'sửa đổi', example: 'Revise the budget plan.', exampleVN: 'Sửa đổi kế hoạch ngân sách.' },
  { id: 'i61', word: 'submit', meaning: 'nộp, đệ trình', example: 'Submit your report by Friday.', exampleVN: 'Nộp báo cáo trước thứ Sáu.' },
  { id: 'i62', word: 'distribute', meaning: 'phân phối', example: 'Distribute the flyers downtown.', exampleVN: 'Phân phát tờ rơi ở trung tâm.' },
  { id: 'i63', word: 'subscribe', meaning: 'đăng ký', example: 'Subscribe to the newsletter.', exampleVN: 'Đăng ký nhận bản tin.' },
  { id: 'i64', word: 'representative', meaning: 'đại diện', example: 'Speak to a sales representative.', exampleVN: 'Nói chuyện với đại diện bán hàng.' },
  { id: 'i65', word: 'complaint', meaning: 'lời phàn nàn', example: 'File a formal complaint.', exampleVN: 'Nộp đơn khiếu nại chính thức.' },
  { id: 'i66', word: 'satisfaction', meaning: 'sự hài lòng', example: 'Customer satisfaction is our priority.', exampleVN: 'Sự hài lòng khách hàng là ưu tiên.' },
  { id: 'i67', word: 'reliable', meaning: 'đáng tin cậy', example: 'We need a reliable supplier.', exampleVN: 'Chúng tôi cần nhà cung cấp đáng tin cậy.' },
  { id: 'i68', word: 'efficient', meaning: 'hiệu quả', example: 'This method is more efficient.', exampleVN: 'Phương pháp này hiệu quả hơn.' },
  { id: 'i69', word: 'convenient', meaning: 'thuận tiện', example: 'Is this time convenient for you?', exampleVN: 'Thời gian này có thuận tiện cho bạn không?' },
  { id: 'i70', word: 'essential', meaning: 'thiết yếu', example: 'Good communication is essential.', exampleVN: 'Giao tiếp tốt là điều thiết yếu.' },
  { id: 'i71', word: 'significant', meaning: 'đáng kể', example: 'A significant increase in sales.', exampleVN: 'Sự tăng trưởng đáng kể trong doanh số.' },
  { id: 'i72', word: 'additional', meaning: 'bổ sung, thêm', example: 'No additional fees are charged.', exampleVN: 'Không tính phí bổ sung.' },
  { id: 'i73', word: 'approximately', meaning: 'khoảng, xấp xỉ', example: 'Approximately 200 people attended.', exampleVN: 'Khoảng 200 người đã tham dự.' },
  { id: 'i74', word: 'temporarily', meaning: 'tạm thời', example: 'The office is temporarily closed.', exampleVN: 'Văn phòng tạm thời đóng cửa.' },
  { id: 'i75', word: 'promptly', meaning: 'ngay lập tức', example: 'Please respond promptly.', exampleVN: 'Vui lòng phản hồi ngay.' },
  { id: 'i76', word: 'strategy', meaning: 'chiến lược', example: 'Develop a marketing strategy.', exampleVN: 'Phát triển chiến lược tiếp thị.' },
  { id: 'i77', word: 'analyze', meaning: 'phân tích', example: 'Analyze the sales data.', exampleVN: 'Phân tích dữ liệu bán hàng.' },
  { id: 'i78', word: 'survey', meaning: 'khảo sát', example: 'Conduct a customer survey.', exampleVN: 'Tiến hành khảo sát khách hàng.' },
  { id: 'i79', word: 'criteria', meaning: 'tiêu chí', example: 'Meet the selection criteria.', exampleVN: 'Đáp ứng tiêu chí tuyển chọn.' },
  { id: 'i80', word: 'evaluation', meaning: 'đánh giá', example: 'Annual performance evaluation.', exampleVN: 'Đánh giá hiệu suất hàng năm.' },
  { id: 'i81', word: 'objective', meaning: 'mục tiêu, khách quan', example: 'Set clear objectives.', exampleVN: 'Đặt mục tiêu rõ ràng.' },
  { id: 'i82', word: 'organize', meaning: 'tổ chức', example: 'Organize the company event.', exampleVN: 'Tổ chức sự kiện công ty.' },
  { id: 'i83', word: 'publish', meaning: 'xuất bản', example: 'Publish the annual report.', exampleVN: 'Xuất bản báo cáo thường niên.' },
  { id: 'i84', word: 'volunteer', meaning: 'tình nguyện viên', example: 'We need more volunteers.', exampleVN: 'Chúng tôi cần thêm tình nguyện viên.' },
  { id: 'i85', word: 'donation', meaning: 'quyên góp', example: 'Make a donation to charity.', exampleVN: 'Quyên góp cho từ thiện.' },
  { id: 'i86', word: 'recognize', meaning: 'nhận ra, công nhận', example: 'Recognize employee contributions.', exampleVN: 'Ghi nhận đóng góp của nhân viên.' },
  { id: 'i87', word: 'appropriate', meaning: 'thích hợp', example: 'Wear appropriate clothing.', exampleVN: 'Mặc quần áo phù hợp.' },
  { id: 'i88', word: 'regarding', meaning: 'liên quan đến', example: 'I am writing regarding your order.', exampleVN: 'Tôi viết thư liên quan đến đơn hàng.' },
  { id: 'i89', word: 'furthermore', meaning: 'hơn nữa', example: 'Furthermore, costs have been reduced.', exampleVN: 'Hơn nữa, chi phí đã được giảm.' },
  { id: 'i90', word: 'therefore', meaning: 'vì vậy', example: 'Therefore, we must act quickly.', exampleVN: 'Vì vậy, chúng ta phải hành động nhanh.' },
  { id: 'i91', word: 'nevertheless', meaning: 'tuy nhiên', example: 'Nevertheless, we will proceed.', exampleVN: 'Tuy nhiên, chúng tôi sẽ tiếp tục.' },
  { id: 'i92', word: 'meanwhile', meaning: 'trong khi đó', example: 'Meanwhile, sales are growing.', exampleVN: 'Trong khi đó, doanh số đang tăng.' },
  { id: 'i93', word: 'eventually', meaning: 'cuối cùng', example: 'He eventually got promoted.', exampleVN: 'Cuối cùng anh ấy được thăng chức.' },
  { id: 'i94', word: 'apparently', meaning: 'rõ ràng, có vẻ', example: 'Apparently, the deal fell through.', exampleVN: 'Có vẻ như thỏa thuận đã thất bại.' },
  { id: 'i95', word: 'regarding', meaning: 'về, liên quan đến', example: 'Questions regarding the schedule.', exampleVN: 'Câu hỏi về lịch trình.' },
  { id: 'i96', word: 'extensive', meaning: 'rộng rãi, sâu rộng', example: 'Extensive research was conducted.', exampleVN: 'Nghiên cứu sâu rộng đã được thực hiện.' },
  { id: 'i97', word: 'initiative', meaning: 'sáng kiến', example: 'Launch a new green initiative.', exampleVN: 'Khởi động sáng kiến xanh mới.' },
  { id: 'i98', word: 'anticipate', meaning: 'dự đoán', example: 'We anticipate strong demand.', exampleVN: 'Chúng tôi dự đoán nhu cầu cao.' },
  { id: 'i99', word: 'indicate', meaning: 'chỉ ra', example: 'Data indicates a positive trend.', exampleVN: 'Dữ liệu chỉ ra xu hướng tích cực.' },
  { id: 'i100', word: 'specialize', meaning: 'chuyên môn hóa', example: 'We specialize in IT solutions.', exampleVN: 'Chúng tôi chuyên về giải pháp CNTT.' },
];

export const processChunkInter1 = () => {
  return chunkInter1.map(w => ({ ...w, pos: '(n)' as string }));
};
