import { Word } from './types';

export const chunk21_raw: Omit<Word, 'id'>[] = [
  { word: "appointment", meaning: "cuộc hẹn", example: "I've got a dental appointment.", exampleVN: "Tôi có một cuộc hẹn nha khoa." },
  { word: "convenient", meaning: "thuận tiện, tiện lợi", example: "The clinic is very convenient for me.", exampleVN: "Phòng khám rất thuận tiện cho tôi." },
  { word: "take the afternoon off", meaning: "nghỉ làm buổi chiều", example: "I'm planning to take the afternoon off.", exampleVN: "Tôi dự định nghỉ làm buổi chiều." },
  { word: "patient", meaning: "bệnh nhân", example: "Dr. Molina sees patients in her office.", exampleVN: "Bác sĩ Molina khám cho bệnh nhân ở văn phòng." },
  { word: "receptionist", meaning: "lễ tân", example: "Looking for a new receptionist.", exampleVN: "Đang tìm một lễ tân mới." },
  { word: "permit", meaning: "cho phép", example: "Smoking is not permitted.", exampleVN: "Hút thuốc không được cho phép." },
  { word: "prescription", meaning: "đơn thuốc", example: "A prescription for antibiotics.", exampleVN: "Một đơn thuốc kháng sinh." },
  { word: "practice", meaning: "phòng khám, cơ sở kinh doanh", example: "Open her own dental practice.", exampleVN: "Mở phòng khám nha khoa riêng." },
  { word: "nutritional", meaning: "thuộc về dinh dưỡng", example: "Nutritional information.", exampleVN: "Thông tin dinh dưỡng." },
  { word: "knowledgeable", meaning: "có kiến thức, am hiểu", example: "Very knowledgeable about exercise.", exampleVN: "Rất am hiểu về tập thể dục." },
  { word: "routine", meaning: "thói quen, quy trình", example: "Online exercise routines.", exampleVN: "Các bài tập thể dục trực tuyến." },
  { word: "composer", meaning: "nhà soạn nhạc", example: "Leading composers.", exampleVN: "Những nhà soạn nhạc hàng đầu." },
  { word: "effectiveness", meaning: "tính hiệu quả", example: "Testing the effectiveness.", exampleVN: "Kiểm tra tính hiệu quả." },
  { word: "stay hydrated", meaning: "giữ cho cơ thể đủ nước", example: "Important to stay hydrated.", exampleVN: "Quan trọng là phải giữ đủ nước." },
  { word: "accounting department", meaning: "phòng kế toán", example: "The accounting department is on the third floor.", exampleVN: "Phòng kế toán nằm ở tầng ba." },
  { word: "rent out", meaning: "cho thuê", example: "Rent out her spare room.", exampleVN: "Cho thuê căn phòng trống." },
  { word: "burden", meaning: "gánh nặng", example: "A heavy burden.", exampleVN: "Một gánh nặng lớn." },
  { word: "feasible", meaning: "khả thi", example: "It is not feasible to finish today.", exampleVN: "Không khả thi để hoàn thành hôm nay." },
  { word: "tenant", meaning: "người thuê nhà", example: "The tenant moved out.", exampleVN: "Người thuê đã chuyển đi." },
  { word: "prototype", meaning: "nguyên mẫu", example: "Provide the prototype design.", exampleVN: "Cung cấp thiết kế nguyên mẫu." },
  { word: "originally", meaning: "ban đầu", example: "Originally planned for next year.", exampleVN: "Ban đầu được lên kế hoạch cho năm tới." },
  { word: "floor plan", meaning: "sơ đồ tầng, sơ đồ mặt bằng", example: "Floor plans for the new office.", exampleVN: "Sơ đồ mặt bằng cho văn phòng mới." },
  { word: "architect", meaning: "kiến trúc sư", example: "Ask the architect for drawings.", exampleVN: "Hỏi kiến trúc sư bản vẽ." },
  { word: "lumber", meaning: "gỗ xẻ", example: "Built using local lumber.", exampleVN: "Được xây bằng gỗ xẻ địa phương." },
  { word: "renovation", meaning: "sự cải tạo, tu sửa", example: "Undergoing a major renovation.", exampleVN: "Đang trải qua cuộc đại tu." },
  { word: "extensive", meaning: "sâu rộng, quy mô lớn", example: "Requires more extensive work.", exampleVN: "Cần nhiều công việc quy mô lớn hơn." },
  { word: "brand-new", meaning: "mới toanh", example: "This building is brand-new.", exampleVN: "Tòa nhà này mới toanh." },
  { word: "touch base", meaning: "liên lạc, trao đổi", example: "Calling to touch base with you.", exampleVN: "Gọi để trao đổi với bạn." },
  { word: "expertise", meaning: "chuyên môn", example: "Extensive expertise.", exampleVN: "Chuyên môn sâu rộng." },
  { word: "real estate", meaning: "bất động sản", example: "Historic estates.", exampleVN: "Các bất động sản lịch sử." },
  { word: "remodel", meaning: "tu sửa, cải tạo", example: "Remodel the entrance hall.", exampleVN: "Cải tạo lại sảnh." },
  { word: "be due", meaning: "đến hạn", example: "The project is due this Friday.", exampleVN: "Dự án đến hạn vào thứ Sáu." },
  { word: "bid", meaning: "sự đấu thầu", example: "Submitted a bid for the project.", exampleVN: "Đã nộp hồ sơ đấu thầu dự án." },
  { word: "city council", meaning: "hội đồng thành phố", example: "The city council approved.", exampleVN: "Hội đồng thành phố đã phê duyệt." },
  { word: "color scheme", meaning: "hệ màu, phối màu", example: "A blue and white color scheme.", exampleVN: "Một cách phối màu xanh và trắng." },
  { word: "my treat", meaning: "tôi bao, tôi mời", example: "It's my treat.", exampleVN: "Tới tôi mời." },
  { word: "corporate", meaning: "thuộc doanh nghiệp/công ty", example: "Corporate clients.", exampleVN: "Khách hàng công ty." },
  { word: "roll up one's sleeves", meaning: "xắn tay áo lên (bắt tay vào việc)", example: "Rolled up his sleeves.", exampleVN: "Đã xắn tay áo lên." },
  { word: "patron", meaning: "khách quen", example: "Many loyal patrons.", exampleVN: "Nhiều khách hàng quen." },
  { word: "detergent", meaning: "chất tẩy rửa", example: "Liquid laundry detergent.", exampleVN: "Nước giặt quần áo." },
  { word: "open-air market", meaning: "chợ ngoài trời", example: "At the open-air market.", exampleVN: "Tại khu chợ ngoài trời." },
  { word: "hardware store", meaning: "cửa hàng kim khí", example: "Go to the hardware store.", exampleVN: "Đến cửa hàng kim khí." },
  { word: "device", meaning: "thiết bị", example: "This device helps us.", exampleVN: "Thiết bị này giúp chúng ta." },
  { word: "database", meaning: "cơ sở dữ liệu", example: "Updating the customer database.", exampleVN: "Cập nhật cơ sở dữ liệu khách hàng." },
  { word: "worry-free", meaning: "không lo lắng", example: "Worry-free repair service.", exampleVN: "Dịch vụ sửa chữa không âu lo." },
  { word: "facilitate", meaning: "tạo điều kiện, làm cho dễ dàng", example: "Facilitate the process.", exampleVN: "Làm cho quy trình dễ dàng." },
  { word: "robotic", meaning: "thuộc rô-bốt", example: "Robotic vacuum cleaner.", exampleVN: "Máy hút bụi rô bốt." },
  { word: "from scratch", meaning: "từ đầu, từ con số không", example: "Build the software from scratch.", exampleVN: "Xây dựng phần mềm từ đầu." },
  { word: "admire", meaning: "ngưỡng mộ", example: "I admire your work.", exampleVN: "Tôi ngưỡng mộ thành quả của bạn." },
  { word: "be known for", meaning: "nổi tiếng vì", example: "Known for making mobile phones.", exampleVN: "Nổi tiếng vì sản xuất điện thoại." },
  { word: "be stuck", meaning: "bị kẹt", example: "We're stuck using the old lift.", exampleVN: "Chúng ta bị kẹt việc dùng thang máy cũ." },
  { word: "leverage", meaning: "tận dụng, đòn bẩy", example: "By leveraging social media.", exampleVN: "Bằng cách tận dụng mạng xã hội." },
  { word: "vending machine", meaning: "máy bán hàng tự động", example: "Vending machines in the lobby.", exampleVN: "Máy bán hàng ở sảnh đợi." },
  { word: "spreadsheet", meaning: "bảng tính", example: "Data into the spreadsheet.", exampleVN: "Dữ liệu vào bảng tính." },
  { word: "dispenser", meaning: "máy/hộp phân phát", example: "The soap dispenser.", exampleVN: "Hộp đựng xà phòng." },
  { word: "pump", meaning: "cái bơm", example: "Fuel injection pump.", exampleVN: "Bơm phun nhiên liệu." },
  { word: "unpredictability", meaning: "sự không thể dự đoán", example: "The unpredictability of this system.", exampleVN: "Sự không thể dự đoán của hệ thống này." },
  { word: "visibility", meaning: "độ nhận diện, khả năng hiển thị", example: "Increases its visibility.", exampleVN: "Tăng độ nhận diện." },
  { word: "transit", meaning: "vận tải", example: "Public transit system.", exampleVN: "Hệ thống vận tải công cộng." },
  { word: "notification", meaning: "thông báo", example: "Receive a notification.", exampleVN: "Nhận thông báo." },
  { word: "in-house", meaning: "nội bộ (tự làm)", example: "We do everything in-house.", exampleVN: "Chúng tôi tự làm mọi thứ nội bộ." },
  { word: "metal scrap", meaning: "kim loại vụn", example: "A lot of metal scrap.", exampleVN: "Nhiều kim loại vụn." },
  { word: "concrete", meaning: "bê tông", example: "Solid concrete.", exampleVN: "Bê tông cứng." },
  { word: "in the meantime", meaning: "trong lúc đó", example: "In the meantime, we will use the old car.", exampleVN: "Trong lúc đó, chúng tôi sẽ dùng xe cũ." },
  { word: "tracking system", meaning: "hệ thống theo dõi", example: "A GPS tracking system.", exampleVN: "Hệ thống theo dõi GPS." },
  { word: "engineering team", meaning: "đội ngũ kỹ thuật", example: "The engineering team requested.", exampleVN: "Đội ngũ kỹ thuật đã yêu cầu." },
  { word: "snowmobile", meaning: "xe trượt tuyết", example: "Rode a snowmobile.", exampleVN: "Đã lái xe trượt tuyết." },
  { word: "tourism", meaning: "ngành du lịch", example: "Tourism is the main source of income.", exampleVN: "Du lịch là nguồn thu nhập chính." },
  { word: "slow down", meaning: "chậm lại", example: "Need to slow down.", exampleVN: "Cần đi chậm lại." },
  { word: "kiosk", meaning: "quầy bán hàng, trạm thông tin", example: "At the information kiosk.", exampleVN: "Tại quầy thông tin." },
  { word: "lettering", meaning: "kiểu chữ", example: "The lettering on the sign.", exampleVN: "Kiểu chữ trên biển hiệu." },
  { word: "fuel-efficient", meaning: "tiết kiệm nhiên liệu", example: "A fuel-efficient car.", exampleVN: "Chiếc xe tiết kiệm nhiên liệu." },
  { word: "railing", meaning: "lan can, rào chắn", example: "Against the metal railing.", exampleVN: "Tựa vào lan can kim loại." },
  { word: "round-trip", meaning: "khứ hồi", example: "A round-trip ticket.", exampleVN: "Một vé khứ hồi." },
  { word: "insurance", meaning: "bảo hiểm", example: "Car insurance.", exampleVN: "Bảo hiểm xe hơi." },
  { word: "nonstop flight", meaning: "chuyến bay thẳng", example: "Nonstop flights are expensive.", exampleVN: "Các chuyến bay thẳng thường đắt." },
  { word: "shipment", meaning: "lô hàng, sự giao hàng", example: "Missing from the shipment.", exampleVN: "Thiếu trong lô hàng." },
  { word: "timetable", meaning: "thời khóa biểu, lịch trình", example: "Bus timetables.", exampleVN: "Lịch trình xe buýt." },
  { word: "fuel", meaning: "nhiên liệu", example: "Stop for some fuel.", exampleVN: "Dừng lại đổ nhiên liệu." },
  { word: "ride", meaning: "đi xe", example: "Ride his bike.", exampleVN: "Đạp xe." },
  { word: "lobby", meaning: "sảnh chờ", example: "Wait in the hotel lobby.", exampleVN: "Đợi ở sảnh khách sạn." },
  { word: "frequently", meaning: "thường xuyên", example: "Run frequently.", exampleVN: "Chạy thường xuyên." },
  { word: "reimbursement", meaning: "sự hoàn trả", example: "Claim reimbursement.", exampleVN: "Yêu cầu hoàn trả." },
  { word: "alignment", meaning: "sự căn chỉnh", example: "Need proper alignment.", exampleVN: "Cần căn chỉnh đúng." },
  { word: "surge pricing", meaning: "định giá tăng vọt", example: "Use surge pricing.", exampleVN: "Sử dụng định giá tăng vọt." },
  { word: "garage", meaning: "nhà xe", example: "Parked in the garage.", exampleVN: "Đã đỗ trong nhà xe." },
  { word: "catering", meaning: "dịch vụ cung cấp đồ ăn", example: "Catering order.", exampleVN: "Đơn hàng đồ ăn." },
  { word: "station", meaning: "nhà ga, trạm", example: "The station is on Mulberry Avenue.", exampleVN: "Nhà ga nằm trên đại lộ Mulberry." },
  { word: "congested", meaning: "tắc nghẽn", example: "Routinely congested.", exampleVN: "Thường xuyên tắc nghẽn." },
  { word: "hospitality", meaning: "ngành khách sạn/dịch vụ", example: "Hospitality conference.", exampleVN: "Hội nghị ngành khách sạn." },
  { word: "all-access", meaning: "truy cập toàn bộ", example: "All-access tour.", exampleVN: "Chuyến tham quan trọn gói." },
  { word: "shuttle bus", meaning: "xe buýt đưa đón", example: "A shuttle bus will meet us.", exampleVN: "Xe buýt đưa đón sẽ gặp chúng ta." }
];

export function processChunk21(): Word[] {
  return chunk21_raw.map((w, index) => {
    return {
      ...w,
      id: `c21_${index}`,
      pos: '(n/a)'
    };
  });
}
