import { Word } from './types';

export const chunk9: Word[] = [
  { id: '1001', word: 'coast', meaning: 'bờ biển', example: 'East coast.', exampleVN: 'Bờ biển phía đông.' },
  { id: '1002', word: 'coat', meaning: 'áo khoác', example: 'Winter coat.', exampleVN: 'Áo khoác mùa đông.' },
  { id: '1003', word: 'code', meaning: 'mã số', example: 'Dress code.', exampleVN: 'Quy định về trang phục.' },
  { id: '1004', word: 'coffee', meaning: 'cà phê', example: 'Black coffee.', exampleVN: 'Cà phê đen.' },
  { id: '1005', word: 'cognitive', meaning: 'nhận thức', example: 'Cognitive skills.', exampleVN: 'Có kỹ năng nhận thức.' },
  { id: '1006', word: 'cold', meaning: 'lạnh', example: 'Catch a cold.', exampleVN: 'Bị cảm lạnh.' },
  { id: '1007', word: 'collapse', meaning: 'sụp đổ', example: 'Building collapse.', exampleVN: 'Sụp đổ tòa nhà.' },
  { id: '1008', word: 'colleague', meaning: 'đồng nghiệp', example: 'Former colleague.', exampleVN: 'Đồng nghiệp cũ.' },
  { id: '1009', word: 'collect', meaning: 'thu thập', example: 'Collect data.', exampleVN: 'Thu thập dữ liệu.' },
  { id: '1010', word: 'collection', meaning: 'bộ sưu tập', example: 'Art collection.', exampleVN: 'Bộ sưu tập nghệ thuật.' },
  { id: '1011', word: 'collective', meaning: 'tập thể', example: 'Collective effort.', exampleVN: 'Nỗ lực tập thể.' },
  { id: '1012', word: 'college', meaning: 'trường cao đẳng', example: 'Go to college.', exampleVN: 'Học đại học.' },
  { id: '1013', word: 'color', meaning: 'màu sắc', example: 'Bright color.', exampleVN: 'Màu sắc tươi sáng.' },
  { id: '1014', word: 'column', meaning: 'cột', example: 'Marble column.', exampleVN: 'Cột đá cẩm thạch.' },
  { id: '1015', word: 'combination', meaning: 'sự kết hợp', example: 'Winning combination.', exampleVN: 'Sự kết hợp chiến thắng.' },
  { id: '1016', word: 'combine', meaning: 'kết hợp', example: 'Combine forces.', exampleVN: 'Kết hợp lực lượng.' },
  { id: '1017', word: 'come', meaning: 'đến', example: 'Come back.', exampleVN: 'Quay lại.' },
  { id: '1018', word: 'comedy', meaning: 'hài kịch', example: 'Romantic comedy.', exampleVN: 'Phim hài lãng mạn.' },
  { id: '1019', word: 'comfort', meaning: 'sự thoải mái', example: 'Provide comfort.', exampleVN: 'Mang lại sự thoải mái.' },
  { id: '1020', word: 'comfortable', meaning: 'thoải mái', example: 'Comfortable bed.', exampleVN: 'Một chiếc giường thoải mái.' },
  { id: '1021', word: 'command', meaning: 'lệnh', example: 'Give a command.', exampleVN: 'Ra lệnh.' },
  { id: '1022', word: 'commander', meaning: 'chỉ huy', example: 'Base commander.', exampleVN: 'Chỉ huy căn cứ.' },
  { id: '1023', word: 'comment', meaning: 'bình luận', example: 'Leave a comment.', exampleVN: 'Để lại bình luận.' },
  { id: '1024', word: 'commercial', meaning: 'thương mại', example: 'Commercial break.', exampleVN: 'Nghỉ thương mại.' },
  { id: '1025', word: 'commission', meaning: 'tiền hoa hồng', example: 'Sales commission.', exampleVN: 'Hoa hồng bán hàng.' },
  { id: '1026', word: 'commit', meaning: 'cam kết, phạm', example: 'Commit a crime.', exampleVN: 'Phạm tội.' },
  { id: '1027', word: 'commitment', meaning: 'sự cam kết', example: 'Make a commitment.', exampleVN: 'Đưa ra cam kết.' },
  { id: '1028', word: 'committee', meaning: 'ủy ban', example: 'Join a committee.', exampleVN: 'Tham gia một ủy ban.' },
  { id: '1029', word: 'common', meaning: 'phổ biến', example: 'Common sense.', exampleVN: 'Có ý thức chung.' },
  { id: '1030', word: 'communicate', meaning: 'giao tiếp', example: 'Communicate well.', exampleVN: 'Giao tiếp tốt.' },
  { id: '1031', word: 'communication', meaning: 'sự giao tiếp', example: 'Effective communication.', exampleVN: 'Giao tiếp hiệu quả.' },
  { id: '1032', word: 'community', meaning: 'cộng đồng', example: 'Local community.', exampleVN: 'Cộng đồng địa phương.' },
  { id: '1033', word: 'company', meaning: 'công ty', example: 'Large company.', exampleVN: 'Công ty lớn.' },
  { id: '1034', word: 'compare', meaning: 'so sánh', example: 'Compare prices.', exampleVN: 'So sánh giá cả.' },
  { id: '1035', word: 'comparison', meaning: 'sự so sánh', example: 'Make a comparison.', exampleVN: 'So sánh.' },
  { id: '1036', word: 'compete', meaning: 'cạnh tranh', example: 'Compete for.', exampleVN: 'Cạnh tranh để có được.' },
  { id: '1037', word: 'competition', meaning: 'sự cạnh tranh', example: 'Fierce competition.', exampleVN: 'Sự cạnh tranh khốc liệt.' },
  { id: '1038', word: 'competitive', meaning: 'có tính cạnh tranh', example: 'Competitive advantage.', exampleVN: 'Có lợi thế cạnh tranh.' },
  { id: '1039', word: 'competitor', meaning: 'đối thủ', example: 'Main competitor.', exampleVN: 'Đối thủ cạnh tranh chính.' },
  { id: '1040', word: 'complain', meaning: 'phàn nàn', example: 'Complain about.', exampleVN: 'Phàn nàn về.' },
  { id: '1041', word: 'complaint', meaning: 'lời phàn nàn', example: 'File a complaint.', exampleVN: 'Nộp đơn khiếu nại.' },
  { id: '1042', word: 'complete', meaning: 'hoàn thành', example: 'Complete a task.', exampleVN: 'Hoàn thành một nhiệm vụ.' },
  { id: '1043', word: 'completely', meaning: 'hoàn toàn', example: 'Completely different.', exampleVN: 'Hoàn toàn khác biệt.' },
  { id: '1044', word: 'complex', meaning: 'phức tạp', example: 'Complex issue.', exampleVN: 'Giải quyết vấn đề phức tạp.' },
  { id: '1045', word: 'complicate', meaning: 'làm phức tạp', example: "Don't complicate it.", exampleVN: "Đừng làm phức tạp nó." },
  { id: '1046', word: 'complicated', meaning: 'phức tạp', example: 'Complicated problem.', exampleVN: 'Giải quyết vấn đề phức tạp.' },
  { id: '1047', word: 'component', meaning: 'thành phần', example: 'Key component.', exampleVN: 'Thành phần chính.' },
  { id: '1048', word: 'compose', meaning: 'soạn thảo', example: 'Compose a letter.', exampleVN: 'Soạn một lá thư.' },
  { id: '1049', word: 'composition', meaning: 'sự cấu thành', example: 'Chemical composition.', exampleVN: 'Thành phần hóa học.' },
  { id: '1050', word: 'comprehensive', meaning: 'toàn diện', example: 'Comprehensive guide.', exampleVN: 'Hướng dẫn toàn diện.' },
  { id: '1051', word: 'computer', meaning: 'máy tính', example: 'Computer screen.', exampleVN: 'Tới màn hình máy tính.' },
  { id: '1052', word: 'concentrate', meaning: 'tập trung', example: 'Concentrate on.', exampleVN: 'Tập trung vào.' },
  { id: '1053', word: 'concentration', meaning: 'sự tập trung', example: 'High concentration.', exampleVN: 'Sự tập trung cao độ.' },
  { id: '1054', word: 'concept', meaning: 'khái niệm', example: 'Basic concept.', exampleVN: 'Khái niệm cơ bản.' },
  { id: '1055', word: 'concern', meaning: 'mối quan tâm', example: 'Express concern.', exampleVN: 'Bày tỏ mối quan ngại.' },
  { id: '1056', word: 'concerned', meaning: 'quan tâm', example: 'Be concerned about.', exampleVN: 'Quan tâm đến.' },
  { id: '1057', word: 'concert', meaning: 'buổi hòa nhạc', example: 'Pop concert.', exampleVN: 'Buổi hòa nhạc pop.' },
  { id: '1058', word: 'conclude', meaning: 'kết luận', example: 'Conclude the meeting.', exampleVN: 'Kết thúc cuộc họp.' },
  { id: '1059', word: 'conclusion', meaning: 'phần kết luận', example: 'Draw a conclusion.', exampleVN: 'Rút ra kết luận.' },
  { id: '1060', word: 'concrete', meaning: 'bê tông, cụ thể', example: 'Concrete evidence.', exampleVN: 'Bằng chứng cụ thể.' },
  { id: '1061', word: 'condition', meaning: 'điều kiện', example: 'Working condition.', exampleVN: 'Điều kiện làm việc.' },
  { id: '1062', word: 'conduct', meaning: 'hành vi, tiến hành', example: 'Conduct research.', exampleVN: 'Tiến hành nghiên cứu.' },
  { id: '1063', word: 'conference', meaning: 'hội nghị', example: 'Press conference.', exampleVN: 'Buổi họp báo.' },
  { id: '1064', word: 'confidence', meaning: 'sự tự tin', example: 'Gain confidence.', exampleVN: 'Đạt được sự tự tin.' },
  { id: '1065', word: 'confident', meaning: 'tự tin', example: 'Feel confident.', exampleVN: 'Cảm thấy tự tin.' },
  { id: '1066', word: 'confirm', meaning: 'xác nhận', example: 'Confirm booking.', exampleVN: 'Xác nhận đặt phòng.' },
  { id: '1067', word: 'confirmation', meaning: 'sự xác nhận', example: 'Booking confirmation.', exampleVN: 'Xác nhận đặt phòng.' },
  { id: '1068', word: 'conflict', meaning: 'xung đột', example: 'Resolve a conflict.', exampleVN: 'Giải quyết xung đột.' },
  { id: '1069', word: 'confront', meaning: 'đối mặt', example: 'Confront the issue.', exampleVN: 'Đối mặt với vấn đề này.' },
  { id: '1070', word: 'confusion', meaning: 'sự nhầm lẫn', example: 'Cause confusion.', exampleVN: 'Gây ra sự nhầm lẫn.' },
  { id: '1071', word: 'congress', meaning: 'đại hội', example: 'Member of congress.', exampleVN: 'Thành viên của quốc hội.' },
  { id: '1072', word: 'connect', meaning: 'kết nối', example: 'Connect the dots.', exampleVN: 'Kết nối các dấu chấm.' },
  { id: '1073', word: 'connection', meaning: 'sự kết nối', example: 'Internet connection.', exampleVN: 'Kết nối internet.' },
  { id: '1074', word: 'consequence', meaning: 'hậu quả', example: 'Face consequence.', exampleVN: 'Hậu quả đối mặt.' },
  { id: '1075', word: 'conservative', meaning: 'thận trọng', example: 'Conservative estimate.', exampleVN: 'Ước tính thận trọng.' },
  { id: '1076', word: 'consider', meaning: 'xem xét', example: 'Consider an offer.', exampleVN: 'Xem xét một lời đề nghị.' },
  { id: '1077', word: 'considerable', meaning: 'đáng kể', example: 'Considerable amount.', exampleVN: 'Một số lượng đáng kể.' },
  { id: '1078', word: 'consideration', meaning: 'sự cân nhắc', example: 'Take into consideration.', exampleVN: 'Xem xét.' },
  { id: '1079', word: 'consist', meaning: 'bao gồm', example: 'Consist of.', exampleVN: 'Bao gồm.' },
  { id: '1080', word: 'consistent', meaning: 'nhất quán', example: 'Consistent quality.', exampleVN: 'Chất lượng nhất quán.' },
  { id: '1081', word: 'constant', meaning: 'liên tục', example: 'Constant change.', exampleVN: 'Thay đổi liên tục.' },
  { id: '1082', word: 'constantly', meaning: 'liên tục', example: 'Constantly improve.', exampleVN: 'không ngừng cải thiện.' },
  { id: '1083', word: 'constitute', meaning: 'cấu thành', example: 'Constitute a threat.', exampleVN: 'Tạo thành một mối đe dọa.' },
  { id: '1084', word: 'construct', meaning: 'xây dựng', example: 'Construct a building.', exampleVN: 'Xây dựng một tòa nhà.' },
  { id: '1085', word: 'construction', meaning: 'sự xây dựng', example: 'Under construction.', exampleVN: 'Được xây dựng.' },
  { id: '1086', word: 'consult', meaning: 'tham khảo', example: 'Consult a doctor.', exampleVN: 'Tham khảo ý kiến ​​bác sĩ.' },
  { id: '1087', word: 'consultant', meaning: 'chuyên viên tư vấn', example: 'Business consultant.', exampleVN: 'Tư vấn kinh doanh.' },
  { id: '1088', word: 'consume', meaning: 'tiêu thụ', example: 'Consume alcohol.', exampleVN: 'Uống rượu.' },
  { id: '1089', word: 'consumer', meaning: 'nhười tiêu dùng', example: 'Consumer rights.', exampleVN: 'Quyền lợi của người tiêu dùng.' },
  { id: '1090', word: 'consumption', meaning: 'sự tiêu thụ', example: 'Energy consumption.', exampleVN: 'Tiêu thụ năng lượng.' },
  { id: '1091', word: 'contact', meaning: 'liên lạc', example: 'Contact details.', exampleVN: 'Liên hệ chi tiết.' },
  { id: '1092', word: 'contain', meaning: 'chứa', example: 'Contain sugar.', exampleVN: 'Chứa đường.' },
  { id: '1093', word: 'container', meaning: 'thùng chứa', example: 'Storage container.', exampleVN: 'Container lưu trữ.' },
  { id: '1094', word: 'contemporary', meaning: 'đương đại', example: 'Contemporary art.', exampleVN: 'Nghệ thuật đương đại.' },
  { id: '1095', word: 'content', meaning: 'nội dung', example: 'Table of content.', exampleVN: 'Mục lục.' },
  { id: '1096', word: 'contest', meaning: 'cuộc thi', example: 'Beauty contest.', exampleVN: 'Cuộc thi sắc đẹp.' },
  { id: '1097', word: 'context', meaning: 'bối cảnh', example: 'In this context.', exampleVN: 'Trong bối cảnh này.' },
  { id: '1098', word: 'continue', meaning: 'tiếp tục', example: 'Continue to grow.', exampleVN: 'Tiếp tục phát triển.' },
  { id: '1099', word: 'continued', meaning: 'tiếp tục', example: 'Continued success.', exampleVN: 'Tiếp tục thành công.' },
  { id: '1100', word: 'contract', meaning: 'hợp đồng', example: 'Sign a contract.', exampleVN: 'Ký hợp đồng.' }
];

export const processChunk9 = () => chunk9;
