import { Word } from './types';

export const chunkAdvanced: Word[] = [
  { id: 'a1', word: 'mitigate', meaning: 'giảm nhẹ, làm dịu bớt', example: 'Measures were taken to mitigate the environmental impact.', exampleVN: 'Các biện pháp đã được thực hiện để giảm thiểu tác động môi trường.' },
  { id: 'a2', word: 'ubiquitous', meaning: 'phổ biến, có mặt khắp nơi', example: 'Cell phones are ubiquitous in modern society.', exampleVN: 'Điện thoại di động có mặt khắp nơi trong xã hội hiện đại.' },
  { id: 'a3', word: 'consolidate', meaning: 'củng cố, hợp nhất', example: 'The company plans to consolidate its position in the market.', exampleVN: 'Công ty kế hoạch củng cố vị thế của mình trên thị trường.' },
  { id: 'a4', word: 'discrepancy', meaning: 'sự khác biệt, không nhất quán', example: 'There was a discrepancy between the two reports.', exampleVN: 'Có sự khác biệt giữa hai báo cáo.' },
  { id: 'a5', word: 'prerequisite', meaning: 'điều kiện tiên quyết', example: 'A degree is a prerequisite for this job.', exampleVN: 'Bằng cấp là điều kiện tiên quyết cho công việc này.' },
  { id: 'a6', word: 'unprecedented', meaning: 'chưa từng có', example: 'Unprecedented in recent history.', exampleVN: 'Tình huống này chưa từng có trong lịch sử gần đây.' },
  { id: 'a7', word: 'mandatory', meaning: 'bắt buộc', example: 'Wearing a helmet is mandatory while riding a bike.', exampleVN: 'Đội mũ bảo hiểm là bắt buộc khi đi xe đạp.' },
  { id: 'a8', word: 'feasible', meaning: 'khả thi', example: 'It is not feasible to complete the project in one day.', exampleVN: 'Không khả thi để hoàn thành dự án trong một ngày.' },
  { id: 'a9', word: 'volatile', meaning: 'biến động, không ổn định', example: 'The stock market is extremely volatile right now.', exampleVN: 'Thị trường chứng khoán hiện đang vô cùng biến động.' },
  { id: 'a10', word: 'stagnant', meaning: 'trì trệ, không phát triển', example: 'The economy has been stagnant for several years.', exampleVN: 'Nền kinh tế đã trì trệ trong vài năm qua.' },
  { id: 'a11', word: 'lucrative', meaning: 'có lợi, sinh lợi cao', example: 'He landed a lucrative contract with a major firm.', exampleVN: 'Anh ấy đã giành được một hợp đồng béo bở với một công ty lớn.' },
  { id: 'a12', word: 'adhere', meaning: 'tuân thủ, dính vào', example: 'Staff must adhere to strict safety guidelines.', exampleVN: 'Nhân viên phải tuân thủ nghiêm ngặt các hướng dẫn an toàn.' },
  { id: 'a13', word: 'bolster', meaning: 'ủng hộ, củng cố', example: 'Additional data was needed to bolster their argument.', exampleVN: 'Cần thêm dữ liệu để củng cố lập luận của họ.' },
  { id: 'a14', word: 'curtail', meaning: 'cắt giảm', example: 'We must curtail our spending to stay within budget.', exampleVN: 'Chúng ta phải cắt giảm chi tiêu để nằm trong ngân sách.' },
  { id: 'a15', word: 'deteriorate', meaning: 'xấu đi, suy yếu', example: 'The condition of the building began to deteriorate rapidly.', exampleVN: 'Tình trạng của tòa nhà bắt đầu xuống cấp nhanh chóng.' },
  { id: 'a16', word: 'elucidate', meaning: 'làm sáng tỏ', example: 'The professor attempted to elucidate the complex theory.', exampleVN: 'Giáo sư đã cố gắng làm sáng tỏ lý thuyết phức tạp.' },
  { id: 'a17', word: 'fluctuate', meaning: 'biến động, dao động', example: 'Oil prices fluctuate according to global demand.', exampleVN: 'Giá dầu biến động theo nhu cầu toàn cầu.' },
  { id: 'a18', word: 'hinder', meaning: 'cản trở', example: 'Language barriers often hinder effective communication.', exampleVN: 'Rào cản ngôn ngữ thường cản trở giao tiếp hiệu quả.' },
  { id: 'a19', word: 'incumbent', meaning: 'đang đương nhiệm; là trách nhiệm của', example: 'It is incumbent upon the manager to ensure safety.', exampleVN: 'Người quản lý có trách nhiệm đảm bảo an toàn.' },
  { id: 'a20', word: 'jeopardize', meaning: 'gây nguy hiểm, hủy hoại', example: 'Any bad publicity could jeopardize our chances of winning.', exampleVN: 'Bất kỳ sự công khai xấu nào cũng có thể gây nguy hiểm cho cơ hội chiến thắng của chúng ta.' },
  { id: 'a21', word: 'leverage', meaning: 'tận dụng; đòn bẩy', example: 'We can leverage our existing contacts to grow the business.', exampleVN: 'Chúng ta có thể tận dụng các liên hệ hiện có để phát triển doanh nghiệp.' },
  { id: 'a22', word: 'nullify', meaning: 'vô hiệu hóa', example: 'The judge nullified the contract due to fraud.', exampleVN: 'Thẩm phán đã vô hiệu hóa hợp đồng do gian lận.' },
  { id: 'a23', word: 'ostensible', meaning: 'có vẻ là, bề ngoài là', example: 'The ostensible reason for his visit was to say hello.', exampleVN: 'Lý do bề ngoài cho chuyến thăm của anh ấy là để chào hỏi.' },
  { id: 'a24', word: 'permeate', meaning: 'lan tỏa, thấm qua', example: 'A sense of optimism began to permeate the company.', exampleVN: 'Một cảm giác lạc quan bắt đầu lan tỏa khắp công ty.' },
  { id: 'a26', word: 'rectify', meaning: 'chỉnh sửa, khắc phục', example: 'The firm promised to rectify the errors immediately.', exampleVN: 'Công ty hứa sẽ khắc phục các lỗi ngay lập tức.' },
  { id: 'a27', word: 'scrutinize', meaning: 'xem xét kỹ lưỡng', example: 'Every detail of the proposal was scrutinized by the board.', exampleVN: 'Mọi chi tiết của đề xuất đều được hội đồng quản trị xem xét kỹ lưỡng.' },
  { id: 'a28', word: 'tenacious', meaning: 'kiên trì, bền bỉ', example: 'She was a tenacious investigator who never gave up.', exampleVN: 'Cô ấy là một điều tra viên kiên trì, người không bao giờ bỏ cuộc.' },
  { id: 'a29', word: 'unilateral', meaning: 'đơn phương', example: 'The country made a unilateral decision to withdraw.', exampleVN: 'Quốc gia này đã đưa ra quyết định đơn phương rút lui.' },
  { id: 'a30', word: 'vacillate', meaning: 'do dự, lưỡng lự', example: 'He vacillated between the two options for hours.', exampleVN: 'Anh ấy đã do dự giữa hai lựa chọn trong nhiều giờ.' },
  { id: 'a31', word: 'warrant', meaning: 'đảm bảo; trát lệnh', example: 'The situation didn\'t warrant such drastic measures.', exampleVN: 'Tình hình không đảm bảo cho những biện pháp quyết liệt như vậy.' },
  { id: 'a32', word: 'yield', meaning: 'mang lại; sản lượng', example: 'The investment should yield a high return.', exampleVN: 'Khoản đầu tư sẽ mang lại lợi nhuận cao.' },
  { id: 'a33', word: 'zealous', meaning: 'nhiệt tình, hăng hái', example: 'They are zealous defenders of human rights.', exampleVN: 'Họ là những người bảo vệ nhân quyền hăng hái.' },
  { id: 'a39', word: 'frugal', meaning: 'tiết kiệm, thanh đạm', example: 'He lives a frugal lifestyle to save money.', exampleVN: 'Anh ấy sống một phong cách sống tiết kiệm để dành tiền.' },
  { id: 'a40', word: 'gregarious', meaning: 'thích giao du, hòa đồng', example: 'He is a gregarious person who enjoys meeting new people.', exampleVN: 'Anh ấy là một người hòa đồng, thích gặp gỡ những người mới.' },
  { id: 'a42', word: 'inevitable', meaning: 'tất yếu, không thể tránh khỏi', example: 'Change is an inevitable part of life.', exampleVN: 'Thay đổi là một phần tất yếu của cuộc sống.' },
  { id: 'a43', word: 'judicious', meaning: 'sáng suốt, khôn ngoan', example: 'The manager made a judicious choice in hiring him.', exampleVN: 'Người quản lý đã đưa ra một lựa chọn khôn ngoan khi thuê anh ta.' },
  { id: 'a51', word: 'resilient', meaning: 'kiên cường, đàn hồi', example: 'Children are often more resilient than adults.', exampleVN: 'Trẻ em thường kiên cường hơn người lớn.' },
  { id: 'a61', word: 'benchmark', meaning: 'điểm chuẩn, mốc chuẩn', example: 'The company set a new benchmark for quality.', exampleVN: 'Công ty đã đặt ra một tiêu chuẩn mới cho chất lượng.' },
  { id: 'a65', word: 'facilitate', meaning: 'tạo điều kiện thuận lợi', example: 'New software will facilitate the data analysis.', exampleVN: 'Phần mềm mới sẽ tạo điều kiện thuận lợi cho việc phân tích dữ liệu.' },
  { id: 'a68', word: 'incentive', meaning: 'động lực, sự khuyến khích', example: 'The bonus provided an extra incentive to work harder.', exampleVN: 'Tiền thưởng đã cung cấp thêm động lực để làm việc chăm chỉ hơn.' },
  { id: 'a72', word: 'meticulous', meaning: 'tỉ mỉ, kỹ lưỡng', example: 'She is meticulous in her accounting procedures.', exampleVN: 'Cô ấy rất tỉ mỉ trong các thủ tục kế toán của mình.' },
  { id: 'a73', word: 'nominal', meaning: 'không đáng kể, nhỏ bé (về giá)', example: 'A nominal fee is charged for admission.', exampleVN: 'Một khoản phí nhỏ được tính cho việc vào cửa.' },
  { id: 'a76', word: 'quota', meaning: 'hạn ngạch, chỉ tiêu', example: 'The factory has met its production quota for the month.', exampleVN: 'Nhà máy đã đạt chỉ tiêu sản xuất trong tháng.' },
  { id: 'a77', word: 'redundant', meaning: 'dư thừa; bị sa thải', example: 'New technology has made many old skills redundant.', exampleVN: 'Công nghệ mới đã làm cho nhiều kỹ năng cũ trở nên dư thừa.' },
  { id: 'a78', word: 'subsidy', meaning: 'tiền trợ cấp (chính phủ)', example: 'Farmers receive a subsidy for growing certain crops.', exampleVN: 'Nông dân nhận được trợ cấp cho việc trồng một số loại cây trồng.' },
  { id: 'a79', word: 'tangible', meaning: 'hữu hình, rõ ràng', example: 'The results are finally tangible after months of work.', exampleVN: 'Các kết quả cuối cùng đã rõ ràng sau nhiều tháng làm việc.' },
  { id: 'a80', word: 'unilateral', meaning: 'đơn phương', example: 'The deal was cancelled by a unilateral decision.', exampleVN: 'Thỏa thuận đã bị hủy do một quyết định đơn phương.' },
  { id: 'a81', word: 'vantage', meaning: 'thuận lợi; lợi thế', example: 'From his vantage point, he could see the entire valley.', exampleVN: 'Từ vị trí thuận lợi của mình, anh có thể nhìn thấy toàn bộ thung lũng.' },
  { id: 'a82', word: 'wholesale', meaning: 'bán buôn, sỉ', example: 'They buy the products at wholesale prices.', exampleVN: 'Họ mua sản phẩm với giá bán buôn.' },
  { id: 'a88', word: 'complacent', meaning: 'tự mãn', example: 'We cannot afford to become complacent about safety.', exampleVN: 'Chúng ta không thể để mình trở nên tự mãn về an toàn.' },
  { id: 'a90', word: 'elicit', meaning: 'gợi ra, moi ra', example: 'The questionnaire was designed to elicit information.', exampleVN: 'Bản câu hỏi được thiết kế để gợi ra thông tin.' },
  { id: 'a103', word: 'salient', meaning: 'nổi bật, quan trọng nhất', example: 'What are the salient features of the proposal?', exampleVN: 'Những đặc điểm nổi bật nhất của đề xuất là gì?' },
  { id: 'a104', word: 'tenure', meaning: 'nhiệm kỳ, sự nắm giữ', example: 'During his tenure as CEO, the company expanded.', exampleVN: 'Trong suốt nhiệm kỳ làm CEO của mình, công ty đã mở rộng.' },
  { id: 'a110', word: 'allocation', meaning: 'sự phân bổ', example: 'The allocation of resources was not equal.', exampleVN: 'Việc phân bổ nguồn lực không đồng đều.' },
  { id: 'a111', word: 'breach', meaning: 'sự vi phạm (hợp đồng/luật)', example: 'The company was sued for breach of contract.', exampleVN: 'Công ty đã bị kiện vì vi phạm hợp đồng.' },
  { id: 'a112', word: 'circumvent', meaning: 'né tránh, lách (luật)', example: 'They found a way to circumvent the regulations.', exampleVN: 'Họ đã tìm ra cách để lách các quy định.' },
  { id: 'a113', word: 'divest', meaning: 'thoái vốn, tước bỏ', example: 'The company decided to divest itself of its loss-making branches.', exampleVN: 'Công ty đã quyết định thoái vốn khỏi các chi nhánh thua lỗ.' },
  { id: 'a114', word: 'encompass', meaning: 'bao gồm, bao quanh', example: 'The group encompasses a wide range of interests.', exampleVN: 'Nhóm bao gồm một loạt các mối quan tâm.' },
  { id: 'a115', word: 'fiscal', meaning: 'thuộc tài chính/ngân khố', example: 'They are facing a major fiscal crisis.', exampleVN: 'Họ đang đối mặt với một cuộc khủng hoảng tài chính lớn.' },
  { id: 'a116', word: 'grievance', meaning: 'lời phàn nàn, sự bất bình', example: 'He had a long-standing grievance against the company.', exampleVN: 'Anh ấy đã có một sự bất bình lâu dài đối với công ty.' },
  { id: 'a118', word: 'impede', meaning: 'cản trở, ngăn cản', example: 'The snow will impede our progress.', exampleVN: 'Tuyết sẽ cản trở tiến độ của chúng ta.' },
  { id: 'a120', word: 'litigation', meaning: 'sự kiện tụng', example: 'The company is currently involved in litigation.', exampleVN: 'Công ty hiện đang tham gia vào việc kiện tụng.' },
  { id: 'a121', word: 'merger', meaning: 'sự sáp nhập', example: 'The merger of the two airlines was announced today.', exampleVN: 'Sự sáp nhập của hai hãng hàng không đã được thông báo hôm nay.' },
  { id: 'a122', word: 'negligible', meaning: 'không đáng kể', example: 'The cost of the repair was negligible.', exampleVN: 'Chi phí sửa chữa là không đáng kể.' },
  { id: 'a123', word: 'outlay', meaning: 'kinh phí, sự chi tiêu', example: 'The project requires a huge capital outlay.', exampleVN: 'Dự án yêu cầu một khoản chi phí vốn lớn.' },
  { id: 'a124', word: 'portfolio', meaning: 'danh mục đầu tư, hồ sơ năng lực', example: 'He manages a large portfolio of stocks and bonds.', exampleVN: 'Ông quản lý một danh mục đầu tư lớn gồm cổ phiếu và trái phiếu.' },
  { id: 'a125', word: 'quota', meaning: 'hạn ngạch', example: 'The government imposed a quota on imported cars.', exampleVN: 'Chính phủ đã áp đặt hạn ngạch đối với xe hơi nhập khẩu.' },
  { id: 'a126', word: 'solicit', meaning: 'khẩn khoản, nài xin', example: 'The organization is soliciting donations for the earthquake victims.', exampleVN: 'Tổ chức đang kêu gọi quyên góp cho các nạn nhân động đất.' },
  { id: 'a127', word: 'turnover', meaning: 'doanh thu; tỉ lệ thay thế nhân viên', example: 'The company has a high turnover of staff.', exampleVN: 'Công ty có tỉ lệ thay thế nhân viên cao.' },
  { id: 'a128', word: 'underpin', meaning: 'làm nền móng, củng cố', example: 'The reports underpin the need for immediate action.', exampleVN: 'Các báo cáo củng cố nhu cầu hành động ngay lập tức.' },
  { id: 'a129', word: 'viability', meaning: 'khả năng tồn tại, tính khả thi', example: 'Assess the economic viability of the project.', exampleVN: 'Đánh giá tính khả thi về kinh tế của dự án.' },
  { id: 'a130', word: 'waive', meaning: 'từ bỏ, khước từ (quyền lợi)', example: 'The fee will be waived for students.', exampleVN: 'Phí sẽ được miễn cho sinh viên.' },
  { id: 'a131', word: 'accrue', meaning: 'tích lũy, dồn lại', example: 'Interest will accrue from the date of investment.', exampleVN: 'Lãi suất sẽ được tích lũy kể từ ngày đầu tư.' },
  { id: 'a133', word: 'counterfeit', meaning: 'giả mạo', example: 'It is a crime to possess counterfeit currency.', exampleVN: 'Sở hữu tiền giả là một tội ác.' },
  { id: 'a134', word: 'downturn', meaning: 'sự suy thoái', example: 'The economic downturn has affected many businesses.', exampleVN: 'Sự suy thoái kinh tế đã ảnh hưởng đến nhiều doanh nghiệp.' },
  { id: 'a135', word: 'embargo', meaning: 'lệnh cấm vận', example: 'The government imposed a trade embargo on the country.', exampleVN: 'Chính phủ đã áp đặt lệnh cấm vận thương mại đối với quốc gia này.' },
  { id: 'a136', word: 'franchise', meaning: 'nhượng quyền thương mại', example: 'They own a fast-food franchise in the city center.', exampleVN: 'Họ sở hữu một cửa hàng nhượng quyền thức ăn nhanh ở trung tâm thành phố.' },
  { id: 'a138', word: 'hedge', meaning: 'đảm bảo, rào chắn; phòng ngừa rủi ro', example: 'Buying gold is often seen as a hedge against inflation.', exampleVN: 'Mua vàng thường được coi là một biện pháp phòng ngừa lạm phát.' },
  { id: 'a139', word: 'insolvent', meaning: 'vỡ nợ, không trả được nợ', example: 'The company was declared insolvent after it failed to pay its loans.', exampleVN: 'Công ty bị tuyên bố vỡ nợ sau khi không trả được các khoản vay.' },
  { id: 'a142', word: 'levy', meaning: 'thu thuế, đánh thuế', example: 'They decided to levy a new tax on luxury goods.', exampleVN: 'Họ quyết định đánh một loại thuế mới lên hàng xa xỉ.' },
  { id: 'a143', word: 'markup', meaning: 'mức tăng giá', example: 'The retailer adds a 50% markup to all products.', exampleVN: 'Nhà bán lẻ thêm mức tăng giá 50% cho tất cả sản phẩm.' },
  { id: 'a144', word: 'outsourcing', meaning: 'thuê ngoài, gia công', example: 'Outsourcing has helped the company reduce costs.', exampleVN: 'Thuê ngoài đã giúp công ty giảm chi phí.' },
  { id: 'a145', word: 'proprietor', meaning: 'chủ sở hữu', example: 'The proprietor of the hotel greeted them personally.', exampleVN: 'Chủ khách sạn đã trực tiếp chào đón họ.' },
  { id: 'a146', word: 'receivership', meaning: 'tình trạng bị quản lý tài sản (vỡ nợ)', example: 'The company went into receivership after failing to find a buyer.', exampleVN: 'Công ty đã rơi vào tình trạng bị quản lý tài sản sau khi không tìm được người mua.' },
  { id: 'a147', word: 'stipulation', meaning: 'điều quy định, điều kiện', example: 'There is a stipulation in the contract that all goals must be met.', exampleVN: 'Có một điều khoản trong hợp đồng rằng tất cả các mục tiêu phải được thực hiện.' },
  { id: 'a148', word: 'tender', meaning: 'bỏ thầu; mềm', example: 'The government invited tenders for the new bridge.', exampleVN: 'Chính phủ đã mời thầu cho cây cầu mới.' },
  { id: 'a149', word: 'underwriter', meaning: 'người bảo hiểm, người bao mua', example: 'The underwriters agreed to cover the full cost of the issue.', exampleVN: 'Các bên bao mua đã đồng ý chi trả toàn bộ chi phí phát hành.' },
  { id: 'a150', word: 'valuation', meaning: 'sự định giá', example: 'The bank is carrying out a valuation of the property.', exampleVN: 'Ngân hàng đang tiến hành định giá bất động sản.' },
  { id: 'a151', word: 'windfall', meaning: 'món lợi bất ngờ', example: 'The company received a windfall of $5 million from the tax refund.', exampleVN: 'Công ty đã nhận được một món lợi bất ngờ trị giá 5 triệu đô la từ việc hoàn thuế.' },
  { id: 'a152', word: 'yield', meaning: 'lợi suất, sản lượng', example: 'The bond has a yield of 4.5%.', exampleVN: 'Trái phiếu có lợi suất là 4,5%.' },
  { id: 'a153', word: 'abrogate', meaning: 'bãi bỏ, hủy bỏ (luật)', example: 'The council decided to abrogate the existing regulations.', exampleVN: 'Hội đồng đã quyết định bãi bỏ các quy định hiện hành.' },
  { id: 'a154', word: 'beneficiary', meaning: 'người thụ hưởng', example: 'He is the sole beneficiary of his father\'s will.', exampleVN: 'Anh là người thụ hưởng duy nhất trong di chúc của cha mình.' },
  { id: 'a155', word: 'collateral', meaning: 'tài sản thế chấp', example: 'He used his house as collateral for the loan.', exampleVN: 'Ông đã dùng ngôi nhà của mình làm tài sản thế chấp cho khoản vay.' },
  { id: 'a157', word: 'exacerbate', meaning: 'làm trầm trọng thêm', example: 'The new regulations will only exacerbate the problem.', exampleVN: 'Các quy định mới sẽ chỉ làm trầm trọng thêm vấn đề.' },
  { id: 'a158', word: 'forfeit', meaning: 'bị tước bỏ, mất quyền', example: 'If you cancel late, you will forfeit your deposit.', exampleVN: 'Nếu bạn hủy muộn, bạn sẽ bị mất tiền cọc.' },
  { id: 'a159', word: 'indemnify', meaning: 'bồi thường, bảo đảm', example: 'The insurance policy will indemnify you against all losses.', exampleVN: 'Chính sách bảo hiểm sẽ bồi thường cho bạn mọi tổn thất.' },
  { id: 'a160', word: 'liquidate', meaning: 'thanh lý (tài sản), trả nợ', example: 'The company was forced to liquidate its assets.', exampleVN: 'Công ty buộc phải thanh lý tài sản.' },
  { id: 'a162', word: 'overdraft', meaning: 'thấu chi', example: 'I have an overdraft of $500 at the bank.', exampleVN: 'Tôi có một khoản thấu chi 500 đô la tại ngân hàng.' },
  { id: 'a164', word: 'remittance', meaning: 'sự chuyển tiền', example: 'Please send the remittance by bank transfer.', exampleVN: 'Vui lòng gửi khoản chuyển tiền bằng hình thức chuyển khoản ngân hàng.' },
  { id: 'a165', word: 'solvent', meaning: 'có khả năng chi trả (nợ)', example: 'The bank is currently solvent despite the economic crisis.', exampleVN: 'Ngân hàng hiện có khả năng chi trả mặc dù có cuộc khủng hoảng kinh tế.' },
  { id: 'a167', word: 'waive', meaning: 'từ bỏ (yêu cầu/quyền)', example: 'The airline decided to waive the cancellation fee.', exampleVN: 'Hãng hàng không đã quyết định miễn phí hủy bỏ.' },
  { id: 'a215', word: 'wary', meaning: 'thận trọng, cảnh giác', example: 'The company is wary of making any major changes.', exampleVN: 'Công ty đang cảnh giác với việc thực hiện bất kỳ thay đổi lớn nào.' },
  { id: 'a219', word: 'adversity', meaning: 'nghịch cảnh', example: 'He showed great courage in the face of adversity.', exampleVN: 'Anh ấy đã thể hiện sự can đảm tuyệt vời khi đối mặt với nghịch cảnh.' }
];

export const processChunkAdvanced = () => {
    return chunkAdvanced.map(w => {
        let pos = '(v)';
        const nouns = new Set(['ubiquity', 'discrepancy', 'prerequisite', 'quandary', 'aberration', 'deference', 'hubris', 'knack', 'paradigm', 'quota', 'subsidy', 'vantage', 'zealot', 'hedonism', 'iconoclast', 'nihilism', 'salient', 'tenure', 'allocation', 'breach', 'fiscal', 'grievance', 'jargon', 'litigation', 'merger', 'outlay', 'portfolio', 'quota', 'turnover', 'viability', 'behest', 'counterfeit', 'downturn', 'embargo', 'franchise', 'kickback', 'markup', 'outsourcing', 'proprietor', 'receivership', 'stipulation', 'underwriter', 'valuation', 'windfall', 'beneficiary', 'collateral', 'non-compliance', 'overdraft', 'perjury', 'remittance', 'accoutrements', 'conduit', 'heretic', 'knave', 'trepidation', 'umbrage', 'blandishment', 'cacophony', 'effrontery', 'idiosyncrasy', 'malediction', 'nadir', 'conundrum', 'venality', 'canard', 'adversity']);
        const both_nv = new Set(['consolidate', 'leverage', 'warrant', 'yield', 'articulate', 'benchmark', 'garner', 'hurtle', 'merger', 'solicit', 'underpin', 'waive', 'accrue', 'levy', 'tender', 'abrogate', 'defer', 'forfeit', 'indemnify', 'liquidate', 'bequeath', 'abscond', 'debilitate', 'kowtow']);
        const adjs = new Set(['ubiquitous', 'unprecedented', 'mandatory', 'feasible', 'volatile', 'stagnant', 'lucrative', 'incumbent', 'jeopardize', 'ostensible', 'tenacious', 'unilateral', 'vacillate', 'zealous', 'benevolent', 'cogent', 'ebullient', 'frugal', 'gregarious', 'inevitable', 'judicious', 'latent', 'magnanimous', 'nebulous', 'obdurate', 'pensive', 'quintessential', 'resilient', 'sagacious', 'untenable', 'venerable', 'wistful', 'yielding', 'articulate', 'empirical', 'holistic', 'tangible', 'unilateral', 'belligerent', 'complacent', 'facetious', 'garish', 'languid', 'maverick', 'oblique', 'quixotic', 'salient', 'negligible', 'insolvent', 'solvent', 'deleterious', 'enervate', 'fastidious', 'grandiloquent', 'impecunious', 'jubilant', 'limucid', 'munificent', 'nascent', 'obsequious', 'parsimonious', 'querulous', 'recalcitrant', 'sanguine', 'vicarious', 'winsome', 'fatuous', 'garrulous', 'hapless', 'pallid', 'quiescent', 'raucous', 'scurrilous', 'tantamount', 'unctuous', 'vacuous', 'wary', 'exigent', 'boisterous', 'demure', 'effervescent', 'gratuitous', 'haughty', 'improvident', 'loquacious', 'nefarious', 'surreptitious', 'truculent', 'abstruse', 'decorous', 'gorgeous']);
        const advs = new Set(['unilaterally', 'meticulously', 'judiciously']);

        if (nouns.has(w.word)) pos = '(n)';
        if (both_nv.has(w.word)) pos = '(n, v)';
        if (adjs.has(w.word)) pos = '(adj)';
        if (advs.has(w.word)) pos = '(adv)';
        
        return { ...w, pos };
    });
};
