import { Word } from './types';

export const chunk3: Word[] = [
  { id: '301', word: 'constant', meaning: 'liên tục', example: 'Constant changes.', exampleVN: 'Thay đổi liên tục.' },
  { id: '302', word: 'construct', meaning: 'xây dựng', example: 'Construct a building.', exampleVN: 'Xây dựng một tòa nhà.' },
  { id: '303', word: 'consultant', meaning: 'cố vấn', example: 'Financial consultant.', exampleVN: 'Tư vấn tài chính.' },
  { id: '304', word: 'contact', meaning: 'liên hệ', example: 'Contact us.', exampleVN: 'Liên hệ với chúng tôi.' },
  { id: '305', word: 'content', meaning: 'nội dung', example: 'Table of content.', exampleVN: 'Mục lục.' },
  { id: '306', word: 'contest', meaning: 'cuộc thi', example: 'Photo contest.', exampleVN: 'Cuộc thi ảnh.' },
  { id: '307', word: 'context', meaning: 'bối cảnh', example: 'In this context.', exampleVN: 'Trong bối cảnh này.' },
  { id: '308', word: 'continue', meaning: 'tiếp tục', example: 'Continue working.', exampleVN: 'Tiếp tục làm việc.' },
  { id: '309', word: 'contrast', meaning: 'tương phản', example: 'In contrast.', exampleVN: 'Ngược lại.' },
  { id: '310', word: 'convenience', meaning: 'sự tiện lợi', example: 'For your convenience.', exampleVN: 'Để thuận tiện cho bạn.' },
  { id: '311', word: 'convenient', meaning: 'tiện lợi', example: 'Convenient time.', exampleVN: 'Thời gian thuận tiện.' },
  { id: '312', word: 'convention', meaning: 'hội nghị, tục lệ', example: 'Annual convention.', exampleVN: 'Hội nghị hàng năm.' },
  { id: '313', word: 'copy', meaning: 'bản sao', example: 'Make a copy.', exampleVN: 'Tạo một bản sao.' },
  { id: '314', word: 'corporate', meaning: 'thuộc công ty', example: 'Corporate structure.', exampleVN: 'Cơ cấu công ty.' },
  { id: '315', word: 'corporation', meaning: 'tập đoàn', example: 'Multinational corporation.', exampleVN: 'Tập đoàn đa quốc gia.' },
  { id: '316', word: 'council', meaning: 'hội đồng', example: 'City council.', exampleVN: 'Hội đồng thành phố.' },
  { id: '317', word: 'count', meaning: 'đếm', example: 'Count the money.', exampleVN: 'Đếm tiền.' },
  { id: '318', word: 'country', meaning: 'quốc gia', example: 'My country.', exampleVN: 'Họ thảo luận về đất nước của tôi.' },
  { id: '319', word: 'couple', meaning: 'cặp đôi', example: 'A couple of days.', exampleVN: 'Họ đã thảo luận trong vài ngày.' },
  { id: '320', word: 'course', meaning: 'khóa học', example: 'Training course.', exampleVN: 'Khóa đào tạo.' },
  { id: '321', word: 'credit', meaning: 'tín dụng', example: 'Credit card.', exampleVN: 'Thẻ tín dụng.' },
  { id: '322', word: 'crisis', meaning: 'khủng hoảng', example: 'Economic crisis.', exampleVN: 'Khủng hoảng kinh tế.' },
  { id: '323', word: 'criteria', meaning: 'tiêu chuẩn', example: 'Selection criteria.', exampleVN: 'Tiêu chí lựa chọn.' },
  { id: '324', word: 'critical', meaning: 'quan trọng', example: 'Critical thinking.', exampleVN: 'Tư duy phản biện.' },
  { id: '325', word: 'crop', meaning: 'mùa màng', example: 'Cash crop.', exampleVN: 'Vụ mùa.' },
  { id: '326', word: 'cross', meaning: 'băng qua', example: 'Cross the street.', exampleVN: 'Băng qua đường.' },
  { id: '327', word: 'crowd', meaning: 'đám đông', example: 'Large crowd.', exampleVN: 'Đám đông lớn.' },
  { id: '328', word: 'crucial', meaning: 'quan trọng', example: 'Crucial moment.', exampleVN: 'Thời điểm quan trọng.' },
  { id: '329', word: 'culture', meaning: 'văn hóa', example: 'Corporate culture.', exampleVN: 'Văn hóa doanh nghiệp.' },
  { id: '330', word: 'current', meaning: 'hiện tại', example: 'Current status.', exampleVN: 'Hiện trạng.' },
  { id: '331', word: 'custom', meaning: 'tập quán', example: 'Local custom.', exampleVN: 'Phong tục địa phương.' },
  { id: '332', word: 'cut', meaning: 'cắt', example: 'Cut costs.', exampleVN: 'Cắt giảm chi phí.' },
  { id: '333', word: 'damage', meaning: 'thiệt hại', example: 'Damage the property.', exampleVN: 'Làm hư hỏng tài sản.' },
  { id: '334', word: 'data', meaning: 'dữ liệu', example: 'Collect data.', exampleVN: 'Thu thập dữ liệu.' },
  { id: '335', word: 'database', meaning: 'cơ sở dữ liệu', example: 'Update the database.', exampleVN: 'Cập nhật cơ sở dữ liệu.' },
  { id: '336', word: 'date', meaning: 'ngày', example: 'Save the date.', exampleVN: 'Lưu lại ngày tháng.' },
  { id: '337', word: 'deal', meaning: 'thỏa thuận', example: 'Good deal.', exampleVN: 'Thỏa thuận tốt.' },
  { id: '338', word: 'debate', meaning: 'tranh luận', example: 'Heated debate.', exampleVN: 'Cuộc tranh luận sôi nổi.' },
  { id: '339', word: 'debt', meaning: 'nợ', example: 'In debt.', exampleVN: 'Nợ nần.' },
  { id: '340', word: 'decade', meaning: 'thập kỷ', example: 'A decade ago.', exampleVN: 'Họ đã thảo luận cách đây một thập kỷ.' },
  { id: '341', word: 'decision', meaning: 'quyết định', example: 'Make a decision.', exampleVN: 'Đưa ra quyết định.' },
  { id: '342', word: 'declare', meaning: 'tuyên bố', example: 'Declare winner.', exampleVN: 'Tuyên bố người chiến thắng.' },
  { id: '343', word: 'default', meaning: 'mặc định', example: 'Default setting.', exampleVN: 'Cài đặt mặc định.' },
  { id: '344', word: 'defeat', meaning: 'đánh bại', example: 'Defeat the enemy.', exampleVN: 'Đánh bại kẻ thù.' },
  { id: '345', word: 'defect', meaning: 'lỗi', example: 'Product defect.', exampleVN: 'Khiếm khuyết của sản phẩm.' },
  { id: '346', word: 'definite', meaning: 'chắc chắn', example: 'Definite answer.', exampleVN: 'Có câu trả lời dứt khoát.' },
  { id: '347', word: 'delegate', meaning: 'ủy quyền', example: 'Delegate tasks.', exampleVN: 'Phân công nhiệm vụ.' },
  { id: '348', word: 'deliberate', meaning: 'cố ý', example: 'Deliberate action.', exampleVN: 'Hành động có chủ ý.' },
  { id: '349', word: 'delivery', meaning: 'sự giao hàng', example: 'Free delivery.', exampleVN: 'Giao hàng miễn phí.' },
  { id: '350', word: 'deny', meaning: 'từ chối', example: 'Deny the rumors.', exampleVN: 'Phủ nhận những tin đồn.' },
  { id: '351', word: 'depress', meaning: 'làm chán nản', example: 'Depress the market.', exampleVN: 'Làm suy yếu thị trường.' },
  { id: '352', word: 'depth', meaning: 'độ sâu', example: 'In depth.', exampleVN: 'Tình hình có chiều sâu.' },
  { id: '353', word: 'derive', meaning: 'bắt nguồn từ', example: 'Derive from.', exampleVN: 'Bắt nguồn từ đó.' },
  { id: '354', word: 'description', meaning: 'sự miêu tả', example: 'Job description.', exampleVN: 'Mô tả công việc.' },
  { id: '355', word: 'desert', meaning: 'rời bỏ', example: 'Desert the post.', exampleVN: 'Bỏ bài đăng.' },
  { id: '356', word: 'desire', meaning: 'mong muốn', example: 'Strong desire.', exampleVN: 'Mong muốn mạnh mẽ.' },
  { id: '357', word: 'desk', meaning: 'bàn', example: 'Front desk.', exampleVN: 'Quầy lễ tân.' },
  { id: '358', word: 'detail', meaning: 'chi tiết', example: 'In detail.', exampleVN: 'Chi tiết.' },
  { id: '359', word: 'device', meaning: 'thiết bị', example: 'Mobile device.', exampleVN: 'Thiết bị di động.' },
  { id: '360', word: 'devote', meaning: 'cống hiến', example: 'Devote time.', exampleVN: 'Dành thời gian.' },
  { id: '361', word: 'dictate', meaning: 'đọc cho chép', example: 'Dictate a letter.', exampleVN: 'Viết một lá thư.' },
  { id: '362', word: 'differ', meaning: 'khác biệt', example: 'Opinions differ.', exampleVN: 'Những ý kiến ​​khác nhau.' },
  { id: '363', word: 'difference', meaning: 'sự khác biệt', example: 'Make a difference.', exampleVN: 'Tạo ra sự khác biệt.' },
  { id: '364', word: 'different', meaning: 'khác nhau', example: 'Different approach.', exampleVN: 'Có cách tiếp cận khác.' },
  { id: '365', word: 'difficult', meaning: 'khó', example: 'Difficult task.', exampleVN: 'Thực hiện nhiệm vụ khó khăn.' },
  { id: '366', word: 'difficulty', meaning: 'sự khó khăn', example: 'Face difficulty.', exampleVN: 'Đối mặt với khó khăn.' },
  { id: '367', word: 'direction', meaning: 'hướng', example: 'Right direction.', exampleVN: 'Hướng đi đúng đắn.' },
  { id: '368', word: 'director', meaning: 'giám đốc', example: 'Managing director.', exampleVN: 'Giám đốc điều hành.' },
  { id: '369', word: 'disagree', meaning: 'không đồng ý', example: 'Disagree with him.', exampleVN: 'Không đồng ý với anh ta.' },
  { id: '370', word: 'disappear', meaning: 'biến mất', example: 'Disappear entirely.', exampleVN: 'Biến mất hoàn toàn.' },
  { id: '371', word: 'disaster', meaning: 'thảm họa', example: 'Natural disaster.', exampleVN: 'Thảm họa thiên nhiên.' },
  { id: '372', word: 'discipline', meaning: 'kỷ luật', example: 'Strict discipline.', exampleVN: 'Kỷ luật nghiêm ngặt.' },
  { id: '373', word: 'discover', meaning: 'khám phá', example: 'Discover truth.', exampleVN: 'Khám phá sự thật.' },
  { id: '374', word: 'discussion', meaning: 'cuộc thảo luận', example: 'Group discussion.', exampleVN: 'Thảo luận nhóm.' },
  { id: '375', word: 'disease', meaning: 'bệnh', example: 'Heart disease.', exampleVN: 'Bệnh tim.' },
  { id: '376', word: 'disk', meaning: 'đĩa', example: 'Hard disk.', exampleVN: 'Đĩa cứng.' },
  { id: '377', word: 'dispute', meaning: 'tranh chấp', example: 'Labor dispute.', exampleVN: 'Tranh chấp lao động.' },
  { id: '378', word: 'distance', meaning: 'khoảng cách', example: 'Long distance.', exampleVN: 'Khoảng cách xa.' },
  { id: '379', word: 'distinguish', meaning: 'phân biệt', example: 'Distinguish clearly.', exampleVN: 'Phân biệt rõ ràng.' },
  { id: '380', word: 'distribution', meaning: 'sự phân phối', example: 'Distribution channel.', exampleVN: 'Kênh phân phối.' },
  { id: '381', word: 'district', meaning: 'khu vực', example: 'Business district.', exampleVN: 'Khu kinh doanh.' },
  { id: '382', word: 'document', meaning: 'tài liệu', example: 'Legal document.', exampleVN: 'Văn bản pháp luật.' },
  { id: '383', word: 'domestic', meaning: 'trong nước', example: 'Domestic flight.', exampleVN: 'Chuyến bay nội địa.' },
  { id: '384', word: 'dominate', meaning: 'thống trị', example: 'Dominate the market.', exampleVN: 'Chiếm lĩnh thị trường.' },
  { id: '385', word: 'double', meaning: 'gấp đôi', example: 'Double the price.', exampleVN: 'Tăng giá gấp đôi.' },
  { id: '386', word: 'doubt', meaning: 'sự nghi ngờ', example: 'No doubt.', exampleVN: 'Không nghi ngờ gì.' },
  { id: '387', word: 'dramatic', meaning: 'đáng chú ý', example: 'Dramatic increase.', exampleVN: 'Tăng lên đáng kể.' },
  { id: '388', word: 'draw', meaning: 'vẽ', example: 'Draw a line.', exampleVN: 'Vẽ một đường.' },
  { id: '389', word: 'drop', meaning: 'rơi', example: 'Drop the ball.', exampleVN: 'Thả bóng.' },
  { id: '390', word: 'due', meaning: 'tới hạn', example: 'Due date.', exampleVN: 'Đến hạn.' },
  { id: '391', word: 'dull', meaning: 'chậm, chán', example: 'Dull moment.', exampleVN: 'Khoảnh khắc buồn tẻ.' },
  { id: '392', word: 'during', meaning: 'trong suốt', example: 'During the meeting.', exampleVN: 'Trong cuộc họp.' },
  { id: '393', word: 'duty', meaning: 'nghĩa vụ', example: 'Duty free.', exampleVN: 'Miễn thuế.' },
  { id: '394', word: 'dynamic', meaning: 'năng động', example: 'Dynamic team.', exampleVN: 'Đội ngũ năng động.' },
  { id: '395', word: 'earnings', meaning: 'thu nhập', example: 'Estimated earnings.', exampleVN: 'Thu nhập ước tính.' },
  { id: '396', word: 'easily', meaning: 'dễ dàng', example: 'Easily done.', exampleVN: 'Dễ dàng thực hiện.' },
  { id: '397', word: 'east', meaning: 'phía Đông', example: 'East coast.', exampleVN: 'Đến bờ biển phía đông.' },
  { id: '398', word: 'easy', meaning: 'dễ', example: 'Easy going.', exampleVN: 'Dễ dàng đi.' },
  { id: '399', word: 'edge', meaning: 'lợi thế cạnh tranh', example: 'Competitive edge.', exampleVN: 'Lợi thế cạnh tranh.' },
  { id: '400', word: 'edition', meaning: 'phiên bản', example: 'First edition.', exampleVN: 'Ấn bản đầu tiên.' },
  { id: '401', word: 'editor', meaning: 'biên tập viên', example: 'Chief editor.', exampleVN: 'Tổng biên tập.' },
  { id: '402', word: 'education', meaning: 'sự giáo dục', example: 'Higher education.', exampleVN: 'Giáo dục đại học.' },
  { id: '403', word: 'effect', meaning: 'hậu quả', example: 'Side effect.', exampleVN: 'Tác dụng phụ.' },
  { id: '404', word: 'effective', meaning: 'hiệu quả', example: 'Effective method.', exampleVN: 'Có phương pháp hiệu quả.' },
  { id: '405', word: 'efficiency', meaning: 'hiệu suất', example: 'High efficiency.', exampleVN: 'Hiệu quả cao.' },
  { id: '406', word: 'efficient', meaning: 'hiệu quả', example: 'Efficient use.', exampleVN: 'Sử dụng hiệu quả.' },
  { id: '407', word: 'effort', meaning: 'nỗ lực', example: 'Team effort.', exampleVN: 'Nỗ lực của nhóm.' },
  { id: '408', word: 'either', meaning: 'một trong hai', example: 'Either this or that.', exampleVN: 'Cái này hoặc cái kia.' },
  { id: '409', word: 'elect', meaning: 'bầu chọn', example: 'Elect president.', exampleVN: 'Bầu tổng thống.' },
  { id: '410', word: 'element', meaning: 'yếu tố', example: 'Key element.', exampleVN: 'Yếu tố then chốt.' },
  { id: '411', word: 'else', meaning: 'khác', example: 'Someone else.', exampleVN: 'Người khác.' },
  { id: '412', word: 'email', meaning: 'thư điện tử', example: 'Send an email.', exampleVN: 'Gửi email.' },
  { id: '413', word: 'emerge', meaning: 'nổi lên', example: 'Emerge victorious.', exampleVN: 'Giành chiến thắng.' },
  { id: '414', word: 'emergency', meaning: 'tình trạng khẩn cấp', example: 'In case of emergency.', exampleVN: 'Trong trường hợp khẩn cấp.' },
  { id: '415', word: 'emotion', meaning: 'cảm xúc', example: 'Show emotion.', exampleVN: 'Thể hiện cảm xúc.' },
  { id: '416', word: 'emphasis', meaning: 'sự nhấn mạnh', example: 'Put emphasis on.', exampleVN: 'Nhấn mạnh vào.' },
  { id: '417', word: 'empire', meaning: 'đế chế', example: 'Business empire.', exampleVN: 'Đế chế kinh doanh.' },
  { id: '418', word: 'employee', meaning: 'nhân viên', example: 'Best employee.', exampleVN: 'Nhân viên giỏi nhất.' },
  { id: '419', word: 'employer', meaning: 'nhà tuyển dụng', example: 'Good employer.', exampleVN: 'Người sử dụng lao động tốt.' },
  { id: '420', word: 'employment', meaning: 'việc làm', example: 'Employment rate.', exampleVN: 'Tỷ lệ việc làm.' },
  { id: '421', word: 'empty', meaning: 'trống', example: 'Empty room.', exampleVN: 'Trống phòng.' },
  { id: '422', word: 'encounter', meaning: 'chạm trán', example: 'Encounter problems.', exampleVN: 'Gặp phải vấn đề.' },
  { id: '423', word: 'end', meaning: 'kết thúc', example: 'The end.', exampleVN: 'Họ thảo luận về phần cuối.' },
  { id: '424', word: 'endorse', meaning: 'xác nhận', example: 'Endorse the check.', exampleVN: 'Xác nhận tấm séc.' },
  { id: '425', word: 'energy', meaning: 'năng lượng', example: 'Clean energy.', exampleVN: 'Làm sạch năng lượng.' },
  { id: '426', word: 'engage', meaning: 'tham gia', example: 'Engage in conversation.', exampleVN: 'Tham gia vào cuộc trò chuyện.' },
  { id: '427', word: 'engine', meaning: 'động cơ', example: 'Search engine.', exampleVN: 'Công cụ tìm kiếm.' },
  { id: '428', word: 'engineer', meaning: 'kỹ sư', example: 'Software engineer.', exampleVN: 'Kỹ sư phần mềm.' },
  { id: '429', word: 'enjoy', meaning: 'thưởng thức', example: 'Enjoy the meal.', exampleVN: 'Thưởng thức bữa ăn.' },
  { id: '430', word: 'enormous', meaning: 'to lớn', example: 'Enormous potential.', exampleVN: 'Có tiềm năng to lớn.' },
  { id: '431', word: 'enough', meaning: 'đủ', example: 'Fair enough.', exampleVN: 'Sự công bằng.' },
  { id: '432', word: 'enter', meaning: 'nhập', example: 'Enter password.', exampleVN: 'Nhập mật khẩu.' },
  { id: '433', word: 'enterprise', meaning: 'doanh nghiệp', example: 'Small enterprise.', exampleVN: 'Doanh nghiệp nhỏ.' },
  { id: '434', word: 'entertain', meaning: 'giải trí', example: 'Entertain guests.', exampleVN: 'Giải trí cho khách.' },
  { id: '435', word: 'entire', meaning: 'toàn bộ', example: 'Entire building.', exampleVN: 'Đến toàn bộ tòa nhà.' },
  { id: '436', word: 'entitle', meaning: 'cho quyền', example: 'Entitle to vote.', exampleVN: 'Có quyền bầu cử.' },
  { id: '437', word: 'entrance', meaning: 'cổng vào', example: 'Main entrance.', exampleVN: 'Lối vào chính.' },
  { id: '438', word: 'entry', meaning: 'lối vào, sự nhập vào, mục', example: 'Data entry.', exampleVN: 'Nhập dữ liệu.' },
  { id: '439', word: 'environment', meaning: 'môi trường', example: 'Work environment.', exampleVN: 'Môi trường làm việc.' },
  { id: '440', word: 'equal', meaning: 'bình đẳng', example: 'Equal rights.', exampleVN: 'Có quyền bình đẳng.' },
  { id: '441', word: 'equip', meaning: 'trang bị', example: 'Equip well.', exampleVN: 'Trang bị tốt.' },
  { id: '442', word: 'equipment', meaning: 'thiết bị', example: 'Office equipment.', exampleVN: 'Thiết bị văn phòng.' },
  { id: '443', word: 'equivalent', meaning: 'tương đương', example: 'Equivalent value.', exampleVN: 'Giá trị tương đương.' },
  { id: '444', word: 'error', meaning: 'lỗi', example: 'System error.', exampleVN: 'Lỗi hệ thống.' },
  { id: '445', word: 'escape', meaning: 'trốn thoát', example: 'Escape plan.', exampleVN: 'Thoát khỏi kế hoạch.' },
  { id: '446', word: 'especially', meaning: 'đặc biệt', example: 'Especially for you.', exampleVN: 'Đặc biệt dành cho bạn.' },
  { id: '447', word: 'essay', meaning: 'bài luận', example: 'Write an essay.', exampleVN: 'Viết một bài luận.' },
  { id: '448', word: 'essential', meaning: 'cần thiết', example: 'Essential item.', exampleVN: 'Mặt hàng thiết yếu.' },
  { id: '449', word: 'establish', meaning: 'thành lập', example: 'Establish business.', exampleVN: 'Thành lập doanh nghiệp.' },
  { id: '450', word: 'estate', meaning: 'bất động sản', example: 'Real estate.', exampleVN: 'Bất động sản.' }
];

export const processChunk3 = () => {
    return chunk3.map(w => {
      let pos = '(v)';
      const nouns = new Set(['consultant', 'context', 'convenience', 'convention', 'copy', 'corporation', 'council', 'country', 'course', 'credit', 'crisis', 'criteria', 'crop', 'crowd', 'culture', 'custom', 'data', 'database', 'debt', 'decade', 'decision', 'defect', 'delivery', 'depth', 'description', 'desire', 'desk', 'detail', 'device', 'difference', 'difficulty', 'direction', 'director', 'disaster', 'discipline', 'discussion', 'disease', 'disk', 'distance', 'distribution', 'district', 'document', 'duty', 'earnings', 'east', 'edge', 'edition', 'editor', 'education', 'effect', 'efficiency', 'effort', 'element', 'email', 'emergency', 'emotion', 'emphasis', 'empire', 'employee', 'employer', 'employment', 'energy', 'engine', 'engineer', 'enterprise', 'entrance', 'entry', 'environment', 'equipment', 'error', 'essay', 'estate']);
      const adjs = new Set(['constant', 'convenient', 'corporate', 'critical', 'crucial', 'current', 'definite', 'deliberate', 'different', 'difficult', 'domestic', 'dramatic', 'dull', 'dynamic', 'easy', 'effective', 'efficient', 'enormous', 'enough', 'entire', 'equal', 'equivalent', 'essential']);
      const both = new Set(['contact', 'content', 'contest', 'contrast', 'count', 'couple', 'cross', 'cut', 'damage', 'date', 'deal', 'debate', 'default', 'defeat', 'delay', 'desert', 'design', 'dispute', 'double', 'doubt', 'draft', 'draw', 'drop', 'due', 'end', 'escape', 'exchange']);
      if (nouns.has(w.word)) pos = '(n)';
      else if (adjs.has(w.word)) pos = '(adj)';
      else if (both.has(w.word)) pos = '(n, v)';
      return { ...w, pos };
    });
};
