import { Word } from './types';

export const chunkInter5: Word[] = [
  { id: 'i451', word: 'leap', meaning: 'nhảy vọt', example: 'A giant leap for mankind.', exampleVN: 'Một bước nhảy vọt cho nhân loại.' },
  { id: 'i452', word: 'lease', meaning: 'hợp đồng cho thuê', example: 'Sign a five-year lease.', exampleVN: 'Ký hợp đồng thuê năm năm.' },
  { id: 'i453', word: 'lecture', meaning: 'bài giảng', example: 'Attend a lecture on history.', exampleVN: 'Tham dự một bài giảng về lịch sử.' },
  { id: 'i454', word: 'legal', meaning: 'hợp pháp', example: 'Seek legal advice.', exampleVN: 'Tìm lời khuyên pháp lý.' },
  { id: 'i455', word: 'legend', meaning: 'huyền thoại', example: 'A local legend.', exampleVN: 'Một huyền thoại địa phương.' },
  { id: 'i456', word: 'legislate', meaning: 'lập pháp', example: 'The power to legislate.', exampleVN: 'Quyền lập pháp.' },
  { id: 'i457', word: 'legitimate', meaning: 'hợp pháp, chính đáng', example: 'A legitimate concern.', exampleVN: 'Một mối quan tâm chính đáng.' },
  { id: 'i458', word: 'leisure', meaning: 'thời gian rảnh rỗi', example: 'Leisure activities.', exampleVN: 'Hoạt động giải trí.' },
  { id: 'i459', word: 'lend', meaning: 'cho mượn', example: 'Can you lend me some money?', exampleVN: 'Bạn có thể cho tôi mượn ít tiền không?' },
  { id: 'i460', word: 'length', meaning: 'chiều dài', example: 'The length of the pool.', exampleVN: 'Chiều dài của hồ bơi.' },
  { id: 'i461', word: 'lens', meaning: 'thấu kính', example: 'Camera lens.', exampleVN: 'Ống kính máy ảnh.' },
  { id: 'i462', word: 'lessen', meaning: 'giảm bớt', example: 'Lessen the impact.', exampleVN: 'Giảm bớt tác động.' },
  { id: 'i463', word: 'lethal', meaning: 'gây chết người', example: 'A lethal dose.', exampleVN: 'Một liều gây chết người.' },
  { id: 'i464', word: 'liable', meaning: 'có trách nhiệm pháp lý', example: 'You are liable for the damage.', exampleVN: 'Bạn chịu trách nhiệm về thiệt hại.' },
  { id: 'i465', word: 'liberal', meaning: 'tự do, rộng rãi', example: 'A liberal education.', exampleVN: 'Một nền giáo dục khai phóng.' },
  { id: 'i466', word: 'liberty', meaning: 'tự do', example: 'Statue of Liberty.', exampleVN: 'Tượng Nữ thần Tự do.' },
  { id: 'i467', word: 'license', meaning: 'giấy phép', example: 'Driving license.', exampleVN: 'Bằng lái xe.' },
  { id: 'i468', word: 'lifelong', meaning: 'suốt đời', example: 'A lifelong friend.', exampleVN: 'Một người bạn suốt đời.' },
  { id: 'i469', word: 'lifetime', meaning: 'cả đời', example: 'A once in a lifetime opportunity.', exampleVN: 'Cơ hội ngàn năm có một.' },
  { id: 'i470', word: 'likely', meaning: 'có khả năng', example: 'It\'s likely to rain.', exampleVN: 'Có khả năng trời sẽ mưa.' },
  { id: 'i471', word: 'limit', meaning: 'giới hạn', example: 'Speed limit.', exampleVN: 'Giới hạn tốc độ.' },
  { id: 'i472', word: 'lineage', meaning: 'dòng dõi', example: 'Ancient lineage.', exampleVN: 'Dòng dõi cổ xưa.' },
  { id: 'i473', word: 'linear', meaning: 'tuyến tính', example: 'A linear relationship.', exampleVN: 'Một mối quan hệ tuyến tính.' },
  { id: 'i474', word: 'linger', meaning: 'nán lại, chần chừ', example: 'The smell lingered for days.', exampleVN: 'Mùi hương nán lại trong nhiều ngày.' },
  { id: 'i475', word: 'linguistic', meaning: 'thuộc về ngôn ngữ', example: 'Linguistic skills.', exampleVN: 'Kỹ năng ngôn ngữ.' },
  { id: 'i476', word: 'link', meaning: 'liên kết', example: 'Click the link.', exampleVN: 'Nhấp vào liên kết.' },
  { id: 'i477', word: 'liquid', meaning: 'chất lỏng', example: 'Liquid soap.', exampleVN: 'Xà phòng lỏng.' },
  { id: 'i478', word: 'list', meaning: 'danh sách', example: 'Shopping list.', exampleVN: 'Danh sách mua sắm.' },
  { id: 'i479', word: 'literal', meaning: 'nghĩa đen', example: 'Literal meaning.', exampleVN: 'Nghĩa đen.' },
  { id: 'i480', word: 'literary', meaning: 'thuộc về văn học', example: 'Literary works.', exampleVN: 'Các tác phẩm văn học.' },
  { id: 'i481', word: 'literature', meaning: 'văn học', example: 'English literature.', exampleVN: 'Văn học Anh.' },
  { id: 'i482', word: 'litter', meaning: 'rác, xả rác', example: 'Don\'t litter.', exampleVN: 'Đừng xả rác.' },
  { id: 'i483', word: 'load', meaning: 'tải, vật nặng', example: 'Load the truck.', exampleVN: 'Chất hàng lên xe tải.' },
  { id: 'i484', word: 'loan', meaning: 'khoản vay', example: 'A bank loan.', exampleVN: 'Một khoản vay ngân hàng.' },
  { id: 'i485', word: 'local', meaning: 'địa phương', example: 'Local government.', exampleVN: 'Chính quyền địa phương.' },
  { id: 'i486', word: 'locate', meaning: 'xác định vị trí', example: 'Locate the office.', exampleVN: 'Xác định vị trí văn phòng.' },
  { id: 'i487', word: 'location', meaning: 'vị trí', example: 'A secret location.', exampleVN: 'Một vị trí bí mật.' },
  { id: 'i488', word: 'logic', meaning: 'lô-gic', example: 'Mathematical logic.', exampleVN: 'Lô-gic toán học.' },
  { id: 'i489', word: 'logo', meaning: 'biểu trưng', example: 'Company logo.', exampleVN: 'Biểu trưng công ty.' },
  { id: 'i490', word: 'lonely', meaning: 'cô đơn', example: 'Feel lonely.', exampleVN: 'Cảm thấy cô đơn.' },
  { id: 'i491', word: 'loose', meaning: 'lỏng, rộng', example: 'A loose screw.', exampleVN: 'Một con vít bị lỏng.' },
  { id: 'i492', word: 'loyal', meaning: 'trung thành', example: 'A loyal customer.', exampleVN: 'Một khách hàng trung thành.' },
  { id: 'i493', word: 'loyalty', meaning: 'lòng trung thành', example: 'Brand loyalty.', exampleVN: 'Lòng trung thành với thương hiệu.' },
  { id: 'i494', word: 'lucrative', meaning: 'có lợi nhuận', example: 'A lucrative business.', exampleVN: 'Một công việc kinh doanh có lợi nhuận.' },
  { id: 'i495', word: 'lumber', meaning: 'gỗ xẻ', example: 'The lumber industry.', exampleVN: 'Ngành công nghiệp gỗ.' },
  { id: 'i496', word: 'luxury', meaning: 'xa xỉ', example: 'Luxury goods.', exampleVN: 'Hàng xa xỉ.' },
  { id: 'i497', word: 'machinery', meaning: 'máy móc', example: 'Agricultural machinery.', exampleVN: 'Máy móc nông nghiệp.' },
  { id: 'i498', word: 'magazine', meaning: 'tạp chí', example: 'Read a magazine.', exampleVN: 'Đọc tạp chí.' },
  { id: 'i499', word: 'magic', meaning: 'phép thuật', example: 'Magic trick.', exampleVN: 'Trò ảo thuật.' },
  { id: 'i500', word: 'magnify', meaning: 'phóng đại', example: 'Magnify the image.', exampleVN: 'Phóng đại hình ảnh.' },
  { id: 'i501', word: 'magnitude', meaning: 'tầm vóc, cường độ', example: 'An earthquake of large magnitude.', exampleVN: 'Một trận động đất có cường độ lớn.' },
  { id: 'i502', word: 'main', meaning: 'chính', example: 'Main entrance.', exampleVN: 'Lối vào chính.' },
  { id: 'i503', word: 'maintain', meaning: 'duy trì, bảo trì', example: 'Maintain high standards.', exampleVN: 'Duy trì các tiêu chuẩn cao.' },
  { id: 'i504', word: 'major', meaning: 'chính, quan trọng', example: 'A major problem.', exampleVN: 'Một vấn đề chính.' },
  { id: 'i505', word: 'majority', meaning: 'đa số', example: 'The majority of people.', exampleVN: 'Đa số mọi người.' },
  { id: 'i506', word: 'manage', meaning: 'quản lý', example: 'Manage a team.', exampleVN: 'Quản lý một nhóm.' },
  { id: 'i507', word: 'mandatory', meaning: 'bắt buộc', example: 'Attendance is mandatory.', exampleVN: 'Sự tham dự là bắt buộc.' },
  { id: 'i508', word: 'manifest', meaning: 'biểu lộ, bản kê khai', example: 'The symptoms manifest early.', exampleVN: 'Các triệu chứng biểu lộ sớm.' },
  { id: 'i509', word: 'manipulate', meaning: 'thao túng', example: 'Manipulate the data.', exampleVN: 'Thao túng dữ liệu.' },
  { id: 'i510', word: 'manner', meaning: 'cách thức, thái độ', example: 'In a professional manner.', exampleVN: 'Theo một cách chuyên nghiệp.' },
  { id: 'i511', word: 'manual', meaning: 'thủ công, sách hướng dẫn', example: 'Manual labor.', exampleVN: 'Lao động tay chân.' },
  { id: 'i512', word: 'margin', meaning: 'lề, lợi nhuận biên', example: 'Profit margin.', exampleVN: 'Biên lợi nhuận.' },
  { id: 'i513', word: 'marine', meaning: 'thuộc về biển', example: 'Marine life.', exampleVN: 'Sinh vật biển.' },
  { id: 'i514', word: 'mark', meaning: 'đánh dấu, điểm', example: 'Mark the date.', exampleVN: 'Đánh dấu ngày.' },
  { id: 'i515', word: 'marketing', meaning: 'tiếp thị', example: 'Marketing strategy.', exampleVN: 'Chiến lược tiếp thị.' },
  { id: 'i516', word: 'massive', meaning: 'to lớn, đồ sộ', example: 'A massive explosion.', exampleVN: 'Một vụ nổ lớn.' },
  { id: 'i517', word: 'master', meaning: 'làm chủ, thầy', example: 'Master a skill.', exampleVN: 'Làm chủ một kỹ năng.' },
  { id: 'i518', word: 'material', meaning: 'vật liệu, tài liệu', example: 'Raw materials.', exampleVN: 'Nguyên liệu thô.' },
  { id: 'i519', word: 'mature', meaning: 'trưởng thành', example: 'A mature adult.', exampleVN: 'Một người trưởng thành.' },
  { id: 'i520', word: 'maximum', meaning: 'tối đa', example: 'Maximum speed.', exampleVN: 'Tốc độ tối đa.' },
  { id: 'i521', word: 'mean', meaning: 'nghĩa là, hèn hạ', example: 'What do you mean?', exampleVN: 'Bạn ý là gì?' },
  { id: 'i522', word: 'measure', meaning: 'đo lường, biện pháp', example: 'Take measures.', exampleVN: 'Thực hiện các biện pháp.' },
  { id: 'i523', word: 'mechanism', meaning: 'cơ chế', example: 'A defense mechanism.', exampleVN: 'Một cơ chế phòng thủ.' },
  { id: 'i524', word: 'media', meaning: 'phương tiện truyền thông', example: 'Social media.', exampleVN: 'Phương tiện truyền thông xã hội.' },
  { id: 'i525', word: 'mediate', meaning: 'hòa giải', example: 'Mediate a dispute.', exampleVN: 'Hòa giải một cuộc tranh chấp.' },
  { id: 'i526', word: 'medical', meaning: 'thuộc y tế', example: 'Medical care.', exampleVN: 'Chăm sóc y tế.' },
  { id: 'i527', word: 'medicine', meaning: 'thuốc, y học', example: 'Take your medicine.', exampleVN: 'Uống thuốc đi.' },
  { id: 'i528', word: 'medium', meaning: 'trung bình, phương tiện', example: 'A medium-sized company.', exampleVN: 'Một công ty quy mô trung bình.' },
  { id: 'i529', word: 'meet', meaning: 'gặp gỡ, đáp ứng', example: 'Meet the requirements.', exampleVN: 'Đáp ứng các yêu cầu.' },
  { id: 'i530', word: 'memory', meaning: 'bộ nhớ, kỷ niệm', example: 'Fond memories.', exampleVN: 'Những kỷ niệm đẹp.' },
  { id: 'i531', word: 'mental', meaning: 'thuộc về tâm thần, trí tuệ', example: 'Mental health.', exampleVN: 'Sức khỏe tâm thần.' },
  { id: 'i532', word: 'mention', meaning: 'đề cập', example: 'Don\'t mention it.', exampleVN: 'Đừng nhắc đến việc đó.' },
  { id: 'i533', word: 'mentor', meaning: 'người cố vấn', example: 'He is my mentor.', exampleVN: 'Ông ấy là người cố vấn của tôi.' },
  { id: 'i534', word: 'menu', meaning: 'thực đơn', example: 'Check the menu.', exampleVN: 'Kiểm tra thực đơn.' },
  { id: 'i535', word: 'merchandise', meaning: 'hàng hóa', example: 'Sell merchandise.', exampleVN: 'Bán hàng hóa.' },
  { id: 'i536', word: 'merchant', meaning: 'thương gia', example: 'A wine merchant.', exampleVN: 'Một người buôn rượu.' },
  { id: 'i537', word: 'mercy', meaning: 'lòng khoan dung', example: 'Show mercy.', exampleVN: 'Tỏ lòng khoan dung.' },
  { id: 'i538', word: 'merge', meaning: 'sáp nhập', example: 'The two companies merged.', exampleVN: 'Hai công ty đã sáp nhập.' },
  { id: 'i539', word: 'merit', meaning: 'xứng đáng, công trạng', example: 'Based on merit.', exampleVN: 'Dựa trên thực lực.' },
  { id: 'i540', word: 'message', meaning: 'tin nhắn', example: 'Leave a message.', exampleVN: 'Để lại một tin nhắn.' },
  { id: 'i541', word: 'metal', meaning: 'kim loại', example: 'Scrap metal.', exampleVN: 'Kim loại phế liệu.' },
  { id: 'i542', word: 'method', meaning: 'phương pháp', example: 'A scientific method.', exampleVN: 'Một phương pháp khoa học.' },
  { id: 'i543', word: 'metric', meaning: 'số liệu đo lường', example: 'Performance metrics.', exampleVN: 'Các số liệu đo lường hiệu suất.' },
  { id: 'i544', word: 'microscope', meaning: 'kính hiển vi', example: 'Look through a microscope.', exampleVN: 'Nhìn qua kính hiển vi.' },
  { id: 'i545', word: 'middle', meaning: 'giữa', example: 'Middle management.', exampleVN: 'Quản lý cấp trung.' },
  { id: 'i546', word: 'migrant', meaning: 'người di cư', example: 'Migrant workers.', exampleVN: 'Công nhân di cư.' },
  { id: 'i547', word: 'mild', meaning: 'nhẹ, ôn hòa', example: 'Mild weather.', exampleVN: 'Thời tiết ôn hòa.' },
  { id: 'i548', word: 'military', meaning: 'quân sự', example: 'Military service.', exampleVN: 'Nghĩa vụ quân sự.' },
  { id: 'i459', word: 'million', meaning: 'triệu', example: 'One million dollars.', exampleVN: 'Một triệu đô la.' },
  { id: 'i550', word: 'mind', meaning: 'tâm trí, phiền', example: 'Do you mind?', exampleVN: 'Bạn có phiền không?' },
  { id: 'i551', word: 'mineral', meaning: 'khoáng sản', example: 'Mineral water.', exampleVN: 'Nước khoáng.' },
  { id: 'i552', word: 'minimum', meaning: 'tối thiểu', example: 'Minimum wage.', exampleVN: 'Lương tối thiểu.' },
  { id: 'i553', word: 'minister', meaning: 'bộ trưởng', example: 'The Minister of Finance.', exampleVN: 'Bộ trưởng Tài chính.' },
  { id: 'i554', word: 'minor', meaning: 'nhỏ, không quan trọng', example: 'A minor problem.', exampleVN: 'Một vấn đề nhỏ.' },
  { id: 'i555', word: 'minority', meaning: 'thiểu số', example: 'Ethnic minority.', exampleVN: 'Dân tộc thiểu số.' },
  { id: 'i556', word: 'minute', meaning: 'phút, biên bản cuộc họp', example: 'Wait a minute.', exampleVN: 'Đợi một phút.' },
  { id: 'i557', word: 'miracle', meaning: 'phép màu', example: 'It\'s a miracle.', exampleVN: 'Đó là một phép màu.' },
  { id: 'i558', word: 'mirror', meaning: 'gương', example: 'Look in the mirror.', exampleVN: 'Nhìn vào gương.' },
  { id: 'i559', word: 'mischief', meaning: 'trò tinh quái', example: 'Keep out of mischief.', exampleVN: 'Đừng có nghịch ngợm.' },
  { id: 'i560', word: 'mislead', meaning: 'làm lạc hướng', example: 'Mislead the public.', exampleVN: 'Làm công chúng hiểu lầm.' },
  { id: 'i561', word: 'miss', meaning: 'lỡ, nhớ', example: 'Miss the bus.', exampleVN: 'Lỡ xe buýt.' },
  { id: 'i562', word: 'mission', meaning: 'nhiệm vụ', example: 'A secret mission.', exampleVN: 'Một nhiệm vụ bí mật.' },
  { id: 'i563', word: 'mistake', meaning: 'lỗi lầm', example: 'Make a mistake.', exampleVN: 'Phạm lỗi.' },
  { id: 'i564', word: 'mix', meaning: 'trộn', example: 'Mix the ingredients.', exampleVN: 'Trộn các thành phần.' },
  { id: 'i565', word: 'mobile', meaning: 'di động', example: 'Mobile phone.', exampleVN: 'Điện thoại di động.' },
  { id: 'i566', word: 'mode', meaning: 'chế độ', example: 'Silent mode.', exampleVN: 'Chế độ im lặng.' },
  { id: 'i567', word: 'model', meaning: 'người mẫu, mô hình', example: 'A business model.', exampleVN: 'Một mô hình kinh doanh.' },
  { id: 'i568', word: 'moderate', meaning: 'vừa phải, ôn hòa', example: 'Moderate exercise.', exampleVN: 'Tập thể dục vừa phải.' },
  { id: 'i569', word: 'modern', meaning: 'hiện đại', example: 'Modern architecture.', exampleVN: 'Kiến trúc hiện đại.' },
  { id: 'i570', word: 'modest', meaning: 'khiêm tốn', example: 'A modest home.', exampleVN: 'Một ngôi nhà khiêm tốn.' },
  { id: 'i571', word: 'modify', meaning: 'sửa đổi', example: 'Modify the plan.', exampleVN: 'Sửa đổi kế hoạch.' },
  { id: 'i572', word: 'module', meaning: 'mô-đun', example: 'A training module.', exampleVN: 'Một mô-đun đào tạo.' },
  { id: 'i573', word: 'moment', meaning: 'khoảnh khắc', example: 'Wait a moment.', exampleVN: 'Đợi một lát.' },
  { id: 'i574', word: 'momentum', meaning: 'đà, xung lực', example: 'Gain momentum.', exampleVN: 'Lấy đà.' },
  { id: 'i575', word: 'monetary', meaning: 'thuộc về tiền tệ', example: 'Monetary policy.', exampleVN: 'Chính sách tiền tệ.' },
  { id: 'i576', word: 'monitor', meaning: 'giám sát, màn hình', example: 'Monitor the situation.', exampleVN: 'Theo dõi tình hình.' },
  { id: 'i577', word: 'monopoly', meaning: 'độc quyền', example: 'A monopoly on the market.', exampleVN: 'Sự độc quyền trên thị trường.' },
  { id: 'i578', word: 'mood', meaning: 'tâm trạng', example: 'In a good mood.', exampleVN: 'Trong tâm trạng tốt.' },
  { id: 'i579', word: 'moral', meaning: 'thuộc đạo đức', example: 'Moral values.', exampleVN: 'Các giá trị đạo đức.' },
  { id: 'i580', word: 'mortgage', meaning: 'thế chấp, tiền vay mua nhà', example: 'Pay off the mortgage.', exampleVN: 'Trả hết nợ thế chấp.' },
  { id: 'i581', word: 'motion', meaning: 'chuyển động, sự vận động', example: 'A motion sensor.', exampleVN: 'Một cảm biến chuyển động.' },
  { id: 'i582', word: 'motivate', meaning: 'thúc đẩy, truyền động lực', example: 'Motivate the employees.', exampleVN: 'Thúc đẩy nhân viên.' },
  { id: 'i583', word: 'motive', meaning: 'động cơ', example: 'A hidden motive.', exampleVN: 'Một động cơ ẩn giấu.' },
  { id: 'i584', word: 'mount', meaning: 'gắn, leo lên', example: 'Mount the TV on the wall.', exampleVN: 'Gắn TV lên tường.' },
  { id: 'i585', word: 'mountain', meaning: 'núi', example: 'Climb a mountain.', exampleVN: 'Leo núi.' },
  { id: 'i586', word: 'move', meaning: 'di chuyển', example: 'Move to a new house.', exampleVN: 'Chuyển sang nhà mới.' },
  { id: 'i587', word: 'multiple', meaning: 'nhiều, phức hợp', example: 'Multiple choices.', exampleVN: 'Nhiều lựa chọn.' },
  { id: 'i588', word: 'multiply', meaning: 'nhân lên', example: 'Two multiplied by three.', exampleVN: 'Hai nhân ba.' },
  { id: 'i589', word: 'municipal', meaning: 'thuộc đô thị, thành phố', example: 'Municipal elections.', exampleVN: 'Bầu cử thành phố.' },
  { id: 'i590', word: 'muscle', meaning: 'cơ bắp', example: 'Build muscle.', exampleVN: 'Xây dựng cơ bắp.' },
  { id: 'i591', word: 'museum', meaning: 'bảo tàng', example: 'Visit a museum.', exampleVN: 'Tham quan bảo tàng.' },
  { id: 'i592', word: 'music', meaning: 'âm nhạc', example: 'Listen to music.', exampleVN: 'Nghe nhạc.' },
  { id: 'i593', word: 'mutual', meaning: 'lẫn nhau, chung', example: 'Mutual respect.', exampleVN: 'Sự tôn trọng lẫn nhau.' },
  { id: 'i594', word: 'mystery', meaning: 'bí ẩn', example: 'Solve a mystery.', exampleVN: 'Giải quyết một điều bí ẩn.' },
  { id: 'i595', word: 'myth', meaning: 'thần thoại, huyền thoại', example: 'Greek myth.', exampleVN: 'Thần thoại Hy Lạp.' },
  { id: 'i596', word: 'naked', meaning: 'trần trụi', example: 'Naked eye.', exampleVN: 'Mắt thường.' },
  { id: 'i597', word: 'name', meaning: 'tên', example: 'Brand name.', exampleVN: 'Tên thương hiệu.' },
  { id: 'i598', word: 'narrative', meaning: 'bản tường thuật, câu chuyện', example: 'A compelling narrative.', exampleVN: 'Một câu chuyện hấp dẫn.' },
  { id: 'i599', word: 'narrow', meaning: 'hẹp', example: 'A narrow street.', exampleVN: 'Một con phố hẹp.' },
  { id: 'i600', word: 'nation', meaning: 'quốc gia', example: 'The whole nation.', exampleVN: 'Cả quốc gia.' },
];

export const processChunkInter5 = () => {
  return chunkInter5.map(w => ({ ...w, pos: '(n)' as string }));
};
