import { Word } from './types';

export const chunk18_raw: Omit<Word, 'id'>[] = [
  { word: "run into", meaning: "gặp phải (vấn đề)", example: "We have run into an issue.", exampleVN: "Chúng ta gặp vấn đề." },
  { word: "featured speaker", meaning: "diễn giả chính", example: "The featured speaker at the summit.", exampleVN: "Diễn giả chính tại hội nghị." },
  { word: "audition", meaning: "buổi thử giọng, thử vai", example: "A television audition.", exampleVN: "Thử vai truyền hình." },
  { word: "busy", meaning: "đông đúc, bận rộn", example: "A busy street.", exampleVN: "Con đường đông đúc." },
  { word: "remove", meaning: "tháo ra, gỡ bỏ", example: "Removing her glasses.", exampleVN: "Tháo kính ra." },
  { word: "fence", meaning: "hàng rào", example: "Along the fence.", exampleVN: "Dọc bờ rào." },
  { word: "corridor", meaning: "hành lang", example: "Walking down the corridor.", exampleVN: "Đi xuống hành lang." },
  { word: "container", meaning: "vật chứa, thùng đựng", example: "A large container.", exampleVN: "Vật chứa lớn." },
  { word: "path", meaning: "lối đi, đường mòn", example: "Clearing snow off the path.", exampleVN: "Dọn tuyết trên lối đi." },
  { word: "lean", meaning: "cúi, nghiêng, tựa", example: "Leaning over to tie his shoe.", exampleVN: "Cúi xuống buộc dây giày." },
  { word: "shoulder", meaning: "vai", example: "Carrying a bag on her shoulder.", exampleVN: "Đeo túi trên vai." },
  { word: "agree", meaning: "đồng ý", example: "I agree with you.", exampleVN: "Tôi đồng ý với bạn." },
  { word: "decide", meaning: "quyết định", example: "Decide to become a pilot.", exampleVN: "Quyết định trở thành phi công." },
  { word: "total", meaning: "tổng cộng", example: "Five people in total.", exampleVN: "Tổng cộng có năm người." },
  { word: "negative", meaning: "tiêu cực", example: "Negative feedback.", exampleVN: "Phản hồi tiêu cực." },
  { word: "storage", meaning: "kho lưu trữ", example: "Storage room.", exampleVN: "Phòng chứa đồ." },
  { word: "prepare", meaning: "chuẩn bị", example: "Prepare for the meeting.", exampleVN: "Chuẩn bị cuộc họp." },
  { word: "résumé", meaning: "sơ yếu lý lịch", example: "Review the résumés first.", exampleVN: "Xem các sơ yếu lý lịch trước." },
  { word: "oven", meaning: "lò nướng", example: "Checked the oven.", exampleVN: "Kiểm tra lò nướng." },
  { word: "delicious", meaning: "thơm ngon", example: "The cake is delicious.", exampleVN: "Cái bánh rất ngon." },
  { word: "in person", meaning: "trực tiếp (đích thân)", example: "Visit in person.", exampleVN: "Đến xem trực tiếp." },
  { word: "neighborhood", meaning: "khu vực lân cận", example: "Live in this neighborhood.", exampleVN: "Sống ở khu vực này." },
  { word: "particular", meaning: "cụ thể, đặc biệt", example: "That particular area.", exampleVN: "Khu vực cụ thể đó." },
  { word: "guarantee", meaning: "sự đảm bảo", example: "No guarantee.", exampleVN: "Không có sự đảm bảo." },
  { word: "proposal", meaning: "bản đề xuất", example: "Read their proposal.", exampleVN: "Đọc đề xuất." },
  { word: "access", meaning: "truy cập", example: "Password to access them.", exampleVN: "Mật khẩu để cập." },
  { word: "appearance", meaning: "sự xuất hiện", example: "His appearance on the show.", exampleVN: "Sự xuất hiện của anh ấy." },
  { word: "slot", meaning: "chỗ, khoảng thời gian", example: "A slot to fill.", exampleVN: "Chỗ trống cần lấp." },
  { word: "in advance", meaning: "trước", example: "Sign up in advance.", exampleVN: "Đăng ký trước." },
  { word: "collection", meaning: "bộ sưu tập", example: "Our collection.", exampleVN: "Bộ sưu tập của chúng tôi." },
  { word: "convenient", meaning: "tiện lợi", example: "It will be convenient.", exampleVN: "Nó sẽ rất tiện lợi." },
  { word: "contribution", meaning: "sự đóng góp", example: "Their contributions.", exampleVN: "Sự đóng góp của họ." },
  { word: "recognize", meaning: "ghi nhận, công nhận", example: "Contributions aren't recognized.", exampleVN: "Không được ghi nhận." },
  { word: "apparel", meaning: "trang phục/quần áo", example: "Athletic apparel.", exampleVN: "Trang phục thể thao." },
  { word: "jigsaw puzzle", meaning: "trò chơi xếp hình", example: "Jigsaw puzzles.", exampleVN: "Trò chơi ghép hình." },
  { word: "timeline", meaning: "tiến độ/khung thời gian", example: "A short timeline.", exampleVN: "Khung thời gian ngắn." },
  { word: "illustrator", meaning: "họa sĩ minh họa", example: "Our illustrators sent new ones.", exampleVN: "Họa sĩ minh họa của chúng tôi." },
  { word: "sketch", meaning: "bản phác thảo", example: "The sketches right here.", exampleVN: "Bản phác thảo ở ngay đây." },
  { word: "clarify", meaning: "làm rõ", example: "Clarifying that charge.", exampleVN: "Làm rõ khoản phí." },
  { word: "celebrity", meaning: "người nổi tiếng", example: "Three celebrity performers.", exampleVN: "Những nghệ sĩ nổi tiếng." },
  { word: "aisle", meaning: "lối đi (giữa các kệ hàng)", example: "In aisle four.", exampleVN: "Ở lối đi số 4." },
  { word: "domestic", meaning: "nội địa/trong nước", example: "Domestic fees.", exampleVN: "Phí nội địa." },
  { word: "disruption", meaning: "sự gián đoạn", example: "Disruptions to service.", exampleVN: "Sự gián đoạn dịch vụ." },
  { word: "restore", meaning: "phục hồi, khôi phục", example: "Restore the gardens.", exampleVN: "Khôi phục các khu vườn." },
  { word: "authentic", meaning: "đích thực, nguyên bản", example: "An authentic re-creation.", exampleVN: "Một bản tái hiện nguyên bản." },
  { word: "receptive", meaning: "dễ tiếp thu, cởi mở", example: "Receptive to cold calls.", exampleVN: "Cởi mở với các cuộc gọi." },
  { word: "worth one's while", meaning: "đáng để bỏ thời gian", example: "Worth their while.", exampleVN: "Đáng bỏ thời gian." },
  { word: "recording", meaning: "bản ghi âm", example: "Listen to some recordings.", exampleVN: "Lắng nghe bản ghi âm." },
  { word: "replacement", meaning: "sự thay thế", example: "Replacement set.", exampleVN: "Bộ thay thế." },
  { word: "qualified", meaning: "có đủ trình độ, năng lực", example: "Qualified temporary workers.", exampleVN: "Nhân viên đủ năng lực." },
  { word: "facility", meaning: "cơ sở vật chất", example: "Modern sports facility.", exampleVN: "Cơ sở vật chất hiện đại." },
  { word: "forecast", meaning: "dự báo", example: "Today's forecast.", exampleVN: "Dự báo hôm nay." },
  { word: "combination", meaning: "sự kết hợp", example: "Right combination.", exampleVN: "Sự kết hợp hoàn hảo." },
  { word: "ballroom", meaning: "phòng khiêu vũ/hội trường", example: "Set up the ballroom.", exampleVN: "Dọn dẹp hội trường." },
  { word: "cover for", meaning: "làm thay cho ai", example: "Covering for her tonight.", exampleVN: "Làm thay cô ấy tối nay." },
  { word: "otherwise", meaning: "nếu không thì/ngoài ra", example: "Available all day otherwise.", exampleVN: "Ngoài ra thì rảnh cả ngày." },
  { word: "seal", meaning: "niêm phong, đóng kín", example: "Seal the packages.", exampleVN: "Đóng kín gói hàng." },
  { word: "prop open", meaning: "chống cửa để mở", example: "Propped open.", exampleVN: "Chống mở." },
  { word: "window shade", meaning: "rèm che cửa sổ", example: "Pulled down the window shade.", exampleVN: "Kéo rèm cửa xuống." },
  { word: "reserve", meaning: "đặt trước", example: "Reserve a table.", exampleVN: "Đặt trước bàn." },
  { word: "at the latest", meaning: "muộn nhất là", example: "By Monday at the latest.", exampleVN: "Muộn nhất vào thứ Hai." },
  { word: "registration deadline", meaning: "hạn chót đăng ký", example: "The registration deadline.", exampleVN: "Hạn chót đăng ký." },
  { word: "adjust", meaning: "điều chỉnh", example: "Adjust the height.", exampleVN: "Điều chỉnh độ cao." },
  { word: "do someone a favor", meaning: "giúp đỡ ai đó", example: "Do me a favor.", exampleVN: "Giúp tôi một việc." },
  { word: "scientific research", meaning: "nghiên cứu khoa học", example: "Scientific research.", exampleVN: "Nghiên cứu khoa học." },
  { word: "meet the demand", meaning: "đáp ứng nhu cầu", example: "Meet the growing demand.", exampleVN: "Đáp ứng nhu cầu tăng." },
  { word: "entrust", meaning: "giao phó", example: "Entrust your secrets.", exampleVN: "Giao phó bí mật." },
  { word: "skylight", meaning: "cửa sổ trần", example: "The skylight makes the room brighter.", exampleVN: "Cửa sổ làm phòng sáng hơn." },
  { word: "cover page", meaning: "trang bìa", example: "On the cover page.", exampleVN: "Trên trang bìa." },
  { word: "attend", meaning: "tham dự", example: "Attend the conference.", exampleVN: "Tham dự sự kiện." },
  { word: "culinary", meaning: "thuộc về ẩm thực", example: "Culinary skills.", exampleVN: "Kĩ năng ẩm thực." },
  { word: "be noted for", meaning: "nổi tiếng về cái gì", example: "Noted for its scenery.", exampleVN: "Nổi tiếng phong cảnh." },
  { word: "apprenticeship", meaning: "sự học việc, chương trình thực tập", example: "Serving an apprenticeship.", exampleVN: "Thực hiện việc học nghề." },
  { word: "in good shape", meaning: "trong tình trạng tốt", example: "Is still in good shape.", exampleVN: "Vẫn trong tình trạng tốt." },
  { word: "imaginative", meaning: "giàu trí tưởng tượng", example: "Imaginative stories.", exampleVN: "Câu chuyện giàu tưởng tượng." },
  { word: "widespread", meaning: "phổ biến, rộng rãi", example: "Widespread attention.", exampleVN: "Chú ý rộng rãi." },
  { word: "insulated", meaning: "cách nhiệt/cách âm", example: "Insulated walls.", exampleVN: "Tường cách nhiệt." },
  { word: "magnificent", meaning: "lộng lẫy, tráng lệ", example: "Magnificent view.", exampleVN: "Cảnh lộng lẫy." },
  { word: "notably", meaning: "đáng kể, nhất là", example: "Notably a large garden.", exampleVN: "Nhất là khu vườn lớn." },
  { word: "geometric", meaning: "thuộc hình học", example: "Geometric patterns.", exampleVN: "Họa tiết hình học." },
  { word: "emissions", meaning: "khí thải", example: "Carbon emissions.", exampleVN: "Khí thải carbon." },
  { word: "suitcase", meaning: "cái vali", example: "Lifted a suitcase.", exampleVN: "Nâng cái vali." },
  { word: "counter", meaning: "quầy", example: "On the counter.", exampleVN: "Trên quầy." },
  { word: "dry cleaning", meaning: "giặt khô", example: "Needs dry cleaning.", exampleVN: "Cần giặt khô." },
  { word: "abroad", meaning: "ở nước ngoài", example: "Studying abroad.", exampleVN: "Du học ở nước ngoài." },
  { word: "seminar", meaning: "hội thảo", example: "The seminar begins.", exampleVN: "Buổi hội thảo bắt đầu." },
  { word: "notify", meaning: "thông báo", example: "Notify me of changes.", exampleVN: "Thông báo cho tôi." },
  { word: "orientation", meaning: "buổi định hướng", example: "The orientation starts.", exampleVN: "Buổi định hướng bắt đầu." },
  { word: "discuss", meaning: "thảo luận", example: "Let's discuss it.", exampleVN: "Hãy thảo luận." },
  { word: "inspiring", meaning: "truyền cảm hứng", example: "Inspiring speech.", exampleVN: "Lời phát biểu truyền cảm." },
  { word: "buffet", meaning: "tiệc buffet", example: "Buffet will be set up.", exampleVN: "Tiệc buffet được bày." },
  { word: "meeting minutes", meaning: "biên bản cuộc họp", example: "Take meeting minutes.", exampleVN: "Ghi biên bản." },
  { word: "assistant", meaning: "trợ lý", example: "Special assistant.", exampleVN: "Trợ lý đặc biệt." },
  { word: "competent", meaning: "có năng lực, giỏi chuyên môn", example: "Competent in his work.", exampleVN: "Có năng lực." },
  { word: "conference call", meaning: "cuộc họp trực tuyến", example: "Conference call.", exampleVN: "Họp trực tuyến." },
  { word: "borrow", meaning: "mượn", example: "Borrow a book.", exampleVN: "Mượn sách." },
  { word: "task", meaning: "nhiệm vụ, công việc", example: "Your task.", exampleVN: "Nhiệm vụ của bạn." },
  { word: "implement", meaning: "thực hiện, triển khai", example: "Implement a new policy.", exampleVN: "Thực hiện." },
  { word: "peer", meaning: "người cùng trang lứa, đồng nghiệp", example: "Respected by his peers.", exampleVN: "Đồng nghiệp kính trọng." },
  { word: "shadow", meaning: "đi theo quan sát", example: "Will shadow a senior staff.", exampleVN: "Quan sát học việc." },
  { word: "separate", meaning: "riêng biệt, tách rời", example: "Separate folders.", exampleVN: "Tài liệu tách biệt." },
  { word: "in the middle of", meaning: "ở giữa, đang dở dang", example: "In the middle of a meeting.", exampleVN: "Đang dở cuộc họp." },
  { word: "quarterly", meaning: "hàng quý", example: "Quarterly review.", exampleVN: "Đánh giá hàng quý." },
  { word: "shortly", meaning: "sớm, ngay sau đó", example: "Will be with you shortly.", exampleVN: "Sẽ đến sớm thôi." },
  { word: "have access to", meaning: "có quyền truy cập vào", example: "Have access to files.", exampleVN: "Có quyền." },
  { word: "agenda item", meaning: "mục trong chương trình họp", example: "Next agenda item.", exampleVN: "Mục nghị sự." },
  { word: "board", meaning: "ban giám đốc, hội đồng", example: "Board of directors.", exampleVN: "Hội đồng." },
  { word: "put together", meaning: "tổng hợp, chuẩn bị", example: "Putting together a presentation.", exampleVN: "Chuẩn bị báo cáo." },
  { word: "get to", meaning: "đi đến", example: "Get to work.", exampleVN: "Đi đến làm." },
  { word: "reminder", meaning: "lời nhắc nhở", example: "This email is a reminder.", exampleVN: "Email nhắc nhở." }
];

export function processChunk18(): Word[] {
  return chunk18_raw.map((w, index) => {
    return {
      ...w,
      id: `c18_${index}`,
      pos: '(n/a)'
    };
  });
}
