import { Word } from './types';

export const chunk2: Word[] = [
  { id: '151', word: 'access', meaning: 'truy cập', example: 'Access the database.', exampleVN: 'Truy cập vào cơ sở dữ liệu.' },
  { id: '152', word: 'accommodate', meaning: 'đáp ứng', example: 'Accommodate your needs.', exampleVN: 'Đáp ứng nhu cầu của bạn.' },
  { id: '153', word: 'account', meaning: 'tài khoản', example: 'Bank account.', exampleVN: 'Tài khoản ngân hàng.' },
  { id: '154', word: 'accumulate', meaning: 'tích lũy', example: 'Accumulate experience.', exampleVN: 'Tích lũy kinh nghiệm.' },
  { id: '155', word: 'accurate', meaning: 'chính xác', example: 'Accurate data.', exampleVN: 'Dữ liệu chính xác.' },
  { id: '156', word: 'accustom', meaning: 'làm quen', example: 'Accustom to the rules.', exampleVN: 'Làm quen với các quy tắc.' },
  { id: '157', word: 'acknowledge', meaning: 'công nhận', example: 'Acknowledge his effort.', exampleVN: 'Ghi nhận nỗ lực của anh ấy.' },
  { id: '158', word: 'active', meaning: 'chủ động', example: 'Active participation.', exampleVN: 'Tham gia tích cực.' },
  { id: '159', word: 'actual', meaning: 'thực tế', example: 'Actual cost.', exampleVN: 'Chi phí thực tế.' },
  { id: '160', word: 'adapt', meaning: 'thích nghi', example: 'Adapt to the environment.', exampleVN: 'Thích nghi với môi trường.' },
  { id: '161', word: 'additional', meaning: 'bổ sung', example: 'Additional information.', exampleVN: 'Thêm thông tin.' },
  { id: '162', word: 'adequate', meaning: 'đầy đủ', example: 'Adequate resources.', exampleVN: 'Có đủ nguồn lực.' },
  { id: '163', word: 'administer', meaning: 'quản lý', example: 'Administer the tests.', exampleVN: 'Quản lý các bài kiểm tra.' },
  { id: '164', word: 'admit', meaning: 'thú nhận', example: 'Admit the mistake.', exampleVN: 'Thừa nhận sai lầm.' },
  { id: '165', word: 'advantage', meaning: 'lợi thế', example: 'A competitive advantage.', exampleVN: 'Họ thảo luận về lợi thế cạnh tranh.' },
  { id: '166', word: 'advertise', meaning: 'quảng cáo', example: 'Advertise the product.', exampleVN: 'Quảng cáo sản phẩm.' },
  { id: '167', word: 'advice', meaning: 'lời khuyên', example: 'Good advice.', exampleVN: 'Lời khuyên tốt.' },
  { id: '168', word: 'advise', meaning: 'khuyên bảo', example: 'Advise him to stop.', exampleVN: 'Khuyên anh ấy dừng lại.' },
  { id: '169', word: 'affect', meaning: 'ảnh hưởng', example: 'Affect the outcome.', exampleVN: 'Tác động đến kết quả.' },
  { id: '170', word: 'afford', meaning: 'đủ khả năng', example: 'Afford to buy.', exampleVN: 'Có đủ khả năng để mua.' },
  { id: '171', word: 'agency', meaning: 'đại lý', example: 'Travel agency.', exampleVN: 'Công ty du lịch.' },
  { id: '172', word: 'agenda', meaning: 'chương trình nghị sự', example: 'Meeting agenda.', exampleVN: 'Chương trình họp.' },
  { id: '173', word: 'agree', meaning: 'đồng ý', example: 'Agree with you.', exampleVN: 'đồng ý với bạn.' },
  { id: '174', word: 'aim', meaning: 'mục đích', example: 'Aim for success.', exampleVN: 'Hướng tới sự thành công.' },
  { id: '175', word: 'allow', meaning: 'cho phép', example: 'Allow to enter.', exampleVN: 'Cho phép vào.' },
  { id: '176', word: 'alternative', meaning: 'thay thế', example: 'Alternative plan.', exampleVN: 'Có kế hoạch thay thế.' },
  { id: '177', word: 'amount', meaning: 'số lượng', example: 'A large amount.', exampleVN: 'Họ đã thảo luận rất nhiều.' },
  { id: '178', word: 'analyze', meaning: 'phân tích', example: 'Analyze the data.', exampleVN: 'Phân tích dữ liệu.' },
  { id: '179', word: 'annual', meaning: 'hàng năm', example: 'Annual report.', exampleVN: 'Báo cáo hàng năm.' },
  { id: '180', word: 'anticipate', meaning: 'dự kiến', example: 'Anticipate the problem.', exampleVN: 'Lường trước vấn đề.' },
  { id: '181', word: 'apologize', meaning: 'xin lỗi', example: 'Apologize for the delay.', exampleVN: 'xin lỗi vì sự chậm trễ.' },
  { id: '182', word: 'apparent', meaning: 'rõ ràng', example: 'Apparent reason.', exampleVN: 'Làm rõ lý do.' },
  { id: '183', word: 'appeal', meaning: 'kêu gọi', example: 'Appeal for help.', exampleVN: 'Kêu gọi sự giúp đỡ.' },
  { id: '184', word: 'appear', meaning: 'xuất hiện', example: 'Appear on TV.', exampleVN: 'Xuất hiện trên truyền hình.' },
  { id: '185', word: 'apply', meaning: 'áp dụng', example: 'Apply for a job.', exampleVN: 'nộp đơn xin việc.' },
  { id: '186', word: 'appraise', meaning: 'đánh giá', example: 'Appraise the property.', exampleVN: 'Định giá tài sản.' },
  { id: '187', word: 'appreciate', meaning: 'trân trọng', example: 'Appreciate your help.', exampleVN: 'Đánh giá cao sự giúp đỡ của bạn.' },
  { id: '188', word: 'approach', meaning: 'phương pháp', example: 'A new approach.', exampleVN: 'Một cách tiếp cận mới.' },
  { id: '189', word: 'appropriate', meaning: 'thích hợp', example: 'Appropriate clothes.', exampleVN: 'Mặc quần áo phù hợp.' },
  { id: '190', word: 'approval', meaning: 'sự chấp thuận', example: 'Need your approval.', exampleVN: 'Cần sự chấp thuận của bạn.' },
  { id: '191', word: 'approximate', meaning: 'xấp xỉ', example: 'Approximate number.', exampleVN: 'Ước tính số lượng.' },
  { id: '192', word: 'argue', meaning: 'tranh luận', example: 'Argue about it.', exampleVN: 'Tranh luận về nó.' },
  { id: '193', word: 'arise', meaning: 'nảy sinh', example: 'Problems may arise.', exampleVN: 'Những vấn đề có thể phát sinh.' },
  { id: '194', word: 'arrive', meaning: 'đến nơi', example: 'Arrive at the station.', exampleVN: 'Đến nhà ga.' },
  { id: '195', word: 'article', meaning: 'bài báo', example: 'Read the article.', exampleVN: 'Đọc bài viết.' },
  { id: '196', word: 'aspect', meaning: 'khía cạnh', example: 'Every aspect of life.', exampleVN: 'Mọi khía cạnh của cuộc sống.' },
  { id: '197', word: 'associate', meaning: 'liên kết', example: 'Associate with them.', exampleVN: 'Liên kết với họ.' },
  { id: '198', word: 'assume', meaning: 'giả sử', example: 'Assume it is true.', exampleVN: 'Cho rằng đó là sự thật.' },
  { id: '199', word: 'assure', meaning: 'đảm bảo', example: 'Assure the quality.', exampleVN: 'Đảm bảo chất lượng.' },
  { id: '200', word: 'attempt', meaning: 'cố gắng', example: 'Make an attempt.', exampleVN: 'Cố gắng.' },
  { id: '201', word: 'attention', meaning: 'sự chú ý', example: 'Pay attention.', exampleVN: 'Chú ý.' },
  { id: '202', word: 'attitude', meaning: 'thái độ', example: 'Positive attitude.', exampleVN: 'Thái độ tích cực.' },
  { id: '203', word: 'attribute', meaning: 'đặc tính', example: 'A positive attribute.', exampleVN: 'Một thuộc tính tích cực.' },
  { id: '204', word: 'audience', meaning: 'khán giả', example: 'Large audience.', exampleVN: 'Lượng lớn khán giả.' },
  { id: '205', word: 'author', meaning: 'tác giả', example: 'The author of the book.', exampleVN: 'Họ thảo luận về tác giả của cuốn sách.' },
  { id: '206', word: 'authority', meaning: 'quyền lực', example: 'Have the authority.', exampleVN: 'Có được thẩm quyền.' },
  { id: '207', word: 'authorize', meaning: 'ủy quyền', example: 'Authorize the payment.', exampleVN: 'Ủy quyền thanh toán.' },
  { id: '208', word: 'available', meaning: 'có sẵn', example: 'Available now.', exampleVN: 'Có sẵn ngay bây giờ.' },
  { id: '209', word: 'average', meaning: 'trung bình', example: 'Average temperature.', exampleVN: 'Nhiệt độ trung bình.' },
  { id: '210', word: 'avoid', meaning: 'tránh', example: 'Avoid mistakes.', exampleVN: 'Tránh những sai lầm.' },
  { id: '211', word: 'award', meaning: 'phần thưởng', example: 'Win an award.', exampleVN: 'Giành được một giải thưởng.' },
  { id: '212', word: 'aware', meaning: 'nhận thức', example: 'Be aware of risks.', exampleVN: 'Nhận thức được những rủi ro.' },
  { id: '213', word: 'background', meaning: 'bối cảnh', example: 'Background check.', exampleVN: 'Kiểm tra lý lịch.' },
  { id: '214', word: 'balance', meaning: 'cân bằng', example: 'Balance the budget.', exampleVN: 'Cân bằng ngân sách.' },
  { id: '215', word: 'ban', meaning: 'lệnh cấm', example: 'Ban smoking.', exampleVN: 'Cấm hút thuốc.' },
  { id: '216', word: 'basic', meaning: 'cơ bản', example: 'Basic skills.', exampleVN: 'Những kỹ năng cơ bản.' },
  { id: '217', word: 'basis', meaning: 'cơ sở', example: 'On a daily basis.', exampleVN: 'Hàng ngày.' },
  { id: '218', word: 'bear', meaning: 'chịu đựng', example: 'Bear the cost.', exampleVN: 'Chịu chi phí.' },
  { id: '219', word: 'bill', meaning: 'hóa đơn', example: 'Pay the bill.', exampleVN: 'Thanh toán hóa đơn.' },
  { id: '220', word: 'blame', meaning: 'đổ lỗi', example: 'Blame someone else.', exampleVN: 'Đổ lỗi cho người khác.' },
  { id: '221', word: 'board', meaning: 'ban giám đốc', example: 'Board of directors.', exampleVN: 'Có ban giám đốc.' },
  { id: '222', word: 'boost', meaning: 'thúc đẩy', example: 'Boost sales.', exampleVN: 'Tăng doanh số bán hàng.' },
  { id: '223', word: 'borrow', meaning: 'mượn', example: 'Borrow money.', exampleVN: 'Vay tiền.' },
  { id: '224', word: 'bound', meaning: 'chắc chắn', example: 'Bound to happen.', exampleVN: 'Chắc chắn xảy ra.' },
  { id: '225', word: 'branch', meaning: 'chi nhánh', example: 'A local branch.', exampleVN: 'Họ thảo luận về một chi nhánh địa phương.' },
  { id: '226', word: 'brand', meaning: 'thương hiệu', example: 'Popular brand.', exampleVN: 'Thương hiệu phổ biến.' },
  { id: '227', word: 'brief', meaning: 'ngắn gọn', example: 'Brief introduction.', exampleVN: 'Giới thiệu ngắn gọn.' },
  { id: '228', word: 'broad', meaning: 'rộng', example: 'Broad range.', exampleVN: 'Có phạm vi rộng.' },
  { id: '229', word: 'build', meaning: 'xây dựng', example: 'Build a house.', exampleVN: 'Xây một ngôi nhà.' },
  { id: '230', word: 'bulletin', meaning: 'bản tin', example: 'News bulletin.', exampleVN: 'Bản tin thời sự.' },
  { id: '231', word: 'burden', meaning: 'gánh nặng', example: 'A heavy burden.', exampleVN: 'Họ thảo luận về một gánh nặng lớn.' },
  { id: '232', word: 'business', meaning: 'kinh doanh', example: 'Doing business.', exampleVN: 'Kinh doanh.' },
  { id: '233', word: 'calculate', meaning: 'tính toán', example: 'Calculate the total.', exampleVN: 'Tính tổng.' },
  { id: '234', word: 'campaign', meaning: 'chiến dịch', example: 'Marketing campaign.', exampleVN: 'Chiến dịch tiếp thị.' },
  { id: '235', word: 'capable', meaning: 'có khả năng', example: 'Capable of doing.', exampleVN: 'Có khả năng làm được.' },
  { id: '236', word: 'capture', meaning: 'chụp, bắt', example: 'Capture the moment.', exampleVN: 'Nắm bắt khoảnh khắc.' },
  { id: '237', word: 'careful', meaning: 'cẩn thận', example: 'Be careful.', exampleVN: 'Cẩn thận.' },
  { id: '238', word: 'carry', meaning: 'mang', example: 'Carry the bag.', exampleVN: 'Mang theo cái túi.' },
  { id: '239', word: 'case', meaning: 'trường hợp', example: 'In any case.', exampleVN: 'Trong mọi trường hợp.' },
  { id: '240', word: 'cash', meaning: 'tiền mặt', example: 'Pay in cash.', exampleVN: 'Thanh toán bằng tiền mặt.' },
  { id: '241', word: 'catalog', meaning: 'danh mục', example: 'Product catalog.', exampleVN: 'Danh mục sản phẩm.' },
  { id: '242', word: 'catch', meaning: 'bắt kịp', example: 'Catch the train.', exampleVN: 'Bắt tàu.' },
  { id: '243', word: 'cause', meaning: 'nguyên nhân', example: 'Cause of the fire.', exampleVN: 'Gây ra vụ cháy.' },
  { id: '244', word: 'cease', meaning: 'ngừng', example: 'Cease fire.', exampleVN: 'Ngừng bắn.' },
  { id: '245', word: 'celebrate', meaning: 'kỷ niệm', example: 'Celebrate birthday.', exampleVN: 'Tổ chức sinh nhật.' },
  { id: '246', word: 'central', meaning: 'trung tâm', example: 'Central office.', exampleVN: 'Đến văn phòng trung tâm.' },
  { id: '247', word: 'certificate', meaning: 'chứng chỉ', example: 'Gift certificate.', exampleVN: 'Phiếu quà tặng.' },
  { id: '248', word: 'chain', meaning: 'chuỗi', example: 'Chain of events.', exampleVN: 'Xâu chuỗi các sự kiện.' },
  { id: '249', word: 'chair', meaning: 'chủ tọa', example: 'Chair the meeting.', exampleVN: 'Chủ trì cuộc họp.' },
  { id: '250', word: 'challenge', meaning: 'thử thách', example: 'Face the challenge.', exampleVN: 'Đối mặt với thử thách.' },
  { id: '251', word: 'chance', meaning: 'cơ hội', example: 'Take a chance.', exampleVN: 'Nắm bắt cơ hội.' },
  { id: '252', word: 'change', meaning: 'thay đổi', example: 'Change your mind.', exampleVN: 'Thay đổi suy nghĩ của bạn.' },
  { id: '253', word: 'channel', meaning: 'kênh', example: 'News channel.', exampleVN: 'Kênh tin tức.' },
  { id: '254', word: 'characteristic', meaning: 'đặc điểm', example: 'Main characteristic.', exampleVN: 'Đặc điểm chính.' },
  { id: '255', word: 'chart', meaning: 'biểu đồ', example: 'Pie chart.', exampleVN: 'Biểu đồ hình tròn.' },
  { id: '256', word: 'chase', meaning: 'theo đuổi', example: 'Chase the dream.', exampleVN: 'Theo đuổi giấc mơ.' },
  { id: '257', word: 'cheap', meaning: 'rẻ', example: 'Cheap price.', exampleVN: 'Giá rẻ.' },
  { id: '258', word: 'check', meaning: 'kiểm tra', example: 'Check the details.', exampleVN: 'Kiểm tra chi tiết.' },
  { id: '259', word: 'choice', meaning: 'sự lựa chọn', example: 'Make a choice.', exampleVN: 'Đưa ra lựa chọn.' },
  { id: '260', word: 'choose', meaning: 'chọn', example: 'Choose one.', exampleVN: 'Chọn một.' },
  { id: '261', word: 'circumstance', meaning: 'hoàn cảnh', example: 'Under no circumstance.', exampleVN: 'Không có trường hợp.' },
  { id: '262', word: 'claim', meaning: 'yêu cầu', example: 'Claim your prize.', exampleVN: 'Nhận giải thưởng của bạn.' },
  { id: '263', word: 'clear', meaning: 'rõ ràng', example: 'Crystal clear.', exampleVN: 'Sự rõ ràng như pha lê.' },
  { id: '264', word: 'clerk', meaning: 'nhân viên', example: 'Bank clerk.', exampleVN: 'Nhân viên ngân hàng.' },
  { id: '265', word: 'client', meaning: 'khách hàng', example: 'New client.', exampleVN: 'Khách hàng mới.' },
  { id: '266', word: 'climate', meaning: 'khí hậu', example: 'Good climate.', exampleVN: 'Khí hậu tốt.' },
  { id: '267', word: 'climb', meaning: 'leo lên', example: 'Climb the ladder.', exampleVN: 'Leo lên thang.' },
  { id: '268', word: 'close', meaning: 'đóng', example: 'Close the door.', exampleVN: 'Đóng cửa lại.' },
  { id: '269', word: 'collect', meaning: 'thu thập', example: 'Collect data.', exampleVN: 'Thu thập dữ liệu.' },
  { id: '270', word: 'come', meaning: 'đến', example: 'Come here.', exampleVN: 'Đến đây.' },
  { id: '271', word: 'comfort', meaning: 'sự thoải mái', example: 'In comfort.', exampleVN: 'Thoải mái.' },
  { id: '272', word: 'command', meaning: 'ra lệnh', example: 'Command the army.', exampleVN: 'Chỉ huy quân đội.' },
  { id: '273', word: 'comment', meaning: 'bình luận', example: 'No comment.', exampleVN: 'Không bình luận.' },
  { id: '274', word: 'commerce', meaning: 'thương mại', example: 'E-commerce.', exampleVN: 'Thương mại điện tử.' },
  { id: '275', word: 'commission', meaning: 'tiền hoa hồng', example: 'Sales commission.', exampleVN: 'Hoa hồng bán hàng.' },
  { id: '276', word: 'commit', meaning: 'cam kết', example: 'Commit to the project.', exampleVN: 'Cam kết với dự án.' },
  { id: '277', word: 'committee', meaning: 'ủy ban', example: 'Committee members.', exampleVN: 'Các thành viên ủy ban.' },
  { id: '278', word: 'common', meaning: 'phổ biến', example: 'Common sense.', exampleVN: 'Có ý thức chung.' },
  { id: '279', word: 'communicate', meaning: 'giao tiếp', example: 'Communicate well.', exampleVN: 'Giao tiếp tốt.' },
  { id: '280', word: 'community', meaning: 'cộng đồng', example: 'Local community.', exampleVN: 'Cộng đồng địa phương.' },
  { id: '281', word: 'company', meaning: 'công ty', example: 'Our company.', exampleVN: 'Họ thảo luận về công ty của chúng tôi.' },
  { id: '282', word: 'compare', meaning: 'so sánh', example: 'Compare prices.', exampleVN: 'So sánh giá cả.' },
  { id: '283', word: 'competition', meaning: 'cuộc thi', example: 'Winning competition.', exampleVN: 'Giành chiến thắng trong cuộc cạnh tranh.' },
  { id: '284', word: 'competitive', meaning: 'có tính cạnh tranh', example: 'Competitive advantage.', exampleVN: 'Có lợi thế cạnh tranh.' },
  { id: '285', word: 'complaint', meaning: 'lời phàn nàn', example: 'Make a complaint.', exampleVN: 'Khiếu nại.' },
  { id: '286', word: 'complex', meaning: 'phức tạp', example: 'Complex problem.', exampleVN: 'Giải quyết vấn đề phức tạp.' },
  { id: '287', word: 'component', meaning: 'thành phần', example: 'Key component.', exampleVN: 'Thành phần chính.' },
  { id: '288', word: 'comprise', meaning: 'bao gồm', example: 'Comprise of 3 parts.', exampleVN: 'Bao gồm 3 phần.' },
  { id: '289', word: 'computer', meaning: 'máy tính', example: 'Personal computer.', exampleVN: 'Máy tính cá nhân.' },
  { id: '290', word: 'concept', meaning: 'khái niệm', example: 'Basic concept.', exampleVN: 'Khái niệm cơ bản.' },
  { id: '291', word: 'concern', meaning: 'mối quan tâm', example: 'Main concern.', exampleVN: 'Mối quan tâm chính.' },
  { id: '292', word: 'condition', meaning: 'điều kiện', example: 'Good condition.', exampleVN: 'Tình trạng tốt.' },
  { id: '293', word: 'conference', meaning: 'hội nghị', example: 'Press conference.', exampleVN: 'Buổi họp báo.' },
  { id: '294', word: 'confidence', meaning: 'sự tự tin', example: 'Have confidence.', exampleVN: 'Có được sự tự tin.' },
  { id: '295', word: 'conflict', meaning: 'xung đột', example: 'Resolve conflict.', exampleVN: 'Giải quyết xung đột.' },
  { id: '296', word: 'confuse', meaning: 'làm bối rối', example: 'Confuse the issue.', exampleVN: 'Nhầm lẫn vấn đề.' },
  { id: '297', word: 'connection', meaning: 'sự liên kết', example: 'Bad connection.', exampleVN: 'Kết nối kém.' },
  { id: '298', word: 'consequence', meaning: 'hậu quả', example: 'Face the consequence.', exampleVN: 'Đối mặt với hậu quả.' },
  { id: '299', word: 'consider', meaning: 'xem xét', example: 'Consider all options.', exampleVN: 'Xem xét tất cả các lựa chọn.' },
  { id: '300', word: 'consistent', meaning: 'nhất quán', example: 'Consistent quality.', exampleVN: 'Chất lượng nhất quán.' }
];

export const processChunk2 = () => {
    return chunk2.map(w => {
      let pos = '(v)';
      const nouns = new Set(['account', 'advantage', 'advice', 'agency', 'agenda', 'amount', 'approval', 'article', 'aspect', 'attention', 'attitude', 'attribute', 'audience', 'author', 'authority', 'award', 'background', 'balance', 'basis', 'bill', 'board', 'branch', 'brand', 'bulletin', 'burden', 'business', 'campaign', 'candidate', 'capacity', 'capital', 'career', 'case', 'cash', 'catalog', 'category', 'cause', 'certificate', 'chain', 'challenge', 'chance', 'change', 'channel', 'characteristic', 'chart', 'choice', 'circumstance', 'clerk', 'client', 'climate', 'colleague', 'comfort', 'command', 'comment', 'commerce', 'commission', 'committee', 'community', 'company', 'competition', 'complaint', 'component', 'computer', 'concept', 'concern', 'condition', 'conference', 'confidence', 'conflict', 'connection', 'consequence']);
      const adjs = new Set(['accurate', 'active', 'actual', 'additional', 'adequate', 'alternative', 'annual', 'apparent', 'appropriate', 'approximate', 'available', 'average', 'aware', 'basic', 'brief', 'broad', 'capable', 'careful', 'central', 'cheap', 'clear', 'common', 'competitive', 'complex', 'consistent']);
      const both = new Set(['access', 'aim', 'appeal', 'approach', 'audit', 'ban', 'benefit', 'blame', 'boost', 'budget', 'capture', 'care', 'cash', 'catch', 'charge', 'chase', 'check', 'claim', 'climb', 'close', 'collect', 'compare', 'compromise']);
      if (nouns.has(w.word)) pos = '(n)';
      else if (adjs.has(w.word)) pos = '(adj)';
      else if (both.has(w.word)) pos = '(n, v)';
      return { ...w, pos };
    });
};
